In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('/content/drive/MyDrive/XAU_1m_data.csv')
data.rename(columns={
    'Datetime': 'Date',
    'Open': 'open',
    'Close': 'close',
    'Low': 'low',
    'High': 'high',
    'Volume': 'volume'
}, inplace=True)

data['Ticker'] = 'XAUUSD'

data

,Unnamed: 0,Date,open,high,low,close,volume,Ticker
0,0,2004-06-11 07:18:00,384.00,384.10,384.00,384.00,3,XAUUSD
1,1,2004-06-11 07:23:00,384.10,384.10,384.00,384.00,2,XAUUSD
2,2,2004-06-11 07:24:00,383.80,383.80,383.80,383.80,1,XAUUSD
3,3,2004-06-11 07:25:00,383.80,384.30,383.80,384.30,3,XAUUSD
4,4,2004-06-11 07:27:00,383.80,383.80,383.80,383.80,1,XAUUSD
...,...,...,...,...,...,...,...,...
6559231,6559231,2025-04-25 14:33:00,3299.53,3299.59,3298.34,3298.35,277,XAUUSD
6559232,6559232,2025-04-25 14:34:00,3298.36,3298.88,3298.07,3298.62,327,XAUUSD
6559233,6559233,2025-04-25 14:35:00,3298.61,3298.61,3296.77,3296.81,461,XAUUSD
6559234,6559234,2025-04-25 14:36:00,3296.82,3297.27,3296.40,3296.40,385,XAUUSD
6559235,6559235,2025-04-25 14:37:00,3296.41,3296.91,3296.35,3296.91,60,XAUUSD

In [4]:
data['Ticker'].unique()

array(['XAUUSD'], dtype=object)

In [5]:
# Convert 'Date' column to datetime if it isn't already
data['Date'] = pd.to_datetime(data['Date'])

# Define the date range
start_date = '2020-01-01'
end_date = '2025-12-31'

# Define the tickers you want to filter
selected_tickers = ['XAUUSD']  # Add tickers you want

# Apply filtering
data = data[
    (data["Date"] >= start_date) &
    (data["Date"] <= end_date) &
    (data["Ticker"].isin(selected_tickers))
]

# Display filtered results
data

,Unnamed: 0,Date,open,high,low,close,volume,Ticker
4685138,4685138,2020-01-02 06:00:00,1520.26,1520.30,1520.21,1520.26,15,XAUUSD
4685139,4685139,2020-01-02 06:01:00,1520.26,1520.36,1520.26,1520.30,12,XAUUSD
4685140,4685140,2020-01-02 06:02:00,1520.31,1520.31,1520.21,1520.21,11,XAUUSD
4685141,4685141,2020-01-02 06:03:00,1520.21,1520.26,1520.16,1520.26,14,XAUUSD
4685142,4685142,2020-01-02 06:04:00,1520.26,1520.28,1520.24,1520.26,8,XAUUSD
...,...,...,...,...,...,...,...,...
6559231,6559231,2025-04-25 14:33:00,3299.53,3299.59,3298.34,3298.35,277,XAUUSD
6559232,6559232,2025-04-25 14:34:00,3298.36,3298.88,3298.07,3298.62,327,XAUUSD
6559233,6559233,2025-04-25 14:35:00,3298.61,3298.61,3296.77,3296.81,461,XAUUSD
6559234,6559234,2025-04-25 14:36:00,3296.82,3297.27,3296.40,3296.40,385,XAUUSD
6559235,6559235,2025-04-25 14:37:00,3296.41,3296.91,3296.35,3296.91,60,XAUUSD

In [6]:
import pandas as pd

# Ensure Date is datetime
data['Date'] = pd.to_datetime(data['Date'])

# Custom resampling function with offset
def resample_1hr_custom(group):
    ticker = group['Ticker'].iloc[0]
    group = group.set_index('Date')
    resampled = group.resample('15min').agg({
        'open': 'first',
        'high': 'max',
        'low': 'min',
        'close': 'last',
        'volume': 'sum'
    }).dropna().reset_index()
    resampled['Ticker'] = ticker
    return resampled

# Apply per ticker
data_1hr = data.groupby('Ticker').apply(resample_1hr_custom).reset_index(drop=True)

# Reorder columns
data_1hr = data_1hr[['Ticker', 'Date', 'open', 'high', 'low', 'close', 'volume']]

data = data_1hr
data

<ipython-input-6-1792869645>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Date'] = pd.to_datetime(data['Date'])
<ipython-input-6-1792869645>:21: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  data_1hr = data.groupby('Ticker').apply(resample_1hr_custom).reset_index(drop=True)

        Ticker                Date     open     high      low    close  volume
0       XAUUSD 2020-01-02 06:00:00  1520.26  1520.36  1519.90  1519.90     149
1       XAUUSD 2020-01-02 06:15:00  1519.90  1520.08  1519.77  1519.81     159
2       XAUUSD 2020-01-02 06:30:00  1519.81  1520.03  1519.71  1519.85     239
3       XAUUSD 2020-01-02 06:45:00  1519.85  1520.05  1519.39  1519.39     209
4       XAUUSD 2020-01-02 07:00:00  1519.37  1519.41  1518.95  1519.26     276
...        ...                 ...      ...      ...      ...      ...     ...
125512  XAUUSD 2025-04-25 13:30:00  3304.87  3306.35  3301.22  3303.57    9223
125513  XAUUSD 2025-04-25 13:45:00  3303.54  3303.59  3297.83  3297.98    7832
125514  XAUUSD 2025-04-25 14:00:00  3297.96  3300.93  3296.95  3298.44    6001
125515  XAUUSD 2025-04-25 14:15:00  3298.45  3299.09  3294.35  3298.63    7979
125516  XAUUSD 2025-04-25 14:30:00  3298.64  3299.59  3296.35  3296.91    2579

[125517 rows x 7 columns]

In [7]:
data.dropna()
data

        Ticker                Date     open     high      low    close  volume
0       XAUUSD 2020-01-02 06:00:00  1520.26  1520.36  1519.90  1519.90     149
1       XAUUSD 2020-01-02 06:15:00  1519.90  1520.08  1519.77  1519.81     159
2       XAUUSD 2020-01-02 06:30:00  1519.81  1520.03  1519.71  1519.85     239
3       XAUUSD 2020-01-02 06:45:00  1519.85  1520.05  1519.39  1519.39     209
4       XAUUSD 2020-01-02 07:00:00  1519.37  1519.41  1518.95  1519.26     276
...        ...                 ...      ...      ...      ...      ...     ...
125512  XAUUSD 2025-04-25 13:30:00  3304.87  3306.35  3301.22  3303.57    9223
125513  XAUUSD 2025-04-25 13:45:00  3303.54  3303.59  3297.83  3297.98    7832
125514  XAUUSD 2025-04-25 14:00:00  3297.96  3300.93  3296.95  3298.44    6001
125515  XAUUSD 2025-04-25 14:15:00  3298.45  3299.09  3294.35  3298.63    7979
125516  XAUUSD 2025-04-25 14:30:00  3298.64  3299.59  3296.35  3296.91    2579

[125517 rows x 7 columns]

In [8]:
data.columns

Index(['Ticker', 'Date', 'open', 'high', 'low', 'close', 'volume'], dtype='object')

In [12]:
import pandas as pd
import numpy as np
from tqdm import tqdm
from joblib import Parallel, delayed

# === Normalized JMA + Signal in One Function ===
def compute_jma_indicator(
    df,
    smooth_length=10,
    norm_period=90,
    upper_thresh=2,
    lower_thresh=-2.5,
    rs_period=10,
    rs_percentile=10
):
    # === JMA Calculation ===
    price_series = df['close']
    alpha = 2.0 / (smooth_length + 1)
    jma = [price_series.iloc[0]]
    for price in price_series.iloc[1:]:
        jma.append(jma[-1] + (price - jma[-1]) * alpha)
    jma_series = pd.Series(jma, index=price_series.index)

    # === Normalization ===
    mean = jma_series.rolling(window=norm_period).mean()
    std = jma_series.rolling(window=norm_period).std()
    normalized_jma = (jma_series - mean) / std

    # === Rogers-Satchell Volatility ===
    # Replace 0s to avoid log(0)
    open_, high, low, close = df['open'].replace(0, np.nan), df['high'], df['low'], df['close'].replace(0, np.nan)
    log_hc = np.log(high / close)
    log_ho = np.log(high / open_)
    log_lc = np.log(low / close)
    log_lo = np.log(low / open_)
    rs_vol = (log_hc * log_ho + log_lc * log_lo).rolling(window=rs_period).mean()

    # === RS Volatility Filter ===
    rs_thresh = rs_vol.rolling(window=norm_period).quantile(rs_percentile / 100.0)

    # === Generate Signals ===
    long_condition = (normalized_jma > upper_thresh) & (rs_vol > rs_thresh)
    short_condition = (normalized_jma < lower_thresh) & (rs_vol > rs_thresh)
    signal = pd.Series(0, index=df.index)
    signal[long_condition] = 1
    signal[short_condition] = 2

    # === Output ===
    df['jma'] = jma_series
    df['normalized_jma'] = normalized_jma
    df['rs_vol'] = rs_vol
    df['rs_thresh'] = rs_thresh
    df['Signal'] = signal

    return df

# === Per-Ticker Trade Processor ===
def process_ticker(ticker, ticker_data, initial_capital, fee, slippage, tp_pct, sl_pct):
    open_positions = {}
    trades = []
    cumulative_pnl = 0

    for row in ticker_data:
        timestamp, close, open_price, high, low, signal = row["date"], row["close"], row["open"], row["high"], row["low"], row["Signal"]

        if ticker in open_positions:
            position = open_positions[ticker]
            entry_price, direction, qty = position["entry_price"], position["direction"], position["qty"]
            exit_price, exit_reason = None, None

            tp_price = entry_price * (1 + tp_pct) if direction == "long" else entry_price * (1 - tp_pct)
            sl_price = entry_price * (1 - sl_pct) if direction == "long" else entry_price * (1 + sl_pct)

            if (direction == "long" and high >= tp_price) or (direction == "short" and low <= tp_price):
                exit_price = tp_price
                exit_reason = "Take Profit"
            elif (direction == "long" and low <= sl_price) or (direction == "short" and high >= sl_price):
                exit_price = sl_price
                exit_reason = "Stop Loss"

            if exit_price is not None:
                exit_price *= (1 - slippage) if direction == "long" else (1 + slippage)
                raw_pnl = (exit_price - entry_price) * qty if direction == "long" else (entry_price - exit_price) * qty
                pnl = raw_pnl - (fee * entry_price * qty) - (fee * exit_price * qty)
                cumulative_pnl += pnl

                trades.append([ticker, position["entry_time"], timestamp, entry_price, exit_price, pnl, exit_reason, cumulative_pnl, direction])
                del open_positions[ticker]
                continue

        if ticker not in open_positions:
            if signal == 1:
                direction = "long"
            elif signal == 2:
                direction = "short"
            else:
                continue

            entry_price = open_price * (1 + slippage) if direction == "long" else open_price * (1 - slippage)
            qty = initial_capital / entry_price
            open_positions[ticker] = {"entry_time": timestamp, "entry_price": entry_price, "direction": direction, "qty": qty}

    return trades

# === Backtest Function ===
def backtest_trades(data, tp_pct, sl_pct):
    initial_capital = 100000
    fee = 0.0004
    slippage = 0.0005

    unique_tickers = data['Ticker'].unique()

    dtype = [
        ("Ticker", "U10"), ("date", "M8[ms]"), ("close", "f8"),
        ("open", "f8"), ("high", "f8"), ("low", "f8"), ("Signal", "i4")
    ]

    data_np = np.array(
        list(data[["Ticker", "Date", "close", "open", "high", "low", "Signal"]]
             .itertuples(index=False, name=None)),
        dtype=dtype
    )

    results = Parallel(n_jobs=-1)(
        delayed(process_ticker)(
            ticker,
            data_np[data_np['Ticker'] == ticker],
            initial_capital,
            fee,
            slippage,
            tp_pct,
            sl_pct
        ) for ticker in tqdm(unique_tickers)
    )

    trades = [trade for result in results for trade in result]
    return pd.DataFrame(trades, columns=[
        "Ticker", "Entry Time", "Exit Time", "Entry Price", "Exit Price", "PnL", "Exit Reason", "Cumulative PnL", "Direction"
    ])

# === Main Execution ===
# Make sure your 'data' DataFrame exists and has columns: Ticker, Date, close, open, high, low
data['Date'] = pd.to_datetime(data['Date'])

# Compute normalized JMA and generate signals
data = data.groupby('Ticker', group_keys=False).apply(compute_jma_indicator)

# Shift Signal for next-bar execution
data['Signal'] = data.groupby('Ticker')['Signal'].shift(1)
data = data.dropna(subset=['Signal'])
data['Signal'] = data['Signal'].astype(int)

# Run backtest
tradebook = backtest_trades(data, tp_pct=0.1, sl_pct=0.02)

# Save tradebook
tradebook.to_csv("/content/drive/MyDrive/tradebook_Gold.csv", index=False)
tradebook

<ipython-input-12-2712610951>:146: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  data = data.groupby('Ticker', group_keys=False).apply(compute_jma_indicator)
100%|██████████| 1/1 [00:00<00:00, 124.94it/s]

,Ticker,Entry Time,Exit Time,Entry Price,Exit Price,PnL,Exit Reason,Cumulative PnL,Direction
0,XAUUSD,2020-01-03 08:15:00,2020-03-09 01:00:00,1542.560895,1695.968576,9861.0220,Take Profit,9861.0220,long
1,XAUUSD,2020-03-09 02:00:00,2020-03-09 06:15:00,1700.970060,1666.117183,-2128.1804,Stop Loss,7732.8416,long
2,XAUUSD,2020-03-10 07:30:00,2020-03-16 12:45:00,1655.421875,1490.624627,9878.9820,Take Profit,17611.8236,short
3,XAUUSD,2020-03-16 14:15:00,2020-03-16 17:00:00,1470.314475,1500.470625,-2131.8204,Stop Loss,15480.0032,short
4,XAUUSD,2020-03-17 17:45:00,2020-03-18 08:30:00,1535.907570,1504.436824,-2128.1804,Stop Loss,13351.8228,long
5,XAUUSD,2020-03-20 08:30:00,2020-04-06 16:45:00,1495.697475,1644.444589,9861.0220,Take Profit,23212.8448,long
6,XAUUSD,2020-04-06 17:00:00,2020-07-08 16:30:00,1649.404290,1813.437547,9861.0220,Take Profit,33073.8668,long
7,XAUUSD,2020-07-08 16:45:00,2020-08-04 18:45:00,1814.626860,1995.091501,9861.0220,Take Profit,42934.8888,long
8,XAUUSD,2020-08-04 19:00:00,2020-08-11 15:45:00,1996.057530,1955.158311,-2128.1804,Stop Loss,40806.7084,long
9,XAUUSD,2020-08-11 16:15:00,2020-08-17 17:15:00,1941.098965,1980.910905,-2131.8204,Stop Loss,38674.8880,short
10,XAUUSD,2020-08-17 17:30:00,2020-08-19 21:15:00,1983.211110,1942.575114,-2128.1804,Stop Loss,36546.7076,long
11,XAUUSD,2020-08-19 21:30:00,2020-09-01 05:15:00,1943.837595,1983.705704,-2131.8204,Stop Loss,34414.8872,short
12,XAUUSD,2020-09-01 05:30:00,2020-09-02 17:00:00,1984.191600,1943.535514,-2128.1804,Stop Loss,32286.7068,long
13,XAUUSD,2020-09-02 17:15:00,2021-02-26 16:45:00,1944.407310,1750.841562,9878.9820,Take Profit,42165.6888,short
14,XAUUSD,2021-02-26 17:30:00,2021-04-15 17:00:00,1727.335900,1762.763559,-2131.8204,Stop Loss,40033.8684,short
15,XAUUSD,2021-04-15 17:15:00,2021-08-09 01:45:00,1764.291705,1728.141368,-2128.1804,Stop Loss,37905.6880,long
16,XAUUSD,2021-08-09 02:15:00,2021-08-09 04:00:00,1698.500325,1733.336567,-2131.8204,Stop Loss,35773.8676,short
17,XAUUSD,2021-08-11 14:00:00,2022-02-22 01:00:00,1738.278705,1911.150522,9861.0220,Take Profit,45634.8896,long
18,XAUUSD,2022-02-22 01:15:00,2022-04-28 08:30:00,1913.116080,1873.916332,-2128.1804,Stop Loss,43506.7092,long
19,XAUUSD,2022-04-28 22:45:00,2022-05-02 16:30:00,1895.957505,1857.109336,-2128.1804,Stop Loss,41378.5288,long
20,XAUUSD,2022-05-03 17:45:00,2022-05-10 22:30:00,1877.308185,1838.842140,-2128.1804,Stop Loss,39250.3484,long
21,XAUUSD,2022-05-12 15:15:00,2022-09-16 10:45:00,1843.097990,1659.617585,9878.9820,Take Profit,49129.3304,short
22,XAUUSD,2022-09-16 18:15:00,2022-09-23 13:45:00,1675.987575,1641.646590,-2128.1804,Stop Loss,47001.1500,long
23,XAUUSD,2022-09-23 14:00:00,2022-10-03 17:00:00,1642.708235,1676.400181,-2131.8204,Stop Loss,44869.3296,short
24,XAUUSD,2022-10-03 17:15:00,2022-10-13 15:45:00,1679.019090,1644.615989,-2128.1804,Stop Loss,42741.1492,long
25,XAUUSD,2022-10-13 16:15:00,2022-11-08 17:00:00,1649.035070,1682.856779,-2131.8204,Stop Loss,40609.3288,short
26,XAUUSD,2022-11-08 17:15:00,2023-01-06 21:00:00,1699.639395,1868.668533,9861.0220,Take Profit,50470.3508,long
27,XAUUSD,2023-01-06 21:15:00,2023-02-15 10:00:00,1869.854460,1831.541142,-2128.1804,Stop Loss,48342.1704,long
28,XAUUSD,2023-02-15 10:15:00,2023-03-10 22:45:00,1832.993045,1870.587732,-2131.8204,Stop Loss,46210.3500,short
29,XAUUSD,2023-03-10 23:00:00,2023-05-04 01:00:00,1870.784925,2056.834486,9861.0220,Take Profit,56071.3720,long
30,XAUUSD,2023-05-04 01:15:00,2023-05-05 15:30:00,2051.265120,2009.234698,-2128.1804,Stop Loss,53943.1916,long
31,XAUUSD,2023-05-05 15:45:00,2023-05-10 15:30:00,2007.535730,2048.710288,-2131.8204,Stop Loss,51811.3712,short
32,XAUUSD,2023-05-11 12:15:00,2023-10-03 05:00:00,2022.488250,1821.149545,9878.9820,Take Profit,61690.3532,short
33,XAUUSD,2023-10-05 05:00:00,2023-11-27 03:15:00,1829.004045,2010.898497,9861.0220,Take Profit,71551.3752,long
34,XAUUSD,2023-11-27 03:30:00,2023-12-11 19:45:00,2018.028510,1976.679106,-2128.1804,Stop Loss,69423.1948,long
35,XAUUSD,2023-12-11 20:00:00,2023-12-13 21:30:00,1975.721645,2016.243696,-2131.8204,Stop Loss,67291.3744,short
36,XAUUSD,2023-12-13 21:45:00,2024-03-21 00:15:00,2016.437715,2216.972446,9861.0220,Take Profit,77152.3964,long
37,XAUUSD,2024-03-21 00:30:00,2024-03-22 09:15:00,2209.564230,2164.290259,-2128.1804,Stop Loss,75024.2160,long
38,XAUUSD,2024-03-25 16:15:00,2024-04-12 10:45:00,2181.049980,2397.955401,9861.0220,Take Profit,84885.2380,long
39,XAUUSD,2024-04-12 22:00:00,2024-04-15 22:15:00,2337.610610,2385.555004,-2131.8204,Stop Loss,82753.4176,short
40,XAUUSD,2024-04-15 22:30:00,2024-04-22 15:00:00,2385.542175,2336.662416,-2128.1804,Stop Loss,80625.2372,long
41,XAUUSD,2024-04-26 09:45:00,2024-04-30 17:45:00,2342.480655,2294.483226,-2128.1804,Stop Loss,78497.0568,long
42,XAUUSD,2024-05-01 17:30:00,2024-09-12 16:00:00,2307.032940,2536.467366,9861.0220,Take Profit,88358.0788,long
43,XAUUSD,2024-09-12 16:15:00,2025-01-30 17:45:00,2539.269000,2791.799302,9861.0220,Take Profit,98219.1008,long
44,XAUUSD,2025-01-30 18:00:00,2025-03-28 04:00:00,2796.557580,3074.675231,9861.0220,Take Profit,108080.1228,long
45,XAUUSD,2025-03-28 04:30:00,2025-04-07 01:00:00,3076.997730,3013.950047,-2128.1804,Stop Loss,105951.9424,long
46,XAUUSD,2025-04-07 19:00:00,2025-04-09 10:00:00,2985.996255,3047.239038,-2131.8204,Stop Loss,103820.1220,short
47,XAUUSD,2025-04-09 10:15:00,2025-04-17 01:00:00,3046.752615,3349.752163,9861.0220,Take Profit,113681.1440,long
48,XAUUSD,2025-04-17 18:45:00,2025-04-21 03:30:00,3295.591380,3363.183959,-2131.8204,Stop Loss,111549.3236,short
49,XAUUSD,2025-04-21 04:00:00,2025-04-23 09:45:00,3370.384350,3301.325175,-2128.1804,Stop Loss,109421.1432,long
50,XAUUSD,2025-04-25 01:45:00,2025-04-25 08:45:00,3366.732525,3297.748176,-2128.1804,Stop Loss,107292.9628,long

In [10]:
from itertools import product
from tqdm import tqdm
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression

# === Metrics Calculation Function (with R² and Monthly Consistency) ===
def calculate_metrics(tradebook):
    if tradebook.empty:
        return 0, 0, 0, 0

    # Ensure datetime
    tradebook['Date'] = pd.to_datetime(tradebook['Entry Time'])  # Replace with correct column if different

    equity = tradebook['PnL'].cumsum()
    total_profit = equity.iloc[-1]

    roll_max = equity.cummax()
    drawdown = roll_max - equity
    max_drawdown = drawdown.max()

    if max_drawdown == 0:
        ratio = float('inf') if total_profit > 0 else 0
    else:
        ratio = total_profit / max_drawdown

    # R² for equity curve smoothness
    x = np.arange(len(equity)).reshape(-1, 1)
    y = equity.values.reshape(-1, 1)
    model = LinearRegression().fit(x, y)
    r2 = model.score(x, y)

    # Monthly return consistency metric
    tradebook['Month'] = tradebook['Date'].dt.to_period('M')
    monthly_returns = tradebook.groupby('Month')['PnL'].sum()
    if len(monthly_returns) < 2:
        monthly_consistency = 0
    else:
        monthly_mean = monthly_returns.mean()
        monthly_std = monthly_returns.std()
        monthly_consistency = monthly_mean / monthly_std if monthly_std > 0 else float('inf')

    return ratio, total_profit, r2, monthly_consistency

# === Hyperparameter Grid ===
param_grid = {
    'smooth_length': [10, 14],
    'norm_period': [100, 120],
    'upper_thresh': [1.75, 2],
    'lower_thresh': [-2, -2.25, -2.5],
    'rs_period': [10, 14],
    'rs_percentile': [10, 30, 50],
    'tp_pct': [0.05, 0.07, 0.1],
    'sl_pct': [0.01, 0.015, 0.02]
}

# === Generate All Parameter Combinations ===
keys, values = zip(*param_grid.items())
param_combinations = list(product(*values))
results = []

print(f"Total combinations to test: {len(param_combinations)}\n")

# === Hyperparameter Tuning Loop ===
for i, combo in enumerate(tqdm(param_combinations, desc="Hypertuning"), 1):
    param = dict(zip(keys, combo))

    print(f"\n=== [{i}/{len(param_combinations)}] Testing Parameters ===")
    for k, v in param.items():
        print(f"{k}: {v}")

    temp_data = data.copy()

    def apply_strategy(group):
        return compute_jma_indicator(
            group,
            smooth_length=param['smooth_length'],
            norm_period=param['norm_period'],
            upper_thresh=param['upper_thresh'],
            lower_thresh=param['lower_thresh'],
            rs_period=param['rs_period'],
            rs_percentile=param['rs_percentile']
        )

    temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

    # Shift signals to next bar to avoid lookahead bias
    temp_data['Signal'] = temp_data.groupby('Ticker')['Signal'].shift(1)
    temp_data = temp_data.dropna(subset=['Signal'])
    temp_data['Signal'] = temp_data['Signal'].astype(int)

    # Run Backtest
    tradebook = backtest_trades(
        temp_data,
        sl_pct=param['sl_pct'],
        tp_pct=param['tp_pct']
    )

    # Evaluate metrics
    ratio, total_profit, r2, monthly_consistency = calculate_metrics(tradebook)

    print(f"➡️ Profit-to-Drawdown Ratio: {ratio:.4f}")
    print(f"➡️ Total Profit: ₹{total_profit:,.2f}")
    print(f"➡️ Equity Curve R²: {r2:.4f}")
    print(f"➡️ Monthly Consistency Score: {monthly_consistency:.4f}")

    result = {
        **param,
        'Profit/Drawdown': ratio,
        'Total Profit': total_profit,
        'Equity R2': r2,
        'Monthly Consistency': monthly_consistency
    }
    results.append(result)

# === Final Results and Export ===
results_df = pd.DataFrame(results)

# Optional: Composite metric for sorting
results_df['Composite Score'] = (
    results_df['Profit/Drawdown'] * 0.5 +
    results_df['Equity R2'] * 0.4 +
    results_df['Monthly Consistency'] * 0.1
)

results_df = results_df.sort_values(by='Composite Score', ascending=False)
results_df.to_csv("/content/drive/MyDrive/hyperparameter_results_adaptive_intraday_full.csv", index=False)

print("\n✅ Hyperparameter tuning complete. Top 5 results:")
print(results_df.head())

Total combinations to test: 3456

Hypertuning:   0%|          | 0/3456 [00:00<?, ?it/s]

=== [1/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.60it/s]
Hypertuning:   0%|          | 1/3456 [00:01<1:22:32,  1.43s/it]

➡️ Profit-to-Drawdown Ratio: -0.7666
➡️ Total Profit: ₹-59,432.26
➡️ Equity Curve R²: 0.8763
➡️ Monthly Consistency Score: -0.2317

=== [2/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.04it/s]
Hypertuning:   0%|          | 2/3456 [00:02<1:18:59,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.5933
➡️ Total Profit: ₹-35,638.68
➡️ Equity Curve R²: 0.9446
➡️ Monthly Consistency Score: -0.1630

=== [3/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.28it/s]
Hypertuning:   0%|          | 3/3456 [00:04<1:19:11,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.6762
➡️ Total Profit: ₹36,819.73
➡️ Equity Curve R²: 0.7511
➡️ Monthly Consistency Score: 0.1634

=== [4/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.01it/s]
Hypertuning:   0%|          | 4/3456 [00:05<1:17:49,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.4058
➡️ Total Profit: ₹-18,103.26
➡️ Equity Curve R²: 0.4791
➡️ Monthly Consistency Score: -0.0614

=== [5/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.65it/s]
Hypertuning:   0%|          | 5/3456 [00:06<1:19:12,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.1185
➡️ Total Profit: ₹3,450.65
➡️ Equity Curve R²: 0.1114
➡️ Monthly Consistency Score: 0.0118

=== [6/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.80it/s]
Hypertuning:   0%|          | 6/3456 [00:08<1:17:48,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2922
➡️ Total Profit: ₹8,197.53
➡️ Equity Curve R²: 0.2208
➡️ Monthly Consistency Score: 0.0335

=== [7/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.17it/s]
Hypertuning:   0%|          | 7/3456 [00:09<1:17:58,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0849
➡️ Total Profit: ₹2,356.25
➡️ Equity Curve R²: 0.0098
➡️ Monthly Consistency Score: 0.0098

=== [8/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.64it/s]
Hypertuning:   0%|          | 8/3456 [00:10<1:16:38,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: -0.2563
➡️ Total Profit: ₹-10,369.80
➡️ Equity Curve R²: 0.4660
➡️ Monthly Consistency Score: -0.0417

=== [9/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.27it/s]
Hypertuning:   0%|          | 9/3456 [00:12<1:17:38,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2857
➡️ Total Profit: ₹-12,473.68
➡️ Equity Curve R²: 0.6756
➡️ Monthly Consistency Score: -0.0442

=== [10/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.98it/s]
Hypertuning:   0%|          | 10/3456 [00:13<1:18:16,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3387
➡️ Total Profit: ₹-14,782.56
➡️ Equity Curve R²: 0.4494
➡️ Monthly Consistency Score: -0.0555

=== [11/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.98it/s]
Hypertuning:   0%|          | 11/3456 [00:14<1:17:09,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.8951
➡️ Total Profit: ₹28,231.11
➡️ Equity Curve R²: 0.0735
➡️ Monthly Consistency Score: 0.1140

=== [12/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.45it/s]
Hypertuning:   0%|          | 12/3456 [00:16<1:18:09,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.3644
➡️ Total Profit: ₹34,869.19
➡️ Equity Curve R²: 0.4970
➡️ Monthly Consistency Score: 0.1440

=== [13/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.66it/s]
Hypertuning:   0%|          | 13/3456 [00:17<1:17:54,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0613
➡️ Total Profit: ₹3,077.65
➡️ Equity Curve R²: 0.5788
➡️ Monthly Consistency Score: 0.0117

=== [14/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 109.58it/s]
Hypertuning:   0%|          | 14/3456 [00:19<1:18:42,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.9505
➡️ Total Profit: ₹35,806.33
➡️ Equity Curve R²: 0.0744
➡️ Monthly Consistency Score: 0.1416

=== [15/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.06it/s]
Hypertuning:   0%|          | 15/3456 [00:20<1:17:45,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.1890
➡️ Total Profit: ₹40,391.93
➡️ Equity Curve R²: 0.0510
➡️ Monthly Consistency Score: 0.1619

=== [16/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.55it/s]
Hypertuning:   0%|          | 16/3456 [00:21<1:16:28,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 2.3280
➡️ Total Profit: ₹56,381.01
➡️ Equity Curve R²: 0.3259
➡️ Monthly Consistency Score: 0.2694

=== [17/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.80it/s]
Hypertuning:   0%|          | 17/3456 [00:23<1:17:39,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.7518
➡️ Total Profit: ₹-56,702.40
➡️ Equity Curve R²: 0.8773
➡️ Monthly Consistency Score: -0.2305

=== [18/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.51it/s]
Hypertuning:   1%|          | 18/3456 [00:24<1:18:49,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.4990
➡️ Total Profit: ₹-25,469.60
➡️ Equity Curve R²: 0.8549
➡️ Monthly Consistency Score: -0.1084

=== [19/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.72it/s]
Hypertuning:   1%|          | 19/3456 [00:25<1:17:43,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.9345
➡️ Total Profit: ₹42,493.85
➡️ Equity Curve R²: 0.7286
➡️ Monthly Consistency Score: 0.1796

=== [20/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.65it/s]
Hypertuning:   1%|          | 20/3456 [00:27<1:18:25,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1538
➡️ Total Profit: ₹-6,708.66
➡️ Equity Curve R²: 0.2155
➡️ Monthly Consistency Score: -0.0228

=== [21/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.75it/s]
Hypertuning:   1%|          | 21/3456 [00:28<1:18:00,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4880
➡️ Total Profit: ₹11,300.18
➡️ Equity Curve R²: 0.0451
➡️ Monthly Consistency Score: 0.0379

=== [22/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.18it/s]
Hypertuning:   1%|          | 22/3456 [00:30<1:19:23,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 0.5563
➡️ Total Profit: ₹14,979.37
➡️ Equity Curve R²: 0.1016
➡️ Monthly Consistency Score: 0.0594

=== [23/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.04it/s]
Hypertuning:   1%|          | 23/3456 [00:31<1:18:15,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.5575
➡️ Total Profit: ₹33,224.52
➡️ Equity Curve R²: 0.3382
➡️ Monthly Consistency Score: 0.1298

=== [24/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.05it/s]
Hypertuning:   1%|          | 24/3456 [00:32<1:18:34,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3112
➡️ Total Profit: ₹-12,497.98
➡️ Equity Curve R²: 0.7187
➡️ Monthly Consistency Score: -0.0472

=== [25/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.41it/s]
Hypertuning:   1%|          | 25/3456 [00:34<1:17:48,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4409
➡️ Total Profit: ₹-25,581.34
➡️ Equity Curve R²: 0.7791
➡️ Monthly Consistency Score: -0.0903

=== [26/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.79it/s]
Hypertuning:   1%|          | 26/3456 [00:35<1:18:05,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1833
➡️ Total Profit: ₹-8,002.56
➡️ Equity Curve R²: 0.3285
➡️ Monthly Consistency Score: -0.0302

=== [27/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.68it/s]
Hypertuning:   1%|          | 27/3456 [00:36<1:16:36,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.9468
➡️ Total Profit: ₹29,862.48
➡️ Equity Curve R²: 0.0855
➡️ Monthly Consistency Score: 0.1199

=== [28/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.37it/s]
Hypertuning:   1%|          | 28/3456 [00:38<1:16:48,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.8021
➡️ Total Profit: ₹42,221.01
➡️ Equity Curve R²: 0.5388
➡️ Monthly Consistency Score: 0.1644

=== [29/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.09it/s]
Hypertuning:   1%|          | 29/3456 [00:39<1:18:05,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.1694
➡️ Total Profit: ₹8,114.83
➡️ Equity Curve R²: 0.5645
➡️ Monthly Consistency Score: 0.0306

=== [30/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.00it/s]
Hypertuning:   1%|          | 30/3456 [00:40<1:17:15,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.2505
➡️ Total Profit: ₹41,457.25
➡️ Equity Curve R²: 0.0090
➡️ Monthly Consistency Score: 0.1670

=== [31/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.93it/s]
Hypertuning:   1%|          | 31/3456 [00:42<1:16:14,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.4767
➡️ Total Profit: ₹50,169.19
➡️ Equity Curve R²: 0.0014
➡️ Monthly Consistency Score: 0.1962

=== [32/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.39it/s]
Hypertuning:   1%|          | 32/3456 [00:43<1:16:27,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.4664
➡️ Total Profit: ₹56,381.01
➡️ Equity Curve R²: 0.2835
➡️ Monthly Consistency Score: 0.2538

=== [33/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.14it/s]
Hypertuning:   1%|          | 33/3456 [00:44<1:18:01,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.7184
➡️ Total Profit: ₹-62,229.72
➡️ Equity Curve R²: 0.9131
➡️ Monthly Consistency Score: -0.2625

=== [34/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.56it/s]
Hypertuning:   1%|          | 34/3456 [00:46<1:19:39,  1.40s/it]

➡️ Profit-to-Drawdown Ratio: -0.5449
➡️ Total Profit: ₹-37,376.92
➡️ Equity Curve R²: 0.8955
➡️ Monthly Consistency Score: -0.1561

=== [35/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.45it/s]
Hypertuning:   1%|          | 35/3456 [00:47<1:23:02,  1.46s/it]

➡️ Profit-to-Drawdown Ratio: 1.5448
➡️ Total Profit: ₹31,925.62
➡️ Equity Curve R²: 0.5701
➡️ Monthly Consistency Score: 0.1276

=== [36/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.73it/s]
Hypertuning:   1%|          | 36/3456 [00:49<1:22:45,  1.45s/it]

➡️ Profit-to-Drawdown Ratio: -0.0203
➡️ Total Profit: ₹-884.97
➡️ Equity Curve R²: 0.1920
➡️ Monthly Consistency Score: -0.0031

=== [37/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 89.16it/s]
Hypertuning:   1%|          | 37/3456 [00:51<1:25:45,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.2734
➡️ Total Profit: ₹7,394.29
➡️ Equity Curve R²: 0.0240
➡️ Monthly Consistency Score: 0.0289

=== [38/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.92it/s]
Hypertuning:   1%|          | 38/3456 [00:52<1:24:36,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 0.6700
➡️ Total Profit: ₹14,544.77
➡️ Equity Curve R²: 0.0319
➡️ Monthly Consistency Score: 0.0563

=== [39/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.56it/s]
Hypertuning:   1%|          | 39/3456 [00:54<1:26:29,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 1.3126
➡️ Total Profit: ₹23,533.48
➡️ Equity Curve R²: 0.6005
➡️ Monthly Consistency Score: 0.1084

=== [40/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.68it/s]
Hypertuning:   1%|          | 40/3456 [00:55<1:25:43,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.3082
➡️ Total Profit: ₹-17,069.80
➡️ Equity Curve R²: 0.7562
➡️ Monthly Consistency Score: -0.0657

=== [41/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.34it/s]
Hypertuning:   1%|          | 41/3456 [00:57<1:27:33,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: -0.3378
➡️ Total Profit: ₹-16,129.92
➡️ Equity Curve R²: 0.7031
➡️ Monthly Consistency Score: -0.0575

=== [42/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.83it/s]
Hypertuning:   1%|          | 42/3456 [00:58<1:26:05,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 3.0227
➡️ Total Profit: ₹66,939.30
➡️ Equity Curve R²: 0.3405
➡️ Monthly Consistency Score: 0.2918

=== [43/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 90.41it/s]
Hypertuning:   1%|          | 43/3456 [01:00<1:27:18,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.5786
➡️ Total Profit: ₹19,738.76
➡️ Equity Curve R²: 0.0136
➡️ Monthly Consistency Score: 0.0807

=== [44/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.76it/s]
Hypertuning:   1%|▏         | 44/3456 [01:01<1:25:49,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.8933
➡️ Total Profit: ₹44,356.47
➡️ Equity Curve R²: 0.4107
➡️ Monthly Consistency Score: 0.1712

=== [45/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.07it/s]
Hypertuning:   1%|▏         | 45/3456 [01:03<1:24:48,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 0.9584
➡️ Total Profit: ₹35,835.77
➡️ Equity Curve R²: 0.0005
➡️ Monthly Consistency Score: 0.1533

=== [46/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.29it/s]
Hypertuning:   1%|▏         | 46/3456 [01:04<1:25:51,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.1766
➡️ Total Profit: ₹40,331.85
➡️ Equity Curve R²: 0.0359
➡️ Monthly Consistency Score: 0.1644

=== [47/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.64it/s]
Hypertuning:   1%|▏         | 47/3456 [01:06<1:27:17,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 1.5248
➡️ Total Profit: ₹51,800.56
➡️ Equity Curve R²: 0.0150
➡️ Monthly Consistency Score: 0.2174

=== [48/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.05it/s]
Hypertuning:   1%|▏         | 48/3456 [01:07<1:26:11,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 2.4160
➡️ Total Profit: ₹58,512.83
➡️ Equity Curve R²: 0.3083
➡️ Monthly Consistency Score: 0.2750

=== [49/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.71it/s]
Hypertuning:   1%|▏         | 49/3456 [01:09<1:24:53,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: -0.7666
➡️ Total Profit: ₹-59,431.32
➡️ Equity Curve R²: 0.8807
➡️ Monthly Consistency Score: -0.2312

=== [50/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.75it/s]
Hypertuning:   1%|▏         | 50/3456 [01:10<1:25:37,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.6342
➡️ Total Profit: ₹-37,380.44
➡️ Equity Curve R²: 0.9457
➡️ Monthly Consistency Score: -0.1684

=== [51/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 89.72it/s]
Hypertuning:   1%|▏         | 51/3456 [01:12<1:26:22,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 1.7681
➡️ Total Profit: ₹38,838.42
➡️ Equity Curve R²: 0.7873
➡️ Monthly Consistency Score: 0.1671

=== [52/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.60it/s]
Hypertuning:   2%|▏         | 52/3456 [01:13<1:24:39,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 0.4220
➡️ Total Profit: ₹8,936.75
➡️ Equity Curve R²: 0.0000
➡️ Monthly Consistency Score: 0.0324

=== [53/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.15it/s]
Hypertuning:   2%|▏         | 53/3456 [01:15<1:26:19,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.1918
➡️ Total Profit: ₹5,341.12
➡️ Equity Curve R²: 0.0904
➡️ Monthly Consistency Score: 0.0183

=== [54/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.86it/s]
Hypertuning:   2%|▏         | 54/3456 [01:16<1:24:46,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.2922
➡️ Total Profit: ₹8,197.53
➡️ Equity Curve R²: 0.2208
➡️ Monthly Consistency Score: 0.0335

=== [55/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.72it/s]
Hypertuning:   2%|▏         | 55/3456 [01:18<1:26:10,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.0849
➡️ Total Profit: ₹2,356.25
➡️ Equity Curve R²: 0.0098
➡️ Monthly Consistency Score: 0.0098

=== [56/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 87.28it/s]
Hypertuning:   2%|▏         | 56/3456 [01:19<1:24:55,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.2563
➡️ Total Profit: ₹-10,369.80
➡️ Equity Curve R²: 0.4660
➡️ Monthly Consistency Score: -0.0417

=== [57/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.65it/s]
Hypertuning:   2%|▏         | 57/3456 [01:21<1:26:39,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.2752
➡️ Total Profit: ₹-11,842.27
➡️ Equity Curve R²: 0.6715
➡️ Monthly Consistency Score: -0.0420

=== [58/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 87.70it/s]
Hypertuning:   2%|▏         | 58/3456 [01:22<1:24:46,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.2351
➡️ Total Profit: ₹-10,262.56
➡️ Equity Curve R²: 0.3813
➡️ Monthly Consistency Score: -0.0386

=== [59/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.96it/s]
Hypertuning:   2%|▏         | 59/3456 [01:24<1:25:36,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.8951
➡️ Total Profit: ₹28,231.11
➡️ Equity Curve R²: 0.0735
➡️ Monthly Consistency Score: 0.1100

=== [60/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 86.68it/s]
Hypertuning:   2%|▏         | 60/3456 [01:25<1:24:49,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 1.3644
➡️ Total Profit: ₹34,869.19
➡️ Equity Curve R²: 0.4970
➡️ Monthly Consistency Score: 0.1440

=== [61/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.32it/s]
Hypertuning:   2%|▏         | 61/3456 [01:27<1:26:46,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.0613
➡️ Total Profit: ₹3,077.65
➡️ Equity Curve R²: 0.5788
➡️ Monthly Consistency Score: 0.0117

=== [62/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.94it/s]
Hypertuning:   2%|▏         | 62/3456 [01:28<1:25:13,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.9505
➡️ Total Profit: ₹35,806.33
➡️ Equity Curve R²: 0.0744
➡️ Monthly Consistency Score: 0.1416

=== [63/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.82it/s]
Hypertuning:   2%|▏         | 63/3456 [01:30<1:26:18,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 1.1890
➡️ Total Profit: ₹40,391.93
➡️ Equity Curve R²: 0.0510
➡️ Monthly Consistency Score: 0.1619

=== [64/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.33it/s]
Hypertuning:   2%|▏         | 64/3456 [01:31<1:24:57,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 2.3280
➡️ Total Profit: ₹56,381.01
➡️ Equity Curve R²: 0.3259
➡️ Monthly Consistency Score: 0.2694

=== [65/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.83it/s]
Hypertuning:   2%|▏         | 65/3456 [01:33<1:26:12,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.7753
➡️ Total Profit: ₹-60,824.08
➡️ Equity Curve R²: 0.9059
➡️ Monthly Consistency Score: -0.2377

=== [66/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 84.76it/s]
Hypertuning:   2%|▏         | 66/3456 [01:34<1:24:33,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.3752
➡️ Total Profit: ₹-21,887.79
➡️ Equity Curve R²: 0.8450
➡️ Monthly Consistency Score: -0.0915

=== [67/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.18it/s]
Hypertuning:   2%|▏         | 67/3456 [01:36<1:25:04,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.8604
➡️ Total Profit: ₹40,865.22
➡️ Equity Curve R²: 0.7237
➡️ Monthly Consistency Score: 0.1725

=== [68/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 87.32it/s]
Hypertuning:   2%|▏         | 68/3456 [01:37<1:26:17,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.3817
➡️ Total Profit: ₹-17,360.48
➡️ Equity Curve R²: 0.3603
➡️ Monthly Consistency Score: -0.0604

=== [69/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.42it/s]
Hypertuning:   2%|▏         | 69/3456 [01:39<1:25:21,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.1205
➡️ Total Profit: ₹4,079.24
➡️ Equity Curve R²: 0.0008
➡️ Monthly Consistency Score: 0.0146

=== [70/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.81it/s]
Hypertuning:   2%|▏         | 70/3456 [01:40<1:23:53,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 0.6403
➡️ Total Profit: ₹17,239.37
➡️ Equity Curve R²: 0.1178
➡️ Monthly Consistency Score: 0.0687

=== [71/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.18it/s]
Hypertuning:   2%|▏         | 71/3456 [01:42<1:24:23,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 1.7867
➡️ Total Profit: ₹38,113.15
➡️ Equity Curve R²: 0.3172
➡️ Monthly Consistency Score: 0.1463

=== [72/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 89.30it/s]
Hypertuning:   2%|▏         | 72/3456 [01:43<1:25:43,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.1509
➡️ Total Profit: ₹-6,106.16
➡️ Equity Curve R²: 0.4587
➡️ Monthly Consistency Score: -0.0244

=== [73/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.98it/s]
Hypertuning:   2%|▏         | 73/3456 [01:45<1:25:36,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.3258
➡️ Total Profit: ₹-14,359.45
➡️ Equity Curve R²: 0.6630
➡️ Monthly Consistency Score: -0.0514

=== [74/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.15it/s]
Hypertuning:   2%|▏         | 74/3456 [01:47<1:27:00,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: -0.4163
➡️ Total Profit: ₹-18,173.48
➡️ Equity Curve R²: 0.4602
➡️ Monthly Consistency Score: -0.0677

=== [75/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 89.95it/s]
Hypertuning:   2%|▏         | 75/3456 [01:48<1:25:19,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.0501
➡️ Total Profit: ₹33,122.48
➡️ Equity Curve R²: 0.1612
➡️ Monthly Consistency Score: 0.1344

=== [76/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.82it/s]
Hypertuning:   2%|▏         | 76/3456 [01:49<1:23:34,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 1.8021
➡️ Total Profit: ₹42,221.01
➡️ Equity Curve R²: 0.5388
➡️ Monthly Consistency Score: 0.1644

=== [77/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.11it/s]
Hypertuning:   2%|▏         | 77/3456 [01:51<1:25:06,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.0863
➡️ Total Profit: ₹4,336.71
➡️ Equity Curve R²: 0.5866
➡️ Monthly Consistency Score: 0.0162

=== [78/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.63it/s]
Hypertuning:   2%|▏         | 78/3456 [01:53<1:26:16,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 1.1069
➡️ Total Profit: ₹39,197.25
➡️ Equity Curve R²: 0.0421
➡️ Monthly Consistency Score: 0.1571

=== [79/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.82it/s]
Hypertuning:   2%|▏         | 79/3456 [01:54<1:24:22,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 1.5248
➡️ Total Profit: ₹51,800.56
➡️ Equity Curve R²: 0.0002
➡️ Monthly Consistency Score: 0.2057

=== [80/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.71it/s]
Hypertuning:   2%|▏         | 80/3456 [01:56<1:24:53,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 2.4160
➡️ Total Profit: ₹58,512.83
➡️ Equity Curve R²: 0.3083
➡️ Monthly Consistency Score: 0.2750

=== [81/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.26it/s]
Hypertuning:   2%|▏         | 81/3456 [01:57<1:24:41,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.7490
➡️ Total Profit: ₹-57,757.24
➡️ Equity Curve R²: 0.9064
➡️ Monthly Consistency Score: -0.2566

=== [82/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.45it/s]
Hypertuning:   2%|▏         | 82/3456 [01:59<1:26:14,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.1809
➡️ Total Profit: ₹-8,434.95
➡️ Equity Curve R²: 0.5257
➡️ Monthly Consistency Score: -0.0365

=== [83/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.29it/s]
Hypertuning:   2%|▏         | 83/3456 [02:00<1:24:39,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.5189
➡️ Total Profit: ₹33,952.41
➡️ Equity Curve R²: 0.6558
➡️ Monthly Consistency Score: 0.1425

=== [84/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.27it/s]
Hypertuning:   2%|▏         | 84/3456 [02:02<1:25:43,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.2743
➡️ Total Profit: ₹-15,146.90
➡️ Equity Curve R²: 0.4077
➡️ Monthly Consistency Score: -0.0539

=== [85/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.67it/s]
Hypertuning:   2%|▏         | 85/3456 [02:03<1:24:54,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.5032
➡️ Total Profit: ₹11,171.47
➡️ Equity Curve R²: 0.1369
➡️ Monthly Consistency Score: 0.0463

=== [86/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 88.42it/s]
Hypertuning:   2%|▏         | 86/3456 [02:05<1:25:49,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 1.3450
➡️ Total Profit: ₹25,839.49
➡️ Equity Curve R²: 0.4533
➡️ Monthly Consistency Score: 0.1028

=== [87/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.35it/s]
Hypertuning:   3%|▎         | 87/3456 [02:06<1:24:15,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.5893
➡️ Total Profit: ₹15,399.00
➡️ Equity Curve R²: 0.2665
➡️ Monthly Consistency Score: 0.0663

=== [88/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.87it/s]
Hypertuning:   3%|▎         | 88/3456 [02:08<1:25:28,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.3833
➡️ Total Profit: ₹13,062.03
➡️ Equity Curve R²: 0.0935
➡️ Monthly Consistency Score: 0.0496

=== [89/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 88.08it/s]
Hypertuning:   3%|▎         | 89/3456 [02:09<1:25:04,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.3246
➡️ Total Profit: ₹-15,497.57
➡️ Equity Curve R²: 0.7282
➡️ Monthly Consistency Score: -0.0533

=== [90/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.19it/s]
Hypertuning:   3%|▎         | 90/3456 [02:11<1:25:53,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 3.1704
➡️ Total Profit: ₹68,072.06
➡️ Equity Curve R²: 0.4726
➡️ Monthly Consistency Score: 0.3081

=== [91/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.19it/s]
Hypertuning:   3%|▎         | 91/3456 [02:12<1:24:03,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 1.6403
➡️ Total Profit: ₹34,760.93
➡️ Equity Curve R²: 0.6744
➡️ Monthly Consistency Score: 0.1411

=== [92/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.16it/s]
Hypertuning:   3%|▎         | 92/3456 [02:14<1:24:47,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 2.0706
➡️ Total Profit: ₹46,969.11
➡️ Equity Curve R²: 0.6552
➡️ Monthly Consistency Score: 0.1762

=== [93/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.49it/s]
Hypertuning:   3%|▎         | 93/3456 [02:15<1:24:02,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.2621
➡️ Total Profit: ₹12,117.57
➡️ Equity Curve R²: 0.5097
➡️ Monthly Consistency Score: 0.0492

=== [94/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.30it/s]
Hypertuning:   3%|▎         | 94/3456 [02:17<1:25:05,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 1.8442
➡️ Total Profit: ₹54,185.63
➡️ Equity Curve R²: 0.1513
➡️ Monthly Consistency Score: 0.2181

=== [95/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.81it/s]
Hypertuning:   3%|▎         | 95/3456 [02:18<1:23:19,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 1.4974
➡️ Total Profit: ₹48,546.04
➡️ Equity Curve R²: 0.1256
➡️ Monthly Consistency Score: 0.1987

=== [96/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.84it/s]
Hypertuning:   3%|▎         | 96/3456 [02:20<1:24:58,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 2.9379
➡️ Total Profit: ₹64,901.01
➡️ Equity Curve R²: 0.3801
➡️ Monthly Consistency Score: 0.3098

=== [97/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 90.22it/s]
Hypertuning:   3%|▎         | 97/3456 [02:21<1:24:10,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.6342
➡️ Total Profit: ₹-46,771.34
➡️ Equity Curve R²: 0.8990
➡️ Monthly Consistency Score: -0.1951

=== [98/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.18it/s]
Hypertuning:   3%|▎         | 98/3456 [02:23<1:25:20,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.6392
➡️ Total Profit: ₹-39,123.72
➡️ Equity Curve R²: 0.9405
➡️ Monthly Consistency Score: -0.1588

=== [99/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 89.71it/s]
Hypertuning:   3%|▎         | 99/3456 [02:24<1:23:53,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.2675
➡️ Total Profit: ₹11,847.00
➡️ Equity Curve R²: 0.1416
➡️ Monthly Consistency Score: 0.0406

=== [100/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.00it/s]
Hypertuning:   3%|▎         | 100/3456 [02:26<1:24:29,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.8927
➡️ Total Profit: ₹21,798.91
➡️ Equity Curve R²: 0.0150
➡️ Monthly Consistency Score: 0.0736

=== [101/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.34it/s]
Hypertuning:   3%|▎         | 101/3456 [02:27<1:23:01,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 0.3503
➡️ Total Profit: ₹7,405.57
➡️ Equity Curve R²: 0.0054
➡️ Monthly Consistency Score: 0.0256

=== [102/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.89it/s]
Hypertuning:   3%|▎         | 102/3456 [02:29<1:23:58,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.0100
➡️ Total Profit: ₹288.69
➡️ Equity Curve R²: 0.1196
➡️ Monthly Consistency Score: 0.0012

=== [103/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.35it/s]
Hypertuning:   3%|▎         | 103/3456 [02:30<1:24:43,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.3093
➡️ Total Profit: ₹-12,293.49
➡️ Equity Curve R²: 0.7345
➡️ Monthly Consistency Score: -0.0466

=== [104/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 90.41it/s]
Hypertuning:   3%|▎         | 104/3456 [02:32<1:23:09,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 1.7575
➡️ Total Profit: ₹35,284.97
➡️ Equity Curve R²: 0.6203
➡️ Monthly Consistency Score: 0.1584

=== [105/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.40it/s]
Hypertuning:   3%|▎         | 105/3456 [02:33<1:22:38,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: -0.1612
➡️ Total Profit: ₹-6,743.38
➡️ Equity Curve R²: 0.5348
➡️ Monthly Consistency Score: -0.0247

=== [106/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.51it/s]
Hypertuning:   3%|▎         | 106/3456 [02:35<1:24:27,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.5942
➡️ Total Profit: ₹23,917.73
➡️ Equity Curve R²: 0.0078
➡️ Monthly Consistency Score: 0.0857

=== [107/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.25it/s]
Hypertuning:   3%|▎         | 107/3456 [02:36<1:25:21,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.6023
➡️ Total Profit: ₹17,171.68
➡️ Equity Curve R²: 0.0663
➡️ Monthly Consistency Score: 0.0744

=== [108/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.26it/s]
Hypertuning:   3%|▎         | 108/3456 [02:38<1:23:25,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 1.7357
➡️ Total Profit: ₹44,358.47
➡️ Equity Curve R²: 0.4140
➡️ Monthly Consistency Score: 0.1788

=== [109/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.16it/s]
Hypertuning:   3%|▎         | 109/3456 [02:39<1:24:59,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 1.0502
➡️ Total Profit: ₹29,115.77
➡️ Equity Curve R²: 0.0058
➡️ Monthly Consistency Score: 0.1108

=== [110/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.33it/s]
Hypertuning:   3%|▎         | 110/3456 [02:41<1:23:40,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 2.2406
➡️ Total Profit: ₹60,963.79
➡️ Equity Curve R²: 0.1315
➡️ Monthly Consistency Score: 0.2618

=== [111/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.66it/s]
Hypertuning:   3%|▎         | 111/3456 [02:42<1:22:03,  1.47s/it]

➡️ Profit-to-Drawdown Ratio: 1.5317
➡️ Total Profit: ₹51,895.28
➡️ Equity Curve R²: 0.0313
➡️ Monthly Consistency Score: 0.2209

=== [112/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.83it/s]
Hypertuning:   3%|▎         | 112/3456 [02:44<1:22:44,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 4.0681
➡️ Total Profit: ₹60,648.29
➡️ Equity Curve R²: 0.5031
➡️ Monthly Consistency Score: 0.3000

=== [113/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 89.61it/s]
Hypertuning:   3%|▎         | 113/3456 [02:45<1:25:02,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.6061
➡️ Total Profit: ₹-40,538.33
➡️ Equity Curve R²: 0.8866
➡️ Monthly Consistency Score: -0.1704

=== [114/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.74it/s]
Hypertuning:   3%|▎         | 114/3456 [02:47<1:23:55,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.6712
➡️ Total Profit: ₹-50,945.64
➡️ Equity Curve R²: 0.9461
➡️ Monthly Consistency Score: -0.2158

=== [115/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 88.66it/s]
Hypertuning:   3%|▎         | 115/3456 [02:48<1:24:55,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.0160
➡️ Total Profit: ₹759.68
➡️ Equity Curve R²: 0.3306
➡️ Monthly Consistency Score: 0.0028

=== [116/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.84it/s]
Hypertuning:   3%|▎         | 116/3456 [02:50<1:22:57,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 1.5037
➡️ Total Profit: ₹30,318.91
➡️ Equity Curve R²: 0.2931
➡️ Monthly Consistency Score: 0.1040

=== [117/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.20it/s]
Hypertuning:   3%|▎         | 117/3456 [02:51<1:24:40,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.7949
➡️ Total Profit: ₹16,804.63
➡️ Equity Curve R²: 0.3662
➡️ Monthly Consistency Score: 0.0590

=== [118/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.43it/s]
Hypertuning:   3%|▎         | 118/3456 [02:53<1:23:17,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.0096
➡️ Total Profit: ₹288.69
➡️ Equity Curve R²: 0.2110
➡️ Monthly Consistency Score: 0.0012

=== [119/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 88.84it/s]
Hypertuning:   3%|▎         | 119/3456 [02:54<1:24:18,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.3711
➡️ Total Profit: ₹-17,161.75
➡️ Equity Curve R²: 0.8239
➡️ Monthly Consistency Score: -0.0653

=== [120/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.71it/s]
Hypertuning:   3%|▎         | 120/3456 [02:56<1:22:40,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 1.7575
➡️ Total Profit: ₹35,284.97
➡️ Equity Curve R²: 0.6203
➡️ Monthly Consistency Score: 0.1584

=== [121/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.54it/s]
Hypertuning:   4%|▎         | 121/3456 [02:57<1:24:33,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.4611
➡️ Total Profit: ₹-30,563.39
➡️ Equity Curve R²: 0.8488
➡️ Monthly Consistency Score: -0.1023

=== [122/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.48it/s]
Hypertuning:   4%|▎         | 122/3456 [02:59<1:23:28,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.5381
➡️ Total Profit: ₹21,657.73
➡️ Equity Curve R²: 0.0012
➡️ Monthly Consistency Score: 0.0783

=== [123/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.98it/s]
Hypertuning:   4%|▎         | 123/3456 [03:00<1:24:29,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 1.0030
➡️ Total Profit: ₹23,691.68
➡️ Equity Curve R²: 0.0000
➡️ Monthly Consistency Score: 0.1035

=== [124/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.60it/s]
Hypertuning:   4%|▎         | 124/3456 [03:02<1:22:55,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 1.9857
➡️ Total Profit: ₹50,746.65
➡️ Equity Curve R²: 0.5959
➡️ Monthly Consistency Score: 0.2112

=== [125/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.61it/s]
Hypertuning:   4%|▎         | 125/3456 [03:03<1:24:42,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 1.0479
➡️ Total Profit: ₹30,372.95
➡️ Equity Curve R²: 0.0187
➡️ Monthly Consistency Score: 0.1150

=== [126/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.18it/s]
Hypertuning:   4%|▎         | 126/3456 [03:05<1:23:18,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 1.8817
➡️ Total Profit: ₹57,574.71
➡️ Equity Curve R²: 0.0570
➡️ Monthly Consistency Score: 0.2310

=== [127/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.76it/s]
Hypertuning:   4%|▎         | 127/3456 [03:06<1:24:24,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 1.5798
➡️ Total Profit: ₹53,526.65
➡️ Equity Curve R²: 0.0215
➡️ Monthly Consistency Score: 0.2275

=== [128/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 84.11it/s]
Hypertuning:   4%|▎         | 128/3456 [03:08<1:22:53,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 5.2469
➡️ Total Profit: ₹67,036.47
➡️ Equity Curve R²: 0.6411
➡️ Monthly Consistency Score: 0.3290

=== [129/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.62it/s]
Hypertuning:   4%|▎         | 129/3456 [03:09<1:22:12,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: -0.5669
➡️ Total Profit: ₹-38,152.03
➡️ Equity Curve R²: 0.9021
➡️ Monthly Consistency Score: -0.1646

=== [130/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.77it/s]
Hypertuning:   4%|▍         | 130/3456 [03:11<1:23:19,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.7143
➡️ Total Profit: ₹-59,556.48
➡️ Equity Curve R²: 0.9644
➡️ Monthly Consistency Score: -0.2541

=== [131/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.88it/s]
Hypertuning:   4%|▍         | 131/3456 [03:12<1:24:26,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.4967
➡️ Total Profit: ₹-32,301.76
➡️ Equity Curve R²: 0.8447
➡️ Monthly Consistency Score: -0.1276

=== [132/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.41it/s]
Hypertuning:   4%|▍         | 132/3456 [03:14<1:22:53,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 2.5128
➡️ Total Profit: ₹51,798.92
➡️ Equity Curve R²: 0.6889
➡️ Monthly Consistency Score: 0.1785

=== [133/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.07it/s]
Hypertuning:   4%|▍         | 133/3456 [03:15<1:24:45,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 1.2306
➡️ Total Profit: ₹23,441.81
➡️ Equity Curve R²: 0.5330
➡️ Monthly Consistency Score: 0.0891

=== [134/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.29it/s]
Hypertuning:   4%|▍         | 134/3456 [03:17<1:23:37,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.1315
➡️ Total Profit: ₹-5,016.71
➡️ Equity Curve R²: 0.3126
➡️ Monthly Consistency Score: -0.0200

=== [135/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.83it/s]
Hypertuning:   4%|▍         | 135/3456 [03:18<1:22:03,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: -0.0299
➡️ Total Profit: ₹-932.79
➡️ Equity Curve R²: 0.2011
➡️ Monthly Consistency Score: -0.0038

=== [136/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 88.53it/s]
Hypertuning:   4%|▍         | 136/3456 [03:20<1:23:22,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.5599
➡️ Total Profit: ₹21,284.97
➡️ Equity Curve R²: 0.0005
➡️ Monthly Consistency Score: 0.0898

=== [137/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.61it/s]
Hypertuning:   4%|▍         | 137/3456 [03:22<1:24:36,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.4655
➡️ Total Profit: ₹-30,562.45
➡️ Equity Curve R²: 0.8739
➡️ Monthly Consistency Score: -0.1018

=== [138/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.57it/s]
Hypertuning:   4%|▍         | 138/3456 [03:23<1:23:32,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.6954
➡️ Total Profit: ₹29,564.97
➡️ Equity Curve R²: 0.0105
➡️ Monthly Consistency Score: 0.1069

=== [139/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.87it/s]
Hypertuning:   4%|▍         | 139/3456 [03:24<1:22:11,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: -0.1158
➡️ Total Profit: ₹-4,355.20
➡️ Equity Curve R²: 0.4627
➡️ Monthly Consistency Score: -0.0164

=== [140/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 90.05it/s]
Hypertuning:   4%|▍         | 140/3456 [03:26<1:22:40,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 3.1776
➡️ Total Profit: ₹74,445.84
➡️ Equity Curve R²: 0.5837
➡️ Monthly Consistency Score: 0.2838

=== [141/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.19it/s]
Hypertuning:   4%|▍         | 141/3456 [03:27<1:21:43,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 2.1630
➡️ Total Profit: ₹51,792.02
➡️ Equity Curve R²: 0.2702
➡️ Monthly Consistency Score: 0.2171

=== [142/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.82it/s]
Hypertuning:   4%|▍         | 142/3456 [03:29<1:22:45,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 1.5108
➡️ Total Profit: ₹53,054.71
➡️ Equity Curve R²: 0.0127
➡️ Monthly Consistency Score: 0.2141

=== [143/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.18it/s]
Hypertuning:   4%|▍         | 143/3456 [03:31<1:24:03,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.7637
➡️ Total Profit: ₹37,142.89
➡️ Equity Curve R²: 0.1125
➡️ Monthly Consistency Score: 0.1555

=== [144/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.00it/s]
Hypertuning:   4%|▍         | 144/3456 [03:32<1:22:37,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 5.0982
➡️ Total Profit: ₹69,168.30
➡️ Equity Curve R²: 0.6485
➡️ Monthly Consistency Score: 0.3571

=== [145/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.15it/s]
Hypertuning:   4%|▍         | 145/3456 [03:34<1:24:17,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.6404
➡️ Total Profit: ₹-48,032.28
➡️ Equity Curve R²: 0.8993
➡️ Monthly Consistency Score: -0.1998

=== [146/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.37it/s]
Hypertuning:   4%|▍         | 146/3456 [03:35<1:22:56,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.7450
➡️ Total Profit: ₹-61,211.00
➡️ Equity Curve R²: 0.9574
➡️ Monthly Consistency Score: -0.2586

=== [147/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.65it/s]
Hypertuning:   4%|▍         | 147/3456 [03:36<1:21:39,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 0.3541
➡️ Total Profit: ₹15,104.26
➡️ Equity Curve R²: 0.0607
➡️ Monthly Consistency Score: 0.0512

=== [148/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.06it/s]
Hypertuning:   4%|▍         | 148/3456 [03:38<1:22:15,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 1.3428
➡️ Total Profit: ₹29,663.45
➡️ Equity Curve R²: 0.4237
➡️ Monthly Consistency Score: 0.1015

=== [149/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.52it/s]
Hypertuning:   4%|▍         | 149/3456 [03:39<1:21:29,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 0.4531
➡️ Total Profit: ₹10,838.99
➡️ Equity Curve R²: 0.1207
➡️ Monthly Consistency Score: 0.0385

=== [150/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 90.30it/s]
Hypertuning:   4%|▍         | 150/3456 [03:41<1:22:22,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.0293
➡️ Total Profit: ₹-842.23
➡️ Equity Curve R²: 0.1269
➡️ Monthly Consistency Score: -0.0034

=== [151/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.79it/s]
Hypertuning:   4%|▍         | 151/3456 [03:42<1:23:29,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.3233
➡️ Total Profit: ₹-12,336.23
➡️ Equity Curve R²: 0.6474
➡️ Monthly Consistency Score: -0.0480

=== [152/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 102.84it/s]
Hypertuning:   4%|▍         | 152/3456 [03:44<1:22:14,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 1.6514
➡️ Total Profit: ₹33,153.15
➡️ Equity Curve R²: 0.6059
➡️ Monthly Consistency Score: 0.1496

=== [153/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.04it/s]
Hypertuning:   4%|▍         | 153/3456 [03:45<1:23:21,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.3617
➡️ Total Profit: ₹44,164.28
➡️ Equity Curve R²: 0.1269
➡️ Monthly Consistency Score: 0.1641

=== [154/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.29it/s]
Hypertuning:   4%|▍         | 154/3456 [03:47<1:22:12,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 0.5661
➡️ Total Profit: ₹22,786.81
➡️ Equity Curve R²: 0.0068
➡️ Monthly Consistency Score: 0.0819

=== [155/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.81it/s]
Hypertuning:   4%|▍         | 155/3456 [03:49<1:23:45,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.6389
➡️ Total Profit: ₹17,171.68
➡️ Equity Curve R²: 0.0466
➡️ Monthly Consistency Score: 0.0733

=== [156/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.36it/s]
Hypertuning:   5%|▍         | 156/3456 [03:50<1:22:08,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 2.1251
➡️ Total Profit: ₹54,310.37
➡️ Equity Curve R²: 0.6445
➡️ Monthly Consistency Score: 0.2111

=== [157/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.46it/s]
Hypertuning:   5%|▍         | 157/3456 [03:52<1:23:33,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 1.0275
➡️ Total Profit: ₹28,485.30
➡️ Equity Curve R²: 0.0044
➡️ Monthly Consistency Score: 0.1089

=== [158/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.72it/s]
Hypertuning:   5%|▍         | 158/3456 [03:53<1:21:48,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 2.1990
➡️ Total Profit: ₹59,832.87
➡️ Equity Curve R²: 0.1445
➡️ Monthly Consistency Score: 0.2595

=== [159/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 89.94it/s]
Hypertuning:   5%|▍         | 159/3456 [03:54<1:22:47,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.4835
➡️ Total Profit: ₹50,263.91
➡️ Equity Curve R²: 0.0388
➡️ Monthly Consistency Score: 0.2170

=== [160/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.49it/s]
Hypertuning:   5%|▍         | 160/3456 [03:56<1:21:02,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 3.9251
➡️ Total Profit: ₹58,516.47
➡️ Equity Curve R²: 0.5331
➡️ Monthly Consistency Score: 0.2944

=== [161/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.99it/s]
Hypertuning:   5%|▍         | 161/3456 [03:57<1:22:46,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.6399
➡️ Total Profit: ₹-46,206.92
➡️ Equity Curve R²: 0.9210
➡️ Monthly Consistency Score: -0.1942

=== [162/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.68it/s]
Hypertuning:   5%|▍         | 162/3456 [03:59<1:21:26,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: -0.6531
➡️ Total Profit: ₹-49,291.12
➡️ Equity Curve R²: 0.9360
➡️ Monthly Consistency Score: -0.2157

=== [163/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.56it/s]
Hypertuning:   5%|▍         | 163/3456 [04:00<1:22:23,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.1649
➡️ Total Profit: ₹-7,842.16
➡️ Equity Curve R²: 0.4109
➡️ Monthly Consistency Score: -0.0285

=== [164/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.36it/s]
Hypertuning:   5%|▍         | 164/3456 [04:02<1:23:23,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 1.9130
➡️ Total Profit: ₹38,187.09
➡️ Equity Curve R²: 0.5962
➡️ Monthly Consistency Score: 0.1312

=== [165/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.04it/s]
Hypertuning:   5%|▍         | 165/3456 [04:03<1:22:43,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.7727
➡️ Total Profit: ₹16,512.28
➡️ Equity Curve R²: 0.3232
➡️ Monthly Consistency Score: 0.0586

=== [166/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.39it/s]
Hypertuning:   5%|▍         | 166/3456 [04:05<1:21:07,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 0.0931
➡️ Total Profit: ₹2,546.85
➡️ Equity Curve R²: 0.1143
➡️ Monthly Consistency Score: 0.0101

=== [167/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.72it/s]
Hypertuning:   5%|▍         | 167/3456 [04:06<1:22:05,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.2378
➡️ Total Profit: ₹-9,076.23
➡️ Equity Curve R²: 0.6722
➡️ Monthly Consistency Score: -0.0330

=== [168/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.00it/s]
Hypertuning:   5%|▍         | 168/3456 [04:08<1:23:01,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 1.6514
➡️ Total Profit: ₹33,153.15
➡️ Equity Curve R²: 0.6329
➡️ Monthly Consistency Score: 0.1492

=== [169/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.01it/s]
Hypertuning:   5%|▍         | 169/3456 [04:09<1:22:23,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 1.4284
➡️ Total Profit: ₹45,427.10
➡️ Equity Curve R²: 0.1252
➡️ Monthly Consistency Score: 0.1695

=== [170/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.38it/s]
Hypertuning:   5%|▍         | 170/3456 [04:11<1:21:07,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 0.7907
➡️ Total Profit: ₹31,828.65
➡️ Equity Curve R²: 0.0000
➡️ Monthly Consistency Score: 0.1163

=== [171/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.49it/s]
Hypertuning:   5%|▍         | 171/3456 [04:12<1:22:11,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 1.0844
➡️ Total Profit: ₹30,914.42
➡️ Equity Curve R²: 0.0004
➡️ Monthly Consistency Score: 0.1297

=== [172/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.31it/s]
Hypertuning:   5%|▍         | 172/3456 [04:14<1:23:33,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 2.5419
➡️ Total Profit: ₹64,962.20
➡️ Equity Curve R²: 0.5757
➡️ Monthly Consistency Score: 0.2576

=== [173/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.06it/s]
Hypertuning:   5%|▌         | 173/3456 [04:16<1:22:41,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.9193
➡️ Total Profit: ₹27,224.36
➡️ Equity Curve R²: 0.0276
➡️ Monthly Consistency Score: 0.1025

=== [174/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.69it/s]
Hypertuning:   5%|▌         | 174/3456 [04:17<1:21:01,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 1.8078
➡️ Total Profit: ₹55,314.71
➡️ Equity Curve R²: 0.0674
➡️ Monthly Consistency Score: 0.2316

=== [175/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 90.84it/s]
Hypertuning:   5%|▌         | 175/3456 [04:18<1:21:45,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 1.5798
➡️ Total Profit: ₹53,526.65
➡️ Equity Curve R²: 0.0215
➡️ Monthly Consistency Score: 0.2275

=== [176/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.28it/s]
Hypertuning:   5%|▌         | 176/3456 [04:20<1:22:56,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 4.0681
➡️ Total Profit: ₹60,648.29
➡️ Equity Curve R²: 0.5031
➡️ Monthly Consistency Score: 0.3000

=== [177/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.04it/s]
Hypertuning:   5%|▌         | 177/3456 [04:22<1:22:24,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.7233
➡️ Total Profit: ₹-51,319.55
➡️ Equity Curve R²: 0.9263
➡️ Monthly Consistency Score: -0.2333

=== [178/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.91it/s]
Hypertuning:   5%|▌         | 178/3456 [04:23<1:20:51,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: -0.5645
➡️ Total Profit: ₹-34,607.40
➡️ Equity Curve R²: 0.9237
➡️ Monthly Consistency Score: -0.1581

=== [179/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.58it/s]
Hypertuning:   5%|▌         | 179/3456 [04:24<1:21:46,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.1785
➡️ Total Profit: ₹-8,627.76
➡️ Equity Curve R²: 0.5663
➡️ Monthly Consistency Score: -0.0331

=== [180/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.59it/s]
Hypertuning:   5%|▌         | 180/3456 [04:26<1:23:13,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 2.6161
➡️ Total Profit: ₹53,927.10
➡️ Equity Curve R²: 0.6842
➡️ Monthly Consistency Score: 0.1846

=== [181/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 87.41it/s]
Hypertuning:   5%|▌         | 181/3456 [04:28<1:22:27,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.2552
➡️ Total Profit: ₹24,701.81
➡️ Equity Curve R²: 0.5527
➡️ Monthly Consistency Score: 0.0958

=== [182/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.42it/s]
Hypertuning:   5%|▌         | 182/3456 [04:29<1:23:18,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.3804
➡️ Total Profit: ₹14,192.37
➡️ Equity Curve R²: 0.0085
➡️ Monthly Consistency Score: 0.0530

=== [183/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.84it/s]
Hypertuning:   5%|▌         | 183/3456 [04:31<1:21:38,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.0279
➡️ Total Profit: ₹-915.90
➡️ Equity Curve R²: 0.2934
➡️ Monthly Consistency Score: -0.0038

=== [184/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.21it/s]
Hypertuning:   5%|▌         | 184/3456 [04:32<1:23:21,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 2.3941
➡️ Total Profit: ₹48,064.97
➡️ Equity Curve R²: 0.6729
➡️ Monthly Consistency Score: 0.2162

=== [185/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.52it/s]
Hypertuning:   5%|▌         | 185/3456 [04:34<1:22:17,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.4330
➡️ Total Profit: ₹-28,668.22
➡️ Equity Curve R²: 0.8583
➡️ Monthly Consistency Score: -0.0942

=== [186/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.98it/s]
Hypertuning:   5%|▌         | 186/3456 [04:35<1:20:37,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 0.4622
➡️ Total Profit: ₹22,784.97
➡️ Equity Curve R²: 0.0964
➡️ Monthly Consistency Score: 0.0857

=== [187/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 88.07it/s]
Hypertuning:   5%|▌         | 187/3456 [04:37<1:21:37,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.2051
➡️ Total Profit: ₹8,335.60
➡️ Equity Curve R²: 0.0582
➡️ Monthly Consistency Score: 0.0315

=== [188/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.47it/s]
Hypertuning:   5%|▌         | 188/3456 [04:38<1:23:05,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 2.9374
➡️ Total Profit: ₹56,926.65
➡️ Equity Curve R²: 0.4365
➡️ Monthly Consistency Score: 0.2104

=== [189/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.21it/s]
Hypertuning:   5%|▌         | 189/3456 [04:40<1:22:20,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.0257
➡️ Total Profit: ₹30,594.75
➡️ Equity Curve R²: 0.0293
➡️ Monthly Consistency Score: 0.1234

=== [190/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.86it/s]
Hypertuning:   5%|▌         | 190/3456 [04:41<1:20:47,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 1.2247
➡️ Total Profit: ₹48,538.39
➡️ Equity Curve R²: 0.0003
➡️ Monthly Consistency Score: 0.1871

=== [191/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.04it/s]
Hypertuning:   6%|▌         | 191/3456 [04:43<1:21:18,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 0.6740
➡️ Total Profit: ₹33,880.15
➡️ Equity Curve R²: 0.2445
➡️ Monthly Consistency Score: 0.1446

=== [192/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.22it/s]
Hypertuning:   6%|▌         | 192/3456 [04:44<1:22:19,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 5.8401
➡️ Total Profit: ₹71,296.48
➡️ Equity Curve R²: 0.6304
➡️ Monthly Consistency Score: 0.3567

=== [193/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.61it/s]
Hypertuning:   6%|▌         | 193/3456 [04:46<1:21:30,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.8110
➡️ Total Profit: ₹-82,390.92
➡️ Equity Curve R²: 0.9652
➡️ Monthly Consistency Score: -0.3336

=== [194/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.30it/s]
Hypertuning:   6%|▌         | 194/3456 [04:47<1:22:49,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.4425
➡️ Total Profit: ₹-20,428.71
➡️ Equity Curve R²: 0.6719
➡️ Monthly Consistency Score: -0.0726

=== [195/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.81it/s]
Hypertuning:   6%|▌         | 195/3456 [04:49<1:21:19,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.7489
➡️ Total Profit: ₹27,760.04
➡️ Equity Curve R²: 0.0154
➡️ Monthly Consistency Score: 0.0931

=== [196/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.11it/s]
Hypertuning:   6%|▌         | 196/3456 [04:50<1:19:56,  1.47s/it]

➡️ Profit-to-Drawdown Ratio: 2.3630
➡️ Total Profit: ₹44,682.71
➡️ Equity Curve R²: 0.7449
➡️ Monthly Consistency Score: 0.1517

=== [197/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.63it/s]
Hypertuning:   6%|▌         | 197/3456 [04:52<1:21:28,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.0044
➡️ Total Profit: ₹-155.87
➡️ Equity Curve R²: 0.0451
➡️ Monthly Consistency Score: -0.0005

=== [198/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.61it/s]
Hypertuning:   6%|▌         | 198/3456 [04:53<1:22:54,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.4699
➡️ Total Profit: ₹12,285.49
➡️ Equity Curve R²: 0.0005
➡️ Monthly Consistency Score: 0.0471

=== [199/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.28it/s]
Hypertuning:   6%|▌         | 199/3456 [04:55<1:21:24,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.7496
➡️ Total Profit: ₹23,514.37
➡️ Equity Curve R²: 0.0005
➡️ Monthly Consistency Score: 0.0890

=== [200/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.65it/s]
Hypertuning:   6%|▌         | 200/3456 [04:56<1:19:53,  1.47s/it]

➡️ Profit-to-Drawdown Ratio: 3.4251
➡️ Total Profit: ₹61,461.42
➡️ Equity Curve R²: 0.8480
➡️ Monthly Consistency Score: 0.2882

=== [201/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.45it/s]
Hypertuning:   6%|▌         | 201/3456 [04:58<1:21:35,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 1.2677
➡️ Total Profit: ₹41,025.09
➡️ Equity Curve R²: 0.1650
➡️ Monthly Consistency Score: 0.1511

=== [202/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.61it/s]
Hypertuning:   6%|▌         | 202/3456 [04:59<1:22:51,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 1.3634
➡️ Total Profit: ₹39,921.41
➡️ Equity Curve R²: 0.1703
➡️ Monthly Consistency Score: 0.1435

=== [203/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.01it/s]
Hypertuning:   6%|▌         | 203/3456 [05:01<1:21:08,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 1.0727
➡️ Total Profit: ₹25,331.27
➡️ Equity Curve R²: 0.0780
➡️ Monthly Consistency Score: 0.1099

=== [204/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.44it/s]
Hypertuning:   6%|▌         | 204/3456 [05:02<1:19:36,  1.47s/it]

➡️ Profit-to-Drawdown Ratio: 2.7737
➡️ Total Profit: ₹64,973.12
➡️ Equity Curve R²: 0.7765
➡️ Monthly Consistency Score: 0.2486

=== [205/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.29it/s]
Hypertuning:   6%|▌         | 205/3456 [05:04<1:21:36,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.2511
➡️ Total Profit: ₹7,274.78
➡️ Equity Curve R²: 0.0199
➡️ Monthly Consistency Score: 0.0251

=== [206/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.16it/s]
Hypertuning:   6%|▌         | 206/3456 [05:05<1:20:09,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 0.8450
➡️ Total Profit: ₹36,343.21
➡️ Equity Curve R²: 0.1843
➡️ Monthly Consistency Score: 0.1202

=== [207/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.33it/s]
Hypertuning:   6%|▌         | 207/3456 [05:07<1:20:49,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 2.0662
➡️ Total Profit: ₹53,701.17
➡️ Equity Curve R²: 0.3194
➡️ Monthly Consistency Score: 0.1856

=== [208/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.40it/s]
Hypertuning:   6%|▌         | 208/3456 [05:08<1:21:56,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 4.3013
➡️ Total Profit: ₹64,124.77
➡️ Equity Curve R²: 0.6187
➡️ Monthly Consistency Score: 0.2903

=== [209/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.53it/s]
Hypertuning:   6%|▌         | 209/3456 [05:10<1:21:24,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.8052
➡️ Total Profit: ₹-77,702.00
➡️ Equity Curve R²: 0.9653
➡️ Monthly Consistency Score: -0.3156

=== [210/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.47it/s]
Hypertuning:   6%|▌         | 210/3456 [05:11<1:22:27,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.0646
➡️ Total Profit: ₹-2,343.35
➡️ Equity Curve R²: 0.1044
➡️ Monthly Consistency Score: -0.0091

=== [211/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.10it/s]
Hypertuning:   6%|▌         | 211/3456 [05:13<1:20:55,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.4652
➡️ Total Profit: ₹18,759.92
➡️ Equity Curve R²: 0.1192
➡️ Monthly Consistency Score: 0.0663

=== [212/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.00it/s]
Hypertuning:   6%|▌         | 212/3456 [05:14<1:19:28,  1.47s/it]

➡️ Profit-to-Drawdown Ratio: 2.9111
➡️ Total Profit: ₹48,851.75
➡️ Equity Curve R²: 0.7803
➡️ Monthly Consistency Score: 0.1686

=== [213/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 86.29it/s]
Hypertuning:   6%|▌         | 213/3456 [05:16<1:21:38,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.1594
➡️ Total Profit: ₹5,173.66
➡️ Equity Curve R²: 0.0224
➡️ Monthly Consistency Score: 0.0166

=== [214/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 88.92it/s]
Hypertuning:   6%|▌         | 214/3456 [05:17<1:22:59,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: -0.2014
➡️ Total Profit: ₹-7,189.24
➡️ Equity Curve R²: 0.7302
➡️ Monthly Consistency Score: -0.0285

=== [215/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.27it/s]
Hypertuning:   6%|▌         | 215/3456 [05:19<1:21:19,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.3688
➡️ Total Profit: ₹38,140.26
➡️ Equity Curve R²: 0.1789
➡️ Monthly Consistency Score: 0.1314

=== [216/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.27it/s]
Hypertuning:   6%|▋         | 216/3456 [05:20<1:19:59,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 3.4251
➡️ Total Profit: ₹61,461.42
➡️ Equity Curve R²: 0.8480
➡️ Monthly Consistency Score: 0.2882

=== [217/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 89.20it/s]
Hypertuning:   6%|▋         | 217/3456 [05:22<1:21:52,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.4178
➡️ Total Profit: ₹-27,398.82
➡️ Equity Curve R²: 0.8491
➡️ Monthly Consistency Score: -0.0901

=== [218/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.99it/s]
Hypertuning:   6%|▋         | 218/3456 [05:23<1:23:16,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 2.0194
➡️ Total Profit: ₹59,128.66
➡️ Equity Curve R²: 0.5204
➡️ Monthly Consistency Score: 0.2271

=== [219/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.61it/s]
Hypertuning:   6%|▋         | 219/3456 [05:25<1:21:47,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 1.2920
➡️ Total Profit: ₹30,219.90
➡️ Equity Curve R²: 0.2770
➡️ Monthly Consistency Score: 0.1325

=== [220/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.56it/s]
Hypertuning:   6%|▋         | 220/3456 [05:26<1:20:44,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 2.9556
➡️ Total Profit: ₹69,233.12
➡️ Equity Curve R²: 0.8218
➡️ Monthly Consistency Score: 0.2773

=== [221/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.53it/s]
Hypertuning:   6%|▋         | 221/3456 [05:28<1:22:16,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.5124
➡️ Total Profit: ₹14,202.43
➡️ Equity Curve R²: 0.0002
➡️ Monthly Consistency Score: 0.0494

=== [222/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.42it/s]
Hypertuning:   6%|▋         | 222/3456 [05:29<1:20:44,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.7278
➡️ Total Profit: ₹32,950.45
➡️ Equity Curve R²: 0.2117
➡️ Monthly Consistency Score: 0.1054

=== [223/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.79it/s]
Hypertuning:   6%|▋         | 223/3456 [05:31<1:21:03,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 2.9358
➡️ Total Profit: ₹66,741.18
➡️ Equity Curve R²: 0.5278
➡️ Monthly Consistency Score: 0.2445

=== [224/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 90.52it/s]
Hypertuning:   6%|▋         | 224/3456 [05:32<1:22:09,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 4.9375
➡️ Total Profit: ₹64,128.41
➡️ Equity Curve R²: 0.6274
➡️ Monthly Consistency Score: 0.2947

=== [225/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 90.01it/s]
Hypertuning:   7%|▋         | 225/3456 [05:34<1:21:16,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.7583
➡️ Total Profit: ₹-65,797.58
➡️ Equity Curve R²: 0.9553
➡️ Monthly Consistency Score: -0.2635

=== [226/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 89.35it/s]
Hypertuning:   7%|▋         | 226/3456 [05:35<1:23:05,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 0.0627
➡️ Total Profit: ₹2,263.89
➡️ Equity Curve R²: 0.3746
➡️ Monthly Consistency Score: 0.0083

=== [227/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.38it/s]
Hypertuning:   7%|▋         | 227/3456 [05:37<1:21:28,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.8088
➡️ Total Profit: ₹28,141.64
➡️ Equity Curve R²: 0.0027
➡️ Monthly Consistency Score: 0.1074

=== [228/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.48it/s]
Hypertuning:   7%|▋         | 228/3456 [05:38<1:19:41,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 3.6003
➡️ Total Profit: ₹60,419.08
➡️ Equity Curve R²: 0.8596
➡️ Monthly Consistency Score: 0.2034

=== [229/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.27it/s]
Hypertuning:   7%|▋         | 229/3456 [05:40<1:21:23,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.1036
➡️ Total Profit: ₹3,328.02
➡️ Equity Curve R²: 0.0461
➡️ Monthly Consistency Score: 0.0121

=== [230/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.56it/s]
Hypertuning:   7%|▋         | 230/3456 [05:41<1:22:47,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: -0.1516
➡️ Total Profit: ₹-4,934.76
➡️ Equity Curve R²: 0.6660
➡️ Monthly Consistency Score: -0.0193

=== [231/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.88it/s]
Hypertuning:   7%|▋         | 231/3456 [05:43<1:21:01,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.7585
➡️ Total Profit: ₹18,663.74
➡️ Equity Curve R²: 0.0877
➡️ Monthly Consistency Score: 0.0726

=== [232/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.13it/s]
Hypertuning:   7%|▋         | 232/3456 [05:44<1:21:59,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 2.8828
➡️ Total Profit: ₹51,730.37
➡️ Equity Curve R²: 0.8413
➡️ Monthly Consistency Score: 0.2378

=== [233/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.28it/s]
Hypertuning:   7%|▋         | 233/3456 [05:46<1:21:07,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.3986
➡️ Total Profit: ₹-24,880.70
➡️ Equity Curve R²: 0.8518
➡️ Monthly Consistency Score: -0.0810

=== [234/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 89.28it/s]
Hypertuning:   7%|▋         | 234/3456 [05:47<1:22:34,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 2.1351
➡️ Total Profit: ₹62,515.90
➡️ Equity Curve R²: 0.3864
➡️ Monthly Consistency Score: 0.2404

=== [235/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.55it/s]
Hypertuning:   7%|▋         | 235/3456 [05:49<1:21:10,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.8099
➡️ Total Profit: ₹42,334.01
➡️ Equity Curve R²: 0.2132
➡️ Monthly Consistency Score: 0.1824

=== [236/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.87it/s]
Hypertuning:   7%|▋         | 236/3456 [05:50<1:19:56,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 4.2962
➡️ Total Profit: ₹91,493.12
➡️ Equity Curve R²: 0.8158
➡️ Monthly Consistency Score: 0.3423

=== [237/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.84it/s]
Hypertuning:   7%|▋         | 237/3456 [05:52<1:21:13,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.3673
➡️ Total Profit: ₹10,643.29
➡️ Equity Curve R²: 0.1348
➡️ Monthly Consistency Score: 0.0416

=== [238/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.18it/s]
Hypertuning:   7%|▋         | 238/3456 [05:54<1:23:20,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: 1.1865
➡️ Total Profit: ₹51,030.45
➡️ Equity Curve R²: 0.0135
➡️ Monthly Consistency Score: 0.1716

=== [239/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.64it/s]
Hypertuning:   7%|▋         | 239/3456 [05:55<1:21:26,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 4.2351
➡️ Total Profit: ₹89,735.70
➡️ Equity Curve R²: 0.8965
➡️ Monthly Consistency Score: 0.3508

=== [240/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.20it/s]
Hypertuning:   7%|▋         | 240/3456 [05:56<1:20:08,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 4.5803
➡️ Total Profit: ₹58,520.11
➡️ Equity Curve R²: 0.5782
➡️ Monthly Consistency Score: 0.2606

=== [241/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.90it/s]
Hypertuning:   7%|▋         | 241/3456 [05:58<1:21:22,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.8064
➡️ Total Profit: ₹-82,390.92
➡️ Equity Curve R²: 0.9649
➡️ Monthly Consistency Score: -0.3333

=== [242/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.45it/s]
Hypertuning:   7%|▋         | 242/3456 [06:00<1:22:37,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: -0.4558
➡️ Total Profit: ₹-21,557.79
➡️ Equity Curve R²: 0.7029
➡️ Monthly Consistency Score: -0.0758

=== [243/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.79it/s]
Hypertuning:   7%|▋         | 243/3456 [06:01<1:20:52,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.7928
➡️ Total Profit: ₹29,388.67
➡️ Equity Curve R²: 0.0070
➡️ Monthly Consistency Score: 0.0976

=== [244/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.95it/s]
Hypertuning:   7%|▋         | 244/3456 [06:02<1:19:19,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 2.3630
➡️ Total Profit: ₹44,682.71
➡️ Equity Curve R²: 0.7449
➡️ Monthly Consistency Score: 0.1517

=== [245/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.08it/s]
Hypertuning:   7%|▋         | 245/3456 [06:04<1:20:59,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.0133
➡️ Total Profit: ₹473.66
➡️ Equity Curve R²: 0.0459
➡️ Monthly Consistency Score: 0.0015

=== [246/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 88.36it/s]
Hypertuning:   7%|▋         | 246/3456 [06:06<1:22:46,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: 0.4699
➡️ Total Profit: ₹12,285.49
➡️ Equity Curve R²: 0.0005
➡️ Monthly Consistency Score: 0.0471

=== [247/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.36it/s]
Hypertuning:   7%|▋         | 247/3456 [06:07<1:21:05,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.7496
➡️ Total Profit: ₹23,514.37
➡️ Equity Curve R²: 0.0005
➡️ Monthly Consistency Score: 0.0890

=== [248/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.76it/s]
Hypertuning:   7%|▋         | 248/3456 [06:09<1:21:59,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 3.4251
➡️ Total Profit: ₹61,461.42
➡️ Equity Curve R²: 0.8480
➡️ Monthly Consistency Score: 0.2882

=== [249/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.67it/s]
Hypertuning:   7%|▋         | 249/3456 [06:10<1:21:06,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 1.2482
➡️ Total Profit: ₹40,394.62
➡️ Equity Curve R²: 0.1681
➡️ Monthly Consistency Score: 0.1489

=== [250/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.55it/s]
Hypertuning:   7%|▋         | 250/3456 [06:12<1:22:14,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 1.3634
➡️ Total Profit: ₹39,921.41
➡️ Equity Curve R²: 0.1703
➡️ Monthly Consistency Score: 0.1435

=== [251/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 87.69it/s]
Hypertuning:   7%|▋         | 251/3456 [06:13<1:20:33,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.2262
➡️ Total Profit: ₹26,959.90
➡️ Equity Curve R²: 0.1271
➡️ Monthly Consistency Score: 0.1165

=== [252/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.09it/s]
Hypertuning:   7%|▋         | 252/3456 [06:15<1:18:52,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 2.7737
➡️ Total Profit: ₹64,973.12
➡️ Equity Curve R²: 0.7765
➡️ Monthly Consistency Score: 0.2486

=== [253/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.66it/s]
Hypertuning:   7%|▋         | 253/3456 [06:16<1:20:27,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.2728
➡️ Total Profit: ₹7,904.31
➡️ Equity Curve R²: 0.0164
➡️ Monthly Consistency Score: 0.0273

=== [254/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.40it/s]
Hypertuning:   7%|▋         | 254/3456 [06:18<1:22:00,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 0.8450
➡️ Total Profit: ₹36,343.21
➡️ Equity Curve R²: 0.1843
➡️ Monthly Consistency Score: 0.1202

=== [255/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.14it/s]
Hypertuning:   7%|▋         | 255/3456 [06:19<1:20:24,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 2.0662
➡️ Total Profit: ₹53,701.17
➡️ Equity Curve R²: 0.3194
➡️ Monthly Consistency Score: 0.1856

=== [256/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.45it/s]
Hypertuning:   7%|▋         | 256/3456 [06:21<1:21:20,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 4.3013
➡️ Total Profit: ₹64,124.77
➡️ Equity Curve R²: 0.6187
➡️ Monthly Consistency Score: 0.2903

=== [257/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 86.92it/s]
Hypertuning:   7%|▋         | 257/3456 [06:22<1:20:33,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.7950
➡️ Total Profit: ₹-80,220.12
➡️ Equity Curve R²: 0.9664
➡️ Monthly Consistency Score: -0.3219

=== [258/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.85it/s]
Hypertuning:   7%|▋         | 258/3456 [06:24<1:21:42,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.2036
➡️ Total Profit: ₹-7,468.83
➡️ Equity Curve R²: 0.4462
➡️ Monthly Consistency Score: -0.0282

=== [259/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.80it/s]
Hypertuning:   7%|▋         | 259/3456 [06:25<1:20:01,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.4082
➡️ Total Profit: ₹17,128.55
➡️ Equity Curve R²: 0.1613
➡️ Monthly Consistency Score: 0.0606

=== [260/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.61it/s]
Hypertuning:   8%|▊         | 260/3456 [06:27<1:18:23,  1.47s/it]

➡️ Profit-to-Drawdown Ratio: 3.0874
➡️ Total Profit: ₹51,811.76
➡️ Equity Curve R²: 0.7947
➡️ Monthly Consistency Score: 0.1820

=== [261/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 88.63it/s]
Hypertuning:   8%|▊         | 261/3456 [06:28<1:20:06,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.0698
➡️ Total Profit: ₹2,361.31
➡️ Equity Curve R²: 0.0030
➡️ Monthly Consistency Score: 0.0076

=== [262/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.19it/s]
Hypertuning:   8%|▊         | 262/3456 [06:30<1:21:40,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.1176
➡️ Total Profit: ₹-3,800.15
➡️ Equity Curve R²: 0.6672
➡️ Monthly Consistency Score: -0.0149

=== [263/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.06it/s]
Hypertuning:   8%|▊         | 263/3456 [06:31<1:19:51,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 1.1263
➡️ Total Profit: ₹31,663.00
➡️ Equity Curve R²: 0.0048
➡️ Monthly Consistency Score: 0.1149

=== [264/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.99it/s]
Hypertuning:   8%|▊         | 264/3456 [06:33<1:20:43,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 3.5099
➡️ Total Profit: ₹62,984.08
➡️ Equity Curve R²: 0.8279
➡️ Monthly Consistency Score: 0.2907

=== [265/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.59it/s]
Hypertuning:   8%|▊         | 265/3456 [06:34<1:20:00,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 1.4154
➡️ Total Profit: ₹46,695.56
➡️ Equity Curve R²: 0.1080
➡️ Monthly Consistency Score: 0.1703

=== [266/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.42it/s]
Hypertuning:   8%|▊         | 266/3456 [06:36<1:18:35,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 2.0580
➡️ Total Profit: ₹60,257.74
➡️ Equity Curve R²: 0.5133
➡️ Monthly Consistency Score: 0.2307

=== [267/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.18it/s]
Hypertuning:   8%|▊         | 267/3456 [06:37<1:19:39,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 1.9994
➡️ Total Profit: ₹43,959.90
➡️ Equity Curve R²: 0.1756
➡️ Monthly Consistency Score: 0.1936

=== [268/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.33it/s]
Hypertuning:   8%|▊         | 268/3456 [06:39<1:20:21,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 3.0464
➡️ Total Profit: ₹71,361.30
➡️ Equity Curve R²: 0.6818
➡️ Monthly Consistency Score: 0.2749

=== [269/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.81it/s]
Hypertuning:   8%|▊         | 269/3456 [06:40<1:19:42,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.4033
➡️ Total Profit: ₹11,685.25
➡️ Equity Curve R²: 0.0149
➡️ Monthly Consistency Score: 0.0403

=== [270/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 89.49it/s]
Hypertuning:   8%|▊         | 270/3456 [06:42<1:21:11,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.8138
➡️ Total Profit: ₹34,081.37
➡️ Equity Curve R²: 0.1735
➡️ Monthly Consistency Score: 0.1113

=== [271/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.32it/s]
Hypertuning:   8%|▊         | 271/3456 [06:43<1:19:51,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 2.9358
➡️ Total Profit: ₹66,741.18
➡️ Equity Curve R²: 0.5278
➡️ Monthly Consistency Score: 0.2445

=== [272/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.13it/s]
Hypertuning:   8%|▊         | 272/3456 [06:45<1:18:02,  1.47s/it]

➡️ Profit-to-Drawdown Ratio: 4.4443
➡️ Total Profit: ₹66,256.59
➡️ Equity Curve R²: 0.6003
➡️ Monthly Consistency Score: 0.3064

=== [273/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.76it/s]
Hypertuning:   8%|▊         | 273/3456 [06:46<1:19:23,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.8323
➡️ Total Profit: ₹-86,028.71
➡️ Equity Curve R²: 0.9767
➡️ Monthly Consistency Score: -0.3486

=== [274/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.17it/s]
Hypertuning:   8%|▊         | 274/3456 [06:48<1:20:43,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.2674
➡️ Total Profit: ₹7,914.97
➡️ Equity Curve R²: 0.0206
➡️ Monthly Consistency Score: 0.0301

=== [275/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.35it/s]
Hypertuning:   8%|▊         | 275/3456 [06:49<1:19:13,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 0.8853
➡️ Total Profit: ₹35,131.17
➡️ Equity Curve R²: 0.0560
➡️ Monthly Consistency Score: 0.1246

=== [276/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.99it/s]
Hypertuning:   8%|▊         | 276/3456 [06:51<1:20:15,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 3.7272
➡️ Total Profit: ₹62,547.26
➡️ Equity Curve R²: 0.8575
➡️ Monthly Consistency Score: 0.2086

=== [277/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.13it/s]
Hypertuning:   8%|▊         | 277/3456 [06:52<1:19:32,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.2331
➡️ Total Profit: ₹8,034.60
➡️ Equity Curve R²: 0.0121
➡️ Monthly Consistency Score: 0.0273

=== [278/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.29it/s]
Hypertuning:   8%|▊         | 278/3456 [06:54<1:18:17,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: -0.2876
➡️ Total Profit: ₹-12,063.72
➡️ Equity Curve R²: 0.7791
➡️ Monthly Consistency Score: -0.0473

=== [279/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.10it/s]
Hypertuning:   8%|▊         | 279/3456 [06:55<1:19:45,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.0124
➡️ Total Profit: ₹26,772.37
➡️ Equity Curve R²: 0.1342
➡️ Monthly Consistency Score: 0.0978

=== [280/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.59it/s]
Hypertuning:   8%|▊         | 280/3456 [06:57<1:21:00,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 3.5088
➡️ Total Profit: ₹65,119.54
➡️ Equity Curve R²: 0.8818
➡️ Monthly Consistency Score: 0.2789

=== [281/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.79it/s]
Hypertuning:   8%|▊         | 281/3456 [06:58<1:20:12,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.2800
➡️ Total Profit: ₹-17,440.69
➡️ Equity Curve R²: 0.7740
➡️ Monthly Consistency Score: -0.0572

=== [282/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.20it/s]
Hypertuning:   8%|▊         | 282/3456 [07:00<1:18:33,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 1.0687
➡️ Total Profit: ₹40,948.69
➡️ Equity Curve R²: 0.0989
➡️ Monthly Consistency Score: 0.1507

=== [283/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.25it/s]
Hypertuning:   8%|▊         | 283/3456 [07:01<1:19:08,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.8643
➡️ Total Profit: ₹18,808.53
➡️ Equity Curve R²: 0.3347
➡️ Monthly Consistency Score: 0.0840

=== [284/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.46it/s]
Hypertuning:   8%|▊         | 284/3456 [07:03<1:20:17,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 3.3193
➡️ Total Profit: ₹77,753.12
➡️ Equity Curve R²: 0.7252
➡️ Monthly Consistency Score: 0.3006

=== [285/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.13it/s]
Hypertuning:   8%|▊         | 285/3456 [07:04<1:19:54,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.0331
➡️ Total Profit: ₹30,588.07
➡️ Equity Curve R²: 0.0062
➡️ Monthly Consistency Score: 0.1243

=== [286/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.77it/s]
Hypertuning:   8%|▊         | 286/3456 [07:06<1:18:34,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 1.3355
➡️ Total Profit: ₹54,421.37
➡️ Equity Curve R²: 0.0003
➡️ Monthly Consistency Score: 0.1903

=== [287/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.44it/s]
Hypertuning:   8%|▊         | 287/3456 [07:07<1:20:11,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 2.4634
➡️ Total Profit: ₹60,221.17
➡️ Equity Curve R²: 0.5469
➡️ Monthly Consistency Score: 0.2214

=== [288/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.13it/s]
Hypertuning:   8%|▊         | 288/3456 [07:09<1:18:16,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 4.4138
➡️ Total Profit: ₹56,391.93
➡️ Equity Curve R²: 0.5764
➡️ Monthly Consistency Score: 0.2486

=== [289/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.50it/s]
Hypertuning:   8%|▊         | 289/3456 [07:10<1:19:47,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.7406
➡️ Total Profit: ₹-53,624.84
➡️ Equity Curve R²: 0.8998
➡️ Monthly Consistency Score: -0.2330

=== [290/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.87it/s]
Hypertuning:   8%|▊         | 290/3456 [07:12<1:20:51,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.5095
➡️ Total Profit: ₹-27,733.44
➡️ Equity Curve R²: 0.8540
➡️ Monthly Consistency Score: -0.1219

=== [291/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 100.09it/s]
Hypertuning:   8%|▊         | 291/3456 [07:13<1:19:02,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.4052
➡️ Total Profit: ₹-21,992.30
➡️ Equity Curve R²: 0.6915
➡️ Monthly Consistency Score: -0.0934

=== [292/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.94it/s]
Hypertuning:   8%|▊         | 292/3456 [07:15<1:20:06,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.1997
➡️ Total Profit: ₹-8,762.56
➡️ Equity Curve R²: 0.5024
➡️ Monthly Consistency Score: -0.0329

=== [293/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.94it/s]
Hypertuning:   8%|▊         | 293/3456 [07:16<1:19:04,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.6132
➡️ Total Profit: ₹-23,303.08
➡️ Equity Curve R²: 0.7884
➡️ Monthly Consistency Score: -0.0926

=== [294/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.73it/s]
Hypertuning:   9%|▊         | 294/3456 [07:18<1:20:10,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.6755
➡️ Total Profit: ₹15,669.93
➡️ Equity Curve R²: 0.0121
➡️ Monthly Consistency Score: 0.0622

=== [295/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.61it/s]
Hypertuning:   9%|▊         | 295/3456 [07:19<1:18:56,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.4158
➡️ Total Profit: ₹-13,817.53
➡️ Equity Curve R²: 0.4493
➡️ Monthly Consistency Score: -0.0632

=== [296/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.78it/s]
Hypertuning:   9%|▊         | 296/3456 [07:21<1:19:55,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.4342
➡️ Total Profit: ₹8,189.22
➡️ Equity Curve R²: 0.2434
➡️ Monthly Consistency Score: 0.0339

=== [297/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 87.37it/s]
Hypertuning:   9%|▊         | 297/3456 [07:23<1:19:21,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.3926
➡️ Total Profit: ₹-23,005.87
➡️ Equity Curve R²: 0.8596
➡️ Monthly Consistency Score: -0.0831

=== [298/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.61it/s]
Hypertuning:   9%|▊         | 298/3456 [07:24<1:20:24,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.4385
➡️ Total Profit: ₹12,610.05
➡️ Equity Curve R²: 0.0006
➡️ Monthly Consistency Score: 0.0451

=== [299/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 86.84it/s]
Hypertuning:   9%|▊         | 299/3456 [07:26<1:18:49,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 1.9608
➡️ Total Profit: ₹38,359.17
➡️ Equity Curve R²: 0.4422
➡️ Monthly Consistency Score: 0.1553

=== [300/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.29it/s]
Hypertuning:   9%|▊         | 300/3456 [07:27<1:17:21,  1.47s/it]

➡️ Profit-to-Drawdown Ratio: 0.7046
➡️ Total Profit: ₹16,178.19
➡️ Equity Curve R²: 0.5826
➡️ Monthly Consistency Score: 0.0627

=== [301/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.41it/s]
Hypertuning:   9%|▊         | 301/3456 [07:28<1:18:58,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.9595
➡️ Total Profit: ₹37,091.07
➡️ Equity Curve R²: 0.0019
➡️ Monthly Consistency Score: 0.1630

=== [302/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.87it/s]
Hypertuning:   9%|▊         | 302/3456 [07:30<1:20:34,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 1.0210
➡️ Total Profit: ₹32,413.57
➡️ Equity Curve R²: 0.0016
➡️ Monthly Consistency Score: 0.1365

=== [303/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 89.82it/s]
Hypertuning:   9%|▉         | 303/3456 [07:32<1:19:14,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.1363
➡️ Total Profit: ₹7,705.42
➡️ Equity Curve R²: 0.5572
➡️ Monthly Consistency Score: 0.0316

=== [304/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.77it/s]
Hypertuning:   9%|▉         | 304/3456 [07:33<1:20:30,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 1.4067
➡️ Total Profit: ₹44,952.71
➡️ Equity Curve R²: 0.2554
➡️ Monthly Consistency Score: 0.1849

=== [305/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.28it/s]
Hypertuning:   9%|▉         | 305/3456 [07:35<1:19:37,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.7546
➡️ Total Profit: ₹-59,711.22
➡️ Equity Curve R²: 0.9041
➡️ Monthly Consistency Score: -0.2689

=== [306/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 89.60it/s]
Hypertuning:   9%|▉         | 306/3456 [07:36<1:18:08,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: -0.4896
➡️ Total Profit: ₹-26,691.60
➡️ Equity Curve R²: 0.8424
➡️ Monthly Consistency Score: -0.1126

=== [307/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.12it/s]
Hypertuning:   9%|▉         | 307/3456 [07:38<1:18:34,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.4754
➡️ Total Profit: ₹-28,124.98
➡️ Equity Curve R²: 0.8085
➡️ Monthly Consistency Score: -0.1205

=== [308/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.20it/s]
Hypertuning:   9%|▉         | 308/3456 [07:39<1:16:50,  1.46s/it]

➡️ Profit-to-Drawdown Ratio: 0.2124
➡️ Total Profit: ₹8,284.73
➡️ Equity Curve R²: 0.0000
➡️ Monthly Consistency Score: 0.0311

=== [309/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.61it/s]
Hypertuning:   9%|▉         | 309/3456 [07:41<1:18:24,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.4953
➡️ Total Profit: ₹-15,449.79
➡️ Equity Curve R²: 0.6394
➡️ Monthly Consistency Score: -0.0594

=== [310/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.83it/s]
Hypertuning:   9%|▉         | 310/3456 [07:42<1:19:36,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.3409
➡️ Total Profit: ₹10,455.45
➡️ Equity Curve R²: 0.1411
➡️ Monthly Consistency Score: 0.0419

=== [311/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.31it/s]
Hypertuning:   9%|▉         | 311/3456 [07:44<1:18:30,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.1808
➡️ Total Profit: ₹-5,689.27
➡️ Equity Curve R²: 0.3281
➡️ Monthly Consistency Score: -0.0264

=== [312/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.62it/s]
Hypertuning:   9%|▉         | 312/3456 [07:45<1:20:03,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.2636
➡️ Total Profit: ₹-7,942.60
➡️ Equity Curve R²: 0.4362
➡️ Monthly Consistency Score: -0.0316

=== [313/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.53it/s]
Hypertuning:   9%|▉         | 313/3456 [07:47<1:19:02,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.4308
➡️ Total Profit: ₹-27,411.64
➡️ Equity Curve R²: 0.8701
➡️ Monthly Consistency Score: -0.0978

=== [314/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.57it/s]
Hypertuning:   9%|▉         | 314/3456 [07:48<1:20:47,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 0.8766
➡️ Total Profit: ₹21,648.21
➡️ Equity Curve R²: 0.1860
➡️ Monthly Consistency Score: 0.0813

=== [315/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.99it/s]
Hypertuning:   9%|▉         | 315/3456 [07:50<1:19:12,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.0454
➡️ Total Profit: ₹36,382.48
➡️ Equity Curve R²: 0.0946
➡️ Monthly Consistency Score: 0.1471

=== [316/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.11it/s]
Hypertuning:   9%|▉         | 316/3456 [07:51<1:17:27,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 0.7975
➡️ Total Profit: ₹18,310.01
➡️ Equity Curve R²: 0.5992
➡️ Monthly Consistency Score: 0.0707

=== [317/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.78it/s]
Hypertuning:   9%|▉         | 317/3456 [07:53<1:18:51,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.0747
➡️ Total Profit: ₹3,922.40
➡️ Equity Curve R²: 0.5968
➡️ Monthly Consistency Score: 0.0160

=== [318/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.65it/s]
Hypertuning:   9%|▉         | 318/3456 [07:54<1:17:20,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 1.0566
➡️ Total Profit: ₹33,544.49
➡️ Equity Curve R²: 0.0002
➡️ Monthly Consistency Score: 0.1398

=== [319/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.62it/s]
Hypertuning:   9%|▉         | 319/3456 [07:56<1:18:13,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.2058
➡️ Total Profit: ₹10,968.16
➡️ Equity Curve R²: 0.5614
➡️ Monthly Consistency Score: 0.0453

=== [320/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 87.84it/s]
Hypertuning:   9%|▉         | 320/3456 [07:57<1:19:44,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 1.7214
➡️ Total Profit: ₹51,344.53
➡️ Equity Curve R²: 0.3149
➡️ Monthly Consistency Score: 0.2087

=== [321/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.47it/s]
Hypertuning:   9%|▉         | 321/3456 [07:59<1:18:45,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.7604
➡️ Total Profit: ₹-63,838.55
➡️ Equity Curve R²: 0.8860
➡️ Monthly Consistency Score: -0.2870

=== [322/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.16it/s]
Hypertuning:   9%|▉         | 322/3456 [08:00<1:20:23,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 0.0125
➡️ Total Profit: ₹519.33
➡️ Equity Curve R²: 0.3340
➡️ Monthly Consistency Score: 0.0020

=== [323/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.34it/s]
Hypertuning:   9%|▉         | 323/3456 [08:02<1:18:42,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.5293
➡️ Total Profit: ₹-39,599.62
➡️ Equity Curve R²: 0.8563
➡️ Monthly Consistency Score: -0.1642

=== [324/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.79it/s]
Hypertuning:   9%|▉         | 324/3456 [08:03<1:17:07,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: -0.3460
➡️ Total Profit: ₹-13,015.28
➡️ Equity Curve R²: 0.4011
➡️ Monthly Consistency Score: -0.0525

=== [325/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.52it/s]
Hypertuning:   9%|▉         | 325/3456 [08:05<1:18:53,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.0307
➡️ Total Profit: ₹809.02
➡️ Equity Curve R²: 0.4146
➡️ Monthly Consistency Score: 0.0034

=== [326/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.12it/s]
Hypertuning:   9%|▉         | 326/3456 [08:06<1:20:46,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: 0.3283
➡️ Total Profit: ₹9,326.37
➡️ Equity Curve R²: 0.1759
➡️ Monthly Consistency Score: 0.0369

=== [327/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.02it/s]
Hypertuning:   9%|▉         | 327/3456 [08:08<1:19:17,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.1932
➡️ Total Profit: ₹5,679.37
➡️ Equity Curve R²: 0.0274
➡️ Monthly Consistency Score: 0.0234

=== [328/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.45it/s]
Hypertuning:   9%|▉         | 328/3456 [08:09<1:18:00,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.0737
➡️ Total Profit: ₹-1,547.14
➡️ Equity Curve R²: 0.0848
➡️ Monthly Consistency Score: -0.0062

=== [329/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.14it/s]
Hypertuning:  10%|▉         | 329/3456 [08:11<1:19:10,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.5174
➡️ Total Profit: ₹-37,486.94
➡️ Equity Curve R²: 0.8972
➡️ Monthly Consistency Score: -0.1307

=== [330/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.11it/s]
Hypertuning:  10%|▉         | 330/3456 [08:12<1:20:19,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 1.3799
➡️ Total Profit: ₹34,079.13
➡️ Equity Curve R²: 0.0750
➡️ Monthly Consistency Score: 0.1294

=== [331/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.85it/s]
Hypertuning:  10%|▉         | 331/3456 [08:14<1:18:41,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.8112
➡️ Total Profit: ₹28,233.85
➡️ Equity Curve R²: 0.0184
➡️ Monthly Consistency Score: 0.1140

=== [332/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.89it/s]
Hypertuning:  10%|▉         | 332/3456 [08:15<1:19:51,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 1.3034
➡️ Total Profit: ₹29,925.47
➡️ Equity Curve R²: 0.7090
➡️ Monthly Consistency Score: 0.1108

=== [333/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.09it/s]
Hypertuning:  10%|▉         | 333/3456 [08:17<1:19:04,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.2152
➡️ Total Profit: ₹10,222.40
➡️ Equity Curve R²: 0.4612
➡️ Monthly Consistency Score: 0.0408

=== [334/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.36it/s]
Hypertuning:  10%|▉         | 334/3456 [08:19<1:20:35,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: 1.0211
➡️ Total Profit: ₹32,415.41
➡️ Equity Curve R²: 0.0022
➡️ Monthly Consistency Score: 0.1369

=== [335/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.50it/s]
Hypertuning:  10%|▉         | 335/3456 [08:20<1:18:58,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.2058
➡️ Total Profit: ₹10,968.16
➡️ Equity Curve R²: 0.5199
➡️ Monthly Consistency Score: 0.0455

=== [336/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.84it/s]
Hypertuning:  10%|▉         | 336/3456 [08:21<1:17:29,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 0.4662
➡️ Total Profit: ₹20,956.35
➡️ Equity Curve R²: 0.3165
➡️ Monthly Consistency Score: 0.0817

=== [337/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.20it/s]
Hypertuning:  10%|▉         | 337/3456 [08:23<1:18:56,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.7103
➡️ Total Profit: ₹-47,607.05
➡️ Equity Curve R²: 0.8665
➡️ Monthly Consistency Score: -0.2063

=== [338/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.93it/s]
Hypertuning:  10%|▉         | 338/3456 [08:25<1:19:54,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: -0.5530
➡️ Total Profit: ₹-29,477.04
➡️ Equity Curve R²: 0.8472
➡️ Monthly Consistency Score: -0.1296

=== [339/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.34it/s]
Hypertuning:  10%|▉         | 339/3456 [08:26<1:18:08,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.4281
➡️ Total Profit: ₹-23,233.61
➡️ Equity Curve R²: 0.7057
➡️ Monthly Consistency Score: -0.0985

=== [340/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.23it/s]
Hypertuning:  10%|▉         | 340/3456 [08:28<1:19:08,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.2368
➡️ Total Profit: ₹-10,894.38
➡️ Equity Curve R²: 0.5491
➡️ Monthly Consistency Score: -0.0413

=== [341/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.49it/s]
Hypertuning:  10%|▉         | 341/3456 [08:29<1:18:11,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.5397
➡️ Total Profit: ₹-17,970.73
➡️ Equity Curve R²: 0.6786
➡️ Monthly Consistency Score: -0.0692

=== [342/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.68it/s]
Hypertuning:  10%|▉         | 342/3456 [08:30<1:17:03,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 0.6755
➡️ Total Profit: ₹15,669.93
➡️ Equity Curve R²: 0.0121
➡️ Monthly Consistency Score: 0.0622

=== [343/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.82it/s]
Hypertuning:  10%|▉         | 343/3456 [08:32<1:17:49,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.4158
➡️ Total Profit: ₹-13,817.53
➡️ Equity Curve R²: 0.4493
➡️ Monthly Consistency Score: -0.0632

=== [344/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.22it/s]
Hypertuning:  10%|▉         | 344/3456 [08:33<1:16:39,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 0.4342
➡️ Total Profit: ₹8,189.22
➡️ Equity Curve R²: 0.2434
➡️ Monthly Consistency Score: 0.0339

=== [345/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.51it/s]
Hypertuning:  10%|▉         | 345/3456 [08:35<1:18:21,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.3860
➡️ Total Profit: ₹-22,374.46
➡️ Equity Curve R²: 0.8575
➡️ Monthly Consistency Score: -0.0809

=== [346/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.73it/s]
Hypertuning:  10%|█         | 346/3456 [08:37<1:18:56,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.4385
➡️ Total Profit: ₹12,610.05
➡️ Equity Curve R²: 0.0006
➡️ Monthly Consistency Score: 0.0451

=== [347/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)
<ipython-input-10-980624002>:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_data['Signal'] = temp_data['Signal'].astype(int)

100%|██████████| 1/1 [00:00<00:00, 98.69it/s]
Hypertuning:  10%|█         | 347/3456 [08:38<1:17:21,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 1.9608
➡️ Total Profit: ₹38,359.17
➡️ Equity Curve R²: 0.4422
➡️ Monthly Consistency Score: 0.1553

=== [348/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 90.55it/s]
Hypertuning:  10%|█         | 348/3456 [08:40<1:18:42,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.7046
➡️ Total Profit: ₹16,178.19
➡️ Equity Curve R²: 0.5826
➡️ Monthly Consistency Score: 0.0627

=== [349/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.04it/s]
Hypertuning:  10%|█         | 349/3456 [08:41<1:17:37,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.9595
➡️ Total Profit: ₹37,091.07
➡️ Equity Curve R²: 0.0019
➡️ Monthly Consistency Score: 0.1630

=== [350/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.32it/s]
Hypertuning:  10%|█         | 350/3456 [08:43<1:18:54,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 1.0210
➡️ Total Profit: ₹32,413.57
➡️ Equity Curve R²: 0.0016
➡️ Monthly Consistency Score: 0.1365

=== [351/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.36it/s]
Hypertuning:  10%|█         | 351/3456 [08:44<1:17:29,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.1363
➡️ Total Profit: ₹7,705.42
➡️ Equity Curve R²: 0.5572
➡️ Monthly Consistency Score: 0.0316

=== [352/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.07it/s]
Hypertuning:  10%|█         | 352/3456 [08:46<1:18:31,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 1.4067
➡️ Total Profit: ₹44,952.71
➡️ Equity Curve R²: 0.2554
➡️ Monthly Consistency Score: 0.1849

=== [353/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.32it/s]
Hypertuning:  10%|█         | 353/3456 [08:47<1:17:59,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.8073
➡️ Total Profit: ₹-62,853.51
➡️ Equity Curve R²: 0.9099
➡️ Monthly Consistency Score: -0.2726

=== [354/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.72it/s]
Hypertuning:  10%|█         | 354/3456 [08:49<1:19:23,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: -0.1531
➡️ Total Profit: ₹-8,426.07
➡️ Equity Curve R²: 0.6400
➡️ Monthly Consistency Score: -0.0331

=== [355/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.96it/s]
Hypertuning:  10%|█         | 355/3456 [08:50<1:17:45,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.2160
➡️ Total Profit: ₹-11,822.24
➡️ Equity Curve R²: 0.7377
➡️ Monthly Consistency Score: -0.0499

=== [356/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.14it/s]
Hypertuning:  10%|█         | 356/3456 [08:52<1:18:43,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.0640
➡️ Total Profit: ₹2,544.73
➡️ Equity Curve R²: 0.0090
➡️ Monthly Consistency Score: 0.0100

=== [357/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.50it/s]
Hypertuning:  10%|█         | 357/3456 [08:53<1:17:58,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.5585
➡️ Total Profit: ₹-18,262.14
➡️ Equity Curve R²: 0.7133
➡️ Monthly Consistency Score: -0.0727

=== [358/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.58it/s]
Hypertuning:  10%|█         | 358/3456 [08:55<1:19:07,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.2775
➡️ Total Profit: ₹8,197.29
➡️ Equity Curve R²: 0.2297
➡️ Monthly Consistency Score: 0.0323

=== [359/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.20it/s]
Hypertuning:  10%|█         | 359/3456 [08:56<1:17:37,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.1378
➡️ Total Profit: ₹4,050.73
➡️ Equity Curve R²: 0.0014
➡️ Monthly Consistency Score: 0.0169

=== [360/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.63it/s]
Hypertuning:  10%|█         | 360/3456 [08:58<1:19:01,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.7671
➡️ Total Profit: ₹16,098.39
➡️ Equity Curve R²: 0.0588
➡️ Monthly Consistency Score: 0.0680

=== [361/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.58it/s]
Hypertuning:  10%|█         | 361/3456 [08:59<1:18:47,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.4755
➡️ Total Profit: ₹-30,560.23
➡️ Equity Curve R²: 0.8801
➡️ Monthly Consistency Score: -0.1101

=== [362/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 86.87it/s]
Hypertuning:  10%|█         | 362/3456 [09:01<1:19:52,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: 1.3799
➡️ Total Profit: ₹34,079.13
➡️ Equity Curve R²: 0.0750
➡️ Monthly Consistency Score: 0.1294

=== [363/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 101.64it/s]
Hypertuning:  11%|█         | 363/3456 [09:02<1:18:03,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.0454
➡️ Total Profit: ₹36,382.48
➡️ Equity Curve R²: 0.0946
➡️ Monthly Consistency Score: 0.1471

=== [364/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.40it/s]
Hypertuning:  11%|█         | 364/3456 [09:04<1:16:48,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 0.7975
➡️ Total Profit: ₹18,310.01
➡️ Equity Curve R²: 0.5992
➡️ Monthly Consistency Score: 0.0707

=== [365/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.10it/s]
Hypertuning:  11%|█         | 365/3456 [09:05<1:18:13,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.0627
➡️ Total Profit: ₹3,292.87
➡️ Equity Curve R²: 0.5776
➡️ Monthly Consistency Score: 0.0135

=== [366/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.60it/s]
Hypertuning:  11%|█         | 366/3456 [09:07<1:16:50,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 1.0566
➡️ Total Profit: ₹33,544.49
➡️ Equity Curve R²: 0.0002
➡️ Monthly Consistency Score: 0.1398

=== [367/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 88.67it/s]
Hypertuning:  11%|█         | 367/3456 [09:08<1:17:49,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.1651
➡️ Total Profit: ₹9,336.79
➡️ Equity Curve R²: 0.5658
➡️ Monthly Consistency Score: 0.0378

=== [368/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.75it/s]
Hypertuning:  11%|█         | 368/3456 [09:10<1:19:29,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 0.2959
➡️ Total Profit: ₹14,564.52
➡️ Equity Curve R²: 0.4861
➡️ Monthly Consistency Score: 0.0571

=== [369/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.94it/s]
Hypertuning:  11%|█         | 369/3456 [09:11<1:18:55,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.7383
➡️ Total Profit: ₹-63,844.19
➡️ Equity Curve R²: 0.8621
➡️ Monthly Consistency Score: -0.2825

=== [370/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.07it/s]
Hypertuning:  11%|█         | 370/3456 [09:13<1:19:59,  1.56s/it]

➡️ Profit-to-Drawdown Ratio: -0.3502
➡️ Total Profit: ₹-18,087.79
➡️ Equity Curve R²: 0.6333
➡️ Monthly Consistency Score: -0.0756

=== [371/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.79it/s]
Hypertuning:  11%|█         | 371/3456 [09:15<1:18:14,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.3652
➡️ Total Profit: ₹-23,302.36
➡️ Equity Curve R²: 0.7847
➡️ Monthly Consistency Score: -0.0975

=== [372/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.72it/s]
Hypertuning:  11%|█         | 372/3456 [09:16<1:16:47,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: -0.4663
➡️ Total Profit: ₹-28,021.70
➡️ Equity Curve R²: 0.6909
➡️ Monthly Consistency Score: -0.1065

=== [373/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.57it/s]
Hypertuning:  11%|█         | 373/3456 [09:18<1:18:03,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.2344
➡️ Total Profit: ₹-6,757.56
➡️ Equity Curve R²: 0.4493
➡️ Monthly Consistency Score: -0.0280

=== [374/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.48it/s]
Hypertuning:  11%|█         | 374/3456 [09:19<1:19:06,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 1.2571
➡️ Total Profit: ₹28,964.77
➡️ Equity Curve R²: 0.4943
➡️ Monthly Consistency Score: 0.1219

=== [375/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 86.93it/s]
Hypertuning:  11%|█         | 375/3456 [09:21<1:17:36,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.2604
➡️ Total Profit: ₹7,268.00
➡️ Equity Curve R²: 0.0425
➡️ Monthly Consistency Score: 0.0297

=== [376/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 89.20it/s]
Hypertuning:  11%|█         | 376/3456 [09:22<1:15:55,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 0.7884
➡️ Total Profit: ₹21,582.03
➡️ Equity Curve R²: 0.0541
➡️ Monthly Consistency Score: 0.0877

=== [377/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.14it/s]
Hypertuning:  11%|█         | 377/3456 [09:24<1:17:49,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.4907
➡️ Total Profit: ₹-33,077.41
➡️ Equity Curve R²: 0.8908
➡️ Monthly Consistency Score: -0.1126

=== [378/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.72it/s]
Hypertuning:  11%|█         | 378/3456 [09:25<1:18:59,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 1.6545
➡️ Total Profit: ₹40,860.97
➡️ Equity Curve R²: 0.2627
➡️ Monthly Consistency Score: 0.1585

=== [379/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.53it/s]
Hypertuning:  11%|█         | 379/3456 [09:27<1:17:21,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.5744
➡️ Total Profit: ₹23,342.48
➡️ Equity Curve R²: 0.0013
➡️ Monthly Consistency Score: 0.0944

=== [380/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.24it/s]
Hypertuning:  11%|█         | 380/3456 [09:28<1:18:12,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 1.2105
➡️ Total Profit: ₹27,793.65
➡️ Equity Curve R²: 0.6594
➡️ Monthly Consistency Score: 0.1011

=== [381/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.39it/s]
Hypertuning:  11%|█         | 381/3456 [09:30<1:17:26,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.1502
➡️ Total Profit: ₹7,704.28
➡️ Equity Curve R²: 0.5663
➡️ Monthly Consistency Score: 0.0304

=== [382/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.85it/s]
Hypertuning:  11%|█         | 382/3456 [09:31<1:18:43,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 0.8904
➡️ Total Profit: ₹31,286.33
➡️ Equity Curve R²: 0.0243
➡️ Monthly Consistency Score: 0.1275

=== [383/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.90it/s]
Hypertuning:  11%|█         | 383/3456 [09:33<1:17:14,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.2843
➡️ Total Profit: ₹14,225.43
➡️ Equity Curve R²: 0.4856
➡️ Monthly Consistency Score: 0.0600

=== [384/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 90.69it/s]
Hypertuning:  11%|█         | 384/3456 [09:34<1:15:54,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 0.3998
➡️ Total Profit: ₹18,824.53
➡️ Equity Curve R²: 0.3769
➡️ Monthly Consistency Score: 0.0729

=== [385/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.29it/s]
Hypertuning:  11%|█         | 385/3456 [09:36<1:17:51,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.7576
➡️ Total Profit: ₹-56,152.51
➡️ Equity Curve R²: 0.9496
➡️ Monthly Consistency Score: -0.2599

=== [386/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.32it/s]
Hypertuning:  11%|█         | 386/3456 [09:37<1:19:09,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: -0.6456
➡️ Total Profit: ₹-44,345.80
➡️ Equity Curve R²: 0.9385
➡️ Monthly Consistency Score: -0.1835

=== [387/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.58it/s]
Hypertuning:  11%|█         | 387/3456 [09:39<1:17:17,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.0860
➡️ Total Profit: ₹-5,763.18
➡️ Equity Curve R²: 0.6019
➡️ Monthly Consistency Score: -0.0214

=== [388/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.17it/s]
Hypertuning:  11%|█         | 388/3456 [09:40<1:15:54,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 0.3394
➡️ Total Profit: ₹11,056.13
➡️ Equity Curve R²: 0.3314
➡️ Monthly Consistency Score: 0.0453

=== [389/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.57it/s]
Hypertuning:  11%|█▏        | 389/3456 [09:42<1:17:13,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.2070
➡️ Total Profit: ₹5,803.25
➡️ Equity Curve R²: 0.0437
➡️ Monthly Consistency Score: 0.0236

=== [390/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.59it/s]
Hypertuning:  11%|█▏        | 390/3456 [09:43<1:18:20,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.2239
➡️ Total Profit: ₹-7,976.96
➡️ Equity Curve R²: 0.3757
➡️ Monthly Consistency Score: -0.0306

=== [391/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.51it/s]
Hypertuning:  11%|█▏        | 391/3456 [09:45<1:16:40,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.1304
➡️ Total Profit: ₹-4,095.16
➡️ Equity Curve R²: 0.4653
➡️ Monthly Consistency Score: -0.0163

=== [392/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.03it/s]
Hypertuning:  11%|█▏        | 392/3456 [09:46<1:17:45,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.8368
➡️ Total Profit: ₹20,362.03
➡️ Equity Curve R²: 0.0162
➡️ Monthly Consistency Score: 0.0933

=== [393/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.15it/s]
Hypertuning:  11%|█▏        | 393/3456 [09:48<1:17:09,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.2869
➡️ Total Profit: ₹-15,381.33
➡️ Equity Curve R²: 0.8044
➡️ Monthly Consistency Score: -0.0581

=== [394/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.30it/s]
Hypertuning:  11%|█▏        | 394/3456 [09:49<1:16:31,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 1.3081
➡️ Total Profit: ₹37,646.69
➡️ Equity Curve R²: 0.3905
➡️ Monthly Consistency Score: 0.1464

=== [395/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.70it/s]
Hypertuning:  11%|█▏        | 395/3456 [09:51<1:17:05,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.4996
➡️ Total Profit: ₹15,188.37
➡️ Equity Curve R²: 0.0017
➡️ Monthly Consistency Score: 0.0638

=== [396/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.96it/s]
Hypertuning:  11%|█▏        | 396/3456 [09:52<1:17:46,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 1.2798
➡️ Total Profit: ₹38,447.47
➡️ Equity Curve R²: 0.0005
➡️ Monthly Consistency Score: 0.1503

=== [397/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.20it/s]
Hypertuning:  11%|█▏        | 397/3456 [09:54<1:16:58,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.6910
➡️ Total Profit: ₹48,643.43
➡️ Equity Curve R²: 0.1008
➡️ Monthly Consistency Score: 0.2026

=== [398/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.11it/s]
Hypertuning:  12%|█▏        | 398/3456 [09:55<1:18:14,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 1.3819
➡️ Total Profit: ₹48,532.87
➡️ Equity Curve R²: 0.0170
➡️ Monthly Consistency Score: 0.1994

=== [399/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.18it/s]
Hypertuning:  12%|█▏        | 399/3456 [09:57<1:16:48,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 2.8534
➡️ Total Profit: ₹59,954.67
➡️ Equity Curve R²: 0.5112
➡️ Monthly Consistency Score: 0.2692

=== [400/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.55it/s]
Hypertuning:  12%|█▏        | 400/3456 [09:58<1:15:14,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 2.1576
➡️ Total Profit: ₹58,512.83
➡️ Equity Curve R²: 0.2949
➡️ Monthly Consistency Score: 0.2650

=== [401/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.04it/s]
Hypertuning:  12%|█▏        | 401/3456 [10:00<1:16:59,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.7514
➡️ Total Profit: ₹-56,215.74
➡️ Equity Curve R²: 0.9482
➡️ Monthly Consistency Score: -0.2583

=== [402/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 89.42it/s]
Hypertuning:  12%|█▏        | 402/3456 [10:01<1:18:29,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: -0.5399
➡️ Total Profit: ₹-30,607.64
➡️ Equity Curve R²: 0.9142
➡️ Monthly Consistency Score: -0.1265

=== [403/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.04it/s]
Hypertuning:  12%|█▏        | 403/3456 [10:03<1:16:40,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.0144
➡️ Total Profit: ₹-871.93
➡️ Equity Curve R²: 0.4878
➡️ Monthly Consistency Score: -0.0032

=== [404/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.10it/s]
Hypertuning:  12%|█▏        | 404/3456 [10:05<1:18:21,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 0.1583
➡️ Total Profit: ₹4,667.75
➡️ Equity Curve R²: 0.1261
➡️ Monthly Consistency Score: 0.0192

=== [405/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.71it/s]
Hypertuning:  12%|█▏        | 405/3456 [10:06<1:17:29,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.6047
➡️ Total Profit: ₹14,287.01
➡️ Equity Curve R²: 0.3757
➡️ Monthly Consistency Score: 0.0570

=== [406/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.54it/s]
Hypertuning:  12%|█▏        | 406/3456 [10:08<1:18:39,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: -0.2623
➡️ Total Profit: ₹-10,236.96
➡️ Equity Curve R²: 0.5082
➡️ Monthly Consistency Score: -0.0389

=== [407/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.28it/s]
Hypertuning:  12%|█▏        | 407/3456 [10:09<1:17:04,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.1238
➡️ Total Profit: ₹-4,092.42
➡️ Equity Curve R²: 0.5509
➡️ Monthly Consistency Score: -0.0163

=== [408/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.92it/s]
Hypertuning:  12%|█▏        | 408/3456 [10:10<1:15:32,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 0.4014
➡️ Total Profit: ₹10,622.03
➡️ Equity Curve R²: 0.0080
➡️ Monthly Consistency Score: 0.0496

=== [409/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.41it/s]
Hypertuning:  12%|█▏        | 409/3456 [10:12<1:17:13,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.2951
➡️ Total Profit: ₹-16,005.23
➡️ Equity Curve R²: 0.8131
➡️ Monthly Consistency Score: -0.0599

=== [410/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.73it/s]
Hypertuning:  12%|█▏        | 410/3456 [10:14<1:18:56,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: 1.3081
➡️ Total Profit: ₹37,646.69
➡️ Equity Curve R²: 0.3905
➡️ Monthly Consistency Score: 0.1464

=== [411/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.12it/s]
Hypertuning:  12%|█▏        | 411/3456 [10:15<1:17:29,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.6704
➡️ Total Profit: ₹26,607.96
➡️ Equity Curve R²: 0.0211
➡️ Monthly Consistency Score: 0.1070

=== [412/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.07it/s]
Hypertuning:  12%|█▏        | 412/3456 [10:17<1:16:26,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 2.2787
➡️ Total Profit: ₹51,227.47
➡️ Equity Curve R²: 0.4223
➡️ Monthly Consistency Score: 0.2100

=== [413/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.78it/s]
Hypertuning:  12%|█▏        | 413/3456 [10:18<1:17:38,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.7803
➡️ Total Profit: ₹24,921.46
➡️ Equity Curve R²: 0.0724
➡️ Monthly Consistency Score: 0.0984

=== [414/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.48it/s]
Hypertuning:  12%|█▏        | 414/3456 [10:20<1:16:43,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.3077
➡️ Total Profit: ₹47,403.79
➡️ Equity Curve R²: 0.0091
➡️ Monthly Consistency Score: 0.1848

=== [415/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.47it/s]
Hypertuning:  12%|█▏        | 415/3456 [10:21<1:17:03,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.6770
➡️ Total Profit: ₹30,614.67
➡️ Equity Curve R²: 0.1146
➡️ Monthly Consistency Score: 0.1208

=== [416/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.53it/s]
Hypertuning:  12%|█▏        | 416/3456 [10:23<1:15:21,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 1.4557
➡️ Total Profit: ₹46,516.35
➡️ Equity Curve R²: 0.1581
➡️ Monthly Consistency Score: 0.2119

=== [417/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.65it/s]
Hypertuning:  12%|█▏        | 417/3456 [10:24<1:16:48,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.7962
➡️ Total Profit: ₹-65,031.33
➡️ Equity Curve R²: 0.9563
➡️ Monthly Consistency Score: -0.2896

=== [418/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.62it/s]
Hypertuning:  12%|█▏        | 418/3456 [10:26<1:18:18,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: -0.5000
➡️ Total Profit: ₹-28,956.64
➡️ Equity Curve R²: 0.8813
➡️ Monthly Consistency Score: -0.1119

=== [419/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.48it/s]
Hypertuning:  12%|█▏        | 419/3456 [10:27<1:16:40,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.4367
➡️ Total Profit: ₹-31,914.80
➡️ Equity Curve R²: 0.6274
➡️ Monthly Consistency Score: -0.1147

=== [420/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.13it/s]
Hypertuning:  12%|█▏        | 420/3456 [10:29<1:17:53,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 0.8369
➡️ Total Profit: ₹24,669.67
➡️ Equity Curve R²: 0.3922
➡️ Monthly Consistency Score: 0.1048

=== [421/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.07it/s]
Hypertuning:  12%|█▏        | 421/3456 [10:30<1:16:59,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.7730
➡️ Total Profit: ₹17,775.60
➡️ Equity Curve R²: 0.4041
➡️ Monthly Consistency Score: 0.0731

=== [422/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.74it/s]
Hypertuning:  12%|█▏        | 422/3456 [10:32<1:17:22,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.2701
➡️ Total Profit: ₹-10,233.28
➡️ Equity Curve R²: 0.5033
➡️ Monthly Consistency Score: -0.0390

=== [423/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.54it/s]
Hypertuning:  12%|█▏        | 423/3456 [10:33<1:15:49,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.1047
➡️ Total Profit: ₹2,404.47
➡️ Equity Curve R²: 0.0137
➡️ Monthly Consistency Score: 0.0090

=== [424/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.92it/s]
Hypertuning:  12%|█▏        | 424/3456 [10:35<1:16:29,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.5240
➡️ Total Profit: ₹12,750.21
➡️ Equity Curve R²: 0.0023
➡️ Monthly Consistency Score: 0.0594

=== [425/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 86.20it/s]
Hypertuning:  12%|█▏        | 425/3456 [10:36<1:16:05,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.3627
➡️ Total Profit: ₹-21,044.29
➡️ Equity Curve R²: 0.8396
➡️ Monthly Consistency Score: -0.0775

=== [426/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.26it/s]
Hypertuning:  12%|█▏        | 426/3456 [10:38<1:17:25,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 1.4098
➡️ Total Profit: ₹42,166.69
➡️ Equity Curve R²: 0.2036
➡️ Monthly Consistency Score: 0.1664

=== [427/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.27it/s]
Hypertuning:  12%|█▏        | 427/3456 [10:39<1:15:59,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.8257
➡️ Total Profit: ₹35,464.81
➡️ Equity Curve R²: 0.0003
➡️ Monthly Consistency Score: 0.1395

=== [428/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.86it/s]
Hypertuning:  12%|█▏        | 428/3456 [10:41<1:16:44,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 4.0721
➡️ Total Profit: ₹60,707.47
➡️ Equity Curve R²: 0.5636
➡️ Monthly Consistency Score: 0.2355

=== [429/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 82.32it/s]
Hypertuning:  12%|█▏        | 429/3456 [10:42<1:15:48,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.7508
➡️ Total Profit: ₹24,924.28
➡️ Equity Curve R²: 0.1105
➡️ Monthly Consistency Score: 0.0973

=== [430/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.39it/s]
Hypertuning:  12%|█▏        | 430/3456 [10:44<1:16:41,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 1.2604
➡️ Total Profit: ₹48,534.71
➡️ Equity Curve R²: 0.0000
➡️ Monthly Consistency Score: 0.1894

=== [431/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.07it/s]
Hypertuning:  12%|█▏        | 431/3456 [10:45<1:15:17,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 0.4972
➡️ Total Profit: ₹25,726.04
➡️ Equity Curve R²: 0.2617
➡️ Monthly Consistency Score: 0.1104

=== [432/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.46it/s]
Hypertuning:  12%|█▎        | 432/3456 [10:47<1:16:32,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.9391
➡️ Total Profit: ₹41,472.83
➡️ Equity Curve R²: 0.0016
➡️ Monthly Consistency Score: 0.1621

=== [433/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.86it/s]
Hypertuning:  13%|█▎        | 433/3456 [10:48<1:15:57,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.7490
➡️ Total Profit: ₹-53,632.51
➡️ Equity Curve R²: 0.9462
➡️ Monthly Consistency Score: -0.2462

=== [434/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.64it/s]
Hypertuning:  13%|█▎        | 434/3456 [10:50<1:16:58,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.6645
➡️ Total Profit: ₹-43,745.84
➡️ Equity Curve R²: 0.9446
➡️ Monthly Consistency Score: -0.1834

=== [435/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.67it/s]
Hypertuning:  13%|█▎        | 435/3456 [10:51<1:15:22,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.0882
➡️ Total Profit: ₹-5,765.92
➡️ Equity Curve R²: 0.5878
➡️ Monthly Consistency Score: -0.0216

=== [436/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.30it/s]
Hypertuning:  13%|█▎        | 436/3456 [10:53<1:15:51,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.7539
➡️ Total Profit: ₹21,048.85
➡️ Equity Curve R²: 0.0413
➡️ Monthly Consistency Score: 0.0868

=== [437/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.58it/s]
Hypertuning:  13%|█▎        | 437/3456 [10:54<1:14:49,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 0.3297
➡️ Total Profit: ₹9,245.13
➡️ Equity Curve R²: 0.1861
➡️ Monthly Consistency Score: 0.0367

=== [438/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.62it/s]
Hypertuning:  13%|█▎        | 438/3456 [10:56<1:15:59,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.2556
➡️ Total Profit: ₹-9,107.88
➡️ Equity Curve R²: 0.3855
➡️ Monthly Consistency Score: -0.0350

=== [439/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.89it/s]
Hypertuning:  13%|█▎        | 439/3456 [10:58<1:17:00,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.1823
➡️ Total Profit: ₹-5,726.53
➡️ Equity Curve R²: 0.4871
➡️ Monthly Consistency Score: -0.0227

=== [440/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.53it/s]
Hypertuning:  13%|█▎        | 440/3456 [10:59<1:15:31,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.7492
➡️ Total Profit: ₹18,230.21
➡️ Equity Curve R²: 0.0100
➡️ Monthly Consistency Score: 0.0823

=== [441/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.38it/s]
Hypertuning:  13%|█▎        | 441/3456 [11:00<1:14:41,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: -0.2986
➡️ Total Profit: ₹-16,011.81
➡️ Equity Curve R²: 0.8071
➡️ Monthly Consistency Score: -0.0607

=== [442/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.89it/s]
Hypertuning:  13%|█▎        | 442/3456 [11:02<1:15:37,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.2688
➡️ Total Profit: ₹36,515.77
➡️ Equity Curve R²: 0.3845
➡️ Monthly Consistency Score: 0.1422

=== [443/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.99it/s]
Hypertuning:  13%|█▎        | 443/3456 [11:04<1:17:10,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 0.4459
➡️ Total Profit: ₹13,557.00
➡️ Equity Curve R²: 0.0049
➡️ Monthly Consistency Score: 0.0572

=== [444/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.25it/s]
Hypertuning:  13%|█▎        | 444/3456 [11:05<1:15:45,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 4.5037
➡️ Total Profit: ₹64,960.20
➡️ Equity Curve R²: 0.5962
➡️ Monthly Consistency Score: 0.2504

=== [445/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.88it/s]
Hypertuning:  13%|█▎        | 445/3456 [11:07<1:14:47,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 1.6691
➡️ Total Profit: ₹48,012.96
➡️ Equity Curve R²: 0.1055
➡️ Monthly Consistency Score: 0.2008

=== [446/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.28it/s]
Hypertuning:  13%|█▎        | 446/3456 [11:08<1:15:45,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.3497
➡️ Total Profit: ₹47,401.95
➡️ Equity Curve R²: 0.0219
➡️ Monthly Consistency Score: 0.1965

=== [447/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.41it/s]
Hypertuning:  13%|█▎        | 447/3456 [11:10<1:16:54,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 2.7758
➡️ Total Profit: ₹58,323.30
➡️ Equity Curve R²: 0.5271
➡️ Monthly Consistency Score: 0.2653

=== [448/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.24it/s]
Hypertuning:  13%|█▎        | 448/3456 [11:11<1:15:28,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 2.0789
➡️ Total Profit: ₹56,381.01
➡️ Equity Curve R²: 0.3087
➡️ Monthly Consistency Score: 0.2596

=== [449/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.12it/s]
Hypertuning:  13%|█▎        | 449/3456 [11:13<1:14:50,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: -0.7383
➡️ Total Profit: ₹-54,259.50
➡️ Equity Curve R²: 0.9423
➡️ Monthly Consistency Score: -0.2400

=== [450/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.55it/s]
Hypertuning:  13%|█▎        | 450/3456 [11:14<1:15:50,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.4483
➡️ Total Profit: ₹-24,445.84
➡️ Equity Curve R²: 0.8848
➡️ Monthly Consistency Score: -0.0979

=== [451/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.26it/s]
Hypertuning:  13%|█▎        | 451/3456 [11:16<1:17:02,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: -0.1999
➡️ Total Profit: ₹-12,744.74
➡️ Equity Curve R²: 0.6039
➡️ Monthly Consistency Score: -0.0485

=== [452/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 90.62it/s]
Hypertuning:  13%|█▎        | 452/3456 [11:17<1:15:30,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.0062
➡️ Total Profit: ₹29,661.53
➡️ Equity Curve R²: 0.3776
➡️ Monthly Consistency Score: 0.1209

=== [453/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.05it/s]
Hypertuning:  13%|█▎        | 453/3456 [11:19<1:14:40,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 0.5923
➡️ Total Profit: ₹13,993.72
➡️ Equity Curve R²: 0.3315
➡️ Monthly Consistency Score: 0.0572

=== [454/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.57it/s]
Hypertuning:  13%|█▎        | 454/3456 [11:20<1:15:37,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.2999
➡️ Total Profit: ₹-11,364.20
➡️ Equity Curve R²: 0.5460
➡️ Monthly Consistency Score: -0.0426

=== [455/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 89.89it/s]
Hypertuning:  13%|█▎        | 455/3456 [11:22<1:14:15,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 0.2432
➡️ Total Profit: ₹5,664.48
➡️ Equity Curve R²: 0.0214
➡️ Monthly Consistency Score: 0.0208

=== [456/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.69it/s]
Hypertuning:  13%|█▎        | 456/3456 [11:23<1:14:58,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.4014
➡️ Total Profit: ₹10,622.03
➡️ Equity Curve R²: 0.0080
➡️ Monthly Consistency Score: 0.0496

=== [457/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.74it/s]
Hypertuning:  13%|█▎        | 457/3456 [11:25<1:14:16,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: -0.2750
➡️ Total Profit: ₹-14,745.22
➡️ Equity Curve R²: 0.8126
➡️ Monthly Consistency Score: -0.0554

=== [458/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.74it/s]
Hypertuning:  13%|█▎        | 458/3456 [11:26<1:15:18,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.5830
➡️ Total Profit: ₹45,557.61
➡️ Equity Curve R²: 0.3012
➡️ Monthly Consistency Score: 0.1812

=== [459/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.22it/s]
Hypertuning:  13%|█▎        | 459/3456 [11:28<1:16:45,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 1.4207
➡️ Total Profit: ₹51,759.33
➡️ Equity Curve R²: 0.1535
➡️ Monthly Consistency Score: 0.2106

=== [460/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.85it/s]
Hypertuning:  13%|█▎        | 460/3456 [11:29<1:15:15,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 4.5040
➡️ Total Profit: ₹64,963.84
➡️ Equity Curve R²: 0.6178
➡️ Monthly Consistency Score: 0.2511

=== [461/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.64it/s]
Hypertuning:  13%|█▎        | 461/3456 [11:31<1:14:15,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 0.7266
➡️ Total Profit: ₹23,662.40
➡️ Equity Curve R²: 0.0699
➡️ Monthly Consistency Score: 0.0936

=== [462/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.35it/s]
Hypertuning:  13%|█▎        | 462/3456 [11:32<1:15:01,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 1.1722
➡️ Total Profit: ₹45,141.95
➡️ Equity Curve R²: 0.0001
➡️ Monthly Consistency Score: 0.1776

=== [463/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.07it/s]
Hypertuning:  13%|█▎        | 463/3456 [11:34<1:15:55,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 1.0438
➡️ Total Profit: ₹40,394.67
➡️ Equity Curve R²: 0.0087
➡️ Monthly Consistency Score: 0.1560

=== [464/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.92it/s]
Hypertuning:  13%|█▎        | 464/3456 [11:35<1:14:39,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.9391
➡️ Total Profit: ₹41,472.83
➡️ Equity Curve R²: 0.0016
➡️ Monthly Consistency Score: 0.1621

=== [465/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.94it/s]
Hypertuning:  13%|█▎        | 465/3456 [11:37<1:16:29,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.8031
➡️ Total Profit: ₹-65,319.18
➡️ Equity Curve R²: 0.9503
➡️ Monthly Consistency Score: -0.2876

=== [466/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.65it/s]
Hypertuning:  13%|█▎        | 466/3456 [11:38<1:15:20,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.6105
➡️ Total Profit: ₹-40,869.32
➡️ Equity Curve R²: 0.9219
➡️ Monthly Consistency Score: -0.1657

=== [467/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.63it/s]
Hypertuning:  14%|█▎        | 467/3456 [11:40<1:16:43,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: -0.1319
➡️ Total Profit: ₹-8,246.16
➡️ Equity Curve R²: 0.4414
➡️ Monthly Consistency Score: -0.0309

=== [468/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.89it/s]
Hypertuning:  14%|█▎        | 468/3456 [11:41<1:15:27,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.5228
➡️ Total Profit: ₹15,410.53
➡️ Equity Curve R²: 0.1404
➡️ Monthly Consistency Score: 0.0628

=== [469/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.94it/s]
Hypertuning:  14%|█▎        | 469/3456 [11:43<1:14:09,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 0.8003
➡️ Total Profit: ₹18,403.25
➡️ Equity Curve R²: 0.4227
➡️ Monthly Consistency Score: 0.0755

=== [470/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.17it/s]
Hypertuning:  14%|█▎        | 470/3456 [11:44<1:14:53,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.4684
➡️ Total Profit: ₹14,624.89
➡️ Equity Curve R²: 0.0675
➡️ Monthly Consistency Score: 0.0542

=== [471/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.41it/s]
Hypertuning:  14%|█▎        | 471/3456 [11:46<1:13:23,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 0.6710
➡️ Total Profit: ₹15,404.48
➡️ Equity Curve R²: 0.0771
➡️ Monthly Consistency Score: 0.0603

=== [472/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.69it/s]
Hypertuning:  14%|█▎        | 472/3456 [11:47<1:14:23,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.4014
➡️ Total Profit: ₹10,622.03
➡️ Equity Curve R²: 0.0080
➡️ Monthly Consistency Score: 0.0496

=== [473/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.02it/s]
Hypertuning:  14%|█▎        | 473/3456 [11:49<1:15:53,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.3054
➡️ Total Profit: ₹-17,893.82
➡️ Equity Curve R²: 0.8344
➡️ Monthly Consistency Score: -0.0652

=== [474/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.26it/s]
Hypertuning:  14%|█▎        | 474/3456 [11:50<1:14:48,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.2756
➡️ Total Profit: ₹41,035.77
➡️ Equity Curve R²: 0.0425
➡️ Monthly Consistency Score: 0.1581

=== [475/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 90.50it/s]
Hypertuning:  14%|█▎        | 475/3456 [11:52<1:16:01,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.7073
➡️ Total Profit: ₹32,199.33
➡️ Equity Curve R²: 0.0048
➡️ Monthly Consistency Score: 0.1307

=== [476/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.24it/s]
Hypertuning:  14%|█▍        | 476/3456 [11:53<1:15:03,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 2.2875
➡️ Total Profit: ₹40,572.01
➡️ Equity Curve R²: 0.5602
➡️ Monthly Consistency Score: 0.1560

=== [477/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.75it/s]
Hypertuning:  14%|█▍        | 477/3456 [11:55<1:14:16,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.7181
➡️ Total Profit: ₹24,292.87
➡️ Equity Curve R²: 0.1581
➡️ Monthly Consistency Score: 0.0949

=== [478/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.49it/s]
Hypertuning:  14%|█▍        | 478/3456 [11:56<1:14:47,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.1628
➡️ Total Profit: ₹47,405.63
➡️ Equity Curve R²: 0.0055
➡️ Monthly Consistency Score: 0.1825

=== [479/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.36it/s]
Hypertuning:  14%|█▍        | 479/3456 [11:58<1:15:44,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.2120
➡️ Total Profit: ₹10,970.90
➡️ Equity Curve R²: 0.5458
➡️ Monthly Consistency Score: 0.0448

=== [480/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.51it/s]
Hypertuning:  14%|█▍        | 480/3456 [11:59<1:14:20,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.9391
➡️ Total Profit: ₹41,472.83
➡️ Equity Curve R²: 0.0016
➡️ Monthly Consistency Score: 0.1621

=== [481/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.25it/s]
Hypertuning:  14%|█▍        | 481/3456 [12:01<1:13:31,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: -0.7473
➡️ Total Profit: ₹-64,054.30
➡️ Equity Curve R²: 0.9511
➡️ Monthly Consistency Score: -0.2685

=== [482/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 90.53it/s]
Hypertuning:  14%|█▍        | 482/3456 [12:02<1:14:17,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.4597
➡️ Total Profit: ₹-22,865.36
➡️ Equity Curve R²: 0.8730
➡️ Monthly Consistency Score: -0.0938

=== [483/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.91it/s]
Hypertuning:  14%|█▍        | 483/3456 [12:04<1:15:47,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 1.1484
➡️ Total Profit: ₹42,428.44
➡️ Equity Curve R²: 0.0022
➡️ Monthly Consistency Score: 0.1595

=== [484/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 89.54it/s]
Hypertuning:  14%|█▍        | 484/3456 [12:05<1:14:59,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.2199
➡️ Total Profit: ₹37,449.67
➡️ Equity Curve R²: 0.3562
➡️ Monthly Consistency Score: 0.1328

=== [485/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.40it/s]
Hypertuning:  14%|█▍        | 485/3456 [12:07<1:13:49,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 0.1443
➡️ Total Profit: ₹4,723.81
➡️ Equity Curve R²: 0.0000
➡️ Monthly Consistency Score: 0.0177

=== [486/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.69it/s]
Hypertuning:  14%|█▍        | 486/3456 [12:08<1:14:39,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.0097
➡️ Total Profit: ₹287.09
➡️ Equity Curve R²: 0.0985
➡️ Monthly Consistency Score: 0.0011

=== [487/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.23it/s]
Hypertuning:  14%|█▍        | 487/3456 [12:10<1:15:44,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.5828
➡️ Total Profit: ₹15,426.85
➡️ Equity Curve R²: 0.0201
➡️ Monthly Consistency Score: 0.0591

=== [488/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 88.74it/s]
Hypertuning:  14%|█▍        | 488/3456 [12:11<1:14:29,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.8499
➡️ Total Profit: ₹37,723.09
➡️ Equity Curve R²: 0.7012
➡️ Monthly Consistency Score: 0.1604

=== [489/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.66it/s]
Hypertuning:  14%|█▍        | 489/3456 [12:13<1:13:55,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.4679
➡️ Total Profit: ₹-37,994.93
➡️ Equity Curve R²: 0.8922
➡️ Monthly Consistency Score: -0.1287

=== [490/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.78it/s]
Hypertuning:  14%|█▍        | 490/3456 [12:14<1:14:34,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.5382
➡️ Total Profit: ₹43,303.13
➡️ Equity Curve R²: 0.3408
➡️ Monthly Consistency Score: 0.1623

=== [491/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.02it/s]
Hypertuning:  14%|█▍        | 491/3456 [12:16<1:15:34,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.5999
➡️ Total Profit: ₹21,371.27
➡️ Equity Curve R²: 0.1056
➡️ Monthly Consistency Score: 0.0943

=== [492/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.33it/s]
Hypertuning:  14%|█▍        | 492/3456 [12:17<1:14:39,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 4.0060
➡️ Total Profit: ₹73,006.66
➡️ Equity Curve R²: 0.6704
➡️ Monthly Consistency Score: 0.3062

=== [493/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.31it/s]
Hypertuning:  14%|█▍        | 493/3456 [12:19<1:13:41,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 0.6967
➡️ Total Profit: ₹22,822.35
➡️ Equity Curve R²: 0.1662
➡️ Monthly Consistency Score: 0.0807

=== [494/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.06it/s]
Hypertuning:  14%|█▍        | 494/3456 [12:21<1:14:53,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 1.3360
➡️ Total Profit: ₹51,021.25
➡️ Equity Curve R²: 0.0078
➡️ Monthly Consistency Score: 0.2004

=== [495/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.87it/s]
Hypertuning:  14%|█▍        | 495/3456 [12:22<1:15:36,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 5.1711
➡️ Total Profit: ₹101,147.07
➡️ Equity Curve R²: 0.8559
➡️ Monthly Consistency Score: 0.4137

=== [496/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.32it/s]
Hypertuning:  14%|█▍        | 496/3456 [12:24<1:14:10,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 3.2750
➡️ Total Profit: ₹62,776.47
➡️ Equity Curve R²: 0.6217
➡️ Monthly Consistency Score: 0.2904

=== [497/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.84it/s]
Hypertuning:  14%|█▍        | 497/3456 [12:25<1:13:16,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: -0.7541
➡️ Total Profit: ₹-65,379.41
➡️ Equity Curve R²: 0.9592
➡️ Monthly Consistency Score: -0.2716

=== [498/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.71it/s]
Hypertuning:  14%|█▍        | 498/3456 [12:27<1:14:27,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.1513
➡️ Total Profit: ₹-5,301.75
➡️ Equity Curve R²: 0.5623
➡️ Monthly Consistency Score: -0.0217

=== [499/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.24it/s]
Hypertuning:  14%|█▍        | 499/3456 [12:28<1:15:21,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 1.6356
➡️ Total Profit: ₹46,468.32
➡️ Equity Curve R²: 0.1784
➡️ Monthly Consistency Score: 0.1804

=== [500/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 84.12it/s]
Hypertuning:  14%|█▍        | 500/3456 [12:30<1:14:19,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 2.2221
➡️ Total Profit: ₹47,447.95
➡️ Equity Curve R²: 0.6767
➡️ Monthly Consistency Score: 0.1705

=== [501/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.80it/s]
Hypertuning:  14%|█▍        | 501/3456 [12:31<1:13:28,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 0.3327
➡️ Total Profit: ₹10,055.22
➡️ Equity Curve R²: 0.1050
➡️ Monthly Consistency Score: 0.0372

=== [502/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.36it/s]
Hypertuning:  15%|█▍        | 502/3456 [12:33<1:14:47,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.0830
➡️ Total Profit: ₹2,545.25
➡️ Equity Curve R²: 0.0437
➡️ Monthly Consistency Score: 0.0097

=== [503/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.53it/s]
Hypertuning:  15%|█▍        | 503/3456 [12:34<1:13:08,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 1.0354
➡️ Total Profit: ₹20,315.48
➡️ Equity Curve R²: 0.2362
➡️ Monthly Consistency Score: 0.0774

=== [504/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.46it/s]
Hypertuning:  15%|█▍        | 504/3456 [12:36<1:13:42,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 1.4766
➡️ Total Profit: ₹30,111.27
➡️ Equity Curve R²: 0.5836
➡️ Monthly Consistency Score: 0.1296

=== [505/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.51it/s]
Hypertuning:  15%|█▍        | 505/3456 [12:37<1:12:56,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: -0.4756
➡️ Total Profit: ₹-38,620.70
➡️ Equity Curve R²: 0.8947
➡️ Monthly Consistency Score: -0.1304

=== [506/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.50it/s]
Hypertuning:  15%|█▍        | 506/3456 [12:39<1:13:57,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 1.6587
➡️ Total Profit: ₹46,694.05
➡️ Equity Curve R²: 0.4600
➡️ Monthly Consistency Score: 0.1730

=== [507/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.81it/s]
Hypertuning:  15%|█▍        | 507/3456 [12:40<1:14:57,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 1.1510
➡️ Total Profit: ₹26,259.90
➡️ Equity Curve R²: 0.0022
➡️ Monthly Consistency Score: 0.1141

=== [508/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.18it/s]
Hypertuning:  15%|█▍        | 508/3456 [12:42<1:13:50,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 5.4686
➡️ Total Profit: ₹81,526.66
➡️ Equity Curve R²: 0.8147
➡️ Monthly Consistency Score: 0.3724

=== [509/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.84it/s]
Hypertuning:  15%|█▍        | 509/3456 [12:43<1:13:19,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 0.8046
➡️ Total Profit: ₹25,343.29
➡️ Equity Curve R²: 0.1521
➡️ Monthly Consistency Score: 0.0895

=== [510/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.25it/s]
Hypertuning:  15%|█▍        | 510/3456 [12:45<1:14:22,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.3837
➡️ Total Profit: ₹54,408.49
➡️ Equity Curve R²: 0.0002
➡️ Monthly Consistency Score: 0.2104

=== [511/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.66it/s]
Hypertuning:  15%|█▍        | 511/3456 [12:46<1:15:21,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 5.0880
➡️ Total Profit: ₹99,521.18
➡️ Equity Curve R²: 0.8548
➡️ Monthly Consistency Score: 0.4097

=== [512/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.39it/s]
Hypertuning:  15%|█▍        | 512/3456 [12:48<1:14:05,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 3.2750
➡️ Total Profit: ₹62,776.47
➡️ Equity Curve R²: 0.6217
➡️ Monthly Consistency Score: 0.2904

=== [513/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 84.09it/s]
Hypertuning:  15%|█▍        | 513/3456 [12:49<1:15:50,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: -0.7934
➡️ Total Profit: ₹-73,004.52
➡️ Equity Curve R²: 0.9675
➡️ Monthly Consistency Score: -0.3016

=== [514/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.78it/s]
Hypertuning:  15%|█▍        | 514/3456 [12:51<1:14:31,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.0146
➡️ Total Profit: ₹440.09
➡️ Equity Curve R²: 0.3391
➡️ Monthly Consistency Score: 0.0017

=== [515/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.98it/s]
Hypertuning:  15%|█▍        | 515/3456 [12:52<1:13:02,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 0.8798
➡️ Total Profit: ₹24,430.93
➡️ Equity Curve R²: 0.0112
➡️ Monthly Consistency Score: 0.0940

=== [516/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.50it/s]
Hypertuning:  15%|█▍        | 516/3456 [12:54<1:14:11,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 2.2263
➡️ Total Profit: ₹47,538.91
➡️ Equity Curve R²: 0.7343
➡️ Monthly Consistency Score: 0.1646

=== [517/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.84it/s]
Hypertuning:  15%|█▍        | 517/3456 [12:55<1:16:02,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: 0.4185
➡️ Total Profit: ₹12,909.58
➡️ Equity Curve R²: 0.0755
➡️ Monthly Consistency Score: 0.0501

=== [518/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.32it/s]
Hypertuning:  15%|█▍        | 518/3456 [12:57<1:14:36,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.3762
➡️ Total Profit: ₹-15,103.84
➡️ Equity Curve R²: 0.6851
➡️ Monthly Consistency Score: -0.0581

=== [519/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.56it/s]
Hypertuning:  15%|█▌        | 519/3456 [12:58<1:12:59,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 0.9523
➡️ Total Profit: ₹18,684.11
➡️ Equity Curve R²: 0.3669
➡️ Monthly Consistency Score: 0.0725

=== [520/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.26it/s]
Hypertuning:  15%|█▌        | 520/3456 [13:00<1:14:05,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.1335
➡️ Total Profit: ₹23,113.93
➡️ Equity Curve R²: 0.5406
➡️ Monthly Consistency Score: 0.1030

=== [521/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 90.66it/s]
Hypertuning:  15%|█▌        | 521/3456 [13:01<1:13:16,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.4989
➡️ Total Profit: ₹-40,511.17
➡️ Equity Curve R²: 0.8945
➡️ Monthly Consistency Score: -0.1363

=== [522/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.59it/s]
Hypertuning:  15%|█▌        | 522/3456 [13:03<1:14:03,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 2.0186
➡️ Total Profit: ₹61,383.14
➡️ Equity Curve R²: 0.4363
➡️ Monthly Consistency Score: 0.2491

=== [523/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.77it/s]
Hypertuning:  15%|█▌        | 523/3456 [13:04<1:15:23,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 2.2842
➡️ Total Profit: ₹52,114.01
➡️ Equity Curve R²: 0.3625
➡️ Monthly Consistency Score: 0.2312

=== [524/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.57it/s]
Hypertuning:  15%|█▌        | 524/3456 [13:06<1:14:11,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 6.2472
➡️ Total Profit: ₹93,134.84
➡️ Equity Curve R²: 0.8141
➡️ Monthly Consistency Score: 0.3859

=== [525/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.15it/s]
Hypertuning:  15%|█▌        | 525/3456 [13:07<1:13:53,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.9654
➡️ Total Profit: ₹31,012.82
➡️ Equity Curve R²: 0.2398
➡️ Monthly Consistency Score: 0.1107

=== [526/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.92it/s]
Hypertuning:  15%|█▌        | 526/3456 [13:09<1:14:49,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 1.4986
➡️ Total Profit: ₹55,539.41
➡️ Equity Curve R²: 0.0030
➡️ Monthly Consistency Score: 0.2158

=== [527/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.71it/s]
Hypertuning:  15%|█▌        | 527/3456 [13:11<1:15:41,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: 4.8379
➡️ Total Profit: ₹94,629.81
➡️ Equity Curve R²: 0.8098
➡️ Monthly Consistency Score: 0.3823

=== [528/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.45it/s]
Hypertuning:  15%|█▌        | 528/3456 [13:12<1:14:27,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 2.9239
➡️ Total Profit: ₹60,648.29
➡️ Equity Curve R²: 0.5566
➡️ Monthly Consistency Score: 0.2784

=== [529/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.24it/s]
Hypertuning:  15%|█▌        | 529/3456 [13:14<1:16:40,  1.57s/it]

➡️ Profit-to-Drawdown Ratio: -0.7356
➡️ Total Profit: ₹-60,274.30
➡️ Equity Curve R²: 0.9501
➡️ Monthly Consistency Score: -0.2523

=== [530/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.93it/s]
Hypertuning:  15%|█▌        | 530/3456 [13:15<1:15:04,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: -0.4461
➡️ Total Profit: ₹-21,643.51
➡️ Equity Curve R²: 0.8385
➡️ Monthly Consistency Score: -0.0803

=== [531/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 86.45it/s]
Hypertuning:  15%|█▌        | 531/3456 [13:17<1:13:23,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.2477
➡️ Total Profit: ₹44,059.81
➡️ Equity Curve R²: 0.0160
➡️ Monthly Consistency Score: 0.1646

=== [532/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.25it/s]
Hypertuning:  15%|█▌        | 532/3456 [13:18<1:14:12,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 1.2199
➡️ Total Profit: ₹37,449.67
➡️ Equity Curve R²: 0.3562
➡️ Monthly Consistency Score: 0.1328

=== [533/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.61it/s]
Hypertuning:  15%|█▌        | 533/3456 [13:20<1:15:52,  1.56s/it]

➡️ Profit-to-Drawdown Ratio: 0.2494
➡️ Total Profit: ₹8,165.69
➡️ Equity Curve R²: 0.0454
➡️ Monthly Consistency Score: 0.0300

=== [534/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.75it/s]
Hypertuning:  15%|█▌        | 534/3456 [13:21<1:14:36,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.0097
➡️ Total Profit: ₹287.09
➡️ Equity Curve R²: 0.0985
➡️ Monthly Consistency Score: 0.0011

=== [535/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.96it/s]
Hypertuning:  15%|█▌        | 535/3456 [13:23<1:12:55,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.6526
➡️ Total Profit: ₹17,058.22
➡️ Equity Curve R²: 0.0660
➡️ Monthly Consistency Score: 0.0653

=== [536/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 89.85it/s]
Hypertuning:  16%|█▌        | 536/3456 [13:24<1:13:51,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 1.8499
➡️ Total Profit: ₹37,723.09
➡️ Equity Curve R²: 0.7012
➡️ Monthly Consistency Score: 0.1604

=== [537/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.63it/s]
Hypertuning:  16%|█▌        | 537/3456 [13:26<1:13:05,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.4679
➡️ Total Profit: ₹-37,994.93
➡️ Equity Curve R²: 0.8922
➡️ Monthly Consistency Score: -0.1287

=== [538/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.40it/s]
Hypertuning:  16%|█▌        | 538/3456 [13:27<1:14:00,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 1.5382
➡️ Total Profit: ₹43,303.13
➡️ Equity Curve R²: 0.3408
➡️ Monthly Consistency Score: 0.1623

=== [539/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.63it/s]
Hypertuning:  16%|█▌        | 539/3456 [13:29<1:14:49,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 0.6767
➡️ Total Profit: ₹23,002.64
➡️ Equity Curve R²: 0.0607
➡️ Monthly Consistency Score: 0.1007

=== [540/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.07it/s]
Hypertuning:  16%|█▌        | 540/3456 [13:30<1:13:55,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 4.0060
➡️ Total Profit: ₹73,006.66
➡️ Equity Curve R²: 0.6704
➡️ Monthly Consistency Score: 0.3062

=== [541/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.78it/s]
Hypertuning:  16%|█▌        | 541/3456 [13:32<1:13:07,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.6198
➡️ Total Profit: ₹20,303.29
➡️ Equity Curve R²: 0.0965
➡️ Monthly Consistency Score: 0.0709

=== [542/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 87.33it/s]
Hypertuning:  16%|█▌        | 542/3456 [13:33<1:14:09,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 1.3360
➡️ Total Profit: ₹51,021.25
➡️ Equity Curve R²: 0.0078
➡️ Monthly Consistency Score: 0.2004

=== [543/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.59it/s]
Hypertuning:  16%|█▌        | 543/3456 [13:35<1:15:06,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: 5.2545
➡️ Total Profit: ₹102,778.44
➡️ Equity Curve R²: 0.8693
➡️ Monthly Consistency Score: 0.4178

=== [544/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.54it/s]
Hypertuning:  16%|█▌        | 544/3456 [13:36<1:13:26,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 3.2750
➡️ Total Profit: ₹62,776.47
➡️ Equity Curve R²: 0.6217
➡️ Monthly Consistency Score: 0.2904

=== [545/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.96it/s]
Hypertuning:  16%|█▌        | 545/3456 [13:38<1:14:55,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: -0.7549
➡️ Total Profit: ₹-67,615.32
➡️ Equity Curve R²: 0.9567
➡️ Monthly Consistency Score: -0.2816

=== [546/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.12it/s]
Hypertuning:  16%|█▌        | 546/3456 [13:39<1:13:41,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.0577
➡️ Total Profit: ₹-1,819.91
➡️ Equity Curve R²: 0.5322
➡️ Monthly Consistency Score: -0.0074

=== [547/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.69it/s]
Hypertuning:  16%|█▌        | 547/3456 [13:41<1:14:24,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 1.4924
➡️ Total Profit: ₹44,836.95
➡️ Equity Curve R²: 0.1179
➡️ Monthly Consistency Score: 0.1743

=== [548/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.14it/s]
Hypertuning:  16%|█▌        | 548/3456 [13:43<1:13:10,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 2.1914
➡️ Total Profit: ₹46,792.49
➡️ Equity Curve R²: 0.6959
➡️ Monthly Consistency Score: 0.1685

=== [549/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.80it/s]
Hypertuning:  16%|█▌        | 549/3456 [13:44<1:12:44,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.3230
➡️ Total Profit: ₹9,760.99
➡️ Equity Curve R²: 0.0683
➡️ Monthly Consistency Score: 0.0369

=== [550/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 89.36it/s]
Hypertuning:  16%|█▌        | 550/3456 [13:46<1:13:46,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.0830
➡️ Total Profit: ₹2,545.25
➡️ Equity Curve R²: 0.0437
➡️ Monthly Consistency Score: 0.0097

=== [551/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.64it/s]
Hypertuning:  16%|█▌        | 551/3456 [13:47<1:12:26,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 1.0354
➡️ Total Profit: ₹20,315.48
➡️ Equity Curve R²: 0.2362
➡️ Monthly Consistency Score: 0.0774

=== [552/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 83.72it/s]
Hypertuning:  16%|█▌        | 552/3456 [13:49<1:13:31,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 1.5511
➡️ Total Profit: ₹31,630.29
➡️ Equity Curve R²: 0.5345
➡️ Monthly Consistency Score: 0.1383

=== [553/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.78it/s]
Hypertuning:  16%|█▌        | 553/3456 [13:50<1:12:31,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.4595
➡️ Total Profit: ₹-36,732.11
➡️ Equity Curve R²: 0.8924
➡️ Monthly Consistency Score: -0.1249

=== [554/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.25it/s]
Hypertuning:  16%|█▌        | 554/3456 [13:52<1:13:31,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 1.4982
➡️ Total Profit: ₹42,175.89
➡️ Equity Curve R²: 0.3793
➡️ Monthly Consistency Score: 0.1526

=== [555/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 87.35it/s]
Hypertuning:  16%|█▌        | 555/3456 [13:53<1:14:47,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: 1.4497
➡️ Total Profit: ₹35,108.53
➡️ Equity Curve R²: 0.0174
➡️ Monthly Consistency Score: 0.1524

=== [556/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.52it/s]
Hypertuning:  16%|█▌        | 556/3456 [13:55<1:13:33,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 4.6679
➡️ Total Profit: ₹75,134.84
➡️ Equity Curve R²: 0.7176
➡️ Monthly Consistency Score: 0.3158

=== [557/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.49it/s]
Hypertuning:  16%|█▌        | 557/3456 [13:56<1:12:41,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.9046
➡️ Total Profit: ₹28,492.82
➡️ Equity Curve R²: 0.2519
➡️ Monthly Consistency Score: 0.1010

=== [558/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.92it/s]
Hypertuning:  16%|█▌        | 558/3456 [13:58<1:13:50,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 1.2688
➡️ Total Profit: ₹49,890.33
➡️ Equity Curve R²: 0.0192
➡️ Monthly Consistency Score: 0.1924

=== [559/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 87.57it/s]
Hypertuning:  16%|█▌        | 559/3456 [13:59<1:14:43,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: 5.1713
➡️ Total Profit: ₹101,149.81
➡️ Equity Curve R²: 0.8563
➡️ Monthly Consistency Score: 0.4137

=== [560/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.04it/s]
Hypertuning:  16%|█▌        | 560/3456 [14:01<1:13:35,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 3.2750
➡️ Total Profit: ₹62,776.47
➡️ Equity Curve R²: 0.6217
➡️ Monthly Consistency Score: 0.2904

=== [561/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 82.48it/s]
Hypertuning:  16%|█▌        | 561/3456 [14:02<1:15:23,  1.56s/it]

➡️ Profit-to-Drawdown Ratio: -0.8233
➡️ Total Profit: ₹-74,620.68
➡️ Equity Curve R²: 0.9749
➡️ Monthly Consistency Score: -0.3030

=== [562/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 89.09it/s]
Hypertuning:  16%|█▋        | 562/3456 [14:04<1:14:00,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.3494
➡️ Total Profit: ₹-13,825.35
➡️ Equity Curve R²: 0.7425
➡️ Monthly Consistency Score: -0.0556

=== [563/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 87.92it/s]
Hypertuning:  16%|█▋        | 563/3456 [14:05<1:14:56,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: 1.5760
➡️ Total Profit: ₹34,600.87
➡️ Equity Curve R²: 0.3344
➡️ Monthly Consistency Score: 0.1424

=== [564/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.16it/s]
Hypertuning:  16%|█▋        | 564/3456 [14:07<1:13:38,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 2.2263
➡️ Total Profit: ₹47,538.91
➡️ Equity Curve R²: 0.7343
➡️ Monthly Consistency Score: 0.1661

=== [565/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.60it/s]
Hypertuning:  16%|█▋        | 565/3456 [14:08<1:12:49,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.4102
➡️ Total Profit: ₹12,911.46
➡️ Equity Curve R²: 0.0915
➡️ Monthly Consistency Score: 0.0501

=== [566/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.62it/s]
Hypertuning:  16%|█▋        | 566/3456 [14:10<1:13:43,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.4727
➡️ Total Profit: ₹-26,329.24
➡️ Equity Curve R²: 0.8785
➡️ Monthly Consistency Score: -0.1055

=== [567/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.78it/s]
Hypertuning:  16%|█▋        | 567/3456 [14:11<1:12:09,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: 0.3229
➡️ Total Profit: ₹10,538.22
➡️ Equity Curve R²: 0.1014
➡️ Monthly Consistency Score: 0.0420

=== [568/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.88it/s]
Hypertuning:  16%|█▋        | 568/3456 [14:13<1:12:43,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.2491
➡️ Total Profit: ₹27,373.93
➡️ Equity Curve R²: 0.4740
➡️ Monthly Consistency Score: 0.1188

=== [569/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 88.60it/s]
Hypertuning:  16%|█▋        | 569/3456 [14:14<1:11:56,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: -0.3788
➡️ Total Profit: ₹-31,186.34
➡️ Equity Curve R²: 0.8312
➡️ Monthly Consistency Score: -0.1083

=== [570/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.72it/s]
Hypertuning:  16%|█▋        | 570/3456 [14:16<1:12:45,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.3146
➡️ Total Profit: ₹13,830.53
➡️ Equity Curve R²: 0.2103
➡️ Monthly Consistency Score: 0.0468

=== [571/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.91it/s]
Hypertuning:  17%|█▋        | 571/3456 [14:17<1:11:12,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 2.5810
➡️ Total Profit: ₹50,477.16
➡️ Equity Curve R²: 0.3797
➡️ Monthly Consistency Score: 0.2261

=== [572/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 102.03it/s]
Hypertuning:  17%|█▋        | 572/3456 [14:19<1:08:36,  1.43s/it]

➡️ Profit-to-Drawdown Ratio: 4.4037
➡️ Total Profit: ₹65,651.20
➡️ Equity Curve R²: 0.8292
➡️ Monthly Consistency Score: 0.2975

=== [573/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 111.25it/s]
Hypertuning:  17%|█▋        | 573/3456 [14:20<1:07:12,  1.40s/it]

➡️ Profit-to-Drawdown Ratio: 1.7937
➡️ Total Profit: ₹55,364.32
➡️ Equity Curve R²: 0.3139
➡️ Monthly Consistency Score: 0.2117

=== [574/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.13it/s]
Hypertuning:  17%|█▋        | 574/3456 [14:21<1:06:56,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 1.3840
➡️ Total Profit: ₹54,414.01
➡️ Equity Curve R²: 0.0055
➡️ Monthly Consistency Score: 0.2145

=== [575/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.28it/s]
Hypertuning:  17%|█▋        | 575/3456 [14:23<1:06:56,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 5.0045
➡️ Total Profit: ₹97,887.07
➡️ Equity Curve R²: 0.8192
➡️ Monthly Consistency Score: 0.3925

=== [576/3456] Testing Parameters ===
smooth_length: 5
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.00it/s]
Hypertuning:  17%|█▋        | 576/3456 [14:24<1:05:39,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.9239
➡️ Total Profit: ₹60,648.29
➡️ Equity Curve R²: 0.5566
➡️ Monthly Consistency Score: 0.2784

=== [577/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.67it/s]
Hypertuning:  17%|█▋        | 577/3456 [14:26<1:06:24,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.8233
➡️ Total Profit: ₹-85,272.47
➡️ Equity Curve R²: 0.9708
➡️ Monthly Consistency Score: -0.3692

=== [578/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.02it/s]
Hypertuning:  17%|█▋        | 578/3456 [14:27<1:05:26,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4023
➡️ Total Profit: ₹-19,485.79
➡️ Equity Curve R²: 0.8416
➡️ Monthly Consistency Score: -0.0758

=== [579/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.26it/s]
Hypertuning:  17%|█▋        | 579/3456 [14:28<1:05:42,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1769
➡️ Total Profit: ₹-8,169.43
➡️ Equity Curve R²: 0.5588
➡️ Monthly Consistency Score: -0.0302

=== [580/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.78it/s]
Hypertuning:  17%|█▋        | 580/3456 [14:30<1:04:57,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.3888
➡️ Total Profit: ₹12,726.85
➡️ Equity Curve R²: 0.0063
➡️ Monthly Consistency Score: 0.0481

=== [581/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.32it/s]
Hypertuning:  17%|█▋        | 581/3456 [14:31<1:04:29,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.8361
➡️ Total Profit: ₹20,413.97
➡️ Equity Curve R²: 0.6131
➡️ Monthly Consistency Score: 0.0755

=== [582/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.47it/s]
Hypertuning:  17%|█▋        | 582/3456 [14:32<1:05:05,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.1236
➡️ Total Profit: ₹22,455.69
➡️ Equity Curve R²: 0.2160
➡️ Monthly Consistency Score: 0.0866

=== [583/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.61it/s]
Hypertuning:  17%|█▋        | 583/3456 [14:34<1:05:54,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.4212
➡️ Total Profit: ₹33,259.04
➡️ Equity Curve R²: 0.0208
➡️ Monthly Consistency Score: 0.1186

=== [584/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.60it/s]
Hypertuning:  17%|█▋        | 584/3456 [14:35<1:04:52,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4432
➡️ Total Profit: ₹9,713.85
➡️ Equity Curve R²: 0.0853
➡️ Monthly Consistency Score: 0.0413

=== [585/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.45it/s]
Hypertuning:  17%|█▋        | 585/3456 [14:36<1:04:31,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1952
➡️ Total Profit: ₹5,787.39
➡️ Equity Curve R²: 0.2255
➡️ Monthly Consistency Score: 0.0221

=== [586/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.09it/s]
Hypertuning:  17%|█▋        | 586/3456 [14:38<1:04:48,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3597
➡️ Total Profit: ₹9,132.05
➡️ Equity Curve R²: 0.0001
➡️ Monthly Consistency Score: 0.0378

=== [587/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.65it/s]
Hypertuning:  17%|█▋        | 587/3456 [14:39<1:05:19,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1955
➡️ Total Profit: ₹-7,626.16
➡️ Equity Curve R²: 0.2448
➡️ Monthly Consistency Score: -0.0296

=== [588/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.58it/s]
Hypertuning:  17%|█▋        | 588/3456 [14:40<1:04:19,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.5689
➡️ Total Profit: ₹-24,076.18
➡️ Equity Curve R²: 0.7269
➡️ Monthly Consistency Score: -0.0953

=== [589/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.52it/s]
Hypertuning:  17%|█▋        | 589/3456 [14:42<1:03:54,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.2107
➡️ Total Profit: ₹7,479.66
➡️ Equity Curve R²: 0.1833
➡️ Monthly Consistency Score: 0.0284

=== [590/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.79it/s]
Hypertuning:  17%|█▋        | 590/3456 [14:43<1:04:33,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.0517
➡️ Total Profit: ₹42,878.27
➡️ Equity Curve R²: 0.0073
➡️ Monthly Consistency Score: 0.1695

=== [591/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.42it/s]
Hypertuning:  17%|█▋        | 591/3456 [14:44<1:05:03,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5299
➡️ Total Profit: ₹25,726.04
➡️ Equity Curve R²: 0.1102
➡️ Monthly Consistency Score: 0.1012

=== [592/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.52it/s]
Hypertuning:  17%|█▋        | 592/3456 [14:46<1:04:24,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.5212
➡️ Total Profit: ₹62,772.83
➡️ Equity Curve R²: 0.6336
➡️ Monthly Consistency Score: 0.3159

=== [593/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.51it/s]
Hypertuning:  17%|█▋        | 593/3456 [14:47<1:04:08,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.8056
➡️ Total Profit: ₹-70,710.59
➡️ Equity Curve R²: 0.9596
➡️ Monthly Consistency Score: -0.3103

=== [594/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.01it/s]
Hypertuning:  17%|█▋        | 594/3456 [14:49<1:04:37,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3055
➡️ Total Profit: ₹-13,233.07
➡️ Equity Curve R²: 0.7685
➡️ Monthly Consistency Score: -0.0519

=== [595/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.87it/s]
Hypertuning:  17%|█▋        | 595/3456 [14:50<1:05:11,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.0728
➡️ Total Profit: ₹2,846.40
➡️ Equity Curve R²: 0.2837
➡️ Monthly Consistency Score: 0.0112

=== [596/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.60it/s]
Hypertuning:  17%|█▋        | 596/3456 [14:51<1:04:14,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3888
➡️ Total Profit: ₹12,726.85
➡️ Equity Curve R²: 0.0063
➡️ Monthly Consistency Score: 0.0481

=== [597/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.47it/s]
Hypertuning:  17%|█▋        | 597/3456 [14:53<1:05:18,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.0333
➡️ Total Profit: ₹23,273.97
➡️ Equity Curve R²: 0.6332
➡️ Monthly Consistency Score: 0.0887

=== [598/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.47it/s]
Hypertuning:  17%|█▋        | 598/3456 [14:54<1:04:34,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5117
➡️ Total Profit: ₹14,979.37
➡️ Equity Curve R²: 0.0838
➡️ Monthly Consistency Score: 0.0584

=== [599/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.43it/s]
Hypertuning:  17%|█▋        | 599/3456 [14:55<1:03:31,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 1.4909
➡️ Total Profit: ₹34,890.41
➡️ Equity Curve R²: 0.0294
➡️ Monthly Consistency Score: 0.1225

=== [600/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.07it/s]
Hypertuning:  17%|█▋        | 600/3456 [14:57<1:03:57,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.5405
➡️ Total Profit: ₹11,845.67
➡️ Equity Curve R²: 0.0814
➡️ Monthly Consistency Score: 0.0503

=== [601/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.26it/s]
Hypertuning:  17%|█▋        | 601/3456 [14:58<1:05:19,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.2803
➡️ Total Profit: ₹8,310.21
➡️ Equity Curve R²: 0.1243
➡️ Monthly Consistency Score: 0.0317

=== [602/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.68it/s]
Hypertuning:  17%|█▋        | 602/3456 [14:59<1:04:46,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.8937
➡️ Total Profit: ₹22,690.21
➡️ Equity Curve R²: 0.0196
➡️ Monthly Consistency Score: 0.0929

=== [603/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.35it/s]
Hypertuning:  17%|█▋        | 603/3456 [15:01<1:04:55,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0701
➡️ Total Profit: ₹-2,734.79
➡️ Equity Curve R²: 0.1030
➡️ Monthly Consistency Score: -0.0107

=== [604/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.45it/s]
Hypertuning:  17%|█▋        | 604/3456 [15:02<1:03:46,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.6084
➡️ Total Profit: ₹-28,336.18
➡️ Equity Curve R²: 0.7954
➡️ Monthly Consistency Score: -0.1108

=== [605/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.91it/s]
Hypertuning:  18%|█▊        | 605/3456 [15:03<1:04:47,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5818
➡️ Total Profit: ₹18,819.66
➡️ Equity Curve R²: 0.0517
➡️ Monthly Consistency Score: 0.0744

=== [606/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.71it/s]
Hypertuning:  18%|█▊        | 606/3456 [15:05<1:04:04,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.8389
➡️ Total Profit: ₹36,098.27
➡️ Equity Curve R²: 0.0403
➡️ Monthly Consistency Score: 0.1414

=== [607/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.68it/s]
Hypertuning:  18%|█▊        | 607/3456 [15:06<1:04:21,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5635
➡️ Total Profit: ₹27,357.41
➡️ Equity Curve R²: 0.1140
➡️ Monthly Consistency Score: 0.1063

=== [608/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.87it/s]
Hypertuning:  18%|█▊        | 608/3456 [15:08<1:05:06,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.5212
➡️ Total Profit: ₹62,772.83
➡️ Equity Curve R²: 0.6336
➡️ Monthly Consistency Score: 0.3159

=== [609/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.17it/s]
Hypertuning:  18%|█▊        | 609/3456 [15:09<1:05:03,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.8364
➡️ Total Profit: ₹-87,229.27
➡️ Equity Curve R²: 0.9707
➡️ Monthly Consistency Score: -0.3763

=== [610/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.94it/s]
Hypertuning:  18%|█▊        | 610/3456 [15:10<1:05:38,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.4532
➡️ Total Profit: ₹-24,434.96
➡️ Equity Curve R²: 0.8723
➡️ Monthly Consistency Score: -0.0981

=== [611/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.49it/s]
Hypertuning:  18%|█▊        | 611/3456 [15:12<1:04:48,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0516
➡️ Total Profit: ₹-2,110.86
➡️ Equity Curve R²: 0.3922
➡️ Monthly Consistency Score: -0.0081

=== [612/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.35it/s]
Hypertuning:  18%|█▊        | 612/3456 [15:13<1:04:51,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.4945
➡️ Total Profit: ₹26,892.25
➡️ Equity Curve R²: 0.7787
➡️ Monthly Consistency Score: 0.1028

=== [613/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.09it/s]
Hypertuning:  18%|█▊        | 613/3456 [15:14<1:04:21,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3564
➡️ Total Profit: ₹-11,976.74
➡️ Equity Curve R²: 0.2267
➡️ Monthly Consistency Score: -0.0457

=== [614/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.00it/s]
Hypertuning:  18%|█▊        | 614/3456 [15:16<1:05:05,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0467
➡️ Total Profit: ₹-1,891.67
➡️ Equity Curve R²: 0.6141
➡️ Monthly Consistency Score: -0.0073

=== [615/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.40it/s]
Hypertuning:  18%|█▊        | 615/3456 [15:17<1:03:51,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.5851
➡️ Total Profit: ₹10,490.74
➡️ Equity Curve R²: 0.0175
➡️ Monthly Consistency Score: 0.0380

=== [616/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.36it/s]
Hypertuning:  18%|█▊        | 616/3456 [15:18<1:04:14,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5405
➡️ Total Profit: ₹11,845.67
➡️ Equity Curve R²: 0.0814
➡️ Monthly Consistency Score: 0.0515

=== [617/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.23it/s]
Hypertuning:  18%|█▊        | 617/3456 [15:20<1:03:44,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4616
➡️ Total Profit: ₹13,977.86
➡️ Equity Curve R²: 0.0129
➡️ Monthly Consistency Score: 0.0543

=== [618/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.88it/s]
Hypertuning:  18%|█▊        | 618/3456 [15:21<1:04:25,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.0653
➡️ Total Profit: ₹65,813.90
➡️ Equity Curve R²: 0.4190
➡️ Monthly Consistency Score: 0.2901

=== [619/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 111.90it/s]
Hypertuning:  18%|█▊        | 619/3456 [15:22<1:03:32,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.0685
➡️ Total Profit: ₹-2,737.53
➡️ Equity Curve R²: 0.1980
➡️ Monthly Consistency Score: -0.0105

=== [620/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.69it/s]
Hypertuning:  18%|█▊        | 620/3456 [15:24<1:04:12,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.5084
➡️ Total Profit: ₹-18,863.46
➡️ Equity Curve R²: 0.5595
➡️ Monthly Consistency Score: -0.0771

=== [621/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.08it/s]
Hypertuning:  18%|█▊        | 621/3456 [15:25<1:03:41,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6010
➡️ Total Profit: ₹19,444.49
➡️ Equity Curve R²: 0.0647
➡️ Monthly Consistency Score: 0.0779

=== [622/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.13it/s]
Hypertuning:  18%|█▊        | 622/3456 [15:27<1:04:46,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.8686
➡️ Total Profit: ₹38,358.27
➡️ Equity Curve R²: 0.0559
➡️ Monthly Consistency Score: 0.1476

=== [623/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.02it/s]
Hypertuning:  18%|█▊        | 623/3456 [15:28<1:03:37,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.5635
➡️ Total Profit: ₹27,357.41
➡️ Equity Curve R²: 0.0674
➡️ Monthly Consistency Score: 0.1066

=== [624/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.85it/s]
Hypertuning:  18%|█▊        | 624/3456 [15:29<1:03:56,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.5212
➡️ Total Profit: ₹62,772.83
➡️ Equity Curve R²: 0.6336
➡️ Monthly Consistency Score: 0.3159

=== [625/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.32it/s]
Hypertuning:  18%|█▊        | 625/3456 [15:31<1:03:35,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.8265
➡️ Total Profit: ₹-87,159.18
➡️ Equity Curve R²: 0.9716
➡️ Monthly Consistency Score: -0.3739

=== [626/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.95it/s]
Hypertuning:  18%|█▊        | 626/3456 [15:32<1:04:21,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3730
➡️ Total Profit: ₹-17,225.79
➡️ Equity Curve R²: 0.8226
➡️ Monthly Consistency Score: -0.0665

=== [627/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.99it/s]
Hypertuning:  18%|█▊        | 627/3456 [15:33<1:03:15,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.1063
➡️ Total Profit: ₹-4,909.43
➡️ Equity Curve R²: 0.4784
➡️ Monthly Consistency Score: -0.0178

=== [628/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.72it/s]
Hypertuning:  18%|█▊        | 628/3456 [15:35<1:02:31,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 0.2359
➡️ Total Profit: ₹7,722.35
➡️ Equity Curve R²: 0.0093
➡️ Monthly Consistency Score: 0.0291

=== [629/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.98it/s]
Hypertuning:  18%|█▊        | 629/3456 [15:36<1:03:35,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.9089
➡️ Total Profit: ₹21,045.38
➡️ Equity Curve R²: 0.6229
➡️ Monthly Consistency Score: 0.0780

=== [630/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.77it/s]
Hypertuning:  18%|█▊        | 630/3456 [15:37<1:04:37,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.4413
➡️ Total Profit: ₹28,804.77
➡️ Equity Curve R²: 0.2580
➡️ Monthly Consistency Score: 0.1096

=== [631/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.98it/s]
Hypertuning:  18%|█▊        | 631/3456 [15:39<1:03:37,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.4212
➡️ Total Profit: ₹33,259.04
➡️ Equity Curve R²: 0.0208
➡️ Monthly Consistency Score: 0.1186

=== [632/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.55it/s]
Hypertuning:  18%|█▊        | 632/3456 [15:40<1:02:32,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 0.3842
➡️ Total Profit: ₹10,634.83
➡️ Equity Curve R²: 0.2254
➡️ Monthly Consistency Score: 0.0395

=== [633/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.25it/s]
Hypertuning:  18%|█▊        | 633/3456 [15:41<1:03:27,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1912
➡️ Total Profit: ₹5,789.27
➡️ Equity Curve R²: 0.2336
➡️ Monthly Consistency Score: 0.0221

=== [634/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.02it/s]
Hypertuning:  18%|█▊        | 634/3456 [15:43<1:04:10,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.3597
➡️ Total Profit: ₹9,132.05
➡️ Equity Curve R²: 0.0001
➡️ Monthly Consistency Score: 0.0378

=== [635/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.86it/s]
Hypertuning:  18%|█▊        | 635/3456 [15:44<1:03:20,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1955
➡️ Total Profit: ₹-7,626.16
➡️ Equity Curve R²: 0.2448
➡️ Monthly Consistency Score: -0.0286

=== [636/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.05it/s]
Hypertuning:  18%|█▊        | 636/3456 [15:45<1:02:17,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: -0.5689
➡️ Total Profit: ₹-24,076.18
➡️ Equity Curve R²: 0.7269
➡️ Monthly Consistency Score: -0.0953

=== [637/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.77it/s]
Hypertuning:  18%|█▊        | 637/3456 [15:47<1:03:16,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2107
➡️ Total Profit: ₹7,479.66
➡️ Equity Curve R²: 0.1833
➡️ Monthly Consistency Score: 0.0284

=== [638/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.27it/s]
Hypertuning:  18%|█▊        | 638/3456 [15:48<1:04:42,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.0517
➡️ Total Profit: ₹42,878.27
➡️ Equity Curve R²: 0.0073
➡️ Monthly Consistency Score: 0.1695

=== [639/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.62it/s]
Hypertuning:  18%|█▊        | 639/3456 [15:50<1:03:41,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5299
➡️ Total Profit: ₹25,726.04
➡️ Equity Curve R²: 0.1102
➡️ Monthly Consistency Score: 0.1012

=== [640/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.28it/s]
Hypertuning:  19%|█▊        | 640/3456 [15:51<1:02:40,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 3.5212
➡️ Total Profit: ₹62,772.83
➡️ Equity Curve R²: 0.6336
➡️ Monthly Consistency Score: 0.3159

=== [641/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.87it/s]
Hypertuning:  19%|█▊        | 641/3456 [15:52<1:03:37,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.8250
➡️ Total Profit: ₹-83,375.70
➡️ Equity Curve R²: 0.9668
➡️ Monthly Consistency Score: -0.3697

=== [642/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.91it/s]
Hypertuning:  19%|█▊        | 642/3456 [15:54<1:02:55,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.3812
➡️ Total Profit: ₹-20,618.55
➡️ Equity Curve R²: 0.8228
➡️ Monthly Consistency Score: -0.0790

=== [643/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.76it/s]
Hypertuning:  19%|█▊        | 643/3456 [15:55<1:03:17,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2791
➡️ Total Profit: ₹9,369.14
➡️ Equity Curve R²: 0.1874
➡️ Monthly Consistency Score: 0.0368

=== [644/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.70it/s]
Hypertuning:  19%|█▊        | 644/3456 [15:56<1:02:18,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 2.3721
➡️ Total Profit: ₹40,420.39
➡️ Equity Curve R²: 0.8572
➡️ Monthly Consistency Score: 0.1464

=== [645/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.44it/s]
Hypertuning:  19%|█▊        | 645/3456 [15:58<1:03:26,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2422
➡️ Total Profit: ₹-7,094.74
➡️ Equity Curve R²: 0.1497
➡️ Monthly Consistency Score: -0.0272

=== [646/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.24it/s]
Hypertuning:  19%|█▊        | 646/3456 [15:59<1:04:08,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.8204
➡️ Total Profit: ₹22,455.69
➡️ Equity Curve R²: 0.0083
➡️ Monthly Consistency Score: 0.0841

=== [647/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.19it/s]
Hypertuning:  19%|█▊        | 647/3456 [16:00<1:03:34,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.1308
➡️ Total Profit: ₹20,273.48
➡️ Equity Curve R²: 0.2676
➡️ Monthly Consistency Score: 0.0791

=== [648/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.68it/s]
Hypertuning:  19%|█▉        | 648/3456 [16:02<1:02:27,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 0.5405
➡️ Total Profit: ₹11,845.67
➡️ Equity Curve R²: 0.0814
➡️ Monthly Consistency Score: 0.0503

=== [649/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.65it/s]
Hypertuning:  19%|█▉        | 649/3456 [16:03<1:03:22,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3732
➡️ Total Profit: ₹10,830.21
➡️ Equity Curve R²: 0.0676
➡️ Monthly Consistency Score: 0.0433

=== [650/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.31it/s]
Hypertuning:  19%|█▉        | 650/3456 [16:04<1:04:08,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.0036
➡️ Total Profit: ₹92.05
➡️ Equity Curve R²: 0.0509
➡️ Monthly Consistency Score: 0.0004

=== [651/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.86it/s]
Hypertuning:  19%|█▉        | 651/3456 [16:06<1:03:05,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1908
➡️ Total Profit: ₹-7,623.42
➡️ Equity Curve R²: 0.1653
➡️ Monthly Consistency Score: -0.0296

=== [652/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.47it/s]
Hypertuning:  19%|█▉        | 652/3456 [16:07<1:02:04,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: -0.5689
➡️ Total Profit: ₹-24,076.18
➡️ Equity Curve R²: 0.7269
➡️ Monthly Consistency Score: -0.0953

=== [653/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.64it/s]
Hypertuning:  19%|█▉        | 653/3456 [16:08<1:02:49,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.6207
➡️ Total Profit: ₹20,079.66
➡️ Equity Curve R²: 0.0503
➡️ Monthly Consistency Score: 0.0800

=== [654/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.39it/s]
Hypertuning:  19%|█▉        | 654/3456 [16:10<1:03:34,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.0240
➡️ Total Profit: ₹41,749.19
➡️ Equity Curve R²: 0.0114
➡️ Monthly Consistency Score: 0.1654

=== [655/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.10it/s]
Hypertuning:  19%|█▉        | 655/3456 [16:11<1:02:45,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.5127
➡️ Total Profit: ₹25,728.78
➡️ Equity Curve R²: 0.0987
➡️ Monthly Consistency Score: 0.1005

=== [656/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.23it/s]
Hypertuning:  19%|█▉        | 656/3456 [16:12<1:03:19,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.5212
➡️ Total Profit: ₹62,772.83
➡️ Equity Curve R²: 0.6336
➡️ Monthly Consistency Score: 0.3159

=== [657/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.27it/s]
Hypertuning:  19%|█▉        | 657/3456 [16:14<1:03:13,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.8295
➡️ Total Profit: ₹-89,113.16
➡️ Equity Curve R²: 0.9691
➡️ Monthly Consistency Score: -0.3907

=== [658/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.76it/s]
Hypertuning:  19%|█▉        | 658/3456 [16:15<1:03:57,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.5091
➡️ Total Profit: ₹-27,047.60
➡️ Equity Curve R²: 0.8869
➡️ Monthly Consistency Score: -0.1023

=== [659/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.90it/s]
Hypertuning:  19%|█▉        | 659/3456 [16:17<1:02:58,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0201
➡️ Total Profit: ₹-872.17
➡️ Equity Curve R²: 0.2284
➡️ Monthly Consistency Score: -0.0035

=== [660/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.57it/s]
Hypertuning:  19%|█▉        | 660/3456 [16:18<1:03:29,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.0848
➡️ Total Profit: ₹20,509.43
➡️ Equity Curve R²: 0.7176
➡️ Monthly Consistency Score: 0.0751

=== [661/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.81it/s]
Hypertuning:  19%|█▉        | 661/3456 [16:19<1:03:16,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2535
➡️ Total Profit: ₹-8,824.39
➡️ Equity Curve R²: 0.2572
➡️ Monthly Consistency Score: -0.0329

=== [662/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.15it/s]
Hypertuning:  19%|█▉        | 662/3456 [16:21<1:02:33,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.7296
➡️ Total Profit: ₹18,366.61
➡️ Equity Curve R²: 0.0016
➡️ Monthly Consistency Score: 0.0676

=== [663/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.44it/s]
Hypertuning:  19%|█▉        | 663/3456 [16:22<1:02:50,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4267
➡️ Total Profit: ₹12,065.22
➡️ Equity Curve R²: 0.0432
➡️ Monthly Consistency Score: 0.0444

=== [664/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.24it/s]
Hypertuning:  19%|█▉        | 664/3456 [16:23<1:02:32,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.7172
➡️ Total Profit: ₹11,551.97
➡️ Equity Curve R²: 0.2910
➡️ Monthly Consistency Score: 0.0495

=== [665/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.35it/s]
Hypertuning:  19%|█▉        | 665/3456 [16:25<1:03:35,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4145
➡️ Total Profit: ₹-21,927.91
➡️ Equity Curve R²: 0.8307
➡️ Monthly Consistency Score: -0.0788

=== [666/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.08it/s]
Hypertuning:  19%|█▉        | 666/3456 [16:26<1:02:53,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.7017
➡️ Total Profit: ₹62,422.98
➡️ Equity Curve R²: 0.3360
➡️ Monthly Consistency Score: 0.2773

=== [667/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.20it/s]
Hypertuning:  19%|█▉        | 667/3456 [16:27<1:02:59,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4685
➡️ Total Profit: ₹-19,378.51
➡️ Equity Curve R²: 0.6628
➡️ Monthly Consistency Score: -0.0747

=== [668/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.98it/s]
Hypertuning:  19%|█▉        | 668/3456 [16:29<1:03:29,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3834
➡️ Total Profit: ₹-14,603.46
➡️ Equity Curve R²: 0.3762
➡️ Monthly Consistency Score: -0.0605

=== [669/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.83it/s]
Hypertuning:  19%|█▉        | 669/3456 [16:30<1:03:02,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1256
➡️ Total Profit: ₹-4,274.65
➡️ Equity Curve R²: 0.6124
➡️ Monthly Consistency Score: -0.0159

=== [670/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.50it/s]
Hypertuning:  19%|█▉        | 670/3456 [16:31<1:02:13,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.1071
➡️ Total Profit: ₹45,138.27
➡️ Equity Curve R²: 0.0097
➡️ Monthly Consistency Score: 0.1763

=== [671/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.56it/s]
Hypertuning:  19%|█▉        | 671/3456 [16:33<1:02:39,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4204
➡️ Total Profit: ₹22,466.04
➡️ Equity Curve R²: 0.3032
➡️ Monthly Consistency Score: 0.0883

=== [672/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.48it/s]
Hypertuning:  19%|█▉        | 672/3456 [16:34<1:01:58,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 3.4018
➡️ Total Profit: ₹60,644.65
➡️ Equity Curve R²: 0.6446
➡️ Monthly Consistency Score: 0.3098

=== [673/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.26it/s]
Hypertuning:  19%|█▉        | 673/3456 [16:35<1:02:42,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.7393
➡️ Total Profit: ₹-65,533.84
➡️ Equity Curve R²: 0.9439
➡️ Monthly Consistency Score: -0.2856

=== [674/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.69it/s]
Hypertuning:  20%|█▉        | 674/3456 [16:37<1:03:40,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0804
➡️ Total Profit: ₹-2,879.99
➡️ Equity Curve R²: 0.6656
➡️ Monthly Consistency Score: -0.0128

=== [675/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.07it/s]
Hypertuning:  20%|█▉        | 675/3456 [16:38<1:03:02,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1596
➡️ Total Profit: ₹-10,264.50
➡️ Equity Curve R²: 0.7326
➡️ Monthly Consistency Score: -0.0382

=== [676/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.52it/s]
Hypertuning:  20%|█▉        | 676/3456 [16:39<1:01:55,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.8562
➡️ Total Profit: ₹23,193.31
➡️ Equity Curve R²: 0.1099
➡️ Monthly Consistency Score: 0.0882

=== [677/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.74it/s]
Hypertuning:  20%|█▉        | 677/3456 [16:41<1:02:33,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2332
➡️ Total Profit: ₹-7,890.79
➡️ Equity Curve R²: 0.3552
➡️ Monthly Consistency Score: -0.0281

=== [678/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.23it/s]
Hypertuning:  20%|█▉        | 678/3456 [16:42<1:03:17,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.2057
➡️ Total Profit: ₹50,713.98
➡️ Equity Curve R²: 0.8484
➡️ Monthly Consistency Score: 0.2023

=== [679/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 105.01it/s]
Hypertuning:  20%|█▉        | 679/3456 [16:44<1:02:18,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.0206
➡️ Total Profit: ₹709.99
➡️ Equity Curve R²: 0.2030
➡️ Monthly Consistency Score: 0.0029

=== [680/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.97it/s]
Hypertuning:  20%|█▉        | 680/3456 [16:45<1:01:52,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.3047
➡️ Total Profit: ₹27,372.17
➡️ Equity Curve R²: 0.3449
➡️ Monthly Consistency Score: 0.1202

=== [681/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.21it/s]
Hypertuning:  20%|█▉        | 681/3456 [16:46<1:02:53,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1734
➡️ Total Profit: ₹-9,209.19
➡️ Equity Curve R²: 0.5402
➡️ Monthly Consistency Score: -0.0342

=== [682/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.13it/s]
Hypertuning:  20%|█▉        | 682/3456 [16:48<1:03:34,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.4495
➡️ Total Profit: ₹29,477.57
➡️ Equity Curve R²: 0.5542
➡️ Monthly Consistency Score: 0.1195

=== [683/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.52it/s]
Hypertuning:  20%|█▉        | 683/3456 [16:49<1:02:35,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1610
➡️ Total Profit: ₹5,078.34
➡️ Equity Curve R²: 0.0167
➡️ Monthly Consistency Score: 0.0200

=== [684/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.61it/s]
Hypertuning:  20%|█▉        | 684/3456 [16:50<1:03:30,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.7583
➡️ Total Profit: ₹24,230.29
➡️ Equity Curve R²: 0.0304
➡️ Monthly Consistency Score: 0.1057

=== [685/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 105.69it/s]
Hypertuning:  20%|█▉        | 685/3456 [16:52<1:02:53,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.7492
➡️ Total Profit: ₹20,294.83
➡️ Equity Curve R²: 0.2410
➡️ Monthly Consistency Score: 0.0728

=== [686/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.22it/s]
Hypertuning:  20%|█▉        | 686/3456 [16:53<1:01:59,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.3378
➡️ Total Profit: ₹60,963.79
➡️ Equity Curve R²: 0.1982
➡️ Monthly Consistency Score: 0.2613

=== [687/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.17it/s]
Hypertuning:  20%|█▉        | 687/3456 [16:54<1:02:19,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.0436
➡️ Total Profit: ₹59,960.15
➡️ Equity Curve R²: 0.2567
➡️ Monthly Consistency Score: 0.2642

=== [688/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 109.96it/s]
Hypertuning:  20%|█▉        | 688/3456 [16:56<1:01:24,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 3.8881
➡️ Total Profit: ₹66,252.95
➡️ Equity Curve R²: 0.5808
➡️ Monthly Consistency Score: 0.3145

=== [689/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.97it/s]
Hypertuning:  20%|█▉        | 689/3456 [16:57<1:02:33,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.7666
➡️ Total Profit: ₹-66,788.48
➡️ Equity Curve R²: 0.9513
➡️ Monthly Consistency Score: -0.2999

=== [690/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.23it/s]
Hypertuning:  20%|█▉        | 690/3456 [16:59<1:03:11,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.1223
➡️ Total Profit: ₹3,905.37
➡️ Equity Curve R²: 0.5109
➡️ Monthly Consistency Score: 0.0175

=== [691/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.77it/s]
Hypertuning:  20%|█▉        | 691/3456 [17:00<1:02:24,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.0936
➡️ Total Profit: ₹4,870.81
➡️ Equity Curve R²: 0.5645
➡️ Monthly Consistency Score: 0.0194

=== [692/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.25it/s]
Hypertuning:  20%|██        | 692/3456 [17:01<1:03:08,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.7230
➡️ Total Profit: ₹19,585.13
➡️ Equity Curve R²: 0.0590
➡️ Monthly Consistency Score: 0.0749

=== [693/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.41it/s]
Hypertuning:  20%|██        | 693/3456 [17:03<1:02:58,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4770
➡️ Total Profit: ₹-14,938.19
➡️ Equity Curve R²: 0.4870
➡️ Monthly Consistency Score: -0.0561

=== [694/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.89it/s]
Hypertuning:  20%|██        | 694/3456 [17:04<1:04:03,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 3.2057
➡️ Total Profit: ₹50,713.98
➡️ Equity Curve R²: 0.8448
➡️ Monthly Consistency Score: 0.2023

=== [695/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.94it/s]
Hypertuning:  20%|██        | 695/3456 [17:05<1:02:48,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.4817
➡️ Total Profit: ₹31,638.63
➡️ Equity Curve R²: 0.2291
➡️ Monthly Consistency Score: 0.1275

=== [696/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.63it/s]
Hypertuning:  20%|██        | 696/3456 [17:07<1:01:47,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.2033
➡️ Total Profit: ₹25,243.99
➡️ Equity Curve R²: 0.3590
➡️ Monthly Consistency Score: 0.1113

=== [697/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.53it/s]
Hypertuning:  20%|██        | 697/3456 [17:08<1:02:35,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1560
➡️ Total Profit: ₹-7,947.31
➡️ Equity Curve R²: 0.5182
➡️ Monthly Consistency Score: -0.0297

=== [698/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.17it/s]
Hypertuning:  20%|██        | 698/3456 [17:09<1:03:07,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.8385
➡️ Total Profit: ₹37,388.49
➡️ Equity Curve R²: 0.5328
➡️ Monthly Consistency Score: 0.1547

=== [699/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.25it/s]
Hypertuning:  20%|██        | 699/3456 [17:11<1:02:06,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1610
➡️ Total Profit: ₹5,078.34
➡️ Equity Curve R²: 0.0167
➡️ Monthly Consistency Score: 0.0200

=== [700/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.06it/s]
Hypertuning:  20%|██        | 700/3456 [17:12<1:01:15,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 0.7583
➡️ Total Profit: ₹24,230.29
➡️ Equity Curve R²: 0.0304
➡️ Monthly Consistency Score: 0.1057

=== [701/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.73it/s]
Hypertuning:  20%|██        | 701/3456 [17:13<1:02:16,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.0528
➡️ Total Profit: ₹27,854.83
➡️ Equity Curve R²: 0.3356
➡️ Monthly Consistency Score: 0.1020

=== [702/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.57it/s]
Hypertuning:  20%|██        | 702/3456 [17:15<1:02:06,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.9918
➡️ Total Profit: ₹56,443.79
➡️ Equity Curve R²: 0.1169
➡️ Monthly Consistency Score: 0.2389

=== [703/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.14it/s]
Hypertuning:  20%|██        | 703/3456 [17:16<1:02:21,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.0992
➡️ Total Profit: ₹61,591.52
➡️ Equity Curve R²: 0.2322
➡️ Monthly Consistency Score: 0.2711

=== [704/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.00it/s]
Hypertuning:  20%|██        | 704/3456 [17:17<1:01:18,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 3.6381
➡️ Total Profit: ₹61,992.95
➡️ Equity Curve R²: 0.6063
➡️ Monthly Consistency Score: 0.2817

=== [705/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.90it/s]
Hypertuning:  20%|██        | 705/3456 [17:19<1:02:07,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.7734
➡️ Total Profit: ₹-71,551.91
➡️ Equity Curve R²: 0.9600
➡️ Monthly Consistency Score: -0.3081

=== [706/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.21it/s]
Hypertuning:  20%|██        | 706/3456 [17:20<1:02:43,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1385
➡️ Total Profit: ₹-5,745.63
➡️ Equity Curve R²: 0.6911
➡️ Monthly Consistency Score: -0.0253

=== [707/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.69it/s]
Hypertuning:  20%|██        | 707/3456 [17:22<1:01:46,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3078
➡️ Total Profit: ₹-18,416.11
➡️ Equity Curve R²: 0.7699
➡️ Monthly Consistency Score: -0.0717

=== [708/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.46it/s]
Hypertuning:  20%|██        | 708/3456 [17:23<1:02:15,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.1543
➡️ Total Profit: ₹36,708.81
➡️ Equity Curve R²: 0.7681
➡️ Monthly Consistency Score: 0.1386

=== [709/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.38it/s]
Hypertuning:  21%|██        | 709/3456 [17:24<1:02:09,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2823
➡️ Total Profit: ₹-8,015.24
➡️ Equity Curve R²: 0.1594
➡️ Monthly Consistency Score: -0.0313

=== [710/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.84it/s]
Hypertuning:  21%|██        | 710/3456 [17:26<1:02:59,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.2672
➡️ Total Profit: ₹27,066.61
➡️ Equity Curve R²: 0.4911
➡️ Monthly Consistency Score: 0.1003

=== [711/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)
<ipython-input-10-980624002>:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_data['Signal'] = temp_data['Signal'].astype(int)

100%|██████████| 1/1 [00:00<00:00, 122.62it/s]
Hypertuning:  21%|██        | 711/3456 [17:27<1:02:04,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.3683
➡️ Total Profit: ₹7,253.11
➡️ Equity Curve R²: 0.2083
➡️ Monthly Consistency Score: 0.0285

=== [712/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.96it/s]
Hypertuning:  21%|██        | 712/3456 [17:28<1:02:28,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1746
➡️ Total Profit: ₹24,642.11
➡️ Equity Curve R²: 0.3790
➡️ Monthly Consistency Score: 0.1057

=== [713/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.01it/s]
Hypertuning:  21%|██        | 713/3456 [17:30<1:02:04,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0076
➡️ Total Profit: ₹-388.25
➡️ Equity Curve R²: 0.4109
➡️ Monthly Consistency Score: -0.0015

=== [714/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.33it/s]
Hypertuning:  21%|██        | 714/3456 [17:31<1:02:41,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.5210
➡️ Total Profit: ₹31,739.41
➡️ Equity Curve R²: 0.4622
➡️ Monthly Consistency Score: 0.1306

=== [715/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.85it/s]
Hypertuning:  21%|██        | 715/3456 [17:32<1:01:35,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.4583
➡️ Total Profit: ₹-21,357.94
➡️ Equity Curve R²: 0.8458
➡️ Monthly Consistency Score: -0.0789

=== [716/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.57it/s]
Hypertuning:  21%|██        | 716/3456 [17:34<1:02:18,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0540
➡️ Total Profit: ₹2,926.64
➡️ Equity Curve R²: 0.5218
➡️ Monthly Consistency Score: 0.0117

=== [717/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.62it/s]
Hypertuning:  21%|██        | 717/3456 [17:35<1:01:49,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.2052
➡️ Total Profit: ₹30,372.01
➡️ Equity Curve R²: 0.4188
➡️ Monthly Consistency Score: 0.1118

=== [718/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.85it/s]
Hypertuning:  21%|██        | 718/3456 [17:37<1:02:41,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.8079
➡️ Total Profit: ₹55,314.71
➡️ Equity Curve R²: 0.0838
➡️ Monthly Consistency Score: 0.2224

=== [719/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.10it/s]
Hypertuning:  21%|██        | 719/3456 [17:38<1:01:48,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.7255
➡️ Total Profit: ₹53,437.41
➡️ Equity Curve R²: 0.2191
➡️ Monthly Consistency Score: 0.2308

=== [720/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.42it/s]
Hypertuning:  21%|██        | 720/3456 [17:39<1:01:03,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 6.2351
➡️ Total Profit: ₹71,300.12
➡️ Equity Curve R²: 0.7025
➡️ Monthly Consistency Score: 0.3719

=== [721/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.84it/s]
Hypertuning:  21%|██        | 721/3456 [17:41<1:02:13,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.7623
➡️ Total Profit: ₹-68,051.96
➡️ Equity Curve R²: 0.9476
➡️ Monthly Consistency Score: -0.2937

=== [722/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.83it/s]
Hypertuning:  21%|██        | 722/3456 [17:42<1:03:14,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.0318
➡️ Total Profit: ₹-1,138.23
➡️ Equity Curve R²: 0.6377
➡️ Monthly Consistency Score: -0.0050

=== [723/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.34it/s]
Hypertuning:  21%|██        | 723/3456 [17:43<1:02:02,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0896
➡️ Total Profit: ₹-5,763.18
➡️ Equity Curve R²: 0.6873
➡️ Monthly Consistency Score: -0.0208

=== [724/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.24it/s]
Hypertuning:  21%|██        | 724/3456 [17:45<1:02:40,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.8562
➡️ Total Profit: ₹23,193.31
➡️ Equity Curve R²: 0.1099
➡️ Monthly Consistency Score: 0.0882

=== [725/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.09it/s]
Hypertuning:  21%|██        | 725/3456 [17:46<1:02:18,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2518
➡️ Total Profit: ₹-8,520.32
➡️ Equity Curve R²: 0.3829
➡️ Monthly Consistency Score: -0.0305

=== [726/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.62it/s]
Hypertuning:  21%|██        | 726/3456 [17:47<1:01:23,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.6070
➡️ Total Profit: ₹57,063.06
➡️ Equity Curve R²: 0.8590
➡️ Monthly Consistency Score: 0.2221

=== [727/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.56it/s]
Hypertuning:  21%|██        | 727/3456 [17:49<1:01:40,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0206
➡️ Total Profit: ₹709.99
➡️ Equity Curve R²: 0.2030
➡️ Monthly Consistency Score: 0.0029

=== [728/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.92it/s]
Hypertuning:  21%|██        | 728/3456 [17:50<1:02:14,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.3047
➡️ Total Profit: ₹27,372.17
➡️ Equity Curve R²: 0.3449
➡️ Monthly Consistency Score: 0.1202

=== [729/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.68it/s]
Hypertuning:  21%|██        | 729/3456 [17:52<1:01:56,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1853
➡️ Total Profit: ₹-9,838.72
➡️ Equity Curve R²: 0.5492
➡️ Monthly Consistency Score: -0.0365

=== [730/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.00it/s]
Hypertuning:  21%|██        | 730/3456 [17:53<1:02:41,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.4495
➡️ Total Profit: ₹29,477.57
➡️ Equity Curve R²: 0.5542
➡️ Monthly Consistency Score: 0.1195

=== [731/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.61it/s]
Hypertuning:  21%|██        | 731/3456 [17:54<1:01:49,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2243
➡️ Total Profit: ₹6,709.71
➡️ Equity Curve R²: 0.0015
➡️ Monthly Consistency Score: 0.0259

=== [732/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.09it/s]
Hypertuning:  21%|██        | 732/3456 [17:56<1:02:09,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.7583
➡️ Total Profit: ₹24,230.29
➡️ Equity Curve R²: 0.0304
➡️ Monthly Consistency Score: 0.1057

=== [733/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.27it/s]
Hypertuning:  21%|██        | 733/3456 [17:57<1:01:46,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.7492
➡️ Total Profit: ₹20,294.83
➡️ Equity Curve R²: 0.2410
➡️ Monthly Consistency Score: 0.0728

=== [734/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.45it/s]
Hypertuning:  21%|██        | 734/3456 [17:58<1:02:16,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.3378
➡️ Total Profit: ₹60,963.79
➡️ Equity Curve R²: 0.1982
➡️ Monthly Consistency Score: 0.2613

=== [735/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.31it/s]
Hypertuning:  21%|██▏       | 735/3456 [18:00<1:01:09,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.0436
➡️ Total Profit: ₹59,960.15
➡️ Equity Curve R²: 0.2567
➡️ Monthly Consistency Score: 0.2642

=== [736/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.14it/s]
Hypertuning:  21%|██▏       | 736/3456 [18:01<1:01:35,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.8881
➡️ Total Profit: ₹66,252.95
➡️ Equity Curve R²: 0.5808
➡️ Monthly Consistency Score: 0.3145

=== [737/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.57it/s]
Hypertuning:  21%|██▏       | 737/3456 [18:02<1:01:20,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.7809
➡️ Total Profit: ₹-72,461.77
➡️ Equity Curve R²: 0.9541
➡️ Monthly Consistency Score: -0.3338

=== [738/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.56it/s]
Hypertuning:  21%|██▏       | 738/3456 [18:04<1:02:07,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.0639
➡️ Total Profit: ₹2,250.85
➡️ Equity Curve R²: 0.4840
➡️ Monthly Consistency Score: 0.0098

=== [739/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.89it/s]
Hypertuning:  21%|██▏       | 739/3456 [18:05<1:01:30,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3336
➡️ Total Profit: ₹-18,869.20
➡️ Equity Curve R²: 0.8397
➡️ Monthly Consistency Score: -0.0796

=== [740/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.14it/s]
Hypertuning:  21%|██▏       | 740/3456 [18:07<1:00:30,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.7691
➡️ Total Profit: ₹32,448.81
➡️ Equity Curve R²: 0.5935
➡️ Monthly Consistency Score: 0.1221

=== [741/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.03it/s]
Hypertuning:  21%|██▏       | 741/3456 [18:08<1:01:22,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4456
➡️ Total Profit: ₹-14,308.66
➡️ Equity Curve R²: 0.4675
➡️ Monthly Consistency Score: -0.0535

=== [742/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.70it/s]
Hypertuning:  21%|██▏       | 742/3456 [18:09<1:00:43,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 3.4640
➡️ Total Profit: ₹54,801.22
➡️ Equity Curve R²: 0.8502
➡️ Monthly Consistency Score: 0.2114

=== [743/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.53it/s]
Hypertuning:  21%|██▏       | 743/3456 [18:11<1:00:54,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.0306
➡️ Total Profit: ₹18,621.74
➡️ Equity Curve R²: 0.4543
➡️ Monthly Consistency Score: 0.0776

=== [744/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.12it/s]
Hypertuning:  22%|██▏       | 744/3456 [18:12<1:01:26,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.9715
➡️ Total Profit: ₹20,382.11
➡️ Equity Curve R²: 0.3861
➡️ Monthly Consistency Score: 0.0901

=== [745/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.09it/s]
Hypertuning:  22%|██▏       | 745/3456 [18:13<1:01:09,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0937
➡️ Total Profit: ₹-4,795.90
➡️ Equity Curve R²: 0.4804
➡️ Monthly Consistency Score: -0.0185

=== [746/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.44it/s]
Hypertuning:  22%|██▏       | 746/3456 [18:15<1:01:56,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.9494
➡️ Total Profit: ₹19,306.65
➡️ Equity Curve R²: 0.4060
➡️ Monthly Consistency Score: 0.0768

=== [747/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.08it/s]
Hypertuning:  22%|██▏       | 747/3456 [18:16<1:01:00,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0434
➡️ Total Profit: ₹-1,438.92
➡️ Equity Curve R²: 0.1062
➡️ Monthly Consistency Score: -0.0056

=== [748/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.44it/s]
Hypertuning:  22%|██▏       | 748/3456 [18:17<1:00:17,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.7583
➡️ Total Profit: ₹24,230.29
➡️ Equity Curve R²: 0.0304
➡️ Monthly Consistency Score: 0.1057

=== [749/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.19it/s]
Hypertuning:  22%|██▏       | 749/3456 [18:19<1:01:11,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.0283
➡️ Total Profit: ₹27,853.89
➡️ Equity Curve R²: 0.3253
➡️ Monthly Consistency Score: 0.1019

=== [750/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.51it/s]
Hypertuning:  22%|██▏       | 750/3456 [18:20<1:00:30,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.3982
➡️ Total Profit: ₹59,832.87
➡️ Equity Curve R²: 0.2415
➡️ Monthly Consistency Score: 0.2579

=== [751/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.30it/s]
Hypertuning:  22%|██▏       | 751/3456 [18:21<1:00:44,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.8836
➡️ Total Profit: ₹58,331.52
➡️ Equity Curve R²: 0.2834
➡️ Monthly Consistency Score: 0.2587

=== [752/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.50it/s]
Hypertuning:  22%|██▏       | 752/3456 [18:23<59:48,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 3.8881
➡️ Total Profit: ₹66,252.95
➡️ Equity Curve R²: 0.5808
➡️ Monthly Consistency Score: 0.3145

=== [753/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.02it/s]
Hypertuning:  22%|██▏       | 753/3456 [18:24<1:00:50,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.7979
➡️ Total Profit: ₹-72,524.06
➡️ Equity Curve R²: 0.9555
➡️ Monthly Consistency Score: -0.3258

=== [754/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.67it/s]
Hypertuning:  22%|██▏       | 754/3456 [18:25<1:01:26,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4823
➡️ Total Profit: ₹-29,567.48
➡️ Equity Curve R²: 0.8730
➡️ Monthly Consistency Score: -0.1248

=== [755/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.24it/s]
Hypertuning:  22%|██▏       | 755/3456 [18:27<1:00:30,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.2475
➡️ Total Profit: ₹-10,657.30
➡️ Equity Curve R²: 0.6745
➡️ Monthly Consistency Score: -0.0418

=== [756/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 130.59it/s]
Hypertuning:  22%|██▏       | 756/3456 [18:28<1:01:09,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5641
➡️ Total Profit: ₹16,149.67
➡️ Equity Curve R²: 0.1065
➡️ Monthly Consistency Score: 0.0548

=== [757/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.76it/s]
Hypertuning:  22%|██▏       | 757/3456 [18:30<1:01:05,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1608
➡️ Total Profit: ₹-4,861.01
➡️ Equity Curve R²: 0.2123
➡️ Monthly Consistency Score: -0.0185

=== [758/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.68it/s]
Hypertuning:  22%|██▏       | 758/3456 [18:31<1:01:41,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.2584
➡️ Total Profit: ₹45,497.65
➡️ Equity Curve R²: 0.6420
➡️ Monthly Consistency Score: 0.1680

=== [759/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.16it/s]
Hypertuning:  22%|██▏       | 759/3456 [18:32<1:00:38,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.5698
➡️ Total Profit: ₹28,364.48
➡️ Equity Curve R²: 0.5653
➡️ Monthly Consistency Score: 0.1145

=== [760/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.49it/s]
Hypertuning:  22%|██▏       | 760/3456 [18:34<1:01:07,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.1748
➡️ Total Profit: ₹24,645.75
➡️ Equity Curve R²: 0.3940
➡️ Monthly Consistency Score: 0.1028

=== [761/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.89it/s]
Hypertuning:  22%|██▏       | 761/3456 [18:35<1:00:56,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.6015
➡️ Total Profit: ₹-53,815.91
➡️ Equity Curve R²: 0.9330
➡️ Monthly Consistency Score: -0.1871

=== [762/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.02it/s]
Hypertuning:  22%|██▏       | 762/3456 [18:36<1:01:36,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.8938
➡️ Total Profit: ₹18,177.57
➡️ Equity Curve R²: 0.3928
➡️ Monthly Consistency Score: 0.0698

=== [763/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.17it/s]
Hypertuning:  22%|██▏       | 763/3456 [18:38<1:00:37,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3462
➡️ Total Profit: ₹-12,503.83
➡️ Equity Curve R²: 0.5294
➡️ Monthly Consistency Score: -0.0481

=== [764/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.43it/s]
Hypertuning:  22%|██▏       | 764/3456 [18:39<59:40,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: -0.0595
➡️ Total Profit: ₹-3,461.54
➡️ Equity Curve R²: 0.5821
➡️ Monthly Consistency Score: -0.0136

=== [765/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.17it/s]
Hypertuning:  22%|██▏       | 765/3456 [18:40<1:00:40,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.2005
➡️ Total Profit: ₹31,007.18
➡️ Equity Curve R²: 0.4214
➡️ Monthly Consistency Score: 0.1153

=== [766/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.57it/s]
Hypertuning:  22%|██▏       | 766/3456 [18:42<1:01:20,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.2668
➡️ Total Profit: ₹44,853.69
➡️ Equity Curve R²: 0.0307
➡️ Monthly Consistency Score: 0.1899

=== [767/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.47it/s]
Hypertuning:  22%|██▏       | 767/3456 [18:43<1:00:28,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.1657
➡️ Total Profit: ₹45,291.52
➡️ Equity Curve R²: 0.0028
➡️ Monthly Consistency Score: 0.1848

=== [768/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.28it/s]
Hypertuning:  22%|██▏       | 768/3456 [18:44<59:26,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 3.7634
➡️ Total Profit: ₹64,128.41
➡️ Equity Curve R²: 0.6096
➡️ Monthly Consistency Score: 0.3166

=== [769/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.21it/s]
Hypertuning:  22%|██▏       | 769/3456 [18:46<1:00:15,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.5912
➡️ Total Profit: ₹-49,208.98
➡️ Equity Curve R²: 0.9185
➡️ Monthly Consistency Score: -0.2054

=== [770/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.27it/s]
Hypertuning:  22%|██▏       | 770/3456 [18:47<1:00:52,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2325
➡️ Total Profit: ₹-8,090.39
➡️ Equity Curve R²: 0.6886
➡️ Monthly Consistency Score: -0.0359

=== [771/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.54it/s]
Hypertuning:  22%|██▏       | 771/3456 [18:48<1:00:06,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.1631
➡️ Total Profit: ₹37,932.60
➡️ Equity Curve R²: 0.0222
➡️ Monthly Consistency Score: 0.1378

=== [772/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.78it/s]
Hypertuning:  22%|██▏       | 772/3456 [18:50<59:16,  1.32s/it]

➡️ Profit-to-Drawdown Ratio: 0.5978
➡️ Total Profit: ₹21,236.33
➡️ Equity Curve R²: 0.0130
➡️ Monthly Consistency Score: 0.0793

=== [773/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.73it/s]
Hypertuning:  22%|██▏       | 773/3456 [18:51<1:00:19,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1108
➡️ Total Profit: ₹-3,258.69
➡️ Equity Curve R²: 0.4425
➡️ Monthly Consistency Score: -0.0119

=== [774/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.82it/s]
Hypertuning:  22%|██▏       | 774/3456 [18:53<1:01:01,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0929
➡️ Total Profit: ₹-3,880.03
➡️ Equity Curve R²: 0.6663
➡️ Monthly Consistency Score: -0.0141

=== [775/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.96it/s]
Hypertuning:  22%|██▏       | 775/3456 [18:54<1:00:26,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.7235
➡️ Total Profit: ₹36,583.41
➡️ Equity Curve R²: 0.4533
➡️ Monthly Consistency Score: 0.1406

=== [776/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.79it/s]
Hypertuning:  22%|██▏       | 776/3456 [18:55<59:49,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.7149
➡️ Total Profit: ₹34,969.51
➡️ Equity Curve R²: 0.6761
➡️ Monthly Consistency Score: 0.1491

=== [777/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.33it/s]
Hypertuning:  22%|██▏       | 777/3456 [18:57<1:00:41,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0458
➡️ Total Profit: ₹2,141.15
➡️ Equity Curve R²: 0.3826
➡️ Monthly Consistency Score: 0.0079

=== [778/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.58it/s]
Hypertuning:  23%|██▎       | 778/3456 [18:58<1:01:15,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.2092
➡️ Total Profit: ₹35,401.73
➡️ Equity Curve R²: 0.4387
➡️ Monthly Consistency Score: 0.1199

=== [779/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.04it/s]
Hypertuning:  23%|██▎       | 779/3456 [18:59<1:00:08,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.4263
➡️ Total Profit: ₹30,217.16
➡️ Equity Curve R²: 0.1101
➡️ Monthly Consistency Score: 0.1381

=== [780/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.78it/s]
Hypertuning:  23%|██▎       | 780/3456 [19:01<59:16,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 0.4755
➡️ Total Profit: ₹16,182.19
➡️ Equity Curve R²: 0.0159
➡️ Monthly Consistency Score: 0.0636

=== [781/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.61it/s]
Hypertuning:  23%|██▎       | 781/3456 [19:02<1:00:20,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.3484
➡️ Total Profit: ₹32,274.70
➡️ Equity Curve R²: 0.5297
➡️ Monthly Consistency Score: 0.1181

=== [782/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.79it/s]
Hypertuning:  23%|██▎       | 782/3456 [19:03<59:46,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.4857
➡️ Total Profit: ₹64,586.78
➡️ Equity Curve R²: 0.2584
➡️ Monthly Consistency Score: 0.2508

=== [783/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.38it/s]
Hypertuning:  23%|██▎       | 783/3456 [19:05<1:00:15,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.2203
➡️ Total Profit: ₹78,152.55
➡️ Equity Curve R²: 0.5438
➡️ Monthly Consistency Score: 0.3077

=== [784/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.47it/s]
Hypertuning:  23%|██▎       | 784/3456 [19:06<1:00:45,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 4.5871
➡️ Total Profit: ₹68,384.78
➡️ Equity Curve R²: 0.7297
➡️ Monthly Consistency Score: 0.3188

=== [785/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.32it/s]
Hypertuning:  23%|██▎       | 785/3456 [19:07<1:00:35,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.6230
➡️ Total Profit: ₹-50,463.62
➡️ Equity Curve R²: 0.9241
➡️ Monthly Consistency Score: -0.2178

=== [786/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.55it/s]
Hypertuning:  23%|██▎       | 786/3456 [19:09<1:01:11,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.2325
➡️ Total Profit: ₹-8,086.87
➡️ Equity Curve R²: 0.7201
➡️ Monthly Consistency Score: -0.0364

=== [787/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.10it/s]
Hypertuning:  23%|██▎       | 787/3456 [19:10<1:00:19,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.9210
➡️ Total Profit: ₹33,041.23
➡️ Equity Curve R²: 0.0000
➡️ Monthly Consistency Score: 0.1213

=== [788/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.06it/s]
Hypertuning:  23%|██▎       | 788/3456 [19:11<59:23,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.5978
➡️ Total Profit: ₹21,236.33
➡️ Equity Curve R²: 0.0130
➡️ Monthly Consistency Score: 0.0793

=== [789/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.81it/s]
Hypertuning:  23%|██▎       | 789/3456 [19:13<1:00:23,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3255
➡️ Total Profit: ₹-8,755.62
➡️ Equity Curve R²: 0.4462
➡️ Monthly Consistency Score: -0.0329

=== [790/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.72it/s]
Hypertuning:  23%|██▎       | 790/3456 [19:14<1:01:13,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.2720
➡️ Total Profit: ₹-11,363.72
➡️ Equity Curve R²: 0.7460
➡️ Monthly Consistency Score: -0.0413

=== [791/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.28it/s]
Hypertuning:  23%|██▎       | 791/3456 [19:16<1:00:16,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.7234
➡️ Total Profit: ₹36,580.67
➡️ Equity Curve R²: 0.4540
➡️ Monthly Consistency Score: 0.1403

=== [792/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.29it/s]
Hypertuning:  23%|██▎       | 792/3456 [19:17<59:18,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.7149
➡️ Total Profit: ₹34,969.51
➡️ Equity Curve R²: 0.6761
➡️ Monthly Consistency Score: 0.1491

=== [793/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.05it/s]
Hypertuning:  23%|██▎       | 793/3456 [19:18<1:00:20,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0609
➡️ Total Profit: ₹2,771.62
➡️ Equity Curve R²: 0.3406
➡️ Monthly Consistency Score: 0.0105

=== [794/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.90it/s]
Hypertuning:  23%|██▎       | 794/3456 [19:20<1:01:04,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.2092
➡️ Total Profit: ₹35,401.73
➡️ Equity Curve R²: 0.4387
➡️ Monthly Consistency Score: 0.1199

=== [795/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.15it/s]
Hypertuning:  23%|██▎       | 795/3456 [19:21<1:00:05,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.5032
➡️ Total Profit: ₹31,845.79
➡️ Equity Curve R²: 0.1559
➡️ Monthly Consistency Score: 0.1446

=== [796/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.85it/s]
Hypertuning:  23%|██▎       | 796/3456 [19:22<59:12,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.4755
➡️ Total Profit: ₹16,182.19
➡️ Equity Curve R²: 0.0159
➡️ Monthly Consistency Score: 0.0636

=== [797/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.56it/s]
Hypertuning:  23%|██▎       | 797/3456 [19:24<1:00:12,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.6009
➡️ Total Profit: ₹37,312.82
➡️ Equity Curve R²: 0.5669
➡️ Monthly Consistency Score: 0.1376

=== [798/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.62it/s]
Hypertuning:  23%|██▎       | 798/3456 [19:25<59:32,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.2066
➡️ Total Profit: ₹62,323.10
➡️ Equity Curve R²: 0.2835
➡️ Monthly Consistency Score: 0.2397

=== [799/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.84it/s]
Hypertuning:  23%|██▎       | 799/3456 [19:26<59:43,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.2203
➡️ Total Profit: ₹78,152.55
➡️ Equity Curve R²: 0.5438
➡️ Monthly Consistency Score: 0.3077

=== [800/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.34it/s]
Hypertuning:  23%|██▎       | 800/3456 [19:28<58:50,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 4.5871
➡️ Total Profit: ₹68,384.78
➡️ Equity Curve R²: 0.7297
➡️ Monthly Consistency Score: 0.3188

=== [801/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.05it/s]
Hypertuning:  23%|██▎       | 801/3456 [19:29<59:47,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6991
➡️ Total Profit: ₹-61,526.12
➡️ Equity Curve R²: 0.9492
➡️ Monthly Consistency Score: -0.2684

=== [802/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.20it/s]
Hypertuning:  23%|██▎       | 802/3456 [19:30<1:00:34,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0354
➡️ Total Profit: ₹-1,210.59
➡️ Equity Curve R²: 0.4398
➡️ Monthly Consistency Score: -0.0051

=== [803/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.58it/s]
Hypertuning:  23%|██▎       | 803/3456 [19:32<59:47,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2182
➡️ Total Profit: ₹10,147.12
➡️ Equity Curve R²: 0.3299
➡️ Monthly Consistency Score: 0.0380

=== [804/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.91it/s]
Hypertuning:  23%|██▎       | 804/3456 [19:33<1:00:09,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.4911
➡️ Total Profit: ₹35,401.73
➡️ Equity Curve R²: 0.3433
➡️ Monthly Consistency Score: 0.1306

=== [805/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.51it/s]
Hypertuning:  23%|██▎       | 805/3456 [19:34<59:54,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0773
➡️ Total Profit: ₹-1,997.25
➡️ Equity Curve R²: 0.1362
➡️ Monthly Consistency Score: -0.0082

=== [806/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.73it/s]
Hypertuning:  23%|██▎       | 806/3456 [19:36<1:00:08,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4087
➡️ Total Profit: ₹-23,361.88
➡️ Equity Curve R²: 0.8194
➡️ Monthly Consistency Score: -0.0819

=== [807/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.99it/s]
Hypertuning:  23%|██▎       | 807/3456 [19:37<59:18,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.8700
➡️ Total Profit: ₹17,069.63
➡️ Equity Curve R²: 0.5699
➡️ Monthly Consistency Score: 0.0686

=== [808/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.66it/s]
Hypertuning:  23%|██▎       | 808/3456 [19:39<59:38,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.9545
➡️ Total Profit: ₹39,854.91
➡️ Equity Curve R²: 0.6266
➡️ Monthly Consistency Score: 0.1697

=== [809/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.83it/s]
Hypertuning:  23%|██▎       | 809/3456 [19:40<59:25,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1828
➡️ Total Profit: ₹8,439.27
➡️ Equity Curve R²: 0.2487
➡️ Monthly Consistency Score: 0.0326

=== [810/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.09it/s]
Hypertuning:  23%|██▎       | 810/3456 [19:41<59:53,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.4293
➡️ Total Profit: ₹38,614.17
➡️ Equity Curve R²: 0.4469
➡️ Monthly Consistency Score: 0.1488

=== [811/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.16it/s]
Hypertuning:  23%|██▎       | 811/3456 [19:43<59:07,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.5245
➡️ Total Profit: ₹37,439.90
➡️ Equity Curve R²: 0.1201
➡️ Monthly Consistency Score: 0.1527

=== [812/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.89it/s]
Hypertuning:  23%|██▎       | 812/3456 [19:44<59:48,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.4210
➡️ Total Profit: ₹36,310.37
➡️ Equity Curve R²: 0.0394
➡️ Monthly Consistency Score: 0.1395

=== [813/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.36it/s]
Hypertuning:  24%|██▎       | 813/3456 [19:45<59:28,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.7564
➡️ Total Profit: ₹39,830.94
➡️ Equity Curve R²: 0.6034
➡️ Monthly Consistency Score: 0.1461

=== [814/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.14it/s]
Hypertuning:  24%|██▎       | 814/3456 [19:47<59:58,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.0063
➡️ Total Profit: ₹58,934.02
➡️ Equity Curve R²: 0.0982
➡️ Monthly Consistency Score: 0.2390

=== [815/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.42it/s]
Hypertuning:  24%|██▎       | 815/3456 [19:48<59:07,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 3.5562
➡️ Total Profit: ₹86,303.92
➡️ Equity Curve R²: 0.6566
➡️ Monthly Consistency Score: 0.3513

=== [816/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.26it/s]
Hypertuning:  24%|██▎       | 816/3456 [19:49<59:30,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 4.0587
➡️ Total Profit: ₹69,161.02
➡️ Equity Curve R²: 0.5237
➡️ Monthly Consistency Score: 0.3205

=== [817/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.53it/s]
Hypertuning:  24%|██▎       | 817/3456 [19:51<59:01,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.6138
➡️ Total Profit: ₹-51,097.57
➡️ Equity Curve R²: 0.9217
➡️ Monthly Consistency Score: -0.2125

=== [818/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.59it/s]
Hypertuning:  24%|██▎       | 818/3456 [19:52<59:36,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2118
➡️ Total Profit: ₹-7,479.55
➡️ Equity Curve R²: 0.6897
➡️ Monthly Consistency Score: -0.0327

=== [819/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.11it/s]
Hypertuning:  24%|██▎       | 819/3456 [19:53<1:00:02,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1630
➡️ Total Profit: ₹37,929.86
➡️ Equity Curve R²: 0.0293
➡️ Monthly Consistency Score: 0.1374

=== [820/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.17it/s]
Hypertuning:  24%|██▎       | 820/3456 [19:55<59:27,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.5978
➡️ Total Profit: ₹21,236.33
➡️ Equity Curve R²: 0.0130
➡️ Monthly Consistency Score: 0.0793

=== [821/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.42it/s]
Hypertuning:  24%|██▍       | 821/3456 [19:56<59:07,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1108
➡️ Total Profit: ₹-3,258.69
➡️ Equity Curve R²: 0.4425
➡️ Monthly Consistency Score: -0.0119

=== [822/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.73it/s]
Hypertuning:  24%|██▍       | 822/3456 [19:57<59:31,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0576
➡️ Total Profit: ₹-2,405.43
➡️ Equity Curve R²: 0.6587
➡️ Monthly Consistency Score: -0.0086

=== [823/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.14it/s]
Hypertuning:  24%|██▍       | 823/3456 [19:59<58:28,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 1.7235
➡️ Total Profit: ₹36,583.41
➡️ Equity Curve R²: 0.4533
➡️ Monthly Consistency Score: 0.1406

=== [824/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.36it/s]
Hypertuning:  24%|██▍       | 824/3456 [20:00<58:53,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.7149
➡️ Total Profit: ₹34,969.51
➡️ Equity Curve R²: 0.6761
➡️ Monthly Consistency Score: 0.1491

=== [825/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.50it/s]
Hypertuning:  24%|██▍       | 825/3456 [20:02<59:50,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0458
➡️ Total Profit: ₹2,141.15
➡️ Equity Curve R²: 0.3826
➡️ Monthly Consistency Score: 0.0079

=== [826/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.47it/s]
Hypertuning:  24%|██▍       | 826/3456 [20:03<59:04,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.2092
➡️ Total Profit: ₹35,401.73
➡️ Equity Curve R²: 0.4387
➡️ Monthly Consistency Score: 0.1199

=== [827/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.86it/s]
Hypertuning:  24%|██▍       | 827/3456 [20:04<59:36,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.4263
➡️ Total Profit: ₹30,217.16
➡️ Equity Curve R²: 0.1101
➡️ Monthly Consistency Score: 0.1350

=== [828/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.79it/s]
Hypertuning:  24%|██▍       | 828/3456 [20:06<58:53,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.4755
➡️ Total Profit: ₹16,182.19
➡️ Equity Curve R²: 0.0159
➡️ Monthly Consistency Score: 0.0636

=== [829/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.93it/s]
Hypertuning:  24%|██▍       | 829/3456 [20:07<58:33,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.3484
➡️ Total Profit: ₹32,274.70
➡️ Equity Curve R²: 0.5297
➡️ Monthly Consistency Score: 0.1181

=== [830/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.29it/s]
Hypertuning:  24%|██▍       | 830/3456 [20:08<59:09,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.5291
➡️ Total Profit: ₹65,715.86
➡️ Equity Curve R²: 0.2713
➡️ Monthly Consistency Score: 0.2557

=== [831/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.23it/s]
Hypertuning:  24%|██▍       | 831/3456 [20:10<59:53,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.2203
➡️ Total Profit: ₹78,152.55
➡️ Equity Curve R²: 0.5438
➡️ Monthly Consistency Score: 0.3077

=== [832/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.86it/s]
Hypertuning:  24%|██▍       | 832/3456 [20:11<58:49,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 4.5871
➡️ Total Profit: ₹68,384.78
➡️ Equity Curve R²: 0.7297
➡️ Monthly Consistency Score: 0.3188

=== [833/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.73it/s]
Hypertuning:  24%|██▍       | 833/3456 [20:12<58:28,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.6191
➡️ Total Profit: ₹-52,354.09
➡️ Equity Curve R²: 0.9307
➡️ Monthly Consistency Score: -0.2311

=== [834/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.93it/s]
Hypertuning:  24%|██▍       | 834/3456 [20:14<58:58,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0879
➡️ Total Profit: ₹-2,959.55
➡️ Equity Curve R²: 0.4501
➡️ Monthly Consistency Score: -0.0128

=== [835/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.10it/s]
Hypertuning:  24%|██▍       | 835/3456 [20:15<59:35,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2814
➡️ Total Profit: ₹12,168.55
➡️ Equity Curve R²: 0.2165
➡️ Monthly Consistency Score: 0.0454

=== [836/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.98it/s]
Hypertuning:  24%|██▍       | 836/3456 [20:16<58:39,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.0457
➡️ Total Profit: ₹29,013.55
➡️ Equity Curve R²: 0.0927
➡️ Monthly Consistency Score: 0.1081

=== [837/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.73it/s]
Hypertuning:  24%|██▍       | 837/3456 [20:18<58:22,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.2952
➡️ Total Profit: ₹-8,126.09
➡️ Equity Curve R²: 0.4586
➡️ Monthly Consistency Score: -0.0304

=== [838/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.24it/s]
Hypertuning:  24%|██▍       | 838/3456 [20:19<59:02,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2155
➡️ Total Profit: ₹-8,760.04
➡️ Equity Curve R²: 0.7331
➡️ Monthly Consistency Score: -0.0310

=== [839/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.98it/s]
Hypertuning:  24%|██▍       | 839/3456 [20:20<58:13,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 1.1883
➡️ Total Profit: ₹25,223.74
➡️ Equity Curve R²: 0.3390
➡️ Monthly Consistency Score: 0.1058

=== [840/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.49it/s]
Hypertuning:  24%|██▍       | 840/3456 [20:22<58:51,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.6410
➡️ Total Profit: ₹33,463.09
➡️ Equity Curve R²: 0.5944
➡️ Monthly Consistency Score: 0.1479

=== [841/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.66it/s]
Hypertuning:  24%|██▍       | 841/3456 [20:23<58:32,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.1439
➡️ Total Profit: ₹6,553.50
➡️ Equity Curve R²: 0.2987
➡️ Monthly Consistency Score: 0.0251

=== [842/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.34it/s]
Hypertuning:  24%|██▍       | 842/3456 [20:24<59:01,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.1320
➡️ Total Profit: ₹33,139.89
➡️ Equity Curve R²: 0.3790
➡️ Monthly Consistency Score: 0.1135

=== [843/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.84it/s]
Hypertuning:  24%|██▍       | 843/3456 [20:26<59:26,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.1817
➡️ Total Profit: ₹26,959.90
➡️ Equity Curve R²: 0.0676
➡️ Monthly Consistency Score: 0.1215

=== [844/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.67it/s]
Hypertuning:  24%|██▍       | 844/3456 [20:27<58:46,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4755
➡️ Total Profit: ₹16,182.19
➡️ Equity Curve R²: 0.0159
➡️ Monthly Consistency Score: 0.0636

=== [845/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.04it/s]
Hypertuning:  24%|██▍       | 845/3456 [20:28<58:26,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.5589
➡️ Total Profit: ₹37,313.76
➡️ Equity Curve R²: 0.5420
➡️ Monthly Consistency Score: 0.1374

=== [846/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.60it/s]
Hypertuning:  24%|██▍       | 846/3456 [20:30<58:54,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.4422
➡️ Total Profit: ₹63,455.86
➡️ Equity Curve R²: 0.2823
➡️ Monthly Consistency Score: 0.2495

=== [847/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.21it/s]
Hypertuning:  25%|██▍       | 847/3456 [20:31<59:21,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.1532
➡️ Total Profit: ₹76,523.92
➡️ Equity Curve R²: 0.5479
➡️ Monthly Consistency Score: 0.3047

=== [848/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.95it/s]
Hypertuning:  25%|██▍       | 848/3456 [20:33<58:42,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 4.5871
➡️ Total Profit: ₹68,384.78
➡️ Equity Curve R²: 0.7297
➡️ Monthly Consistency Score: 0.3188

=== [849/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.39it/s]
Hypertuning:  25%|██▍       | 849/3456 [20:34<1:00:01,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.7178
➡️ Total Profit: ₹-60,961.42
➡️ Equity Curve R²: 0.9526
➡️ Monthly Consistency Score: -0.2778

=== [850/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.08it/s]
Hypertuning:  25%|██▍       | 850/3456 [20:35<59:08,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2818
➡️ Total Profit: ₹-12,694.27
➡️ Equity Curve R²: 0.7044
➡️ Monthly Consistency Score: -0.0542

=== [851/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.81it/s]
Hypertuning:  25%|██▍       | 851/3456 [20:37<58:08,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.4456
➡️ Total Profit: ₹15,434.03
➡️ Equity Curve R²: 0.0676
➡️ Monthly Consistency Score: 0.0533

=== [852/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.78it/s]
Hypertuning:  25%|██▍       | 852/3456 [20:38<58:13,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.5052
➡️ Total Profit: ₹14,016.33
➡️ Equity Curve R²: 0.0002
➡️ Monthly Consistency Score: 0.0528

=== [853/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.00it/s]
Hypertuning:  25%|██▍       | 853/3456 [20:39<57:55,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.1291
➡️ Total Profit: ₹-3,715.62
➡️ Equity Curve R²: 0.2734
➡️ Monthly Consistency Score: -0.0141

=== [854/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.07it/s]
Hypertuning:  25%|██▍       | 854/3456 [20:41<58:28,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3766
➡️ Total Profit: ₹-25,623.72
➡️ Equity Curve R²: 0.8502
➡️ Monthly Consistency Score: -0.0884

=== [855/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.76it/s]
Hypertuning:  25%|██▍       | 855/3456 [20:42<58:57,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.7221
➡️ Total Profit: ₹36,552.37
➡️ Equity Curve R²: 0.5906
➡️ Monthly Consistency Score: 0.1383

=== [856/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.33it/s]
Hypertuning:  25%|██▍       | 856/3456 [20:43<58:07,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.7456
➡️ Total Profit: ₹35,594.91
➡️ Equity Curve R²: 0.5500
➡️ Monthly Consistency Score: 0.1504

=== [857/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.38it/s]
Hypertuning:  25%|██▍       | 857/3456 [20:45<57:55,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.5121
➡️ Total Profit: ₹-37,423.69
➡️ Equity Curve R²: 0.9139
➡️ Monthly Consistency Score: -0.1302

=== [858/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.01it/s]
Hypertuning:  25%|██▍       | 858/3456 [20:46<58:39,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.7077
➡️ Total Profit: ₹49,996.05
➡️ Equity Curve R²: 0.4929
➡️ Monthly Consistency Score: 0.1888

=== [859/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.60it/s]
Hypertuning:  25%|██▍       | 859/3456 [20:47<59:00,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1630
➡️ Total Profit: ₹4,137.15
➡️ Equity Curve R²: 0.0017
➡️ Monthly Consistency Score: 0.0176

=== [860/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.38it/s]
Hypertuning:  25%|██▍       | 860/3456 [20:49<58:10,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.5712
➡️ Total Profit: ₹60,230.29
➡️ Equity Curve R²: 0.6308
➡️ Monthly Consistency Score: 0.2480

=== [861/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.95it/s]
Hypertuning:  25%|██▍       | 861/3456 [20:50<57:56,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.8985
➡️ Total Profit: ₹44,246.11
➡️ Equity Curve R²: 0.6141
➡️ Monthly Consistency Score: 0.1705

=== [862/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.92it/s]
Hypertuning:  25%|██▍       | 862/3456 [20:51<58:25,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.6082
➡️ Total Profit: ₹67,977.70
➡️ Equity Curve R²: 0.3090
➡️ Monthly Consistency Score: 0.2637

=== [863/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.15it/s]
Hypertuning:  25%|██▍       | 863/3456 [20:53<58:48,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.2874
➡️ Total Profit: ₹79,781.18
➡️ Equity Curve R²: 0.5601
➡️ Monthly Consistency Score: 0.3184

=== [864/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.01it/s]
Hypertuning:  25%|██▌       | 864/3456 [20:54<58:04,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 4.5871
➡️ Total Profit: ₹68,384.78
➡️ Equity Curve R²: 0.7876
➡️ Monthly Consistency Score: 0.3205

=== [865/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.84it/s]
Hypertuning:  25%|██▌       | 865/3456 [20:56<59:08,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.8496
➡️ Total Profit: ₹-74,295.77
➡️ Equity Curve R²: 0.9630
➡️ Monthly Consistency Score: -0.3300

=== [866/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.24it/s]
Hypertuning:  25%|██▌       | 866/3456 [20:57<58:29,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.5274
➡️ Total Profit: ₹-32,435.12
➡️ Equity Curve R²: 0.8400
➡️ Monthly Consistency Score: -0.1242

=== [867/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.03it/s]
Hypertuning:  25%|██▌       | 867/3456 [20:58<59:05,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.1830
➡️ Total Profit: ₹6,490.86
➡️ Equity Curve R²: 0.1049
➡️ Monthly Consistency Score: 0.0256

=== [868/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.90it/s]
Hypertuning:  25%|██▌       | 868/3456 [21:00<58:03,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6189
➡️ Total Profit: ₹16,153.11
➡️ Equity Curve R²: 0.0014
➡️ Monthly Consistency Score: 0.0630

=== [869/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.14it/s]
Hypertuning:  25%|██▌       | 869/3456 [21:01<57:29,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 0.9015
➡️ Total Profit: ₹21,034.10
➡️ Equity Curve R²: 0.5581
➡️ Monthly Consistency Score: 0.0808

=== [870/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.50it/s]
Hypertuning:  25%|██▌       | 870/3456 [21:02<57:58,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3164
➡️ Total Profit: ₹-12,144.56
➡️ Equity Curve R²: 0.5993
➡️ Monthly Consistency Score: -0.0436

=== [871/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.64it/s]
Hypertuning:  25%|██▌       | 871/3456 [21:04<58:20,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.5485
➡️ Total Profit: ₹15,394.26
➡️ Equity Curve R²: 0.1622
➡️ Monthly Consistency Score: 0.0624

=== [872/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.69it/s]
Hypertuning:  25%|██▌       | 872/3456 [21:05<57:42,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.8480
➡️ Total Profit: ₹34,657.41
➡️ Equity Curve R²: 0.7111
➡️ Monthly Consistency Score: 0.1544

=== [873/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.17it/s]
Hypertuning:  25%|██▌       | 873/3456 [21:06<57:18,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: -0.2061
➡️ Total Profit: ₹-9,844.96
➡️ Equity Curve R²: 0.5530
➡️ Monthly Consistency Score: -0.0371

=== [874/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.05it/s]
Hypertuning:  25%|██▌       | 874/3456 [21:08<57:41,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.6398
➡️ Total Profit: ₹47,722.85
➡️ Equity Curve R²: 0.5791
➡️ Monthly Consistency Score: 0.2058

=== [875/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.89it/s]
Hypertuning:  25%|██▌       | 875/3456 [21:09<58:11,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.4587
➡️ Total Profit: ₹-19,389.47
➡️ Equity Curve R²: 0.4884
➡️ Monthly Consistency Score: -0.0756

=== [876/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.19it/s]
Hypertuning:  25%|██▌       | 876/3456 [21:10<57:41,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.6927
➡️ Total Profit: ₹-27,862.64
➡️ Equity Curve R²: 0.5842
➡️ Monthly Consistency Score: -0.1049

=== [877/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.09it/s]
Hypertuning:  25%|██▌       | 877/3456 [21:12<57:40,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.2251
➡️ Total Profit: ₹25,741.67
➡️ Equity Curve R²: 0.1220
➡️ Monthly Consistency Score: 0.1045

=== [878/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.74it/s]
Hypertuning:  25%|██▌       | 878/3456 [21:13<58:06,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6842
➡️ Total Profit: ₹30,155.41
➡️ Equity Curve R²: 0.0041
➡️ Monthly Consistency Score: 0.1146

=== [879/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.74it/s]
Hypertuning:  25%|██▌       | 879/3456 [21:14<57:16,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 0.5113
➡️ Total Profit: ₹22,371.32
➡️ Equity Curve R²: 0.3908
➡️ Monthly Consistency Score: 0.0998

=== [880/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.30it/s]
Hypertuning:  25%|██▌       | 880/3456 [21:16<57:34,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.1382
➡️ Total Profit: ₹41,465.55
➡️ Equity Curve R²: 0.0535
➡️ Monthly Consistency Score: 0.1828

=== [881/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.98it/s]
Hypertuning:  25%|██▌       | 881/3456 [21:17<57:19,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.8171
➡️ Total Profit: ₹-62,320.87
➡️ Equity Curve R²: 0.9383
➡️ Monthly Consistency Score: -0.2875

=== [882/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.14it/s]
Hypertuning:  26%|██▌       | 882/3456 [21:18<57:43,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.5131
➡️ Total Profit: ₹-31,829.64
➡️ Equity Curve R²: 0.8422
➡️ Monthly Consistency Score: -0.1185

=== [883/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.32it/s]
Hypertuning:  26%|██▌       | 883/3456 [21:20<58:18,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0091
➡️ Total Profit: ₹363.54
➡️ Equity Curve R²: 0.3404
➡️ Monthly Consistency Score: 0.0014

=== [884/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.45it/s]
Hypertuning:  26%|██▌       | 884/3456 [21:21<57:19,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.5370
➡️ Total Profit: ₹14,762.15
➡️ Equity Curve R²: 0.0012
➡️ Monthly Consistency Score: 0.0570

=== [885/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.95it/s]
Hypertuning:  26%|██▌       | 885/3456 [21:22<57:07,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 1.1208
➡️ Total Profit: ₹25,444.58
➡️ Equity Curve R²: 0.6051
➡️ Monthly Consistency Score: 0.0978

=== [886/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.56it/s]
Hypertuning:  26%|██▌       | 886/3456 [21:24<57:43,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2320
➡️ Total Profit: ₹-10,659.16
➡️ Equity Curve R²: 0.4353
➡️ Monthly Consistency Score: -0.0394

=== [887/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.64it/s]
Hypertuning:  26%|██▌       | 887/3456 [21:25<58:11,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.6067
➡️ Total Profit: ₹17,025.63
➡️ Equity Curve R²: 0.1409
➡️ Monthly Consistency Score: 0.0685

=== [888/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.18it/s]
Hypertuning:  26%|██▌       | 888/3456 [21:26<57:25,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.8480
➡️ Total Profit: ₹34,657.41
➡️ Equity Curve R²: 0.7111
➡️ Monthly Consistency Score: 0.1544

=== [889/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.62it/s]
Hypertuning:  26%|██▌       | 889/3456 [21:28<57:00,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: -0.1505
➡️ Total Profit: ₹-5,486.80
➡️ Equity Curve R²: 0.4823
➡️ Monthly Consistency Score: -0.0199

=== [890/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.48it/s]
Hypertuning:  26%|██▌       | 890/3456 [21:29<57:21,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.8400
➡️ Total Profit: ₹23,733.73
➡️ Equity Curve R²: 0.0086
➡️ Monthly Consistency Score: 0.0905

=== [891/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.33it/s]
Hypertuning:  26%|██▌       | 891/3456 [21:30<57:50,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.4803
➡️ Total Profit: ₹-22,649.47
➡️ Equity Curve R²: 0.5623
➡️ Monthly Consistency Score: -0.0902

=== [892/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.72it/s]
Hypertuning:  26%|██▌       | 892/3456 [21:32<57:01,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: -0.6397
➡️ Total Profit: ₹-25,730.82
➡️ Equity Curve R²: 0.5134
➡️ Monthly Consistency Score: -0.1001

=== [893/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 129.38it/s]
Hypertuning:  26%|██▌       | 893/3456 [21:33<56:49,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 1.8612
➡️ Total Profit: ₹35,193.08
➡️ Equity Curve R²: 0.2951
➡️ Monthly Consistency Score: 0.1482

=== [894/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.03it/s]
Hypertuning:  26%|██▌       | 894/3456 [21:34<57:36,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.5401
➡️ Total Profit: ₹25,637.25
➡️ Equity Curve R²: 0.0146
➡️ Monthly Consistency Score: 0.0940

=== [895/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.62it/s]
Hypertuning:  26%|██▌       | 895/3456 [21:36<56:54,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 1.0733
➡️ Total Profit: ₹43,742.69
➡️ Equity Curve R²: 0.0345
➡️ Monthly Consistency Score: 0.1792

=== [896/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.88it/s]
Hypertuning:  26%|██▌       | 896/3456 [21:37<57:29,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.1382
➡️ Total Profit: ₹41,465.55
➡️ Equity Curve R²: 0.0535
➡️ Monthly Consistency Score: 0.1828

=== [897/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.06it/s]
Hypertuning:  26%|██▌       | 897/3456 [21:39<58:46,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.8529
➡️ Total Profit: ₹-76,248.81
➡️ Equity Curve R²: 0.9705
➡️ Monthly Consistency Score: -0.3503

=== [898/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.56it/s]
Hypertuning:  26%|██▌       | 898/3456 [21:40<58:08,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0324
➡️ Total Profit: ₹-1,225.95
➡️ Equity Curve R²: 0.6921
➡️ Monthly Consistency Score: -0.0048

=== [899/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.41it/s]
Hypertuning:  26%|██▌       | 899/3456 [21:41<58:31,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2158
➡️ Total Profit: ₹-10,652.42
➡️ Equity Curve R²: 0.6655
➡️ Monthly Consistency Score: -0.0414

=== [900/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.91it/s]
Hypertuning:  26%|██▌       | 900/3456 [21:43<57:41,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6307
➡️ Total Profit: ₹12,628.41
➡️ Equity Curve R²: 0.2552
➡️ Monthly Consistency Score: 0.0486

=== [901/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.56it/s]
Hypertuning:  26%|██▌       | 901/3456 [21:44<57:17,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.5435
➡️ Total Profit: ₹-19,205.20
➡️ Equity Curve R²: 0.7985
➡️ Monthly Consistency Score: -0.0727

=== [902/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.35it/s]
Hypertuning:  26%|██▌       | 902/3456 [21:45<57:46,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1600
➡️ Total Profit: ₹-5,360.87
➡️ Equity Curve R²: 0.4572
➡️ Monthly Consistency Score: -0.0207

=== [903/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.48it/s]
Hypertuning:  26%|██▌       | 903/3456 [21:47<56:55,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.4636
➡️ Total Profit: ₹13,765.63
➡️ Equity Curve R²: 0.2132
➡️ Monthly Consistency Score: 0.0556

=== [904/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.30it/s]
Hypertuning:  26%|██▌       | 904/3456 [21:48<57:35,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.8480
➡️ Total Profit: ₹34,657.41
➡️ Equity Curve R²: 0.7111
➡️ Monthly Consistency Score: 0.1544

=== [905/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.55it/s]
Hypertuning:  26%|██▌       | 905/3456 [21:49<58:27,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.0166
➡️ Total Profit: ₹692.26
➡️ Equity Curve R²: 0.2915
➡️ Monthly Consistency Score: 0.0025

=== [906/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.38it/s]
Hypertuning:  26%|██▌       | 906/3456 [21:51<57:49,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.6495
➡️ Total Profit: ₹46,599.29
➡️ Equity Curve R²: 0.3333
➡️ Monthly Consistency Score: 0.1842

=== [907/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.23it/s]
Hypertuning:  26%|██▌       | 907/3456 [21:52<58:15,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.2682
➡️ Total Profit: ₹5,061.90
➡️ Equity Curve R²: 0.0770
➡️ Monthly Consistency Score: 0.0196

=== [908/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.19it/s]
Hypertuning:  26%|██▋       | 908/3456 [21:53<57:27,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2691
➡️ Total Profit: ₹-10,822.64
➡️ Equity Curve R²: 0.1350
➡️ Monthly Consistency Score: -0.0451

=== [909/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.65it/s]
Hypertuning:  26%|██▋       | 909/3456 [21:55<57:25,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0172
➡️ Total Profit: ₹-499.35
➡️ Equity Curve R²: 0.4181
➡️ Monthly Consistency Score: -0.0020

=== [910/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.47it/s]
Hypertuning:  26%|██▋       | 910/3456 [21:56<57:50,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5977
➡️ Total Profit: ₹30,445.51
➡️ Equity Curve R²: 0.1605
➡️ Monthly Consistency Score: 0.1155

=== [911/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.17it/s]
Hypertuning:  26%|██▋       | 911/3456 [21:58<58:16,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.8458
➡️ Total Profit: ₹37,225.43
➡️ Equity Curve R²: 0.0034
➡️ Monthly Consistency Score: 0.1513

=== [912/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.78it/s]
Hypertuning:  26%|██▋       | 912/3456 [21:59<57:38,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.1382
➡️ Total Profit: ₹41,465.55
➡️ Equity Curve R²: 0.0535
➡️ Monthly Consistency Score: 0.1828

=== [913/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.10it/s]
Hypertuning:  26%|██▋       | 913/3456 [22:00<57:17,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.8518
➡️ Total Profit: ₹-75,554.83
➡️ Equity Curve R²: 0.9626
➡️ Monthly Consistency Score: -0.3344

=== [914/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.43it/s]
Hypertuning:  26%|██▋       | 914/3456 [22:02<57:33,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.5274
➡️ Total Profit: ₹-32,435.12
➡️ Equity Curve R²: 0.8400
➡️ Monthly Consistency Score: -0.1242

=== [915/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.25it/s]
Hypertuning:  26%|██▋       | 915/3456 [22:03<57:46,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0911
➡️ Total Profit: ₹3,230.86
➡️ Equity Curve R²: 0.2097
➡️ Monthly Consistency Score: 0.0126

=== [916/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.36it/s]
Hypertuning:  27%|██▋       | 916/3456 [22:04<57:01,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.5370
➡️ Total Profit: ₹14,762.15
➡️ Equity Curve R²: 0.0012
➡️ Monthly Consistency Score: 0.0570

=== [917/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.43it/s]
Hypertuning:  27%|██▋       | 917/3456 [22:06<58:04,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.9015
➡️ Total Profit: ₹21,034.10
➡️ Equity Curve R²: 0.5581
➡️ Monthly Consistency Score: 0.0806

=== [918/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.17it/s]
Hypertuning:  27%|██▋       | 918/3456 [22:07<57:11,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1216
➡️ Total Profit: ₹-4,666.39
➡️ Equity Curve R²: 0.5972
➡️ Monthly Consistency Score: -0.0167

=== [919/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.20it/s]
Hypertuning:  27%|██▋       | 919/3456 [22:08<57:29,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5485
➡️ Total Profit: ₹15,394.26
➡️ Equity Curve R²: 0.1622
➡️ Monthly Consistency Score: 0.0624

=== [920/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.78it/s]
Hypertuning:  27%|██▋       | 920/3456 [22:10<57:00,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.8480
➡️ Total Profit: ₹34,657.41
➡️ Equity Curve R²: 0.7111
➡️ Monthly Consistency Score: 0.1544

=== [921/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.62it/s]
Hypertuning:  27%|██▋       | 921/3456 [22:11<57:56,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2061
➡️ Total Profit: ₹-9,844.96
➡️ Equity Curve R²: 0.5530
➡️ Monthly Consistency Score: -0.0369

=== [922/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.19it/s]
Hypertuning:  27%|██▋       | 922/3456 [22:13<57:17,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.4258
➡️ Total Profit: ₹46,593.77
➡️ Equity Curve R²: 0.5456
➡️ Monthly Consistency Score: 0.1989

=== [923/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.03it/s]
Hypertuning:  27%|██▋       | 923/3456 [22:14<57:38,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4587
➡️ Total Profit: ₹-19,389.47
➡️ Equity Curve R²: 0.4884
➡️ Monthly Consistency Score: -0.0756

=== [924/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.89it/s]
Hypertuning:  27%|██▋       | 924/3456 [22:15<57:10,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6927
➡️ Total Profit: ₹-27,862.64
➡️ Equity Curve R²: 0.5842
➡️ Monthly Consistency Score: -0.1049

=== [925/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.37it/s]
Hypertuning:  27%|██▋       | 925/3456 [22:17<58:21,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.2251
➡️ Total Profit: ₹25,741.67
➡️ Equity Curve R²: 0.1220
➡️ Monthly Consistency Score: 0.1042

=== [926/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.53it/s]
Hypertuning:  27%|██▋       | 926/3456 [22:18<57:35,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.6842
➡️ Total Profit: ₹30,155.41
➡️ Equity Curve R²: 0.0041
➡️ Monthly Consistency Score: 0.1146

=== [927/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.91it/s]
Hypertuning:  27%|██▋       | 927/3456 [22:19<56:37,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.5113
➡️ Total Profit: ₹22,371.32
➡️ Equity Curve R²: 0.3908
➡️ Monthly Consistency Score: 0.0998

=== [928/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.76it/s]
Hypertuning:  27%|██▋       | 928/3456 [22:21<57:05,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.5673
➡️ Total Profit: ₹23,084.53
➡️ Equity Curve R²: 0.2147
➡️ Monthly Consistency Score: 0.0946

=== [929/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.41it/s]
Hypertuning:  27%|██▋       | 929/3456 [22:22<57:50,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.8274
➡️ Total Profit: ₹-74,637.73
➡️ Equity Curve R²: 0.9401
➡️ Monthly Consistency Score: -0.3314

=== [930/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)
<ipython-input-10-980624002>:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_data['Signal'] = temp_data['Signal'].astype(int)

100%|██████████| 1/1 [00:00<00:00, 123.48it/s]
Hypertuning:  27%|██▋       | 930/3456 [22:23<57:13,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2022
➡️ Total Profit: ₹-9,746.03
➡️ Equity Curve R²: 0.7225
➡️ Monthly Consistency Score: -0.0355

=== [931/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.90it/s]
Hypertuning:  27%|██▋       | 931/3456 [22:25<57:25,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.3024
➡️ Total Profit: ₹8,061.70
➡️ Equity Curve R²: 0.1327
➡️ Monthly Consistency Score: 0.0329

=== [932/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.54it/s]
Hypertuning:  27%|██▋       | 932/3456 [22:26<56:29,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.7686
➡️ Total Profit: ₹29,023.87
➡️ Equity Curve R²: 0.6968
➡️ Monthly Consistency Score: 0.1091

=== [933/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.47it/s]
Hypertuning:  27%|██▋       | 933/3456 [22:28<57:16,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.5360
➡️ Total Profit: ₹-17,183.20
➡️ Equity Curve R²: 0.7207
➡️ Monthly Consistency Score: -0.0660

=== [934/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.04it/s]
Hypertuning:  27%|██▋       | 934/3456 [22:29<56:28,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.0458
➡️ Total Profit: ₹-2,051.91
➡️ Equity Curve R²: 0.4092
➡️ Monthly Consistency Score: -0.0075

=== [935/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.78it/s]
Hypertuning:  27%|██▋       | 935/3456 [22:30<56:45,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.5486
➡️ Total Profit: ₹15,397.00
➡️ Equity Curve R²: 0.1621
➡️ Monthly Consistency Score: 0.0624

=== [936/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.13it/s]
Hypertuning:  27%|██▋       | 936/3456 [22:32<57:22,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.8480
➡️ Total Profit: ₹34,657.41
➡️ Equity Curve R²: 0.7111
➡️ Monthly Consistency Score: 0.1544

=== [937/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.88it/s]
Hypertuning:  27%|██▋       | 937/3456 [22:33<57:07,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1906
➡️ Total Profit: ₹-7,443.08
➡️ Equity Curve R²: 0.6563
➡️ Monthly Consistency Score: -0.0272

=== [938/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 109.96it/s]
Hypertuning:  27%|██▋       | 938/3456 [22:34<56:29,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.8118
➡️ Total Profit: ₹40,942.85
➡️ Equity Curve R²: 0.4671
➡️ Monthly Consistency Score: 0.1680

=== [939/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.28it/s]
Hypertuning:  27%|██▋       | 939/3456 [22:36<56:52,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4974
➡️ Total Profit: ₹-22,303.01
➡️ Equity Curve R²: 0.5530
➡️ Monthly Consistency Score: -0.0848

=== [940/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.77it/s]
Hypertuning:  27%|██▋       | 940/3456 [22:37<56:13,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.6927
➡️ Total Profit: ₹-27,862.64
➡️ Equity Curve R²: 0.5842
➡️ Monthly Consistency Score: -0.1049

=== [941/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.54it/s]
Hypertuning:  27%|██▋       | 941/3456 [22:38<57:25,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.7500
➡️ Total Profit: ₹34,564.49
➡️ Equity Curve R²: 0.2308
➡️ Monthly Consistency Score: 0.1471

=== [942/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.46it/s]
Hypertuning:  27%|██▋       | 942/3456 [22:40<56:36,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.5401
➡️ Total Profit: ₹25,637.25
➡️ Equity Curve R²: 0.0146
➡️ Monthly Consistency Score: 0.0940

=== [943/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.34it/s]
Hypertuning:  27%|██▋       | 943/3456 [22:41<56:52,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4571
➡️ Total Profit: ₹20,745.43
➡️ Equity Curve R²: 0.4101
➡️ Monthly Consistency Score: 0.0924

=== [944/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.15it/s]
Hypertuning:  27%|██▋       | 944/3456 [22:42<56:11,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.1382
➡️ Total Profit: ₹41,465.55
➡️ Equity Curve R²: 0.0535
➡️ Monthly Consistency Score: 0.1828

=== [945/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.52it/s]
Hypertuning:  27%|██▋       | 945/3456 [22:44<57:05,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.8263
➡️ Total Profit: ₹-80,026.93
➡️ Equity Curve R²: 0.9422
➡️ Monthly Consistency Score: -0.3461

=== [946/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 129.05it/s]
Hypertuning:  27%|██▋       | 946/3456 [22:45<57:38,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.3430
➡️ Total Profit: ₹-19,831.39
➡️ Equity Curve R²: 0.8346
➡️ Monthly Consistency Score: -0.0711

=== [947/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.41it/s]
Hypertuning:  27%|██▋       | 947/3456 [22:46<56:42,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0675
➡️ Total Profit: ₹-2,569.67
➡️ Equity Curve R²: 0.4008
➡️ Monthly Consistency Score: -0.0103

=== [948/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.55it/s]
Hypertuning:  27%|██▋       | 948/3456 [22:48<57:03,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1455
➡️ Total Profit: ₹-4,584.32
➡️ Equity Curve R²: 0.1663
➡️ Monthly Consistency Score: -0.0181

=== [949/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.49it/s]
Hypertuning:  27%|██▋       | 949/3456 [22:49<56:52,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.8239
➡️ Total Profit: ₹-31,807.09
➡️ Equity Curve R²: 0.8231
➡️ Monthly Consistency Score: -0.1221

=== [950/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.16it/s]
Hypertuning:  27%|██▋       | 950/3456 [22:51<57:41,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.2604
➡️ Total Profit: ₹7,419.25
➡️ Equity Curve R²: 0.3092
➡️ Monthly Consistency Score: 0.0272

=== [951/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.65it/s]
Hypertuning:  28%|██▊       | 951/3456 [22:52<56:41,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2395
➡️ Total Profit: ₹-10,659.90
➡️ Equity Curve R²: 0.7174
➡️ Monthly Consistency Score: -0.0473

=== [952/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.70it/s]
Hypertuning:  28%|██▊       | 952/3456 [22:53<57:03,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.0808
➡️ Total Profit: ₹31,624.69
➡️ Equity Curve R²: 0.4129
➡️ Monthly Consistency Score: 0.1327

=== [953/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.23it/s]
Hypertuning:  28%|██▊       | 953/3456 [22:55<56:50,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.6537
➡️ Total Profit: ₹-37,563.09
➡️ Equity Curve R²: 0.8721
➡️ Monthly Consistency Score: -0.1319

=== [954/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.06it/s]
Hypertuning:  28%|██▊       | 954/3456 [22:56<57:22,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.5013
➡️ Total Profit: ₹41,980.85
➡️ Equity Curve R²: 0.7993
➡️ Monthly Consistency Score: 0.1804

=== [955/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.70it/s]
Hypertuning:  28%|██▊       | 955/3456 [22:57<56:30,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.5960
➡️ Total Profit: ₹-32,429.47
➡️ Equity Curve R²: 0.7881
➡️ Monthly Consistency Score: -0.1260

=== [956/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.88it/s]
Hypertuning:  28%|██▊       | 956/3456 [22:59<57:01,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2555
➡️ Total Profit: ₹-10,822.64
➡️ Equity Curve R²: 0.1618
➡️ Monthly Consistency Score: -0.0448

=== [957/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.52it/s]
Hypertuning:  28%|██▊       | 957/3456 [23:00<56:47,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1578
➡️ Total Profit: ₹-4,280.29
➡️ Equity Curve R²: 0.0352
➡️ Monthly Consistency Score: -0.0168

=== [958/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.88it/s]
Hypertuning:  28%|██▊       | 958/3456 [23:02<57:28,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.3921
➡️ Total Profit: ₹17,726.33
➡️ Equity Curve R²: 0.2207
➡️ Monthly Consistency Score: 0.0662

=== [959/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.38it/s]
Hypertuning:  28%|██▊       | 959/3456 [23:03<56:45,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.8334
➡️ Total Profit: ₹33,962.69
➡️ Equity Curve R²: 0.0180
➡️ Monthly Consistency Score: 0.1415

=== [960/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.30it/s]
Hypertuning:  28%|██▊       | 960/3456 [23:04<55:55,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.5150
➡️ Total Profit: ₹20,956.35
➡️ Equity Curve R²: 0.2134
➡️ Monthly Consistency Score: 0.0870

=== [961/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.62it/s]
Hypertuning:  28%|██▊       | 961/3456 [23:06<56:47,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.6929
➡️ Total Profit: ₹-47,902.57
➡️ Equity Curve R²: 0.9151
➡️ Monthly Consistency Score: -0.2185

=== [962/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.04it/s]
Hypertuning:  28%|██▊       | 962/3456 [23:07<57:18,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.3861
➡️ Total Profit: ₹-14,271.23
➡️ Equity Curve R²: 0.7963
➡️ Monthly Consistency Score: -0.0584

=== [963/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.11it/s]
Hypertuning:  28%|██▊       | 963/3456 [23:08<56:22,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.3707
➡️ Total Profit: ₹14,175.80
➡️ Equity Curve R²: 0.3177
➡️ Monthly Consistency Score: 0.0580

=== [964/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.53it/s]
Hypertuning:  28%|██▊       | 964/3456 [23:10<55:22,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 0.5401
➡️ Total Profit: ₹16,797.85
➡️ Equity Curve R²: 0.0198
➡️ Monthly Consistency Score: 0.0619

=== [965/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.34it/s]
Hypertuning:  28%|██▊       | 965/3456 [23:11<56:16,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0477
➡️ Total Profit: ₹-1,765.71
➡️ Equity Curve R²: 0.0031
➡️ Monthly Consistency Score: -0.0065

=== [966/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.63it/s]
Hypertuning:  28%|██▊       | 966/3456 [23:12<56:57,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.2800
➡️ Total Profit: ₹7,857.53
➡️ Equity Curve R²: 0.0401
➡️ Monthly Consistency Score: 0.0283

=== [967/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.39it/s]
Hypertuning:  28%|██▊       | 967/3456 [23:14<56:07,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.2397
➡️ Total Profit: ₹20,313.48
➡️ Equity Curve R²: 0.3588
➡️ Monthly Consistency Score: 0.0877

=== [968/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.24it/s]
Hypertuning:  28%|██▊       | 968/3456 [23:15<55:32,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.4211
➡️ Total Profit: ₹28,572.09
➡️ Equity Curve R²: 0.2837
➡️ Monthly Consistency Score: 0.1164

=== [969/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 129.03it/s]
Hypertuning:  28%|██▊       | 969/3456 [23:16<56:17,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4902
➡️ Total Profit: ₹-33,665.31
➡️ Equity Curve R²: 0.8847
➡️ Monthly Consistency Score: -0.1236

=== [970/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.02it/s]
Hypertuning:  28%|██▊       | 970/3456 [23:18<57:00,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 3.1598
➡️ Total Profit: ₹60,161.14
➡️ Equity Curve R²: 0.7797
➡️ Monthly Consistency Score: 0.2690

=== [971/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.87it/s]
Hypertuning:  28%|██▊       | 971/3456 [23:19<56:03,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1697
➡️ Total Profit: ₹-6,341.25
➡️ Equity Curve R²: 0.2966
➡️ Monthly Consistency Score: -0.0240

=== [972/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.40it/s]
Hypertuning:  28%|██▊       | 972/3456 [23:21<56:27,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.2677
➡️ Total Profit: ₹34,172.91
➡️ Equity Curve R²: 0.1054
➡️ Monthly Consistency Score: 0.1286

=== [973/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.07it/s]
Hypertuning:  28%|██▊       | 973/3456 [23:22<56:12,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.7123
➡️ Total Profit: ₹18,399.66
➡️ Equity Curve R²: 0.1344
➡️ Monthly Consistency Score: 0.0654

=== [974/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.09it/s]
Hypertuning:  28%|██▊       | 974/3456 [23:23<55:26,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.7620
➡️ Total Profit: ₹51,921.95
➡️ Equity Curve R²: 0.1480
➡️ Monthly Consistency Score: 0.2226

=== [975/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.27it/s]
Hypertuning:  28%|██▊       | 975/3456 [23:25<55:47,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4414
➡️ Total Profit: ₹20,750.91
➡️ Equity Curve R²: 0.3826
➡️ Monthly Consistency Score: 0.0807

=== [976/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.00it/s]
Hypertuning:  28%|██▊       | 976/3456 [23:26<55:27,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.0561
➡️ Total Profit: ₹56,945.55
➡️ Equity Curve R²: 0.2583
➡️ Monthly Consistency Score: 0.2400

=== [977/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.73it/s]
Hypertuning:  28%|██▊       | 977/3456 [23:27<56:28,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.7233
➡️ Total Profit: ₹-57,134.06
➡️ Equity Curve R²: 0.9281
➡️ Monthly Consistency Score: -0.2588

=== [978/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.15it/s]
Hypertuning:  28%|██▊       | 978/3456 [23:29<55:43,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1200
➡️ Total Profit: ₹-3,485.79
➡️ Equity Curve R²: 0.6382
➡️ Monthly Consistency Score: -0.0141

=== [979/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.13it/s]
Hypertuning:  28%|██▊       | 979/3456 [23:30<55:56,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2827
➡️ Total Profit: ₹10,921.16
➡️ Equity Curve R²: 0.4361
➡️ Monthly Consistency Score: 0.0443

=== [980/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.28it/s]
Hypertuning:  28%|██▊       | 980/3456 [23:31<56:14,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.3187
➡️ Total Profit: ₹11,061.49
➡️ Equity Curve R²: 0.1391
➡️ Monthly Consistency Score: 0.0412

=== [981/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.44it/s]
Hypertuning:  28%|██▊       | 981/3456 [23:33<55:55,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0395
➡️ Total Profit: ₹1,384.76
➡️ Equity Curve R²: 0.0030
➡️ Monthly Consistency Score: 0.0051

=== [982/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.75it/s]
Hypertuning:  28%|██▊       | 982/3456 [23:34<56:35,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.2398
➡️ Total Profit: ₹6,728.45
➡️ Equity Curve R²: 0.0205
➡️ Monthly Consistency Score: 0.0241

=== [983/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.29it/s]
Hypertuning:  28%|██▊       | 983/3456 [23:35<55:37,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.3392
➡️ Total Profit: ₹21,944.85
➡️ Equity Curve R²: 0.3470
➡️ Monthly Consistency Score: 0.0942

=== [984/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.38it/s]
Hypertuning:  28%|██▊       | 984/3456 [23:37<56:07,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.3153
➡️ Total Profit: ₹26,443.91
➡️ Equity Curve R²: 0.3001
➡️ Monthly Consistency Score: 0.1081

=== [985/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.45it/s]
Hypertuning:  29%|██▊       | 985/3456 [23:38<56:11,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2852
➡️ Total Profit: ₹-13,619.66
➡️ Equity Curve R²: 0.7633
➡️ Monthly Consistency Score: -0.0499

=== [986/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.33it/s]
Hypertuning:  29%|██▊       | 986/3456 [23:40<55:35,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.1005
➡️ Total Profit: ₹59,032.06
➡️ Equity Curve R²: 0.7935
➡️ Monthly Consistency Score: 0.2587

=== [987/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.98it/s]
Hypertuning:  29%|██▊       | 987/3456 [23:41<55:54,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1697
➡️ Total Profit: ₹-6,341.25
➡️ Equity Curve R²: 0.2966
➡️ Monthly Consistency Score: -0.0240

=== [988/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.23it/s]
Hypertuning:  29%|██▊       | 988/3456 [23:42<55:06,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.5930
➡️ Total Profit: ₹38,436.55
➡️ Equity Curve R²: 0.2916
➡️ Monthly Consistency Score: 0.1596

=== [989/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.66it/s]
Hypertuning:  29%|██▊       | 989/3456 [23:44<55:50,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.8588
➡️ Total Profit: ₹22,181.54
➡️ Equity Curve R²: 0.1550
➡️ Monthly Consistency Score: 0.0800

=== [990/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.04it/s]
Hypertuning:  29%|██▊       | 990/3456 [23:45<56:28,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.2803
➡️ Total Profit: ₹44,853.69
➡️ Equity Curve R²: 0.2729
➡️ Monthly Consistency Score: 0.1664

=== [991/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.80it/s]
Hypertuning:  29%|██▊       | 991/3456 [23:46<55:37,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4414
➡️ Total Profit: ₹20,750.91
➡️ Equity Curve R²: 0.3826
➡️ Monthly Consistency Score: 0.0807

=== [992/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.69it/s]
Hypertuning:  29%|██▊       | 992/3456 [23:48<56:10,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 6.4954
➡️ Total Profit: ₹69,164.66
➡️ Equity Curve R²: 0.7353
➡️ Monthly Consistency Score: 0.3522

=== [993/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.31it/s]
Hypertuning:  29%|██▊       | 993/3456 [23:49<56:00,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.7710
➡️ Total Profit: ₹-60,918.77
➡️ Equity Curve R²: 0.9507
➡️ Monthly Consistency Score: -0.2835

=== [994/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.78it/s]
Hypertuning:  29%|██▉       | 994/3456 [23:50<55:18,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3416
➡️ Total Profit: ₹11,201.45
➡️ Equity Curve R²: 0.3943
➡️ Monthly Consistency Score: 0.0484

=== [995/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.96it/s]
Hypertuning:  29%|██▉       | 995/3456 [23:52<55:31,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1566
➡️ Total Profit: ₹-6,623.01
➡️ Equity Curve R²: 0.7524
➡️ Monthly Consistency Score: -0.0272

=== [996/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.49it/s]
Hypertuning:  29%|██▉       | 996/3456 [23:53<54:40,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 0.2709
➡️ Total Profit: ₹9,665.17
➡️ Equity Curve R²: 0.0006
➡️ Monthly Consistency Score: 0.0347

=== [997/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.04it/s]
Hypertuning:  29%|██▉       | 997/3456 [23:54<55:39,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1107
➡️ Total Profit: ₹3,606.77
➡️ Equity Curve R²: 0.0077
➡️ Monthly Consistency Score: 0.0140

=== [998/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.50it/s]
Hypertuning:  29%|██▉       | 998/3456 [23:56<56:07,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.9439
➡️ Total Profit: ₹18,028.45
➡️ Equity Curve R²: 0.4429
➡️ Monthly Consistency Score: 0.0666

=== [999/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.54it/s]
Hypertuning:  29%|██▉       | 999/3456 [23:57<55:19,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.7449
➡️ Total Profit: ₹28,441.74
➡️ Equity Curve R²: 0.6950
➡️ Monthly Consistency Score: 0.1161

=== [1000/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.02it/s]
Hypertuning:  29%|██▉       | 1000/3456 [23:59<55:49,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.3056
➡️ Total Profit: ₹25,838.39
➡️ Equity Curve R²: 0.3994
➡️ Monthly Consistency Score: 0.1021

=== [1001/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.18it/s]
Hypertuning:  29%|██▉       | 1001/3456 [24:00<55:33,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4347
➡️ Total Profit: ₹-29,306.21
➡️ Equity Curve R²: 0.8473
➡️ Monthly Consistency Score: -0.1079

=== [1002/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.19it/s]
Hypertuning:  29%|██▉       | 1002/3456 [24:01<54:52,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 3.3904
➡️ Total Profit: ₹61,292.06
➡️ Equity Curve R²: 0.7773
➡️ Monthly Consistency Score: 0.2560

=== [1003/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.93it/s]
Hypertuning:  29%|██▉       | 1003/3456 [24:03<55:06,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6432
➡️ Total Profit: ₹-36,032.05
➡️ Equity Curve R²: 0.8702
➡️ Monthly Consistency Score: -0.1242

=== [1004/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 101.52it/s]
Hypertuning:  29%|██▉       | 1004/3456 [24:04<55:42,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2564
➡️ Total Profit: ₹-16,248.82
➡️ Equity Curve R²: 0.6427
➡️ Monthly Consistency Score: -0.0578

=== [1005/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.17it/s]
Hypertuning:  29%|██▉       | 1005/3456 [24:05<55:47,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1847
➡️ Total Profit: ₹29,108.25
➡️ Equity Curve R²: 0.3581
➡️ Monthly Consistency Score: 0.1077

=== [1006/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.27it/s]
Hypertuning:  29%|██▉       | 1006/3456 [24:07<56:23,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.0519
➡️ Total Profit: ₹42,881.95
➡️ Equity Curve R²: 0.0034
➡️ Monthly Consistency Score: 0.1672

=== [1007/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 131.40it/s]
Hypertuning:  29%|██▉       | 1007/3456 [24:08<55:29,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1136
➡️ Total Profit: ₹6,082.27
➡️ Equity Curve R²: 0.5990
➡️ Monthly Consistency Score: 0.0241

=== [1008/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.20it/s]
Hypertuning:  29%|██▉       | 1008/3456 [24:09<54:30,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.8038
➡️ Total Profit: ₹37,209.19
➡️ Equity Curve R²: 0.0154
➡️ Monthly Consistency Score: 0.1446

=== [1009/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.04it/s]
Hypertuning:  29%|██▉       | 1009/3456 [24:11<55:13,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6984
➡️ Total Profit: ₹-49,161.63
➡️ Equity Curve R²: 0.9196
➡️ Monthly Consistency Score: -0.2233

=== [1010/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.88it/s]
Hypertuning:  29%|██▉       | 1010/3456 [24:12<55:54,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2959
➡️ Total Profit: ₹-10,269.47
➡️ Equity Curve R²: 0.7424
➡️ Monthly Consistency Score: -0.0417

=== [1011/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.61it/s]
Hypertuning:  29%|██▉       | 1011/3456 [24:13<54:57,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2929
➡️ Total Profit: ₹12,157.11
➡️ Equity Curve R²: 0.3953
➡️ Monthly Consistency Score: 0.0490

=== [1012/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.95it/s]
Hypertuning:  29%|██▉       | 1012/3456 [24:15<54:13,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 0.2776
➡️ Total Profit: ₹10,406.03
➡️ Equity Curve R²: 0.1846
➡️ Monthly Consistency Score: 0.0372

=== [1013/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.83it/s]
Hypertuning:  29%|██▉       | 1013/3456 [24:16<55:14,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0637
➡️ Total Profit: ₹-2,395.24
➡️ Equity Curve R²: 0.0058
➡️ Monthly Consistency Score: -0.0088

=== [1014/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.39it/s]
Hypertuning:  29%|██▉       | 1014/3456 [24:18<56:22,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 0.5466
➡️ Total Profit: ₹15,335.69
➡️ Equity Curve R²: 0.0448
➡️ Monthly Consistency Score: 0.0545

=== [1015/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.13it/s]
Hypertuning:  29%|██▉       | 1015/3456 [24:19<55:20,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.2397
➡️ Total Profit: ₹20,313.48
➡️ Equity Curve R²: 0.3588
➡️ Monthly Consistency Score: 0.0877

=== [1016/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.02it/s]
Hypertuning:  29%|██▉       | 1016/3456 [24:20<54:26,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.4211
➡️ Total Profit: ₹28,572.09
➡️ Equity Curve R²: 0.2837
➡️ Monthly Consistency Score: 0.1164

=== [1017/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.70it/s]
Hypertuning:  29%|██▉       | 1017/3456 [24:22<55:11,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4993
➡️ Total Profit: ₹-34,294.84
➡️ Equity Curve R²: 0.8887
➡️ Monthly Consistency Score: -0.1255

=== [1018/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.02it/s]
Hypertuning:  29%|██▉       | 1018/3456 [24:23<56:10,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.9269
➡️ Total Profit: ₹59,032.06
➡️ Equity Curve R²: 0.7617
➡️ Monthly Consistency Score: 0.2611

=== [1019/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.50it/s]
Hypertuning:  29%|██▉       | 1019/3456 [24:24<55:22,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1697
➡️ Total Profit: ₹-6,341.25
➡️ Equity Curve R²: 0.2966
➡️ Monthly Consistency Score: -0.0240

=== [1020/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.85it/s]
Hypertuning:  30%|██▉       | 1020/3456 [24:26<54:18,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.2677
➡️ Total Profit: ₹34,172.91
➡️ Equity Curve R²: 0.1054
➡️ Monthly Consistency Score: 0.1286

=== [1021/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.44it/s]
Hypertuning:  30%|██▉       | 1021/3456 [24:27<55:11,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.6880
➡️ Total Profit: ₹17,770.13
➡️ Equity Curve R²: 0.1217
➡️ Monthly Consistency Score: 0.0629

=== [1022/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.18it/s]
Hypertuning:  30%|██▉       | 1022/3456 [24:28<54:34,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.7620
➡️ Total Profit: ₹51,921.95
➡️ Equity Curve R²: 0.1480
➡️ Monthly Consistency Score: 0.2226

=== [1023/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.02it/s]
Hypertuning:  30%|██▉       | 1023/3456 [24:30<55:02,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4414
➡️ Total Profit: ₹20,750.91
➡️ Equity Curve R²: 0.3826
➡️ Monthly Consistency Score: 0.0807

=== [1024/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.59it/s]
Hypertuning:  30%|██▉       | 1024/3456 [24:31<54:07,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.0561
➡️ Total Profit: ₹56,945.55
➡️ Equity Curve R²: 0.2583
➡️ Monthly Consistency Score: 0.2400

=== [1025/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.34it/s]
Hypertuning:  30%|██▉       | 1025/3456 [24:32<54:56,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.7311
➡️ Total Profit: ₹-58,680.97
➡️ Equity Curve R²: 0.9361
➡️ Monthly Consistency Score: -0.2699

=== [1026/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.77it/s]
Hypertuning:  30%|██▉       | 1026/3456 [24:34<55:26,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.2852
➡️ Total Profit: ₹9,030.53
➡️ Equity Curve R²: 0.4029
➡️ Monthly Consistency Score: 0.0361

=== [1027/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.01it/s]
Hypertuning:  30%|██▉       | 1027/3456 [24:35<54:39,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1279
➡️ Total Profit: ₹-4,991.64
➡️ Equity Curve R²: 0.7004
➡️ Monthly Consistency Score: -0.0219

=== [1028/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.25it/s]
Hypertuning:  30%|██▉       | 1028/3456 [24:37<55:11,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.6211
➡️ Total Profit: ₹18,185.17
➡️ Equity Curve R²: 0.1251
➡️ Monthly Consistency Score: 0.0671

=== [1029/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.00it/s]
Hypertuning:  30%|██▉       | 1029/3456 [24:38<55:02,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1092
➡️ Total Profit: ₹3,902.88
➡️ Equity Curve R²: 0.0154
➡️ Monthly Consistency Score: 0.0146

=== [1030/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.77it/s]
Hypertuning:  30%|██▉       | 1030/3456 [24:39<55:13,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.4244
➡️ Total Profit: ₹11,944.77
➡️ Equity Curve R²: 0.0066
➡️ Monthly Consistency Score: 0.0422

=== [1031/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.79it/s]
Hypertuning:  30%|██▉       | 1031/3456 [24:41<54:29,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.4448
➡️ Total Profit: ₹23,550.37
➡️ Equity Curve R²: 0.6309
➡️ Monthly Consistency Score: 0.0969

=== [1032/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.24it/s]
Hypertuning:  30%|██▉       | 1032/3456 [24:42<55:04,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.8612
➡️ Total Profit: ₹17,314.75
➡️ Equity Curve R²: 0.2413
➡️ Monthly Consistency Score: 0.0688

=== [1033/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.85it/s]
Hypertuning:  30%|██▉       | 1033/3456 [24:43<54:41,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1890
➡️ Total Profit: ₹-7,953.89
➡️ Equity Curve R²: 0.6937
➡️ Monthly Consistency Score: -0.0299

=== [1034/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.89it/s]
Hypertuning:  30%|██▉       | 1034/3456 [24:45<55:08,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.2658
➡️ Total Profit: ₹53,381.13
➡️ Equity Curve R²: 0.7143
➡️ Monthly Consistency Score: 0.2250

=== [1035/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.27it/s]
Hypertuning:  30%|██▉       | 1035/3456 [24:46<54:12,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.3515
➡️ Total Profit: ₹-14,487.14
➡️ Equity Curve R²: 0.4349
➡️ Monthly Consistency Score: -0.0540

=== [1036/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.23it/s]
Hypertuning:  30%|██▉       | 1036/3456 [24:47<54:37,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.1015
➡️ Total Profit: ₹32,041.09
➡️ Equity Curve R²: 0.0587
➡️ Monthly Consistency Score: 0.1184

=== [1037/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.29it/s]
Hypertuning:  30%|███       | 1037/3456 [24:49<54:15,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.9801
➡️ Total Profit: ₹24,699.66
➡️ Equity Curve R²: 0.1930
➡️ Monthly Consistency Score: 0.0902

=== [1038/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.20it/s]
Hypertuning:  30%|███       | 1038/3456 [24:50<54:42,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.2803
➡️ Total Profit: ₹44,853.69
➡️ Equity Curve R²: 0.2729
➡️ Monthly Consistency Score: 0.1664

=== [1039/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.47it/s]
Hypertuning:  30%|███       | 1039/3456 [24:51<53:55,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.1921
➡️ Total Profit: ₹9,342.27
➡️ Equity Curve R²: 0.4459
➡️ Monthly Consistency Score: 0.0362

=== [1040/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.49it/s]
Hypertuning:  30%|███       | 1040/3456 [24:53<54:28,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.0561
➡️ Total Profit: ₹56,945.55
➡️ Equity Curve R²: 0.2583
➡️ Monthly Consistency Score: 0.2400

=== [1041/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.82it/s]
Hypertuning:  30%|███       | 1041/3456 [24:54<54:23,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.7345
➡️ Total Profit: ₹-60,287.36
➡️ Equity Curve R²: 0.9323
➡️ Monthly Consistency Score: -0.2651

=== [1042/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.20it/s]
Hypertuning:  30%|███       | 1042/3456 [24:55<54:52,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3064
➡️ Total Profit: ₹-19,393.03
➡️ Equity Curve R²: 0.8154
➡️ Monthly Consistency Score: -0.0809

=== [1043/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.64it/s]
Hypertuning:  30%|███       | 1043/3456 [24:57<54:00,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.0226
➡️ Total Profit: ₹679.73
➡️ Equity Curve R²: 0.5556
➡️ Monthly Consistency Score: 0.0030

=== [1044/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.45it/s]
Hypertuning:  30%|███       | 1044/3456 [24:58<54:21,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2113
➡️ Total Profit: ₹7,538.71
➡️ Equity Curve R²: 0.0027
➡️ Monthly Consistency Score: 0.0274

=== [1045/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.61it/s]
Hypertuning:  30%|███       | 1045/3456 [24:59<54:07,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2138
➡️ Total Profit: ₹-7,099.94
➡️ Equity Curve R²: 0.0047
➡️ Monthly Consistency Score: -0.0275

=== [1046/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.45it/s]
Hypertuning:  30%|███       | 1046/3456 [25:01<54:50,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.4667
➡️ Total Profit: ₹27,415.81
➡️ Equity Curve R²: 0.3708
➡️ Monthly Consistency Score: 0.1024

=== [1047/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.70it/s]
Hypertuning:  30%|███       | 1047/3456 [25:02<53:52,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.2208
➡️ Total Profit: ₹39,815.85
➡️ Equity Curve R²: 0.7883
➡️ Monthly Consistency Score: 0.1641

=== [1048/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 108.23it/s]
Hypertuning:  30%|███       | 1048/3456 [25:04<54:19,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.6903
➡️ Total Profit: ₹33,450.21
➡️ Equity Curve R²: 0.4806
➡️ Monthly Consistency Score: 0.1290

=== [1049/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.07it/s]
Hypertuning:  30%|███       | 1049/3456 [25:05<55:27,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.7125
➡️ Total Profit: ₹-49,292.96
➡️ Equity Curve R²: 0.8951
➡️ Monthly Consistency Score: -0.1840

=== [1050/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.33it/s]
Hypertuning:  30%|███       | 1050/3456 [25:06<54:55,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.8107
➡️ Total Profit: ₹47,639.13
➡️ Equity Curve R²: 0.8411
➡️ Monthly Consistency Score: 0.2115

=== [1051/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.21it/s]
Hypertuning:  30%|███       | 1051/3456 [25:08<55:06,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.6138
➡️ Total Profit: ₹-36,032.05
➡️ Equity Curve R²: 0.8820
➡️ Monthly Consistency Score: -0.1265

=== [1052/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.39it/s]
Hypertuning:  30%|███       | 1052/3456 [25:09<54:14,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2517
➡️ Total Profit: ₹-16,248.82
➡️ Equity Curve R²: 0.6813
➡️ Monthly Consistency Score: -0.0569

=== [1053/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.81it/s]
Hypertuning:  30%|███       | 1053/3456 [25:10<53:51,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.0310
➡️ Total Profit: ₹25,332.01
➡️ Equity Curve R²: 0.5290
➡️ Monthly Consistency Score: 0.0949

=== [1054/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.02it/s]
Hypertuning:  30%|███       | 1054/3456 [25:12<54:15,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.8438
➡️ Total Profit: ₹32,419.09
➡️ Equity Curve R²: 0.0011
➡️ Monthly Consistency Score: 0.1252

=== [1055/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.19it/s]
Hypertuning:  31%|███       | 1055/3456 [25:13<54:41,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.0530
➡️ Total Profit: ₹2,819.53
➡️ Equity Curve R²: 0.6120
➡️ Monthly Consistency Score: 0.0112

=== [1056/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.35it/s]
Hypertuning:  31%|███       | 1056/3456 [25:14<53:59,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.8909
➡️ Total Profit: ₹39,341.01
➡️ Equity Curve R²: 0.0068
➡️ Monthly Consistency Score: 0.1574

=== [1057/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.51it/s]
Hypertuning:  31%|███       | 1057/3456 [25:16<53:58,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.5322
➡️ Total Profit: ₹-36,965.98
➡️ Equity Curve R²: 0.8892
➡️ Monthly Consistency Score: -0.1595

=== [1058/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.38it/s]
Hypertuning:  31%|███       | 1058/3456 [25:17<54:14,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1361
➡️ Total Profit: ₹-3,657.95
➡️ Equity Curve R²: 0.3464
➡️ Monthly Consistency Score: -0.0155

=== [1059/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.09it/s]
Hypertuning:  31%|███       | 1059/3456 [25:19<54:40,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.3823
➡️ Total Profit: ₹39,091.46
➡️ Equity Curve R²: 0.1657
➡️ Monthly Consistency Score: 0.1297

=== [1060/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.90it/s]
Hypertuning:  31%|███       | 1060/3456 [25:20<53:57,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.5665
➡️ Total Profit: ₹19,665.37
➡️ Equity Curve R²: 0.0971
➡️ Monthly Consistency Score: 0.0705

=== [1061/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.68it/s]
Hypertuning:  31%|███       | 1061/3456 [25:21<53:44,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4444
➡️ Total Profit: ₹13,076.98
➡️ Equity Curve R²: 0.1316
➡️ Monthly Consistency Score: 0.0506

=== [1062/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.72it/s]
Hypertuning:  31%|███       | 1062/3456 [25:23<54:00,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.7890
➡️ Total Profit: ₹-59,443.85
➡️ Equity Curve R²: 0.9571
➡️ Monthly Consistency Score: -0.2097

=== [1063/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.36it/s]
Hypertuning:  31%|███       | 1063/3456 [25:24<53:06,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 1.6175
➡️ Total Profit: ₹31,735.52
➡️ Equity Curve R²: 0.6634
➡️ Monthly Consistency Score: 0.1342

=== [1064/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.29it/s]
Hypertuning:  31%|███       | 1064/3456 [25:25<53:24,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.7982
➡️ Total Profit: ₹32,841.33
➡️ Equity Curve R²: 0.6548
➡️ Monthly Consistency Score: 0.1424

=== [1065/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.39it/s]
Hypertuning:  31%|███       | 1065/3456 [25:27<54:27,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3486
➡️ Total Profit: ₹-20,425.44
➡️ Equity Curve R²: 0.8481
➡️ Monthly Consistency Score: -0.0736

=== [1066/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.12it/s]
Hypertuning:  31%|███       | 1066/3456 [25:28<53:49,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.1309
➡️ Total Profit: ₹31,830.49
➡️ Equity Curve R²: 0.1718
➡️ Monthly Consistency Score: 0.1247

=== [1067/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.94it/s]
Hypertuning:  31%|███       | 1067/3456 [25:29<54:24,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.4915
➡️ Total Profit: ₹17,174.42
➡️ Equity Curve R²: 0.1493
➡️ Monthly Consistency Score: 0.0723

=== [1068/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.08it/s]
Hypertuning:  31%|███       | 1068/3456 [25:31<53:40,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.7822
➡️ Total Profit: ₹25,172.09
➡️ Equity Curve R²: 0.0240
➡️ Monthly Consistency Score: 0.0956

=== [1069/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.10it/s]
Hypertuning:  31%|███       | 1069/3456 [25:32<53:56,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.3846
➡️ Total Profit: ₹32,270.94
➡️ Equity Curve R²: 0.4242
➡️ Monthly Consistency Score: 0.1169

=== [1070/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.88it/s]
Hypertuning:  31%|███       | 1070/3456 [25:33<54:23,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.4965
➡️ Total Profit: ₹51,623.09
➡️ Equity Curve R²: 0.0044
➡️ Monthly Consistency Score: 0.2255

=== [1071/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.78it/s]
Hypertuning:  31%|███       | 1071/3456 [25:35<54:46,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 4.4950
➡️ Total Profit: ₹94,447.07
➡️ Equity Curve R²: 0.6748
➡️ Monthly Consistency Score: 0.3988

=== [1072/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 129.06it/s]
Hypertuning:  31%|███       | 1072/3456 [25:36<53:58,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.5587
➡️ Total Profit: ₹60,641.01
➡️ Equity Curve R²: 0.6476
➡️ Monthly Consistency Score: 0.2836

=== [1073/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.99it/s]
Hypertuning:  31%|███       | 1073/3456 [25:37<53:36,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.5942
➡️ Total Profit: ₹-45,219.68
➡️ Equity Curve R²: 0.9057
➡️ Monthly Consistency Score: -0.1921

=== [1074/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.69it/s]
Hypertuning:  31%|███       | 1074/3456 [25:39<54:28,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.0596
➡️ Total Profit: ₹1,472.89
➡️ Equity Curve R²: 0.1654
➡️ Monthly Consistency Score: 0.0062

=== [1075/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.81it/s]
Hypertuning:  31%|███       | 1075/3456 [25:40<53:33,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.8535
➡️ Total Profit: ₹25,197.35
➡️ Equity Curve R²: 0.0094
➡️ Monthly Consistency Score: 0.0884

=== [1076/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.03it/s]
Hypertuning:  31%|███       | 1076/3456 [25:42<53:47,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.0144
➡️ Total Profit: ₹31,054.41
➡️ Equity Curve R²: 0.0341
➡️ Monthly Consistency Score: 0.1103

=== [1077/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.58it/s]
Hypertuning:  31%|███       | 1077/3456 [25:43<55:13,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 0.5314
➡️ Total Profit: ₹14,966.51
➡️ Equity Curve R²: 0.1934
➡️ Monthly Consistency Score: 0.0577

=== [1078/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.24it/s]
Hypertuning:  31%|███       | 1078/3456 [25:44<54:45,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.6452
➡️ Total Profit: ₹-42,494.76
➡️ Equity Curve R²: 0.9291
➡️ Monthly Consistency Score: -0.1547

=== [1079/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 130.46it/s]
Hypertuning:  31%|███       | 1079/3456 [25:46<53:51,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.6175
➡️ Total Profit: ₹31,735.52
➡️ Equity Curve R²: 0.6634
➡️ Monthly Consistency Score: 0.1342

=== [1080/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 101.32it/s]
Hypertuning:  31%|███▏      | 1080/3456 [25:47<54:06,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.7982
➡️ Total Profit: ₹32,841.33
➡️ Equity Curve R²: 0.6548
➡️ Monthly Consistency Score: 0.1424

=== [1081/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 100.32it/s]
Hypertuning:  31%|███▏      | 1081/3456 [25:48<53:50,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0102
➡️ Total Profit: ₹-379.79
➡️ Equity Curve R²: 0.5817
➡️ Monthly Consistency Score: -0.0014

=== [1082/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 100.80it/s]
Hypertuning:  31%|███▏      | 1082/3456 [25:50<54:08,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.0104
➡️ Total Profit: ₹28,441.41
➡️ Equity Curve R²: 0.1979
➡️ Monthly Consistency Score: 0.1094

=== [1083/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.75it/s]
Hypertuning:  31%|███▏      | 1083/3456 [25:51<54:30,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.4915
➡️ Total Profit: ₹17,174.42
➡️ Equity Curve R²: 0.1493
➡️ Monthly Consistency Score: 0.0723

=== [1084/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.00it/s]
Hypertuning:  31%|███▏      | 1084/3456 [25:53<53:42,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.8167
➡️ Total Profit: ₹45,307.55
➡️ Equity Curve R²: 0.5369
➡️ Monthly Consistency Score: 0.1801

=== [1085/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 107.62it/s]
Hypertuning:  31%|███▏      | 1085/3456 [25:54<53:34,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.4387
➡️ Total Profit: ₹33,531.88
➡️ Equity Curve R²: 0.4123
➡️ Monthly Consistency Score: 0.1213

=== [1086/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.50it/s]
Hypertuning:  31%|███▏      | 1086/3456 [25:55<54:08,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.5810
➡️ Total Profit: ₹52,752.17
➡️ Equity Curve R²: 0.0101
➡️ Monthly Consistency Score: 0.2310

=== [1087/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.06it/s]
Hypertuning:  31%|███▏      | 1087/3456 [25:57<54:26,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 5.6710
➡️ Total Profit: ₹110,924.33
➡️ Equity Curve R²: 0.8282
➡️ Monthly Consistency Score: 0.4568

=== [1088/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.92it/s]
Hypertuning:  31%|███▏      | 1088/3456 [25:58<53:38,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.5587
➡️ Total Profit: ₹60,641.01
➡️ Equity Curve R²: 0.6476
➡️ Monthly Consistency Score: 0.2836

=== [1089/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.63it/s]
Hypertuning:  32%|███▏      | 1089/3456 [25:59<54:49,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.6750
➡️ Total Profit: ₹-47,742.50
➡️ Equity Curve R²: 0.9322
➡️ Monthly Consistency Score: -0.2178

=== [1090/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.88it/s]
Hypertuning:  32%|███▏      | 1090/3456 [26:01<53:59,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.6140
➡️ Total Profit: ₹15,116.45
➡️ Equity Curve R²: 0.0230
➡️ Monthly Consistency Score: 0.0620

=== [1091/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.77it/s]
Hypertuning:  32%|███▏      | 1091/3456 [26:02<53:04,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1489
➡️ Total Profit: ₹5,181.40
➡️ Equity Curve R²: 0.3556
➡️ Monthly Consistency Score: 0.0182

=== [1092/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.14it/s]
Hypertuning:  32%|███▏      | 1092/3456 [26:03<53:14,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.0498
➡️ Total Profit: ₹24,658.95
➡️ Equity Curve R²: 0.1098
➡️ Monthly Consistency Score: 0.0897

=== [1093/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.06it/s]
Hypertuning:  32%|███▏      | 1093/3456 [26:05<52:57,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.3726
➡️ Total Profit: ₹10,258.99
➡️ Equity Curve R²: 0.0587
➡️ Monthly Consistency Score: 0.0409

=== [1094/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.82it/s]
Hypertuning:  32%|███▏      | 1094/3456 [26:06<53:23,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.5399
➡️ Total Profit: ₹-30,069.36
➡️ Equity Curve R²: 0.8963
➡️ Monthly Consistency Score: -0.1134

=== [1095/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.31it/s]
Hypertuning:  32%|███▏      | 1095/3456 [26:08<53:54,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.5345
➡️ Total Profit: ₹30,106.89
➡️ Equity Curve R²: 0.6399
➡️ Monthly Consistency Score: 0.1273

=== [1096/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.52it/s]
Hypertuning:  32%|███▏      | 1096/3456 [26:09<53:23,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.7650
➡️ Total Profit: ₹32,235.81
➡️ Equity Curve R²: 0.7050
➡️ Monthly Consistency Score: 0.1362

=== [1097/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.94it/s]
Hypertuning:  32%|███▏      | 1097/3456 [26:10<52:56,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3032
➡️ Total Profit: ₹-17,957.75
➡️ Equity Curve R²: 0.7921
➡️ Monthly Consistency Score: -0.0667

=== [1098/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.99it/s]
Hypertuning:  32%|███▏      | 1098/3456 [26:12<53:18,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.9239
➡️ Total Profit: ₹24,961.25
➡️ Equity Curve R²: 0.4815
➡️ Monthly Consistency Score: 0.1011

=== [1099/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.27it/s]
Hypertuning:  32%|███▏      | 1099/3456 [26:13<52:27,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.2589
➡️ Total Profit: ₹30,917.16
➡️ Equity Curve R²: 0.1150
➡️ Monthly Consistency Score: 0.1251

=== [1100/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.66it/s]
Hypertuning:  32%|███▏      | 1100/3456 [26:14<52:49,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.7577
➡️ Total Profit: ₹44,343.91
➡️ Equity Curve R²: 0.5882
➡️ Monthly Consistency Score: 0.1925

=== [1101/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.17it/s]
Hypertuning:  32%|███▏      | 1101/3456 [26:16<52:49,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.6636
➡️ Total Profit: ₹36,678.59
➡️ Equity Curve R²: 0.5086
➡️ Monthly Consistency Score: 0.1344

=== [1102/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.16it/s]
Hypertuning:  32%|███▏      | 1102/3456 [26:17<53:13,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.6064
➡️ Total Profit: ₹73,619.42
➡️ Equity Curve R²: 0.4028
➡️ Monthly Consistency Score: 0.3212

=== [1103/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.57it/s]
Hypertuning:  32%|███▏      | 1103/3456 [26:18<52:25,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 5.5877
➡️ Total Profit: ₹109,295.70
➡️ Equity Curve R²: 0.8282
➡️ Monthly Consistency Score: 0.4546

=== [1104/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.70it/s]
Hypertuning:  32%|███▏      | 1104/3456 [26:20<52:44,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.5587
➡️ Total Profit: ₹60,641.01
➡️ Equity Curve R²: 0.6476
➡️ Monthly Consistency Score: 0.2836

=== [1105/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.37it/s]
Hypertuning:  32%|███▏      | 1105/3456 [26:21<53:57,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.5413
➡️ Total Profit: ₹-37,595.51
➡️ Equity Curve R²: 0.8921
➡️ Monthly Consistency Score: -0.1618

=== [1106/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.84it/s]
Hypertuning:  32%|███▏      | 1106/3456 [26:22<53:07,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0134
➡️ Total Profit: ₹343.81
➡️ Equity Curve R²: 0.1961
➡️ Monthly Consistency Score: 0.0014

=== [1107/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.45it/s]
Hypertuning:  32%|███▏      | 1107/3456 [26:24<53:24,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.3246
➡️ Total Profit: ₹37,460.09
➡️ Equity Curve R²: 0.1532
➡️ Monthly Consistency Score: 0.1249

=== [1108/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.01it/s]
Hypertuning:  32%|███▏      | 1108/3456 [26:25<52:31,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.4759
➡️ Total Profit: ₹17,533.55
➡️ Equity Curve R²: 0.1590
➡️ Monthly Consistency Score: 0.0623

=== [1109/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.76it/s]
Hypertuning:  32%|███▏      | 1109/3456 [26:26<53:25,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.4142
➡️ Total Profit: ₹12,447.45
➡️ Equity Curve R²: 0.1148
➡️ Monthly Consistency Score: 0.0480

=== [1110/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.18it/s]
Hypertuning:  32%|███▏      | 1110/3456 [26:28<52:42,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.7381
➡️ Total Profit: ₹-56,838.32
➡️ Equity Curve R²: 0.9578
➡️ Monthly Consistency Score: -0.1985

=== [1111/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.30it/s]
Hypertuning:  32%|███▏      | 1111/3456 [26:29<53:06,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.6175
➡️ Total Profit: ₹31,735.52
➡️ Equity Curve R²: 0.6634
➡️ Monthly Consistency Score: 0.1342

=== [1112/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.21it/s]
Hypertuning:  32%|███▏      | 1112/3456 [26:30<52:22,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.7982
➡️ Total Profit: ₹32,841.33
➡️ Equity Curve R²: 0.6548
➡️ Monthly Consistency Score: 0.1424

=== [1113/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.65it/s]
Hypertuning:  32%|███▏      | 1113/3456 [26:32<53:23,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3593
➡️ Total Profit: ₹-21,054.97
➡️ Equity Curve R²: 0.8535
➡️ Monthly Consistency Score: -0.0755

=== [1114/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.24it/s]
Hypertuning:  32%|███▏      | 1114/3456 [26:33<52:52,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.0907
➡️ Total Profit: ₹30,701.41
➡️ Equity Curve R²: 0.1388
➡️ Monthly Consistency Score: 0.1193

=== [1115/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.67it/s]
Hypertuning:  32%|███▏      | 1115/3456 [26:35<52:08,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.4915
➡️ Total Profit: ₹17,174.42
➡️ Equity Curve R²: 0.1493
➡️ Monthly Consistency Score: 0.0723

=== [1116/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.78it/s]
Hypertuning:  32%|███▏      | 1116/3456 [26:36<52:36,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.7822
➡️ Total Profit: ₹25,172.09
➡️ Equity Curve R²: 0.0240
➡️ Monthly Consistency Score: 0.0956

=== [1117/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.91it/s]
Hypertuning:  32%|███▏      | 1117/3456 [26:37<52:35,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.3576
➡️ Total Profit: ₹31,641.41
➡️ Equity Curve R²: 0.4096
➡️ Monthly Consistency Score: 0.1143

=== [1118/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.81it/s]
Hypertuning:  32%|███▏      | 1118/3456 [26:39<52:54,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.5810
➡️ Total Profit: ₹52,752.17
➡️ Equity Curve R²: 0.0101
➡️ Monthly Consistency Score: 0.2310

=== [1119/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.07it/s]
Hypertuning:  32%|███▏      | 1119/3456 [26:40<51:59,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 4.4950
➡️ Total Profit: ₹94,447.07
➡️ Equity Curve R²: 0.6748
➡️ Monthly Consistency Score: 0.3988

=== [1120/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.97it/s]
Hypertuning:  32%|███▏      | 1120/3456 [26:41<52:17,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 3.5587
➡️ Total Profit: ₹60,641.01
➡️ Equity Curve R²: 0.6476
➡️ Monthly Consistency Score: 0.2836

=== [1121/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.32it/s]
Hypertuning:  32%|███▏      | 1121/3456 [26:43<53:27,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.5997
➡️ Total Profit: ₹-45,849.21
➡️ Equity Curve R²: 0.9201
➡️ Monthly Consistency Score: -0.2003

=== [1122/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.18it/s]
Hypertuning:  32%|███▏      | 1122/3456 [26:44<52:48,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4464
➡️ Total Profit: ₹11,029.29
➡️ Equity Curve R²: 0.0444
➡️ Monthly Consistency Score: 0.0466

=== [1123/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.75it/s]
Hypertuning:  32%|███▏      | 1123/3456 [26:45<53:18,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.1137
➡️ Total Profit: ₹3,940.09
➡️ Equity Curve R²: 0.3382
➡️ Monthly Consistency Score: 0.0143

=== [1124/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.27it/s]
Hypertuning:  33%|███▎      | 1124/3456 [26:47<52:35,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.0498
➡️ Total Profit: ₹24,658.95
➡️ Equity Curve R²: 0.1098
➡️ Monthly Consistency Score: 0.0897

=== [1125/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.50it/s]
Hypertuning:  33%|███▎      | 1125/3456 [26:48<53:38,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.5985
➡️ Total Profit: ₹16,855.10
➡️ Equity Curve R²: 0.2208
➡️ Monthly Consistency Score: 0.0650

=== [1126/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.89it/s]
Hypertuning:  33%|███▎      | 1126/3456 [26:50<52:51,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.6052
➡️ Total Profit: ₹-43,280.16
➡️ Equity Curve R²: 0.9331
➡️ Monthly Consistency Score: -0.1509

=== [1127/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.52it/s]
Hypertuning:  33%|███▎      | 1127/3456 [26:51<53:11,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.2853
➡️ Total Profit: ₹25,218.26
➡️ Equity Curve R²: 0.5211
➡️ Monthly Consistency Score: 0.1051

=== [1128/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.13it/s]
Hypertuning:  33%|███▎      | 1128/3456 [26:52<52:25,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.5316
➡️ Total Profit: ₹27,972.17
➡️ Equity Curve R²: 0.6306
➡️ Monthly Consistency Score: 0.1211

=== [1129/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.37it/s]
Hypertuning:  33%|███▎      | 1129/3456 [26:54<53:24,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.1116
➡️ Total Profit: ₹4,026.92
➡️ Equity Curve R²: 0.5090
➡️ Monthly Consistency Score: 0.0149

=== [1130/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.96it/s]
Hypertuning:  33%|███▎      | 1130/3456 [26:55<52:49,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.8499
➡️ Total Profit: ₹23,921.41
➡️ Equity Curve R²: 0.0674
➡️ Monthly Consistency Score: 0.0887

=== [1131/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.49it/s]
Hypertuning:  33%|███▎      | 1131/3456 [26:56<52:05,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.1084
➡️ Total Profit: ₹4,139.89
➡️ Equity Curve R²: 0.4542
➡️ Monthly Consistency Score: 0.0164

=== [1132/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.53it/s]
Hypertuning:  33%|███▎      | 1132/3456 [26:58<52:25,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.8167
➡️ Total Profit: ₹45,307.55
➡️ Equity Curve R²: 0.5369
➡️ Monthly Consistency Score: 0.1801

=== [1133/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.70it/s]
Hypertuning:  33%|███▎      | 1133/3456 [26:59<53:28,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.5342
➡️ Total Profit: ₹34,790.94
➡️ Equity Curve R²: 0.4210
➡️ Monthly Consistency Score: 0.1270

=== [1134/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.65it/s]
Hypertuning:  33%|███▎      | 1134/3456 [27:00<52:46,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.4963
➡️ Total Profit: ₹51,621.25
➡️ Equity Curve R²: 0.0025
➡️ Monthly Consistency Score: 0.2243

=== [1135/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.40it/s]
Hypertuning:  33%|███▎      | 1135/3456 [27:02<51:53,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 5.5877
➡️ Total Profit: ₹109,295.70
➡️ Equity Curve R²: 0.8282
➡️ Monthly Consistency Score: 0.4546

=== [1136/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.44it/s]
Hypertuning:  33%|███▎      | 1136/3456 [27:03<52:15,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.5587
➡️ Total Profit: ₹60,641.01
➡️ Equity Curve R²: 0.6476
➡️ Monthly Consistency Score: 0.2836

=== [1137/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.06it/s]
Hypertuning:  33%|███▎      | 1137/3456 [27:05<53:23,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.6738
➡️ Total Profit: ₹-50,961.56
➡️ Equity Curve R²: 0.9350
➡️ Monthly Consistency Score: -0.2237

=== [1138/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.91it/s]
Hypertuning:  33%|███▎      | 1138/3456 [27:06<52:39,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1366
➡️ Total Profit: ₹-5,830.71
➡️ Equity Curve R²: 0.7181
➡️ Monthly Consistency Score: -0.0235

=== [1139/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.81it/s]
Hypertuning:  33%|███▎      | 1139/3456 [27:07<53:16,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.2152
➡️ Total Profit: ₹6,354.08
➡️ Equity Curve R²: 0.1981
➡️ Monthly Consistency Score: 0.0224

=== [1140/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.83it/s]
Hypertuning:  33%|███▎      | 1140/3456 [27:09<52:35,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.7202
➡️ Total Profit: ₹17,447.95
➡️ Equity Curve R²: 0.0865
➡️ Monthly Consistency Score: 0.0637

=== [1141/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.51it/s]
Hypertuning:  33%|███▎      | 1141/3456 [27:10<52:14,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1631
➡️ Total Profit: ₹4,594.16
➡️ Equity Curve R²: 0.0676
➡️ Monthly Consistency Score: 0.0187

=== [1142/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 108.11it/s]
Hypertuning:  33%|███▎      | 1142/3456 [27:11<52:39,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4429
➡️ Total Profit: ₹-26,323.96
➡️ Equity Curve R²: 0.8749
➡️ Monthly Consistency Score: -0.0958

=== [1143/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.50it/s]
Hypertuning:  33%|███▎      | 1143/3456 [27:13<51:47,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.0305
➡️ Total Profit: ₹39,838.22
➡️ Equity Curve R²: 0.7432
➡️ Monthly Consistency Score: 0.1579

=== [1144/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.60it/s]
Hypertuning:  33%|███▎      | 1144/3456 [27:14<52:05,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.0651
➡️ Total Profit: ₹37,715.81
➡️ Equity Curve R²: 0.6678
➡️ Monthly Consistency Score: 0.1552

=== [1145/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.86it/s]
Hypertuning:  33%|███▎      | 1145/3456 [27:15<53:00,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.6405
➡️ Total Profit: ₹-38,572.15
➡️ Equity Curve R²: 0.8678
➡️ Monthly Consistency Score: -0.1443

=== [1146/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.64it/s]
Hypertuning:  33%|███▎      | 1146/3456 [27:17<52:18,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.6981
➡️ Total Profit: ₹20,437.57
➡️ Equity Curve R²: 0.2535
➡️ Monthly Consistency Score: 0.0790

=== [1147/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.52it/s]
Hypertuning:  33%|███▎      | 1147/3456 [27:18<52:43,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1639
➡️ Total Profit: ₹27,651.68
➡️ Equity Curve R²: 0.0715
➡️ Monthly Consistency Score: 0.1107

=== [1148/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.57it/s]
Hypertuning:  33%|███▎      | 1148/3456 [27:19<51:59,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 4.2268
➡️ Total Profit: ₹64,000.20
➡️ Equity Curve R²: 0.8113
➡️ Monthly Consistency Score: 0.2992

=== [1149/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.18it/s]
Hypertuning:  33%|███▎      | 1149/3456 [27:21<51:42,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.9209
➡️ Total Profit: ₹42,350.00
➡️ Equity Curve R²: 0.7285
➡️ Monthly Consistency Score: 0.1717

=== [1150/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.78it/s]
Hypertuning:  33%|███▎      | 1150/3456 [27:22<52:12,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.6318
➡️ Total Profit: ₹71,359.42
➡️ Equity Curve R²: 0.3571
➡️ Monthly Consistency Score: 0.2943

=== [1151/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.05it/s]
Hypertuning:  33%|███▎      | 1151/3456 [27:24<52:49,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 5.7542
➡️ Total Profit: ₹112,552.96
➡️ Equity Curve R²: 0.8385
➡️ Monthly Consistency Score: 0.4638

=== [1152/3456] Testing Parameters ===
smooth_length: 5
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.24it/s]
Hypertuning:  33%|███▎      | 1152/3456 [27:25<51:52,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.5587
➡️ Total Profit: ₹60,641.01
➡️ Equity Curve R²: 0.6530
➡️ Monthly Consistency Score: 0.2881

=== [1153/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.18it/s]
Hypertuning:  33%|███▎      | 1153/3456 [27:26<51:37,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.6779
➡️ Total Profit: ₹-50,466.29
➡️ Equity Curve R²: 0.9604
➡️ Monthly Consistency Score: -0.2094

=== [1154/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.21it/s]
Hypertuning:  33%|███▎      | 1154/3456 [27:28<52:08,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1363
➡️ Total Profit: ₹-5,558.59
➡️ Equity Curve R²: 0.6555
➡️ Monthly Consistency Score: -0.0232

=== [1155/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 130.21it/s]
Hypertuning:  33%|███▎      | 1155/3456 [27:29<52:31,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.5062
➡️ Total Profit: ₹14,258.01
➡️ Equity Curve R²: 0.0717
➡️ Monthly Consistency Score: 0.0594

=== [1156/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.67it/s]
Hypertuning:  33%|███▎      | 1156/3456 [27:30<51:47,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.7528
➡️ Total Profit: ₹30,416.75
➡️ Equity Curve R²: 0.6260
➡️ Monthly Consistency Score: 0.1143

=== [1157/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.91it/s]
Hypertuning:  33%|███▎      | 1157/3456 [27:32<51:31,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.4611
➡️ Total Profit: ₹13,021.37
➡️ Equity Curve R²: 0.3964
➡️ Monthly Consistency Score: 0.0463

=== [1158/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.03it/s]
Hypertuning:  34%|███▎      | 1158/3456 [27:33<51:51,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.2776
➡️ Total Profit: ₹28,875.69
➡️ Equity Curve R²: 0.4357
➡️ Monthly Consistency Score: 0.1074

=== [1159/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 110.83it/s]
Hypertuning:  34%|███▎      | 1159/3456 [27:34<52:23,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.6666
➡️ Total Profit: ₹21,879.74
➡️ Equity Curve R²: 0.0369
➡️ Monthly Consistency Score: 0.0795

=== [1160/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.88it/s]
Hypertuning:  34%|███▎      | 1160/3456 [27:36<51:51,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3626
➡️ Total Profit: ₹-17,972.46
➡️ Equity Curve R²: 0.4801
➡️ Monthly Consistency Score: -0.0633

=== [1161/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.25it/s]
Hypertuning:  34%|███▎      | 1161/3456 [27:37<51:35,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2313
➡️ Total Profit: ₹-11,091.80
➡️ Equity Curve R²: 0.6259
➡️ Monthly Consistency Score: -0.0377

=== [1162/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.95it/s]
Hypertuning:  34%|███▎      | 1162/3456 [27:38<52:02,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.4831
➡️ Total Profit: ₹41,901.13
➡️ Equity Curve R²: 0.3300
➡️ Monthly Consistency Score: 0.1798

=== [1163/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.04it/s]
Hypertuning:  34%|███▎      | 1163/3456 [27:40<51:11,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.2791
➡️ Total Profit: ₹12,285.79
➡️ Equity Curve R²: 0.3321
➡️ Monthly Consistency Score: 0.0436

=== [1164/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.46it/s]
Hypertuning:  34%|███▎      | 1164/3456 [27:41<51:24,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.0312
➡️ Total Profit: ₹26,352.83
➡️ Equity Curve R²: 0.5643
➡️ Monthly Consistency Score: 0.0975

=== [1165/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.86it/s]
Hypertuning:  34%|███▎      | 1165/3456 [27:43<52:20,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.2244
➡️ Total Profit: ₹39,613.89
➡️ Equity Curve R²: 0.1123
➡️ Monthly Consistency Score: 0.1668

=== [1166/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.32it/s]
Hypertuning:  34%|███▎      | 1166/3456 [27:44<51:42,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.3366
➡️ Total Profit: ₹66,014.72
➡️ Equity Curve R²: 0.5386
➡️ Monthly Consistency Score: 0.2656

=== [1167/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.76it/s]
Hypertuning:  34%|███▍      | 1167/3456 [27:45<52:06,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.4623
➡️ Total Profit: ₹45,286.04
➡️ Equity Curve R²: 0.1845
➡️ Monthly Consistency Score: 0.1853

=== [1168/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.92it/s]
Hypertuning:  34%|███▍      | 1168/3456 [27:47<51:30,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.9401
➡️ Total Profit: ₹64,901.01
➡️ Equity Curve R²: 0.5850
➡️ Monthly Consistency Score: 0.3103

=== [1169/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.69it/s]
Hypertuning:  34%|███▍      | 1169/3456 [27:48<51:28,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6369
➡️ Total Profit: ₹-42,064.08
➡️ Equity Curve R²: 0.9421
➡️ Monthly Consistency Score: -0.1826

=== [1170/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.26it/s]
Hypertuning:  34%|███▍      | 1170/3456 [27:49<51:49,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0026
➡️ Total Profit: ₹95.85
➡️ Equity Curve R²: 0.3835
➡️ Monthly Consistency Score: 0.0004

=== [1171/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.26it/s]
Hypertuning:  34%|███▍      | 1171/3456 [27:51<52:07,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0837
➡️ Total Profit: ₹-3,667.88
➡️ Equity Curve R²: 0.6373
➡️ Monthly Consistency Score: -0.0144

=== [1172/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.72it/s]
Hypertuning:  34%|███▍      | 1172/3456 [27:52<51:23,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4518
➡️ Total Profit: ₹13,202.11
➡️ Equity Curve R²: 0.0078
➡️ Monthly Consistency Score: 0.0491

=== [1173/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.52it/s]
Hypertuning:  34%|███▍      | 1173/3456 [27:53<52:15,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.6440
➡️ Total Profit: ₹16,967.83
➡️ Equity Curve R²: 0.4544
➡️ Monthly Consistency Score: 0.0582

=== [1174/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.49it/s]
Hypertuning:  34%|███▍      | 1174/3456 [27:55<51:37,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.7703
➡️ Total Profit: ₹19,137.53
➡️ Equity Curve R²: 0.1356
➡️ Monthly Consistency Score: 0.0777

=== [1175/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.88it/s]
Hypertuning:  34%|███▍      | 1175/3456 [27:56<50:49,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.2955
➡️ Total Profit: ₹12,127.59
➡️ Equity Curve R²: 0.2895
➡️ Monthly Consistency Score: 0.0432

=== [1176/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.02it/s]
Hypertuning:  34%|███▍      | 1176/3456 [27:57<51:11,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0167
➡️ Total Profit: ₹-626.16
➡️ Equity Curve R²: 0.3814
➡️ Monthly Consistency Score: -0.0023

=== [1177/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.12it/s]
Hypertuning:  34%|███▍      | 1177/3456 [27:59<52:09,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2382
➡️ Total Profit: ₹-11,720.39
➡️ Equity Curve R²: 0.6522
➡️ Monthly Consistency Score: -0.0399

=== [1178/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.36it/s]
Hypertuning:  34%|███▍      | 1178/3456 [28:00<51:41,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.6830
➡️ Total Profit: ₹47,548.37
➡️ Equity Curve R²: 0.4059
➡️ Monthly Consistency Score: 0.2023

=== [1179/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.46it/s]
Hypertuning:  34%|███▍      | 1179/3456 [28:02<52:01,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1033
➡️ Total Profit: ₹-4,714.22
➡️ Equity Curve R²: 0.7215
➡️ Monthly Consistency Score: -0.0177

=== [1180/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.73it/s]
Hypertuning:  34%|███▍      | 1180/3456 [28:03<51:19,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.1146
➡️ Total Profit: ₹28,484.65
➡️ Equity Curve R²: 0.5630
➡️ Monthly Consistency Score: 0.1039

=== [1181/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.93it/s]
Hypertuning:  34%|███▍      | 1181/3456 [28:04<51:01,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.7193
➡️ Total Profit: ₹31,428.12
➡️ Equity Curve R²: 0.0397
➡️ Monthly Consistency Score: 0.1315

=== [1182/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.02it/s]
Hypertuning:  34%|███▍      | 1182/3456 [28:06<51:26,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.4166
➡️ Total Profit: ₹68,274.72
➡️ Equity Curve R²: 0.5154
➡️ Monthly Consistency Score: 0.2719

=== [1183/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.09it/s]
Hypertuning:  34%|███▍      | 1183/3456 [28:07<51:50,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.5676
➡️ Total Profit: ₹48,546.04
➡️ Equity Curve R²: 0.1630
➡️ Monthly Consistency Score: 0.1962

=== [1184/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.80it/s]
Hypertuning:  34%|███▍      | 1184/3456 [28:08<51:11,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 4.1534
➡️ Total Profit: ₹62,769.19
➡️ Equity Curve R²: 0.5796
➡️ Monthly Consistency Score: 0.2833

=== [1185/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.57it/s]
Hypertuning:  34%|███▍      | 1185/3456 [28:10<51:05,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6962
➡️ Total Profit: ₹-45,001.87
➡️ Equity Curve R²: 0.9071
➡️ Monthly Consistency Score: -0.1924

=== [1186/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.02it/s]
Hypertuning:  34%|███▍      | 1186/3456 [28:11<51:26,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2417
➡️ Total Profit: ₹-10,675.03
➡️ Equity Curve R²: 0.7370
➡️ Monthly Consistency Score: -0.0435

=== [1187/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.72it/s]
Hypertuning:  34%|███▍      | 1187/3456 [28:12<52:02,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.2525
➡️ Total Profit: ₹11,069.26
➡️ Equity Curve R²: 0.3662
➡️ Monthly Consistency Score: 0.0454

=== [1188/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.41it/s]
Hypertuning:  34%|███▍      | 1188/3456 [28:14<51:07,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2664
➡️ Total Profit: ₹9,684.89
➡️ Equity Curve R²: 0.0380
➡️ Monthly Consistency Score: 0.0359

=== [1189/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.98it/s]
Hypertuning:  34%|███▍      | 1189/3456 [28:15<52:00,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.3894
➡️ Total Profit: ₹-13,393.36
➡️ Equity Curve R²: 0.6283
➡️ Monthly Consistency Score: -0.0465

=== [1190/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.13it/s]
Hypertuning:  34%|███▍      | 1190/3456 [28:16<51:20,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.2934
➡️ Total Profit: ₹34,182.93
➡️ Equity Curve R²: 0.2885
➡️ Monthly Consistency Score: 0.1329

=== [1191/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.09it/s]
Hypertuning:  34%|███▍      | 1191/3456 [28:18<50:34,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.5172
➡️ Total Profit: ₹39,776.59
➡️ Equity Curve R²: 0.6693
➡️ Monthly Consistency Score: 0.1476

=== [1192/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.56it/s]
Hypertuning:  34%|███▍      | 1192/3456 [28:19<50:56,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.8714
➡️ Total Profit: ₹24,636.51
➡️ Equity Curve R²: 0.1154
➡️ Monthly Consistency Score: 0.0906

=== [1193/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.85it/s]
Hypertuning:  35%|███▍      | 1193/3456 [28:21<51:47,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3286
➡️ Total Profit: ₹-18,650.86
➡️ Equity Curve R²: 0.8156
➡️ Monthly Consistency Score: -0.0626

=== [1194/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.92it/s]
Hypertuning:  35%|███▍      | 1194/3456 [28:22<51:09,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.8546
➡️ Total Profit: ₹56,588.38
➡️ Equity Curve R²: 0.1414
➡️ Monthly Consistency Score: 0.2428

=== [1195/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.10it/s]
Hypertuning:  35%|███▍      | 1195/3456 [28:23<51:43,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.6844
➡️ Total Profit: ₹23,347.96
➡️ Equity Curve R²: 0.0005
➡️ Monthly Consistency Score: 0.0936

=== [1196/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.15it/s]
Hypertuning:  35%|███▍      | 1196/3456 [28:25<51:09,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.8933
➡️ Total Profit: ₹44,356.47
➡️ Equity Curve R²: 0.6115
➡️ Monthly Consistency Score: 0.1543

=== [1197/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.89it/s]
Hypertuning:  35%|███▍      | 1197/3456 [28:26<50:55,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.9610
➡️ Total Profit: ₹38,357.65
➡️ Equity Curve R²: 0.0043
➡️ Monthly Consistency Score: 0.1589

=== [1198/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.85it/s]
Hypertuning:  35%|███▍      | 1198/3456 [28:27<51:19,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.9857
➡️ Total Profit: ₹49,371.85
➡️ Equity Curve R²: 0.0489
➡️ Monthly Consistency Score: 0.2169

=== [1199/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.09it/s]
Hypertuning:  35%|███▍      | 1199/3456 [28:29<51:46,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.5150
➡️ Total Profit: ₹46,917.41
➡️ Equity Curve R²: 0.2190
➡️ Monthly Consistency Score: 0.1919

=== [1200/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.50it/s]
Hypertuning:  35%|███▍      | 1200/3456 [28:30<51:08,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 4.0695
➡️ Total Profit: ₹67,032.83
➡️ Equity Curve R²: 0.5770
➡️ Monthly Consistency Score: 0.3114

=== [1201/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.16it/s]
Hypertuning:  35%|███▍      | 1201/3456 [28:31<50:47,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6609
➡️ Total Profit: ₹-49,208.17
➡️ Equity Curve R²: 0.9592
➡️ Monthly Consistency Score: -0.2016

=== [1202/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.36it/s]
Hypertuning:  35%|███▍      | 1202/3456 [28:33<51:13,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1557
➡️ Total Profit: ₹-6,171.27
➡️ Equity Curve R²: 0.6311
➡️ Monthly Consistency Score: -0.0261

=== [1203/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.78it/s]
Hypertuning:  35%|███▍      | 1203/3456 [28:34<51:41,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.5778
➡️ Total Profit: ₹16,276.70
➡️ Equity Curve R²: 0.0244
➡️ Monthly Consistency Score: 0.0667

=== [1204/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.82it/s]
Hypertuning:  35%|███▍      | 1204/3456 [28:36<50:57,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.3288
➡️ Total Profit: ₹40,413.11
➡️ Equity Curve R²: 0.7898
➡️ Monthly Consistency Score: 0.1526

=== [1205/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.12it/s]
Hypertuning:  35%|███▍      | 1205/3456 [28:37<50:36,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.5057
➡️ Total Profit: ₹14,281.37
➡️ Equity Curve R²: 0.4178
➡️ Monthly Consistency Score: 0.0509

=== [1206/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.42it/s]
Hypertuning:  35%|███▍      | 1206/3456 [28:38<51:24,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1276
➡️ Total Profit: ₹25,484.77
➡️ Equity Curve R²: 0.3051
➡️ Monthly Consistency Score: 0.0941

=== [1207/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.79it/s]
Hypertuning:  35%|███▍      | 1207/3456 [28:40<50:21,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.6666
➡️ Total Profit: ₹21,879.74
➡️ Equity Curve R²: 0.0369
➡️ Monthly Consistency Score: 0.0795

=== [1208/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.89it/s]
Hypertuning:  35%|███▍      | 1208/3456 [28:41<50:35,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3310
➡️ Total Profit: ₹-10,061.62
➡️ Equity Curve R²: 0.2535
➡️ Monthly Consistency Score: -0.0357

=== [1209/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.49it/s]
Hypertuning:  35%|███▍      | 1209/3456 [28:42<51:30,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.2182
➡️ Total Profit: ₹-10,462.27
➡️ Equity Curve R²: 0.6176
➡️ Monthly Consistency Score: -0.0355

=== [1210/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.24it/s]
Hypertuning:  35%|███▌      | 1210/3456 [28:44<50:46,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.4030
➡️ Total Profit: ₹39,639.29
➡️ Equity Curve R²: 0.2575
➡️ Monthly Consistency Score: 0.1694

=== [1211/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.22it/s]
Hypertuning:  35%|███▌      | 1211/3456 [28:45<51:12,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.2791
➡️ Total Profit: ₹12,285.79
➡️ Equity Curve R²: 0.3321
➡️ Monthly Consistency Score: 0.0436

=== [1212/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.26it/s]
Hypertuning:  35%|███▌      | 1212/3456 [28:46<50:19,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.0312
➡️ Total Profit: ₹26,352.83
➡️ Equity Curve R²: 0.5643
➡️ Monthly Consistency Score: 0.0975

=== [1213/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.15it/s]
Hypertuning:  35%|███▌      | 1213/3456 [28:48<51:24,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.2828
➡️ Total Profit: ₹41,504.36
➡️ Equity Curve R²: 0.0987
➡️ Monthly Consistency Score: 0.1732

=== [1214/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.67it/s]
Hypertuning:  35%|███▌      | 1214/3456 [28:49<50:47,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.4565
➡️ Total Profit: ₹69,403.80
➡️ Equity Curve R²: 0.5122
➡️ Monthly Consistency Score: 0.2760

=== [1215/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.94it/s]
Hypertuning:  35%|███▌      | 1215/3456 [28:50<50:06,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.4622
➡️ Total Profit: ₹45,283.30
➡️ Equity Curve R²: 0.1317
➡️ Monthly Consistency Score: 0.1846

=== [1216/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.28it/s]
Hypertuning:  35%|███▌      | 1216/3456 [28:52<50:28,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.8107
➡️ Total Profit: ₹62,769.19
➡️ Equity Curve R²: 0.6055
➡️ Monthly Consistency Score: 0.3004

=== [1217/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.47it/s]
Hypertuning:  35%|███▌      | 1217/3456 [28:53<50:19,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6786
➡️ Total Profit: ₹-47,387.23
➡️ Equity Curve R²: 0.9566
➡️ Monthly Consistency Score: -0.2107

=== [1218/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.87it/s]
Hypertuning:  35%|███▌      | 1218/3456 [28:55<50:49,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2020
➡️ Total Profit: ₹-11,113.07
➡️ Equity Curve R²: 0.8208
➡️ Monthly Consistency Score: -0.0432

=== [1219/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.37it/s]
Hypertuning:  35%|███▌      | 1219/3456 [28:56<51:12,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0781
➡️ Total Profit: ₹-4,057.94
➡️ Equity Curve R²: 0.7171
➡️ Monthly Consistency Score: -0.0159

=== [1220/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.14it/s]
Hypertuning:  35%|███▌      | 1220/3456 [28:57<50:29,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.7939
➡️ Total Profit: ₹23,198.47
➡️ Equity Curve R²: 0.1613
➡️ Monthly Consistency Score: 0.0865

=== [1221/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.91it/s]
Hypertuning:  35%|███▌      | 1221/3456 [28:59<51:19,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.4232
➡️ Total Profit: ₹-14,025.71
➡️ Equity Curve R²: 0.5820
➡️ Monthly Consistency Score: -0.0486

=== [1222/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.62it/s]
Hypertuning:  35%|███▌      | 1222/3456 [29:00<50:44,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.6278
➡️ Total Profit: ₹36,790.29
➡️ Equity Curve R²: 0.5791
➡️ Monthly Consistency Score: 0.1458

=== [1223/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.34it/s]
Hypertuning:  35%|███▌      | 1223/3456 [29:01<50:07,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.3322
➡️ Total Profit: ₹34,922.48
➡️ Equity Curve R²: 0.3191
➡️ Monthly Consistency Score: 0.1273

=== [1224/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.76it/s]
Hypertuning:  35%|███▌      | 1224/3456 [29:03<50:35,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0329
➡️ Total Profit: ₹-1,231.68
➡️ Equity Curve R²: 0.3629
➡️ Monthly Consistency Score: -0.0046

=== [1225/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.20it/s]
Hypertuning:  35%|███▌      | 1225/3456 [29:04<51:30,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.2742
➡️ Total Profit: ₹-14,871.80
➡️ Equity Curve R²: 0.7633
➡️ Monthly Consistency Score: -0.0514

=== [1226/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.78it/s]
Hypertuning:  35%|███▌      | 1226/3456 [29:05<50:54,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.9630
➡️ Total Profit: ₹55,459.29
➡️ Equity Curve R²: 0.2224
➡️ Monthly Consistency Score: 0.2423

=== [1227/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.11it/s]
Hypertuning:  36%|███▌      | 1227/3456 [29:07<51:09,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.1033
➡️ Total Profit: ₹-4,714.22
➡️ Equity Curve R²: 0.7215
➡️ Monthly Consistency Score: -0.0177

=== [1228/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.12it/s]
Hypertuning:  36%|███▌      | 1228/3456 [29:08<50:21,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.1146
➡️ Total Profit: ₹28,484.65
➡️ Equity Curve R²: 0.5630
➡️ Monthly Consistency Score: 0.1039

=== [1229/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.43it/s]
Hypertuning:  36%|███▌      | 1229/3456 [29:10<50:06,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.5180
➡️ Total Profit: ₹45,286.24
➡️ Equity Curve R²: 0.1381
➡️ Monthly Consistency Score: 0.1963

=== [1230/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.26it/s]
Hypertuning:  36%|███▌      | 1230/3456 [29:11<50:32,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.0966
➡️ Total Profit: ₹59,234.71
➡️ Equity Curve R²: 0.2629
➡️ Monthly Consistency Score: 0.2397

=== [1231/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.65it/s]
Hypertuning:  36%|███▌      | 1231/3456 [29:12<50:55,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.5676
➡️ Total Profit: ₹48,546.04
➡️ Equity Curve R²: 0.1630
➡️ Monthly Consistency Score: 0.1962

=== [1232/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.74it/s]
Hypertuning:  36%|███▌      | 1232/3456 [29:14<50:13,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.9401
➡️ Total Profit: ₹64,901.01
➡️ Equity Curve R²: 0.5937
➡️ Monthly Consistency Score: 0.3064

=== [1233/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.43it/s]
Hypertuning:  36%|███▌      | 1233/3456 [29:15<50:17,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.6674
➡️ Total Profit: ₹-44,022.48
➡️ Equity Curve R²: 0.8943
➡️ Monthly Consistency Score: -0.1957

=== [1234/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.86it/s]
Hypertuning:  36%|███▌      | 1234/3456 [29:16<50:33,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0299
➡️ Total Profit: ₹-1,554.83
➡️ Equity Curve R²: 0.6911
➡️ Monthly Consistency Score: -0.0067

=== [1235/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.56it/s]
Hypertuning:  36%|███▌      | 1235/3456 [29:18<50:54,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.2082
➡️ Total Profit: ₹-12,275.33
➡️ Equity Curve R²: 0.7974
➡️ Monthly Consistency Score: -0.0481

=== [1236/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.16it/s]
Hypertuning:  36%|███▌      | 1236/3456 [29:19<50:14,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2371
➡️ Total Profit: ₹9,584.93
➡️ Equity Curve R²: 0.1552
➡️ Monthly Consistency Score: 0.0355

=== [1237/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.32it/s]
Hypertuning:  36%|███▌      | 1237/3456 [29:21<51:10,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.4818
➡️ Total Profit: ₹-15,740.76
➡️ Equity Curve R²: 0.6174
➡️ Monthly Consistency Score: -0.0572

=== [1238/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.00it/s]
Hypertuning:  36%|███▌      | 1238/3456 [29:22<50:31,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.6052
➡️ Total Profit: ₹33,050.17
➡️ Equity Curve R²: 0.4826
➡️ Monthly Consistency Score: 0.1349

=== [1239/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.95it/s]
Hypertuning:  36%|███▌      | 1239/3456 [29:23<49:39,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.8827
➡️ Total Profit: ₹46,288.37
➡️ Equity Curve R²: 0.7181
➡️ Monthly Consistency Score: 0.1694

=== [1240/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.80it/s]
Hypertuning:  36%|███▌      | 1240/3456 [29:25<50:02,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6278
➡️ Total Profit: ₹16,417.49
➡️ Equity Curve R²: 0.0016
➡️ Monthly Consistency Score: 0.0583

=== [1241/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.97it/s]
Hypertuning:  36%|███▌      | 1241/3456 [29:26<51:04,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.3206
➡️ Total Profit: ₹-17,389.92
➡️ Equity Curve R²: 0.8095
➡️ Monthly Consistency Score: -0.0580

=== [1242/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.60it/s]
Hypertuning:  36%|███▌      | 1242/3456 [29:27<50:34,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.8916
➡️ Total Profit: ₹57,719.30
➡️ Equity Curve R²: 0.2401
➡️ Monthly Consistency Score: 0.2530

=== [1243/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.27it/s]
Hypertuning:  36%|███▌      | 1243/3456 [29:29<50:58,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.6684
➡️ Total Profit: ₹24,979.33
➡️ Equity Curve R²: 0.0031
➡️ Monthly Consistency Score: 0.0995

=== [1244/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.63it/s]
Hypertuning:  36%|███▌      | 1244/3456 [29:30<50:21,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.2813
➡️ Total Profit: ₹32,744.65
➡️ Equity Curve R²: 0.5572
➡️ Monthly Consistency Score: 0.1177

=== [1245/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.84it/s]
Hypertuning:  36%|███▌      | 1245/3456 [29:31<50:01,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.0567
➡️ Total Profit: ₹41,509.06
➡️ Equity Curve R²: 0.0063
➡️ Monthly Consistency Score: 0.1696

=== [1246/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.02it/s]
Hypertuning:  36%|███▌      | 1246/3456 [29:33<50:18,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.7641
➡️ Total Profit: ₹50,502.77
➡️ Equity Curve R²: 0.0332
➡️ Monthly Consistency Score: 0.2023

=== [1247/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 109.68it/s]
Hypertuning:  36%|███▌      | 1247/3456 [29:34<50:56,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.4128
➡️ Total Profit: ₹50,177.41
➡️ Equity Curve R²: 0.0317
➡️ Monthly Consistency Score: 0.1997

=== [1248/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.66it/s]
Hypertuning:  36%|███▌      | 1248/3456 [29:36<50:11,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 4.1987
➡️ Total Profit: ₹69,161.02
➡️ Equity Curve R²: 0.5550
➡️ Monthly Consistency Score: 0.3211

=== [1249/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.64it/s]
Hypertuning:  36%|███▌      | 1249/3456 [29:37<49:47,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6820
➡️ Total Profit: ₹-45,976.00
➡️ Equity Curve R²: 0.9444
➡️ Monthly Consistency Score: -0.1911

=== [1250/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.35it/s]
Hypertuning:  36%|███▌      | 1250/3456 [29:38<50:12,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3295
➡️ Total Profit: ₹-19,485.15
➡️ Equity Curve R²: 0.8832
➡️ Monthly Consistency Score: -0.0771

=== [1251/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.69it/s]
Hypertuning:  36%|███▌      | 1251/3456 [29:40<49:23,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.0078
➡️ Total Profit: ₹-410.26
➡️ Equity Curve R²: 0.5745
➡️ Monthly Consistency Score: -0.0014

=== [1252/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.59it/s]
Hypertuning:  36%|███▌      | 1252/3456 [29:41<49:34,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.1268
➡️ Total Profit: ₹44,751.83
➡️ Equity Curve R²: 0.6201
➡️ Monthly Consistency Score: 0.1524

=== [1253/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.62it/s]
Hypertuning:  36%|███▋      | 1253/3456 [29:42<49:14,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.3730
➡️ Total Profit: ₹36,172.41
➡️ Equity Curve R²: 0.6477
➡️ Monthly Consistency Score: 0.1227

=== [1254/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.43it/s]
Hypertuning:  36%|███▋      | 1254/3456 [29:44<49:36,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.2892
➡️ Total Profit: ₹27,677.77
➡️ Equity Curve R²: 0.4448
➡️ Monthly Consistency Score: 0.1021

=== [1255/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.93it/s]
Hypertuning:  36%|███▋      | 1255/3456 [29:45<50:07,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.3796
➡️ Total Profit: ₹13,729.63
➡️ Equity Curve R²: 0.0055
➡️ Monthly Consistency Score: 0.0478

=== [1256/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.73it/s]
Hypertuning:  36%|███▋      | 1256/3456 [29:46<49:26,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.2040
➡️ Total Profit: ₹39,550.57
➡️ Equity Curve R²: 0.6849
➡️ Monthly Consistency Score: 0.1650

=== [1257/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.26it/s]
Hypertuning:  36%|███▋      | 1257/3456 [29:48<49:13,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.3888
➡️ Total Profit: ₹-25,522.45
➡️ Equity Curve R²: 0.8529
➡️ Monthly Consistency Score: -0.0836

=== [1258/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.63it/s]
Hypertuning:  36%|███▋      | 1258/3456 [29:49<49:40,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5872
➡️ Total Profit: ₹18,270.49
➡️ Equity Curve R²: 0.0131
➡️ Monthly Consistency Score: 0.0646

=== [1259/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.32it/s]
Hypertuning:  36%|███▋      | 1259/3456 [29:50<48:57,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.9422
➡️ Total Profit: ₹35,105.79
➡️ Equity Curve R²: 0.0001
➡️ Monthly Consistency Score: 0.1433

=== [1260/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.98it/s]
Hypertuning:  36%|███▋      | 1260/3456 [29:52<49:29,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.9774
➡️ Total Profit: ₹52,878.47
➡️ Equity Curve R²: 0.2178
➡️ Monthly Consistency Score: 0.2067

=== [1261/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.03it/s]
Hypertuning:  36%|███▋      | 1261/3456 [29:53<49:05,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.3906
➡️ Total Profit: ₹11,896.71
➡️ Equity Curve R²: 0.0708
➡️ Monthly Consistency Score: 0.0445

=== [1262/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.27it/s]
Hypertuning:  37%|███▋      | 1262/3456 [29:54<49:41,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.4946
➡️ Total Profit: ₹50,796.55
➡️ Equity Curve R²: 0.0347
➡️ Monthly Consistency Score: 0.2195

=== [1263/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.13it/s]
Hypertuning:  37%|███▋      | 1263/3456 [29:56<50:05,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.5662
➡️ Total Profit: ₹27,443.91
➡️ Equity Curve R²: 0.3986
➡️ Monthly Consistency Score: 0.1019

=== [1264/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.27it/s]
Hypertuning:  37%|███▋      | 1264/3456 [29:57<49:26,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 6.0203
➡️ Total Profit: ₹94,512.96
➡️ Equity Curve R²: 0.8222
➡️ Monthly Consistency Score: 0.4856

=== [1265/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.22it/s]
Hypertuning:  37%|███▋      | 1265/3456 [29:58<49:20,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6409
➡️ Total Profit: ₹-39,394.73
➡️ Equity Curve R²: 0.9368
➡️ Monthly Consistency Score: -0.1708

=== [1266/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.48it/s]
Hypertuning:  37%|███▋      | 1266/3456 [30:00<49:43,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2756
➡️ Total Profit: ₹-15,912.55
➡️ Equity Curve R²: 0.8790
➡️ Monthly Consistency Score: -0.0591

=== [1267/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.98it/s]
Hypertuning:  37%|███▋      | 1267/3456 [30:01<48:57,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.0226
➡️ Total Profit: ₹1,223.73
➡️ Equity Curve R²: 0.5860
➡️ Monthly Consistency Score: 0.0045

=== [1268/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.30it/s]
Hypertuning:  37%|███▋      | 1268/3456 [30:03<49:16,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.0732
➡️ Total Profit: ₹29,100.87
➡️ Equity Curve R²: 0.1408
➡️ Monthly Consistency Score: 0.1024

=== [1269/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.60it/s]
Hypertuning:  37%|███▋      | 1269/3456 [30:04<50:26,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.2121
➡️ Total Profit: ₹31,934.54
➡️ Equity Curve R²: 0.6414
➡️ Monthly Consistency Score: 0.1096

=== [1270/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.69it/s]
Hypertuning:  37%|███▋      | 1270/3456 [30:05<49:57,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.8483
➡️ Total Profit: ₹39,681.45
➡️ Equity Curve R²: 0.7156
➡️ Monthly Consistency Score: 0.1476

=== [1271/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.98it/s]
Hypertuning:  37%|███▋      | 1271/3456 [30:07<49:01,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1997
➡️ Total Profit: ₹7,249.63
➡️ Equity Curve R²: 0.2319
➡️ Monthly Consistency Score: 0.0265

=== [1272/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.98it/s]
Hypertuning:  37%|███▋      | 1272/3456 [30:08<49:07,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.7082
➡️ Total Profit: ₹17,028.61
➡️ Equity Curve R²: 0.1545
➡️ Monthly Consistency Score: 0.0710

=== [1273/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.33it/s]
Hypertuning:  37%|███▋      | 1273/3456 [30:09<48:51,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.3925
➡️ Total Profit: ₹-25,521.51
➡️ Equity Curve R²: 0.8492
➡️ Monthly Consistency Score: -0.0848

=== [1274/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.94it/s]
Hypertuning:  37%|███▋      | 1274/3456 [30:11<49:09,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6235
➡️ Total Profit: ₹19,399.57
➡️ Equity Curve R²: 0.0171
➡️ Monthly Consistency Score: 0.0688

=== [1275/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.93it/s]
Hypertuning:  37%|███▋      | 1275/3456 [30:12<49:40,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.1498
➡️ Total Profit: ₹6,697.15
➡️ Equity Curve R²: 0.4606
➡️ Monthly Consistency Score: 0.0281

=== [1276/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.90it/s]
Hypertuning:  37%|███▋      | 1276/3456 [30:13<49:09,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.9774
➡️ Total Profit: ₹52,878.47
➡️ Equity Curve R²: 0.2178
➡️ Monthly Consistency Score: 0.2067

=== [1277/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.41it/s]
Hypertuning:  37%|███▋      | 1277/3456 [30:15<48:58,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.8017
➡️ Total Profit: ₹23,235.77
➡️ Equity Curve R²: 0.0044
➡️ Monthly Consistency Score: 0.0905

=== [1278/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.41it/s]
Hypertuning:  37%|███▋      | 1278/3456 [30:16<49:15,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.5767
➡️ Total Profit: ₹72,798.40
➡️ Equity Curve R²: 0.5379
➡️ Monthly Consistency Score: 0.2866

=== [1279/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 111.41it/s]
Hypertuning:  37%|███▋      | 1279/3456 [30:18<49:44,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.9636
➡️ Total Profit: ₹38,852.54
➡️ Equity Curve R²: 0.0113
➡️ Monthly Consistency Score: 0.1517

=== [1280/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.86it/s]
Hypertuning:  37%|███▋      | 1280/3456 [30:19<48:55,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 5.2469
➡️ Total Profit: ₹67,036.47
➡️ Equity Curve R²: 0.6411
➡️ Monthly Consistency Score: 0.3290

=== [1281/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.86it/s]
Hypertuning:  37%|███▋      | 1281/3456 [30:20<49:54,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.6322
➡️ Total Profit: ₹-41,566.47
➡️ Equity Curve R²: 0.9168
➡️ Monthly Consistency Score: -0.1725

=== [1282/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.11it/s]
Hypertuning:  37%|███▋      | 1282/3456 [30:22<49:11,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3596
➡️ Total Profit: ₹-24,514.52
➡️ Equity Curve R²: 0.8499
➡️ Monthly Consistency Score: -0.1025

=== [1283/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.69it/s]
Hypertuning:  37%|███▋      | 1283/3456 [30:23<48:26,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.2209
➡️ Total Profit: ₹-12,667.65
➡️ Equity Curve R²: 0.7731
➡️ Monthly Consistency Score: -0.0471

=== [1284/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.35it/s]
Hypertuning:  37%|███▋      | 1284/3456 [30:24<48:53,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.9947
➡️ Total Profit: ₹26,970.77
➡️ Equity Curve R²: 0.1591
➡️ Monthly Consistency Score: 0.0977

=== [1285/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.09it/s]
Hypertuning:  37%|███▋      | 1285/3456 [30:26<48:33,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.8949
➡️ Total Profit: ₹20,758.17
➡️ Equity Curve R²: 0.5355
➡️ Monthly Consistency Score: 0.0735

=== [1286/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.58it/s]
Hypertuning:  37%|███▋      | 1286/3456 [30:27<48:59,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4547
➡️ Total Profit: ₹12,366.73
➡️ Equity Curve R²: 0.1059
➡️ Monthly Consistency Score: 0.0473

=== [1287/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.21it/s]
Hypertuning:  37%|███▋      | 1287/3456 [30:28<48:21,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.2854
➡️ Total Profit: ₹8,872.33
➡️ Equity Curve R²: 0.0229
➡️ Monthly Consistency Score: 0.0342

=== [1288/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.05it/s]
Hypertuning:  37%|███▋      | 1288/3456 [30:30<48:52,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.0174
➡️ Total Profit: ₹36,200.43
➡️ Equity Curve R²: 0.6143
➡️ Monthly Consistency Score: 0.1499

=== [1289/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.35it/s]
Hypertuning:  37%|███▋      | 1289/3456 [30:31<48:28,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.4432
➡️ Total Profit: ₹-29,933.86
➡️ Equity Curve R²: 0.8953
➡️ Monthly Consistency Score: -0.0986

=== [1290/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.92it/s]
Hypertuning:  37%|███▋      | 1290/3456 [30:32<48:58,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.9523
➡️ Total Profit: ₹30,695.89
➡️ Equity Curve R²: 0.0430
➡️ Monthly Consistency Score: 0.1061

=== [1291/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.17it/s]
Hypertuning:  37%|███▋      | 1291/3456 [30:34<49:22,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.7385
➡️ Total Profit: ₹60,610.71
➡️ Equity Curve R²: 0.5748
➡️ Monthly Consistency Score: 0.2388

=== [1292/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.15it/s]
Hypertuning:  37%|███▋      | 1292/3456 [30:35<48:41,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.5697
➡️ Total Profit: ₹53,842.11
➡️ Equity Curve R²: 0.0210
➡️ Monthly Consistency Score: 0.1968

=== [1293/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.95it/s]
Hypertuning:  37%|███▋      | 1293/3456 [30:36<48:30,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.1809
➡️ Total Profit: ₹28,274.83
➡️ Equity Curve R²: 0.0670
➡️ Monthly Consistency Score: 0.1100

=== [1294/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.75it/s]
Hypertuning:  37%|███▋      | 1294/3456 [30:38<48:51,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.6494
➡️ Total Profit: ₹54,189.31
➡️ Equity Curve R²: 0.0458
➡️ Monthly Consistency Score: 0.2211

=== [1295/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.91it/s]
Hypertuning:  37%|███▋      | 1295/3456 [30:39<49:14,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.9199
➡️ Total Profit: ₹35,592.54
➡️ Equity Curve R²: 0.0068
➡️ Monthly Consistency Score: 0.1436

=== [1296/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.72it/s]
Hypertuning:  38%|███▊      | 1296/3456 [30:41<49:16,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 4.2701
➡️ Total Profit: ₹67,036.47
➡️ Equity Curve R²: 0.5991
➡️ Monthly Consistency Score: 0.3463

=== [1297/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.18it/s]
Hypertuning:  38%|███▊      | 1297/3456 [30:42<50:12,  1.40s/it]

➡️ Profit-to-Drawdown Ratio: -0.6695
➡️ Total Profit: ₹-45,976.94
➡️ Equity Curve R²: 0.9436
➡️ Monthly Consistency Score: -0.1900

=== [1298/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.75it/s]
Hypertuning:  38%|███▊      | 1298/3456 [30:43<49:16,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2729
➡️ Total Profit: ₹-14,877.91
➡️ Equity Curve R²: 0.8578
➡️ Monthly Consistency Score: -0.0593

=== [1299/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.03it/s]
Hypertuning:  38%|███▊      | 1299/3456 [30:45<48:25,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.0556
➡️ Total Profit: ₹2,847.00
➡️ Equity Curve R²: 0.5076
➡️ Monthly Consistency Score: 0.0099

=== [1300/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.99it/s]
Hypertuning:  38%|███▊      | 1300/3456 [30:46<48:35,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.3995
➡️ Total Profit: ₹50,488.20
➡️ Equity Curve R²: 0.7593
➡️ Monthly Consistency Score: 0.1741

=== [1301/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.17it/s]
Hypertuning:  38%|███▊      | 1301/3456 [30:47<48:22,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.3969
➡️ Total Profit: ₹36,801.94
➡️ Equity Curve R²: 0.6476
➡️ Monthly Consistency Score: 0.1247

=== [1302/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.48it/s]
Hypertuning:  38%|███▊      | 1302/3456 [30:49<48:40,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.3418
➡️ Total Profit: ₹28,806.85
➡️ Equity Curve R²: 0.4418
➡️ Monthly Consistency Score: 0.1060

=== [1303/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 130.25it/s]
Hypertuning:  38%|███▊      | 1303/3456 [30:50<47:53,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 0.3796
➡️ Total Profit: ₹13,729.63
➡️ Equity Curve R²: 0.0055
➡️ Monthly Consistency Score: 0.0478

=== [1304/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.75it/s]
Hypertuning:  38%|███▊      | 1304/3456 [30:51<48:10,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.4577
➡️ Total Profit: ₹26,157.77
➡️ Equity Curve R²: 0.5613
➡️ Monthly Consistency Score: 0.1069

=== [1305/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.48it/s]
Hypertuning:  38%|███▊      | 1305/3456 [30:53<47:59,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.3888
➡️ Total Profit: ₹-25,522.45
➡️ Equity Curve R²: 0.8529
➡️ Monthly Consistency Score: -0.0836

=== [1306/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.01it/s]
Hypertuning:  38%|███▊      | 1306/3456 [30:54<48:31,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6235
➡️ Total Profit: ₹19,399.57
➡️ Equity Curve R²: 0.0171
➡️ Monthly Consistency Score: 0.0688

=== [1307/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.76it/s]
Hypertuning:  38%|███▊      | 1307/3456 [30:55<48:50,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.9422
➡️ Total Profit: ₹35,105.79
➡️ Equity Curve R²: 0.0001
➡️ Monthly Consistency Score: 0.1433

=== [1308/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.27it/s]
Hypertuning:  38%|███▊      | 1308/3456 [30:57<48:08,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 3.0257
➡️ Total Profit: ₹70,874.84
➡️ Equity Curve R²: 0.6976
➡️ Monthly Consistency Score: 0.2636

=== [1309/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.38it/s]
Hypertuning:  38%|███▊      | 1309/3456 [30:58<47:45,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 0.4320
➡️ Total Profit: ₹13,155.77
➡️ Equity Curve R²: 0.0705
➡️ Monthly Consistency Score: 0.0491

=== [1310/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.67it/s]
Hypertuning:  38%|███▊      | 1310/3456 [30:59<48:13,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.6567
➡️ Total Profit: ₹75,058.40
➡️ Equity Curve R²: 0.5228
➡️ Monthly Consistency Score: 0.2926

=== [1311/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.39it/s]
Hypertuning:  38%|███▊      | 1311/3456 [31:01<48:35,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5662
➡️ Total Profit: ₹27,443.91
➡️ Equity Curve R²: 0.3986
➡️ Monthly Consistency Score: 0.1019

=== [1312/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.33it/s]
Hypertuning:  38%|███▊      | 1312/3456 [31:02<47:55,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 5.8845
➡️ Total Profit: ₹92,381.14
➡️ Equity Curve R²: 0.8309
➡️ Monthly Consistency Score: 0.4740

=== [1313/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.63it/s]
Hypertuning:  38%|███▊      | 1313/3456 [31:04<48:55,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.5720
➡️ Total Profit: ₹-35,198.82
➡️ Equity Curve R²: 0.9147
➡️ Monthly Consistency Score: -0.1543

=== [1314/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.16it/s]
Hypertuning:  38%|███▊      | 1314/3456 [31:05<48:25,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2718
➡️ Total Profit: ₹-16,523.39
➡️ Equity Curve R²: 0.8770
➡️ Monthly Consistency Score: -0.0598

=== [1315/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.76it/s]
Hypertuning:  38%|███▊      | 1315/3456 [31:06<48:51,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0072
➡️ Total Profit: ₹-410.38
➡️ Equity Curve R²: 0.6376
➡️ Monthly Consistency Score: -0.0015

=== [1316/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.91it/s]
Hypertuning:  38%|███▊      | 1316/3456 [31:08<48:07,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.6972
➡️ Total Profit: ₹38,449.05
➡️ Equity Curve R²: 0.4494
➡️ Monthly Consistency Score: 0.1359

=== [1317/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.36it/s]
Hypertuning:  38%|███▊      | 1317/3456 [31:09<47:53,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.8314
➡️ Total Profit: ₹18,237.23
➡️ Equity Curve R²: 0.4654
➡️ Monthly Consistency Score: 0.0642

=== [1318/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.57it/s]
Hypertuning:  38%|███▊      | 1318/3456 [31:10<48:17,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.3945
➡️ Total Profit: ₹29,939.61
➡️ Equity Curve R²: 0.3835
➡️ Monthly Consistency Score: 0.1164

=== [1319/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.47it/s]
Hypertuning:  38%|███▊      | 1319/3456 [31:12<47:30,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 0.8629
➡️ Total Profit: ₹28,398.26
➡️ Equity Curve R²: 0.0600
➡️ Monthly Consistency Score: 0.1039

=== [1320/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.60it/s]
Hypertuning:  38%|███▊      | 1320/3456 [31:13<47:50,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.8600
➡️ Total Profit: ₹20,679.45
➡️ Equity Curve R²: 0.1163
➡️ Monthly Consistency Score: 0.0871

=== [1321/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.30it/s]
Hypertuning:  38%|███▊      | 1321/3456 [31:14<47:41,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.4167
➡️ Total Profit: ₹-28,671.98
➡️ Equity Curve R²: 0.8900
➡️ Monthly Consistency Score: -0.0965

=== [1322/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.94it/s]
Hypertuning:  38%|███▊      | 1322/3456 [31:16<48:07,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.8076
➡️ Total Profit: ₹26,179.57
➡️ Equity Curve R²: 0.0941
➡️ Monthly Consistency Score: 0.0949

=== [1323/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.60it/s]
Hypertuning:  38%|███▊      | 1323/3456 [31:17<47:23,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 0.3707
➡️ Total Profit: ₹17,179.90
➡️ Equity Curve R²: 0.2695
➡️ Monthly Consistency Score: 0.0702

=== [1324/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.56it/s]
Hypertuning:  38%|███▊      | 1324/3456 [31:18<47:41,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 3.1167
➡️ Total Profit: ₹73,006.66
➡️ Equity Curve R²: 0.7053
➡️ Monthly Consistency Score: 0.2757

=== [1325/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.99it/s]
Hypertuning:  38%|███▊      | 1325/3456 [31:20<48:53,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.0719
➡️ Total Profit: ₹27,015.77
➡️ Equity Curve R²: 0.0436
➡️ Monthly Consistency Score: 0.1054

=== [1326/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.84it/s]
Hypertuning:  38%|███▊      | 1326/3456 [31:21<48:09,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.4465
➡️ Total Profit: ₹50,796.55
➡️ Equity Curve R²: 0.0174
➡️ Monthly Consistency Score: 0.2162

=== [1327/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 110.90it/s]
Hypertuning:  38%|███▊      | 1327/3456 [31:22<48:29,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.9636
➡️ Total Profit: ₹38,852.54
➡️ Equity Curve R²: 0.0113
➡️ Monthly Consistency Score: 0.1517

=== [1328/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.26it/s]
Hypertuning:  38%|███▊      | 1328/3456 [31:24<47:43,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 5.8845
➡️ Total Profit: ₹92,381.14
➡️ Equity Curve R²: 0.8309
➡️ Monthly Consistency Score: 0.4740

=== [1329/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 130.09it/s]
Hypertuning:  38%|███▊      | 1329/3456 [31:25<47:37,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.6629
➡️ Total Profit: ₹-41,914.73
➡️ Equity Curve R²: 0.9007
➡️ Monthly Consistency Score: -0.1820

=== [1330/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.73it/s]
Hypertuning:  38%|███▊      | 1330/3456 [31:26<48:02,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0415
➡️ Total Profit: ₹-2,356.23
➡️ Equity Curve R²: 0.7342
➡️ Monthly Consistency Score: -0.0095

=== [1331/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.41it/s]
Hypertuning:  39%|███▊      | 1331/3456 [31:28<48:23,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1190
➡️ Total Profit: ₹-5,365.02
➡️ Equity Curve R²: 0.6049
➡️ Monthly Consistency Score: -0.0203

=== [1332/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.20it/s]
Hypertuning:  39%|███▊      | 1332/3456 [31:29<47:44,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.5519
➡️ Total Profit: ₹35,479.85
➡️ Equity Curve R²: 0.3371
➡️ Monthly Consistency Score: 0.1305

=== [1333/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.51it/s]
Hypertuning:  39%|███▊      | 1333/3456 [31:30<47:33,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.7666
➡️ Total Profit: ₹17,781.24
➡️ Equity Curve R²: 0.4781
➡️ Monthly Consistency Score: 0.0672

=== [1334/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.22it/s]
Hypertuning:  39%|███▊      | 1334/3456 [31:32<48:06,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.2565
➡️ Total Profit: ₹26,975.93
➡️ Equity Curve R²: 0.2015
➡️ Monthly Consistency Score: 0.1039

=== [1335/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.13it/s]
Hypertuning:  39%|███▊      | 1335/3456 [31:33<47:20,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.6901
➡️ Total Profit: ₹20,329.63
➡️ Equity Curve R²: 0.0049
➡️ Monthly Consistency Score: 0.0828

=== [1336/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.79it/s]
Hypertuning:  39%|███▊      | 1336/3456 [31:35<47:39,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.0861
➡️ Total Profit: ₹26,458.47
➡️ Equity Curve R²: 0.1534
➡️ Monthly Consistency Score: 0.1102

=== [1337/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.75it/s]
Hypertuning:  39%|███▊      | 1337/3456 [31:36<47:18,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.4168
➡️ Total Profit: ₹-28,674.80
➡️ Equity Curve R²: 0.8904
➡️ Monthly Consistency Score: -0.0944

=== [1338/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.12it/s]
Hypertuning:  39%|███▊      | 1338/3456 [31:37<47:40,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.0223
➡️ Total Profit: ₹32,954.05
➡️ Equity Curve R²: 0.0143
➡️ Monthly Consistency Score: 0.1187

=== [1339/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.87it/s]
Hypertuning:  39%|███▊      | 1339/3456 [31:39<46:57,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: -0.1907
➡️ Total Profit: ₹-7,971.48
➡️ Equity Curve R²: 0.5159
➡️ Monthly Consistency Score: -0.0333

=== [1340/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.72it/s]
Hypertuning:  39%|███▉      | 1340/3456 [31:40<47:19,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 3.2985
➡️ Total Profit: ₹77,266.66
➡️ Equity Curve R²: 0.7326
➡️ Monthly Consistency Score: 0.2994

=== [1341/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.69it/s]
Hypertuning:  39%|███▉      | 1341/3456 [31:41<48:12,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.3045
➡️ Total Profit: ₹32,055.77
➡️ Equity Curve R²: 0.0717
➡️ Monthly Consistency Score: 0.1263

=== [1342/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.99it/s]
Hypertuning:  39%|███▉      | 1342/3456 [31:43<47:46,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.5368
➡️ Total Profit: ₹71,671.16
➡️ Equity Curve R²: 0.2433
➡️ Monthly Consistency Score: 0.2992

=== [1343/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.53it/s]
Hypertuning:  39%|███▉      | 1343/3456 [31:44<48:22,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1282
➡️ Total Profit: ₹43,743.91
➡️ Equity Curve R²: 0.0001
➡️ Monthly Consistency Score: 0.1770

=== [1344/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 130.27it/s]
Hypertuning:  39%|███▉      | 1344/3456 [31:45<47:39,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 4.8232
➡️ Total Profit: ₹69,164.66
➡️ Equity Curve R²: 0.5805
➡️ Monthly Consistency Score: 0.3462

=== [1345/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.76it/s]
Hypertuning:  39%|███▉      | 1345/3456 [31:47<47:20,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.4833
➡️ Total Profit: ₹-23,922.81
➡️ Equity Curve R²: 0.9053
➡️ Monthly Consistency Score: -0.1076

=== [1346/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.21it/s]
Hypertuning:  39%|███▉      | 1346/3456 [31:48<47:39,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3030
➡️ Total Profit: ₹-17,655.67
➡️ Equity Curve R²: 0.8871
➡️ Monthly Consistency Score: -0.0705

=== [1347/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.61it/s]
Hypertuning:  39%|███▉      | 1347/3456 [31:49<46:51,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 0.2276
➡️ Total Profit: ₹12,245.40
➡️ Equity Curve R²: 0.4603
➡️ Monthly Consistency Score: 0.0444

=== [1348/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.22it/s]
Hypertuning:  39%|███▉      | 1348/3456 [31:51<47:04,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.1989
➡️ Total Profit: ₹46,146.43
➡️ Equity Curve R²: 0.3751
➡️ Monthly Consistency Score: 0.1703

=== [1349/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.29it/s]
Hypertuning:  39%|███▉      | 1349/3456 [31:52<46:53,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.0564
➡️ Total Profit: ₹-2,036.00
➡️ Equity Curve R²: 0.5069
➡️ Monthly Consistency Score: -0.0079

=== [1350/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.79it/s]
Hypertuning:  39%|███▉      | 1350/3456 [31:53<47:16,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2972
➡️ Total Profit: ₹-16,318.08
➡️ Equity Curve R²: 0.7100
➡️ Monthly Consistency Score: -0.0594

=== [1351/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.43it/s]
Hypertuning:  39%|███▉      | 1351/3456 [31:55<46:48,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 0.2315
➡️ Total Profit: ₹7,254.37
➡️ Equity Curve R²: 0.2156
➡️ Monthly Consistency Score: 0.0289

=== [1352/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.03it/s]
Hypertuning:  39%|███▉      | 1352/3456 [31:56<47:16,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6816
➡️ Total Profit: ₹23,424.35
➡️ Equity Curve R²: 0.0013
➡️ Monthly Consistency Score: 0.0880

=== [1353/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.63it/s]
Hypertuning:  39%|███▉      | 1353/3456 [31:58<48:06,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2559
➡️ Total Profit: ₹-12,909.28
➡️ Equity Curve R²: 0.7928
➡️ Monthly Consistency Score: -0.0442

=== [1354/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.60it/s]
Hypertuning:  39%|███▉      | 1354/3456 [31:59<47:40,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0030
➡️ Total Profit: ₹187.13
➡️ Equity Curve R²: 0.4472
➡️ Monthly Consistency Score: 0.0006

=== [1355/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.61it/s]
Hypertuning:  39%|███▉      | 1355/3456 [32:00<48:03,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.7149
➡️ Total Profit: ₹75,628.54
➡️ Equity Curve R²: 0.4080
➡️ Monthly Consistency Score: 0.3148

=== [1356/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.20it/s]
Hypertuning:  39%|███▉      | 1356/3456 [32:02<47:21,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.6425
➡️ Total Profit: ₹51,229.47
➡️ Equity Curve R²: 0.0678
➡️ Monthly Consistency Score: 0.1875

=== [1357/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.80it/s]
Hypertuning:  39%|███▉      | 1357/3456 [32:03<47:04,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.5654
➡️ Total Profit: ₹21,138.54
➡️ Equity Curve R²: 0.0289
➡️ Monthly Consistency Score: 0.0832

=== [1358/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.81it/s]
Hypertuning:  39%|███▉      | 1358/3456 [32:04<47:56,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.6975
➡️ Total Profit: ₹38,891.47
➡️ Equity Curve R²: 0.2787
➡️ Monthly Consistency Score: 0.1441

=== [1359/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.60it/s]
Hypertuning:  39%|███▉      | 1359/3456 [32:06<48:13,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.8379
➡️ Total Profit: ₹32,332.54
➡️ Equity Curve R²: 0.1968
➡️ Monthly Consistency Score: 0.1176

=== [1360/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.58it/s]
Hypertuning:  39%|███▉      | 1360/3456 [32:07<47:25,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 9.4762
➡️ Total Profit: ₹100,904.78
➡️ Equity Curve R²: 0.9090
➡️ Monthly Consistency Score: 0.4929

=== [1361/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.77it/s]
Hypertuning:  39%|███▉      | 1361/3456 [32:08<47:23,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4468
➡️ Total Profit: ₹-20,492.01
➡️ Equity Curve R²: 0.8873
➡️ Monthly Consistency Score: -0.0951

=== [1362/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.00it/s]
Hypertuning:  39%|███▉      | 1362/3456 [32:10<48:03,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.1950
➡️ Total Profit: ₹-9,839.35
➡️ Equity Curve R²: 0.8495
➡️ Monthly Consistency Score: -0.0436

=== [1363/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.89it/s]
Hypertuning:  39%|███▉      | 1363/3456 [32:11<47:08,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2061
➡️ Total Profit: ₹11,006.71
➡️ Equity Curve R²: 0.4754
➡️ Monthly Consistency Score: 0.0408

=== [1364/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.84it/s]
Hypertuning:  39%|███▉      | 1364/3456 [32:12<47:16,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.8293
➡️ Total Profit: ₹53,923.66
➡️ Equity Curve R²: 0.6197
➡️ Monthly Consistency Score: 0.1991

=== [1365/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.95it/s]
Hypertuning:  39%|███▉      | 1365/3456 [32:14<47:01,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.4181
➡️ Total Profit: ₹-15,094.81
➡️ Equity Curve R²: 0.5918
➡️ Monthly Consistency Score: -0.0587

=== [1366/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.42it/s]
Hypertuning:  40%|███▉      | 1366/3456 [32:15<47:19,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3452
➡️ Total Profit: ₹-21,538.32
➡️ Equity Curve R²: 0.8328
➡️ Monthly Consistency Score: -0.0847

=== [1367/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.19it/s]
Hypertuning:  40%|███▉      | 1367/3456 [32:17<47:38,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.4326
➡️ Total Profit: ₹12,145.74
➡️ Equity Curve R²: 0.0775
➡️ Monthly Consistency Score: 0.0497

=== [1368/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.63it/s]
Hypertuning:  40%|███▉      | 1368/3456 [32:18<47:02,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3455
➡️ Total Profit: ₹14,291.55
➡️ Equity Curve R²: 0.0800
➡️ Monthly Consistency Score: 0.0553

=== [1369/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.16it/s]
Hypertuning:  40%|███▉      | 1369/3456 [32:19<46:47,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.2808
➡️ Total Profit: ₹-14,168.34
➡️ Equity Curve R²: 0.7950
➡️ Monthly Consistency Score: -0.0486

=== [1370/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 110.17it/s]
Hypertuning:  40%|███▉      | 1370/3456 [32:21<47:38,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.5843
➡️ Total Profit: ₹26,352.53
➡️ Equity Curve R²: 0.0124
➡️ Monthly Consistency Score: 0.0867

=== [1371/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.91it/s]
Hypertuning:  40%|███▉      | 1371/3456 [32:22<46:58,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 4.2118
➡️ Total Profit: ₹78,885.80
➡️ Equity Curve R²: 0.4834
➡️ Monthly Consistency Score: 0.3258

=== [1372/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.23it/s]
Hypertuning:  40%|███▉      | 1372/3456 [32:23<47:13,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.8361
➡️ Total Profit: ₹53,357.65
➡️ Equity Curve R²: 0.1186
➡️ Monthly Consistency Score: 0.1965

=== [1373/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.12it/s]
Hypertuning:  40%|███▉      | 1373/3456 [32:25<46:55,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6265
➡️ Total Profit: ₹23,028.07
➡️ Equity Curve R²: 0.0313
➡️ Monthly Consistency Score: 0.0906

=== [1374/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.72it/s]
Hypertuning:  40%|███▉      | 1374/3456 [32:26<47:10,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.7424
➡️ Total Profit: ₹63,144.12
➡️ Equity Curve R²: 0.0214
➡️ Monthly Consistency Score: 0.2231

=== [1375/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 108.71it/s]
Hypertuning:  40%|███▉      | 1375/3456 [32:27<47:31,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.0033
➡️ Total Profit: ₹55,335.28
➡️ Equity Curve R²: 0.2592
➡️ Monthly Consistency Score: 0.1913

=== [1376/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.54it/s]
Hypertuning:  40%|███▉      | 1376/3456 [32:29<46:47,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 4.2111
➡️ Total Profit: ₹62,780.11
➡️ Equity Curve R²: 0.6799
➡️ Monthly Consistency Score: 0.2787

=== [1377/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.46it/s]
Hypertuning:  40%|███▉      | 1377/3456 [32:30<47:52,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.4886
➡️ Total Profit: ₹-23,641.54
➡️ Equity Curve R²: 0.8932
➡️ Monthly Consistency Score: -0.1048

=== [1378/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.38it/s]
Hypertuning:  40%|███▉      | 1378/3456 [32:32<47:22,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3901
➡️ Total Profit: ₹-20,184.91
➡️ Equity Curve R²: 0.8957
➡️ Monthly Consistency Score: -0.0906

=== [1379/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.18it/s]
Hypertuning:  40%|███▉      | 1379/3456 [32:33<46:47,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.0365
➡️ Total Profit: ₹2,006.71
➡️ Equity Curve R²: 0.6361
➡️ Monthly Consistency Score: 0.0075

=== [1380/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.49it/s]
Hypertuning:  40%|███▉      | 1380/3456 [32:34<47:14,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.7442
➡️ Total Profit: ₹61,047.14
➡️ Equity Curve R²: 0.8118
➡️ Monthly Consistency Score: 0.2294

=== [1381/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.09it/s]
Hypertuning:  40%|███▉      | 1381/3456 [32:36<46:56,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0903
➡️ Total Profit: ₹2,998.36
➡️ Equity Curve R²: 0.1091
➡️ Monthly Consistency Score: 0.0111

=== [1382/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.15it/s]
Hypertuning:  40%|███▉      | 1382/3456 [32:37<47:11,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2947
➡️ Total Profit: ₹-17,723.84
➡️ Equity Curve R²: 0.8284
➡️ Monthly Consistency Score: -0.0667

=== [1383/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.63it/s]
Hypertuning:  40%|████      | 1383/3456 [32:38<47:24,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1826
➡️ Total Profit: ₹-5,762.53
➡️ Equity Curve R²: 0.4041
➡️ Monthly Consistency Score: -0.0242

=== [1384/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.01it/s]
Hypertuning:  40%|████      | 1384/3456 [32:40<46:35,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.1636
➡️ Total Profit: ₹23,717.77
➡️ Equity Curve R²: 0.2859
➡️ Monthly Consistency Score: 0.0894

=== [1385/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.60it/s]
Hypertuning:  40%|████      | 1385/3456 [32:41<46:29,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.0455
➡️ Total Profit: ₹2,086.96
➡️ Equity Curve R²: 0.5737
➡️ Monthly Consistency Score: 0.0075

=== [1386/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.89it/s]
Hypertuning:  40%|████      | 1386/3456 [32:42<47:16,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1006
➡️ Total Profit: ₹-4,422.12
➡️ Equity Curve R²: 0.4160
➡️ Monthly Consistency Score: -0.0146

=== [1387/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.89it/s]
Hypertuning:  40%|████      | 1387/3456 [32:44<47:28,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 3.7769
➡️ Total Profit: ₹70,739.91
➡️ Equity Curve R²: 0.5131
➡️ Monthly Consistency Score: 0.2957

=== [1388/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.27it/s]
Hypertuning:  40%|████      | 1388/3456 [32:45<46:44,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.3282
➡️ Total Profit: ₹70,878.48
➡️ Equity Curve R²: 0.4369
➡️ Monthly Consistency Score: 0.2652

=== [1389/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.08it/s]
Hypertuning:  40%|████      | 1389/3456 [32:46<46:31,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.9083
➡️ Total Profit: ₹29,953.84
➡️ Equity Curve R²: 0.0001
➡️ Monthly Consistency Score: 0.1181

=== [1390/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.91it/s]
Hypertuning:  40%|████      | 1390/3456 [32:48<46:49,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.6678
➡️ Total Profit: ₹56,670.33
➡️ Equity Curve R²: 0.0702
➡️ Monthly Consistency Score: 0.2067

=== [1391/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.11it/s]
Hypertuning:  40%|████      | 1391/3456 [32:49<45:57,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.2983
➡️ Total Profit: ₹63,483.92
➡️ Equity Curve R²: 0.4694
➡️ Monthly Consistency Score: 0.2377

=== [1392/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.17it/s]
Hypertuning:  40%|████      | 1392/3456 [32:50<46:08,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 4.2111
➡️ Total Profit: ₹62,780.11
➡️ Equity Curve R²: 0.7115
➡️ Monthly Consistency Score: 0.2740

=== [1393/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.41it/s]
Hypertuning:  40%|████      | 1393/3456 [32:52<47:00,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4535
➡️ Total Profit: ₹-22,033.28
➡️ Equity Curve R²: 0.9035
➡️ Monthly Consistency Score: -0.0991

=== [1394/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.17it/s]
Hypertuning:  40%|████      | 1394/3456 [32:53<46:37,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3051
➡️ Total Profit: ₹-17,137.43
➡️ Equity Curve R²: 0.8819
➡️ Monthly Consistency Score: -0.0673

=== [1395/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 129.46it/s]
Hypertuning:  40%|████      | 1395/3456 [32:55<45:46,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 0.3247
➡️ Total Profit: ₹16,282.66
➡️ Equity Curve R²: 0.3869
➡️ Monthly Consistency Score: 0.0592

=== [1396/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.98it/s]
Hypertuning:  40%|████      | 1396/3456 [32:56<45:57,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.1989
➡️ Total Profit: ₹46,146.43
➡️ Equity Curve R²: 0.3751
➡️ Monthly Consistency Score: 0.1703

=== [1397/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.09it/s]
Hypertuning:  40%|████      | 1397/3456 [32:57<46:54,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0390
➡️ Total Profit: ₹-1,406.47
➡️ Equity Curve R²: 0.5106
➡️ Monthly Consistency Score: -0.0054

=== [1398/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.78it/s]
Hypertuning:  40%|████      | 1398/3456 [32:59<46:31,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2766
➡️ Total Profit: ₹-15,189.00
➡️ Equity Curve R²: 0.7134
➡️ Monthly Consistency Score: -0.0551

=== [1399/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.06it/s]
Hypertuning:  40%|████      | 1399/3456 [33:00<45:43,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 0.3354
➡️ Total Profit: ₹10,511.63
➡️ Equity Curve R²: 0.1590
➡️ Monthly Consistency Score: 0.0415

=== [1400/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.84it/s]
Hypertuning:  41%|████      | 1400/3456 [33:01<46:00,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.6196
➡️ Total Profit: ₹21,292.53
➡️ Equity Curve R²: 0.0031
➡️ Monthly Consistency Score: 0.0803

=== [1401/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.47it/s]
Hypertuning:  41%|████      | 1401/3456 [33:03<45:49,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.2559
➡️ Total Profit: ₹-12,909.28
➡️ Equity Curve R²: 0.7928
➡️ Monthly Consistency Score: -0.0442

=== [1402/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.70it/s]
Hypertuning:  41%|████      | 1402/3456 [33:04<46:16,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.0213
➡️ Total Profit: ₹1,316.21
➡️ Equity Curve R²: 0.4569
➡️ Monthly Consistency Score: 0.0042

=== [1403/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.71it/s]
Hypertuning:  41%|████      | 1403/3456 [33:05<46:44,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.7149
➡️ Total Profit: ₹75,628.54
➡️ Equity Curve R²: 0.4080
➡️ Monthly Consistency Score: 0.3148

=== [1404/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.49it/s]
Hypertuning:  41%|████      | 1404/3456 [33:07<46:02,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.6425
➡️ Total Profit: ₹51,229.47
➡️ Equity Curve R²: 0.0678
➡️ Monthly Consistency Score: 0.1875

=== [1405/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.58it/s]
Hypertuning:  41%|████      | 1405/3456 [33:08<45:38,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.5991
➡️ Total Profit: ₹22,397.60
➡️ Equity Curve R²: 0.0308
➡️ Monthly Consistency Score: 0.0879

=== [1406/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.69it/s]
Hypertuning:  41%|████      | 1406/3456 [33:09<46:09,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.8252
➡️ Total Profit: ₹62,016.88
➡️ Equity Curve R²: 0.0190
➡️ Monthly Consistency Score: 0.2254

=== [1407/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.76it/s]
Hypertuning:  41%|████      | 1407/3456 [33:11<46:39,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.8379
➡️ Total Profit: ₹32,332.54
➡️ Equity Curve R²: 0.1968
➡️ Monthly Consistency Score: 0.1176

=== [1408/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.03it/s]
Hypertuning:  41%|████      | 1408/3456 [33:12<45:59,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 9.2760
➡️ Total Profit: ₹98,772.96
➡️ Equity Curve R²: 0.9134
➡️ Monthly Consistency Score: 0.4818

=== [1409/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.69it/s]
Hypertuning:  41%|████      | 1409/3456 [33:14<46:45,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4488
➡️ Total Profit: ₹-20,143.75
➡️ Equity Curve R²: 0.8929
➡️ Monthly Consistency Score: -0.0952

=== [1410/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.51it/s]
Hypertuning:  41%|████      | 1410/3456 [33:15<46:14,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2501
➡️ Total Profit: ₹-13,922.99
➡️ Equity Curve R²: 0.8612
➡️ Monthly Consistency Score: -0.0613

=== [1411/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.51it/s]
Hypertuning:  41%|████      | 1411/3456 [33:16<45:31,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.1999
➡️ Total Profit: ₹11,003.97
➡️ Equity Curve R²: 0.5020
➡️ Monthly Consistency Score: 0.0404

=== [1412/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.56it/s]
Hypertuning:  41%|████      | 1412/3456 [33:17<45:49,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.3795
➡️ Total Profit: ₹53,275.48
➡️ Equity Curve R²: 0.5596
➡️ Monthly Consistency Score: 0.1969

=== [1413/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.05it/s]
Hypertuning:  41%|████      | 1413/3456 [33:19<45:32,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.0493
➡️ Total Profit: ₹1,739.30
➡️ Equity Curve R²: 0.3526
➡️ Monthly Consistency Score: 0.0069

=== [1414/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.17it/s]
Hypertuning:  41%|████      | 1414/3456 [33:20<45:59,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2962
➡️ Total Profit: ₹-18,143.72
➡️ Equity Curve R²: 0.8232
➡️ Monthly Consistency Score: -0.0704

=== [1415/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.68it/s]
Hypertuning:  41%|████      | 1415/3456 [33:21<45:20,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 0.4907
➡️ Total Profit: ₹13,777.11
➡️ Equity Curve R²: 0.0810
➡️ Monthly Consistency Score: 0.0562

=== [1416/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.89it/s]
Hypertuning:  41%|████      | 1416/3456 [33:23<45:44,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3636
➡️ Total Profit: ₹15,814.21
➡️ Equity Curve R²: 0.1551
➡️ Monthly Consistency Score: 0.0627

=== [1417/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.90it/s]
Hypertuning:  41%|████      | 1417/3456 [33:24<45:38,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.1869
➡️ Total Profit: ₹7,758.37
➡️ Equity Curve R²: 0.5600
➡️ Monthly Consistency Score: 0.0276

=== [1418/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.56it/s]
Hypertuning:  41%|████      | 1418/3456 [33:26<45:59,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4834
➡️ Total Profit: ₹20,705.29
➡️ Equity Curve R²: 0.0480
➡️ Monthly Consistency Score: 0.0669

=== [1419/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 103.43it/s]
Hypertuning:  41%|████      | 1419/3456 [33:27<46:26,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.6348
➡️ Total Profit: ₹73,997.17
➡️ Equity Curve R²: 0.4791
➡️ Monthly Consistency Score: 0.3100

=== [1420/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.31it/s]
Hypertuning:  41%|████      | 1420/3456 [33:28<45:56,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.6425
➡️ Total Profit: ₹51,229.47
➡️ Equity Curve R²: 0.0678
➡️ Monthly Consistency Score: 0.1875

=== [1421/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.59it/s]
Hypertuning:  41%|████      | 1421/3456 [33:30<45:36,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.8320
➡️ Total Profit: ₹27,435.72
➡️ Equity Curve R²: 0.0013
➡️ Monthly Consistency Score: 0.1077

=== [1422/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.46it/s]
Hypertuning:  41%|████      | 1422/3456 [33:31<45:52,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.4684
➡️ Total Profit: ₹49,892.17
➡️ Equity Curve R²: 0.0291
➡️ Monthly Consistency Score: 0.1872

=== [1423/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.87it/s]
Hypertuning:  41%|████      | 1423/3456 [33:32<46:08,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.0033
➡️ Total Profit: ₹55,335.28
➡️ Equity Curve R²: 0.2592
➡️ Monthly Consistency Score: 0.1913

=== [1424/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.61it/s]
Hypertuning:  41%|████      | 1424/3456 [33:34<45:44,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 9.2760
➡️ Total Profit: ₹98,772.96
➡️ Equity Curve R²: 0.9134
➡️ Monthly Consistency Score: 0.4818

=== [1425/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.68it/s]
Hypertuning:  41%|████      | 1425/3456 [33:35<46:48,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.6955
➡️ Total Profit: ₹-41,976.84
➡️ Equity Curve R²: 0.9190
➡️ Monthly Consistency Score: -0.1920

=== [1426/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.82it/s]
Hypertuning:  41%|████▏     | 1426/3456 [33:36<46:16,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1514
➡️ Total Profit: ₹-7,662.91
➡️ Equity Curve R²: 0.8036
➡️ Monthly Consistency Score: -0.0332

=== [1427/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.53it/s]
Hypertuning:  41%|████▏     | 1427/3456 [33:38<45:31,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0370
➡️ Total Profit: ₹-2,099.18
➡️ Equity Curve R²: 0.7069
➡️ Monthly Consistency Score: -0.0077

=== [1428/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.53it/s]
Hypertuning:  41%|████▏     | 1428/3456 [33:39<46:00,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.4375
➡️ Total Profit: ₹56,046.28
➡️ Equity Curve R²: 0.6807
➡️ Monthly Consistency Score: 0.2099

=== [1429/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.65it/s]
Hypertuning:  41%|████▏     | 1429/3456 [33:41<45:35,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2467
➡️ Total Profit: ₹-10,520.70
➡️ Equity Curve R²: 0.3303
➡️ Monthly Consistency Score: -0.0386

=== [1430/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.36it/s]
Hypertuning:  41%|████▏     | 1430/3456 [33:42<46:00,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3110
➡️ Total Profit: ₹-16,943.72
➡️ Equity Curve R²: 0.8181
➡️ Monthly Consistency Score: -0.0668

=== [1431/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.34it/s]
Hypertuning:  41%|████▏     | 1431/3456 [33:43<45:26,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2947
➡️ Total Profit: ₹7,314.74
➡️ Equity Curve R²: 0.1474
➡️ Monthly Consistency Score: 0.0311

=== [1432/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.48it/s]
Hypertuning:  41%|████▏     | 1432/3456 [33:45<45:51,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2906
➡️ Total Profit: ₹9,721.41
➡️ Equity Curve R²: 0.1522
➡️ Monthly Consistency Score: 0.0366

=== [1433/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.53it/s]
Hypertuning:  41%|████▏     | 1433/3456 [33:46<45:37,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0218
➡️ Total Profit: ₹-1,061.63
➡️ Equity Curve R²: 0.6363
➡️ Monthly Consistency Score: -0.0037

=== [1434/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.70it/s]
Hypertuning:  41%|████▏     | 1434/3456 [33:47<46:05,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.3882
➡️ Total Profit: ₹14,872.53
➡️ Equity Curve R²: 0.1494
➡️ Monthly Consistency Score: 0.0492

=== [1435/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.20it/s]
Hypertuning:  42%|████▏     | 1435/3456 [33:49<46:53,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 2.7246
➡️ Total Profit: ₹48,848.53
➡️ Equity Curve R²: 0.6495
➡️ Monthly Consistency Score: 0.2027

=== [1436/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.21it/s]
Hypertuning:  42%|████▏     | 1436/3456 [33:50<46:03,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.3691
➡️ Total Profit: ₹78,919.30
➡️ Equity Curve R²: 0.7495
➡️ Monthly Consistency Score: 0.3210

=== [1437/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.33it/s]
Hypertuning:  42%|████▏     | 1437/3456 [33:51<45:37,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.1338
➡️ Total Profit: ₹33,103.37
➡️ Equity Curve R²: 0.0091
➡️ Monthly Consistency Score: 0.1283

=== [1438/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.74it/s]
Hypertuning:  42%|████▏     | 1438/3456 [33:53<45:57,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.2001
➡️ Total Profit: ₹62,323.10
➡️ Equity Curve R²: 0.2522
➡️ Monthly Consistency Score: 0.2320

=== [1439/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 109.14it/s]
Hypertuning:  42%|████▏     | 1439/3456 [33:54<46:29,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.2983
➡️ Total Profit: ₹63,483.92
➡️ Equity Curve R²: 0.4296
➡️ Monthly Consistency Score: 0.2352

=== [1440/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.61it/s]
Hypertuning:  42%|████▏     | 1440/3456 [33:56<45:42,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 5.2454
➡️ Total Profit: ₹67,036.47
➡️ Equity Curve R²: 0.7465
➡️ Monthly Consistency Score: 0.2978

=== [1441/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.59it/s]
Hypertuning:  42%|████▏     | 1441/3456 [33:57<46:41,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.6419
➡️ Total Profit: ₹-42,983.90
➡️ Equity Curve R²: 0.9449
➡️ Monthly Consistency Score: -0.1974

=== [1442/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.26it/s]
Hypertuning:  42%|████▏     | 1442/3456 [33:58<45:48,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.5957
➡️ Total Profit: ₹-38,069.96
➡️ Equity Curve R²: 0.9229
➡️ Monthly Consistency Score: -0.1786

=== [1443/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 100.47it/s]
Hypertuning:  42%|████▏     | 1443/3456 [34:00<45:11,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6948
➡️ Total Profit: ₹-52,716.35
➡️ Equity Curve R²: 0.8963
➡️ Monthly Consistency Score: -0.2151

=== [1444/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.22it/s]
Hypertuning:  42%|████▏     | 1444/3456 [34:01<45:37,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.7170
➡️ Total Profit: ₹-35,147.10
➡️ Equity Curve R²: 0.6417
➡️ Monthly Consistency Score: -0.1260

=== [1445/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.21it/s]
Hypertuning:  42%|████▏     | 1445/3456 [34:02<45:33,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.6394
➡️ Total Profit: ₹17,945.88
➡️ Equity Curve R²: 0.5052
➡️ Monthly Consistency Score: 0.0666

=== [1446/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.35it/s]
Hypertuning:  42%|████▏     | 1446/3456 [34:04<45:50,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.9029
➡️ Total Profit: ₹22,440.97
➡️ Equity Curve R²: 0.4052
➡️ Monthly Consistency Score: 0.0804

=== [1447/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.57it/s]
Hypertuning:  42%|████▏     | 1447/3456 [34:05<45:14,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6358
➡️ Total Profit: ₹18,682.11
➡️ Equity Curve R²: 0.0316
➡️ Monthly Consistency Score: 0.0733

=== [1448/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.07it/s]
Hypertuning:  42%|████▏     | 1448/3456 [34:06<45:25,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1046
➡️ Total Profit: ₹3,021.04
➡️ Equity Curve R²: 0.0367
➡️ Monthly Consistency Score: 0.0120

=== [1449/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.02it/s]
Hypertuning:  42%|████▏     | 1449/3456 [34:08<46:11,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.3115
➡️ Total Profit: ₹29,745.59
➡️ Equity Curve R²: 0.2935
➡️ Monthly Consistency Score: 0.1094

=== [1450/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.90it/s]
Hypertuning:  42%|████▏     | 1450/3456 [34:09<45:49,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.5228
➡️ Total Profit: ₹-17,135.48
➡️ Equity Curve R²: 0.5561
➡️ Monthly Consistency Score: -0.0651

=== [1451/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.37it/s]
Hypertuning:  42%|████▏     | 1451/3456 [34:11<46:20,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.4065
➡️ Total Profit: ₹-21,023.58
➡️ Equity Curve R²: 0.6309
➡️ Monthly Consistency Score: -0.0802

=== [1452/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.21it/s]
Hypertuning:  42%|████▏     | 1452/3456 [34:12<45:54,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.6419
➡️ Total Profit: ₹21,398.19
➡️ Equity Curve R²: 0.0591
➡️ Monthly Consistency Score: 0.0823

=== [1453/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.86it/s]
Hypertuning:  42%|████▏     | 1453/3456 [34:13<45:40,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1834
➡️ Total Profit: ₹42,759.66
➡️ Equity Curve R²: 0.0261
➡️ Monthly Consistency Score: 0.1803

=== [1454/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.24it/s]
Hypertuning:  42%|████▏     | 1454/3456 [34:15<46:11,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.7455
➡️ Total Profit: ₹68,263.68
➡️ Equity Curve R²: 0.4411
➡️ Monthly Consistency Score: 0.3092

=== [1455/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.38it/s]
Hypertuning:  42%|████▏     | 1455/3456 [34:16<45:31,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.5280
➡️ Total Profit: ₹27,354.67
➡️ Equity Curve R²: 0.1493
➡️ Monthly Consistency Score: 0.1094

=== [1456/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.21it/s]
Hypertuning:  42%|████▏     | 1456/3456 [34:17<44:33,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.6066
➡️ Total Profit: ₹51,340.89
➡️ Equity Curve R²: 0.5437
➡️ Monthly Consistency Score: 0.2273

=== [1457/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.68it/s]
Hypertuning:  42%|████▏     | 1457/3456 [34:19<44:35,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.5536
➡️ Total Profit: ₹-30,518.54
➡️ Equity Curve R²: 0.9204
➡️ Monthly Consistency Score: -0.1439

=== [1458/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.27it/s]
Hypertuning:  42%|████▏     | 1458/3456 [34:20<45:04,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.4498
➡️ Total Profit: ₹-21,117.19
➡️ Equity Curve R²: 0.7774
➡️ Monthly Consistency Score: -0.0970

=== [1459/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.38it/s]
Hypertuning:  42%|████▏     | 1459/3456 [34:21<44:25,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: -0.5385
➡️ Total Profit: ₹-33,930.87
➡️ Equity Curve R²: 0.8046
➡️ Monthly Consistency Score: -0.1380

=== [1460/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.49it/s]
Hypertuning:  42%|████▏     | 1460/3456 [34:23<44:52,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6724
➡️ Total Profit: ₹-30,149.88
➡️ Equity Curve R²: 0.6121
➡️ Monthly Consistency Score: -0.1072

=== [1461/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.23it/s]
Hypertuning:  42%|████▏     | 1461/3456 [34:24<44:50,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.8668
➡️ Total Profit: ₹23,779.99
➡️ Equity Curve R²: 0.5717
➡️ Monthly Consistency Score: 0.0863

=== [1462/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 109.14it/s]
Hypertuning:  42%|████▏     | 1462/3456 [34:26<45:29,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.3178
➡️ Total Profit: ₹8,611.89
➡️ Equity Curve R²: 0.3907
➡️ Monthly Consistency Score: 0.0342

=== [1463/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.48it/s]
Hypertuning:  42%|████▏     | 1463/3456 [34:27<44:44,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.7467
➡️ Total Profit: ₹21,942.11
➡️ Equity Curve R²: 0.0923
➡️ Monthly Consistency Score: 0.0858

=== [1464/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.91it/s]
Hypertuning:  42%|████▏     | 1464/3456 [34:28<45:08,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1905
➡️ Total Profit: ₹-6,722.60
➡️ Equity Curve R²: 0.1971
➡️ Monthly Consistency Score: -0.0254

=== [1465/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.82it/s]
Hypertuning:  42%|████▏     | 1465/3456 [34:30<44:52,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.3775
➡️ Total Profit: ₹30,375.12
➡️ Equity Curve R²: 0.3252
➡️ Monthly Consistency Score: 0.1123

=== [1466/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.91it/s]
Hypertuning:  42%|████▏     | 1466/3456 [34:31<45:08,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0743
➡️ Total Profit: ₹-2,266.40
➡️ Equity Curve R²: 0.0006
➡️ Monthly Consistency Score: -0.0080

=== [1467/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.38it/s]
Hypertuning:  42%|████▏     | 1467/3456 [34:32<45:31,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.4618
➡️ Total Profit: ₹16,825.22
➡️ Equity Curve R²: 0.0383
➡️ Monthly Consistency Score: 0.0670

=== [1468/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.57it/s]
Hypertuning:  42%|████▏     | 1468/3456 [34:34<44:47,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.8586
➡️ Total Profit: ₹44,837.29
➡️ Equity Curve R²: 0.6456
➡️ Monthly Consistency Score: 0.1685

=== [1469/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.02it/s]
Hypertuning:  43%|████▎     | 1469/3456 [34:35<44:38,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.3959
➡️ Total Profit: ₹47,801.54
➡️ Equity Curve R²: 0.0370
➡️ Monthly Consistency Score: 0.1998

=== [1470/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.91it/s]
Hypertuning:  43%|████▎     | 1470/3456 [34:36<45:18,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.7910
➡️ Total Profit: ₹69,394.60
➡️ Equity Curve R²: 0.4274
➡️ Monthly Consistency Score: 0.3113

=== [1471/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.48it/s]
Hypertuning:  43%|████▎     | 1471/3456 [34:38<44:49,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.5118
➡️ Total Profit: ₹27,354.67
➡️ Equity Curve R²: 0.1912
➡️ Monthly Consistency Score: 0.1075

=== [1472/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.66it/s]
Hypertuning:  43%|████▎     | 1472/3456 [34:39<45:06,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.9101
➡️ Total Profit: ₹56,377.37
➡️ Equity Curve R²: 0.4546
➡️ Monthly Consistency Score: 0.2526

=== [1473/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.04it/s]
Hypertuning:  43%|████▎     | 1473/3456 [34:41<45:45,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.6549
➡️ Total Profit: ₹-38,081.36
➡️ Equity Curve R²: 0.8949
➡️ Monthly Consistency Score: -0.1763

=== [1474/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.59it/s]
Hypertuning:  43%|████▎     | 1474/3456 [34:42<45:10,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2620
➡️ Total Profit: ₹-9,817.19
➡️ Equity Curve R²: 0.6935
➡️ Monthly Consistency Score: -0.0454

=== [1475/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.74it/s]
Hypertuning:  43%|████▎     | 1475/3456 [34:43<44:28,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.7206
➡️ Total Profit: ₹-56,358.31
➡️ Equity Curve R²: 0.9027
➡️ Monthly Consistency Score: -0.2429

=== [1476/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.83it/s]
Hypertuning:  43%|████▎     | 1476/3456 [34:45<44:49,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.5158
➡️ Total Profit: ₹-25,791.64
➡️ Equity Curve R²: 0.6432
➡️ Monthly Consistency Score: -0.0945

=== [1477/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.53it/s]
Hypertuning:  43%|████▎     | 1477/3456 [34:46<45:41,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 0.2879
➡️ Total Profit: ₹7,899.87
➡️ Equity Curve R²: 0.1195
➡️ Monthly Consistency Score: 0.0291

=== [1478/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.96it/s]
Hypertuning:  43%|████▎     | 1478/3456 [34:47<45:07,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.7103
➡️ Total Profit: ₹14,624.65
➡️ Equity Curve R²: 0.1764
➡️ Monthly Consistency Score: 0.0555

=== [1479/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.29it/s]
Hypertuning:  43%|████▎     | 1479/3456 [34:49<44:33,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.4873
➡️ Total Profit: ₹57,742.49
➡️ Equity Curve R²: 0.7504
➡️ Monthly Consistency Score: 0.2326

=== [1480/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.15it/s]
Hypertuning:  43%|████▎     | 1480/3456 [34:50<44:53,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.7404
➡️ Total Profit: ₹20,050.13
➡️ Equity Curve R²: 0.5077
➡️ Monthly Consistency Score: 0.0744

=== [1481/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.38it/s]
Hypertuning:  43%|████▎     | 1481/3456 [34:51<45:34,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.5481
➡️ Total Profit: ₹15,881.83
➡️ Equity Curve R²: 0.0299
➡️ Monthly Consistency Score: 0.0613

=== [1482/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.60it/s]
Hypertuning:  43%|████▎     | 1482/3456 [34:53<44:52,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0002
➡️ Total Profit: ₹-6.40
➡️ Equity Curve R²: 0.0103
➡️ Monthly Consistency Score: -0.0000

=== [1483/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.98it/s]
Hypertuning:  43%|████▎     | 1483/3456 [34:54<44:12,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.7001
➡️ Total Profit: ₹27,307.96
➡️ Equity Curve R²: 0.0535
➡️ Monthly Consistency Score: 0.1027

=== [1484/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 110.07it/s]
Hypertuning:  43%|████▎     | 1484/3456 [34:55<44:28,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2205
➡️ Total Profit: ₹10,276.46
➡️ Equity Curve R²: 0.1071
➡️ Monthly Consistency Score: 0.0382

=== [1485/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.89it/s]
Hypertuning:  43%|████▎     | 1485/3456 [34:57<44:09,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.2146
➡️ Total Profit: ₹44,652.01
➡️ Equity Curve R²: 0.0074
➡️ Monthly Consistency Score: 0.1826

=== [1486/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.67it/s]
Hypertuning:  43%|████▎     | 1486/3456 [34:58<44:37,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.3945
➡️ Total Profit: ₹59,535.41
➡️ Equity Curve R²: 0.3765
➡️ Monthly Consistency Score: 0.2654

=== [1487/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.91it/s]
Hypertuning:  43%|████▎     | 1487/3456 [35:00<44:59,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.5594
➡️ Total Profit: ₹28,986.04
➡️ Equity Curve R²: 0.2078
➡️ Monthly Consistency Score: 0.1172

=== [1488/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.37it/s]
Hypertuning:  43%|████▎     | 1488/3456 [35:01<44:20,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.5135
➡️ Total Profit: ₹23,084.53
➡️ Equity Curve R²: 0.2670
➡️ Monthly Consistency Score: 0.0907

=== [1489/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.77it/s]
Hypertuning:  43%|████▎     | 1489/3456 [35:02<44:12,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6218
➡️ Total Profit: ₹-40,463.90
➡️ Equity Curve R²: 0.9365
➡️ Monthly Consistency Score: -0.1856

=== [1490/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.91it/s]
Hypertuning:  43%|████▎     | 1490/3456 [35:04<44:30,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.6296
➡️ Total Profit: ₹-40,942.64
➡️ Equity Curve R²: 0.9275
➡️ Monthly Consistency Score: -0.1934

=== [1491/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.61it/s]
Hypertuning:  43%|████▎     | 1491/3456 [35:05<44:51,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.6724
➡️ Total Profit: ₹-44,963.14
➡️ Equity Curve R²: 0.7874
➡️ Monthly Consistency Score: -0.1777

=== [1492/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.94it/s]
Hypertuning:  43%|████▎     | 1492/3456 [35:06<44:11,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6739
➡️ Total Profit: ₹-28,673.52
➡️ Equity Curve R²: 0.4213
➡️ Monthly Consistency Score: -0.1019

=== [1493/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.00it/s]
Hypertuning:  43%|████▎     | 1493/3456 [35:08<43:49,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.8069
➡️ Total Profit: ₹22,646.82
➡️ Equity Curve R²: 0.5872
➡️ Monthly Consistency Score: 0.0820

=== [1494/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.89it/s]
Hypertuning:  43%|████▎     | 1494/3456 [35:09<44:09,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4655
➡️ Total Profit: ₹11,570.05
➡️ Equity Curve R²: 0.0786
➡️ Monthly Consistency Score: 0.0430

=== [1495/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.36it/s]
Hypertuning:  43%|████▎     | 1495/3456 [35:10<44:30,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.6358
➡️ Total Profit: ₹18,682.11
➡️ Equity Curve R²: 0.0316
➡️ Monthly Consistency Score: 0.0733

=== [1496/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.09it/s]
Hypertuning:  43%|████▎     | 1496/3456 [35:12<43:54,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.1930
➡️ Total Profit: ₹-7,630.78
➡️ Equity Curve R²: 0.2904
➡️ Monthly Consistency Score: -0.0285

=== [1497/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.31it/s]
Hypertuning:  43%|████▎     | 1497/3456 [35:13<43:47,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.3115
➡️ Total Profit: ₹29,745.59
➡️ Equity Curve R²: 0.2935
➡️ Monthly Consistency Score: 0.1094

=== [1498/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.56it/s]
Hypertuning:  43%|████▎     | 1498/3456 [35:14<44:15,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.5058
➡️ Total Profit: ₹-16,008.24
➡️ Equity Curve R²: 0.5175
➡️ Monthly Consistency Score: -0.0600

=== [1499/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.50it/s]
Hypertuning:  43%|████▎     | 1499/3456 [35:16<43:44,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.5352
➡️ Total Profit: ₹-30,798.10
➡️ Equity Curve R²: 0.6938
➡️ Monthly Consistency Score: -0.1142

=== [1500/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 102.84it/s]
Hypertuning:  43%|████▎     | 1500/3456 [35:17<43:59,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6419
➡️ Total Profit: ₹21,398.19
➡️ Equity Curve R²: 0.0591
➡️ Monthly Consistency Score: 0.0823

=== [1501/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 104.22it/s]
Hypertuning:  43%|████▎     | 1501/3456 [35:19<44:46,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.2183
➡️ Total Profit: ₹44,020.60
➡️ Equity Curve R²: 0.0223
➡️ Monthly Consistency Score: 0.1840

=== [1502/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.70it/s]
Hypertuning:  43%|████▎     | 1502/3456 [35:20<44:21,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.7455
➡️ Total Profit: ₹68,263.68
➡️ Equity Curve R²: 0.4411
➡️ Monthly Consistency Score: 0.3092

=== [1503/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 111.93it/s]
Hypertuning:  43%|████▎     | 1503/3456 [35:21<44:49,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.5280
➡️ Total Profit: ₹27,354.67
➡️ Equity Curve R²: 0.1493
➡️ Monthly Consistency Score: 0.1094

=== [1504/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.91it/s]
Hypertuning:  44%|████▎     | 1504/3456 [35:23<43:58,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.6066
➡️ Total Profit: ₹51,340.89
➡️ Equity Curve R²: 0.5437
➡️ Monthly Consistency Score: 0.2273

=== [1505/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.69it/s]
Hypertuning:  44%|████▎     | 1505/3456 [35:24<43:57,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6486
➡️ Total Profit: ₹-37,168.68
➡️ Equity Curve R²: 0.9419
➡️ Monthly Consistency Score: -0.1798

=== [1506/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.26it/s]
Hypertuning:  44%|████▎     | 1506/3456 [35:25<44:22,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3422
➡️ Total Profit: ₹-17,640.71
➡️ Equity Curve R²: 0.8626
➡️ Monthly Consistency Score: -0.0796

=== [1507/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.44it/s]
Hypertuning:  44%|████▎     | 1507/3456 [35:27<44:40,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.4044
➡️ Total Profit: ₹-20,896.35
➡️ Equity Curve R²: 0.7575
➡️ Monthly Consistency Score: -0.0837

=== [1508/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.71it/s]
Hypertuning:  44%|████▎     | 1508/3456 [35:28<43:59,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.4790
➡️ Total Profit: ₹-18,025.34
➡️ Equity Curve R²: 0.1237
➡️ Monthly Consistency Score: -0.0633

=== [1509/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.38it/s]
Hypertuning:  44%|████▎     | 1509/3456 [35:29<43:40,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0777
➡️ Total Profit: ₹-2,180.13
➡️ Equity Curve R²: 0.0228
➡️ Monthly Consistency Score: -0.0079

=== [1510/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.33it/s]
Hypertuning:  44%|████▎     | 1510/3456 [35:31<43:53,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.0594
➡️ Total Profit: ₹25,133.73
➡️ Equity Curve R²: 0.2543
➡️ Monthly Consistency Score: 0.0982

=== [1511/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.49it/s]
Hypertuning:  44%|████▎     | 1511/3456 [35:32<43:12,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 3.5128
➡️ Total Profit: ₹57,739.75
➡️ Equity Curve R²: 0.7635
➡️ Monthly Consistency Score: 0.2332

=== [1512/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.45it/s]
Hypertuning:  44%|████▍     | 1512/3456 [35:33<43:28,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.2238
➡️ Total Profit: ₹-8,850.78
➡️ Equity Curve R²: 0.2780
➡️ Monthly Consistency Score: -0.0327

=== [1513/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.65it/s]
Hypertuning:  44%|████▍     | 1513/3456 [35:35<44:25,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.6882
➡️ Total Profit: ₹17,773.24
➡️ Equity Curve R²: 0.1086
➡️ Monthly Consistency Score: 0.0651

=== [1514/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.20it/s]
Hypertuning:  44%|████▍     | 1514/3456 [35:36<43:53,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4882
➡️ Total Profit: ₹-16,004.56
➡️ Equity Curve R²: 0.4939
➡️ Monthly Consistency Score: -0.0590

=== [1515/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.69it/s]
Hypertuning:  44%|████▍     | 1515/3456 [35:37<44:11,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2191
➡️ Total Profit: ₹-7,980.84
➡️ Equity Curve R²: 0.5615
➡️ Monthly Consistency Score: -0.0298

=== [1516/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.77it/s]
Hypertuning:  44%|████▍     | 1516/3456 [35:39<43:41,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.0833
➡️ Total Profit: ₹3,881.00
➡️ Equity Curve R²: 0.2432
➡️ Monthly Consistency Score: 0.0143

=== [1517/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.19it/s]
Hypertuning:  44%|████▍     | 1517/3456 [35:40<43:24,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.3526
➡️ Total Profit: ₹47,170.13
➡️ Equity Curve R²: 0.0295
➡️ Monthly Consistency Score: 0.1968

=== [1518/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.80it/s]
Hypertuning:  44%|████▍     | 1518/3456 [35:42<43:49,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.3490
➡️ Total Profit: ₹58,404.49
➡️ Equity Curve R²: 0.3939
➡️ Monthly Consistency Score: 0.2631

=== [1519/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.03it/s]
Hypertuning:  44%|████▍     | 1519/3456 [35:43<44:06,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.5118
➡️ Total Profit: ₹27,354.67
➡️ Equity Curve R²: 0.1912
➡️ Monthly Consistency Score: 0.1075

=== [1520/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.09it/s]
Hypertuning:  44%|████▍     | 1520/3456 [35:44<43:31,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.9359
➡️ Total Profit: ₹39,337.37
➡️ Equity Curve R²: 0.0009
➡️ Monthly Consistency Score: 0.1621

=== [1521/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.05it/s]
Hypertuning:  44%|████▍     | 1521/3456 [35:46<43:27,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6149
➡️ Total Profit: ₹-38,080.42
➡️ Equity Curve R²: 0.8865
➡️ Monthly Consistency Score: -0.1808

=== [1522/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.32it/s]
Hypertuning:  44%|████▍     | 1522/3456 [35:47<43:49,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0821
➡️ Total Profit: ₹-3,906.07
➡️ Equity Curve R²: 0.6464
➡️ Monthly Consistency Score: -0.0160

=== [1523/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.23it/s]
Hypertuning:  44%|████▍     | 1523/3456 [35:48<44:15,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.6089
➡️ Total Profit: ₹-35,944.08
➡️ Equity Curve R²: 0.8768
➡️ Monthly Consistency Score: -0.1413

=== [1524/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.49it/s]
Hypertuning:  44%|████▍     | 1524/3456 [35:50<43:29,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6968
➡️ Total Profit: ₹-38,666.24
➡️ Equity Curve R²: 0.8467
➡️ Monthly Consistency Score: -0.1353

=== [1525/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.60it/s]
Hypertuning:  44%|████▍     | 1525/3456 [35:51<43:21,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1692
➡️ Total Profit: ₹4,747.52
➡️ Equity Curve R²: 0.0383
➡️ Monthly Consistency Score: 0.0176

=== [1526/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.43it/s]
Hypertuning:  44%|████▍     | 1526/3456 [35:52<43:59,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.7414
➡️ Total Profit: ₹31,917.41
➡️ Equity Curve R²: 0.4975
➡️ Monthly Consistency Score: 0.1268

=== [1527/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.26it/s]
Hypertuning:  44%|████▍     | 1527/3456 [35:54<43:11,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.8541
➡️ Total Profit: ₹39,768.37
➡️ Equity Curve R²: 0.6966
➡️ Monthly Consistency Score: 0.1446

=== [1528/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.91it/s]
Hypertuning:  44%|████▍     | 1528/3456 [35:55<43:22,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4596
➡️ Total Profit: ₹12,445.59
➡️ Equity Curve R²: 0.1614
➡️ Monthly Consistency Score: 0.0453

=== [1529/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.86it/s]
Hypertuning:  44%|████▍     | 1529/3456 [35:56<44:11,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.6328
➡️ Total Profit: ₹17,142.77
➡️ Equity Curve R²: 0.0103
➡️ Monthly Consistency Score: 0.0663

=== [1530/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.25it/s]
Hypertuning:  44%|████▍     | 1530/3456 [35:58<43:34,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1851
➡️ Total Profit: ₹5,648.21
➡️ Equity Curve R²: 0.0530
➡️ Monthly Consistency Score: 0.0198

=== [1531/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.54it/s]
Hypertuning:  44%|████▍     | 1531/3456 [35:59<43:58,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.6076
➡️ Total Profit: ₹25,679.33
➡️ Equity Curve R²: 0.0389
➡️ Monthly Consistency Score: 0.0983

=== [1532/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.29it/s]
Hypertuning:  44%|████▍     | 1532/3456 [36:01<43:22,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.8586
➡️ Total Profit: ₹44,837.29
➡️ Equity Curve R²: 0.5903
➡️ Monthly Consistency Score: 0.1651

=== [1533/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.53it/s]
Hypertuning:  44%|████▍     | 1533/3456 [36:02<43:06,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2922
➡️ Total Profit: ₹13,999.58
➡️ Equity Curve R²: 0.5569
➡️ Monthly Consistency Score: 0.0528

=== [1534/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.90it/s]
Hypertuning:  44%|████▍     | 1534/3456 [36:03<43:34,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.0309
➡️ Total Profit: ₹50,495.41
➡️ Equity Curve R²: 0.3148
➡️ Monthly Consistency Score: 0.2127

=== [1535/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.18it/s]
Hypertuning:  44%|████▍     | 1535/3456 [36:05<44:06,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.3475
➡️ Total Profit: ₹20,840.15
➡️ Equity Curve R²: 0.3630
➡️ Monthly Consistency Score: 0.0807

=== [1536/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.74it/s]
Hypertuning:  44%|████▍     | 1536/3456 [36:06<43:29,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5135
➡️ Total Profit: ₹23,084.53
➡️ Equity Curve R²: 0.2670
➡️ Monthly Consistency Score: 0.0907

=== [1537/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.49it/s]
Hypertuning:  44%|████▍     | 1537/3456 [36:07<43:10,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6384
➡️ Total Profit: ₹-43,888.17
➡️ Equity Curve R²: 0.9305
➡️ Monthly Consistency Score: -0.1855

=== [1538/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.94it/s]
Hypertuning:  45%|████▍     | 1538/3456 [36:09<43:23,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2412
➡️ Total Profit: ₹6,590.53
➡️ Equity Curve R²: 0.1762
➡️ Monthly Consistency Score: 0.0286

=== [1539/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.09it/s]
Hypertuning:  45%|████▍     | 1539/3456 [36:10<43:42,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.4594
➡️ Total Profit: ₹15,812.65
➡️ Equity Curve R²: 0.0125
➡️ Monthly Consistency Score: 0.0636

=== [1540/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 111.75it/s]
Hypertuning:  45%|████▍     | 1540/3456 [36:11<43:00,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1455
➡️ Total Profit: ₹3,276.99
➡️ Equity Curve R²: 0.0106
➡️ Monthly Consistency Score: 0.0126

=== [1541/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.57it/s]
Hypertuning:  45%|████▍     | 1541/3456 [36:13<42:48,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.7063
➡️ Total Profit: ₹19,377.98
➡️ Equity Curve R²: 0.4374
➡️ Monthly Consistency Score: 0.0674

=== [1542/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.65it/s]
Hypertuning:  45%|████▍     | 1542/3456 [36:14<43:06,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3155
➡️ Total Profit: ₹9,324.77
➡️ Equity Curve R²: 0.1895
➡️ Monthly Consistency Score: 0.0367

=== [1543/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.79it/s]
Hypertuning:  45%|████▍     | 1543/3456 [36:15<42:31,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: -0.0219
➡️ Total Profit: ₹-863.75
➡️ Equity Curve R²: 0.4836
➡️ Monthly Consistency Score: -0.0033

=== [1544/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.46it/s]
Hypertuning:  45%|████▍     | 1544/3456 [36:17<42:54,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0431
➡️ Total Profit: ₹-1,847.84
➡️ Equity Curve R²: 0.3428
➡️ Monthly Consistency Score: -0.0082

=== [1545/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.42it/s]
Hypertuning:  45%|████▍     | 1545/3456 [36:18<43:41,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.9004
➡️ Total Profit: ₹22,239.78
➡️ Equity Curve R²: 0.0414
➡️ Monthly Consistency Score: 0.0812

=== [1546/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.59it/s]
Hypertuning:  45%|████▍     | 1546/3456 [36:19<43:06,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.4630
➡️ Total Profit: ₹50,083.13
➡️ Equity Curve R²: 0.3330
➡️ Monthly Consistency Score: 0.1921

=== [1547/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.17it/s]
Hypertuning:  45%|████▍     | 1547/3456 [36:21<43:24,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3586
➡️ Total Profit: ₹-16,125.59
➡️ Equity Curve R²: 0.7439
➡️ Monthly Consistency Score: -0.0629

=== [1548/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 130.73it/s]
Hypertuning:  45%|████▍     | 1548/3456 [36:22<42:47,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0875
➡️ Total Profit: ₹-4,425.18
➡️ Equity Curve R²: 0.6403
➡️ Monthly Consistency Score: -0.0181

=== [1549/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 130.04it/s]
Hypertuning:  45%|████▍     | 1549/3456 [36:24<42:36,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.9965
➡️ Total Profit: ₹24,488.25
➡️ Equity Curve R²: 0.0923
➡️ Monthly Consistency Score: 0.0934

=== [1550/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.15it/s]
Hypertuning:  45%|████▍     | 1550/3456 [36:25<43:02,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.4276
➡️ Total Profit: ₹85,223.80
➡️ Equity Curve R²: 0.6108
➡️ Monthly Consistency Score: 0.3875

=== [1551/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.76it/s]
Hypertuning:  45%|████▍     | 1551/3456 [36:26<43:20,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.2241
➡️ Total Profit: ₹45,367.06
➡️ Equity Curve R²: 0.0013
➡️ Monthly Consistency Score: 0.1770

=== [1552/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.22it/s]
Hypertuning:  45%|████▍     | 1552/3456 [36:28<42:51,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.1401
➡️ Total Profit: ₹56,384.65
➡️ Equity Curve R²: 0.3230
➡️ Monthly Consistency Score: 0.2666

=== [1553/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.56it/s]
Hypertuning:  45%|████▍     | 1553/3456 [36:29<42:41,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.5865
➡️ Total Profit: ₹-33,870.46
➡️ Equity Curve R²: 0.9198
➡️ Monthly Consistency Score: -0.1471

=== [1554/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.65it/s]
Hypertuning:  45%|████▍     | 1554/3456 [36:30<43:04,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0564
➡️ Total Profit: ₹1,546.93
➡️ Equity Curve R²: 0.3166
➡️ Monthly Consistency Score: 0.0066

=== [1555/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.41it/s]
Hypertuning:  45%|████▍     | 1555/3456 [36:32<42:24,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.0740
➡️ Total Profit: ₹-2,569.19
➡️ Equity Curve R²: 0.4181
➡️ Monthly Consistency Score: -0.0112

=== [1556/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.51it/s]
Hypertuning:  45%|████▌     | 1556/3456 [36:33<42:44,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3307
➡️ Total Profit: ₹7,447.95
➡️ Equity Curve R²: 0.0106
➡️ Monthly Consistency Score: 0.0304

=== [1557/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.47it/s]
Hypertuning:  45%|████▌     | 1557/3456 [36:34<42:30,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.9589
➡️ Total Profit: ₹26,308.45
➡️ Equity Curve R²: 0.5471
➡️ Monthly Consistency Score: 0.0929

=== [1558/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.72it/s]
Hypertuning:  45%|████▌     | 1558/3456 [36:36<42:55,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.0419
➡️ Total Profit: ₹43,841.21
➡️ Equity Curve R²: 0.7721
➡️ Monthly Consistency Score: 0.1581

=== [1559/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.20it/s]
Hypertuning:  45%|████▌     | 1559/3456 [36:37<43:19,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0583
➡️ Total Profit: ₹-2,492.38
➡️ Equity Curve R²: 0.5782
➡️ Monthly Consistency Score: -0.0097

=== [1560/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.50it/s]
Hypertuning:  45%|████▌     | 1560/3456 [36:38<42:40,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3943
➡️ Total Profit: ₹10,323.01
➡️ Equity Curve R²: 0.0019
➡️ Monthly Consistency Score: 0.0493

=== [1561/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.22it/s]
Hypertuning:  45%|████▌     | 1561/3456 [36:40<42:29,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.9514
➡️ Total Profit: ₹23,500.72
➡️ Equity Curve R²: 0.0597
➡️ Monthly Consistency Score: 0.0861

=== [1562/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.02it/s]
Hypertuning:  45%|████▌     | 1562/3456 [36:41<42:48,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.5186
➡️ Total Profit: ₹51,214.05
➡️ Equity Curve R²: 0.3223
➡️ Monthly Consistency Score: 0.1959

=== [1563/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.32it/s]
Hypertuning:  45%|████▌     | 1563/3456 [36:43<43:09,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2968
➡️ Total Profit: ₹-12,865.59
➡️ Equity Curve R²: 0.7216
➡️ Monthly Consistency Score: -0.0494

=== [1564/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.49it/s]
Hypertuning:  45%|████▌     | 1564/3456 [36:44<42:32,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6851
➡️ Total Profit: ₹18,319.29
➡️ Equity Curve R²: 0.0058
➡️ Monthly Consistency Score: 0.0709

=== [1565/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.40it/s]
Hypertuning:  45%|████▌     | 1565/3456 [36:45<43:22,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.4700
➡️ Total Profit: ₹35,197.78
➡️ Equity Curve R²: 0.2720
➡️ Monthly Consistency Score: 0.1395

=== [1566/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.53it/s]
Hypertuning:  45%|████▌     | 1566/3456 [36:47<42:50,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.4731
➡️ Total Profit: ₹86,354.72
➡️ Equity Curve R²: 0.5980
➡️ Monthly Consistency Score: 0.3915

=== [1567/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.86it/s]
Hypertuning:  45%|████▌     | 1567/3456 [36:48<42:09,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.2241
➡️ Total Profit: ₹45,367.06
➡️ Equity Curve R²: 0.0013
➡️ Monthly Consistency Score: 0.1770

=== [1568/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.87it/s]
Hypertuning:  45%|████▌     | 1568/3456 [36:49<42:21,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 5.0801
➡️ Total Profit: ₹64,904.65
➡️ Equity Curve R²: 0.6554
➡️ Monthly Consistency Score: 0.3221

=== [1569/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.34it/s]
Hypertuning:  45%|████▌     | 1569/3456 [36:51<42:12,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.6137
➡️ Total Profit: ₹-37,936.43
➡️ Equity Curve R²: 0.9055
➡️ Monthly Consistency Score: -0.1642

=== [1570/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.70it/s]
Hypertuning:  45%|████▌     | 1570/3456 [36:52<42:29,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0928
➡️ Total Profit: ₹-4,182.19
➡️ Equity Curve R²: 0.6779
➡️ Monthly Consistency Score: -0.0181

=== [1571/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.86it/s]
Hypertuning:  45%|████▌     | 1571/3456 [36:53<42:58,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4988
➡️ Total Profit: ₹-27,405.15
➡️ Equity Curve R²: 0.8055
➡️ Monthly Consistency Score: -0.1084

=== [1572/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.27it/s]
Hypertuning:  45%|████▌     | 1572/3456 [36:55<42:29,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3677
➡️ Total Profit: ₹8,283.41
➡️ Equity Curve R²: 0.2855
➡️ Monthly Consistency Score: 0.0329

=== [1573/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.80it/s]
Hypertuning:  46%|████▌     | 1573/3456 [36:56<43:20,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.4705
➡️ Total Profit: ₹12,612.09
➡️ Equity Curve R²: 0.2347
➡️ Monthly Consistency Score: 0.0449

=== [1574/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.76it/s]
Hypertuning:  46%|████▌     | 1574/3456 [36:57<42:44,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2723
➡️ Total Profit: ₹8,537.53
➡️ Equity Curve R²: 0.2607
➡️ Monthly Consistency Score: 0.0289

=== [1575/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.92it/s]
Hypertuning:  46%|████▌     | 1575/3456 [36:59<42:07,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.4131
➡️ Total Profit: ₹34,916.26
➡️ Equity Curve R²: 0.3274
➡️ Monthly Consistency Score: 0.1321

=== [1576/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.56it/s]
Hypertuning:  46%|████▌     | 1576/3456 [37:00<42:25,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.8904
➡️ Total Profit: ₹32,228.53
➡️ Equity Curve R²: 0.5617
➡️ Monthly Consistency Score: 0.1371

=== [1577/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.84it/s]
Hypertuning:  46%|████▌     | 1577/3456 [37:01<42:15,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.1834
➡️ Total Profit: ₹24,758.84
➡️ Equity Curve R²: 0.1478
➡️ Monthly Consistency Score: 0.0918

=== [1578/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.22it/s]
Hypertuning:  46%|████▌     | 1578/3456 [37:03<42:38,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.9628
➡️ Total Profit: ₹39,912.21
➡️ Equity Curve R²: 0.3503
➡️ Monthly Consistency Score: 0.1370

=== [1579/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.50it/s]
Hypertuning:  46%|████▌     | 1579/3456 [37:04<43:07,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.2648
➡️ Total Profit: ₹44,299.74
➡️ Equity Curve R²: 0.6200
➡️ Monthly Consistency Score: 0.1636

=== [1580/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.02it/s]
Hypertuning:  46%|████▌     | 1580/3456 [37:06<42:29,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5988
➡️ Total Profit: ₹22,098.47
➡️ Equity Curve R²: 0.0167
➡️ Monthly Consistency Score: 0.0885

=== [1581/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.68it/s]
Hypertuning:  46%|████▌     | 1581/3456 [37:07<42:13,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.4028
➡️ Total Profit: ₹33,307.31
➡️ Equity Curve R²: 0.2953
➡️ Monthly Consistency Score: 0.1313

=== [1582/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.44it/s]
Hypertuning:  46%|████▌     | 1582/3456 [37:08<42:35,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.3827
➡️ Total Profit: ₹70,007.48
➡️ Equity Curve R²: 0.1384
➡️ Monthly Consistency Score: 0.2978

=== [1583/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.75it/s]
Hypertuning:  46%|████▌     | 1583/3456 [37:10<41:55,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.2344
➡️ Total Profit: ₹43,738.43
➡️ Equity Curve R²: 0.0031
➡️ Monthly Consistency Score: 0.1782

=== [1584/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.92it/s]
Hypertuning:  46%|████▌     | 1584/3456 [37:11<42:08,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.7457
➡️ Total Profit: ₹60,644.65
➡️ Equity Curve R²: 0.4625
➡️ Monthly Consistency Score: 0.2951

=== [1585/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.98it/s]
Hypertuning:  46%|████▌     | 1585/3456 [37:12<41:55,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.6246
➡️ Total Profit: ₹-41,367.23
➡️ Equity Curve R²: 0.9155
➡️ Monthly Consistency Score: -0.1741

=== [1586/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.28it/s]
Hypertuning:  46%|████▌     | 1586/3456 [37:14<42:16,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1847
➡️ Total Profit: ₹4,934.17
➡️ Equity Curve R²: 0.2186
➡️ Monthly Consistency Score: 0.0216

=== [1587/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.57it/s]
Hypertuning:  46%|████▌     | 1587/3456 [37:15<42:37,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.9515
➡️ Total Profit: ₹26,438.54
➡️ Equity Curve R²: 0.2260
➡️ Monthly Consistency Score: 0.1032

=== [1588/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.90it/s]
Hypertuning:  46%|████▌     | 1588/3456 [37:16<41:56,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1453
➡️ Total Profit: ₹3,273.35
➡️ Equity Curve R²: 0.0117
➡️ Monthly Consistency Score: 0.0129

=== [1589/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.73it/s]
Hypertuning:  46%|████▌     | 1589/3456 [37:18<41:47,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.7063
➡️ Total Profit: ₹19,377.98
➡️ Equity Curve R²: 0.4374
➡️ Monthly Consistency Score: 0.0674

=== [1590/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.90it/s]
Hypertuning:  46%|████▌     | 1590/3456 [37:19<42:11,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.3155
➡️ Total Profit: ₹9,324.77
➡️ Equity Curve R²: 0.1895
➡️ Monthly Consistency Score: 0.0367

=== [1591/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.03it/s]
Hypertuning:  46%|████▌     | 1591/3456 [37:20<41:32,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.0219
➡️ Total Profit: ₹-863.75
➡️ Equity Curve R²: 0.4836
➡️ Monthly Consistency Score: -0.0033

=== [1592/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.67it/s]
Hypertuning:  46%|████▌     | 1592/3456 [37:22<41:44,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.0431
➡️ Total Profit: ₹-1,847.84
➡️ Equity Curve R²: 0.3428
➡️ Monthly Consistency Score: -0.0082

=== [1593/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.89it/s]
Hypertuning:  46%|████▌     | 1593/3456 [37:23<42:32,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.9004
➡️ Total Profit: ₹22,239.78
➡️ Equity Curve R²: 0.0414
➡️ Monthly Consistency Score: 0.0812

=== [1594/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.60it/s]
Hypertuning:  46%|████▌     | 1594/3456 [37:25<42:05,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.4630
➡️ Total Profit: ₹50,083.13
➡️ Equity Curve R²: 0.3330
➡️ Monthly Consistency Score: 0.1921

=== [1595/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.12it/s]
Hypertuning:  46%|████▌     | 1595/3456 [37:26<41:25,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.3586
➡️ Total Profit: ₹-16,125.59
➡️ Equity Curve R²: 0.7439
➡️ Monthly Consistency Score: -0.0629

=== [1596/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.27it/s]
Hypertuning:  46%|████▌     | 1596/3456 [37:27<41:42,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1898
➡️ Total Profit: ₹-10,817.00
➡️ Equity Curve R²: 0.7321
➡️ Monthly Consistency Score: -0.0418

=== [1597/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.77it/s]
Hypertuning:  46%|████▌     | 1597/3456 [37:28<41:30,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.9965
➡️ Total Profit: ₹24,488.25
➡️ Equity Curve R²: 0.0923
➡️ Monthly Consistency Score: 0.0934

=== [1598/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.77it/s]
Hypertuning:  46%|████▌     | 1598/3456 [37:30<41:53,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.4276
➡️ Total Profit: ₹85,223.80
➡️ Equity Curve R²: 0.6108
➡️ Monthly Consistency Score: 0.3875

=== [1599/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.24it/s]
Hypertuning:  46%|████▋     | 1599/3456 [37:31<42:24,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.2241
➡️ Total Profit: ₹45,367.06
➡️ Equity Curve R²: 0.0013
➡️ Monthly Consistency Score: 0.1770

=== [1600/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 130.60it/s]
Hypertuning:  46%|████▋     | 1600/3456 [37:33<41:47,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.1401
➡️ Total Profit: ₹56,384.65
➡️ Equity Curve R²: 0.3230
➡️ Monthly Consistency Score: 0.2666

=== [1601/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.38it/s]
Hypertuning:  46%|████▋     | 1601/3456 [37:34<42:27,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.6065
➡️ Total Profit: ₹-35,411.07
➡️ Equity Curve R²: 0.9179
➡️ Monthly Consistency Score: -0.1575

=== [1602/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.56it/s]
Hypertuning:  46%|████▋     | 1602/3456 [37:35<41:56,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0109
➡️ Total Profit: ₹328.77
➡️ Equity Curve R²: 0.4993
➡️ Monthly Consistency Score: 0.0014

=== [1603/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.29it/s]
Hypertuning:  46%|████▋     | 1603/3456 [37:37<41:16,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.2314
➡️ Total Profit: ₹6,428.07
➡️ Equity Curve R²: 0.0077
➡️ Monthly Consistency Score: 0.0271

=== [1604/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.51it/s]
Hypertuning:  46%|████▋     | 1604/3456 [37:38<41:35,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.5236
➡️ Total Profit: ₹11,795.27
➡️ Equity Curve R²: 0.1860
➡️ Monthly Consistency Score: 0.0479

=== [1605/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.74it/s]
Hypertuning:  46%|████▋     | 1605/3456 [37:39<41:23,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.3219
➡️ Total Profit: ₹8,830.21
➡️ Equity Curve R²: 0.1290
➡️ Monthly Consistency Score: 0.0313

=== [1606/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.76it/s]
Hypertuning:  46%|████▋     | 1606/3456 [37:41<41:44,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6780
➡️ Total Profit: ₹21,666.61
➡️ Equity Curve R²: 0.0478
➡️ Monthly Consistency Score: 0.0759

=== [1607/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.93it/s]
Hypertuning:  46%|████▋     | 1607/3456 [37:42<42:08,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.6380
➡️ Total Profit: ₹34,936.63
➡️ Equity Curve R²: 0.4015
➡️ Monthly Consistency Score: 0.1361

=== [1608/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.58it/s]
Hypertuning:  47%|████▋     | 1608/3456 [37:43<41:39,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0753
➡️ Total Profit: ₹-3,067.84
➡️ Equity Curve R²: 0.3091
➡️ Monthly Consistency Score: -0.0139

=== [1609/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.69it/s]
Hypertuning:  47%|████▋     | 1609/3456 [37:45<41:25,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.0026
➡️ Total Profit: ₹22,239.78
➡️ Equity Curve R²: 0.0290
➡️ Monthly Consistency Score: 0.0817

=== [1610/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.80it/s]
Hypertuning:  47%|████▋     | 1610/3456 [37:46<41:43,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.3519
➡️ Total Profit: ₹47,824.97
➡️ Equity Curve R²: 0.2053
➡️ Monthly Consistency Score: 0.1817

=== [1611/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.62it/s]
Hypertuning:  47%|████▋     | 1611/3456 [37:48<42:04,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.2383
➡️ Total Profit: ₹10,657.16
➡️ Equity Curve R²: 0.4284
➡️ Monthly Consistency Score: 0.0421

=== [1612/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.72it/s]
Hypertuning:  47%|████▋     | 1612/3456 [37:49<41:28,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1243
➡️ Total Profit: ₹-6,553.36
➡️ Equity Curve R²: 0.6516
➡️ Monthly Consistency Score: -0.0257

=== [1613/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.71it/s]
Hypertuning:  47%|████▋     | 1613/3456 [37:50<41:18,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.3647
➡️ Total Profit: ₹32,677.78
➡️ Equity Curve R²: 0.2666
➡️ Monthly Consistency Score: 0.1287

=== [1614/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.19it/s]
Hypertuning:  47%|████▋     | 1614/3456 [37:52<41:45,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.1795
➡️ Total Profit: ₹53,054.71
➡️ Equity Curve R²: 0.0373
➡️ Monthly Consistency Score: 0.2330

=== [1615/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.52it/s]
Hypertuning:  47%|████▋     | 1615/3456 [37:53<41:07,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.2241
➡️ Total Profit: ₹45,367.06
➡️ Equity Curve R²: 0.0013
➡️ Monthly Consistency Score: 0.1770

=== [1616/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.76it/s]
Hypertuning:  47%|████▋     | 1616/3456 [37:54<41:23,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.7457
➡️ Total Profit: ₹60,644.65
➡️ Equity Curve R²: 0.4625
➡️ Monthly Consistency Score: 0.2951

=== [1617/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.15it/s]
Hypertuning:  47%|████▋     | 1617/3456 [37:56<42:16,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.6349
➡️ Total Profit: ₹-36,044.08
➡️ Equity Curve R²: 0.8875
➡️ Monthly Consistency Score: -0.1630

=== [1618/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.21it/s]
Hypertuning:  47%|████▋     | 1618/3456 [37:57<41:47,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0766
➡️ Total Profit: ₹-3,669.47
➡️ Equity Curve R²: 0.5697
➡️ Monthly Consistency Score: -0.0149

=== [1619/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.82it/s]
Hypertuning:  47%|████▋     | 1619/3456 [37:58<42:14,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.0172
➡️ Total Profit: ₹-476.51
➡️ Equity Curve R²: 0.0686
➡️ Monthly Consistency Score: -0.0020

=== [1620/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.70it/s]
Hypertuning:  47%|████▋     | 1620/3456 [38:00<41:32,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4419
➡️ Total Profit: ₹8,926.03
➡️ Equity Curve R²: 0.2530
➡️ Monthly Consistency Score: 0.0386

=== [1621/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.53it/s]
Hypertuning:  47%|████▋     | 1621/3456 [38:01<41:09,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6114
➡️ Total Profit: ₹16,389.27
➡️ Equity Curve R²: 0.3639
➡️ Monthly Consistency Score: 0.0600

=== [1622/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.55it/s]
Hypertuning:  47%|████▋     | 1622/3456 [38:02<41:28,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.0815
➡️ Total Profit: ₹30,350.29
➡️ Equity Curve R²: 0.1172
➡️ Monthly Consistency Score: 0.1116

=== [1623/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.07it/s]
Hypertuning:  47%|████▋     | 1623/3456 [38:04<40:55,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.3764
➡️ Total Profit: ₹10,527.26
➡️ Equity Curve R²: 0.0130
➡️ Monthly Consistency Score: 0.0398

=== [1624/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.28it/s]
Hypertuning:  47%|████▋     | 1624/3456 [38:05<41:18,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6964
➡️ Total Profit: ₹18,230.21
➡️ Equity Curve R²: 0.1279
➡️ Monthly Consistency Score: 0.0811

=== [1625/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 111.52it/s]
Hypertuning:  47%|████▋     | 1625/3456 [38:07<42:05,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.2436
➡️ Total Profit: ₹26,017.90
➡️ Equity Curve R²: 0.1872
➡️ Monthly Consistency Score: 0.0963

=== [1626/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.20it/s]
Hypertuning:  47%|████▋     | 1626/3456 [38:08<41:39,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.0031
➡️ Total Profit: ₹84.69
➡️ Equity Curve R²: 0.1132
➡️ Monthly Consistency Score: 0.0003

=== [1627/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.99it/s]
Hypertuning:  47%|████▋     | 1627/3456 [38:09<41:59,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.3870
➡️ Total Profit: ₹15,548.53
➡️ Equity Curve R²: 0.2831
➡️ Monthly Consistency Score: 0.0643

=== [1628/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.92it/s]
Hypertuning:  47%|████▋     | 1628/3456 [38:11<41:19,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.8655
➡️ Total Profit: ₹27,799.29
➡️ Equity Curve R²: 0.0223
➡️ Monthly Consistency Score: 0.0985

=== [1629/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.77it/s]
Hypertuning:  47%|████▋     | 1629/3456 [38:12<41:03,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.8101
➡️ Total Profit: ₹26,379.66
➡️ Equity Curve R²: 0.0016
➡️ Monthly Consistency Score: 0.1020

=== [1630/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.09it/s]
Hypertuning:  47%|████▋     | 1630/3456 [38:13<41:19,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.9856
➡️ Total Profit: ₹49,368.17
➡️ Equity Curve R²: 0.2768
➡️ Monthly Consistency Score: 0.2099

=== [1631/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.69it/s]
Hypertuning:  47%|████▋     | 1631/3456 [38:15<40:47,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.2316
➡️ Total Profit: ₹43,741.17
➡️ Equity Curve R²: 0.0040
➡️ Monthly Consistency Score: 0.1776

=== [1632/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.74it/s]
Hypertuning:  47%|████▋     | 1632/3456 [38:16<41:00,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.9257
➡️ Total Profit: ₹60,644.65
➡️ Equity Curve R²: 0.4668
➡️ Monthly Consistency Score: 0.2867

=== [1633/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.82it/s]
Hypertuning:  47%|████▋     | 1633/3456 [38:17<40:43,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.3665
➡️ Total Profit: ₹-16,726.11
➡️ Equity Curve R²: 0.8564
➡️ Monthly Consistency Score: -0.0764

=== [1634/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.04it/s]
Hypertuning:  47%|████▋     | 1634/3456 [38:19<41:10,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2317
➡️ Total Profit: ₹-8,708.75
➡️ Equity Curve R²: 0.7423
➡️ Monthly Consistency Score: -0.0372

=== [1635/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.39it/s]
Hypertuning:  47%|████▋     | 1635/3456 [38:20<40:37,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.0592
➡️ Total Profit: ₹-2,895.62
➡️ Equity Curve R²: 0.6392
➡️ Monthly Consistency Score: -0.0104

=== [1636/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.15it/s]
Hypertuning:  47%|████▋     | 1636/3456 [38:21<41:01,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.3255
➡️ Total Profit: ₹44,575.27
➡️ Equity Curve R²: 0.8047
➡️ Monthly Consistency Score: 0.1676

=== [1637/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.07it/s]
Hypertuning:  47%|████▋     | 1637/3456 [38:23<40:45,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.2704
➡️ Total Profit: ₹-9,719.01
➡️ Equity Curve R²: 0.4968
➡️ Monthly Consistency Score: -0.0382

=== [1638/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.14it/s]
Hypertuning:  47%|████▋     | 1638/3456 [38:24<41:06,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0762
➡️ Total Profit: ₹3,667.21
➡️ Equity Curve R²: 0.1997
➡️ Monthly Consistency Score: 0.0128

=== [1639/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.99it/s]
Hypertuning:  47%|████▋     | 1639/3456 [38:25<40:34,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.2712
➡️ Total Profit: ₹25,172.78
➡️ Equity Curve R²: 0.4151
➡️ Monthly Consistency Score: 0.0955

=== [1640/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.71it/s]
Hypertuning:  47%|████▋     | 1640/3456 [38:27<40:52,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3107
➡️ Total Profit: ₹-12,191.40
➡️ Equity Curve R²: 0.6222
➡️ Monthly Consistency Score: -0.0492

=== [1641/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 129.47it/s]
Hypertuning:  47%|████▋     | 1641/3456 [38:28<40:31,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.6925
➡️ Total Profit: ₹17,267.13
➡️ Equity Curve R²: 0.0896
➡️ Monthly Consistency Score: 0.0622

=== [1642/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.50it/s]
Hypertuning:  48%|████▊     | 1642/3456 [38:29<40:51,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.5466
➡️ Total Profit: ₹21,563.29
➡️ Equity Curve R²: 0.0226
➡️ Monthly Consistency Score: 0.0715

=== [1643/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.29it/s]
Hypertuning:  48%|████▊     | 1643/3456 [38:31<41:15,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.4793
➡️ Total Profit: ₹50,474.42
➡️ Equity Curve R²: 0.2571
➡️ Monthly Consistency Score: 0.2142

=== [1644/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.15it/s]
Hypertuning:  48%|████▊     | 1644/3456 [38:32<40:43,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0287
➡️ Total Profit: ₹-1,814.18
➡️ Equity Curve R²: 0.6367
➡️ Monthly Consistency Score: -0.0068

=== [1645/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.48it/s]
Hypertuning:  48%|████▊     | 1645/3456 [38:34<40:39,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.4104
➡️ Total Profit: ₹37,312.82
➡️ Equity Curve R²: 0.5005
➡️ Monthly Consistency Score: 0.1413

=== [1646/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.52it/s]
Hypertuning:  48%|████▊     | 1646/3456 [38:35<40:57,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.8111
➡️ Total Profit: ₹38,061.25
➡️ Equity Curve R²: 0.0679
➡️ Monthly Consistency Score: 0.1448

=== [1647/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.87it/s]
Hypertuning:  48%|████▊     | 1647/3456 [38:36<40:27,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.6749
➡️ Total Profit: ₹64,924.32
➡️ Equity Curve R²: 0.3562
➡️ Monthly Consistency Score: 0.2767

=== [1648/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.07it/s]
Hypertuning:  48%|████▊     | 1648/3456 [38:38<40:41,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.5592
➡️ Total Profit: ₹60,648.29
➡️ Equity Curve R²: 0.5956
➡️ Monthly Consistency Score: 0.2638

=== [1649/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.21it/s]
Hypertuning:  48%|████▊     | 1649/3456 [38:39<41:30,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.2314
➡️ Total Profit: ₹-8,599.81
➡️ Equity Curve R²: 0.7857
➡️ Monthly Consistency Score: -0.0397

=== [1650/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.36it/s]
Hypertuning:  48%|████▊     | 1650/3456 [38:40<40:55,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1273
➡️ Total Profit: ₹3,200.25
➡️ Equity Curve R²: 0.3462
➡️ Monthly Consistency Score: 0.0153

=== [1651/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.23it/s]
Hypertuning:  48%|████▊     | 1651/3456 [38:42<41:07,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3365
➡️ Total Profit: ₹-15,606.22
➡️ Equity Curve R²: 0.7600
➡️ Monthly Consistency Score: -0.0587

=== [1652/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.82it/s]
Hypertuning:  48%|████▊     | 1652/3456 [38:43<40:25,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.5431
➡️ Total Profit: ₹48,746.23
➡️ Equity Curve R²: 0.7835
➡️ Monthly Consistency Score: 0.1834

=== [1653/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.36it/s]
Hypertuning:  48%|████▊     | 1653/3456 [38:44<41:18,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.1408
➡️ Total Profit: ₹4,432.40
➡️ Equity Curve R²: 0.0198
➡️ Monthly Consistency Score: 0.0165

=== [1654/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.14it/s]
Hypertuning:  48%|████▊     | 1654/3456 [38:46<41:01,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1811
➡️ Total Profit: ₹-8,687.52
➡️ Equity Curve R²: 0.7527
➡️ Monthly Consistency Score: -0.0326

=== [1655/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.28it/s]
Hypertuning:  48%|████▊     | 1655/3456 [38:47<41:20,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.4366
➡️ Total Profit: ₹28,412.41
➡️ Equity Curve R²: 0.5250
➡️ Monthly Consistency Score: 0.1079

=== [1656/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.85it/s]
Hypertuning:  48%|████▊     | 1656/3456 [38:49<40:49,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4787
➡️ Total Profit: ₹-19,803.22
➡️ Equity Curve R²: 0.7868
➡️ Monthly Consistency Score: -0.0814

=== [1657/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.93it/s]
Hypertuning:  48%|████▊     | 1657/3456 [38:50<40:32,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6673
➡️ Total Profit: ₹16,638.54
➡️ Equity Curve R²: 0.1049
➡️ Monthly Consistency Score: 0.0599

=== [1658/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.54it/s]
Hypertuning:  48%|████▊     | 1658/3456 [38:51<40:50,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0814
➡️ Total Profit: ₹3,395.89
➡️ Equity Curve R²: 0.1947
➡️ Monthly Consistency Score: 0.0110

=== [1659/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.93it/s]
Hypertuning:  48%|████▊     | 1659/3456 [38:53<40:52,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.3825
➡️ Total Profit: ₹50,474.42
➡️ Equity Curve R²: 0.2633
➡️ Monthly Consistency Score: 0.2131

=== [1660/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.31it/s]
Hypertuning:  48%|████▊     | 1660/3456 [38:54<40:17,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.0415
➡️ Total Profit: ₹2,445.82
➡️ Equity Curve R²: 0.5712
➡️ Monthly Consistency Score: 0.0093

=== [1661/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.58it/s]
Hypertuning:  48%|████▊     | 1661/3456 [38:55<40:56,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.6154
➡️ Total Profit: ₹41,721.41
➡️ Equity Curve R²: 0.5649
➡️ Monthly Consistency Score: 0.1609

=== [1662/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.37it/s]
Hypertuning:  48%|████▊     | 1662/3456 [38:57<40:37,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.1383
➡️ Total Profit: ₹63,444.82
➡️ Equity Curve R²: 0.3008
➡️ Monthly Consistency Score: 0.2343

=== [1663/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.67it/s]
Hypertuning:  48%|████▊     | 1663/3456 [38:58<41:11,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 4.4954
➡️ Total Profit: ₹87,929.81
➡️ Equity Curve R²: 0.8139
➡️ Monthly Consistency Score: 0.3610

=== [1664/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.14it/s]
Hypertuning:  48%|████▊     | 1664/3456 [38:59<40:40,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.5592
➡️ Total Profit: ₹60,648.29
➡️ Equity Curve R²: 0.5956
➡️ Monthly Consistency Score: 0.2638

=== [1665/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.56it/s]
Hypertuning:  48%|████▊     | 1665/3456 [39:01<41:17,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.2507
➡️ Total Profit: ₹-8,598.87
➡️ Equity Curve R²: 0.7790
➡️ Monthly Consistency Score: -0.0383

=== [1666/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.65it/s]
Hypertuning:  48%|████▊     | 1666/3456 [39:02<40:47,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.2192
➡️ Total Profit: ₹5,989.37
➡️ Equity Curve R²: 0.4196
➡️ Monthly Consistency Score: 0.0275

=== [1667/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.62it/s]
Hypertuning:  48%|████▊     | 1667/3456 [39:03<40:09,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.5629
➡️ Total Profit: ₹-33,924.91
➡️ Equity Curve R²: 0.9004
➡️ Monthly Consistency Score: -0.1245

=== [1668/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 101.74it/s]
Hypertuning:  48%|████▊     | 1668/3456 [39:05<40:25,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.1036
➡️ Total Profit: ₹59,490.74
➡️ Equity Curve R²: 0.9281
➡️ Monthly Consistency Score: 0.2222

=== [1669/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.63it/s]
Hypertuning:  48%|████▊     | 1669/3456 [39:06<40:53,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.4409
➡️ Total Profit: ₹13,249.58
➡️ Equity Curve R²: 0.0186
➡️ Monthly Consistency Score: 0.0496

=== [1670/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.10it/s]
Hypertuning:  48%|████▊     | 1670/3456 [39:08<40:21,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0841
➡️ Total Profit: ₹-3,814.87
➡️ Equity Curve R²: 0.7244
➡️ Monthly Consistency Score: -0.0144

=== [1671/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.68it/s]
Hypertuning:  48%|████▊     | 1671/3456 [39:09<40:38,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.3543
➡️ Total Profit: ₹26,783.78
➡️ Equity Curve R²: 0.4974
➡️ Monthly Consistency Score: 0.1015

=== [1672/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.94it/s]
Hypertuning:  48%|████▊     | 1672/3456 [39:10<40:12,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1244
➡️ Total Profit: ₹-3,064.20
➡️ Equity Curve R²: 0.1562
➡️ Monthly Consistency Score: -0.0121

=== [1673/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.64it/s]
Hypertuning:  48%|████▊     | 1673/3456 [39:12<40:42,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.7754
➡️ Total Profit: ₹24,706.19
➡️ Equity Curve R²: 0.0438
➡️ Monthly Consistency Score: 0.0942

=== [1674/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.72it/s]
Hypertuning:  48%|████▊     | 1674/3456 [39:13<41:03,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.0837
➡️ Total Profit: ₹3,395.89
➡️ Equity Curve R²: 0.2016
➡️ Monthly Consistency Score: 0.0122

=== [1675/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.01it/s]
Hypertuning:  48%|████▊     | 1675/3456 [39:14<40:20,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.0801
➡️ Total Profit: ₹32,548.53
➡️ Equity Curve R²: 0.0437
➡️ Monthly Consistency Score: 0.1242

=== [1676/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.27it/s]
Hypertuning:  48%|████▊     | 1676/3456 [39:16<39:42,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 3.1148
➡️ Total Profit: ₹61,874.01
➡️ Equity Curve R²: 0.5137
➡️ Monthly Consistency Score: 0.2422

=== [1677/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.92it/s]
Hypertuning:  49%|████▊     | 1677/3456 [39:17<40:16,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.5972
➡️ Total Profit: ₹65,440.56
➡️ Equity Curve R²: 0.5030
➡️ Monthly Consistency Score: 0.2773

=== [1678/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.85it/s]
Hypertuning:  49%|████▊     | 1678/3456 [39:18<39:47,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.5173
➡️ Total Profit: ₹49,359.41
➡️ Equity Curve R²: 0.0007
➡️ Monthly Consistency Score: 0.1924

=== [1679/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.38it/s]
Hypertuning:  49%|████▊     | 1679/3456 [39:20<39:55,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.3238
➡️ Total Profit: ₹40,663.91
➡️ Equity Curve R²: 0.1512
➡️ Monthly Consistency Score: 0.1399

=== [1680/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.87it/s]
Hypertuning:  49%|████▊     | 1680/3456 [39:21<40:26,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.5592
➡️ Total Profit: ₹60,648.29
➡️ Equity Curve R²: 0.5956
➡️ Monthly Consistency Score: 0.2638

=== [1681/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.95it/s]
Hypertuning:  49%|████▊     | 1681/3456 [39:23<40:17,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3092
➡️ Total Profit: ₹-12,945.17
➡️ Equity Curve R²: 0.8133
➡️ Monthly Consistency Score: -0.0593

=== [1682/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.62it/s]
Hypertuning:  49%|████▊     | 1682/3456 [39:24<40:42,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.1987
➡️ Total Profit: ₹-6,446.91
➡️ Equity Curve R²: 0.6530
➡️ Monthly Consistency Score: -0.0270

=== [1683/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.16it/s]
Hypertuning:  49%|████▊     | 1683/3456 [39:25<40:03,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0112
➡️ Total Profit: ₹-486.99
➡️ Equity Curve R²: 0.5963
➡️ Monthly Consistency Score: -0.0018

=== [1684/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.58it/s]
Hypertuning:  49%|████▊     | 1684/3456 [39:27<39:22,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 2.4705
➡️ Total Profit: ₹47,355.27
➡️ Equity Curve R²: 0.8002
➡️ Monthly Consistency Score: 0.1748

=== [1685/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.35it/s]
Hypertuning:  49%|████▉     | 1685/3456 [39:28<40:02,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2704
➡️ Total Profit: ₹-9,719.01
➡️ Equity Curve R²: 0.4968
➡️ Monthly Consistency Score: -0.0382

=== [1686/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.35it/s]
Hypertuning:  49%|████▉     | 1686/3456 [39:29<39:28,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.3179
➡️ Total Profit: ₹-17,372.80
➡️ Equity Curve R²: 0.7687
➡️ Monthly Consistency Score: -0.0588

=== [1687/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.62it/s]
Hypertuning:  49%|████▉     | 1687/3456 [39:31<39:38,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.2712
➡️ Total Profit: ₹25,172.78
➡️ Equity Curve R²: 0.4151
➡️ Monthly Consistency Score: 0.0955

=== [1688/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.25it/s]
Hypertuning:  49%|████▉     | 1688/3456 [39:32<39:58,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3107
➡️ Total Profit: ₹-12,191.40
➡️ Equity Curve R²: 0.6222
➡️ Monthly Consistency Score: -0.0492

=== [1689/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.67it/s]
Hypertuning:  49%|████▉     | 1689/3456 [39:33<39:55,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.6925
➡️ Total Profit: ₹17,267.13
➡️ Equity Curve R²: 0.0896
➡️ Monthly Consistency Score: 0.0622

=== [1690/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.91it/s]
Hypertuning:  49%|████▉     | 1690/3456 [39:35<39:35,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.5466
➡️ Total Profit: ₹21,563.29
➡️ Equity Curve R²: 0.0226
➡️ Monthly Consistency Score: 0.0715

=== [1691/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.41it/s]
Hypertuning:  49%|████▉     | 1691/3456 [39:36<39:57,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.4793
➡️ Total Profit: ₹50,474.42
➡️ Equity Curve R²: 0.2571
➡️ Monthly Consistency Score: 0.2142

=== [1692/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.79it/s]
Hypertuning:  49%|████▉     | 1692/3456 [39:37<40:15,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0287
➡️ Total Profit: ₹-1,814.18
➡️ Equity Curve R²: 0.6367
➡️ Monthly Consistency Score: -0.0068

=== [1693/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.61it/s]
Hypertuning:  49%|████▉     | 1693/3456 [39:39<39:57,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.4104
➡️ Total Profit: ₹37,312.82
➡️ Equity Curve R²: 0.5005
➡️ Monthly Consistency Score: 0.1413

=== [1694/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.67it/s]
Hypertuning:  49%|████▉     | 1694/3456 [39:40<39:23,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.2737
➡️ Total Profit: ₹62,317.58
➡️ Equity Curve R²: 0.3157
➡️ Monthly Consistency Score: 0.2372

=== [1695/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.97it/s]
Hypertuning:  49%|████▉     | 1695/3456 [39:41<39:35,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.6749
➡️ Total Profit: ₹64,924.32
➡️ Equity Curve R²: 0.3562
➡️ Monthly Consistency Score: 0.2767

=== [1696/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.29it/s]
Hypertuning:  49%|████▉     | 1696/3456 [39:43<38:55,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 3.5592
➡️ Total Profit: ₹60,648.29
➡️ Equity Curve R²: 0.5956
➡️ Monthly Consistency Score: 0.2638

=== [1697/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.61it/s]
Hypertuning:  49%|████▉     | 1697/3456 [39:44<39:35,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3072
➡️ Total Profit: ₹-10,837.60
➡️ Equity Curve R²: 0.8271
➡️ Monthly Consistency Score: -0.0517

=== [1698/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.18it/s]
Hypertuning:  49%|████▉     | 1698/3456 [39:46<40:07,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.4902
➡️ Total Profit: ₹9,467.53
➡️ Equity Curve R²: 0.0991
➡️ Monthly Consistency Score: 0.0443

=== [1699/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.04it/s]
Hypertuning:  49%|████▉     | 1699/3456 [39:47<39:32,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2584
➡️ Total Profit: ₹-10,717.59
➡️ Equity Curve R²: 0.6882
➡️ Monthly Consistency Score: -0.0409

=== [1700/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.55it/s]
Hypertuning:  49%|████▉     | 1700/3456 [39:48<40:18,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.5431
➡️ Total Profit: ₹48,746.23
➡️ Equity Curve R²: 0.7835
➡️ Monthly Consistency Score: 0.1834

=== [1701/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.11it/s]
Hypertuning:  49%|████▉     | 1701/3456 [39:50<39:57,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0497
➡️ Total Profit: ₹-1,532.30
➡️ Equity Curve R²: 0.2888
➡️ Monthly Consistency Score: -0.0061

=== [1702/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.07it/s]
Hypertuning:  49%|████▉     | 1702/3456 [39:51<40:13,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.3728
➡️ Total Profit: ₹-19,983.84
➡️ Equity Curve R²: 0.8026
➡️ Monthly Consistency Score: -0.0711

=== [1703/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.29it/s]
Hypertuning:  49%|████▉     | 1703/3456 [39:52<39:34,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.4366
➡️ Total Profit: ₹28,412.41
➡️ Equity Curve R²: 0.5250
➡️ Monthly Consistency Score: 0.1079

=== [1704/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.34it/s]
Hypertuning:  49%|████▉     | 1704/3456 [39:54<38:56,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: -0.4787
➡️ Total Profit: ₹-19,803.22
➡️ Equity Curve R²: 0.7868
➡️ Monthly Consistency Score: -0.0814

=== [1705/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.09it/s]
Hypertuning:  49%|████▉     | 1705/3456 [39:55<39:28,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.0636
➡️ Total Profit: ₹27,857.60
➡️ Equity Curve R²: 0.0129
➡️ Monthly Consistency Score: 0.1021

=== [1706/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.78it/s]
Hypertuning:  49%|████▉     | 1706/3456 [39:56<39:53,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.3451
➡️ Total Profit: ₹14,785.13
➡️ Equity Curve R²: 0.1975
➡️ Monthly Consistency Score: 0.0468

=== [1707/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.35it/s]
Hypertuning:  49%|████▉     | 1707/3456 [39:58<39:18,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.3700
➡️ Total Profit: ₹52,108.53
➡️ Equity Curve R²: 0.1789
➡️ Monthly Consistency Score: 0.2240

=== [1708/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.34it/s]
Hypertuning:  49%|████▉     | 1708/3456 [39:59<39:46,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.0777
➡️ Total Profit: ₹4,577.64
➡️ Equity Curve R²: 0.5520
➡️ Monthly Consistency Score: 0.0173

=== [1709/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.12it/s]
Hypertuning:  49%|████▉     | 1709/3456 [40:01<39:55,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.5094
➡️ Total Profit: ₹64,810.09
➡️ Equity Curve R²: 0.5081
➡️ Monthly Consistency Score: 0.2746

=== [1710/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.33it/s]
Hypertuning:  49%|████▉     | 1710/3456 [40:02<39:26,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.1539
➡️ Total Profit: ₹41,448.49
➡️ Equity Curve R²: 0.0089
➡️ Monthly Consistency Score: 0.1622

=== [1711/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.72it/s]
Hypertuning:  50%|████▉     | 1711/3456 [40:03<39:36,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.8916
➡️ Total Profit: ₹55,335.28
➡️ Equity Curve R²: 0.2147
➡️ Monthly Consistency Score: 0.1915

=== [1712/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.39it/s]
Hypertuning:  50%|████▉     | 1712/3456 [40:05<39:57,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.5592
➡️ Total Profit: ₹60,648.29
➡️ Equity Curve R²: 0.5956
➡️ Monthly Consistency Score: 0.2638

=== [1713/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.84it/s]
Hypertuning:  50%|████▉     | 1713/3456 [40:06<39:40,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.5690
➡️ Total Profit: ₹-24,065.91
➡️ Equity Curve R²: 0.8341
➡️ Monthly Consistency Score: -0.1124

=== [1714/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.14it/s]
Hypertuning:  50%|████▉     | 1714/3456 [40:07<40:24,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 0.4738
➡️ Total Profit: ₹10,509.53
➡️ Equity Curve R²: 0.1962
➡️ Monthly Consistency Score: 0.0473

=== [1715/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.38it/s]
Hypertuning:  50%|████▉     | 1715/3456 [40:09<39:44,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4356
➡️ Total Profit: ₹-20,879.43
➡️ Equity Curve R²: 0.8218
➡️ Monthly Consistency Score: -0.0760

=== [1716/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.10it/s]
Hypertuning:  50%|████▉     | 1716/3456 [40:10<39:01,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.1422
➡️ Total Profit: ₹60,229.88
➡️ Equity Curve R²: 0.8974
➡️ Monthly Consistency Score: 0.2194

=== [1717/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.85it/s]
Hypertuning:  50%|████▉     | 1717/3456 [40:11<40:00,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.4934
➡️ Total Profit: ₹15,140.05
➡️ Equity Curve R²: 0.0961
➡️ Monthly Consistency Score: 0.0578

=== [1718/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.50it/s]
Hypertuning:  50%|████▉     | 1718/3456 [40:13<39:21,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2302
➡️ Total Profit: ₹-11,298.32
➡️ Equity Curve R²: 0.7725
➡️ Monthly Consistency Score: -0.0439

=== [1719/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.44it/s]
Hypertuning:  50%|████▉     | 1719/3456 [40:14<39:29,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.2721
➡️ Total Profit: ₹25,157.89
➡️ Equity Curve R²: 0.5404
➡️ Monthly Consistency Score: 0.0928

=== [1720/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.56it/s]
Hypertuning:  50%|████▉     | 1720/3456 [40:15<38:52,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.2953
➡️ Total Profit: ₹-11,585.88
➡️ Equity Curve R²: 0.6647
➡️ Monthly Consistency Score: -0.0471

=== [1721/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.42it/s]
Hypertuning:  50%|████▉     | 1721/3456 [40:17<39:36,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.7865
➡️ Total Profit: ₹24,076.66
➡️ Equity Curve R²: 0.0298
➡️ Monthly Consistency Score: 0.0904

=== [1722/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.80it/s]
Hypertuning:  50%|████▉     | 1722/3456 [40:18<39:04,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2002
➡️ Total Profit: ₹-7,898.60
➡️ Equity Curve R²: 0.4503
➡️ Monthly Consistency Score: -0.0254

=== [1723/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 111.48it/s]
Hypertuning:  50%|████▉     | 1723/3456 [40:20<39:18,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.1472
➡️ Total Profit: ₹47,217.16
➡️ Equity Curve R²: 0.1720
➡️ Monthly Consistency Score: 0.2036

=== [1724/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.00it/s]
Hypertuning:  50%|████▉     | 1724/3456 [40:21<38:45,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 4.0312
➡️ Total Profit: ₹77,270.30
➡️ Equity Curve R²: 0.7942
➡️ Monthly Consistency Score: 0.3261

=== [1725/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.70it/s]
Hypertuning:  50%|████▉     | 1725/3456 [40:22<39:55,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.7665
➡️ Total Profit: ₹67,963.38
➡️ Equity Curve R²: 0.5610
➡️ Monthly Consistency Score: 0.2852

=== [1726/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.91it/s]
Hypertuning:  50%|████▉     | 1726/3456 [40:24<39:23,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.4923
➡️ Total Profit: ₹48,232.17
➡️ Equity Curve R²: 0.0003
➡️ Monthly Consistency Score: 0.1893

=== [1727/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.32it/s]
Hypertuning:  50%|████▉     | 1727/3456 [40:25<39:36,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.3768
➡️ Total Profit: ₹42,292.54
➡️ Equity Curve R²: 0.1757
➡️ Monthly Consistency Score: 0.1446

=== [1728/3456] Testing Parameters ===
smooth_length: 10
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.84it/s]
Hypertuning:  50%|█████     | 1728/3456 [40:26<38:48,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.5592
➡️ Total Profit: ₹60,648.29
➡️ Equity Curve R²: 0.5956
➡️ Monthly Consistency Score: 0.2612

=== [1729/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.49it/s]
Hypertuning:  50%|█████     | 1729/3456 [40:28<39:33,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.7136
➡️ Total Profit: ₹-55,035.00
➡️ Equity Curve R²: 0.9619
➡️ Monthly Consistency Score: -0.2256

=== [1730/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.06it/s]
Hypertuning:  50%|█████     | 1730/3456 [40:29<39:47,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.4608
➡️ Total Profit: ₹-29,133.12
➡️ Equity Curve R²: 0.9305
➡️ Monthly Consistency Score: -0.1197

=== [1731/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.67it/s]
Hypertuning:  50%|█████     | 1731/3456 [40:31<39:09,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.8462
➡️ Total Profit: ₹25,732.41
➡️ Equity Curve R²: 0.0000
➡️ Monthly Consistency Score: 0.0984

=== [1732/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.90it/s]
Hypertuning:  50%|█████     | 1732/3456 [40:32<38:32,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.1293
➡️ Total Profit: ₹-5,969.52
➡️ Equity Curve R²: 0.6317
➡️ Monthly Consistency Score: -0.0217

=== [1733/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.98it/s]
Hypertuning:  50%|█████     | 1733/3456 [40:33<39:05,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.7380
➡️ Total Profit: ₹18,979.49
➡️ Equity Curve R²: 0.4977
➡️ Monthly Consistency Score: 0.0650

=== [1734/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.31it/s]
Hypertuning:  50%|█████     | 1734/3456 [40:35<39:27,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.4487
➡️ Total Profit: ₹11,233.73
➡️ Equity Curve R²: 0.0096
➡️ Monthly Consistency Score: 0.0412

=== [1735/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.04it/s]
Hypertuning:  50%|█████     | 1735/3456 [40:36<38:57,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.1810
➡️ Total Profit: ₹25,111.15
➡️ Equity Curve R²: 0.3961
➡️ Monthly Consistency Score: 0.0916

=== [1736/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.37it/s]
Hypertuning:  50%|█████     | 1736/3456 [40:37<38:31,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.0110
➡️ Total Profit: ₹282.02
➡️ Equity Curve R²: 0.0291
➡️ Monthly Consistency Score: 0.0010

=== [1737/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.46it/s]
Hypertuning:  50%|█████     | 1737/3456 [40:39<39:11,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0979
➡️ Total Profit: ₹-4,281.33
➡️ Equity Curve R²: 0.3220
➡️ Monthly Consistency Score: -0.0149

=== [1738/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.18it/s]
Hypertuning:  50%|█████     | 1738/3456 [40:40<38:44,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4736
➡️ Total Profit: ₹14,602.97
➡️ Equity Curve R²: 0.1486
➡️ Monthly Consistency Score: 0.0582

=== [1739/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.16it/s]
Hypertuning:  50%|█████     | 1739/3456 [40:41<38:52,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.5728
➡️ Total Profit: ₹-36,029.31
➡️ Equity Curve R²: 0.8770
➡️ Monthly Consistency Score: -0.1378

=== [1740/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.57it/s]
Hypertuning:  50%|█████     | 1740/3456 [40:43<39:11,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3807
➡️ Total Profit: ₹-16,738.92
➡️ Equity Curve R²: 0.6886
➡️ Monthly Consistency Score: -0.0608

=== [1741/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.60it/s]
Hypertuning:  50%|█████     | 1741/3456 [40:44<39:30,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.2223
➡️ Total Profit: ₹53,679.67
➡️ Equity Curve R²: 0.3099
➡️ Monthly Consistency Score: 0.1982

=== [1742/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.01it/s]
Hypertuning:  50%|█████     | 1742/3456 [40:45<38:53,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.6066
➡️ Total Profit: ₹62,089.19
➡️ Equity Curve R²: 0.2702
➡️ Monthly Consistency Score: 0.2586

=== [1743/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.57it/s]
Hypertuning:  50%|█████     | 1743/3456 [40:47<38:59,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.7899
➡️ Total Profit: ₹37,131.93
➡️ Equity Curve R²: 0.2205
➡️ Monthly Consistency Score: 0.1508

=== [1744/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.63it/s]
Hypertuning:  50%|█████     | 1744/3456 [40:48<38:31,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.6406
➡️ Total Profit: ₹64,901.01
➡️ Equity Curve R²: 0.6557
➡️ Monthly Consistency Score: 0.3191

=== [1745/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.96it/s]
Hypertuning:  50%|█████     | 1745/3456 [40:50<39:14,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.6179
➡️ Total Profit: ₹-42,713.73
➡️ Equity Curve R²: 0.9319
➡️ Monthly Consistency Score: -0.1743

=== [1746/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.13it/s]
Hypertuning:  51%|█████     | 1746/3456 [40:51<39:29,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.1697
➡️ Total Profit: ₹-6,969.47
➡️ Equity Curve R²: 0.6515
➡️ Monthly Consistency Score: -0.0289

=== [1747/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.33it/s]
Hypertuning:  51%|█████     | 1747/3456 [40:52<38:48,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.8643
➡️ Total Profit: ₹28,149.14
➡️ Equity Curve R²: 0.0006
➡️ Monthly Consistency Score: 0.1108

=== [1748/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.28it/s]
Hypertuning:  51%|█████     | 1748/3456 [40:54<38:13,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.1293
➡️ Total Profit: ₹-5,969.52
➡️ Equity Curve R²: 0.6317
➡️ Monthly Consistency Score: -0.0217

=== [1749/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.08it/s]
Hypertuning:  51%|█████     | 1749/3456 [40:55<39:04,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.6043
➡️ Total Profit: ₹15,542.31
➡️ Equity Curve R²: 0.4111
➡️ Monthly Consistency Score: 0.0549

=== [1750/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.12it/s]
Hypertuning:  51%|█████     | 1750/3456 [40:56<39:25,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 0.3994
➡️ Total Profit: ₹10,452.01
➡️ Equity Curve R²: 0.0005
➡️ Monthly Consistency Score: 0.0396

=== [1751/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.76it/s]
Hypertuning:  51%|█████     | 1751/3456 [40:58<38:46,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.4876
➡️ Total Profit: ₹31,631.15
➡️ Equity Curve R²: 0.5127
➡️ Monthly Consistency Score: 0.1150

=== [1752/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.33it/s]
Hypertuning:  51%|█████     | 1752/3456 [40:59<38:07,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.3467
➡️ Total Profit: ₹-13,714.34
➡️ Equity Curve R²: 0.5589
➡️ Monthly Consistency Score: -0.0507

=== [1753/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.27it/s]
Hypertuning:  51%|█████     | 1753/3456 [41:01<38:57,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1249
➡️ Total Profit: ₹-5,540.39
➡️ Equity Curve R²: 0.3194
➡️ Monthly Consistency Score: -0.0193

=== [1754/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.48it/s]
Hypertuning:  51%|█████     | 1754/3456 [41:02<38:31,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4736
➡️ Total Profit: ₹14,602.97
➡️ Equity Curve R²: 0.1486
➡️ Monthly Consistency Score: 0.0582

=== [1755/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.01it/s]
Hypertuning:  51%|█████     | 1755/3456 [41:03<38:46,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.5109
➡️ Total Profit: ₹-29,509.31
➡️ Equity Curve R²: 0.8106
➡️ Monthly Consistency Score: -0.1118

=== [1756/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.84it/s]
Hypertuning:  51%|█████     | 1756/3456 [41:05<38:12,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3491
➡️ Total Profit: ₹-14,607.10
➡️ Equity Curve R²: 0.6382
➡️ Monthly Consistency Score: -0.0547

=== [1757/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.71it/s]
Hypertuning:  51%|█████     | 1757/3456 [41:06<38:48,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.2484
➡️ Total Profit: ₹54,310.14
➡️ Equity Curve R²: 0.3285
➡️ Monthly Consistency Score: 0.2027

=== [1758/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.97it/s]
Hypertuning:  51%|█████     | 1758/3456 [41:07<38:19,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.0341
➡️ Total Profit: ₹53,049.19
➡️ Equity Curve R²: 0.2279
➡️ Monthly Consistency Score: 0.2193

=== [1759/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.89it/s]
Hypertuning:  51%|█████     | 1759/3456 [41:09<38:32,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.1441
➡️ Total Profit: ₹50,354.67
➡️ Equity Curve R²: 0.0037
➡️ Monthly Consistency Score: 0.1865

=== [1760/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.79it/s]
Hypertuning:  51%|█████     | 1760/3456 [41:10<37:54,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 3.8115
➡️ Total Profit: ₹62,769.19
➡️ Equity Curve R²: 0.6447
➡️ Monthly Consistency Score: 0.2939

=== [1761/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.89it/s]
Hypertuning:  51%|█████     | 1761/3456 [41:11<38:29,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.7070
➡️ Total Profit: ₹-57,834.95
➡️ Equity Curve R²: 0.9545
➡️ Monthly Consistency Score: -0.2351

=== [1762/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.16it/s]
Hypertuning:  51%|█████     | 1762/3456 [41:13<39:16,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.5184
➡️ Total Profit: ₹-34,260.44
➡️ Equity Curve R²: 0.9462
➡️ Monthly Consistency Score: -0.1405

=== [1763/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.19it/s]
Hypertuning:  51%|█████     | 1763/3456 [41:14<38:41,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1753
➡️ Total Profit: ₹30,162.35
➡️ Equity Curve R²: 0.1297
➡️ Monthly Consistency Score: 0.1216

=== [1764/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.48it/s]
Hypertuning:  51%|█████     | 1764/3456 [41:15<38:06,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.0178
➡️ Total Profit: ₹416.75
➡️ Equity Curve R²: 0.0775
➡️ Monthly Consistency Score: 0.0016

=== [1765/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.03it/s]
Hypertuning:  51%|█████     | 1765/3456 [41:17<38:34,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.6454
➡️ Total Profit: ₹-26,751.10
➡️ Equity Curve R²: 0.8474
➡️ Monthly Consistency Score: -0.0915

=== [1766/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.80it/s]
Hypertuning:  51%|█████     | 1766/3456 [41:18<39:08,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 0.2334
➡️ Total Profit: ₹6,717.41
➡️ Equity Curve R²: 0.0601
➡️ Monthly Consistency Score: 0.0249

=== [1767/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.19it/s]
Hypertuning:  51%|█████     | 1767/3456 [41:20<38:36,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.7585
➡️ Total Profit: ₹31,659.74
➡️ Equity Curve R²: 0.6054
➡️ Monthly Consistency Score: 0.1243

=== [1768/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.16it/s]
Hypertuning:  51%|█████     | 1768/3456 [41:21<38:54,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.0338
➡️ Total Profit: ₹1,193.84
➡️ Equity Curve R²: 0.1836
➡️ Monthly Consistency Score: 0.0044

=== [1769/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.86it/s]
Hypertuning:  51%|█████     | 1769/3456 [41:22<38:36,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3295
➡️ Total Profit: ₹-16,255.56
➡️ Equity Curve R²: 0.6715
➡️ Monthly Consistency Score: -0.0557

=== [1770/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.27it/s]
Hypertuning:  51%|█████     | 1770/3456 [41:24<38:10,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.8613
➡️ Total Profit: ₹20,433.89
➡️ Equity Curve R²: 0.0142
➡️ Monthly Consistency Score: 0.0784

=== [1771/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.34it/s]
Hypertuning:  51%|█████     | 1771/3456 [41:25<38:19,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4452
➡️ Total Profit: ₹-21,357.94
➡️ Equity Curve R²: 0.7966
➡️ Monthly Consistency Score: -0.0813

=== [1772/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.24it/s]
Hypertuning:  51%|█████▏    | 1772/3456 [41:27<38:41,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.2081
➡️ Total Profit: ₹-8,215.28
➡️ Equity Curve R²: 0.5346
➡️ Monthly Consistency Score: -0.0313

=== [1773/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.89it/s]
Hypertuning:  51%|█████▏    | 1773/3456 [41:28<38:43,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.0368
➡️ Total Profit: ₹53,050.14
➡️ Equity Curve R²: 0.2482
➡️ Monthly Consistency Score: 0.1983

=== [1774/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.93it/s]
Hypertuning:  51%|█████▏    | 1774/3456 [41:29<38:19,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.7233
➡️ Total Profit: ₹50,787.35
➡️ Equity Curve R²: 0.1440
➡️ Monthly Consistency Score: 0.2061

=== [1775/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.13it/s]
Hypertuning:  51%|█████▏    | 1775/3456 [41:31<38:23,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.9234
➡️ Total Profit: ₹40,394.67
➡️ Equity Curve R²: 0.0714
➡️ Monthly Consistency Score: 0.1701

=== [1776/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.22it/s]
Hypertuning:  51%|█████▏    | 1776/3456 [41:32<37:47,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.6406
➡️ Total Profit: ₹64,901.01
➡️ Equity Curve R²: 0.6557
➡️ Monthly Consistency Score: 0.3191

=== [1777/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.95it/s]
Hypertuning:  51%|█████▏    | 1777/3456 [41:33<38:20,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.7128
➡️ Total Profit: ₹-53,423.26
➡️ Equity Curve R²: 0.9590
➡️ Monthly Consistency Score: -0.2211

=== [1778/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.22it/s]
Hypertuning:  51%|█████▏    | 1778/3456 [41:35<37:46,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3406
➡️ Total Profit: ₹-20,614.87
➡️ Equity Curve R²: 0.9107
➡️ Monthly Consistency Score: -0.0822

=== [1779/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.86it/s]
Hypertuning:  51%|█████▏    | 1779/3456 [41:36<37:58,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.8462
➡️ Total Profit: ₹25,732.41
➡️ Equity Curve R²: 0.0000
➡️ Monthly Consistency Score: 0.0984

=== [1780/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.46it/s]
Hypertuning:  52%|█████▏    | 1780/3456 [41:37<37:27,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.1234
➡️ Total Profit: ₹-5,324.98
➡️ Equity Curve R²: 0.5978
➡️ Monthly Consistency Score: -0.0201

=== [1781/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.55it/s]
Hypertuning:  52%|█████▏    | 1781/3456 [41:39<38:05,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.7380
➡️ Total Profit: ₹18,979.49
➡️ Equity Curve R²: 0.4977
➡️ Monthly Consistency Score: 0.0650

=== [1782/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.99it/s]
Hypertuning:  52%|█████▏    | 1782/3456 [41:40<38:49,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 0.7023
➡️ Total Profit: ₹17,582.81
➡️ Equity Curve R²: 0.0162
➡️ Monthly Consistency Score: 0.0637

=== [1783/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.57it/s]
Hypertuning:  52%|█████▏    | 1783/3456 [41:42<38:10,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1810
➡️ Total Profit: ₹25,111.15
➡️ Equity Curve R²: 0.3961
➡️ Monthly Consistency Score: 0.0916

=== [1784/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.49it/s]
Hypertuning:  52%|█████▏    | 1784/3456 [41:43<37:31,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.0110
➡️ Total Profit: ₹282.02
➡️ Equity Curve R²: 0.0291
➡️ Monthly Consistency Score: 0.0010

=== [1785/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.81it/s]
Hypertuning:  52%|█████▏    | 1785/3456 [41:44<38:27,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.0979
➡️ Total Profit: ₹-4,281.33
➡️ Equity Curve R²: 0.3220
➡️ Monthly Consistency Score: -0.0149

=== [1786/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.68it/s]
Hypertuning:  52%|█████▏    | 1786/3456 [41:46<37:46,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4736
➡️ Total Profit: ₹14,602.97
➡️ Equity Curve R²: 0.1486
➡️ Monthly Consistency Score: 0.0582

=== [1787/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.31it/s]
Hypertuning:  52%|█████▏    | 1787/3456 [41:47<37:49,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.5728
➡️ Total Profit: ₹-36,029.31
➡️ Equity Curve R²: 0.8770
➡️ Monthly Consistency Score: -0.1342

=== [1788/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.55it/s]
Hypertuning:  52%|█████▏    | 1788/3456 [41:48<38:09,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3807
➡️ Total Profit: ₹-16,738.92
➡️ Equity Curve R²: 0.6886
➡️ Monthly Consistency Score: -0.0608

=== [1789/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.36it/s]
Hypertuning:  52%|█████▏    | 1789/3456 [41:50<38:20,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.2932
➡️ Total Profit: ₹45,912.95
➡️ Equity Curve R²: 0.0060
➡️ Monthly Consistency Score: 0.1883

=== [1790/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.35it/s]
Hypertuning:  52%|█████▏    | 1790/3456 [41:51<38:44,  1.40s/it]

➡️ Profit-to-Drawdown Ratio: 0.8968
➡️ Total Profit: ₹40,618.27
➡️ Equity Curve R²: 0.0852
➡️ Monthly Consistency Score: 0.1618

=== [1791/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.17it/s]
Hypertuning:  52%|█████▏    | 1791/3456 [41:52<38:06,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.7299
➡️ Total Profit: ₹35,503.30
➡️ Equity Curve R²: 0.2572
➡️ Monthly Consistency Score: 0.1436

=== [1792/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.20it/s]
Hypertuning:  52%|█████▏    | 1792/3456 [41:54<37:25,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.6406
➡️ Total Profit: ₹64,901.01
➡️ Equity Curve R²: 0.6557
➡️ Monthly Consistency Score: 0.3191

=== [1793/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.23it/s]
Hypertuning:  52%|█████▏    | 1793/3456 [41:55<37:55,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.6462
➡️ Total Profit: ₹-47,472.46
➡️ Equity Curve R²: 0.9450
➡️ Monthly Consistency Score: -0.1992

=== [1794/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.85it/s]
Hypertuning:  52%|█████▏    | 1794/3456 [41:57<38:16,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.4429
➡️ Total Profit: ₹-28,004.04
➡️ Equity Curve R²: 0.9276
➡️ Monthly Consistency Score: -0.1131

=== [1795/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.89it/s]
Hypertuning:  52%|█████▏    | 1795/3456 [41:58<37:40,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.4471
➡️ Total Profit: ₹35,905.09
➡️ Equity Curve R²: 0.2671
➡️ Monthly Consistency Score: 0.1460

=== [1796/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.87it/s]
Hypertuning:  52%|█████▏    | 1796/3456 [41:59<37:04,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.3975
➡️ Total Profit: ₹-14,576.84
➡️ Equity Curve R²: 0.6466
➡️ Monthly Consistency Score: -0.0528

=== [1797/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.28it/s]
Hypertuning:  52%|█████▏    | 1797/3456 [42:01<37:43,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.5639
➡️ Total Profit: ₹-22,044.52
➡️ Equity Curve R²: 0.8157
➡️ Monthly Consistency Score: -0.0774

=== [1798/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.28it/s]
Hypertuning:  52%|█████▏    | 1798/3456 [42:02<37:26,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2460
➡️ Total Profit: ₹7,759.25
➡️ Equity Curve R²: 0.0635
➡️ Monthly Consistency Score: 0.0281

=== [1799/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.16it/s]
Hypertuning:  52%|█████▏    | 1799/3456 [42:03<37:38,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.6681
➡️ Total Profit: ₹30,031.11
➡️ Equity Curve R²: 0.5518
➡️ Monthly Consistency Score: 0.1174

=== [1800/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.48it/s]
Hypertuning:  52%|█████▏    | 1800/3456 [42:05<37:13,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.0338
➡️ Total Profit: ₹1,193.84
➡️ Equity Curve R²: 0.1836
➡️ Monthly Consistency Score: 0.0044

=== [1801/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.77it/s]
Hypertuning:  52%|█████▏    | 1801/3456 [42:06<37:51,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3308
➡️ Total Profit: ₹-16,251.80
➡️ Equity Curve R²: 0.6778
➡️ Monthly Consistency Score: -0.0567

=== [1802/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.33it/s]
Hypertuning:  52%|█████▏    | 1802/3456 [42:07<37:47,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.4736
➡️ Total Profit: ₹14,602.97
➡️ Equity Curve R²: 0.1486
➡️ Monthly Consistency Score: 0.0582

=== [1803/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.17it/s]
Hypertuning:  52%|█████▏    | 1803/3456 [42:09<37:52,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.5291
➡️ Total Profit: ₹-26,246.57
➡️ Equity Curve R²: 0.7877
➡️ Monthly Consistency Score: -0.1001

=== [1804/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.55it/s]
Hypertuning:  52%|█████▏    | 1804/3456 [42:10<37:17,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3143
➡️ Total Profit: ₹-12,478.92
➡️ Equity Curve R²: 0.5895
➡️ Monthly Consistency Score: -0.0458

=== [1805/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.25it/s]
Hypertuning:  52%|█████▏    | 1805/3456 [42:12<37:47,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.2745
➡️ Total Profit: ₹54,940.61
➡️ Equity Curve R²: 0.3253
➡️ Monthly Consistency Score: 0.2049

=== [1806/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.50it/s]
Hypertuning:  52%|█████▏    | 1806/3456 [42:13<37:14,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.2745
➡️ Total Profit: ₹54,178.27
➡️ Equity Curve R²: 0.3294
➡️ Monthly Consistency Score: 0.2272

=== [1807/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.79it/s]
Hypertuning:  52%|█████▏    | 1807/3456 [42:14<37:25,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.7553
➡️ Total Profit: ₹35,506.04
➡️ Equity Curve R²: 0.1669
➡️ Monthly Consistency Score: 0.1472

=== [1808/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.82it/s]
Hypertuning:  52%|█████▏    | 1808/3456 [42:16<36:49,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 3.6406
➡️ Total Profit: ₹64,901.01
➡️ Equity Curve R²: 0.6557
➡️ Monthly Consistency Score: 0.3191

=== [1809/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.42it/s]
Hypertuning:  52%|█████▏    | 1809/3456 [42:17<37:32,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.7277
➡️ Total Profit: ₹-60,697.57
➡️ Equity Curve R²: 0.9598
➡️ Monthly Consistency Score: -0.2607

=== [1810/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.86it/s]
Hypertuning:  52%|█████▏    | 1810/3456 [42:18<37:03,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.5201
➡️ Total Profit: ₹-34,962.20
➡️ Equity Curve R²: 0.9221
➡️ Monthly Consistency Score: -0.1466

=== [1811/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.42it/s]
Hypertuning:  52%|█████▏    | 1811/3456 [42:20<37:16,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4344
➡️ Total Profit: ₹-21,736.88
➡️ Equity Curve R²: 0.8339
➡️ Monthly Consistency Score: -0.0922

=== [1812/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 110.86it/s]
Hypertuning:  52%|█████▏    | 1812/3456 [42:21<36:43,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.4159
➡️ Total Profit: ₹10,324.07
➡️ Equity Curve R²: 0.1824
➡️ Monthly Consistency Score: 0.0397

=== [1813/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.81it/s]
Hypertuning:  52%|█████▏    | 1813/3456 [42:22<37:20,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4987
➡️ Total Profit: ₹-18,561.57
➡️ Equity Curve R²: 0.7995
➡️ Monthly Consistency Score: -0.0642

=== [1814/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 111.22it/s]
Hypertuning:  52%|█████▏    | 1814/3456 [42:24<37:43,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.0478
➡️ Total Profit: ₹-1,900.63
➡️ Equity Curve R²: 0.5633
➡️ Monthly Consistency Score: -0.0072

=== [1815/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.52it/s]
Hypertuning:  53%|█████▎    | 1815/3456 [42:25<37:13,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.5784
➡️ Total Profit: ₹28,302.85
➡️ Equity Curve R²: 0.4556
➡️ Monthly Consistency Score: 0.1052

=== [1816/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.86it/s]
Hypertuning:  53%|█████▎    | 1816/3456 [42:26<36:40,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.2075
➡️ Total Profit: ₹-7,322.52
➡️ Equity Curve R²: 0.3248
➡️ Monthly Consistency Score: -0.0265

=== [1817/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.79it/s]
Hypertuning:  53%|█████▎    | 1817/3456 [42:28<37:24,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3391
➡️ Total Profit: ₹-17,514.62
➡️ Equity Curve R²: 0.7645
➡️ Monthly Consistency Score: -0.0596

=== [1818/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.32it/s]
Hypertuning:  53%|█████▎    | 1818/3456 [42:29<37:00,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0761
➡️ Total Profit: ₹2,088.32
➡️ Equity Curve R²: 0.1584
➡️ Monthly Consistency Score: 0.0084

=== [1819/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.95it/s]
Hypertuning:  53%|█████▎    | 1819/3456 [42:31<37:11,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.6676
➡️ Total Profit: ₹-47,437.95
➡️ Equity Curve R²: 0.9019
➡️ Monthly Consistency Score: -0.1790

=== [1820/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.94it/s]
Hypertuning:  53%|█████▎    | 1820/3456 [42:32<36:33,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.3102
➡️ Total Profit: ₹-12,475.28
➡️ Equity Curve R²: 0.5394
➡️ Monthly Consistency Score: -0.0472

=== [1821/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.29it/s]
Hypertuning:  53%|█████▎    | 1821/3456 [42:33<37:09,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.7996
➡️ Total Profit: ₹53,677.79
➡️ Equity Curve R²: 0.1065
➡️ Monthly Consistency Score: 0.1944

=== [1822/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.52it/s]
Hypertuning:  53%|█████▎    | 1822/3456 [42:35<37:35,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.1641
➡️ Total Profit: ₹56,438.27
➡️ Equity Curve R²: 0.2513
➡️ Monthly Consistency Score: 0.2333

=== [1823/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.84it/s]
Hypertuning:  53%|█████▎    | 1823/3456 [42:36<36:58,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.8847
➡️ Total Profit: ₹38,940.56
➡️ Equity Curve R²: 0.0716
➡️ Monthly Consistency Score: 0.1524

=== [1824/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.94it/s]
Hypertuning:  53%|█████▎    | 1824/3456 [42:37<37:18,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.9667
➡️ Total Profit: ₹39,337.37
➡️ Equity Curve R²: 0.0138
➡️ Monthly Consistency Score: 0.1690

=== [1825/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.14it/s]
Hypertuning:  53%|█████▎    | 1825/3456 [42:39<37:04,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.6325
➡️ Total Profit: ₹-49,771.42
➡️ Equity Curve R²: 0.9215
➡️ Monthly Consistency Score: -0.2084

=== [1826/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.15it/s]
Hypertuning:  53%|█████▎    | 1826/3456 [42:40<36:35,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2529
➡️ Total Profit: ₹-11,571.03
➡️ Equity Curve R²: 0.8158
➡️ Monthly Consistency Score: -0.0478

=== [1827/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.65it/s]
Hypertuning:  53%|█████▎    | 1827/3456 [42:41<36:48,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.3829
➡️ Total Profit: ₹17,908.19
➡️ Equity Curve R²: 0.2727
➡️ Monthly Consistency Score: 0.0628

=== [1828/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.51it/s]
Hypertuning:  53%|█████▎    | 1828/3456 [42:43<36:17,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.3020
➡️ Total Profit: ₹9,665.37
➡️ Equity Curve R²: 0.1774
➡️ Monthly Consistency Score: 0.0363

=== [1829/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.24it/s]
Hypertuning:  53%|█████▎    | 1829/3456 [42:44<36:46,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3221
➡️ Total Profit: ₹-11,785.84
➡️ Equity Curve R²: 0.6297
➡️ Monthly Consistency Score: -0.0413

=== [1830/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.26it/s]
Hypertuning:  53%|█████▎    | 1830/3456 [42:46<37:02,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1651
➡️ Total Profit: ₹19,848.57
➡️ Equity Curve R²: 0.5133
➡️ Monthly Consistency Score: 0.0794

=== [1831/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.07it/s]
Hypertuning:  53%|█████▎    | 1831/3456 [42:47<36:27,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.7805
➡️ Total Profit: ₹34,913.52
➡️ Equity Curve R²: 0.7112
➡️ Monthly Consistency Score: 0.1387

=== [1832/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.75it/s]
Hypertuning:  53%|█████▎    | 1832/3456 [42:48<36:50,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0500
➡️ Total Profit: ₹-1,231.40
➡️ Equity Curve R²: 0.0597
➡️ Monthly Consistency Score: -0.0053

=== [1833/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.59it/s]
Hypertuning:  53%|█████▎    | 1833/3456 [42:50<36:34,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0482
➡️ Total Profit: ₹-2,335.73
➡️ Equity Curve R²: 0.4873
➡️ Monthly Consistency Score: -0.0080

=== [1834/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.55it/s]
Hypertuning:  53%|█████▎    | 1834/3456 [42:51<36:10,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.9400
➡️ Total Profit: ₹50,083.13
➡️ Equity Curve R²: 0.4320
➡️ Monthly Consistency Score: 0.1982

=== [1835/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.37it/s]
Hypertuning:  53%|█████▎    | 1835/3456 [42:52<36:26,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.1443
➡️ Total Profit: ₹25,320.31
➡️ Equity Curve R²: 0.1486
➡️ Monthly Consistency Score: 0.1028

=== [1836/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.37it/s]
Hypertuning:  53%|█████▎    | 1836/3456 [42:54<36:55,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.6384
➡️ Total Profit: ₹17,820.27
➡️ Equity Curve R²: 0.0522
➡️ Monthly Consistency Score: 0.0721

=== [1837/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.13it/s]
Hypertuning:  53%|█████▎    | 1837/3456 [42:55<36:37,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.6025
➡️ Total Profit: ₹17,346.32
➡️ Equity Curve R²: 0.0263
➡️ Monthly Consistency Score: 0.0682

=== [1838/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.36it/s]
Hypertuning:  53%|█████▎    | 1838/3456 [42:56<36:13,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 3.1112
➡️ Total Profit: ₹67,747.48
➡️ Equity Curve R²: 0.4514
➡️ Monthly Consistency Score: 0.2968

=== [1839/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.74it/s]
Hypertuning:  53%|█████▎    | 1839/3456 [42:58<36:22,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.4072
➡️ Total Profit: ₹66,654.68
➡️ Equity Curve R²: 0.6407
➡️ Monthly Consistency Score: 0.2759

=== [1840/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.53it/s]
Hypertuning:  53%|█████▎    | 1840/3456 [42:59<36:45,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 5.9249
➡️ Total Profit: ₹80,384.66
➡️ Equity Curve R²: 0.8364
➡️ Monthly Consistency Score: 0.3862

=== [1841/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.73it/s]
Hypertuning:  53%|█████▎    | 1841/3456 [43:00<36:52,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.5623
➡️ Total Profit: ₹-44,447.33
➡️ Equity Curve R²: 0.9125
➡️ Monthly Consistency Score: -0.1848

=== [1842/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.20it/s]
Hypertuning:  53%|█████▎    | 1842/3456 [43:02<36:20,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1665
➡️ Total Profit: ₹-7,051.03
➡️ Equity Curve R²: 0.7842
➡️ Monthly Consistency Score: -0.0293

=== [1843/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.69it/s]
Hypertuning:  53%|█████▎    | 1843/3456 [43:03<36:31,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1366
➡️ Total Profit: ₹7,282.30
➡️ Equity Curve R²: 0.4873
➡️ Monthly Consistency Score: 0.0256

=== [1844/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.00it/s]
Hypertuning:  53%|█████▎    | 1844/3456 [43:04<36:01,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.2355
➡️ Total Profit: ₹7,537.19
➡️ Equity Curve R²: 0.1679
➡️ Monthly Consistency Score: 0.0286

=== [1845/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.79it/s]
Hypertuning:  53%|█████▎    | 1845/3456 [43:06<36:39,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3956
➡️ Total Profit: ₹-15,398.44
➡️ Equity Curve R²: 0.7140
➡️ Monthly Consistency Score: -0.0524

=== [1846/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.61it/s]
Hypertuning:  53%|█████▎    | 1846/3456 [43:07<37:06,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.4341
➡️ Total Profit: ₹25,153.97
➡️ Equity Curve R²: 0.5212
➡️ Monthly Consistency Score: 0.0971

=== [1847/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.24it/s]
Hypertuning:  53%|█████▎    | 1847/3456 [43:09<36:28,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.0280
➡️ Total Profit: ₹39,767.63
➡️ Equity Curve R²: 0.7765
➡️ Monthly Consistency Score: 0.1568

=== [1848/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.06it/s]
Hypertuning:  53%|█████▎    | 1848/3456 [43:10<35:54,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.4404
➡️ Total Profit: ₹-16,748.74
➡️ Equity Curve R²: 0.6247
➡️ Monthly Consistency Score: -0.0748

=== [1849/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.77it/s]
Hypertuning:  54%|█████▎    | 1849/3456 [43:11<36:25,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0463
➡️ Total Profit: ₹-2,331.97
➡️ Equity Curve R²: 0.5127
➡️ Monthly Consistency Score: -0.0079

=== [1850/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.26it/s]
Hypertuning:  54%|█████▎    | 1850/3456 [43:13<35:56,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.9838
➡️ Total Profit: ₹51,214.05
➡️ Equity Curve R²: 0.4231
➡️ Monthly Consistency Score: 0.2021

=== [1851/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 130.36it/s]
Hypertuning:  54%|█████▎    | 1851/3456 [43:14<36:08,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.2180
➡️ Total Profit: ₹26,951.68
➡️ Equity Curve R²: 0.1321
➡️ Monthly Consistency Score: 0.1083

=== [1852/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.21it/s]
Hypertuning:  54%|█████▎    | 1852/3456 [43:15<35:39,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 0.7149
➡️ Total Profit: ₹19,955.73
➡️ Equity Curve R²: 0.1645
➡️ Monthly Consistency Score: 0.0846

=== [1853/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.94it/s]
Hypertuning:  54%|█████▎    | 1853/3456 [43:17<36:16,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5664
➡️ Total Profit: ₹16,305.30
➡️ Equity Curve R²: 0.0538
➡️ Monthly Consistency Score: 0.0660

=== [1854/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.47it/s]
Hypertuning:  54%|█████▎    | 1854/3456 [43:18<36:04,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.4895
➡️ Total Profit: ₹59,834.71
➡️ Equity Curve R²: 0.4087
➡️ Monthly Consistency Score: 0.2613

=== [1855/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.75it/s]
Hypertuning:  54%|█████▎    | 1855/3456 [43:19<36:28,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.4072
➡️ Total Profit: ₹66,654.68
➡️ Equity Curve R²: 0.6407
➡️ Monthly Consistency Score: 0.2759

=== [1856/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.13it/s]
Hypertuning:  54%|█████▎    | 1856/3456 [43:21<35:53,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 7.5491
➡️ Total Profit: ₹80,384.66
➡️ Equity Curve R²: 0.8610
➡️ Monthly Consistency Score: 0.3679

=== [1857/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.97it/s]
Hypertuning:  54%|█████▎    | 1857/3456 [43:22<36:38,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.6970
➡️ Total Profit: ₹-64,327.95
➡️ Equity Curve R²: 0.9532
➡️ Monthly Consistency Score: -0.2606

=== [1858/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.34it/s]
Hypertuning:  54%|█████▍    | 1858/3456 [43:24<36:51,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.1289
➡️ Total Profit: ₹-4,785.67
➡️ Equity Curve R²: 0.7733
➡️ Monthly Consistency Score: -0.0202

=== [1859/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.40it/s]
Hypertuning:  54%|█████▍    | 1859/3456 [43:25<36:16,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.3505
➡️ Total Profit: ₹14,250.03
➡️ Equity Curve R²: 0.3766
➡️ Monthly Consistency Score: 0.0558

=== [1860/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.42it/s]
Hypertuning:  54%|█████▍    | 1860/3456 [43:26<35:40,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.6900
➡️ Total Profit: ₹19,656.17
➡️ Equity Curve R²: 0.0973
➡️ Monthly Consistency Score: 0.0751

=== [1861/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.21it/s]
Hypertuning:  54%|█████▍    | 1861/3456 [43:28<36:07,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3647
➡️ Total Profit: ₹-13,968.66
➡️ Equity Curve R²: 0.6591
➡️ Monthly Consistency Score: -0.0482

=== [1862/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.14it/s]
Hypertuning:  54%|█████▍    | 1862/3456 [43:29<36:38,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.9377
➡️ Total Profit: ₹18,099.37
➡️ Equity Curve R²: 0.0928
➡️ Monthly Consistency Score: 0.0707

=== [1863/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.38it/s]
Hypertuning:  54%|█████▍    | 1863/3456 [43:30<36:13,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.8631
➡️ Total Profit: ₹36,533.48
➡️ Equity Curve R²: 0.7862
➡️ Monthly Consistency Score: 0.1562

=== [1864/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.72it/s]
Hypertuning:  54%|█████▍    | 1864/3456 [43:32<35:52,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.4737
➡️ Total Profit: ₹-18,876.92
➡️ Equity Curve R²: 0.6564
➡️ Monthly Consistency Score: -0.0835

=== [1865/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.64it/s]
Hypertuning:  54%|█████▍    | 1865/3456 [43:33<36:16,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0223
➡️ Total Profit: ₹-1,135.90
➡️ Equity Curve R²: 0.4293
➡️ Monthly Consistency Score: -0.0040

=== [1866/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 129.12it/s]
Hypertuning:  54%|█████▍    | 1866/3456 [43:34<35:43,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.4668
➡️ Total Profit: ₹55,735.90
➡️ Equity Curve R²: 0.4459
➡️ Monthly Consistency Score: 0.2199

=== [1867/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 131.28it/s]
Hypertuning:  54%|█████▍    | 1867/3456 [43:36<35:51,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.0707
➡️ Total Profit: ₹23,691.68
➡️ Equity Curve R²: 0.1089
➡️ Monthly Consistency Score: 0.0955

=== [1868/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.68it/s]
Hypertuning:  54%|█████▍    | 1868/3456 [43:37<35:14,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 0.1151
➡️ Total Profit: ₹4,083.90
➡️ Equity Curve R²: 0.2123
➡️ Monthly Consistency Score: 0.0169

=== [1869/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.52it/s]
Hypertuning:  54%|█████▍    | 1869/3456 [43:38<35:46,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3329
➡️ Total Profit: ₹9,372.95
➡️ Equity Curve R²: 0.1281
➡️ Monthly Consistency Score: 0.0385

=== [1870/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.38it/s]
Hypertuning:  54%|█████▍    | 1870/3456 [43:40<35:20,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.2877
➡️ Total Profit: ₹57,572.87
➡️ Equity Curve R²: 0.3207
➡️ Monthly Consistency Score: 0.2461

=== [1871/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.46it/s]
Hypertuning:  54%|█████▍    | 1871/3456 [43:41<35:38,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.9904
➡️ Total Profit: ₹78,063.31
➡️ Equity Curve R²: 0.6433
➡️ Monthly Consistency Score: 0.3588

=== [1872/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.41it/s]
Hypertuning:  54%|█████▍    | 1872/3456 [43:42<35:15,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.5839
➡️ Total Profit: ₹52,128.29
➡️ Equity Curve R²: 0.2636
➡️ Monthly Consistency Score: 0.2366

=== [1873/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.20it/s]
Hypertuning:  54%|█████▍    | 1873/3456 [43:44<36:06,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.7035
➡️ Total Profit: ₹-55,510.48
➡️ Equity Curve R²: 0.9395
➡️ Monthly Consistency Score: -0.2357

=== [1874/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.53it/s]
Hypertuning:  54%|█████▍    | 1874/3456 [43:45<36:22,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.2529
➡️ Total Profit: ₹-11,571.03
➡️ Equity Curve R²: 0.8158
➡️ Monthly Consistency Score: -0.0478

=== [1875/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.52it/s]
Hypertuning:  54%|█████▍    | 1875/3456 [43:46<35:40,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3829
➡️ Total Profit: ₹17,908.19
➡️ Equity Curve R²: 0.2727
➡️ Monthly Consistency Score: 0.0628

=== [1876/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.17it/s]
Hypertuning:  54%|█████▍    | 1876/3456 [43:48<35:04,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: -0.0713
➡️ Total Profit: ₹-3,114.64
➡️ Equity Curve R²: 0.5493
➡️ Monthly Consistency Score: -0.0108

=== [1877/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.40it/s]
Hypertuning:  54%|█████▍    | 1877/3456 [43:49<35:36,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3102
➡️ Total Profit: ₹-11,156.31
➡️ Equity Curve R²: 0.6164
➡️ Monthly Consistency Score: -0.0391

=== [1878/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.45it/s]
Hypertuning:  54%|█████▍    | 1878/3456 [43:51<35:55,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.5713
➡️ Total Profit: ₹27,326.73
➡️ Equity Curve R²: 0.5328
➡️ Monthly Consistency Score: 0.1098

=== [1879/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.33it/s]
Hypertuning:  54%|█████▍    | 1879/3456 [43:52<35:25,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.7805
➡️ Total Profit: ₹34,913.52
➡️ Equity Curve R²: 0.7112
➡️ Monthly Consistency Score: 0.1387

=== [1880/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.42it/s]
Hypertuning:  54%|█████▍    | 1880/3456 [43:53<35:04,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.0500
➡️ Total Profit: ₹-1,231.40
➡️ Equity Curve R²: 0.0597
➡️ Monthly Consistency Score: -0.0053

=== [1881/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.72it/s]
Hypertuning:  54%|█████▍    | 1881/3456 [43:55<35:47,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0482
➡️ Total Profit: ₹-2,335.73
➡️ Equity Curve R²: 0.4873
➡️ Monthly Consistency Score: -0.0080

=== [1882/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 132.40it/s]
Hypertuning:  54%|█████▍    | 1882/3456 [43:56<35:17,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.9400
➡️ Total Profit: ₹50,083.13
➡️ Equity Curve R²: 0.4320
➡️ Monthly Consistency Score: 0.1982

=== [1883/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.17it/s]
Hypertuning:  54%|█████▍    | 1883/3456 [43:57<35:27,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.9973
➡️ Total Profit: ₹23,691.68
➡️ Equity Curve R²: 0.0998
➡️ Monthly Consistency Score: 0.0934

=== [1884/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.82it/s]
Hypertuning:  55%|█████▍    | 1884/3456 [43:59<34:55,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 0.6384
➡️ Total Profit: ₹17,820.27
➡️ Equity Curve R²: 0.0522
➡️ Monthly Consistency Score: 0.0721

=== [1885/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.73it/s]
Hypertuning:  55%|█████▍    | 1885/3456 [44:00<35:25,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6025
➡️ Total Profit: ₹17,346.32
➡️ Equity Curve R²: 0.0263
➡️ Monthly Consistency Score: 0.0682

=== [1886/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.98it/s]
Hypertuning:  55%|█████▍    | 1886/3456 [44:01<34:53,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 3.1112
➡️ Total Profit: ₹67,747.48
➡️ Equity Curve R²: 0.4514
➡️ Monthly Consistency Score: 0.2968

=== [1887/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.59it/s]
Hypertuning:  55%|█████▍    | 1887/3456 [44:03<35:05,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 3.4072
➡️ Total Profit: ₹66,654.68
➡️ Equity Curve R²: 0.6407
➡️ Monthly Consistency Score: 0.2759

=== [1888/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.89it/s]
Hypertuning:  55%|█████▍    | 1888/3456 [44:04<34:36,  1.32s/it]

➡️ Profit-to-Drawdown Ratio: 5.9249
➡️ Total Profit: ₹80,384.66
➡️ Equity Curve R²: 0.8364
➡️ Monthly Consistency Score: 0.3862

=== [1889/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.72it/s]
Hypertuning:  55%|█████▍    | 1889/3456 [44:05<35:14,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6403
➡️ Total Profit: ₹-52,987.94
➡️ Equity Curve R²: 0.9297
➡️ Monthly Consistency Score: -0.2255

=== [1890/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.38it/s]
Hypertuning:  55%|█████▍    | 1890/3456 [44:07<35:37,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0690
➡️ Total Profit: ₹-2,531.03
➡️ Equity Curve R²: 0.6650
➡️ Monthly Consistency Score: -0.0105

=== [1891/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.77it/s]
Hypertuning:  55%|█████▍    | 1891/3456 [44:08<35:18,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3498
➡️ Total Profit: ₹15,494.08
➡️ Equity Curve R²: 0.2994
➡️ Monthly Consistency Score: 0.0577

=== [1892/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.31it/s]
Hypertuning:  55%|█████▍    | 1892/3456 [44:09<34:46,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 0.2156
➡️ Total Profit: ₹6,142.59
➡️ Equity Curve R²: 0.1616
➡️ Monthly Consistency Score: 0.0221

=== [1893/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.16it/s]
Hypertuning:  55%|█████▍    | 1893/3456 [44:11<35:11,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2927
➡️ Total Profit: ₹-10,523.96
➡️ Equity Curve R²: 0.5955
➡️ Monthly Consistency Score: -0.0370

=== [1894/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.50it/s]
Hypertuning:  55%|█████▍    | 1894/3456 [44:12<35:37,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.0831
➡️ Total Profit: ₹23,590.29
➡️ Equity Curve R²: 0.3528
➡️ Monthly Consistency Score: 0.0882

=== [1895/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.14it/s]
Hypertuning:  55%|█████▍    | 1895/3456 [44:13<35:09,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.7800
➡️ Total Profit: ₹34,904.85
➡️ Equity Curve R²: 0.7609
➡️ Monthly Consistency Score: 0.1501

=== [1896/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.40it/s]
Hypertuning:  55%|█████▍    | 1896/3456 [44:15<34:44,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.1270
➡️ Total Profit: ₹-3,359.58
➡️ Equity Curve R²: 0.0971
➡️ Monthly Consistency Score: -0.0143

=== [1897/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.83it/s]
Hypertuning:  55%|█████▍    | 1897/3456 [44:16<35:14,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0595
➡️ Total Profit: ₹-2,961.50
➡️ Equity Curve R²: 0.5047
➡️ Monthly Consistency Score: -0.0101

=== [1898/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.35it/s]
Hypertuning:  55%|█████▍    | 1898/3456 [44:17<34:46,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.9400
➡️ Total Profit: ₹50,083.13
➡️ Equity Curve R²: 0.4320
➡️ Monthly Consistency Score: 0.1982

=== [1899/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.12it/s]
Hypertuning:  55%|█████▍    | 1899/3456 [44:19<35:03,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.9234
➡️ Total Profit: ₹20,431.68
➡️ Equity Curve R²: 0.0766
➡️ Monthly Consistency Score: 0.0839

=== [1900/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.96it/s]
Hypertuning:  55%|█████▍    | 1900/3456 [44:20<34:41,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.4639
➡️ Total Profit: ₹15,692.09
➡️ Equity Curve R²: 0.0097
➡️ Monthly Consistency Score: 0.0612

=== [1901/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.11it/s]
Hypertuning:  55%|█████▌    | 1901/3456 [44:22<35:19,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5757
➡️ Total Profit: ₹16,936.71
➡️ Equity Curve R²: 0.0724
➡️ Monthly Consistency Score: 0.0691

=== [1902/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.34it/s]
Hypertuning:  55%|█████▌    | 1902/3456 [44:23<34:53,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.7997
➡️ Total Profit: ₹60,963.79
➡️ Equity Curve R²: 0.5070
➡️ Monthly Consistency Score: 0.2709

=== [1903/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.36it/s]
Hypertuning:  55%|█████▌    | 1903/3456 [44:24<35:13,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.2407
➡️ Total Profit: ₹63,397.41
➡️ Equity Curve R²: 0.6716
➡️ Monthly Consistency Score: 0.2684

=== [1904/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.06it/s]
Hypertuning:  55%|█████▌    | 1904/3456 [44:26<34:41,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 5.9249
➡️ Total Profit: ₹80,384.66
➡️ Equity Curve R²: 0.8364
➡️ Monthly Consistency Score: 0.3862

=== [1905/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.54it/s]
Hypertuning:  55%|█████▌    | 1905/3456 [44:27<35:16,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.7384
➡️ Total Profit: ₹-64,319.77
➡️ Equity Curve R²: 0.9469
➡️ Monthly Consistency Score: -0.2717

=== [1906/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.59it/s]
Hypertuning:  55%|█████▌    | 1906/3456 [44:28<35:37,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.3598
➡️ Total Profit: ₹-14,614.67
➡️ Equity Curve R²: 0.8451
➡️ Monthly Consistency Score: -0.0631

=== [1907/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 132.75it/s]
Hypertuning:  55%|█████▌    | 1907/3456 [44:30<35:02,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3341
➡️ Total Profit: ₹-16,850.39
➡️ Equity Curve R²: 0.7749
➡️ Monthly Consistency Score: -0.0638

=== [1908/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.52it/s]
Hypertuning:  55%|█████▌    | 1908/3456 [44:31<34:31,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.1341
➡️ Total Profit: ₹4,660.67
➡️ Equity Curve R²: 0.0424
➡️ Monthly Consistency Score: 0.0164

=== [1909/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.48it/s]
Hypertuning:  55%|█████▌    | 1909/3456 [44:32<35:12,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1954
➡️ Total Profit: ₹-6,410.54
➡️ Equity Curve R²: 0.5186
➡️ Monthly Consistency Score: -0.0227

=== [1910/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.54it/s]
Hypertuning:  55%|█████▌    | 1910/3456 [44:34<35:47,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 1.3796
➡️ Total Profit: ₹28,186.73
➡️ Equity Curve R²: 0.5083
➡️ Monthly Consistency Score: 0.1085

=== [1911/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.25it/s]
Hypertuning:  55%|█████▌    | 1911/3456 [44:35<35:09,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.7580
➡️ Total Profit: ₹18,606.85
➡️ Equity Curve R²: 0.5862
➡️ Monthly Consistency Score: 0.0779

=== [1912/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.41it/s]
Hypertuning:  55%|█████▌    | 1912/3456 [44:37<35:24,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.0184
➡️ Total Profit: ₹-609.64
➡️ Equity Curve R²: 0.2220
➡️ Monthly Consistency Score: -0.0027

=== [1913/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.62it/s]
Hypertuning:  55%|█████▌    | 1913/3456 [44:38<35:12,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3747
➡️ Total Profit: ₹-28,042.45
➡️ Equity Curve R²: 0.7886
➡️ Monthly Consistency Score: -0.0927

=== [1914/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.35it/s]
Hypertuning:  55%|█████▌    | 1914/3456 [44:39<34:46,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.6362
➡️ Total Profit: ₹59,123.14
➡️ Equity Curve R²: 0.5387
➡️ Monthly Consistency Score: 0.2342

=== [1915/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.23it/s]
Hypertuning:  55%|█████▌    | 1915/3456 [44:41<34:58,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.7407
➡️ Total Profit: ₹18,803.05
➡️ Equity Curve R²: 0.0290
➡️ Monthly Consistency Score: 0.0752

=== [1916/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.16it/s]
Hypertuning:  55%|█████▌    | 1916/3456 [44:42<35:19,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.1201
➡️ Total Profit: ₹-4,428.82
➡️ Equity Curve R²: 0.4118
➡️ Monthly Consistency Score: -0.0179

=== [1917/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.94it/s]
Hypertuning:  55%|█████▌    | 1917/3456 [44:43<35:10,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.8283
➡️ Total Profit: ₹20,715.77
➡️ Equity Curve R²: 0.0002
➡️ Monthly Consistency Score: 0.0852

=== [1918/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.88it/s]
Hypertuning:  55%|█████▌    | 1918/3456 [44:45<34:45,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.6121
➡️ Total Profit: ₹59,832.87
➡️ Equity Curve R²: 0.4107
➡️ Monthly Consistency Score: 0.2631

=== [1919/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.28it/s]
Hypertuning:  56%|█████▌    | 1919/3456 [44:46<35:07,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.9904
➡️ Total Profit: ₹78,063.31
➡️ Equity Curve R²: 0.6433
➡️ Monthly Consistency Score: 0.3588

=== [1920/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.06it/s]
Hypertuning:  56%|█████▌    | 1920/3456 [44:47<34:32,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.8149
➡️ Total Profit: ₹76,128.30
➡️ Equity Curve R²: 0.7779
➡️ Monthly Consistency Score: 0.3447

=== [1921/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.46it/s]
Hypertuning:  56%|█████▌    | 1921/3456 [44:49<35:00,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3628
➡️ Total Profit: ₹-18,342.93
➡️ Equity Curve R²: 0.8415
➡️ Monthly Consistency Score: -0.0808

=== [1922/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.37it/s]
Hypertuning:  56%|█████▌    | 1922/3456 [44:50<35:18,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.1001
➡️ Total Profit: ₹-4,266.63
➡️ Equity Curve R²: 0.6303
➡️ Monthly Consistency Score: -0.0163

=== [1923/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.21it/s]
Hypertuning:  56%|█████▌    | 1923/3456 [44:52<34:43,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.3720
➡️ Total Profit: ₹14,653.91
➡️ Equity Curve R²: 0.2911
➡️ Monthly Consistency Score: 0.0515

=== [1924/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.01it/s]
Hypertuning:  56%|█████▌    | 1924/3456 [44:53<34:09,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.6045
➡️ Total Profit: ₹21,063.81
➡️ Equity Curve R²: 0.0583
➡️ Monthly Consistency Score: 0.0810

=== [1925/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.71it/s]
Hypertuning:  56%|█████▌    | 1925/3456 [44:54<34:40,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0055
➡️ Total Profit: ₹184.57
➡️ Equity Curve R²: 0.3156
➡️ Monthly Consistency Score: 0.0007

=== [1926/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.10it/s]
Hypertuning:  56%|█████▌    | 1926/3456 [44:56<35:06,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.3913
➡️ Total Profit: ₹-20,061.88
➡️ Equity Curve R²: 0.7747
➡️ Monthly Consistency Score: -0.0684

=== [1927/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.85it/s]
Hypertuning:  56%|█████▌    | 1927/3456 [44:57<34:33,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3035
➡️ Total Profit: ₹-13,922.86
➡️ Equity Curve R²: 0.4784
➡️ Monthly Consistency Score: -0.0507

=== [1928/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.64it/s]
Hypertuning:  56%|█████▌    | 1928/3456 [44:58<35:02,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.1234
➡️ Total Profit: ₹-4,581.26
➡️ Equity Curve R²: 0.3583
➡️ Monthly Consistency Score: -0.0177

=== [1929/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.84it/s]
Hypertuning:  56%|█████▌    | 1929/3456 [45:00<35:00,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.3135
➡️ Total Profit: ₹-15,440.90
➡️ Equity Curve R²: 0.7430
➡️ Monthly Consistency Score: -0.0579

=== [1930/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.74it/s]
Hypertuning:  56%|█████▌    | 1930/3456 [45:01<34:25,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.2002
➡️ Total Profit: ₹30,779.93
➡️ Equity Curve R²: 0.5333
➡️ Monthly Consistency Score: 0.1057

=== [1931/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.54it/s]
Hypertuning:  56%|█████▌    | 1931/3456 [45:02<34:33,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.3030
➡️ Total Profit: ₹31,848.53
➡️ Equity Curve R²: 0.1739
➡️ Monthly Consistency Score: 0.1272

=== [1932/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.34it/s]
Hypertuning:  56%|█████▌    | 1932/3456 [45:04<34:47,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.2407
➡️ Total Profit: ₹9,794.00
➡️ Equity Curve R²: 0.1181
➡️ Monthly Consistency Score: 0.0345

=== [1933/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.67it/s]
Hypertuning:  56%|█████▌    | 1933/3456 [45:05<34:45,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.5762
➡️ Total Profit: ₹48,005.34
➡️ Equity Curve R²: 0.0943
➡️ Monthly Consistency Score: 0.1882

=== [1934/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.67it/s]
Hypertuning:  56%|█████▌    | 1934/3456 [45:06<34:21,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.4099
➡️ Total Profit: ₹54,711.47
➡️ Equity Curve R²: 0.0034
➡️ Monthly Consistency Score: 0.2023

=== [1935/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.59it/s]
Hypertuning:  56%|█████▌    | 1935/3456 [45:08<34:27,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.7157
➡️ Total Profit: ₹58,412.54
➡️ Equity Curve R²: 0.0431
➡️ Monthly Consistency Score: 0.2510

=== [1936/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 108.10it/s]
Hypertuning:  56%|█████▌    | 1936/3456 [45:09<33:59,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 10.0762
➡️ Total Profit: ₹107,292.96
➡️ Equity Curve R²: 0.9066
➡️ Monthly Consistency Score: 0.5711

=== [1937/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.80it/s]
Hypertuning:  56%|█████▌    | 1937/3456 [45:11<34:58,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.2676
➡️ Total Profit: ₹-13,303.87
➡️ Equity Curve R²: 0.8129
➡️ Monthly Consistency Score: -0.0581

=== [1938/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.73it/s]
Hypertuning:  56%|█████▌    | 1938/3456 [45:12<35:14,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.0223
➡️ Total Profit: ₹-875.71
➡️ Equity Curve R²: 0.6322
➡️ Monthly Consistency Score: -0.0034

=== [1939/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.86it/s]
Hypertuning:  56%|█████▌    | 1939/3456 [45:13<34:32,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.2373
➡️ Total Profit: ₹9,309.33
➡️ Equity Curve R²: 0.3428
➡️ Monthly Consistency Score: 0.0342

=== [1940/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.93it/s]
Hypertuning:  56%|█████▌    | 1940/3456 [45:15<34:58,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.4824
➡️ Total Profit: ₹18,192.85
➡️ Equity Curve R²: 0.1301
➡️ Monthly Consistency Score: 0.0703

=== [1941/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.79it/s]
Hypertuning:  56%|█████▌    | 1941/3456 [45:16<34:51,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.0243
➡️ Total Profit: ₹815.04
➡️ Equity Curve R²: 0.2817
➡️ Monthly Consistency Score: 0.0029

=== [1942/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.36it/s]
Hypertuning:  56%|█████▌    | 1942/3456 [45:17<34:17,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4044
➡️ Total Profit: ₹-21,190.96
➡️ Equity Curve R²: 0.7735
➡️ Monthly Consistency Score: -0.0714

=== [1943/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.78it/s]
Hypertuning:  56%|█████▌    | 1943/3456 [45:19<34:26,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1683
➡️ Total Profit: ₹-7,442.86
➡️ Equity Curve R²: 0.3110
➡️ Monthly Consistency Score: -0.0264

=== [1944/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.57it/s]
Hypertuning:  56%|█████▋    | 1944/3456 [45:20<33:46,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.1026
➡️ Total Profit: ₹3,026.92
➡️ Equity Curve R²: 0.0963
➡️ Monthly Consistency Score: 0.0113

=== [1945/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.06it/s]
Hypertuning:  56%|█████▋    | 1945/3456 [45:22<34:25,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3086
➡️ Total Profit: ₹-14,809.49
➡️ Equity Curve R²: 0.7249
➡️ Monthly Consistency Score: -0.0555

=== [1946/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.60it/s]
Hypertuning:  56%|█████▋    | 1946/3456 [45:23<34:56,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 1.2002
➡️ Total Profit: ₹30,779.93
➡️ Equity Curve R²: 0.5333
➡️ Monthly Consistency Score: 0.1057

=== [1947/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.81it/s]
Hypertuning:  56%|█████▋    | 1947/3456 [45:24<34:27,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.3030
➡️ Total Profit: ₹31,848.53
➡️ Equity Curve R²: 0.1739
➡️ Monthly Consistency Score: 0.1272

=== [1948/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.22it/s]
Hypertuning:  56%|█████▋    | 1948/3456 [45:26<33:52,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2407
➡️ Total Profit: ₹9,794.00
➡️ Equity Curve R²: 0.1181
➡️ Monthly Consistency Score: 0.0345

=== [1949/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.28it/s]
Hypertuning:  56%|█████▋    | 1949/3456 [45:27<34:21,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.5240
➡️ Total Profit: ₹47,375.80
➡️ Equity Curve R²: 0.0776
➡️ Monthly Consistency Score: 0.1852

=== [1950/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 108.07it/s]
Hypertuning:  56%|█████▋    | 1950/3456 [45:28<34:44,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.2773
➡️ Total Profit: ₹52,451.47
➡️ Equity Curve R²: 0.0208
➡️ Monthly Consistency Score: 0.1919

=== [1951/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.47it/s]
Hypertuning:  56%|█████▋    | 1951/3456 [45:30<34:15,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.7051
➡️ Total Profit: ₹78,149.81
➡️ Equity Curve R²: 0.5394
➡️ Monthly Consistency Score: 0.3246

=== [1952/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.89it/s]
Hypertuning:  56%|█████▋    | 1952/3456 [45:31<33:47,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 10.0762
➡️ Total Profit: ₹107,292.96
➡️ Equity Curve R²: 0.9066
➡️ Monthly Consistency Score: 0.5711

=== [1953/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.47it/s]
Hypertuning:  57%|█████▋    | 1953/3456 [45:33<34:23,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4488
➡️ Total Profit: ₹-24,076.91
➡️ Equity Curve R²: 0.8458
➡️ Monthly Consistency Score: -0.1049

=== [1954/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.39it/s]
Hypertuning:  57%|█████▋    | 1954/3456 [45:34<34:00,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3869
➡️ Total Profit: ₹-19,648.59
➡️ Equity Curve R²: 0.8234
➡️ Monthly Consistency Score: -0.0788

=== [1955/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 104.76it/s]
Hypertuning:  57%|█████▋    | 1955/3456 [45:35<34:17,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.3478
➡️ Total Profit: ₹15,428.43
➡️ Equity Curve R²: 0.3227
➡️ Monthly Consistency Score: 0.0580

=== [1956/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.35it/s]
Hypertuning:  57%|█████▋    | 1956/3456 [45:37<34:34,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.5582
➡️ Total Profit: ₹21,054.61
➡️ Equity Curve R²: 0.0878
➡️ Monthly Consistency Score: 0.0805

=== [1957/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.70it/s]
Hypertuning:  57%|█████▋    | 1957/3456 [45:38<34:15,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1599
➡️ Total Profit: ₹-5,151.54
➡️ Equity Curve R²: 0.3902
➡️ Monthly Consistency Score: -0.0179

=== [1958/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.30it/s]
Hypertuning:  57%|█████▋    | 1958/3456 [45:39<33:50,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4082
➡️ Total Profit: ₹-23,021.88
➡️ Equity Curve R²: 0.8386
➡️ Monthly Consistency Score: -0.0795

=== [1959/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.56it/s]
Hypertuning:  57%|█████▋    | 1959/3456 [45:41<34:00,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3865
➡️ Total Profit: ₹-13,945.23
➡️ Equity Curve R²: 0.2449
➡️ Monthly Consistency Score: -0.0510

=== [1960/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.38it/s]
Hypertuning:  57%|█████▋    | 1960/3456 [45:42<34:20,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.2910
➡️ Total Profit: ₹-12,483.14
➡️ Equity Curve R²: 0.6427
➡️ Monthly Consistency Score: -0.0483

=== [1961/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.80it/s]
Hypertuning:  57%|█████▋    | 1961/3456 [45:43<34:09,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3774
➡️ Total Profit: ₹-18,589.50
➡️ Equity Curve R²: 0.7772
➡️ Monthly Consistency Score: -0.0697

=== [1962/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.77it/s]
Hypertuning:  57%|█████▋    | 1962/3456 [45:45<34:32,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 0.7176
➡️ Total Profit: ₹16,092.69
➡️ Equity Curve R²: 0.2557
➡️ Monthly Consistency Score: 0.0534

=== [1963/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.31it/s]
Hypertuning:  57%|█████▋    | 1963/3456 [45:46<34:02,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.2363
➡️ Total Profit: ₹30,219.90
➡️ Equity Curve R²: 0.1901
➡️ Monthly Consistency Score: 0.1209

=== [1964/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.73it/s]
Hypertuning:  57%|█████▋    | 1964/3456 [45:48<33:40,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3283
➡️ Total Profit: ₹14,057.65
➡️ Equity Curve R²: 0.0865
➡️ Monthly Consistency Score: 0.0500

=== [1965/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.92it/s]
Hypertuning:  57%|█████▋    | 1965/3456 [45:49<34:32,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 1.5761
➡️ Total Profit: ₹48,003.46
➡️ Equity Curve R²: 0.1168
➡️ Monthly Consistency Score: 0.1897

=== [1966/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 130.44it/s]
Hypertuning:  57%|█████▋    | 1966/3456 [45:50<33:54,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.9047
➡️ Total Profit: ₹39,195.85
➡️ Equity Curve R²: 0.0574
➡️ Monthly Consistency Score: 0.1473

=== [1967/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.87it/s]
Hypertuning:  57%|█████▋    | 1967/3456 [45:52<33:54,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.7052
➡️ Total Profit: ₹78,152.55
➡️ Equity Curve R²: 0.6067
➡️ Monthly Consistency Score: 0.3290

=== [1968/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.94it/s]
Hypertuning:  57%|█████▋    | 1968/3456 [45:53<33:21,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 3.1642
➡️ Total Profit: ₹60,651.93
➡️ Equity Curve R²: 0.4993
➡️ Monthly Consistency Score: 0.2666

=== [1969/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.91it/s]
Hypertuning:  57%|█████▋    | 1969/3456 [45:54<33:51,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3628
➡️ Total Profit: ₹-18,342.93
➡️ Equity Curve R²: 0.8415
➡️ Monthly Consistency Score: -0.0808

=== [1970/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.03it/s]
Hypertuning:  57%|█████▋    | 1970/3456 [45:56<34:12,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.1263
➡️ Total Profit: ₹5,382.53
➡️ Equity Curve R²: 0.5318
➡️ Monthly Consistency Score: 0.0201

=== [1971/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.62it/s]
Hypertuning:  57%|█████▋    | 1971/3456 [45:57<33:37,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.3720
➡️ Total Profit: ₹14,653.91
➡️ Equity Curve R²: 0.2911
➡️ Monthly Consistency Score: 0.0515

=== [1972/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.31it/s]
Hypertuning:  57%|█████▋    | 1972/3456 [45:59<33:57,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.2176
➡️ Total Profit: ₹9,763.81
➡️ Equity Curve R²: 0.4021
➡️ Monthly Consistency Score: 0.0342

=== [1973/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.31it/s]
Hypertuning:  57%|█████▋    | 1973/3456 [46:00<33:55,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.0243
➡️ Total Profit: ₹814.10
➡️ Equity Curve R²: 0.2938
➡️ Monthly Consistency Score: 0.0029

=== [1974/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.73it/s]
Hypertuning:  57%|█████▋    | 1974/3456 [46:01<34:00,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.3472
➡️ Total Profit: ₹-17,801.88
➡️ Equity Curve R²: 0.7493
➡️ Monthly Consistency Score: -0.0613

=== [1975/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.64it/s]
Hypertuning:  57%|█████▋    | 1975/3456 [46:03<33:24,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3035
➡️ Total Profit: ₹-13,922.86
➡️ Equity Curve R²: 0.4784
➡️ Monthly Consistency Score: -0.0507

=== [1976/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.29it/s]
Hypertuning:  57%|█████▋    | 1976/3456 [46:04<33:35,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1234
➡️ Total Profit: ₹-4,581.26
➡️ Equity Curve R²: 0.3583
➡️ Monthly Consistency Score: -0.0177

=== [1977/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 111.68it/s]
Hypertuning:  57%|█████▋    | 1977/3456 [46:05<33:19,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3135
➡️ Total Profit: ₹-15,440.90
➡️ Equity Curve R²: 0.7430
➡️ Monthly Consistency Score: -0.0579

=== [1978/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.15it/s]
Hypertuning:  57%|█████▋    | 1978/3456 [46:07<33:37,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.2002
➡️ Total Profit: ₹30,779.93
➡️ Equity Curve R²: 0.5333
➡️ Monthly Consistency Score: 0.1057

=== [1979/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.25it/s]
Hypertuning:  57%|█████▋    | 1979/3456 [46:08<33:08,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.4674
➡️ Total Profit: ₹33,477.16
➡️ Equity Curve R²: 0.2326
➡️ Monthly Consistency Score: 0.1336

=== [1980/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.28it/s]
Hypertuning:  57%|█████▋    | 1980/3456 [46:09<33:27,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2407
➡️ Total Profit: ₹9,794.00
➡️ Equity Curve R²: 0.1181
➡️ Monthly Consistency Score: 0.0345

=== [1981/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.78it/s]
Hypertuning:  57%|█████▋    | 1981/3456 [46:11<33:23,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.5762
➡️ Total Profit: ₹48,005.34
➡️ Equity Curve R²: 0.0943
➡️ Monthly Consistency Score: 0.1882

=== [1982/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.15it/s]
Hypertuning:  57%|█████▋    | 1982/3456 [46:12<33:50,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.4099
➡️ Total Profit: ₹54,711.47
➡️ Equity Curve R²: 0.0034
➡️ Monthly Consistency Score: 0.2023

=== [1983/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.73it/s]
Hypertuning:  57%|█████▋    | 1983/3456 [46:13<33:13,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.7157
➡️ Total Profit: ₹58,412.54
➡️ Equity Curve R²: 0.0431
➡️ Monthly Consistency Score: 0.2510

=== [1984/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.52it/s]
Hypertuning:  57%|█████▋    | 1984/3456 [46:15<33:29,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 10.0762
➡️ Total Profit: ₹107,292.96
➡️ Equity Curve R²: 0.9066
➡️ Monthly Consistency Score: 0.5711

=== [1985/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.44it/s]
Hypertuning:  57%|█████▋    | 1985/3456 [46:16<33:25,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3618
➡️ Total Profit: ₹-18,063.54
➡️ Equity Curve R²: 0.8353
➡️ Monthly Consistency Score: -0.0797

=== [1986/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.04it/s]
Hypertuning:  57%|█████▋    | 1986/3456 [46:18<33:37,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.0069
➡️ Total Profit: ₹255.21
➡️ Equity Curve R²: 0.5584
➡️ Monthly Consistency Score: 0.0010

=== [1987/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.28it/s]
Hypertuning:  57%|█████▋    | 1987/3456 [46:19<33:03,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2901
➡️ Total Profit: ₹11,786.59
➡️ Equity Curve R²: 0.3340
➡️ Monthly Consistency Score: 0.0434

=== [1988/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.14it/s]
Hypertuning:  58%|█████▊    | 1988/3456 [46:20<33:16,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4258
➡️ Total Profit: ₹16,061.03
➡️ Equity Curve R²: 0.1473
➡️ Monthly Consistency Score: 0.0630

=== [1989/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.38it/s]
Hypertuning:  58%|█████▊    | 1989/3456 [46:22<33:04,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.0619
➡️ Total Profit: ₹2,074.10
➡️ Equity Curve R²: 0.2420
➡️ Monthly Consistency Score: 0.0073

=== [1990/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.67it/s]
Hypertuning:  58%|█████▊    | 1990/3456 [46:23<33:25,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4452
➡️ Total Profit: ₹-22,321.88
➡️ Equity Curve R²: 0.7741
➡️ Monthly Consistency Score: -0.0756

=== [1991/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.75it/s]
Hypertuning:  58%|█████▊    | 1991/3456 [46:24<32:57,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3751
➡️ Total Profit: ₹-17,197.01
➡️ Equity Curve R²: 0.4063
➡️ Monthly Consistency Score: -0.0630

=== [1992/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.39it/s]
Hypertuning:  58%|█████▊    | 1992/3456 [46:26<33:05,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1807
➡️ Total Profit: ₹-6,709.44
➡️ Equity Curve R²: 0.4111
➡️ Monthly Consistency Score: -0.0257

=== [1993/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.30it/s]
Hypertuning:  58%|█████▊    | 1993/3456 [46:27<33:38,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.3390
➡️ Total Profit: ₹-16,698.08
➡️ Equity Curve R²: 0.7532
➡️ Monthly Consistency Score: -0.0628

=== [1994/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.80it/s]
Hypertuning:  58%|█████▊    | 1994/3456 [46:28<33:12,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.2002
➡️ Total Profit: ₹30,779.93
➡️ Equity Curve R²: 0.5333
➡️ Monthly Consistency Score: 0.1057

=== [1995/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.79it/s]
Hypertuning:  58%|█████▊    | 1995/3456 [46:30<32:39,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.1697
➡️ Total Profit: ₹28,591.27
➡️ Equity Curve R²: 0.1324
➡️ Monthly Consistency Score: 0.1153

=== [1996/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.72it/s]
Hypertuning:  58%|█████▊    | 1996/3456 [46:31<32:54,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2407
➡️ Total Profit: ₹9,794.00
➡️ Equity Curve R²: 0.1181
➡️ Monthly Consistency Score: 0.0345

=== [1997/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.17it/s]
Hypertuning:  58%|█████▊    | 1997/3456 [46:32<32:44,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.5240
➡️ Total Profit: ₹47,375.80
➡️ Equity Curve R²: 0.0776
➡️ Monthly Consistency Score: 0.1852

=== [1998/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.41it/s]
Hypertuning:  58%|█████▊    | 1998/3456 [46:34<33:02,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.4099
➡️ Total Profit: ₹54,711.47
➡️ Equity Curve R²: 0.0034
➡️ Monthly Consistency Score: 0.2023

=== [1999/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.43it/s]
Hypertuning:  58%|█████▊    | 1999/3456 [46:35<33:30,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 3.3817
➡️ Total Profit: ₹71,635.29
➡️ Equity Curve R²: 0.4537
➡️ Monthly Consistency Score: 0.3010

=== [2000/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.33it/s]
Hypertuning:  58%|█████▊    | 2000/3456 [46:37<33:07,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 10.0762
➡️ Total Profit: ₹107,292.96
➡️ Equity Curve R²: 0.9066
➡️ Monthly Consistency Score: 0.5711

=== [2001/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.21it/s]
Hypertuning:  58%|█████▊    | 2001/3456 [46:38<32:47,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.5115
➡️ Total Profit: ₹-26,939.53
➡️ Equity Curve R²: 0.8553
➡️ Monthly Consistency Score: -0.1217

=== [2002/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.05it/s]
Hypertuning:  58%|█████▊    | 2002/3456 [46:39<33:01,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4931
➡️ Total Profit: ₹-24,779.60
➡️ Equity Curve R²: 0.8658
➡️ Monthly Consistency Score: -0.0971

=== [2003/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 129.30it/s]
Hypertuning:  58%|█████▊    | 2003/3456 [46:41<33:12,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.1333
➡️ Total Profit: ₹5,197.96
➡️ Equity Curve R²: 0.4029
➡️ Monthly Consistency Score: 0.0207

=== [2004/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.08it/s]
Hypertuning:  58%|█████▊    | 2004/3456 [46:42<32:39,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1439
➡️ Total Profit: ₹6,150.07
➡️ Equity Curve R²: 0.3394
➡️ Monthly Consistency Score: 0.0225

=== [2005/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.31it/s]
Hypertuning:  58%|█████▊    | 2005/3456 [46:43<32:28,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.1110
➡️ Total Profit: ₹3,506.70
➡️ Equity Curve R²: 0.2165
➡️ Monthly Consistency Score: 0.0129

=== [2006/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.50it/s]
Hypertuning:  58%|█████▊    | 2006/3456 [46:45<32:47,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2287
➡️ Total Profit: ₹-10,670.84
➡️ Equity Curve R²: 0.7359
➡️ Monthly Consistency Score: -0.0385

=== [2007/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.00it/s]
Hypertuning:  58%|█████▊    | 2007/3456 [46:46<32:16,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.3664
➡️ Total Profit: ₹-15,605.64
➡️ Equity Curve R²: 0.3170
➡️ Monthly Consistency Score: -0.0579

=== [2008/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.21it/s]
Hypertuning:  58%|█████▊    | 2008/3456 [46:47<32:33,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0340
➡️ Total Profit: ₹-1,220.48
➡️ Equity Curve R²: 0.3394
➡️ Monthly Consistency Score: -0.0048

=== [2009/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.26it/s]
Hypertuning:  58%|█████▊    | 2009/3456 [46:49<33:13,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.5825
➡️ Total Profit: ₹-43,665.74
➡️ Equity Curve R²: 0.9180
➡️ Monthly Consistency Score: -0.1547

=== [2010/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.00it/s]
Hypertuning:  58%|█████▊    | 2010/3456 [46:50<32:50,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.8859
➡️ Total Profit: ₹22,869.01
➡️ Equity Curve R²: 0.3183
➡️ Monthly Consistency Score: 0.0769

=== [2011/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.93it/s]
Hypertuning:  58%|█████▊    | 2011/3456 [46:52<33:03,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.5802
➡️ Total Profit: ₹33,477.16
➡️ Equity Curve R²: 0.2692
➡️ Monthly Consistency Score: 0.1353

=== [2012/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.40it/s]
Hypertuning:  58%|█████▊    | 2012/3456 [46:53<32:35,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3094
➡️ Total Profit: ₹11,929.47
➡️ Equity Curve R²: 0.0456
➡️ Monthly Consistency Score: 0.0427

=== [2013/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.48it/s]
Hypertuning:  58%|█████▊    | 2013/3456 [46:54<32:27,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.9656
➡️ Total Profit: ₹53,674.87
➡️ Equity Curve R²: 0.1909
➡️ Monthly Consistency Score: 0.2124

=== [2014/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.68it/s]
Hypertuning:  58%|█████▊    | 2014/3456 [46:56<32:37,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.2723
➡️ Total Profit: ₹49,368.61
➡️ Equity Curve R²: 0.0057
➡️ Monthly Consistency Score: 0.1881

=== [2015/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.02it/s]
Hypertuning:  58%|█████▊    | 2015/3456 [46:57<32:47,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.6279
➡️ Total Profit: ₹76,521.18
➡️ Equity Curve R²: 0.5880
➡️ Monthly Consistency Score: 0.3302

=== [2016/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.12it/s]
Hypertuning:  58%|█████▊    | 2016/3456 [46:58<32:19,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 9.8763
➡️ Total Profit: ₹105,164.78
➡️ Equity Curve R²: 0.9079
➡️ Monthly Consistency Score: 0.5687

=== [2017/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.91it/s]
Hypertuning:  58%|█████▊    | 2017/3456 [47:00<32:16,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.7372
➡️ Total Profit: ₹-51,957.44
➡️ Equity Curve R²: 0.9597
➡️ Monthly Consistency Score: -0.2325

=== [2018/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.97it/s]
Hypertuning:  58%|█████▊    | 2018/3456 [47:01<32:34,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3225
➡️ Total Profit: ₹-23,387.92
➡️ Equity Curve R²: 0.8626
➡️ Monthly Consistency Score: -0.0978

=== [2019/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.43it/s]
Hypertuning:  58%|█████▊    | 2019/3456 [47:02<32:51,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.3410
➡️ Total Profit: ₹9,371.76
➡️ Equity Curve R²: 0.0051
➡️ Monthly Consistency Score: 0.0412

=== [2020/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.58it/s]
Hypertuning:  58%|█████▊    | 2020/3456 [47:04<32:22,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3011
➡️ Total Profit: ₹-10,228.00
➡️ Equity Curve R²: 0.3786
➡️ Monthly Consistency Score: -0.0376

=== [2021/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.77it/s]
Hypertuning:  58%|█████▊    | 2021/3456 [47:05<32:07,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.0639
➡️ Total Profit: ₹2,195.41
➡️ Equity Curve R²: 0.1065
➡️ Monthly Consistency Score: 0.0078

=== [2022/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.81it/s]
Hypertuning:  59%|█████▊    | 2022/3456 [47:06<32:22,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1422
➡️ Total Profit: ₹4,373.61
➡️ Equity Curve R²: 0.0205
➡️ Monthly Consistency Score: 0.0147

=== [2023/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.40it/s]
Hypertuning:  59%|█████▊    | 2023/3456 [47:08<31:55,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.8328
➡️ Total Profit: ₹46,303.26
➡️ Equity Curve R²: 0.7078
➡️ Monthly Consistency Score: 0.1749

=== [2024/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.41it/s]
Hypertuning:  59%|█████▊    | 2024/3456 [47:09<32:13,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1033
➡️ Total Profit: ₹-2,767.14
➡️ Equity Curve R²: 0.1821
➡️ Monthly Consistency Score: -0.0115

=== [2025/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.06it/s]
Hypertuning:  59%|█████▊    | 2025/3456 [47:10<31:58,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.7750
➡️ Total Profit: ₹17,773.24
➡️ Equity Curve R²: 0.0038
➡️ Monthly Consistency Score: 0.0630

=== [2026/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 130.37it/s]
Hypertuning:  59%|█████▊    | 2026/3456 [47:12<32:13,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.4774
➡️ Total Profit: ₹-19,208.12
➡️ Equity Curve R²: 0.5206
➡️ Monthly Consistency Score: -0.0648

=== [2027/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.29it/s]
Hypertuning:  59%|█████▊    | 2027/3456 [47:13<31:45,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: -0.3674
➡️ Total Profit: ₹-16,126.73
➡️ Equity Curve R²: 0.5546
➡️ Monthly Consistency Score: -0.0602

=== [2028/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.23it/s]
Hypertuning:  59%|█████▊    | 2028/3456 [47:15<32:18,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.7506
➡️ Total Profit: ₹-40,646.29
➡️ Equity Curve R²: 0.8121
➡️ Monthly Consistency Score: -0.1483

=== [2029/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.14it/s]
Hypertuning:  59%|█████▊    | 2029/3456 [47:16<32:47,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.4385
➡️ Total Profit: ₹54,302.62
➡️ Equity Curve R²: 0.4078
➡️ Monthly Consistency Score: 0.2037

=== [2030/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.59it/s]
Hypertuning:  59%|█████▊    | 2030/3456 [47:17<32:25,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4512
➡️ Total Profit: ₹22,846.33
➡️ Equity Curve R²: 0.5012
➡️ Monthly Consistency Score: 0.0910

=== [2031/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.02it/s]
Hypertuning:  59%|█████▉    | 2031/3456 [47:19<31:54,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.4369
➡️ Total Profit: ₹19,114.06
➡️ Equity Curve R²: 0.3096
➡️ Monthly Consistency Score: 0.0734

=== [2032/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.63it/s]
Hypertuning:  59%|█████▉    | 2032/3456 [47:20<32:04,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3391
➡️ Total Profit: ₹16,689.07
➡️ Equity Curve R²: 0.4359
➡️ Monthly Consistency Score: 0.0643

=== [2033/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.52it/s]
Hypertuning:  59%|█████▉    | 2033/3456 [47:21<31:58,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.7601
➡️ Total Profit: ₹-51,600.34
➡️ Equity Curve R²: 0.9581
➡️ Monthly Consistency Score: -0.2387

=== [2034/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.45it/s]
Hypertuning:  59%|█████▉    | 2034/3456 [47:23<32:14,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3715
➡️ Total Profit: ₹-29,037.00
➡️ Equity Curve R²: 0.8681
➡️ Monthly Consistency Score: -0.1174

=== [2035/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.68it/s]
Hypertuning:  59%|█████▉    | 2035/3456 [47:24<31:44,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.0458
➡️ Total Profit: ₹1,613.07
➡️ Equity Curve R²: 0.2595
➡️ Monthly Consistency Score: 0.0068

=== [2036/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.35it/s]
Hypertuning:  59%|█████▉    | 2036/3456 [47:25<32:03,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2544
➡️ Total Profit: ₹-8,099.82
➡️ Equity Curve R²: 0.3082
➡️ Monthly Consistency Score: -0.0297

=== [2037/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.25it/s]
Hypertuning:  59%|█████▉    | 2037/3456 [47:27<32:06,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0911
➡️ Total Profit: ₹-3,130.36
➡️ Equity Curve R²: 0.0000
➡️ Monthly Consistency Score: -0.0115

=== [2038/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.38it/s]
Hypertuning:  59%|█████▉    | 2038/3456 [47:28<32:23,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.0983
➡️ Total Profit: ₹3,244.53
➡️ Equity Curve R²: 0.0873
➡️ Monthly Consistency Score: 0.0106

=== [2039/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.57it/s]
Hypertuning:  59%|█████▉    | 2039/3456 [47:29<31:48,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.8328
➡️ Total Profit: ₹46,303.26
➡️ Equity Curve R²: 0.7078
➡️ Monthly Consistency Score: 0.1749

=== [2040/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.70it/s]
Hypertuning:  59%|█████▉    | 2040/3456 [47:31<31:56,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1033
➡️ Total Profit: ₹-2,767.14
➡️ Equity Curve R²: 0.1821
➡️ Monthly Consistency Score: -0.0115

=== [2041/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.70it/s]
Hypertuning:  59%|█████▉    | 2041/3456 [47:32<31:41,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.6776
➡️ Total Profit: ₹15,884.65
➡️ Equity Curve R²: 0.0111
➡️ Monthly Consistency Score: 0.0565

=== [2042/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.84it/s]
Hypertuning:  59%|█████▉    | 2042/3456 [47:33<31:56,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.5052
➡️ Total Profit: ₹-21,468.12
➡️ Equity Curve R²: 0.5693
➡️ Monthly Consistency Score: -0.0715

=== [2043/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.95it/s]
Hypertuning:  59%|█████▉    | 2043/3456 [47:35<32:14,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4665
➡️ Total Profit: ₹-24,278.10
➡️ Equity Curve R²: 0.6604
➡️ Monthly Consistency Score: -0.0925

=== [2044/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.30it/s]
Hypertuning:  59%|█████▉    | 2044/3456 [47:36<31:50,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.7293
➡️ Total Profit: ₹-36,382.64
➡️ Equity Curve R²: 0.7560
➡️ Monthly Consistency Score: -0.1341

=== [2045/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.05it/s]
Hypertuning:  59%|█████▉    | 2045/3456 [47:38<31:39,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.4951
➡️ Total Profit: ₹55,562.62
➡️ Equity Curve R²: 0.4157
➡️ Monthly Consistency Score: 0.2098

=== [2046/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.86it/s]
Hypertuning:  59%|█████▉    | 2046/3456 [47:39<32:04,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.3893
➡️ Total Profit: ₹20,588.17
➡️ Equity Curve R²: 0.5372
➡️ Monthly Consistency Score: 0.0808

=== [2047/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.40it/s]
Hypertuning:  59%|█████▉    | 2047/3456 [47:40<32:18,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.7347
➡️ Total Profit: ₹32,336.80
➡️ Equity Curve R²: 0.0042
➡️ Monthly Consistency Score: 0.1142

=== [2048/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.96it/s]
Hypertuning:  59%|█████▉    | 2048/3456 [47:42<31:48,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.8115
➡️ Total Profit: ₹62,769.19
➡️ Equity Curve R²: 0.6447
➡️ Monthly Consistency Score: 0.2939

=== [2049/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.07it/s]
Hypertuning:  59%|█████▉    | 2049/3456 [47:43<32:21,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.7707
➡️ Total Profit: ₹-57,622.83
➡️ Equity Curve R²: 0.9656
➡️ Monthly Consistency Score: -0.2615

=== [2050/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.48it/s]
Hypertuning:  59%|█████▉    | 2050/3456 [47:44<32:01,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2801
➡️ Total Profit: ₹-19,996.99
➡️ Equity Curve R²: 0.8560
➡️ Monthly Consistency Score: -0.0841

=== [2051/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.28it/s]
Hypertuning:  59%|█████▉    | 2051/3456 [47:46<32:16,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.2822
➡️ Total Profit: ₹-13,517.00
➡️ Equity Curve R²: 0.5420
➡️ Monthly Consistency Score: -0.0564

=== [2052/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.35it/s]
Hypertuning:  59%|█████▉    | 2052/3456 [47:47<31:48,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0727
➡️ Total Profit: ₹1,896.55
➡️ Equity Curve R²: 0.0456
➡️ Monthly Consistency Score: 0.0073

=== [2053/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.75it/s]
Hypertuning:  59%|█████▉    | 2053/3456 [47:48<31:41,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.6026
➡️ Total Profit: ₹-30,191.55
➡️ Equity Curve R²: 0.8442
➡️ Monthly Consistency Score: -0.1055

=== [2054/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.25it/s]
Hypertuning:  59%|█████▉    | 2054/3456 [47:50<32:03,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.1372
➡️ Total Profit: ₹4,375.45
➡️ Equity Curve R²: 0.0591
➡️ Monthly Consistency Score: 0.0151

=== [2055/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.34it/s]
Hypertuning:  59%|█████▉    | 2055/3456 [47:51<31:34,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.6214
➡️ Total Profit: ₹43,046.00
➡️ Equity Curve R²: 0.6608
➡️ Monthly Consistency Score: 0.1629

=== [2056/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.71it/s]
Hypertuning:  59%|█████▉    | 2056/3456 [47:53<31:40,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1032
➡️ Total Profit: ₹-2,763.50
➡️ Equity Curve R²: 0.1979
➡️ Monthly Consistency Score: -0.0115

=== [2057/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.08it/s]
Hypertuning:  60%|█████▉    | 2057/3456 [47:54<31:36,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2801
➡️ Total Profit: ₹9,527.64
➡️ Equity Curve R²: 0.3386
➡️ Monthly Consistency Score: 0.0338

=== [2058/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.63it/s]
Hypertuning:  60%|█████▉    | 2058/3456 [47:55<31:52,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.6817
➡️ Total Profit: ₹39,903.01
➡️ Equity Curve R²: 0.6186
➡️ Monthly Consistency Score: 0.1508

=== [2059/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.51it/s]
Hypertuning:  60%|█████▉    | 2059/3456 [47:57<31:19,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2617
➡️ Total Profit: ₹-9,606.73
➡️ Equity Curve R²: 0.4214
➡️ Monthly Consistency Score: -0.0376

=== [2060/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 131.47it/s]
Hypertuning:  60%|█████▉    | 2060/3456 [47:58<31:29,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6133
➡️ Total Profit: ₹-27,862.64
➡️ Equity Curve R²: 0.6847
➡️ Monthly Consistency Score: -0.1065

=== [2061/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.00it/s]
Hypertuning:  60%|█████▉    | 2061/3456 [47:59<32:03,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.3293
➡️ Total Profit: ₹34,364.41
➡️ Equity Curve R²: 0.0058
➡️ Monthly Consistency Score: 0.1300

=== [2062/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.99it/s]
Hypertuning:  60%|█████▉    | 2062/3456 [48:01<31:39,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.1261
➡️ Total Profit: ₹39,797.25
➡️ Equity Curve R²: 0.0415
➡️ Monthly Consistency Score: 0.1621

=== [2063/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.29it/s]
Hypertuning:  60%|█████▉    | 2063/3456 [48:02<31:54,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.6497
➡️ Total Profit: ₹30,710.91
➡️ Equity Curve R²: 0.0000
➡️ Monthly Consistency Score: 0.1134

=== [2064/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.31it/s]
Hypertuning:  60%|█████▉    | 2064/3456 [48:03<31:28,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.3391
➡️ Total Profit: ₹16,689.07
➡️ Equity Curve R²: 0.4359
➡️ Monthly Consistency Score: 0.0643

=== [2065/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.41it/s]
Hypertuning:  60%|█████▉    | 2065/3456 [48:05<31:18,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.7461
➡️ Total Profit: ₹-52,587.91
➡️ Equity Curve R²: 0.9599
➡️ Monthly Consistency Score: -0.2349

=== [2066/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.95it/s]
Hypertuning:  60%|█████▉    | 2066/3456 [48:06<31:32,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3118
➡️ Total Profit: ₹-22,258.83
➡️ Equity Curve R²: 0.8587
➡️ Monthly Consistency Score: -0.0928

=== [2067/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.42it/s]
Hypertuning:  60%|█████▉    | 2067/3456 [48:08<31:47,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.3410
➡️ Total Profit: ₹9,371.76
➡️ Equity Curve R²: 0.0051
➡️ Monthly Consistency Score: 0.0412

=== [2068/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.77it/s]
Hypertuning:  60%|█████▉    | 2068/3456 [48:09<31:21,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2544
➡️ Total Profit: ₹-8,099.82
➡️ Equity Curve R²: 0.3082
➡️ Monthly Consistency Score: -0.0297

=== [2069/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.82it/s]
Hypertuning:  60%|█████▉    | 2069/3456 [48:10<31:03,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.0639
➡️ Total Profit: ₹2,195.41
➡️ Equity Curve R²: 0.1065
➡️ Monthly Consistency Score: 0.0078

=== [2070/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.04it/s]
Hypertuning:  60%|█████▉    | 2070/3456 [48:12<31:16,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4381
➡️ Total Profit: ₹12,980.85
➡️ Equity Curve R²: 0.0071
➡️ Monthly Consistency Score: 0.0429

=== [2071/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.31it/s]
Hypertuning:  60%|█████▉    | 2071/3456 [48:13<30:47,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 2.8328
➡️ Total Profit: ₹46,303.26
➡️ Equity Curve R²: 0.7078
➡️ Monthly Consistency Score: 0.1749

=== [2072/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 110.65it/s]
Hypertuning:  60%|█████▉    | 2072/3456 [48:14<31:03,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1033
➡️ Total Profit: ₹-2,767.14
➡️ Equity Curve R²: 0.1821
➡️ Monthly Consistency Score: -0.0115

=== [2073/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.23it/s]
Hypertuning:  60%|█████▉    | 2073/3456 [48:16<31:52,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.7750
➡️ Total Profit: ₹17,773.24
➡️ Equity Curve R²: 0.0038
➡️ Monthly Consistency Score: 0.0630

=== [2074/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.88it/s]
Hypertuning:  60%|██████    | 2074/3456 [48:17<31:23,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4794
➡️ Total Profit: ₹-19,208.12
➡️ Equity Curve R²: 0.5170
➡️ Monthly Consistency Score: -0.0649

=== [2075/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.21it/s]
Hypertuning:  60%|██████    | 2075/3456 [48:18<31:36,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3674
➡️ Total Profit: ₹-16,126.73
➡️ Equity Curve R²: 0.5546
➡️ Monthly Consistency Score: -0.0602

=== [2076/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.35it/s]
Hypertuning:  60%|██████    | 2076/3456 [48:20<31:07,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.7506
➡️ Total Profit: ₹-40,646.29
➡️ Equity Curve R²: 0.8121
➡️ Monthly Consistency Score: -0.1483

=== [2077/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.51it/s]
Hypertuning:  60%|██████    | 2077/3456 [48:21<30:53,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.3654
➡️ Total Profit: ₹45,905.43
➡️ Equity Curve R²: 0.0261
➡️ Monthly Consistency Score: 0.1841

=== [2078/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.60it/s]
Hypertuning:  60%|██████    | 2078/3456 [48:22<31:27,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.3892
➡️ Total Profit: ₹20,584.49
➡️ Equity Curve R²: 0.5424
➡️ Monthly Consistency Score: 0.0819

=== [2079/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.58it/s]
Hypertuning:  60%|██████    | 2079/3456 [48:24<30:59,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3853
➡️ Total Profit: ₹17,485.43
➡️ Equity Curve R²: 0.3487
➡️ Monthly Consistency Score: 0.0669

=== [2080/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.53it/s]
Hypertuning:  60%|██████    | 2080/3456 [48:25<31:05,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.3391
➡️ Total Profit: ₹16,689.07
➡️ Equity Curve R²: 0.4359
➡️ Monthly Consistency Score: 0.0643

=== [2081/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.01it/s]
Hypertuning:  60%|██████    | 2081/3456 [48:26<30:56,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.7583
➡️ Total Profit: ₹-53,773.96
➡️ Equity Curve R²: 0.9637
➡️ Monthly Consistency Score: -0.2487

=== [2082/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.84it/s]
Hypertuning:  60%|██████    | 2082/3456 [48:28<31:44,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.3430
➡️ Total Profit: ₹-25,647.92
➡️ Equity Curve R²: 0.8633
➡️ Monthly Consistency Score: -0.1038

=== [2083/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.57it/s]
Hypertuning:  60%|██████    | 2083/3456 [48:29<31:46,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 0.1043
➡️ Total Profit: ₹3,247.18
➡️ Equity Curve R²: 0.0456
➡️ Monthly Consistency Score: 0.0147

=== [2084/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.05it/s]
Hypertuning:  60%|██████    | 2084/3456 [48:31<31:10,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2544
➡️ Total Profit: ₹-8,099.82
➡️ Equity Curve R²: 0.3082
➡️ Monthly Consistency Score: -0.0297

=== [2085/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.00it/s]
Hypertuning:  60%|██████    | 2085/3456 [48:32<31:41,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.5757
➡️ Total Profit: ₹-25,309.54
➡️ Equity Curve R²: 0.8014
➡️ Monthly Consistency Score: -0.0943

=== [2086/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.66it/s]
Hypertuning:  60%|██████    | 2086/3456 [48:33<31:32,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.2905
➡️ Total Profit: ₹9,591.77
➡️ Equity Curve R²: 0.0784
➡️ Monthly Consistency Score: 0.0311

=== [2087/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.02it/s]
Hypertuning:  60%|██████    | 2087/3456 [48:35<31:38,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 2.7331
➡️ Total Profit: ₹44,674.63
➡️ Equity Curve R²: 0.6888
➡️ Monthly Consistency Score: 0.1691

=== [2088/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.09it/s]
Hypertuning:  60%|██████    | 2088/3456 [48:36<31:05,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1033
➡️ Total Profit: ₹-2,767.14
➡️ Equity Curve R²: 0.1821
➡️ Monthly Consistency Score: -0.0115

=== [2089/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.37it/s]
Hypertuning:  60%|██████    | 2089/3456 [48:38<31:35,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 0.1938
➡️ Total Profit: ₹6,432.30
➡️ Equity Curve R²: 0.4769
➡️ Monthly Consistency Score: 0.0227

=== [2090/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.72it/s]
Hypertuning:  60%|██████    | 2090/3456 [48:39<31:25,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.3456
➡️ Total Profit: ₹-14,686.28
➡️ Equity Curve R²: 0.3097
➡️ Monthly Consistency Score: -0.0482

=== [2091/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.45it/s]
Hypertuning:  61%|██████    | 2091/3456 [48:40<30:58,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2932
➡️ Total Profit: ₹-12,869.47
➡️ Equity Curve R²: 0.5364
➡️ Monthly Consistency Score: -0.0470

=== [2092/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.95it/s]
Hypertuning:  61%|██████    | 2092/3456 [48:42<31:08,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.7506
➡️ Total Profit: ₹-40,646.29
➡️ Equity Curve R²: 0.8121
➡️ Monthly Consistency Score: -0.1483

=== [2093/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.61it/s]
Hypertuning:  61%|██████    | 2093/3456 [48:43<30:55,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.5517
➡️ Total Profit: ₹56,821.68
➡️ Equity Curve R²: 0.4309
➡️ Monthly Consistency Score: 0.2142

=== [2094/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.47it/s]
Hypertuning:  61%|██████    | 2094/3456 [48:44<31:08,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.3941
➡️ Total Profit: ₹21,409.19
➡️ Equity Curve R²: 0.3633
➡️ Monthly Consistency Score: 0.0807

=== [2095/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.42it/s]
Hypertuning:  61%|██████    | 2095/3456 [48:46<30:34,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4932
➡️ Total Profit: ₹22,379.54
➡️ Equity Curve R²: 0.2800
➡️ Monthly Consistency Score: 0.0890

=== [2096/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.52it/s]
Hypertuning:  61%|██████    | 2096/3456 [48:47<30:44,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.3391
➡️ Total Profit: ₹16,689.07
➡️ Equity Curve R²: 0.4359
➡️ Monthly Consistency Score: 0.0643

=== [2097/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.10it/s]
Hypertuning:  61%|██████    | 2097/3456 [48:49<31:20,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.7345
➡️ Total Profit: ₹-53,777.72
➡️ Equity Curve R²: 0.9570
➡️ Monthly Consistency Score: -0.2438

=== [2098/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.67it/s]
Hypertuning:  61%|██████    | 2098/3456 [48:50<31:17,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.3594
➡️ Total Profit: ₹-27,907.92
➡️ Equity Curve R²: 0.8784
➡️ Monthly Consistency Score: -0.1125

=== [2099/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.76it/s]
Hypertuning:  61%|██████    | 2099/3456 [48:51<30:41,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1563
➡️ Total Profit: ₹-5,365.62
➡️ Equity Curve R²: 0.5743
➡️ Monthly Consistency Score: -0.0236

=== [2100/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.16it/s]
Hypertuning:  61%|██████    | 2100/3456 [48:53<30:49,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0949
➡️ Total Profit: ₹-3,013.55
➡️ Equity Curve R²: 0.1906
➡️ Monthly Consistency Score: -0.0114

=== [2101/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.04it/s]
Hypertuning:  61%|██████    | 2101/3456 [48:54<31:22,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.5567
➡️ Total Profit: ₹-26,587.90
➡️ Equity Curve R²: 0.8184
➡️ Monthly Consistency Score: -0.0928

=== [2102/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.78it/s]
Hypertuning:  61%|██████    | 2102/3456 [48:55<30:53,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.1097
➡️ Total Profit: ₹3,668.33
➡️ Equity Curve R²: 0.4672
➡️ Monthly Consistency Score: 0.0130

=== [2103/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.30it/s]
Hypertuning:  61%|██████    | 2103/3456 [48:57<30:23,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.7911
➡️ Total Profit: ₹16,888.74
➡️ Equity Curve R²: 0.2206
➡️ Monthly Consistency Score: 0.0620

=== [2104/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.38it/s]
Hypertuning:  61%|██████    | 2104/3456 [48:58<30:36,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.5781
➡️ Total Profit: ₹-28,327.14
➡️ Equity Curve R²: 0.7324
➡️ Monthly Consistency Score: -0.1128

=== [2105/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 129.52it/s]
Hypertuning:  61%|██████    | 2105/3456 [48:59<30:18,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0124
➡️ Total Profit: ₹-501.93
➡️ Equity Curve R²: 0.6035
➡️ Monthly Consistency Score: -0.0018

=== [2106/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.70it/s]
Hypertuning:  61%|██████    | 2106/3456 [49:01<30:31,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2809
➡️ Total Profit: ₹11,302.81
➡️ Equity Curve R²: 0.0126
➡️ Monthly Consistency Score: 0.0438

=== [2107/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.68it/s]
Hypertuning:  61%|██████    | 2107/3456 [49:02<30:47,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.0197
➡️ Total Profit: ₹524.07
➡️ Equity Curve R²: 0.0676
➡️ Monthly Consistency Score: 0.0021

=== [2108/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.43it/s]
Hypertuning:  61%|██████    | 2108/3456 [49:03<30:23,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.7541
➡️ Total Profit: ₹-38,510.82
➡️ Equity Curve R²: 0.7640
➡️ Monthly Consistency Score: -0.1417

=== [2109/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.95it/s]
Hypertuning:  61%|██████    | 2109/3456 [49:05<30:16,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.8894
➡️ Total Profit: ₹41,293.00
➡️ Equity Curve R²: 0.0955
➡️ Monthly Consistency Score: 0.1587

=== [2110/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.07it/s]
Hypertuning:  61%|██████    | 2110/3456 [49:06<30:38,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.0431
➡️ Total Profit: ₹38,668.17
➡️ Equity Curve R²: 0.0770
➡️ Monthly Consistency Score: 0.1481

=== [2111/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.82it/s]
Hypertuning:  61%|██████    | 2111/3456 [49:08<30:38,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.1963
➡️ Total Profit: ₹9,514.05
➡️ Equity Curve R²: 0.4323
➡️ Monthly Consistency Score: 0.0331

=== [2112/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.19it/s]
Hypertuning:  61%|██████    | 2112/3456 [49:09<30:11,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1125
➡️ Total Profit: ₹6,044.52
➡️ Equity Curve R²: 0.5506
➡️ Monthly Consistency Score: 0.0229

=== [2113/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.20it/s]
Hypertuning:  61%|██████    | 2113/3456 [49:10<30:43,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.6822
➡️ Total Profit: ₹-49,919.22
➡️ Equity Curve R²: 0.9423
➡️ Monthly Consistency Score: -0.2217

=== [2114/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.62it/s]
Hypertuning:  61%|██████    | 2114/3456 [49:12<30:19,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1288
➡️ Total Profit: ₹5,992.41
➡️ Equity Curve R²: 0.5823
➡️ Monthly Consistency Score: 0.0259

=== [2115/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.54it/s]
Hypertuning:  61%|██████    | 2115/3456 [49:13<30:34,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.6000
➡️ Total Profit: ₹15,820.87
➡️ Equity Curve R²: 0.0708
➡️ Monthly Consistency Score: 0.0648

=== [2116/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.67it/s]
Hypertuning:  61%|██████    | 2116/3456 [49:14<30:11,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0603
➡️ Total Profit: ₹-1,811.20
➡️ Equity Curve R²: 0.0926
➡️ Monthly Consistency Score: -0.0069

=== [2117/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.09it/s]
Hypertuning:  61%|██████▏   | 2117/3456 [49:16<30:02,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.5583
➡️ Total Profit: ₹-27,651.81
➡️ Equity Curve R²: 0.7979
➡️ Monthly Consistency Score: -0.1067

=== [2118/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.74it/s]
Hypertuning:  61%|██████▏   | 2118/3456 [49:17<30:20,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1430
➡️ Total Profit: ₹4,112.13
➡️ Equity Curve R²: 0.2054
➡️ Monthly Consistency Score: 0.0173

=== [2119/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.30it/s]
Hypertuning:  61%|██████▏   | 2119/3456 [49:18<29:59,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.1167
➡️ Total Profit: ₹21,896.63
➡️ Equity Curve R²: 0.2540
➡️ Monthly Consistency Score: 0.0926

=== [2120/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.69it/s]
Hypertuning:  61%|██████▏   | 2120/3456 [49:20<30:10,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.5864
➡️ Total Profit: ₹-20,713.36
➡️ Equity Curve R²: 0.5965
➡️ Monthly Consistency Score: -0.0923

=== [2121/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.50it/s]
Hypertuning:  61%|██████▏   | 2121/3456 [49:21<29:56,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1633
➡️ Total Profit: ₹-9,149.96
➡️ Equity Curve R²: 0.7653
➡️ Monthly Consistency Score: -0.0322

=== [2122/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.87it/s]
Hypertuning:  61%|██████▏   | 2122/3456 [49:22<30:10,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.6823
➡️ Total Profit: ₹63,637.62
➡️ Equity Curve R²: 0.6488
➡️ Monthly Consistency Score: 0.2586

=== [2123/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.84it/s]
Hypertuning:  61%|██████▏   | 2123/3456 [49:24<30:28,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.6177
➡️ Total Profit: ₹35,794.83
➡️ Equity Curve R²: 0.1342
➡️ Monthly Consistency Score: 0.1524

=== [2124/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.42it/s]
Hypertuning:  61%|██████▏   | 2124/3456 [49:25<30:00,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3040
➡️ Total Profit: ₹9,781.08
➡️ Equity Curve R²: 0.0265
➡️ Monthly Consistency Score: 0.0379

=== [2125/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.89it/s]
Hypertuning:  61%|██████▏   | 2125/3456 [49:27<29:50,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.2382
➡️ Total Profit: ₹29,112.01
➡️ Equity Curve R²: 0.4224
➡️ Monthly Consistency Score: 0.1053

=== [2126/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.88it/s]
Hypertuning:  62%|██████▏   | 2126/3456 [49:28<30:00,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.5419
➡️ Total Profit: ₹62,620.12
➡️ Equity Curve R²: 0.3548
➡️ Monthly Consistency Score: 0.2578

=== [2127/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.32it/s]
Hypertuning:  62%|██████▏   | 2127/3456 [49:29<30:15,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.4905
➡️ Total Profit: ₹68,283.31
➡️ Equity Curve R²: 0.6510
➡️ Monthly Consistency Score: 0.2813

=== [2128/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.17it/s]
Hypertuning:  62%|██████▏   | 2128/3456 [49:31<29:50,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.7918
➡️ Total Profit: ₹67,604.66
➡️ Equity Curve R²: 0.6545
➡️ Monthly Consistency Score: 0.2896

=== [2129/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.66it/s]
Hypertuning:  62%|██████▏   | 2129/3456 [49:32<30:26,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.6709
➡️ Total Profit: ₹-50,543.39
➡️ Equity Curve R²: 0.9435
➡️ Monthly Consistency Score: -0.2261

=== [2130/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.18it/s]
Hypertuning:  62%|██████▏   | 2130/3456 [49:33<30:06,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2437
➡️ Total Profit: ₹10,514.25
➡️ Equity Curve R²: 0.5338
➡️ Monthly Consistency Score: 0.0440

=== [2131/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.48it/s]
Hypertuning:  62%|██████▏   | 2131/3456 [49:35<29:36,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.1720
➡️ Total Profit: ₹6,430.81
➡️ Equity Curve R²: 0.4940
➡️ Monthly Consistency Score: 0.0262

=== [2132/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 132.21it/s]
Hypertuning:  62%|██████▏   | 2132/3456 [49:36<29:45,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0357
➡️ Total Profit: ₹-1,072.05
➡️ Equity Curve R²: 0.0878
➡️ Monthly Consistency Score: -0.0041

=== [2133/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.54it/s]
Hypertuning:  62%|██████▏   | 2133/3456 [49:37<29:38,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.5595
➡️ Total Profit: ₹-29,375.82
➡️ Equity Curve R²: 0.8371
➡️ Monthly Consistency Score: -0.1100

=== [2134/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 107.69it/s]
Hypertuning:  62%|██████▏   | 2134/3456 [49:39<29:52,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1389
➡️ Total Profit: ₹-5,273.40
➡️ Equity Curve R²: 0.5823
➡️ Monthly Consistency Score: -0.0218

=== [2135/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.54it/s]
Hypertuning:  62%|██████▏   | 2135/3456 [49:40<29:24,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.1987
➡️ Total Profit: ₹23,504.89
➡️ Equity Curve R²: 0.3438
➡️ Monthly Consistency Score: 0.0991

=== [2136/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.47it/s]
Hypertuning:  62%|██████▏   | 2136/3456 [49:41<29:43,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.5864
➡️ Total Profit: ₹-20,713.36
➡️ Equity Curve R²: 0.5965
➡️ Monthly Consistency Score: -0.0923

=== [2137/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 131.57it/s]
Hypertuning:  62%|██████▏   | 2137/3456 [49:43<29:37,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2727
➡️ Total Profit: ₹10,891.92
➡️ Equity Curve R²: 0.3903
➡️ Monthly Consistency Score: 0.0386

=== [2138/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.98it/s]
Hypertuning:  62%|██████▏   | 2138/3456 [49:44<29:46,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.7164
➡️ Total Profit: ₹61,381.30
➡️ Equity Curve R²: 0.5724
➡️ Monthly Consistency Score: 0.2462

=== [2139/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.51it/s]
Hypertuning:  62%|██████▏   | 2139/3456 [49:46<29:57,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.8388
➡️ Total Profit: ₹40,686.20
➡️ Equity Curve R²: 0.0898
➡️ Monthly Consistency Score: 0.1734

=== [2140/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.02it/s]
Hypertuning:  62%|██████▏   | 2140/3456 [49:47<29:31,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3041
➡️ Total Profit: ₹9,784.72
➡️ Equity Curve R²: 0.0308
➡️ Monthly Consistency Score: 0.0379

=== [2141/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.90it/s]
Hypertuning:  62%|██████▏   | 2141/3456 [49:48<29:26,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.3722
➡️ Total Profit: ₹32,263.42
➡️ Equity Curve R²: 0.4684
➡️ Monthly Consistency Score: 0.1193

=== [2142/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.57it/s]
Hypertuning:  62%|██████▏   | 2142/3456 [49:50<29:43,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.2855
➡️ Total Profit: ₹45,141.95
➡️ Equity Curve R²: 0.0031
➡️ Monthly Consistency Score: 0.1927

=== [2143/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.37it/s]
Hypertuning:  62%|██████▏   | 2143/3456 [49:51<29:15,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 3.4905
➡️ Total Profit: ₹68,283.31
➡️ Equity Curve R²: 0.6510
➡️ Monthly Consistency Score: 0.2813

=== [2144/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.53it/s]
Hypertuning:  62%|██████▏   | 2144/3456 [49:52<29:28,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 5.9565
➡️ Total Profit: ₹76,124.66
➡️ Equity Curve R²: 0.8507
➡️ Monthly Consistency Score: 0.3415

=== [2145/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.12it/s]
Hypertuning:  62%|██████▏   | 2145/3456 [49:54<30:04,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.7384
➡️ Total Profit: ₹-56,565.89
➡️ Equity Curve R²: 0.9542
➡️ Monthly Consistency Score: -0.2613

=== [2146/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.37it/s]
Hypertuning:  62%|██████▏   | 2146/3456 [49:55<29:42,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1261
➡️ Total Profit: ₹-6,611.31
➡️ Equity Curve R²: 0.8206
➡️ Monthly Consistency Score: -0.0274

=== [2147/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.35it/s]
Hypertuning:  62%|██████▏   | 2147/3456 [49:56<29:16,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.2736
➡️ Total Profit: ₹8,446.64
➡️ Equity Curve R²: 0.3626
➡️ Monthly Consistency Score: 0.0367

=== [2148/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.63it/s]
Hypertuning:  62%|██████▏   | 2148/3456 [49:58<29:25,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4024
➡️ Total Profit: ₹10,400.67
➡️ Equity Curve R²: 0.0911
➡️ Monthly Consistency Score: 0.0397

=== [2149/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.90it/s]
Hypertuning:  62%|██████▏   | 2149/3456 [49:59<30:01,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.5280
➡️ Total Profit: ₹-28,118.64
➡️ Equity Curve R²: 0.8336
➡️ Monthly Consistency Score: -0.1035

=== [2150/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.55it/s]
Hypertuning:  62%|██████▏   | 2150/3456 [50:00<29:39,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0678
➡️ Total Profit: ₹1,926.49
➡️ Equity Curve R²: 0.2452
➡️ Monthly Consistency Score: 0.0081

=== [2151/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.86it/s]
Hypertuning:  62%|██████▏   | 2151/3456 [50:02<29:08,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.2012
➡️ Total Profit: ₹21,876.26
➡️ Equity Curve R²: 0.3299
➡️ Monthly Consistency Score: 0.0930

=== [2152/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.68it/s]
Hypertuning:  62%|██████▏   | 2152/3456 [50:03<29:23,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3927
➡️ Total Profit: ₹-9,448.74
➡️ Equity Curve R²: 0.1394
➡️ Monthly Consistency Score: -0.0396

=== [2153/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.09it/s]
Hypertuning:  62%|██████▏   | 2153/3456 [50:04<29:14,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2744
➡️ Total Profit: ₹-17,967.15
➡️ Equity Curve R²: 0.8290
➡️ Monthly Consistency Score: -0.0615

=== [2154/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.44it/s]
Hypertuning:  62%|██████▏   | 2154/3456 [50:06<29:31,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.7124
➡️ Total Profit: ₹38,693.89
➡️ Equity Curve R²: 0.5760
➡️ Monthly Consistency Score: 0.1453

=== [2155/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.13it/s]
Hypertuning:  62%|██████▏   | 2155/3456 [50:07<29:08,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.8497
➡️ Total Profit: ₹18,800.31
➡️ Equity Curve R²: 0.0131
➡️ Monthly Consistency Score: 0.0751

=== [2156/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.44it/s]
Hypertuning:  62%|██████▏   | 2156/3456 [50:09<29:29,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.5558
➡️ Total Profit: ₹-27,860.64
➡️ Equity Curve R²: 0.7755
➡️ Monthly Consistency Score: -0.1039

=== [2157/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.83it/s]
Hypertuning:  62%|██████▏   | 2157/3456 [50:10<29:21,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.6025
➡️ Total Profit: ₹36,671.07
➡️ Equity Curve R²: 0.5321
➡️ Monthly Consistency Score: 0.1377

=== [2158/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.53it/s]
Hypertuning:  62%|██████▏   | 2158/3456 [50:11<29:34,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.2453
➡️ Total Profit: ₹45,140.11
➡️ Equity Curve R²: 0.0013
➡️ Monthly Consistency Score: 0.1900

=== [2159/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.79it/s]
Hypertuning:  62%|██████▏   | 2159/3456 [50:13<29:05,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.1573
➡️ Total Profit: ₹61,766.04
➡️ Equity Curve R²: 0.6769
➡️ Monthly Consistency Score: 0.2554

=== [2160/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.87it/s]
Hypertuning:  62%|██████▎   | 2160/3456 [50:14<29:15,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.2766
➡️ Total Profit: ₹39,348.29
➡️ Equity Curve R²: 0.0092
➡️ Monthly Consistency Score: 0.1618

=== [2161/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.57it/s]
Hypertuning:  63%|██████▎   | 2161/3456 [50:15<29:06,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.7363
➡️ Total Profit: ₹-55,028.75
➡️ Equity Curve R²: 0.9577
➡️ Monthly Consistency Score: -0.2453

=== [2162/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.50it/s]
Hypertuning:  63%|██████▎   | 2162/3456 [50:17<29:15,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2175
➡️ Total Profit: ₹9,381.49
➡️ Equity Curve R²: 0.5167
➡️ Monthly Consistency Score: 0.0402

=== [2163/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.48it/s]
Hypertuning:  63%|██████▎   | 2163/3456 [50:18<29:31,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.2828
➡️ Total Profit: ₹9,300.87
➡️ Equity Curve R²: 0.3504
➡️ Monthly Consistency Score: 0.0380

=== [2164/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.26it/s]
Hypertuning:  63%|██████▎   | 2164/3456 [50:19<29:07,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3064
➡️ Total Profit: ₹-12,463.02
➡️ Equity Curve R²: 0.4003
➡️ Monthly Consistency Score: -0.0443

=== [2165/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.10it/s]
Hypertuning:  63%|██████▎   | 2165/3456 [50:21<28:58,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.5583
➡️ Total Profit: ₹-27,651.81
➡️ Equity Curve R²: 0.7979
➡️ Monthly Consistency Score: -0.1067

=== [2166/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.78it/s]
Hypertuning:  63%|██████▎   | 2166/3456 [50:22<29:16,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4423
➡️ Total Profit: ₹12,719.37
➡️ Equity Curve R²: 0.1314
➡️ Monthly Consistency Score: 0.0524

=== [2167/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.40it/s]
Hypertuning:  63%|██████▎   | 2167/3456 [50:23<28:52,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.1167
➡️ Total Profit: ₹21,896.63
➡️ Equity Curve R²: 0.2540
➡️ Monthly Consistency Score: 0.0926

=== [2168/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.97it/s]
Hypertuning:  63%|██████▎   | 2168/3456 [50:25<29:03,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.5864
➡️ Total Profit: ₹-20,713.36
➡️ Equity Curve R²: 0.5965
➡️ Monthly Consistency Score: -0.0923

=== [2169/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.63it/s]
Hypertuning:  63%|██████▎   | 2169/3456 [50:26<28:52,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1633
➡️ Total Profit: ₹-9,149.96
➡️ Equity Curve R²: 0.7653
➡️ Monthly Consistency Score: -0.0322

=== [2170/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.46it/s]
Hypertuning:  63%|██████▎   | 2170/3456 [50:27<29:03,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.8662
➡️ Total Profit: ₹64,766.70
➡️ Equity Curve R²: 0.6750
➡️ Monthly Consistency Score: 0.2625

=== [2171/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.05it/s]
Hypertuning:  63%|██████▎   | 2171/3456 [50:29<29:19,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.6177
➡️ Total Profit: ₹35,794.83
➡️ Equity Curve R²: 0.1342
➡️ Monthly Consistency Score: 0.1524

=== [2172/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.92it/s]
Hypertuning:  63%|██████▎   | 2172/3456 [50:30<28:54,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3040
➡️ Total Profit: ₹9,781.08
➡️ Equity Curve R²: 0.0265
➡️ Monthly Consistency Score: 0.0379

=== [2173/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.40it/s]
Hypertuning:  63%|██████▎   | 2173/3456 [50:31<28:47,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.2382
➡️ Total Profit: ₹29,112.01
➡️ Equity Curve R²: 0.4224
➡️ Monthly Consistency Score: 0.1053

=== [2174/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.10it/s]
Hypertuning:  63%|██████▎   | 2174/3456 [50:33<29:06,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.5419
➡️ Total Profit: ₹62,620.12
➡️ Equity Curve R²: 0.3548
➡️ Monthly Consistency Score: 0.2578

=== [2175/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.10it/s]
Hypertuning:  63%|██████▎   | 2175/3456 [50:34<28:42,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.4905
➡️ Total Profit: ₹68,283.31
➡️ Equity Curve R²: 0.6510
➡️ Monthly Consistency Score: 0.2813

=== [2176/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.10it/s]
Hypertuning:  63%|██████▎   | 2176/3456 [50:36<28:49,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.7918
➡️ Total Profit: ₹67,604.66
➡️ Equity Curve R²: 0.6545
➡️ Monthly Consistency Score: 0.2896

=== [2177/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.97it/s]
Hypertuning:  63%|██████▎   | 2177/3456 [50:37<29:24,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.7254
➡️ Total Profit: ₹-56,846.21
➡️ Equity Curve R²: 0.9531
➡️ Monthly Consistency Score: -0.2605

=== [2178/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.73it/s]
Hypertuning:  63%|██████▎   | 2178/3456 [50:38<28:59,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2437
➡️ Total Profit: ₹10,512.41
➡️ Equity Curve R²: 0.4924
➡️ Monthly Consistency Score: 0.0445

=== [2179/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.20it/s]
Hypertuning:  63%|██████▎   | 2179/3456 [50:40<28:30,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.2334
➡️ Total Profit: ₹6,823.49
➡️ Equity Curve R²: 0.3368
➡️ Monthly Consistency Score: 0.0294

=== [2180/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.61it/s]
Hypertuning:  63%|██████▎   | 2180/3456 [50:41<28:38,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2628
➡️ Total Profit: ₹6,792.49
➡️ Equity Curve R²: 0.0060
➡️ Monthly Consistency Score: 0.0256

=== [2181/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.80it/s]
Hypertuning:  63%|██████▎   | 2181/3456 [50:42<29:12,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.5063
➡️ Total Profit: ₹-24,501.33
➡️ Equity Curve R²: 0.7833
➡️ Monthly Consistency Score: -0.0948

=== [2182/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.16it/s]
Hypertuning:  63%|██████▎   | 2182/3456 [50:44<28:51,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.7784
➡️ Total Profit: ₹22,110.17
➡️ Equity Curve R²: 0.0743
➡️ Monthly Consistency Score: 0.0867

=== [2183/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.29it/s]
Hypertuning:  63%|██████▎   | 2183/3456 [50:45<28:31,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.6263
➡️ Total Profit: ₹15,356.26
➡️ Equity Curve R²: 0.1118
➡️ Monthly Consistency Score: 0.0641

=== [2184/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.76it/s]
Hypertuning:  63%|██████▎   | 2184/3456 [50:46<28:44,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.5864
➡️ Total Profit: ₹-20,713.36
➡️ Equity Curve R²: 0.5965
➡️ Monthly Consistency Score: -0.0923

=== [2185/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.06it/s]
Hypertuning:  63%|██████▎   | 2185/3456 [50:48<28:35,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2254
➡️ Total Profit: ₹9,002.39
➡️ Equity Curve R²: 0.4330
➡️ Monthly Consistency Score: 0.0320

=== [2186/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.13it/s]
Hypertuning:  63%|██████▎   | 2186/3456 [50:49<28:51,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.6664
➡️ Total Profit: ₹60,250.38
➡️ Equity Curve R²: 0.5767
➡️ Monthly Consistency Score: 0.2423

=== [2187/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.56it/s]
Hypertuning:  63%|██████▎   | 2187/3456 [50:50<28:22,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.5441
➡️ Total Profit: ₹34,166.20
➡️ Equity Curve R²: 0.1187
➡️ Monthly Consistency Score: 0.1457

=== [2188/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.51it/s]
Hypertuning:  63%|██████▎   | 2188/3456 [50:52<28:36,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1450
➡️ Total Profit: ₹5,521.08
➡️ Equity Curve R²: 0.0138
➡️ Monthly Consistency Score: 0.0201

=== [2189/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.50it/s]
Hypertuning:  63%|██████▎   | 2189/3456 [50:53<28:29,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.4925
➡️ Total Profit: ₹34,152.95
➡️ Equity Curve R²: 0.4915
➡️ Monthly Consistency Score: 0.1279

=== [2190/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.74it/s]
Hypertuning:  63%|██████▎   | 2190/3456 [50:55<28:53,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1830
➡️ Total Profit: ₹42,880.11
➡️ Equity Curve R²: 0.0005
➡️ Monthly Consistency Score: 0.1821

=== [2191/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.88it/s]
Hypertuning:  63%|██████▎   | 2191/3456 [50:56<28:27,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.3240
➡️ Total Profit: ₹65,026.05
➡️ Equity Curve R²: 0.6835
➡️ Monthly Consistency Score: 0.2740

=== [2192/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.54it/s]
Hypertuning:  63%|██████▎   | 2192/3456 [50:57<28:40,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.7918
➡️ Total Profit: ₹67,604.66
➡️ Equity Curve R²: 0.6545
➡️ Monthly Consistency Score: 0.2896

=== [2193/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.52it/s]
Hypertuning:  63%|██████▎   | 2193/3456 [50:59<29:14,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.7145
➡️ Total Profit: ₹-48,937.29
➡️ Equity Curve R²: 0.9219
➡️ Monthly Consistency Score: -0.2226

=== [2194/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.34it/s]
Hypertuning:  63%|██████▎   | 2194/3456 [51:00<28:56,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.1655
➡️ Total Profit: ₹-9,292.95
➡️ Equity Curve R²: 0.7540
➡️ Monthly Consistency Score: -0.0375

=== [2195/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.55it/s]
Hypertuning:  64%|██████▎   | 2195/3456 [51:01<28:26,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.8900
➡️ Total Profit: ₹19,468.07
➡️ Equity Curve R²: 0.0009
➡️ Monthly Consistency Score: 0.0826

=== [2196/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.02it/s]
Hypertuning:  64%|██████▎   | 2196/3456 [51:03<28:41,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1890
➡️ Total Profit: ₹-7,374.84
➡️ Equity Curve R²: 0.0580
➡️ Monthly Consistency Score: -0.0257

=== [2197/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.77it/s]
Hypertuning:  64%|██████▎   | 2197/3456 [51:04<29:15,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.4676
➡️ Total Profit: ₹-22,624.52
➡️ Equity Curve R²: 0.7914
➡️ Monthly Consistency Score: -0.0835

=== [2198/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.49it/s]
Hypertuning:  64%|██████▎   | 2198/3456 [51:06<28:53,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.5062
➡️ Total Profit: ₹14,632.01
➡️ Equity Curve R²: 0.0423
➡️ Monthly Consistency Score: 0.0545

=== [2199/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.05it/s]
Hypertuning:  64%|██████▎   | 2199/3456 [51:07<28:25,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2271
➡️ Total Profit: ₹5,581.00
➡️ Equity Curve R²: 0.0869
➡️ Monthly Consistency Score: 0.0236

=== [2200/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.17it/s]
Hypertuning:  64%|██████▎   | 2200/3456 [51:08<28:41,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4311
➡️ Total Profit: ₹-15,226.08
➡️ Equity Curve R²: 0.3584
➡️ Monthly Consistency Score: -0.0658

=== [2201/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.73it/s]
Hypertuning:  64%|██████▎   | 2201/3456 [51:10<28:29,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3307
➡️ Total Profit: ₹-21,695.78
➡️ Equity Curve R²: 0.8472
➡️ Monthly Consistency Score: -0.0740

=== [2202/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.17it/s]
Hypertuning:  64%|██████▎   | 2202/3456 [51:11<28:40,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.4301
➡️ Total Profit: ₹35,304.81
➡️ Equity Curve R²: 0.4452
➡️ Monthly Consistency Score: 0.1289

=== [2203/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 111.65it/s]
Hypertuning:  64%|██████▎   | 2203/3456 [51:12<28:51,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.7290
➡️ Total Profit: ₹33,819.74
➡️ Equity Curve R²: 0.5809
➡️ Monthly Consistency Score: 0.1323

=== [2204/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.59it/s]
Hypertuning:  64%|██████▍   | 2204/3456 [51:14<28:26,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.6548
➡️ Total Profit: ₹-28,332.54
➡️ Equity Curve R²: 0.7684
➡️ Monthly Consistency Score: -0.1139

=== [2205/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.63it/s]
Hypertuning:  64%|██████▍   | 2205/3456 [51:15<28:15,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.0060
➡️ Total Profit: ₹42,970.13
➡️ Equity Curve R²: 0.6110
➡️ Monthly Consistency Score: 0.1651

=== [2206/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.99it/s]
Hypertuning:  64%|██████▍   | 2206/3456 [51:16<28:26,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.3177
➡️ Total Profit: ₹46,271.03
➡️ Equity Curve R²: 0.0113
➡️ Monthly Consistency Score: 0.1907

=== [2207/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.14it/s]
Hypertuning:  64%|██████▍   | 2207/3456 [51:18<28:00,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.9073
➡️ Total Profit: ₹56,874.67
➡️ Equity Curve R²: 0.6614
➡️ Monthly Consistency Score: 0.2351

=== [2208/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.98it/s]
Hypertuning:  64%|██████▍   | 2208/3456 [51:19<28:12,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.7920
➡️ Total Profit: ₹67,608.30
➡️ Equity Curve R²: 0.6914
➡️ Monthly Consistency Score: 0.2921

=== [2209/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.15it/s]
Hypertuning:  64%|██████▍   | 2209/3456 [51:21<28:32,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4343
➡️ Total Profit: ₹-18,764.76
➡️ Equity Curve R²: 0.8416
➡️ Monthly Consistency Score: -0.0887

=== [2210/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.33it/s]
Hypertuning:  64%|██████▍   | 2210/3456 [51:22<28:09,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1217
➡️ Total Profit: ₹5,809.37
➡️ Equity Curve R²: 0.6012
➡️ Monthly Consistency Score: 0.0253

=== [2211/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.20it/s]
Hypertuning:  64%|██████▍   | 2211/3456 [51:23<28:17,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.8651
➡️ Total Profit: ₹29,709.62
➡️ Equity Curve R²: 0.0303
➡️ Monthly Consistency Score: 0.1096

=== [2212/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.44it/s]
Hypertuning:  64%|██████▍   | 2212/3456 [51:25<27:47,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.5640
➡️ Total Profit: ₹15,412.65
➡️ Equity Curve R²: 0.0056
➡️ Monthly Consistency Score: 0.0547

=== [2213/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.03it/s]
Hypertuning:  64%|██████▍   | 2213/3456 [51:26<28:14,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1632
➡️ Total Profit: ₹4,128.71
➡️ Equity Curve R²: 0.2088
➡️ Monthly Consistency Score: 0.0164

=== [2214/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 107.17it/s]
Hypertuning:  64%|██████▍   | 2214/3456 [51:27<27:54,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3527
➡️ Total Profit: ₹-17,376.48
➡️ Equity Curve R²: 0.8031
➡️ Monthly Consistency Score: -0.0626

=== [2215/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.88it/s]
Hypertuning:  64%|██████▍   | 2215/3456 [51:29<28:10,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1048
➡️ Total Profit: ₹-4,125.23
➡️ Equity Curve R²: 0.1573
➡️ Monthly Consistency Score: -0.0148

=== [2216/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.69it/s]
Hypertuning:  64%|██████▍   | 2216/3456 [51:30<27:48,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.5122
➡️ Total Profit: ₹-13,716.02
➡️ Equity Curve R²: 0.3575
➡️ Monthly Consistency Score: -0.0510

=== [2217/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.45it/s]
Hypertuning:  64%|██████▍   | 2217/3456 [51:31<28:14,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2897
➡️ Total Profit: ₹-15,330.31
➡️ Equity Curve R²: 0.8100
➡️ Monthly Consistency Score: -0.0579

=== [2218/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.45it/s]
Hypertuning:  64%|██████▍   | 2218/3456 [51:33<27:55,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1421
➡️ Total Profit: ₹4,603.49
➡️ Equity Curve R²: 0.1128
➡️ Monthly Consistency Score: 0.0153

=== [2219/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.51it/s]
Hypertuning:  64%|██████▍   | 2219/3456 [51:34<28:13,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.3825
➡️ Total Profit: ₹50,474.42
➡️ Equity Curve R²: 0.3328
➡️ Monthly Consistency Score: 0.2223

=== [2220/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.94it/s]
Hypertuning:  64%|██████▍   | 2220/3456 [51:35<27:10,  1.32s/it]

➡️ Profit-to-Drawdown Ratio: 1.0268
➡️ Total Profit: ₹40,087.55
➡️ Equity Curve R²: 0.0646
➡️ Monthly Consistency Score: 0.1623

=== [2221/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.17it/s]
Hypertuning:  64%|██████▍   | 2221/3456 [51:37<27:47,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.6334
➡️ Total Profit: ₹54,734.79
➡️ Equity Curve R²: 0.6783
➡️ Monthly Consistency Score: 0.2070

=== [2222/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.97it/s]
Hypertuning:  64%|██████▍   | 2222/3456 [51:38<27:31,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.1602
➡️ Total Profit: ₹61,192.18
➡️ Equity Curve R²: 0.1719
➡️ Monthly Consistency Score: 0.2241

=== [2223/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.51it/s]
Hypertuning:  64%|██████▍   | 2223/3456 [51:39<27:50,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.0533
➡️ Total Profit: ₹66,563.92
➡️ Equity Curve R²: 0.2002
➡️ Monthly Consistency Score: 0.2743

=== [2224/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.99it/s]
Hypertuning:  64%|██████▍   | 2224/3456 [51:41<27:29,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 10.0762
➡️ Total Profit: ₹107,292.96
➡️ Equity Curve R²: 0.9066
➡️ Monthly Consistency Score: 0.5711

=== [2225/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.94it/s]
Hypertuning:  64%|██████▍   | 2225/3456 [51:42<28:01,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3241
➡️ Total Profit: ₹-12,460.34
➡️ Equity Curve R²: 0.7896
➡️ Monthly Consistency Score: -0.0615

=== [2226/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.64it/s]
Hypertuning:  64%|██████▍   | 2226/3456 [51:44<27:41,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1911
➡️ Total Profit: ₹8,592.97
➡️ Equity Curve R²: 0.5409
➡️ Monthly Consistency Score: 0.0374

=== [2227/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.14it/s]
Hypertuning:  64%|██████▍   | 2227/3456 [51:45<27:59,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.8001
➡️ Total Profit: ₹28,468.19
➡️ Equity Curve R²: 0.0151
➡️ Monthly Consistency Score: 0.1058

=== [2228/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.81it/s]
Hypertuning:  64%|██████▍   | 2228/3456 [51:46<27:38,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.1528
➡️ Total Profit: ₹26,801.69
➡️ Equity Curve R²: 0.4463
➡️ Monthly Consistency Score: 0.0943

=== [2229/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.88it/s]
Hypertuning:  64%|██████▍   | 2229/3456 [51:48<27:30,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2130
➡️ Total Profit: ₹5,388.71
➡️ Equity Curve R²: 0.1514
➡️ Monthly Consistency Score: 0.0212

=== [2230/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.08it/s]
Hypertuning:  65%|██████▍   | 2230/3456 [51:49<27:46,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4310
➡️ Total Profit: ₹-24,156.48
➡️ Equity Curve R²: 0.8422
➡️ Monthly Consistency Score: -0.0843

=== [2231/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.66it/s]
Hypertuning:  65%|██████▍   | 2231/3456 [51:50<28:03,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0226
➡️ Total Profit: ₹-888.34
➡️ Equity Curve R²: 0.0647
➡️ Monthly Consistency Score: -0.0033

=== [2232/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.02it/s]
Hypertuning:  65%|██████▍   | 2232/3456 [51:52<27:42,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.5122
➡️ Total Profit: ₹-13,716.02
➡️ Equity Curve R²: 0.3575
➡️ Monthly Consistency Score: -0.0510

=== [2233/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.26it/s]
Hypertuning:  65%|██████▍   | 2233/3456 [51:53<27:30,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1458
➡️ Total Profit: ₹4,710.64
➡️ Equity Curve R²: 0.3368
➡️ Monthly Consistency Score: 0.0178

=== [2234/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.96it/s]
Hypertuning:  65%|██████▍   | 2234/3456 [51:54<27:48,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.2758
➡️ Total Profit: ₹27,385.33
➡️ Equity Curve R²: 0.5892
➡️ Monthly Consistency Score: 0.0936

=== [2235/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.40it/s]
Hypertuning:  65%|██████▍   | 2235/3456 [51:56<27:22,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.5363
➡️ Total Profit: ₹53,734.42
➡️ Equity Curve R²: 0.2946
➡️ Monthly Consistency Score: 0.2399

=== [2236/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.23it/s]
Hypertuning:  65%|██████▍   | 2236/3456 [51:57<27:37,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.0522
➡️ Total Profit: ₹40,570.37
➡️ Equity Curve R²: 0.0699
➡️ Monthly Consistency Score: 0.1569

=== [2237/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.99it/s]
Hypertuning:  65%|██████▍   | 2237/3456 [51:58<27:27,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.6940
➡️ Total Profit: ₹55,993.85
➡️ Equity Curve R²: 0.6888
➡️ Monthly Consistency Score: 0.2106

=== [2238/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.73it/s]
Hypertuning:  65%|██████▍   | 2238/3456 [52:00<27:43,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1602
➡️ Total Profit: ₹43,714.01
➡️ Equity Curve R²: 0.0059
➡️ Monthly Consistency Score: 0.1673

=== [2239/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.49it/s]
Hypertuning:  65%|██████▍   | 2239/3456 [52:01<27:56,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 4.4121
➡️ Total Profit: ₹86,301.18
➡️ Equity Curve R²: 0.6715
➡️ Monthly Consistency Score: 0.3479

=== [2240/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.86it/s]
Hypertuning:  65%|██████▍   | 2240/3456 [52:03<27:34,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 10.0762
➡️ Total Profit: ₹107,292.96
➡️ Equity Curve R²: 0.9066
➡️ Monthly Consistency Score: 0.5711

=== [2241/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.22it/s]
Hypertuning:  65%|██████▍   | 2241/3456 [52:04<28:04,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.4570
➡️ Total Profit: ₹-19,462.50
➡️ Equity Curve R²: 0.8183
➡️ Monthly Consistency Score: -0.0984

=== [2242/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.83it/s]
Hypertuning:  65%|██████▍   | 2242/3456 [52:05<27:43,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.0135
➡️ Total Profit: ₹603.85
➡️ Equity Curve R²: 0.6948
➡️ Monthly Consistency Score: 0.0026

=== [2243/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.18it/s]
Hypertuning:  65%|██████▍   | 2243/3456 [52:07<27:12,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.0731
➡️ Total Profit: ₹3,096.82
➡️ Equity Curve R²: 0.1071
➡️ Monthly Consistency Score: 0.0123

=== [2244/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.56it/s]
Hypertuning:  65%|██████▍   | 2244/3456 [52:08<27:19,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.3360
➡️ Total Profit: ₹31,061.69
➡️ Equity Curve R²: 0.4514
➡️ Monthly Consistency Score: 0.1129

=== [2245/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.21it/s]
Hypertuning:  65%|██████▍   | 2245/3456 [52:09<27:09,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2378
➡️ Total Profit: ₹6,015.42
➡️ Equity Curve R²: 0.1460
➡️ Monthly Consistency Score: 0.0234

=== [2246/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.48it/s]
Hypertuning:  65%|██████▍   | 2246/3456 [52:11<27:25,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.5673
➡️ Total Profit: ₹-39,545.56
➡️ Equity Curve R²: 0.9070
➡️ Monthly Consistency Score: -0.1370

=== [2247/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.85it/s]
Hypertuning:  65%|██████▌   | 2247/3456 [52:12<27:27,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2928
➡️ Total Profit: ₹-13,891.08
➡️ Equity Curve R²: 0.3305
➡️ Monthly Consistency Score: -0.0501

=== [2248/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.44it/s]
Hypertuning:  65%|██████▌   | 2248/3456 [52:13<27:05,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6372
➡️ Total Profit: ₹-19,192.38
➡️ Equity Curve R²: 0.6103
➡️ Monthly Consistency Score: -0.0739

=== [2249/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.51it/s]
Hypertuning:  65%|██████▌   | 2249/3456 [52:15<27:34,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3882
➡️ Total Profit: ₹-22,259.84
➡️ Equity Curve R²: 0.8511
➡️ Monthly Consistency Score: -0.0815

=== [2250/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.74it/s]
Hypertuning:  65%|██████▌   | 2250/3456 [52:16<27:17,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.9326
➡️ Total Profit: ₹22,865.33
➡️ Equity Curve R²: 0.4982
➡️ Monthly Consistency Score: 0.0777

=== [2251/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.53it/s]
Hypertuning:  65%|██████▌   | 2251/3456 [52:18<27:27,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.5033
➡️ Total Profit: ₹31,848.53
➡️ Equity Curve R²: 0.2789
➡️ Monthly Consistency Score: 0.1304

=== [2252/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 130.74it/s]
Hypertuning:  65%|██████▌   | 2252/3456 [52:19<27:08,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1312
➡️ Total Profit: ₹5,058.46
➡️ Equity Curve R²: 0.0254
➡️ Monthly Consistency Score: 0.0194

=== [2253/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.20it/s]
Hypertuning:  65%|██████▌   | 2253/3456 [52:20<27:39,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.8405
➡️ Total Profit: ₹57,251.97
➡️ Equity Curve R²: 0.7035
➡️ Monthly Consistency Score: 0.2161

=== [2254/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.63it/s]
Hypertuning:  65%|██████▌   | 2254/3456 [52:22<27:21,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.0663
➡️ Total Profit: ₹42,583.09
➡️ Equity Curve R²: 0.0229
➡️ Monthly Consistency Score: 0.1640

=== [2255/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.27it/s]
Hypertuning:  65%|██████▌   | 2255/3456 [52:23<27:35,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 4.2456
➡️ Total Profit: ₹83,043.92
➡️ Equity Curve R²: 0.6815
➡️ Monthly Consistency Score: 0.3408

=== [2256/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.19it/s]
Hypertuning:  65%|██████▌   | 2256/3456 [52:24<27:19,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.9420
➡️ Total Profit: ₹56,391.93
➡️ Equity Curve R²: 0.4620
➡️ Monthly Consistency Score: 0.2445

=== [2257/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.29it/s]
Hypertuning:  65%|██████▌   | 2257/3456 [52:26<27:14,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4051
➡️ Total Profit: ₹-17,505.70
➡️ Equity Curve R²: 0.8352
➡️ Monthly Consistency Score: -0.0830

=== [2258/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.54it/s]
Hypertuning:  65%|██████▌   | 2258/3456 [52:27<27:20,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.2074
➡️ Total Profit: ₹9,198.45
➡️ Equity Curve R²: 0.5264
➡️ Monthly Consistency Score: 0.0396

=== [2259/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.82it/s]
Hypertuning:  65%|██████▌   | 2259/3456 [52:29<27:27,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.8651
➡️ Total Profit: ₹29,709.62
➡️ Equity Curve R²: 0.0303
➡️ Monthly Consistency Score: 0.1096

=== [2260/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.86it/s]
Hypertuning:  65%|██████▌   | 2260/3456 [52:30<27:03,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4508
➡️ Total Profit: ₹13,280.83
➡️ Equity Curve R²: 0.0045
➡️ Monthly Consistency Score: 0.0468

=== [2261/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.52it/s]
Hypertuning:  65%|██████▌   | 2261/3456 [52:31<26:56,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1632
➡️ Total Profit: ₹4,128.71
➡️ Equity Curve R²: 0.2088
➡️ Monthly Consistency Score: 0.0164

=== [2262/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.03it/s]
Hypertuning:  65%|██████▌   | 2262/3456 [52:33<27:11,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3375
➡️ Total Profit: ₹-16,247.40
➡️ Equity Curve R²: 0.7975
➡️ Monthly Consistency Score: -0.0584

=== [2263/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.65it/s]
Hypertuning:  65%|██████▌   | 2263/3456 [52:34<26:44,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1048
➡️ Total Profit: ₹-4,125.23
➡️ Equity Curve R²: 0.1573
➡️ Monthly Consistency Score: -0.0148

=== [2264/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.74it/s]
Hypertuning:  66%|██████▌   | 2264/3456 [52:35<26:56,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.5122
➡️ Total Profit: ₹-13,716.02
➡️ Equity Curve R²: 0.3575
➡️ Monthly Consistency Score: -0.0510

=== [2265/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.57it/s]
Hypertuning:  66%|██████▌   | 2265/3456 [52:37<27:19,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.2897
➡️ Total Profit: ₹-15,330.31
➡️ Equity Curve R²: 0.8100
➡️ Monthly Consistency Score: -0.0579

=== [2266/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.89it/s]
Hypertuning:  66%|██████▌   | 2266/3456 [52:38<26:55,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1833
➡️ Total Profit: ₹5,732.57
➡️ Equity Curve R²: 0.0882
➡️ Monthly Consistency Score: 0.0190

=== [2267/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.39it/s]
Hypertuning:  66%|██████▌   | 2267/3456 [52:39<27:03,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.3825
➡️ Total Profit: ₹50,474.42
➡️ Equity Curve R²: 0.3328
➡️ Monthly Consistency Score: 0.2223

=== [2268/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 111.41it/s]
Hypertuning:  66%|██████▌   | 2268/3456 [52:41<26:35,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.0268
➡️ Total Profit: ₹40,087.55
➡️ Equity Curve R²: 0.0646
➡️ Monthly Consistency Score: 0.1623

=== [2269/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.46it/s]
Hypertuning:  66%|██████▌   | 2269/3456 [52:42<27:01,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.6334
➡️ Total Profit: ₹54,734.79
➡️ Equity Curve R²: 0.6783
➡️ Monthly Consistency Score: 0.2070

=== [2270/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.64it/s]
Hypertuning:  66%|██████▌   | 2270/3456 [52:43<26:42,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.1602
➡️ Total Profit: ₹61,192.18
➡️ Equity Curve R²: 0.1719
➡️ Monthly Consistency Score: 0.2241

=== [2271/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.21it/s]
Hypertuning:  66%|██████▌   | 2271/3456 [52:45<26:54,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.0533
➡️ Total Profit: ₹66,563.92
➡️ Equity Curve R²: 0.2002
➡️ Monthly Consistency Score: 0.2743

=== [2272/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.25it/s]
Hypertuning:  66%|██████▌   | 2272/3456 [52:46<26:33,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 10.0762
➡️ Total Profit: ₹107,292.96
➡️ Equity Curve R²: 0.9066
➡️ Monthly Consistency Score: 0.5711

=== [2273/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.73it/s]
Hypertuning:  66%|██████▌   | 2273/3456 [52:48<27:04,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3241
➡️ Total Profit: ₹-12,462.22
➡️ Equity Curve R²: 0.7998
➡️ Monthly Consistency Score: -0.0622

=== [2274/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.04it/s]
Hypertuning:  66%|██████▌   | 2274/3456 [52:49<26:46,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1076
➡️ Total Profit: ₹5,202.05
➡️ Equity Curve R²: 0.6102
➡️ Monthly Consistency Score: 0.0224

=== [2275/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.80it/s]
Hypertuning:  66%|██████▌   | 2275/3456 [52:50<27:00,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.3164
➡️ Total Profit: ₹11,712.24
➡️ Equity Curve R²: 0.0133
➡️ Monthly Consistency Score: 0.0453

=== [2276/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.29it/s]
Hypertuning:  66%|██████▌   | 2276/3456 [52:52<26:36,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.1528
➡️ Total Profit: ₹26,801.69
➡️ Equity Curve R²: 0.4463
➡️ Monthly Consistency Score: 0.0943

=== [2277/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.96it/s]
Hypertuning:  66%|██████▌   | 2277/3456 [52:53<26:27,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2950
➡️ Total Profit: ₹7,277.30
➡️ Equity Curve R²: 0.1214
➡️ Monthly Consistency Score: 0.0288

=== [2278/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.56it/s]
Hypertuning:  66%|██████▌   | 2278/3456 [52:54<26:43,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3992
➡️ Total Profit: ₹-21,196.48
➡️ Equity Curve R²: 0.7843
➡️ Monthly Consistency Score: -0.0730

=== [2279/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.10it/s]
Hypertuning:  66%|██████▌   | 2279/3456 [52:56<26:19,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.1012
➡️ Total Profit: ₹-4,145.60
➡️ Equity Curve R²: 0.1132
➡️ Monthly Consistency Score: -0.0151

=== [2280/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.87it/s]
Hypertuning:  66%|██████▌   | 2280/3456 [52:57<26:25,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.5122
➡️ Total Profit: ₹-13,716.02
➡️ Equity Curve R²: 0.3575
➡️ Monthly Consistency Score: -0.0510

=== [2281/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.61it/s]
Hypertuning:  66%|██████▌   | 2281/3456 [52:58<26:18,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.1885
➡️ Total Profit: ₹5,971.58
➡️ Equity Curve R²: 0.3903
➡️ Monthly Consistency Score: 0.0227

=== [2282/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.68it/s]
Hypertuning:  66%|██████▌   | 2282/3456 [53:00<26:33,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.2758
➡️ Total Profit: ₹27,385.33
➡️ Equity Curve R²: 0.5892
➡️ Monthly Consistency Score: 0.0936

=== [2283/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.36it/s]
Hypertuning:  66%|██████▌   | 2283/3456 [53:01<26:53,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.3056
➡️ Total Profit: ₹48,845.79
➡️ Equity Curve R²: 0.3183
➡️ Monthly Consistency Score: 0.2158

=== [2284/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.29it/s]
Hypertuning:  66%|██████▌   | 2284/3456 [53:02<26:29,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.0522
➡️ Total Profit: ₹40,570.37
➡️ Equity Curve R²: 0.0699
➡️ Monthly Consistency Score: 0.1569

=== [2285/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.70it/s]
Hypertuning:  66%|██████▌   | 2285/3456 [53:04<26:19,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.8094
➡️ Total Profit: ₹56,623.38
➡️ Equity Curve R²: 0.7040
➡️ Monthly Consistency Score: 0.2146

=== [2286/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.94it/s]
Hypertuning:  66%|██████▌   | 2286/3456 [53:05<26:30,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.0379
➡️ Total Profit: ₹41,452.17
➡️ Equity Curve R²: 0.0287
➡️ Monthly Consistency Score: 0.1570

=== [2287/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.09it/s]
Hypertuning:  66%|██████▌   | 2287/3456 [53:07<26:44,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 4.1623
➡️ Total Profit: ₹81,415.29
➡️ Equity Curve R²: 0.6470
➡️ Monthly Consistency Score: 0.3299

=== [2288/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.86it/s]
Hypertuning:  66%|██████▌   | 2288/3456 [53:08<26:21,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 10.0762
➡️ Total Profit: ₹107,292.96
➡️ Equity Curve R²: 0.9066
➡️ Monthly Consistency Score: 0.5711

=== [2289/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.66it/s]
Hypertuning:  66%|██████▌   | 2289/3456 [53:09<26:51,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.3027
➡️ Total Profit: ₹-11,555.18
➡️ Equity Curve R²: 0.6998
➡️ Monthly Consistency Score: -0.0557

=== [2290/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.81it/s]
Hypertuning:  66%|██████▋   | 2290/3456 [53:11<26:35,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1359
➡️ Total Profit: ₹-7,303.39
➡️ Equity Curve R²: 0.7870
➡️ Monthly Consistency Score: -0.0305

=== [2291/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.83it/s]
Hypertuning:  66%|██████▋   | 2291/3456 [53:12<26:09,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2870
➡️ Total Profit: ₹9,688.19
➡️ Equity Curve R²: 0.0043
➡️ Monthly Consistency Score: 0.0374

=== [2292/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.06it/s]
Hypertuning:  66%|██████▋   | 2292/3456 [53:13<26:26,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.2128
➡️ Total Profit: ₹28,198.01
➡️ Equity Curve R²: 0.4256
➡️ Monthly Consistency Score: 0.1011

=== [2293/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.13it/s]
Hypertuning:  66%|██████▋   | 2293/3456 [53:15<26:13,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4185
➡️ Total Profit: ₹9,796.36
➡️ Equity Curve R²: 0.0538
➡️ Monthly Consistency Score: 0.0386

=== [2294/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.36it/s]
Hypertuning:  66%|██████▋   | 2294/3456 [53:16<26:28,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4653
➡️ Total Profit: ₹-29,803.72
➡️ Equity Curve R²: 0.8547
➡️ Monthly Consistency Score: -0.1091

=== [2295/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.21it/s]
Hypertuning:  66%|██████▋   | 2295/3456 [53:17<26:02,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2837
➡️ Total Profit: ₹-13,922.86
➡️ Equity Curve R²: 0.3547
➡️ Monthly Consistency Score: -0.0514

=== [2296/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.70it/s]
Hypertuning:  66%|██████▋   | 2296/3456 [53:19<26:12,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2933
➡️ Total Profit: ₹-10,356.92
➡️ Equity Curve R²: 0.4972
➡️ Monthly Consistency Score: -0.0404

=== [2297/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.46it/s]
Hypertuning:  66%|██████▋   | 2297/3456 [53:20<26:03,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3294
➡️ Total Profit: ₹-17,850.31
➡️ Equity Curve R²: 0.8230
➡️ Monthly Consistency Score: -0.0662

=== [2298/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.36it/s]
Hypertuning:  66%|██████▋   | 2298/3456 [53:21<26:18,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4287
➡️ Total Profit: ₹11,481.61
➡️ Equity Curve R²: 0.3206
➡️ Monthly Consistency Score: 0.0390

=== [2299/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.64it/s]
Hypertuning:  67%|██████▋   | 2299/3456 [53:23<25:54,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.2725
➡️ Total Profit: ₹26,959.90
➡️ Equity Curve R²: 0.2137
➡️ Monthly Consistency Score: 0.1082

=== [2300/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.81it/s]
Hypertuning:  67%|██████▋   | 2300/3456 [53:24<26:10,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.3859
➡️ Total Profit: ₹14,057.65
➡️ Equity Curve R²: 0.0002
➡️ Monthly Consistency Score: 0.0531

=== [2301/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.26it/s]
Hypertuning:  67%|██████▋   | 2301/3456 [53:25<26:02,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.5130
➡️ Total Profit: ₹68,590.09
➡️ Equity Curve R²: 0.7960
➡️ Monthly Consistency Score: 0.2705

=== [2302/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.18it/s]
Hypertuning:  67%|██████▋   | 2302/3456 [53:27<26:15,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1265
➡️ Total Profit: ₹43,714.01
➡️ Equity Curve R²: 0.0082
➡️ Monthly Consistency Score: 0.1663

=== [2303/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.43it/s]
Hypertuning:  67%|██████▋   | 2303/3456 [53:28<25:51,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.6845
➡️ Total Profit: ₹70,003.92
➡️ Equity Curve R²: 0.4652
➡️ Monthly Consistency Score: 0.2761

=== [2304/3456] Testing Parameters ===
smooth_length: 10
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.67it/s]
Hypertuning:  67%|██████▋   | 2304/3456 [53:30<26:01,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 9.8763
➡️ Total Profit: ₹105,164.78
➡️ Equity Curve R²: 0.9079
➡️ Monthly Consistency Score: 0.5687

=== [2305/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.85it/s]
Hypertuning:  67%|██████▋   | 2305/3456 [53:31<26:28,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.7563
➡️ Total Profit: ₹-84,205.97
➡️ Equity Curve R²: 0.9780
➡️ Monthly Consistency Score: -0.3350

=== [2306/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.17it/s]
Hypertuning:  67%|██████▋   | 2306/3456 [53:32<26:05,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0705
➡️ Total Profit: ₹2,350.33
➡️ Equity Curve R²: 0.3531
➡️ Monthly Consistency Score: 0.0090

=== [2307/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.76it/s]
Hypertuning:  67%|██████▋   | 2307/3456 [53:34<25:37,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.2972
➡️ Total Profit: ₹41,183.78
➡️ Equity Curve R²: 0.1446
➡️ Monthly Consistency Score: 0.1602

=== [2308/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.96it/s]
Hypertuning:  67%|██████▋   | 2308/3456 [53:35<25:50,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.5420
➡️ Total Profit: ₹18,195.89
➡️ Equity Curve R²: 0.1389
➡️ Monthly Consistency Score: 0.0687

=== [2309/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.87it/s]
Hypertuning:  67%|██████▋   | 2309/3456 [53:36<26:24,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.5886
➡️ Total Profit: ₹-26,445.09
➡️ Equity Curve R²: 0.8241
➡️ Monthly Consistency Score: -0.0971

=== [2310/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.05it/s]
Hypertuning:  67%|██████▋   | 2310/3456 [53:38<26:05,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.7503
➡️ Total Profit: ₹56,195.70
➡️ Equity Curve R²: 0.7737
➡️ Monthly Consistency Score: 0.1991

=== [2311/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.25it/s]
Hypertuning:  67%|██████▋   | 2311/3456 [53:39<25:40,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.0647
➡️ Total Profit: ₹2,353.51
➡️ Equity Curve R²: 0.4371
➡️ Monthly Consistency Score: 0.0085

=== [2312/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.09it/s]
Hypertuning:  67%|██████▋   | 2312/3456 [53:40<25:52,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.6953
➡️ Total Profit: ₹18,839.37
➡️ Equity Curve R²: 0.0004
➡️ Monthly Consistency Score: 0.0795

=== [2313/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.28it/s]
Hypertuning:  67%|██████▋   | 2313/3456 [53:42<25:45,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.0828
➡️ Total Profit: ₹32,200.72
➡️ Equity Curve R²: 0.5372
➡️ Monthly Consistency Score: 0.1272

=== [2314/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.08it/s]
Hypertuning:  67%|██████▋   | 2314/3456 [53:43<25:55,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2060
➡️ Total Profit: ₹7,822.97
➡️ Equity Curve R²: 0.1510
➡️ Monthly Consistency Score: 0.0318

=== [2315/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.48it/s]
Hypertuning:  67%|██████▋   | 2315/3456 [53:44<25:35,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2330
➡️ Total Profit: ₹-11,239.70
➡️ Equity Curve R²: 0.7600
➡️ Monthly Consistency Score: -0.0422

=== [2316/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.73it/s]
Hypertuning:  67%|██████▋   | 2316/3456 [53:46<25:44,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1315
➡️ Total Profit: ₹3,881.00
➡️ Equity Curve R²: 0.0824
➡️ Monthly Consistency Score: 0.0139

=== [2317/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.68it/s]
Hypertuning:  67%|██████▋   | 2317/3456 [53:47<25:37,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.6475
➡️ Total Profit: ₹68,385.31
➡️ Equity Curve R²: 0.5277
➡️ Monthly Consistency Score: 0.2889

=== [2318/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.12it/s]
Hypertuning:  67%|██████▋   | 2318/3456 [53:49<25:55,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 4.4267
➡️ Total Profit: ₹75,045.52
➡️ Equity Curve R²: 0.6468
➡️ Monthly Consistency Score: 0.3430

=== [2319/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.87it/s]
Hypertuning:  67%|██████▋   | 2319/3456 [53:50<25:27,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.0825
➡️ Total Profit: ₹43,735.69
➡️ Equity Curve R²: 0.0531
➡️ Monthly Consistency Score: 0.1714

=== [2320/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 129.19it/s]
Hypertuning:  67%|██████▋   | 2320/3456 [53:51<25:38,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.3868
➡️ Total Profit: ₹67,597.38
➡️ Equity Curve R²: 0.7672
➡️ Monthly Consistency Score: 0.2978

=== [2321/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.47it/s]
Hypertuning:  67%|██████▋   | 2321/3456 [53:53<26:06,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.6974
➡️ Total Profit: ₹-61,236.51
➡️ Equity Curve R²: 0.9655
➡️ Monthly Consistency Score: -0.2451

=== [2322/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.58it/s]
Hypertuning:  67%|██████▋   | 2322/3456 [53:54<25:50,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4015
➡️ Total Profit: ₹-18,158.79
➡️ Equity Curve R²: 0.8042
➡️ Monthly Consistency Score: -0.0739

=== [2323/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.11it/s]
Hypertuning:  67%|██████▋   | 2323/3456 [53:55<25:22,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.5098
➡️ Total Profit: ₹18,300.51
➡️ Equity Curve R²: 0.1041
➡️ Monthly Consistency Score: 0.0753

=== [2324/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.43it/s]
Hypertuning:  67%|██████▋   | 2324/3456 [53:57<25:30,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3121
➡️ Total Profit: ₹11,807.71
➡️ Equity Curve R²: 0.0359
➡️ Monthly Consistency Score: 0.0450

=== [2325/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.98it/s]
Hypertuning:  67%|██████▋   | 2325/3456 [53:58<26:04,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.5425
➡️ Total Profit: ₹-22,664.15
➡️ Equity Curve R²: 0.7619
➡️ Monthly Consistency Score: -0.0794

=== [2326/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.80it/s]
Hypertuning:  67%|██████▋   | 2326/3456 [53:59<25:43,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.3041
➡️ Total Profit: ₹27,328.33
➡️ Equity Curve R²: 0.4154
➡️ Monthly Consistency Score: 0.1068

=== [2327/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.04it/s]
Hypertuning:  67%|██████▋   | 2327/3456 [54:01<25:19,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.2974
➡️ Total Profit: ₹30,002.52
➡️ Equity Curve R²: 0.2835
➡️ Monthly Consistency Score: 0.1120

=== [2328/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 111.73it/s]
Hypertuning:  67%|██████▋   | 2328/3456 [54:02<25:33,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3435
➡️ Total Profit: ₹-14,629.80
➡️ Equity Curve R²: 0.6152
➡️ Monthly Consistency Score: -0.0565

=== [2329/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 109.60it/s]
Hypertuning:  67%|██████▋   | 2329/3456 [54:04<25:26,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.0202
➡️ Total Profit: ₹822.60
➡️ Equity Curve R²: 0.3221
➡️ Monthly Consistency Score: 0.0029

=== [2330/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 111.49it/s]
Hypertuning:  67%|██████▋   | 2330/3456 [54:05<25:42,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.1076
➡️ Total Profit: ₹3,299.29
➡️ Equity Curve R²: 0.4495
➡️ Monthly Consistency Score: 0.0130

=== [2331/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 106.50it/s]
Hypertuning:  67%|██████▋   | 2331/3456 [54:06<25:19,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1113
➡️ Total Profit: ₹-4,716.96
➡️ Equity Curve R²: 0.7071
➡️ Monthly Consistency Score: -0.0178

=== [2332/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.21it/s]
Hypertuning:  67%|██████▋   | 2332/3456 [54:08<25:32,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5724
➡️ Total Profit: ₹11,921.83
➡️ Equity Curve R²: 0.3738
➡️ Monthly Consistency Score: 0.0467

=== [2333/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.01it/s]
Hypertuning:  68%|██████▊   | 2333/3456 [54:09<25:26,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.6069
➡️ Total Profit: ₹28,691.96
➡️ Equity Curve R²: 0.3258
➡️ Monthly Consistency Score: 0.1172

=== [2334/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 110.05it/s]
Hypertuning:  68%|██████▊   | 2334/3456 [54:10<25:39,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 4.4267
➡️ Total Profit: ₹75,045.52
➡️ Equity Curve R²: 0.6468
➡️ Monthly Consistency Score: 0.3430

=== [2335/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.04it/s]
Hypertuning:  68%|██████▊   | 2335/3456 [54:12<25:12,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.0825
➡️ Total Profit: ₹43,735.69
➡️ Equity Curve R²: 0.0531
➡️ Monthly Consistency Score: 0.1714

=== [2336/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.32it/s]
Hypertuning:  68%|██████▊   | 2336/3456 [54:13<25:18,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.9410
➡️ Total Profit: ₹64,901.01
➡️ Equity Curve R²: 0.6259
➡️ Monthly Consistency Score: 0.3064

=== [2337/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.93it/s]
Hypertuning:  68%|██████▊   | 2337/3456 [54:14<25:53,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.7476
➡️ Total Profit: ₹-64,032.10
➡️ Equity Curve R²: 0.9575
➡️ Monthly Consistency Score: -0.2557

=== [2338/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.45it/s]
Hypertuning:  68%|██████▊   | 2338/3456 [54:16<25:36,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3171
➡️ Total Profit: ₹-14,669.75
➡️ Equity Curve R²: 0.8413
➡️ Monthly Consistency Score: -0.0562

=== [2339/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.60it/s]
Hypertuning:  68%|██████▊   | 2339/3456 [54:17<25:15,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4856
➡️ Total Profit: ₹19,995.03
➡️ Equity Curve R²: 0.1695
➡️ Monthly Consistency Score: 0.0774

=== [2340/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.95it/s]
Hypertuning:  68%|██████▊   | 2340/3456 [54:19<25:25,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.6441
➡️ Total Profit: ₹26,158.67
➡️ Equity Curve R²: 0.0655
➡️ Monthly Consistency Score: 0.0973

=== [2341/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.16it/s]
Hypertuning:  68%|██████▊   | 2341/3456 [54:20<25:17,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0347
➡️ Total Profit: ₹-1,426.65
➡️ Equity Curve R²: 0.3365
➡️ Monthly Consistency Score: -0.0047

=== [2342/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.24it/s]
Hypertuning:  68%|██████▊   | 2342/3456 [54:21<25:28,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.9520
➡️ Total Profit: ₹22,100.97
➡️ Equity Curve R²: 0.1042
➡️ Monthly Consistency Score: 0.0807

=== [2343/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.77it/s]
Hypertuning:  68%|██████▊   | 2343/3456 [54:23<25:01,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.8730
➡️ Total Profit: ₹18,619.74
➡️ Equity Curve R²: 0.3997
➡️ Monthly Consistency Score: 0.0731

=== [2344/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.58it/s]
Hypertuning:  68%|██████▊   | 2344/3456 [54:24<25:10,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2176
➡️ Total Profit: ₹8,805.67
➡️ Equity Curve R²: 0.2692
➡️ Monthly Consistency Score: 0.0334

=== [2345/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.83it/s]
Hypertuning:  68%|██████▊   | 2345/3456 [54:25<25:00,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0421
➡️ Total Profit: ₹-1,701.16
➡️ Equity Curve R²: 0.5945
➡️ Monthly Consistency Score: -0.0059

=== [2346/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.34it/s]
Hypertuning:  68%|██████▊   | 2346/3456 [54:27<25:15,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3904
➡️ Total Profit: ₹-13,739.04
➡️ Equity Curve R²: 0.6717
➡️ Monthly Consistency Score: -0.0563

=== [2347/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.01it/s]
Hypertuning:  68%|██████▊   | 2347/3456 [54:28<24:55,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.5035
➡️ Total Profit: ₹-22,992.05
➡️ Equity Curve R²: 0.7912
➡️ Monthly Consistency Score: -0.0882

=== [2348/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.03it/s]
Hypertuning:  68%|██████▊   | 2348/3456 [54:29<25:03,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5123
➡️ Total Profit: ₹14,536.47
➡️ Equity Curve R²: 0.0000
➡️ Monthly Consistency Score: 0.0522

=== [2349/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.98it/s]
Hypertuning:  68%|██████▊   | 2349/3456 [54:31<25:33,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 0.7413
➡️ Total Profit: ₹33,319.53
➡️ Equity Curve R²: 0.0803
➡️ Monthly Consistency Score: 0.1326

=== [2350/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.00it/s]
Hypertuning:  68%|██████▊   | 2350/3456 [54:32<25:16,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.5787
➡️ Total Profit: ₹60,668.17
➡️ Equity Curve R²: 0.4948
➡️ Monthly Consistency Score: 0.2751

=== [2351/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.13it/s]
Hypertuning:  68%|██████▊   | 2351/3456 [54:33<24:51,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.0825
➡️ Total Profit: ₹43,738.43
➡️ Equity Curve R²: 0.0260
➡️ Monthly Consistency Score: 0.1720

=== [2352/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.36it/s]
Hypertuning:  68%|██████▊   | 2352/3456 [54:35<25:00,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.3585
➡️ Total Profit: ₹67,032.83
➡️ Equity Curve R²: 0.5705
➡️ Monthly Consistency Score: 0.3268

=== [2353/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.64it/s]
Hypertuning:  68%|██████▊   | 2353/3456 [54:36<24:52,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.7535
➡️ Total Profit: ₹-82,945.97
➡️ Equity Curve R²: 0.9780
➡️ Monthly Consistency Score: -0.3270

=== [2354/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.84it/s]
Hypertuning:  68%|██████▊   | 2354/3456 [54:38<25:05,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.0772
➡️ Total Profit: ₹2,350.33
➡️ Equity Curve R²: 0.2649
➡️ Monthly Consistency Score: 0.0093

=== [2355/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.48it/s]
Hypertuning:  68%|██████▊   | 2355/3456 [54:39<24:41,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.2067
➡️ Total Profit: ₹38,311.10
➡️ Equity Curve R²: 0.1295
➡️ Monthly Consistency Score: 0.1512

=== [2356/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.90it/s]
Hypertuning:  68%|██████▊   | 2356/3456 [54:40<24:50,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.7542
➡️ Total Profit: ₹25,319.57
➡️ Equity Curve R²: 0.3921
➡️ Monthly Consistency Score: 0.0962

=== [2357/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.80it/s]
Hypertuning:  68%|██████▊   | 2357/3456 [54:42<25:16,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.5828
➡️ Total Profit: ₹-25,815.56
➡️ Equity Curve R²: 0.8128
➡️ Monthly Consistency Score: -0.0952

=== [2358/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.09it/s]
Hypertuning:  68%|██████▊   | 2358/3456 [54:43<24:54,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.8063
➡️ Total Profit: ₹41,933.85
➡️ Equity Curve R²: 0.4846
➡️ Monthly Consistency Score: 0.1543

=== [2359/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.86it/s]
Hypertuning:  68%|██████▊   | 2359/3456 [54:44<24:28,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.4448
➡️ Total Profit: ₹15,371.15
➡️ Equity Curve R²: 0.0022
➡️ Monthly Consistency Score: 0.0551

=== [2360/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.56it/s]
Hypertuning:  68%|██████▊   | 2360/3456 [54:46<24:38,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3435
➡️ Total Profit: ₹-14,633.44
➡️ Equity Curve R²: 0.6383
➡️ Monthly Consistency Score: -0.0563

=== [2361/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.47it/s]
Hypertuning:  68%|██████▊   | 2361/3456 [54:47<25:09,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.0828
➡️ Total Profit: ₹32,199.78
➡️ Equity Curve R²: 0.5447
➡️ Monthly Consistency Score: 0.1275

=== [2362/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.95it/s]
Hypertuning:  68%|██████▊   | 2362/3456 [54:48<24:52,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1762
➡️ Total Profit: ₹6,692.05
➡️ Equity Curve R²: 0.1636
➡️ Monthly Consistency Score: 0.0272

=== [2363/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.98it/s]
Hypertuning:  68%|██████▊   | 2363/3456 [54:50<24:26,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.2668
➡️ Total Profit: ₹-12,871.07
➡️ Equity Curve R²: 0.7682
➡️ Monthly Consistency Score: -0.0473

=== [2364/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.25it/s]
Hypertuning:  68%|██████▊   | 2364/3456 [54:51<24:39,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4699
➡️ Total Profit: ₹9,786.36
➡️ Equity Curve R²: 0.2882
➡️ Monthly Consistency Score: 0.0371

=== [2365/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.11it/s]
Hypertuning:  68%|██████▊   | 2365/3456 [54:52<24:35,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6948
➡️ Total Profit: ₹30,795.77
➡️ Equity Curve R²: 0.0580
➡️ Monthly Consistency Score: 0.1313

=== [2366/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.47it/s]
Hypertuning:  68%|██████▊   | 2366/3456 [54:54<24:48,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 4.3600
➡️ Total Profit: ₹73,914.60
➡️ Equity Curve R²: 0.6587
➡️ Monthly Consistency Score: 0.3409

=== [2367/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 131.22it/s]
Hypertuning:  68%|██████▊   | 2367/3456 [54:55<24:23,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.0421
➡️ Total Profit: ₹42,104.32
➡️ Equity Curve R²: 0.0495
➡️ Monthly Consistency Score: 0.1670

=== [2368/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.34it/s]
Hypertuning:  69%|██████▊   | 2368/3456 [54:57<24:28,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.2800
➡️ Total Profit: ₹65,465.55
➡️ Equity Curve R²: 0.7757
➡️ Monthly Consistency Score: 0.2919

=== [2369/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.01it/s]
Hypertuning:  69%|██████▊   | 2369/3456 [54:58<24:24,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.7178
➡️ Total Profit: ₹-65,091.69
➡️ Equity Curve R²: 0.9666
➡️ Monthly Consistency Score: -0.2693

=== [2370/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.30it/s]
Hypertuning:  69%|██████▊   | 2370/3456 [54:59<24:37,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0029
➡️ Total Profit: ₹95.85
➡️ Equity Curve R²: 0.6113
➡️ Monthly Consistency Score: 0.0004

=== [2371/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.26it/s]
Hypertuning:  69%|██████▊   | 2371/3456 [55:01<24:50,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.5088
➡️ Total Profit: ₹19,926.40
➡️ Equity Curve R²: 0.0808
➡️ Monthly Consistency Score: 0.0801

=== [2372/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.56it/s]
Hypertuning:  69%|██████▊   | 2372/3456 [55:02<24:31,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5763
➡️ Total Profit: ₹21,804.07
➡️ Equity Curve R²: 0.2704
➡️ Monthly Consistency Score: 0.0832

=== [2373/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.40it/s]
Hypertuning:  69%|██████▊   | 2373/3456 [55:03<24:27,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3205
➡️ Total Profit: ₹-11,662.27
➡️ Equity Curve R²: 0.3628
➡️ Monthly Consistency Score: -0.0416

=== [2374/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.76it/s]
Hypertuning:  69%|██████▊   | 2374/3456 [55:05<24:57,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.0800
➡️ Total Profit: ₹25,073.85
➡️ Equity Curve R²: 0.3690
➡️ Monthly Consistency Score: 0.0958

=== [2375/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.47it/s]
Hypertuning:  69%|██████▊   | 2375/3456 [55:06<24:31,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.2272
➡️ Total Profit: ₹28,411.15
➡️ Equity Curve R²: 0.2129
➡️ Monthly Consistency Score: 0.1050

=== [2376/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.16it/s]
Hypertuning:  69%|██████▉   | 2376/3456 [55:07<24:39,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1934
➡️ Total Profit: ₹-8,237.98
➡️ Equity Curve R²: 0.5611
➡️ Monthly Consistency Score: -0.0308

=== [2377/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.87it/s]
Hypertuning:  69%|██████▉   | 2377/3456 [55:09<24:25,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4420
➡️ Total Profit: ₹13,419.78
➡️ Equity Curve R²: 0.0882
➡️ Monthly Consistency Score: 0.0496

=== [2378/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.08it/s]
Hypertuning:  69%|██████▉   | 2378/3456 [55:10<24:32,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.1076
➡️ Total Profit: ₹3,299.29
➡️ Equity Curve R²: 0.4495
➡️ Monthly Consistency Score: 0.0130

=== [2379/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.65it/s]
Hypertuning:  69%|██████▉   | 2379/3456 [55:11<24:06,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.1113
➡️ Total Profit: ₹-4,716.96
➡️ Equity Curve R²: 0.7071
➡️ Monthly Consistency Score: -0.0178

=== [2380/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.97it/s]
Hypertuning:  69%|██████▉   | 2380/3456 [55:13<24:14,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4700
➡️ Total Profit: ₹9,790.00
➡️ Equity Curve R²: 0.3036
➡️ Monthly Consistency Score: 0.0371

=== [2381/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.64it/s]
Hypertuning:  69%|██████▉   | 2381/3456 [55:14<24:41,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.2414
➡️ Total Profit: ₹57,895.70
➡️ Equity Curve R²: 0.5176
➡️ Monthly Consistency Score: 0.2346

=== [2382/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.74it/s]
Hypertuning:  69%|██████▉   | 2382/3456 [55:16<24:25,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.7785
➡️ Total Profit: ₹64,055.42
➡️ Equity Curve R²: 0.6083
➡️ Monthly Consistency Score: 0.2936

=== [2383/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 129.63it/s]
Hypertuning:  69%|██████▉   | 2383/3456 [55:17<24:05,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.0825
➡️ Total Profit: ₹43,735.69
➡️ Equity Curve R²: 0.0531
➡️ Monthly Consistency Score: 0.1714

=== [2384/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.68it/s]
Hypertuning:  69%|██████▉   | 2384/3456 [55:18<24:15,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.3868
➡️ Total Profit: ₹67,597.38
➡️ Equity Curve R²: 0.7672
➡️ Monthly Consistency Score: 0.2978

=== [2385/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.64it/s]
Hypertuning:  69%|██████▉   | 2385/3456 [55:20<24:08,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.7439
➡️ Total Profit: ₹-63,613.65
➡️ Equity Curve R²: 0.9458
➡️ Monthly Consistency Score: -0.2695

=== [2386/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.53it/s]
Hypertuning:  69%|██████▉   | 2386/3456 [55:21<24:19,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0738
➡️ Total Profit: ₹-3,382.31
➡️ Equity Curve R²: 0.5361
➡️ Monthly Consistency Score: -0.0130

=== [2387/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.25it/s]
Hypertuning:  69%|██████▉   | 2387/3456 [55:22<23:56,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.0979
➡️ Total Profit: ₹4,029.92
➡️ Equity Curve R²: 0.4060
➡️ Monthly Consistency Score: 0.0167

=== [2388/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.77it/s]
Hypertuning:  69%|██████▉   | 2388/3456 [55:24<24:04,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3686
➡️ Total Profit: ₹15,412.25
➡️ Equity Curve R²: 0.0008
➡️ Monthly Consistency Score: 0.0583

=== [2389/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.10it/s]
Hypertuning:  69%|██████▉   | 2389/3456 [55:25<24:30,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.3578
➡️ Total Profit: ₹-14,311.92
➡️ Equity Curve R²: 0.3601
➡️ Monthly Consistency Score: -0.0505

=== [2390/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.11it/s]
Hypertuning:  69%|██████▉   | 2390/3456 [55:26<24:10,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.6013
➡️ Total Profit: ₹16,457.41
➡️ Equity Curve R²: 0.0118
➡️ Monthly Consistency Score: 0.0587

=== [2391/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.63it/s]
Hypertuning:  69%|██████▉   | 2391/3456 [55:28<23:49,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.2549
➡️ Total Profit: ₹26,765.63
➡️ Equity Curve R²: 0.2920
➡️ Monthly Consistency Score: 0.1055

=== [2392/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.44it/s]
Hypertuning:  69%|██████▉   | 2392/3456 [55:29<24:04,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.2374
➡️ Total Profit: ₹25,232.87
➡️ Equity Curve R²: 0.1445
➡️ Monthly Consistency Score: 0.0985

=== [2393/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.92it/s]
Hypertuning:  69%|██████▉   | 2393/3456 [55:31<24:20,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.1255
➡️ Total Profit: ₹4,599.78
➡️ Equity Curve R²: 0.4395
➡️ Monthly Consistency Score: 0.0163

=== [2394/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.08it/s]
Hypertuning:  69%|██████▉   | 2394/3456 [55:32<24:06,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.5526
➡️ Total Profit: ₹-30,600.72
➡️ Equity Curve R²: 0.8481
➡️ Monthly Consistency Score: -0.1092

=== [2395/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.18it/s]
Hypertuning:  69%|██████▉   | 2395/3456 [55:33<24:14,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.4502
➡️ Total Profit: ₹16,825.22
➡️ Equity Curve R²: 0.0600
➡️ Monthly Consistency Score: 0.0679

=== [2396/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.35it/s]
Hypertuning:  69%|██████▉   | 2396/3456 [55:35<23:53,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2342
➡️ Total Profit: ₹5,537.28
➡️ Equity Curve R²: 0.1328
➡️ Monthly Consistency Score: 0.0202

=== [2397/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.43it/s]
Hypertuning:  69%|██████▉   | 2397/3456 [55:36<24:19,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.9929
➡️ Total Profit: ₹40,878.59
➡️ Equity Curve R²: 0.0355
➡️ Monthly Consistency Score: 0.1635

=== [2398/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.57it/s]
Hypertuning:  69%|██████▉   | 2398/3456 [55:37<24:01,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.2236
➡️ Total Profit: ₹52,760.93
➡️ Equity Curve R²: 0.1140
➡️ Monthly Consistency Score: 0.2375

=== [2399/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.33it/s]
Hypertuning:  69%|██████▉   | 2399/3456 [55:39<24:11,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.0018
➡️ Total Profit: ₹40,478.43
➡️ Equity Curve R²: 0.0823
➡️ Monthly Consistency Score: 0.1591

=== [2400/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.95it/s]
Hypertuning:  69%|██████▉   | 2400/3456 [55:40<23:50,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.7594
➡️ Total Profit: ₹67,032.83
➡️ Equity Curve R²: 0.5786
➡️ Monthly Consistency Score: 0.3174

=== [2401/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.41it/s]
Hypertuning:  69%|██████▉   | 2401/3456 [55:42<24:21,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.7699
➡️ Total Profit: ₹-74,058.75
➡️ Equity Curve R²: 0.9673
➡️ Monthly Consistency Score: -0.3062

=== [2402/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.04it/s]
Hypertuning:  70%|██████▉   | 2402/3456 [55:43<24:04,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2802
➡️ Total Profit: ₹-11,919.99
➡️ Equity Curve R²: 0.8227
➡️ Monthly Consistency Score: -0.0514

=== [2403/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.41it/s]
Hypertuning:  70%|██████▉   | 2403/3456 [55:44<24:12,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.1088
➡️ Total Profit: ₹-6,551.40
➡️ Equity Curve R²: 0.6795
➡️ Monthly Consistency Score: -0.0240

=== [2404/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.77it/s]
Hypertuning:  70%|██████▉   | 2404/3456 [55:46<23:48,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.9230
➡️ Total Profit: ₹51,878.96
➡️ Equity Curve R²: 0.7765
➡️ Monthly Consistency Score: 0.1826

=== [2405/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.41it/s]
Hypertuning:  70%|██████▉   | 2405/3456 [55:47<24:06,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.7379
➡️ Total Profit: ₹46,883.82
➡️ Equity Curve R²: 0.7185
➡️ Monthly Consistency Score: 0.1650

=== [2406/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.80it/s]
Hypertuning:  70%|██████▉   | 2406/3456 [55:48<23:51,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.8541
➡️ Total Profit: ₹24,279.49
➡️ Equity Curve R²: 0.2518
➡️ Monthly Consistency Score: 0.0829

=== [2407/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.59it/s]
Hypertuning:  70%|██████▉   | 2407/3456 [55:50<23:26,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.0208
➡️ Total Profit: ₹721.40
➡️ Equity Curve R²: 0.3909
➡️ Monthly Consistency Score: 0.0026

=== [2408/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.42it/s]
Hypertuning:  70%|██████▉   | 2408/3456 [55:51<23:38,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.7768
➡️ Total Profit: ₹34,064.97
➡️ Equity Curve R²: 0.3402
➡️ Monthly Consistency Score: 0.1452

=== [2409/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.79it/s]
Hypertuning:  70%|██████▉   | 2409/3456 [55:52<23:31,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6210
➡️ Total Profit: ₹17,204.48
➡️ Equity Curve R²: 0.0229
➡️ Monthly Consistency Score: 0.0675

=== [2410/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.84it/s]
Hypertuning:  70%|██████▉   | 2410/3456 [55:54<23:43,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4895
➡️ Total Profit: ₹11,219.41
➡️ Equity Curve R²: 0.1197
➡️ Monthly Consistency Score: 0.0474

=== [2411/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.22it/s]
Hypertuning:  70%|██████▉   | 2411/3456 [55:55<23:24,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.7296
➡️ Total Profit: ₹24,040.88
➡️ Equity Curve R²: 0.0822
➡️ Monthly Consistency Score: 0.1025

=== [2412/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.80it/s]
Hypertuning:  70%|██████▉   | 2412/3456 [55:56<23:31,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1423
➡️ Total Profit: ₹4,572.00
➡️ Equity Curve R²: 0.3315
➡️ Monthly Consistency Score: 0.0175

=== [2413/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.66it/s]
Hypertuning:  70%|██████▉   | 2413/3456 [55:58<23:54,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.6326
➡️ Total Profit: ₹18,608.20
➡️ Equity Curve R²: 0.1374
➡️ Monthly Consistency Score: 0.0698

=== [2414/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.54it/s]
Hypertuning:  70%|██████▉   | 2414/3456 [55:59<23:34,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.9893
➡️ Total Profit: ₹32,422.77
➡️ Equity Curve R²: 0.0074
➡️ Monthly Consistency Score: 0.1351

=== [2415/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.69it/s]
Hypertuning:  70%|██████▉   | 2415/3456 [56:00<23:11,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.1396
➡️ Total Profit: ₹40,472.95
➡️ Equity Curve R²: 0.0121
➡️ Monthly Consistency Score: 0.1816

=== [2416/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.96it/s]
Hypertuning:  70%|██████▉   | 2416/3456 [56:02<23:22,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 4.2701
➡️ Total Profit: ₹76,124.66
➡️ Equity Curve R²: 0.7766
➡️ Monthly Consistency Score: 0.3489

=== [2417/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.85it/s]
Hypertuning:  70%|██████▉   | 2417/3456 [56:03<23:50,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.7456
➡️ Total Profit: ₹-63,058.83
➡️ Equity Curve R²: 0.9579
➡️ Monthly Consistency Score: -0.2666

=== [2418/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.77it/s]
Hypertuning:  70%|██████▉   | 2418/3456 [56:05<23:35,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2117
➡️ Total Profit: ₹-8,529.07
➡️ Equity Curve R²: 0.8040
➡️ Monthly Consistency Score: -0.0362

=== [2419/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.81it/s]
Hypertuning:  70%|██████▉   | 2419/3456 [56:06<23:13,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.0965
➡️ Total Profit: ₹4,868.19
➡️ Equity Curve R²: 0.4605
➡️ Monthly Consistency Score: 0.0185

=== [2420/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.67it/s]
Hypertuning:  70%|███████   | 2420/3456 [56:07<23:23,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.9440
➡️ Total Profit: ₹23,839.77
➡️ Equity Curve R²: 0.3035
➡️ Monthly Consistency Score: 0.0875

=== [2421/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.86it/s]
Hypertuning:  70%|███████   | 2421/3456 [56:09<23:45,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.1197
➡️ Total Profit: ₹30,207.71
➡️ Equity Curve R²: 0.6199
➡️ Monthly Consistency Score: 0.1019

=== [2422/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.29it/s]
Hypertuning:  70%|███████   | 2422/3456 [56:10<23:26,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.7625
➡️ Total Profit: ₹21,675.81
➡️ Equity Curve R²: 0.2420
➡️ Monthly Consistency Score: 0.0776

=== [2423/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.72it/s]
Hypertuning:  70%|███████   | 2423/3456 [56:11<23:03,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.5610
➡️ Total Profit: ₹33,261.78
➡️ Equity Curve R²: 0.4305
➡️ Monthly Consistency Score: 0.1151

=== [2424/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.95it/s]
Hypertuning:  70%|███████   | 2424/3456 [56:13<23:14,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.7259
➡️ Total Profit: ₹23,416.79
➡️ Equity Curve R²: 0.0343
➡️ Monthly Consistency Score: 0.0940

=== [2425/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.90it/s]
Hypertuning:  70%|███████   | 2425/3456 [56:14<23:30,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.7212
➡️ Total Profit: ₹20,358.71
➡️ Equity Curve R²: 0.0021
➡️ Monthly Consistency Score: 0.0757

=== [2426/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.00it/s]
Hypertuning:  70%|███████   | 2426/3456 [56:15<23:14,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.7071
➡️ Total Profit: ₹14,608.49
➡️ Equity Curve R²: 0.0451
➡️ Monthly Consistency Score: 0.0612

=== [2427/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.12it/s]
Hypertuning:  70%|███████   | 2427/3456 [56:17<23:22,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.0332
➡️ Total Profit: ₹23,694.42
➡️ Equity Curve R²: 0.0668
➡️ Monthly Consistency Score: 0.0904

=== [2428/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.61it/s]
Hypertuning:  70%|███████   | 2428/3456 [56:18<23:05,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1096
➡️ Total Profit: ₹-3,940.72
➡️ Equity Curve R²: 0.3065
➡️ Monthly Consistency Score: -0.0152

=== [2429/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.17it/s]
Hypertuning:  70%|███████   | 2429/3456 [56:20<23:34,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.7503
➡️ Total Profit: ₹21,127.26
➡️ Equity Curve R²: 0.0581
➡️ Monthly Consistency Score: 0.0803

=== [2430/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.83it/s]
Hypertuning:  70%|███████   | 2430/3456 [56:21<23:16,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.0238
➡️ Total Profit: ₹33,551.85
➡️ Equity Curve R²: 0.0192
➡️ Monthly Consistency Score: 0.1395

=== [2431/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 130.92it/s]
Hypertuning:  70%|███████   | 2431/3456 [56:22<23:27,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1855
➡️ Total Profit: ₹42,104.32
➡️ Equity Curve R²: 0.0198
➡️ Monthly Consistency Score: 0.1890

=== [2432/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.51it/s]
Hypertuning:  70%|███████   | 2432/3456 [56:24<23:07,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 4.4977
➡️ Total Profit: ₹67,036.47
➡️ Equity Curve R²: 0.6352
➡️ Monthly Consistency Score: 0.3205

=== [2433/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.33it/s]
Hypertuning:  70%|███████   | 2433/3456 [56:25<23:27,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.7836
➡️ Total Profit: ₹-68,584.27
➡️ Equity Curve R²: 0.9635
➡️ Monthly Consistency Score: -0.2845

=== [2434/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.58it/s]
Hypertuning:  70%|███████   | 2434/3456 [56:26<23:05,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.5063
➡️ Total Profit: ₹-34,252.76
➡️ Equity Curve R²: 0.9200
➡️ Monthly Consistency Score: -0.1359

=== [2435/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.03it/s]
Hypertuning:  70%|███████   | 2435/3456 [56:28<23:17,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0495
➡️ Total Profit: ₹-2,429.07
➡️ Equity Curve R²: 0.5488
➡️ Monthly Consistency Score: -0.0093

=== [2436/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.31it/s]
Hypertuning:  70%|███████   | 2436/3456 [56:29<22:55,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.1190
➡️ Total Profit: ₹41,054.41
➡️ Equity Curve R²: 0.6143
➡️ Monthly Consistency Score: 0.1501

=== [2437/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.12it/s]
Hypertuning:  71%|███████   | 2437/3456 [56:31<23:29,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.8159
➡️ Total Profit: ₹35,237.81
➡️ Equity Curve R²: 0.6542
➡️ Monthly Consistency Score: 0.1255

=== [2438/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.51it/s]
Hypertuning:  71%|███████   | 2438/3456 [56:32<23:14,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.2526
➡️ Total Profit: ₹8,622.93
➡️ Equity Curve R²: 0.3930
➡️ Monthly Consistency Score: 0.0339

=== [2439/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.95it/s]
Hypertuning:  71%|███████   | 2439/3456 [56:33<22:50,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.8631
➡️ Total Profit: ₹16,984.89
➡️ Equity Curve R²: 0.3887
➡️ Monthly Consistency Score: 0.0614

=== [2440/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.73it/s]
Hypertuning:  71%|███████   | 2440/3456 [56:35<22:55,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.7512
➡️ Total Profit: ₹38,324.97
➡️ Equity Curve R²: 0.3841
➡️ Monthly Consistency Score: 0.1509

=== [2441/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.84it/s]
Hypertuning:  71%|███████   | 2441/3456 [56:36<23:18,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.6133
➡️ Total Profit: ₹16,574.95
➡️ Equity Curve R²: 0.0080
➡️ Monthly Consistency Score: 0.0656

=== [2442/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.41it/s]
Hypertuning:  71%|███████   | 2442/3456 [56:37<23:01,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2888
➡️ Total Profit: ₹11,392.05
➡️ Equity Curve R²: 0.3816
➡️ Monthly Consistency Score: 0.0406

=== [2443/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.71it/s]
Hypertuning:  71%|███████   | 2443/3456 [56:39<23:11,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.5417
➡️ Total Profit: ₹43,954.42
➡️ Equity Curve R²: 0.0358
➡️ Monthly Consistency Score: 0.1885

=== [2444/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.43it/s]
Hypertuning:  71%|███████   | 2444/3456 [56:40<22:51,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.9111
➡️ Total Profit: ₹55,973.93
➡️ Equity Curve R²: 0.1049
➡️ Monthly Consistency Score: 0.2069

=== [2445/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.95it/s]
Hypertuning:  71%|███████   | 2445/3456 [56:41<22:42,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.0659
➡️ Total Profit: ₹25,751.07
➡️ Equity Curve R²: 0.0268
➡️ Monthly Consistency Score: 0.0997

=== [2446/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.55it/s]
Hypertuning:  71%|███████   | 2446/3456 [56:43<22:54,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.3819
➡️ Total Profit: ₹48,531.03
➡️ Equity Curve R²: 0.0095
➡️ Monthly Consistency Score: 0.1983

=== [2447/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.00it/s]
Hypertuning:  71%|███████   | 2447/3456 [56:44<22:40,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.3054
➡️ Total Profit: ₹42,107.06
➡️ Equity Curve R²: 0.0000
➡️ Monthly Consistency Score: 0.1975

=== [2448/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.89it/s]
Hypertuning:  71%|███████   | 2448/3456 [56:45<22:51,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.7604
➡️ Total Profit: ₹67,036.47
➡️ Equity Curve R²: 0.5931
➡️ Monthly Consistency Score: 0.3369

=== [2449/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.58it/s]
Hypertuning:  71%|███████   | 2449/3456 [56:47<22:42,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.7714
➡️ Total Profit: ₹-74,689.22
➡️ Equity Curve R²: 0.9681
➡️ Monthly Consistency Score: -0.3061

=== [2450/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.65it/s]
Hypertuning:  71%|███████   | 2450/3456 [56:48<22:53,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0943
➡️ Total Profit: ₹-4,012.59
➡️ Equity Curve R²: 0.7631
➡️ Monthly Consistency Score: -0.0168

=== [2451/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.86it/s]
Hypertuning:  71%|███████   | 2451/3456 [56:50<23:02,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.1024
➡️ Total Profit: ₹-6,164.08
➡️ Equity Curve R²: 0.6678
➡️ Monthly Consistency Score: -0.0225

=== [2452/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.72it/s]
Hypertuning:  71%|███████   | 2452/3456 [56:51<22:41,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.8029
➡️ Total Profit: ₹49,747.14
➡️ Equity Curve R²: 0.7807
➡️ Monthly Consistency Score: 0.1770

=== [2453/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.06it/s]
Hypertuning:  71%|███████   | 2453/3456 [56:52<22:31,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.7612
➡️ Total Profit: ₹47,513.35
➡️ Equity Curve R²: 0.7173
➡️ Monthly Consistency Score: 0.1668

=== [2454/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.35it/s]
Hypertuning:  71%|███████   | 2454/3456 [56:54<22:41,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.9336
➡️ Total Profit: ₹26,539.49
➡️ Equity Curve R²: 0.2990
➡️ Monthly Consistency Score: 0.0913

=== [2455/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.91it/s]
Hypertuning:  71%|███████   | 2455/3456 [56:55<22:23,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.0261
➡️ Total Profit: ₹21,890.41
➡️ Equity Curve R²: 0.3253
➡️ Monthly Consistency Score: 0.0802

=== [2456/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.62it/s]
Hypertuning:  71%|███████   | 2456/3456 [56:56<22:37,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.6656
➡️ Total Profit: ₹31,933.15
➡️ Equity Curve R²: 0.3521
➡️ Monthly Consistency Score: 0.1372

=== [2457/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.35it/s]
Hypertuning:  71%|███████   | 2457/3456 [56:58<22:26,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6210
➡️ Total Profit: ₹17,204.48
➡️ Equity Curve R²: 0.0229
➡️ Monthly Consistency Score: 0.0675

=== [2458/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.95it/s]
Hypertuning:  71%|███████   | 2458/3456 [56:59<22:35,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4895
➡️ Total Profit: ₹11,219.41
➡️ Equity Curve R²: 0.1197
➡️ Monthly Consistency Score: 0.0474

=== [2459/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.12it/s]
Hypertuning:  71%|███████   | 2459/3456 [57:00<22:14,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.0024
➡️ Total Profit: ₹31,843.05
➡️ Equity Curve R²: 0.0009
➡️ Monthly Consistency Score: 0.1380

=== [2460/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.89it/s]
Hypertuning:  71%|███████   | 2460/3456 [57:02<22:24,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.0759
➡️ Total Profit: ₹2,440.18
➡️ Equity Curve R²: 0.3324
➡️ Monthly Consistency Score: 0.0093

=== [2461/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.43it/s]
Hypertuning:  71%|███████   | 2461/3456 [57:03<22:15,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.6112
➡️ Total Profit: ₹17,977.73
➡️ Equity Curve R²: 0.1385
➡️ Monthly Consistency Score: 0.0672

=== [2462/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.57it/s]
Hypertuning:  71%|███████   | 2462/3456 [57:04<22:30,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.1272
➡️ Total Profit: ₹36,942.77
➡️ Equity Curve R²: 0.0210
➡️ Monthly Consistency Score: 0.1533

=== [2463/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.35it/s]
Hypertuning:  71%|███████▏  | 2463/3456 [57:06<22:41,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1396
➡️ Total Profit: ₹40,472.95
➡️ Equity Curve R²: 0.0121
➡️ Monthly Consistency Score: 0.1816

=== [2464/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.19it/s]
Hypertuning:  71%|███████▏  | 2464/3456 [57:07<22:23,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 4.2701
➡️ Total Profit: ₹76,124.66
➡️ Equity Curve R²: 0.7766
➡️ Monthly Consistency Score: 0.3489

=== [2465/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.23it/s]
Hypertuning:  71%|███████▏  | 2465/3456 [57:08<22:21,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.7407
➡️ Total Profit: ₹-65,024.47
➡️ Equity Curve R²: 0.9572
➡️ Monthly Consistency Score: -0.2838

=== [2466/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.70it/s]
Hypertuning:  71%|███████▏  | 2466/3456 [57:10<22:32,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2475
➡️ Total Profit: ₹-10,872.79
➡️ Equity Curve R²: 0.8061
➡️ Monthly Consistency Score: -0.0447

=== [2467/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.78it/s]
Hypertuning:  71%|███████▏  | 2467/3456 [57:11<22:11,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0546
➡️ Total Profit: ₹-3,288.66
➡️ Equity Curve R²: 0.6851
➡️ Monthly Consistency Score: -0.0125

=== [2468/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.42it/s]
Hypertuning:  71%|███████▏  | 2468/3456 [57:13<22:19,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.1635
➡️ Total Profit: ₹47,615.32
➡️ Equity Curve R²: 0.6784
➡️ Monthly Consistency Score: 0.1705

=== [2469/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.67it/s]
Hypertuning:  71%|███████▏  | 2469/3456 [57:14<22:11,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.5377
➡️ Total Profit: ₹30,828.28
➡️ Equity Curve R²: 0.5656
➡️ Monthly Consistency Score: 0.1115

=== [2470/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.71it/s]
Hypertuning:  71%|███████▏  | 2470/3456 [57:15<22:23,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1266
➡️ Total Profit: ₹-4,231.55
➡️ Equity Curve R²: 0.4799
➡️ Monthly Consistency Score: -0.0164

=== [2471/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.02it/s]
Hypertuning:  71%|███████▏  | 2471/3456 [57:17<22:02,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.8743
➡️ Total Profit: ₹18,630.41
➡️ Equity Curve R²: 0.0460
➡️ Monthly Consistency Score: 0.0697

=== [2472/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.90it/s]
Hypertuning:  72%|███████▏  | 2472/3456 [57:18<22:07,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.1102
➡️ Total Profit: ₹40,456.79
➡️ Equity Curve R²: 0.5145
➡️ Monthly Consistency Score: 0.1709

=== [2473/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.08it/s]
Hypertuning:  72%|███████▏  | 2473/3456 [57:19<22:02,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.5638
➡️ Total Profit: ₹15,946.36
➡️ Equity Curve R²: 0.0325
➡️ Monthly Consistency Score: 0.0622

=== [2474/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.45it/s]
Hypertuning:  72%|███████▏  | 2474/3456 [57:21<22:20,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.1242
➡️ Total Profit: ₹4,615.73
➡️ Equity Curve R²: 0.2610
➡️ Monthly Consistency Score: 0.0170

=== [2475/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.87it/s]
Hypertuning:  72%|███████▏  | 2475/3456 [57:22<22:01,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.6747
➡️ Total Profit: ₹50,471.68
➡️ Equity Curve R²: 0.0373
➡️ Monthly Consistency Score: 0.2169

=== [2476/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.07it/s]
Hypertuning:  72%|███████▏  | 2476/3456 [57:23<22:10,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2839
➡️ Total Profit: ₹6,703.82
➡️ Equity Curve R²: 0.0176
➡️ Monthly Consistency Score: 0.0266

=== [2477/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.62it/s]
Hypertuning:  72%|███████▏  | 2477/3456 [57:25<22:06,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.1505
➡️ Total Profit: ₹28,272.01
➡️ Equity Curve R²: 0.0871
➡️ Monthly Consistency Score: 0.1096

=== [2478/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.51it/s]
Hypertuning:  72%|███████▏  | 2478/3456 [57:26<22:15,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.8513
➡️ Total Profit: ₹27,900.93
➡️ Equity Curve R²: 0.0005
➡️ Monthly Consistency Score: 0.1151

=== [2479/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.85it/s]
Hypertuning:  72%|███████▏  | 2479/3456 [57:27<22:23,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.2314
➡️ Total Profit: ₹43,732.95
➡️ Equity Curve R²: 0.0313
➡️ Monthly Consistency Score: 0.1960

=== [2480/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.38it/s]
Hypertuning:  72%|███████▏  | 2480/3456 [57:29<22:03,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 4.2701
➡️ Total Profit: ₹76,124.66
➡️ Equity Curve R²: 0.7766
➡️ Monthly Consistency Score: 0.3489

=== [2481/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.52it/s]
Hypertuning:  72%|███████▏  | 2481/3456 [57:30<21:58,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.8223
➡️ Total Profit: ₹-68,588.03
➡️ Equity Curve R²: 0.9718
➡️ Monthly Consistency Score: -0.3046

=== [2482/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.01it/s]
Hypertuning:  72%|███████▏  | 2482/3456 [57:32<22:11,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2902
➡️ Total Profit: ₹-13,405.55
➡️ Equity Curve R²: 0.8530
➡️ Monthly Consistency Score: -0.0561

=== [2483/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.77it/s]
Hypertuning:  72%|███████▏  | 2483/3456 [57:33<21:52,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0979
➡️ Total Profit: ₹-5,304.49
➡️ Equity Curve R²: 0.6480
➡️ Monthly Consistency Score: -0.0188

=== [2484/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.53it/s]
Hypertuning:  72%|███████▏  | 2484/3456 [57:34<22:05,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.4829
➡️ Total Profit: ₹56,787.14
➡️ Equity Curve R²: 0.8972
➡️ Monthly Consistency Score: 0.2059

=== [2485/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.77it/s]
Hypertuning:  72%|███████▏  | 2485/3456 [57:36<22:23,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.1690
➡️ Total Profit: ₹23,612.53
➡️ Equity Curve R²: 0.5741
➡️ Monthly Consistency Score: 0.0883

=== [2486/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.57it/s]
Hypertuning:  72%|███████▏  | 2486/3456 [57:37<22:03,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5928
➡️ Total Profit: ₹14,623.05
➡️ Equity Curve R²: 0.0303
➡️ Monthly Consistency Score: 0.0568

=== [2487/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.77it/s]
Hypertuning:  72%|███████▏  | 2487/3456 [57:38<22:12,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.5450
➡️ Total Profit: ₹17,029.63
➡️ Equity Curve R²: 0.0260
➡️ Monthly Consistency Score: 0.0648

=== [2488/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.33it/s]
Hypertuning:  72%|███████▏  | 2488/3456 [57:40<21:51,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4127
➡️ Total Profit: ₹15,199.45
➡️ Equity Curve R²: 0.0276
➡️ Monthly Consistency Score: 0.0625

=== [2489/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.64it/s]
Hypertuning:  72%|███████▏  | 2489/3456 [57:41<21:45,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.7065
➡️ Total Profit: ₹19,094.95
➡️ Equity Curve R²: 0.0013
➡️ Monthly Consistency Score: 0.0756

=== [2490/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.33it/s]
Hypertuning:  72%|███████▏  | 2490/3456 [57:42<21:56,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3844
➡️ Total Profit: ₹-14,769.68
➡️ Equity Curve R²: 0.6957
➡️ Monthly Consistency Score: -0.0553

=== [2491/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.72it/s]
Hypertuning:  72%|███████▏  | 2491/3456 [57:44<22:11,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.0200
➡️ Total Profit: ₹43,957.16
➡️ Equity Curve R²: 0.1564
➡️ Monthly Consistency Score: 0.1786

=== [2492/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.38it/s]
Hypertuning:  72%|███████▏  | 2492/3456 [57:45<21:53,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.1872
➡️ Total Profit: ₹74,659.30
➡️ Equity Curve R²: 0.7673
➡️ Monthly Consistency Score: 0.3296

=== [2493/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.86it/s]
Hypertuning:  72%|███████▏  | 2493/3456 [57:47<21:52,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.3124
➡️ Total Profit: ₹31,423.42
➡️ Equity Curve R²: 0.0798
➡️ Monthly Consistency Score: 0.1224

=== [2494/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.16it/s]
Hypertuning:  72%|███████▏  | 2494/3456 [57:48<22:01,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.0478
➡️ Total Profit: ₹82,668.18
➡️ Equity Curve R²: 0.6995
➡️ Monthly Consistency Score: 0.3370

=== [2495/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.77it/s]
Hypertuning:  72%|███████▏  | 2495/3456 [57:49<21:38,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4985
➡️ Total Profit: ₹20,834.67
➡️ Equity Curve R²: 0.3744
➡️ Monthly Consistency Score: 0.0897

=== [2496/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.19it/s]
Hypertuning:  72%|███████▏  | 2496/3456 [57:51<21:42,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.7604
➡️ Total Profit: ₹67,036.47
➡️ Equity Curve R²: 0.5931
➡️ Monthly Consistency Score: 0.3369

=== [2497/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.23it/s]
Hypertuning:  72%|███████▏  | 2497/3456 [57:52<22:01,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.6744
➡️ Total Profit: ₹-60,203.93
➡️ Equity Curve R²: 0.9457
➡️ Monthly Consistency Score: -0.2452

=== [2498/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.99it/s]
Hypertuning:  72%|███████▏  | 2498/3456 [57:53<21:46,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3228
➡️ Total Profit: ₹-17,741.23
➡️ Equity Curve R²: 0.8811
➡️ Monthly Consistency Score: -0.0697

=== [2499/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.12it/s]
Hypertuning:  72%|███████▏  | 2499/3456 [57:55<21:25,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.2089
➡️ Total Profit: ₹10,611.41
➡️ Equity Curve R²: 0.3691
➡️ Monthly Consistency Score: 0.0382

=== [2500/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.09it/s]
Hypertuning:  72%|███████▏  | 2500/3456 [57:56<21:31,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.4271
➡️ Total Profit: ₹33,102.75
➡️ Equity Curve R²: 0.0609
➡️ Monthly Consistency Score: 0.1159

=== [2501/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.82it/s]
Hypertuning:  72%|███████▏  | 2501/3456 [57:57<21:54,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.2871
➡️ Total Profit: ₹8,498.11
➡️ Equity Curve R²: 0.1932
➡️ Monthly Consistency Score: 0.0305

=== [2502/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.18it/s]
Hypertuning:  72%|███████▏  | 2502/3456 [57:59<21:41,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2797
➡️ Total Profit: ₹-14,847.16
➡️ Equity Curve R²: 0.8009
➡️ Monthly Consistency Score: -0.0481

=== [2503/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.95it/s]
Hypertuning:  72%|███████▏  | 2503/3456 [58:00<21:20,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.2568
➡️ Total Profit: ₹-12,271.12
➡️ Equity Curve R²: 0.6898
➡️ Monthly Consistency Score: -0.0452

=== [2504/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.64it/s]
Hypertuning:  72%|███████▏  | 2504/3456 [58:01<21:25,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3184
➡️ Total Profit: ₹10,939.73
➡️ Equity Curve R²: 0.1040
➡️ Monthly Consistency Score: 0.0412

=== [2505/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 111.88it/s]
Hypertuning:  72%|███████▏  | 2505/3456 [58:03<21:19,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.0827
➡️ Total Profit: ₹-4,213.98
➡️ Equity Curve R²: 0.6280
➡️ Monthly Consistency Score: -0.0155

=== [2506/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.51it/s]
Hypertuning:  73%|███████▎  | 2506/3456 [58:04<21:34,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4568
➡️ Total Profit: ₹15,916.05
➡️ Equity Curve R²: 0.1528
➡️ Monthly Consistency Score: 0.0557

=== [2507/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.83it/s]
Hypertuning:  73%|███████▎  | 2507/3456 [58:05<21:14,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.7397
➡️ Total Profit: ₹58,043.62
➡️ Equity Curve R²: 0.5981
➡️ Monthly Consistency Score: 0.2281

=== [2508/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.40it/s]
Hypertuning:  73%|███████▎  | 2508/3456 [58:07<21:22,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.2327
➡️ Total Profit: ₹38,445.83
➡️ Equity Curve R²: 0.0426
➡️ Monthly Consistency Score: 0.1412

=== [2509/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.09it/s]
Hypertuning:  73%|███████▎  | 2509/3456 [58:08<21:36,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.4675
➡️ Total Profit: ₹17,773.79
➡️ Equity Curve R²: 0.1997
➡️ Monthly Consistency Score: 0.0674

=== [2510/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.54it/s]
Hypertuning:  73%|███████▎  | 2510/3456 [58:10<21:20,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.3792
➡️ Total Profit: ₹60,887.80
➡️ Equity Curve R²: 0.0233
➡️ Monthly Consistency Score: 0.2260

=== [2511/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.43it/s]
Hypertuning:  73%|███████▎  | 2511/3456 [58:11<21:36,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.2402
➡️ Total Profit: ₹61,669.80
➡️ Equity Curve R²: 0.2687
➡️ Monthly Consistency Score: 0.2610

=== [2512/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.82it/s]
Hypertuning:  73%|███████▎  | 2512/3456 [58:12<21:16,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 9.8760
➡️ Total Profit: ₹105,161.14
➡️ Equity Curve R²: 0.8954
➡️ Monthly Consistency Score: 0.5218

=== [2513/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.41it/s]
Hypertuning:  73%|███████▎  | 2513/3456 [58:14<21:40,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.6452
➡️ Total Profit: ₹-51,724.00
➡️ Equity Curve R²: 0.9262
➡️ Monthly Consistency Score: -0.2148

=== [2514/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.91it/s]
Hypertuning:  73%|███████▎  | 2514/3456 [58:15<21:24,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3051
➡️ Total Profit: ₹-16,615.83
➡️ Equity Curve R²: 0.8797
➡️ Monthly Consistency Score: -0.0699

=== [2515/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.30it/s]
Hypertuning:  73%|███████▎  | 2515/3456 [58:16<21:33,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.1410
➡️ Total Profit: ₹7,741.35
➡️ Equity Curve R²: 0.4236
➡️ Monthly Consistency Score: 0.0281

=== [2516/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.19it/s]
Hypertuning:  73%|███████▎  | 2516/3456 [58:18<21:10,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.5713
➡️ Total Profit: ₹33,102.75
➡️ Equity Curve R²: 0.1643
➡️ Monthly Consistency Score: 0.1177

=== [2517/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.20it/s]
Hypertuning:  73%|███████▎  | 2517/3456 [58:19<21:29,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0486
➡️ Total Profit: ₹-1,408.35
➡️ Equity Curve R²: 0.1832
➡️ Monthly Consistency Score: -0.0051

=== [2518/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.29it/s]
Hypertuning:  73%|███████▎  | 2518/3456 [58:21<21:15,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3364
➡️ Total Profit: ₹-15,198.20
➡️ Equity Curve R²: 0.7445
➡️ Monthly Consistency Score: -0.0558

=== [2519/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.49it/s]
Hypertuning:  73%|███████▎  | 2519/3456 [58:22<21:26,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2723
➡️ Total Profit: ₹-13,899.75
➡️ Equity Curve R²: 0.7631
➡️ Monthly Consistency Score: -0.0508

=== [2520/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.64it/s]
Hypertuning:  73%|███████▎  | 2520/3456 [58:23<21:12,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4390
➡️ Total Profit: ₹14,287.91
➡️ Equity Curve R²: 0.0027
➡️ Monthly Consistency Score: 0.0526

=== [2521/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.84it/s]
Hypertuning:  73%|███████▎  | 2521/3456 [58:25<21:37,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.1088
➡️ Total Profit: ₹-5,473.04
➡️ Equity Curve R²: 0.6276
➡️ Monthly Consistency Score: -0.0203

=== [2522/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.52it/s]
Hypertuning:  73%|███████▎  | 2522/3456 [58:26<21:19,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.2895
➡️ Total Profit: ₹11,396.05
➡️ Equity Curve R²: 0.2901
➡️ Monthly Consistency Score: 0.0386

=== [2523/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.00it/s]
Hypertuning:  73%|███████▎  | 2523/3456 [58:27<20:59,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.1077
➡️ Total Profit: ₹65,840.32
➡️ Equity Curve R²: 0.6321
➡️ Monthly Consistency Score: 0.2629

=== [2524/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.70it/s]
Hypertuning:  73%|███████▎  | 2524/3456 [58:29<21:08,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.3229
➡️ Total Profit: ₹38,445.83
➡️ Equity Curve R²: 0.1076
➡️ Monthly Consistency Score: 0.1417

=== [2525/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.47it/s]
Hypertuning:  73%|███████▎  | 2525/3456 [58:30<21:02,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4923
➡️ Total Profit: ₹18,404.26
➡️ Equity Curve R²: 0.1969
➡️ Monthly Consistency Score: 0.0699

=== [2526/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.97it/s]
Hypertuning:  73%|███████▎  | 2526/3456 [58:31<21:12,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.4344
➡️ Total Profit: ₹77,012.18
➡️ Equity Curve R²: 0.1606
➡️ Monthly Consistency Score: 0.3316

=== [2527/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.10it/s]
Hypertuning:  73%|███████▎  | 2527/3456 [58:33<20:49,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 4.0144
➡️ Total Profit: ₹84,672.55
➡️ Equity Curve R²: 0.7816
➡️ Monthly Consistency Score: 0.3388

=== [2528/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.64it/s]
Hypertuning:  73%|███████▎  | 2528/3456 [58:34<21:02,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 4.2111
➡️ Total Profit: ₹62,780.11
➡️ Equity Curve R²: 0.6799
➡️ Monthly Consistency Score: 0.2787

=== [2529/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.54it/s]
Hypertuning:  73%|███████▎  | 2529/3456 [58:36<21:30,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.7169
➡️ Total Profit: ₹-59,138.32
➡️ Equity Curve R²: 0.9413
➡️ Monthly Consistency Score: -0.2373

=== [2530/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.17it/s]
Hypertuning:  73%|███████▎  | 2530/3456 [58:37<21:14,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.4048
➡️ Total Profit: ₹-24,601.28
➡️ Equity Curve R²: 0.9178
➡️ Monthly Consistency Score: -0.1035

=== [2531/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.96it/s]
Hypertuning:  73%|███████▎  | 2531/3456 [58:38<20:53,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0376
➡️ Total Profit: ₹2,001.35
➡️ Equity Curve R²: 0.4994
➡️ Monthly Consistency Score: 0.0073

=== [2532/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.35it/s]
Hypertuning:  73%|███████▎  | 2532/3456 [58:40<21:03,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.7330
➡️ Total Profit: ₹50,137.19
➡️ Equity Curve R²: 0.7258
➡️ Monthly Consistency Score: 0.1788

=== [2533/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.90it/s]
Hypertuning:  73%|███████▎  | 2533/3456 [58:41<20:55,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.7220
➡️ Total Profit: ₹20,920.81
➡️ Equity Curve R²: 0.0623
➡️ Monthly Consistency Score: 0.0742

=== [2534/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.42it/s]
Hypertuning:  73%|███████▎  | 2534/3456 [58:42<21:06,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2954
➡️ Total Profit: ₹-15,114.64
➡️ Equity Curve R²: 0.7273
➡️ Monthly Consistency Score: -0.0550

=== [2535/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.92it/s]
Hypertuning:  73%|███████▎  | 2535/3456 [58:44<21:15,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.4316
➡️ Total Profit: ₹-22,030.75
➡️ Equity Curve R²: 0.8648
➡️ Monthly Consistency Score: -0.0875

=== [2536/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.50it/s]
Hypertuning:  73%|███████▎  | 2536/3456 [58:45<20:54,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.6702
➡️ Total Profit: ₹19,158.75
➡️ Equity Curve R²: 0.2114
➡️ Monthly Consistency Score: 0.0690

=== [2537/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.97it/s]
Hypertuning:  73%|███████▎  | 2537/3456 [58:46<20:49,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1230
➡️ Total Profit: ₹-6,732.10
➡️ Equity Curve R²: 0.6817
➡️ Monthly Consistency Score: -0.0249

=== [2538/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.36it/s]
Hypertuning:  73%|███████▎  | 2538/3456 [58:48<21:09,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.0670
➡️ Total Profit: ₹2,448.97
➡️ Equity Curve R²: 0.5298
➡️ Monthly Consistency Score: 0.0081

=== [2539/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.67it/s]
Hypertuning:  73%|███████▎  | 2539/3456 [58:49<20:48,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.6938
➡️ Total Profit: ₹65,845.80
➡️ Equity Curve R²: 0.5058
➡️ Monthly Consistency Score: 0.2674

=== [2540/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.94it/s]
Hypertuning:  73%|███████▎  | 2540/3456 [58:51<20:56,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.5282
➡️ Total Profit: ₹75,138.48
➡️ Equity Curve R²: 0.6042
➡️ Monthly Consistency Score: 0.2961

=== [2541/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.70it/s]
Hypertuning:  74%|███████▎  | 2541/3456 [58:52<20:48,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5954
➡️ Total Profit: ₹21,133.84
➡️ Equity Curve R²: 0.0602
➡️ Monthly Consistency Score: 0.0814

=== [2542/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.40it/s]
Hypertuning:  74%|███████▎  | 2542/3456 [58:53<20:58,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.6738
➡️ Total Profit: ₹62,924.94
➡️ Equity Curve R²: 0.0105
➡️ Monthly Consistency Score: 0.2890

=== [2543/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.45it/s]
Hypertuning:  74%|███████▎  | 2543/3456 [58:55<20:38,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 4.2456
➡️ Total Profit: ₹83,043.92
➡️ Equity Curve R²: 0.8119
➡️ Monthly Consistency Score: 0.3423

=== [2544/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.99it/s]
Hypertuning:  74%|███████▎  | 2544/3456 [58:56<20:41,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 4.2111
➡️ Total Profit: ₹62,780.11
➡️ Equity Curve R²: 0.7115
➡️ Monthly Consistency Score: 0.2740

=== [2545/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.38it/s]
Hypertuning:  74%|███████▎  | 2545/3456 [58:58<21:01,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.6673
➡️ Total Profit: ₹-59,574.39
➡️ Equity Curve R²: 0.9462
➡️ Monthly Consistency Score: -0.2415

=== [2546/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.61it/s]
Hypertuning:  74%|███████▎  | 2546/3456 [58:59<20:46,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1678
➡️ Total Profit: ₹-9,222.99
➡️ Equity Curve R²: 0.8460
➡️ Monthly Consistency Score: -0.0351

=== [2547/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.31it/s]
Hypertuning:  74%|███████▎  | 2547/3456 [59:00<20:28,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2422
➡️ Total Profit: ₹12,240.04
➡️ Equity Curve R²: 0.3508
➡️ Monthly Consistency Score: 0.0436

=== [2548/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.75it/s]
Hypertuning:  74%|███████▎  | 2548/3456 [59:02<20:36,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.4271
➡️ Total Profit: ₹33,102.75
➡️ Equity Curve R²: 0.0609
➡️ Monthly Consistency Score: 0.1159

=== [2549/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.25it/s]
Hypertuning:  74%|███████▍  | 2549/3456 [59:03<20:28,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3083
➡️ Total Profit: ₹9,127.64
➡️ Equity Curve R²: 0.1985
➡️ Monthly Consistency Score: 0.0327

=== [2550/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.12it/s]
Hypertuning:  74%|███████▍  | 2550/3456 [59:04<20:38,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2371
➡️ Total Profit: ₹-12,587.16
➡️ Equity Curve R²: 0.7814
➡️ Monthly Consistency Score: -0.0409

=== [2551/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.46it/s]
Hypertuning:  74%|███████▍  | 2551/3456 [59:06<20:49,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.2166
➡️ Total Profit: ₹8,874.78
➡️ Equity Curve R²: 0.0493
➡️ Monthly Consistency Score: 0.0308

=== [2552/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.42it/s]
Hypertuning:  74%|███████▍  | 2552/3456 [59:07<20:33,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2563
➡️ Total Profit: ₹8,807.91
➡️ Equity Curve R²: 0.0994
➡️ Monthly Consistency Score: 0.0334

=== [2553/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.90it/s]
Hypertuning:  74%|███████▍  | 2553/3456 [59:08<20:26,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0951
➡️ Total Profit: ₹-4,844.45
➡️ Equity Curve R²: 0.6344
➡️ Monthly Consistency Score: -0.0179

=== [2554/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.18it/s]
Hypertuning:  74%|███████▍  | 2554/3456 [59:10<20:36,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.4568
➡️ Total Profit: ₹15,916.05
➡️ Equity Curve R²: 0.1528
➡️ Monthly Consistency Score: 0.0557

=== [2555/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.61it/s]
Hypertuning:  74%|███████▍  | 2555/3456 [59:11<20:18,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.7431
➡️ Total Profit: ₹62,583.06
➡️ Equity Curve R²: 0.5812
➡️ Monthly Consistency Score: 0.2438

=== [2556/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 111.06it/s]
Hypertuning:  74%|███████▍  | 2556/3456 [59:12<20:32,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.2327
➡️ Total Profit: ₹38,445.83
➡️ Equity Curve R²: 0.0426
➡️ Monthly Consistency Score: 0.1412

=== [2557/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.28it/s]
Hypertuning:  74%|███████▍  | 2557/3456 [59:14<20:26,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4675
➡️ Total Profit: ₹17,773.79
➡️ Equity Curve R²: 0.1997
➡️ Monthly Consistency Score: 0.0674

=== [2558/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.45it/s]
Hypertuning:  74%|███████▍  | 2558/3456 [59:15<20:37,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.3792
➡️ Total Profit: ₹60,887.80
➡️ Equity Curve R²: 0.0233
➡️ Monthly Consistency Score: 0.2260

=== [2559/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.75it/s]
Hypertuning:  74%|███████▍  | 2559/3456 [59:17<20:37,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.2402
➡️ Total Profit: ₹61,669.80
➡️ Equity Curve R²: 0.2687
➡️ Monthly Consistency Score: 0.2610

=== [2560/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.06it/s]
Hypertuning:  74%|███████▍  | 2560/3456 [59:18<20:15,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 9.6758
➡️ Total Profit: ₹103,029.32
➡️ Equity Curve R²: 0.9012
➡️ Monthly Consistency Score: 0.5123

=== [2561/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.94it/s]
Hypertuning:  74%|███████▍  | 2561/3456 [59:19<20:38,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.6910
➡️ Total Profit: ₹-57,186.50
➡️ Equity Curve R²: 0.9343
➡️ Monthly Consistency Score: -0.2449

=== [2562/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.67it/s]
Hypertuning:  74%|███████▍  | 2562/3456 [59:21<20:22,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2661
➡️ Total Profit: ₹-13,306.79
➡️ Equity Curve R²: 0.8256
➡️ Monthly Consistency Score: -0.0547

=== [2563/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.88it/s]
Hypertuning:  74%|███████▍  | 2563/3456 [59:22<20:34,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.1081
➡️ Total Profit: ₹6,109.98
➡️ Equity Curve R²: 0.4552
➡️ Monthly Consistency Score: 0.0221

=== [2564/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.20it/s]
Hypertuning:  74%|███████▍  | 2564/3456 [59:23<20:19,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.4271
➡️ Total Profit: ₹33,102.75
➡️ Equity Curve R²: 0.0782
➡️ Monthly Consistency Score: 0.1183

=== [2565/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.66it/s]
Hypertuning:  74%|███████▍  | 2565/3456 [59:25<20:53,  1.41s/it]

➡️ Profit-to-Drawdown Ratio: 0.5849
➡️ Total Profit: ₹17,316.23
➡️ Equity Curve R²: 0.0020
➡️ Monthly Consistency Score: 0.0662

=== [2566/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.39it/s]
Hypertuning:  74%|███████▍  | 2566/3456 [59:27<21:41,  1.46s/it]

➡️ Profit-to-Drawdown Ratio: -0.3640
➡️ Total Profit: ₹-17,803.72
➡️ Equity Curve R²: 0.6995
➡️ Monthly Consistency Score: -0.0659

=== [2567/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.58it/s]
Hypertuning:  74%|███████▍  | 2567/3456 [59:28<21:36,  1.46s/it]

➡️ Profit-to-Drawdown Ratio: -0.2403
➡️ Total Profit: ₹-12,268.38
➡️ Equity Curve R²: 0.7669
➡️ Monthly Consistency Score: -0.0446

=== [2568/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.15it/s]
Hypertuning:  74%|███████▍  | 2568/3456 [59:30<22:03,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 0.2564
➡️ Total Profit: ₹8,811.55
➡️ Equity Curve R²: 0.0994
➡️ Monthly Consistency Score: 0.0335

=== [2569/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.66it/s]
Hypertuning:  74%|███████▍  | 2569/3456 [59:31<21:58,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: -0.0199
➡️ Total Profit: ₹-1,061.63
➡️ Equity Curve R²: 0.6928
➡️ Monthly Consistency Score: -0.0039

=== [2570/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.74it/s]
Hypertuning:  74%|███████▍  | 2570/3456 [59:33<22:26,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.0988
➡️ Total Profit: ₹3,490.65
➡️ Equity Curve R²: 0.5275
➡️ Monthly Consistency Score: 0.0117

=== [2571/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.23it/s]
Hypertuning:  74%|███████▍  | 2571/3456 [59:34<22:01,  1.49s/it]

➡️ Profit-to-Drawdown Ratio: 3.4156
➡️ Total Profit: ₹72,363.06
➡️ Equity Curve R²: 0.5907
➡️ Monthly Consistency Score: 0.2993

=== [2572/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.98it/s]
Hypertuning:  74%|███████▍  | 2572/3456 [59:36<22:20,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 1.4376
➡️ Total Profit: ₹44,837.65
➡️ Equity Curve R²: 0.0199
➡️ Monthly Consistency Score: 0.1676

=== [2573/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.15it/s]
Hypertuning:  74%|███████▍  | 2573/3456 [59:37<22:56,  1.56s/it]

➡️ Profit-to-Drawdown Ratio: 0.5599
➡️ Total Profit: ₹19,875.72
➡️ Equity Curve R²: 0.0521
➡️ Monthly Consistency Score: 0.0758

=== [2574/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.10it/s]
Hypertuning:  74%|███████▍  | 2574/3456 [59:39<22:36,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 1.7809
➡️ Total Profit: ₹62,924.94
➡️ Equity Curve R²: 0.0139
➡️ Monthly Consistency Score: 0.2933

=== [2575/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.29it/s]
Hypertuning:  75%|███████▍  | 2575/3456 [59:40<22:14,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 4.0144
➡️ Total Profit: ₹84,672.55
➡️ Equity Curve R²: 0.7816
➡️ Monthly Consistency Score: 0.3388

=== [2576/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.36it/s]
Hypertuning:  75%|███████▍  | 2576/3456 [59:42<22:24,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 9.4759
➡️ Total Profit: ₹100,901.14
➡️ Equity Curve R²: 0.9062
➡️ Monthly Consistency Score: 0.5010

=== [2577/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.17it/s]
Hypertuning:  75%|███████▍  | 2577/3456 [59:43<22:30,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: -0.8140
➡️ Total Profit: ₹-67,326.91
➡️ Equity Curve R²: 0.9544
➡️ Monthly Consistency Score: -0.2959

=== [2578/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)
<ipython-input-10-980624002>:90: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp_data['Signal'] = temp_data['Signal'].astype(int)

100%|██████████| 1/1 [00:00<00:00, 96.63it/s]
Hypertuning:  75%|███████▍  | 2578/3456 [59:45<22:08,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.2584
➡️ Total Profit: ₹-13,395.87
➡️ Equity Curve R²: 0.8495
➡️ Monthly Consistency Score: -0.0560

=== [2579/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.02it/s]
Hypertuning:  75%|███████▍  | 2579/3456 [59:46<22:28,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: -0.0524
➡️ Total Profit: ₹-2,881.92
➡️ Equity Curve R²: 0.5937
➡️ Monthly Consistency Score: -0.0107

=== [2580/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.30it/s]
Hypertuning:  75%|███████▍  | 2580/3456 [59:48<22:12,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 4.0899
➡️ Total Profit: ₹52,269.02
➡️ Equity Curve R²: 0.7686
➡️ Monthly Consistency Score: 0.1974

=== [2581/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 89.97it/s]
Hypertuning:  75%|███████▍  | 2581/3456 [59:50<22:47,  1.56s/it]

➡️ Profit-to-Drawdown Ratio: 0.1391
➡️ Total Profit: ₹5,054.35
➡️ Equity Curve R²: 0.0184
➡️ Monthly Consistency Score: 0.0179

=== [2582/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.85it/s]
Hypertuning:  75%|███████▍  | 2582/3456 [59:51<22:19,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.2326
➡️ Total Profit: ₹-11,378.20
➡️ Equity Curve R²: 0.6477
➡️ Monthly Consistency Score: -0.0430

=== [2583/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 89.81it/s]
Hypertuning:  75%|███████▍  | 2583/3456 [59:53<22:35,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: -0.6260
➡️ Total Profit: ₹-35,048.38
➡️ Equity Curve R²: 0.8928
➡️ Monthly Consistency Score: -0.1393

=== [2584/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.44it/s]
Hypertuning:  75%|███████▍  | 2584/3456 [59:54<22:06,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.5514
➡️ Total Profit: ₹17,942.39
➡️ Equity Curve R²: 0.0511
➡️ Monthly Consistency Score: 0.0651

=== [2585/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.52it/s]
Hypertuning:  75%|███████▍  | 2585/3456 [59:56<22:41,  1.56s/it]

➡️ Profit-to-Drawdown Ratio: -0.0906
➡️ Total Profit: ₹-4,842.57
➡️ Equity Curve R²: 0.6770
➡️ Monthly Consistency Score: -0.0175

=== [2586/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.64it/s]
Hypertuning:  75%|███████▍  | 2586/3456 [59:57<22:11,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.1626
➡️ Total Profit: ₹5,746.97
➡️ Equity Curve R²: 0.4937
➡️ Monthly Consistency Score: 0.0195

=== [2587/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.75it/s]
Hypertuning:  75%|███████▍  | 2587/3456 [59:59<22:31,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: 2.6135
➡️ Total Profit: ₹55,368.53
➡️ Equity Curve R²: 0.3493
➡️ Monthly Consistency Score: 0.2494

=== [2588/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.38it/s]
Hypertuning:  75%|███████▍  | 2588/3456 [1:00:00<22:05,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 3.2782
➡️ Total Profit: ₹76,791.12
➡️ Equity Curve R²: 0.7901
➡️ Monthly Consistency Score: 0.3378

=== [2589/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.92it/s]
Hypertuning:  75%|███████▍  | 2589/3456 [1:00:02<22:35,  1.56s/it]

➡️ Profit-to-Drawdown Ratio: 0.6910
➡️ Total Profit: ₹23,656.66
➡️ Equity Curve R²: 0.0468
➡️ Monthly Consistency Score: 0.0899

=== [2590/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.10it/s]
Hypertuning:  75%|███████▍  | 2590/3456 [1:00:03<22:12,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 1.5251
➡️ Total Profit: ₹53,888.61
➡️ Equity Curve R²: 0.0171
➡️ Monthly Consistency Score: 0.2253

=== [2591/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.54it/s]
Hypertuning:  75%|███████▍  | 2591/3456 [1:00:05<22:22,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: 2.0590
➡️ Total Profit: ₹60,226.65
➡️ Equity Curve R²: 0.3727
➡️ Monthly Consistency Score: 0.2215

=== [2592/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.85it/s]
Hypertuning:  75%|███████▌  | 2592/3456 [1:00:06<21:55,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 5.2454
➡️ Total Profit: ₹67,036.47
➡️ Equity Curve R²: 0.7465
➡️ Monthly Consistency Score: 0.2978

=== [2593/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.32it/s]
Hypertuning:  75%|███████▌  | 2593/3456 [1:00:08<22:22,  1.56s/it]

➡️ Profit-to-Drawdown Ratio: -0.5808
➡️ Total Profit: ₹-32,560.34
➡️ Equity Curve R²: 0.8552
➡️ Monthly Consistency Score: -0.1515

=== [2594/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.86it/s]
Hypertuning:  75%|███████▌  | 2594/3456 [1:00:10<22:00,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.4656
➡️ Total Profit: ₹-17,728.27
➡️ Equity Curve R²: 0.5993
➡️ Monthly Consistency Score: -0.0809

=== [2595/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.42it/s]
Hypertuning:  75%|███████▌  | 2595/3456 [1:00:11<22:15,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: 1.7397
➡️ Total Profit: ₹43,655.33
➡️ Equity Curve R²: 0.4181
➡️ Monthly Consistency Score: 0.1605

=== [2596/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 86.48it/s]
Hypertuning:  75%|███████▌  | 2596/3456 [1:00:13<21:50,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.1658
➡️ Total Profit: ₹5,321.09
➡️ Equity Curve R²: 0.1987
➡️ Monthly Consistency Score: 0.0220

=== [2597/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.92it/s]
Hypertuning:  75%|███████▌  | 2597/3456 [1:00:14<22:23,  1.56s/it]

➡️ Profit-to-Drawdown Ratio: -0.3844
➡️ Total Profit: ₹-10,354.12
➡️ Equity Curve R²: 0.3686
➡️ Monthly Consistency Score: -0.0407

=== [2598/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.03it/s]
Hypertuning:  75%|███████▌  | 2598/3456 [1:00:16<21:57,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 0.1736
➡️ Total Profit: ₹5,153.73
➡️ Equity Curve R²: 0.3013
➡️ Monthly Consistency Score: 0.0192

=== [2599/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.51it/s]
Hypertuning:  75%|███████▌  | 2599/3456 [1:00:17<22:14,  1.56s/it]

➡️ Profit-to-Drawdown Ratio: 2.3833
➡️ Total Profit: ₹43,062.89
➡️ Equity Curve R²: 0.4867
➡️ Monthly Consistency Score: 0.1807

=== [2600/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.09it/s]
Hypertuning:  75%|███████▌  | 2600/3456 [1:00:19<21:50,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.2719
➡️ Total Profit: ₹7,277.40
➡️ Equity Curve R²: 0.0058
➡️ Monthly Consistency Score: 0.0273

=== [2601/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 87.19it/s]
Hypertuning:  75%|███████▌  | 2601/3456 [1:00:20<22:17,  1.56s/it]

➡️ Profit-to-Drawdown Ratio: 1.0438
➡️ Total Profit: ₹28,482.77
➡️ Equity Curve R²: 0.1589
➡️ Monthly Consistency Score: 0.1045

=== [2602/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.95it/s]
Hypertuning:  75%|███████▌  | 2602/3456 [1:00:22<21:57,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 0.5074
➡️ Total Profit: ₹12,526.33
➡️ Equity Curve R²: 0.2435
➡️ Monthly Consistency Score: 0.0514

=== [2603/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.27it/s]
Hypertuning:  75%|███████▌  | 2603/3456 [1:00:24<22:13,  1.56s/it]

➡️ Profit-to-Drawdown Ratio: -0.2369
➡️ Total Profit: ₹-11,591.64
➡️ Equity Curve R²: 0.7112
➡️ Monthly Consistency Score: -0.0454

=== [2604/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 90.47it/s]
Hypertuning:  75%|███████▌  | 2604/3456 [1:00:25<21:45,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 3.1309
➡️ Total Profit: ₹53,350.01
➡️ Equity Curve R²: 0.8359
➡️ Monthly Consistency Score: 0.2178

=== [2605/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 82.09it/s]
Hypertuning:  75%|███████▌  | 2605/3456 [1:00:27<22:19,  1.57s/it]

➡️ Profit-to-Drawdown Ratio: 2.1600
➡️ Total Profit: ₹58,515.83
➡️ Equity Curve R²: 0.5735
➡️ Monthly Consistency Score: 0.2225

=== [2606/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.60it/s]
Hypertuning:  75%|███████▌  | 2606/3456 [1:00:28<21:50,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 1.8194
➡️ Total Profit: ₹63,743.68
➡️ Equity Curve R²: 0.3625
➡️ Monthly Consistency Score: 0.2613

=== [2607/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.92it/s]
Hypertuning:  75%|███████▌  | 2607/3456 [1:00:30<22:11,  1.57s/it]

➡️ Profit-to-Drawdown Ratio: 0.7247
➡️ Total Profit: ₹30,522.69
➡️ Equity Curve R²: 0.1840
➡️ Monthly Consistency Score: 0.1227

=== [2608/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.77it/s]
Hypertuning:  75%|███████▌  | 2608/3456 [1:00:31<21:44,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 0.3997
➡️ Total Profit: ₹18,820.89
➡️ Equity Curve R²: 0.3723
➡️ Monthly Consistency Score: 0.0750

=== [2609/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.86it/s]
Hypertuning:  75%|███████▌  | 2609/3456 [1:00:33<21:34,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.5657
➡️ Total Profit: ₹-30,455.31
➡️ Equity Curve R²: 0.8028
➡️ Monthly Consistency Score: -0.1412

=== [2610/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 90.35it/s]
Hypertuning:  76%|███████▌  | 2610/3456 [1:00:34<21:56,  1.56s/it]

➡️ Profit-to-Drawdown Ratio: -0.3235
➡️ Total Profit: ₹-9,730.11
➡️ Equity Curve R²: 0.5372
➡️ Monthly Consistency Score: -0.0433

=== [2611/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.62it/s]
Hypertuning:  76%|███████▌  | 2611/3456 [1:00:36<21:28,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.9370
➡️ Total Profit: ₹31,016.22
➡️ Equity Curve R²: 0.0004
➡️ Monthly Consistency Score: 0.1178

=== [2612/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 90.50it/s]
Hypertuning:  76%|███████▌  | 2612/3456 [1:00:37<21:44,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: 0.5130
➡️ Total Profit: ₹11,803.87
➡️ Equity Curve R²: 0.5567
➡️ Monthly Consistency Score: 0.0475

=== [2613/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 87.19it/s]
Hypertuning:  76%|███████▌  | 2613/3456 [1:00:39<22:15,  1.58s/it]

➡️ Profit-to-Drawdown Ratio: 0.2020
➡️ Total Profit: ₹5,059.17
➡️ Equity Curve R²: 0.1141
➡️ Monthly Consistency Score: 0.0197

=== [2614/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.06it/s]
Hypertuning:  76%|███████▌  | 2614/3456 [1:00:41<21:49,  1.56s/it]

➡️ Profit-to-Drawdown Ratio: -0.2641
➡️ Total Profit: ₹-12,506.40
➡️ Equity Curve R²: 0.8619
➡️ Monthly Consistency Score: -0.0530

=== [2615/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.85it/s]
Hypertuning:  76%|███████▌  | 2615/3456 [1:00:42<21:21,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 2.5616
➡️ Total Profit: ₹46,282.89
➡️ Equity Curve R²: 0.5684
➡️ Monthly Consistency Score: 0.1963

=== [2616/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 100.41it/s]
Hypertuning:  76%|███████▌  | 2616/3456 [1:00:44<21:31,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 0.2719
➡️ Total Profit: ₹7,277.40
➡️ Equity Curve R²: 0.0058
➡️ Monthly Consistency Score: 0.0273

=== [2617/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.43it/s]
Hypertuning:  76%|███████▌  | 2617/3456 [1:00:45<21:13,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 1.1159
➡️ Total Profit: ₹29,744.65
➡️ Equity Curve R²: 0.2013
➡️ Monthly Consistency Score: 0.1103

=== [2618/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.77it/s]
Hypertuning:  76%|███████▌  | 2618/3456 [1:00:47<21:28,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 0.5074
➡️ Total Profit: ₹12,526.33
➡️ Equity Curve R²: 0.2435
➡️ Monthly Consistency Score: 0.0514

=== [2619/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.16it/s]
Hypertuning:  76%|███████▌  | 2619/3456 [1:00:48<21:50,  1.57s/it]

➡️ Profit-to-Drawdown Ratio: -0.1824
➡️ Total Profit: ₹-8,328.90
➡️ Equity Curve R²: 0.7090
➡️ Monthly Consistency Score: -0.0333

=== [2620/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 101.83it/s]
Hypertuning:  76%|███████▌  | 2620/3456 [1:00:50<21:28,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 3.1311
➡️ Total Profit: ₹53,353.65
➡️ Equity Curve R²: 0.8372
➡️ Monthly Consistency Score: 0.2207

=== [2621/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 89.89it/s]
Hypertuning:  76%|███████▌  | 2621/3456 [1:00:51<21:15,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 2.0642
➡️ Total Profit: ₹58,517.71
➡️ Equity Curve R²: 0.5685
➡️ Monthly Consistency Score: 0.2230

=== [2622/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.59it/s]
Hypertuning:  76%|███████▌  | 2622/3456 [1:00:53<21:37,  1.56s/it]

➡️ Profit-to-Drawdown Ratio: 1.3615
➡️ Total Profit: ₹47,396.43
➡️ Equity Curve R²: 0.0000
➡️ Monthly Consistency Score: 0.1920

=== [2623/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 90.85it/s]
Hypertuning:  76%|███████▌  | 2623/3456 [1:00:54<21:10,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.6008
➡️ Total Profit: ₹27,262.69
➡️ Equity Curve R²: 0.2680
➡️ Monthly Consistency Score: 0.1114

=== [2624/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.05it/s]
Hypertuning:  76%|███████▌  | 2624/3456 [1:00:56<21:18,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 3.9410
➡️ Total Profit: ₹64,901.01
➡️ Equity Curve R²: 0.6259
➡️ Monthly Consistency Score: 0.3064

=== [2625/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.46it/s]
Hypertuning:  76%|███████▌  | 2625/3456 [1:00:58<21:44,  1.57s/it]

➡️ Profit-to-Drawdown Ratio: -0.5259
➡️ Total Profit: ₹-27,861.36
➡️ Equity Curve R²: 0.7158
➡️ Monthly Consistency Score: -0.1279

=== [2626/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.91it/s]
Hypertuning:  76%|███████▌  | 2626/3456 [1:00:59<21:21,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: -0.1536
➡️ Total Profit: ₹-4,166.43
➡️ Equity Curve R²: 0.4674
➡️ Monthly Consistency Score: -0.0194

=== [2627/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.42it/s]
Hypertuning:  76%|███████▌  | 2627/3456 [1:01:00<20:55,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.4058
➡️ Total Profit: ₹46,536.23
➡️ Equity Curve R²: 0.2466
➡️ Monthly Consistency Score: 0.1866

=== [2628/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.17it/s]
Hypertuning:  76%|███████▌  | 2628/3456 [1:01:02<21:15,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 0.6073
➡️ Total Profit: ₹16,158.47
➡️ Equity Curve R²: 0.4734
➡️ Monthly Consistency Score: 0.0703

=== [2629/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.20it/s]
Hypertuning:  76%|███████▌  | 2629/3456 [1:01:04<21:03,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.1702
➡️ Total Profit: ₹5,386.45
➡️ Equity Curve R²: 0.0114
➡️ Monthly Consistency Score: 0.0201

=== [2630/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.01it/s]
Hypertuning:  76%|███████▌  | 2630/3456 [1:01:05<21:15,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: -0.0413
➡️ Total Profit: ₹-1,550.07
➡️ Equity Curve R²: 0.6954
➡️ Monthly Consistency Score: -0.0065

=== [2631/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.58it/s]
Hypertuning:  76%|███████▌  | 2631/3456 [1:01:07<21:35,  1.57s/it]

➡️ Profit-to-Drawdown Ratio: 2.4732
➡️ Total Profit: ₹44,685.59
➡️ Equity Curve R²: 0.5157
➡️ Monthly Consistency Score: 0.1776

=== [2632/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 90.98it/s]
Hypertuning:  76%|███████▌  | 2632/3456 [1:01:08<21:13,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: 0.3396
➡️ Total Profit: ₹9,710.21
➡️ Equity Curve R²: 0.0445
➡️ Monthly Consistency Score: 0.0376

=== [2633/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.19it/s]
Hypertuning:  76%|███████▌  | 2633/3456 [1:01:10<20:59,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.5313
➡️ Total Profit: ₹19,717.90
➡️ Equity Curve R²: 0.2130
➡️ Monthly Consistency Score: 0.0776

=== [2634/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.89it/s]
Hypertuning:  76%|███████▌  | 2634/3456 [1:01:11<21:15,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: 0.5989
➡️ Total Profit: ₹14,786.33
➡️ Equity Curve R²: 0.2830
➡️ Monthly Consistency Score: 0.0606

=== [2635/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.35it/s]
Hypertuning:  76%|███████▌  | 2635/3456 [1:01:13<21:28,  1.57s/it]

➡️ Profit-to-Drawdown Ratio: 0.0456
➡️ Total Profit: ₹2,156.58
➡️ Equity Curve R²: 0.5904
➡️ Monthly Consistency Score: 0.0078

=== [2636/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 88.84it/s]
Hypertuning:  76%|███████▋  | 2636/3456 [1:01:14<21:05,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 3.3813
➡️ Total Profit: ₹57,617.29
➡️ Equity Curve R²: 0.8756
➡️ Monthly Consistency Score: 0.2342

=== [2637/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 90.20it/s]
Hypertuning:  76%|███████▋  | 2637/3456 [1:01:16<20:56,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 1.9593
➡️ Total Profit: ₹55,990.14
➡️ Equity Curve R²: 0.0452
➡️ Monthly Consistency Score: 0.2402

=== [2638/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 90.84it/s]
Hypertuning:  76%|███████▋  | 2638/3456 [1:01:18<21:19,  1.56s/it]

➡️ Profit-to-Drawdown Ratio: 1.3651
➡️ Total Profit: ₹49,366.33
➡️ Equity Curve R²: 0.1491
➡️ Monthly Consistency Score: 0.2032

=== [2639/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.14it/s]
Hypertuning:  76%|███████▋  | 2639/3456 [1:01:19<20:49,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.3494
➡️ Total Profit: ₹15,856.80
➡️ Equity Curve R²: 0.2908
➡️ Monthly Consistency Score: 0.0630

=== [2640/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.41it/s]
Hypertuning:  76%|███████▋  | 2640/3456 [1:01:21<21:02,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: 0.5609
➡️ Total Profit: ₹25,212.71
➡️ Equity Curve R²: 0.2720
➡️ Monthly Consistency Score: 0.0986

=== [2641/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.21it/s]
Hypertuning:  76%|███████▋  | 2641/3456 [1:01:22<20:41,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.5843
➡️ Total Profit: ₹-31,929.87
➡️ Equity Curve R²: 0.8533
➡️ Monthly Consistency Score: -0.1480

=== [2642/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.63it/s]
Hypertuning:  76%|███████▋  | 2642/3456 [1:01:24<21:00,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: -0.5458
➡️ Total Profit: ₹-21,731.87
➡️ Equity Curve R²: 0.6606
➡️ Monthly Consistency Score: -0.0992

=== [2643/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.10it/s]
Hypertuning:  76%|███████▋  | 2643/3456 [1:01:25<21:09,  1.56s/it]

➡️ Profit-to-Drawdown Ratio: 1.6252
➡️ Total Profit: ₹40,782.64
➡️ Equity Curve R²: 0.3965
➡️ Monthly Consistency Score: 0.1506

=== [2644/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.22it/s]
Hypertuning:  77%|███████▋  | 2644/3456 [1:01:27<20:48,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 0.4771
➡️ Total Profit: ₹15,313.81
➡️ Equity Curve R²: 0.4975
➡️ Monthly Consistency Score: 0.0627

=== [2645/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 86.60it/s]
Hypertuning:  77%|███████▋  | 2645/3456 [1:01:28<21:21,  1.58s/it]

➡️ Profit-to-Drawdown Ratio: -0.3844
➡️ Total Profit: ₹-10,354.12
➡️ Equity Curve R²: 0.3316
➡️ Monthly Consistency Score: -0.0408

=== [2646/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.16it/s]
Hypertuning:  77%|███████▋  | 2646/3456 [1:01:30<20:59,  1.56s/it]

➡️ Profit-to-Drawdown Ratio: -0.2378
➡️ Total Profit: ₹-9,108.12
➡️ Equity Curve R²: 0.8178
➡️ Monthly Consistency Score: -0.0357

=== [2647/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 86.41it/s]
Hypertuning:  77%|███████▋  | 2647/3456 [1:01:31<20:31,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 2.2931
➡️ Total Profit: ₹41,431.52
➡️ Equity Curve R²: 0.4603
➡️ Monthly Consistency Score: 0.1739

=== [2648/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.19it/s]
Hypertuning:  77%|███████▋  | 2648/3456 [1:01:33<20:40,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 0.8813
➡️ Total Profit: ₹16,094.75
➡️ Equity Curve R²: 0.2300
➡️ Monthly Consistency Score: 0.0647

=== [2649/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.68it/s]
Hypertuning:  77%|███████▋  | 2649/3456 [1:01:34<20:21,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.0207
➡️ Total Profit: ₹27,852.30
➡️ Equity Curve R²: 0.1572
➡️ Monthly Consistency Score: 0.1024

=== [2650/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.38it/s]
Hypertuning:  77%|███████▋  | 2650/3456 [1:01:36<20:36,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.4616
➡️ Total Profit: ₹11,395.41
➡️ Equity Curve R²: 0.2324
➡️ Monthly Consistency Score: 0.0467

=== [2651/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.57it/s]
Hypertuning:  77%|███████▋  | 2651/3456 [1:01:37<20:09,  1.50s/it]

➡️ Profit-to-Drawdown Ratio: -0.2702
➡️ Total Profit: ₹-13,223.01
➡️ Equity Curve R²: 0.7196
➡️ Monthly Consistency Score: -0.0518

=== [2652/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.30it/s]
Hypertuning:  77%|███████▋  | 2652/3456 [1:01:39<20:35,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 3.0058
➡️ Total Profit: ₹51,218.19
➡️ Equity Curve R²: 0.8193
➡️ Monthly Consistency Score: 0.2087

=== [2653/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.51it/s]
Hypertuning:  77%|███████▋  | 2653/3456 [1:01:41<21:05,  1.58s/it]

➡️ Profit-to-Drawdown Ratio: 2.3719
➡️ Total Profit: ₹59,774.89
➡️ Equity Curve R²: 0.6147
➡️ Monthly Consistency Score: 0.2306

=== [2654/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.14it/s]
Hypertuning:  77%|███████▋  | 2654/3456 [1:01:42<20:45,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: 1.7872
➡️ Total Profit: ₹62,612.76
➡️ Equity Curve R²: 0.3691
➡️ Monthly Consistency Score: 0.2586

=== [2655/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.96it/s]
Hypertuning:  77%|███████▋  | 2655/3456 [1:01:44<20:19,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.6859
➡️ Total Profit: ₹28,891.32
➡️ Equity Curve R²: 0.1760
➡️ Monthly Consistency Score: 0.1176

=== [2656/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 88.60it/s]
Hypertuning:  77%|███████▋  | 2656/3456 [1:01:45<20:29,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 0.9865
➡️ Total Profit: ₹41,465.55
➡️ Equity Curve R²: 0.0000
➡️ Monthly Consistency Score: 0.1676

=== [2657/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.07it/s]
Hypertuning:  77%|███████▋  | 2657/3456 [1:01:47<20:16,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: -0.6468
➡️ Total Profit: ₹-34,858.54
➡️ Equity Curve R²: 0.8491
➡️ Monthly Consistency Score: -0.1728

=== [2658/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.35it/s]
Hypertuning:  77%|███████▋  | 2658/3456 [1:01:48<20:35,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: -0.3790
➡️ Total Profit: ₹-14,862.79
➡️ Equity Curve R²: 0.7330
➡️ Monthly Consistency Score: -0.0669

=== [2659/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.96it/s]
Hypertuning:  77%|███████▋  | 2659/3456 [1:01:50<20:49,  1.57s/it]

➡️ Profit-to-Drawdown Ratio: 1.1198
➡️ Total Profit: ₹33,419.37
➡️ Equity Curve R²: 0.1824
➡️ Monthly Consistency Score: 0.1381

=== [2660/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.56it/s]
Hypertuning:  77%|███████▋  | 2660/3456 [1:01:51<20:27,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 0.6478
➡️ Total Profit: ₹19,577.45
➡️ Equity Curve R²: 0.5694
➡️ Monthly Consistency Score: 0.0847

=== [2661/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 86.41it/s]
Hypertuning:  77%|███████▋  | 2661/3456 [1:01:53<20:52,  1.58s/it]

➡️ Profit-to-Drawdown Ratio: -0.0929
➡️ Total Profit: ₹-2,503.65
➡️ Equity Curve R²: 0.0374
➡️ Monthly Consistency Score: -0.0097

=== [2662/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.90it/s]
Hypertuning:  77%|███████▋  | 2662/3456 [1:01:55<20:31,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: -0.3274
➡️ Total Profit: ₹-14,762.72
➡️ Equity Curve R²: 0.8697
➡️ Monthly Consistency Score: -0.0605

=== [2663/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.31it/s]
Hypertuning:  77%|███████▋  | 2663/3456 [1:01:56<20:00,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 2.3833
➡️ Total Profit: ₹43,062.89
➡️ Equity Curve R²: 0.4867
➡️ Monthly Consistency Score: 0.1807

=== [2664/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.85it/s]
Hypertuning:  77%|███████▋  | 2664/3456 [1:01:58<20:11,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.3516
➡️ Total Profit: ₹9,409.23
➡️ Equity Curve R²: 0.0015
➡️ Monthly Consistency Score: 0.0348

=== [2665/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 93.23it/s]
Hypertuning:  77%|███████▋  | 2665/3456 [1:01:59<19:58,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 0.1390
➡️ Total Profit: ₹5,857.90
➡️ Equity Curve R²: 0.4324
➡️ Monthly Consistency Score: 0.0219

=== [2666/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.15it/s]
Hypertuning:  77%|███████▋  | 2666/3456 [1:02:01<20:17,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 1.1517
➡️ Total Profit: ₹28,433.73
➡️ Equity Curve R²: 0.3979
➡️ Monthly Consistency Score: 0.1129

=== [2667/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.27it/s]
Hypertuning:  77%|███████▋  | 2667/3456 [1:02:02<19:53,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: -0.1195
➡️ Total Profit: ₹-5,068.90
➡️ Equity Curve R²: 0.6669
➡️ Monthly Consistency Score: -0.0200

=== [2668/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.06it/s]
Hypertuning:  77%|███████▋  | 2668/3456 [1:02:04<20:09,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 3.3809
➡️ Total Profit: ₹57,610.01
➡️ Equity Curve R²: 0.8699
➡️ Monthly Consistency Score: 0.2377

=== [2669/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.31it/s]
Hypertuning:  77%|███████▋  | 2669/3456 [1:02:05<19:56,  1.52s/it]

➡️ Profit-to-Drawdown Ratio: 2.2996
➡️ Total Profit: ₹62,296.77
➡️ Equity Curve R²: 0.5976
➡️ Monthly Consistency Score: 0.2369

=== [2670/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.46it/s]
Hypertuning:  77%|███████▋  | 2670/3456 [1:02:07<20:16,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: 1.0458
➡️ Total Profit: ₹36,406.33
➡️ Equity Curve R²: 0.0188
➡️ Monthly Consistency Score: 0.1487

=== [2671/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.98it/s]
Hypertuning:  77%|███████▋  | 2671/3456 [1:02:08<19:45,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 0.7247
➡️ Total Profit: ₹30,522.69
➡️ Equity Curve R²: 0.1840
➡️ Monthly Consistency Score: 0.1227

=== [2672/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.54it/s]
Hypertuning:  77%|███████▋  | 2672/3456 [1:02:10<20:00,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: 0.9866
➡️ Total Profit: ₹41,469.19
➡️ Equity Curve R²: 0.0013
➡️ Monthly Consistency Score: 0.1659

=== [2673/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.86it/s]
Hypertuning:  77%|███████▋  | 2673/3456 [1:02:11<20:24,  1.56s/it]

➡️ Profit-to-Drawdown Ratio: -0.4962
➡️ Total Profit: ₹-26,600.42
➡️ Equity Curve R²: 0.7228
➡️ Monthly Consistency Score: -0.1296

=== [2674/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 94.48it/s]
Hypertuning:  77%|███████▋  | 2674/3456 [1:02:13<20:02,  1.54s/it]

➡️ Profit-to-Drawdown Ratio: 0.6591
➡️ Total Profit: ₹19,731.77
➡️ Equity Curve R²: 0.1027
➡️ Monthly Consistency Score: 0.0806

=== [2675/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 91.24it/s]
Hypertuning:  77%|███████▋  | 2675/3456 [1:02:14<19:40,  1.51s/it]

➡️ Profit-to-Drawdown Ratio: 1.1651
➡️ Total Profit: ₹33,034.79
➡️ Equity Curve R²: 0.2838
➡️ Monthly Consistency Score: 0.1297

=== [2676/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.24it/s]
Hypertuning:  77%|███████▋  | 2676/3456 [1:02:16<19:51,  1.53s/it]

➡️ Profit-to-Drawdown Ratio: -0.2098
➡️ Total Profit: ₹-5,975.28
➡️ Equity Curve R²: 0.0258
➡️ Monthly Consistency Score: -0.0252

=== [2677/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.86it/s]
Hypertuning:  77%|███████▋  | 2677/3456 [1:02:18<20:19,  1.56s/it]

➡️ Profit-to-Drawdown Ratio: 0.2655
➡️ Total Profit: ₹7,901.75
➡️ Equity Curve R²: 0.0522
➡️ Monthly Consistency Score: 0.0300

=== [2678/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.41it/s]
Hypertuning:  77%|███████▋  | 2678/3456 [1:02:19<20:05,  1.55s/it]

➡️ Profit-to-Drawdown Ratio: -0.1069
➡️ Total Profit: ₹-4,579.15
➡️ Equity Curve R²: 0.8221
➡️ Monthly Consistency Score: -0.0193

=== [2679/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.57it/s]
Hypertuning:  78%|███████▊  | 2679/3456 [1:02:20<19:10,  1.48s/it]

➡️ Profit-to-Drawdown Ratio: 0.5491
➡️ Total Profit: ₹15,357.00
➡️ Equity Curve R²: 0.1044
➡️ Monthly Consistency Score: 0.0593

=== [2680/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.21it/s]
Hypertuning:  78%|███████▊  | 2680/3456 [1:02:22<18:46,  1.45s/it]

➡️ Profit-to-Drawdown Ratio: 1.1464
➡️ Total Profit: ₹23,713.85
➡️ Equity Curve R²: 0.4311
➡️ Monthly Consistency Score: 0.0922

=== [2681/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.96it/s]
Hypertuning:  78%|███████▊  | 2681/3456 [1:02:23<18:19,  1.42s/it]

➡️ Profit-to-Drawdown Ratio: 0.6441
➡️ Total Profit: ₹23,497.90
➡️ Equity Curve R²: 0.1443
➡️ Monthly Consistency Score: 0.0946

=== [2682/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 109.22it/s]
Hypertuning:  78%|███████▊  | 2682/3456 [1:02:25<18:11,  1.41s/it]

➡️ Profit-to-Drawdown Ratio: 0.0612
➡️ Total Profit: ₹2,439.13
➡️ Equity Curve R²: 0.0021
➡️ Monthly Consistency Score: 0.0090

=== [2683/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.17it/s]
Hypertuning:  78%|███████▊  | 2683/3456 [1:02:26<18:08,  1.41s/it]

➡️ Profit-to-Drawdown Ratio: -0.6541
➡️ Total Profit: ₹-40,923.42
➡️ Equity Curve R²: 0.9009
➡️ Monthly Consistency Score: -0.1603

=== [2684/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.26it/s]
Hypertuning:  78%|███████▊  | 2684/3456 [1:02:27<17:49,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 3.5062
➡️ Total Profit: ₹59,745.47
➡️ Equity Curve R²: 0.8743
➡️ Monthly Consistency Score: 0.2419

=== [2685/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.02it/s]
Hypertuning:  78%|███████▊  | 2685/3456 [1:02:29<18:03,  1.40s/it]

➡️ Profit-to-Drawdown Ratio: 0.7031
➡️ Total Profit: ₹26,601.46
➡️ Equity Curve R²: 0.3092
➡️ Monthly Consistency Score: 0.1030

=== [2686/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.51it/s]
Hypertuning:  78%|███████▊  | 2686/3456 [1:02:30<17:48,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 1.2713
➡️ Total Profit: ₹45,975.41
➡️ Equity Curve R²: 0.1998
➡️ Monthly Consistency Score: 0.1831

=== [2687/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.27it/s]
Hypertuning:  78%|███████▊  | 2687/3456 [1:02:31<17:30,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.5290
➡️ Total Profit: ₹24,005.43
➡️ Equity Curve R²: 0.3191
➡️ Monthly Consistency Score: 0.0985

=== [2688/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.85it/s]
Hypertuning:  78%|███████▊  | 2688/3456 [1:02:33<17:36,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.5134
➡️ Total Profit: ₹23,080.89
➡️ Equity Curve R²: 0.2604
➡️ Monthly Consistency Score: 0.0890

=== [2689/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.68it/s]
Hypertuning:  78%|███████▊  | 2689/3456 [1:02:34<17:26,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.7522
➡️ Total Profit: ₹-49,568.70
➡️ Equity Curve R²: 0.9460
➡️ Monthly Consistency Score: -0.2372

=== [2690/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.74it/s]
Hypertuning:  78%|███████▊  | 2690/3456 [1:02:36<17:32,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4156
➡️ Total Profit: ₹-19,303.95
➡️ Equity Curve R²: 0.8774
➡️ Monthly Consistency Score: -0.0882

=== [2691/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.08it/s]
Hypertuning:  78%|███████▊  | 2691/3456 [1:02:37<17:13,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1451
➡️ Total Profit: ₹5,238.83
➡️ Equity Curve R²: 0.3080
➡️ Monthly Consistency Score: 0.0214

=== [2692/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.96it/s]
Hypertuning:  78%|███████▊  | 2692/3456 [1:02:38<17:21,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.1241
➡️ Total Profit: ₹25,958.75
➡️ Equity Curve R²: 0.6713
➡️ Monthly Consistency Score: 0.1011

=== [2693/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.56it/s]
Hypertuning:  78%|███████▊  | 2693/3456 [1:02:40<17:39,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 1.6150
➡️ Total Profit: ₹27,575.97
➡️ Equity Curve R²: 0.7598
➡️ Monthly Consistency Score: 0.1108

=== [2694/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.55it/s]
Hypertuning:  78%|███████▊  | 2694/3456 [1:02:41<17:28,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.1212
➡️ Total Profit: ₹-5,011.43
➡️ Equity Curve R²: 0.6113
➡️ Monthly Consistency Score: -0.0183

=== [2695/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.81it/s]
Hypertuning:  78%|███████▊  | 2695/3456 [1:02:42<17:10,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.4482
➡️ Total Profit: ₹33,262.52
➡️ Equity Curve R²: 0.2502
➡️ Monthly Consistency Score: 0.1260

=== [2696/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.12it/s]
Hypertuning:  78%|███████▊  | 2696/3456 [1:02:44<17:24,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.3528
➡️ Total Profit: ₹24,319.37
➡️ Equity Curve R²: 0.4288
➡️ Monthly Consistency Score: 0.0992

=== [2697/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.68it/s]
Hypertuning:  78%|███████▊  | 2697/3456 [1:02:45<17:14,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4580
➡️ Total Profit: ₹17,199.78
➡️ Equity Curve R²: 0.2015
➡️ Monthly Consistency Score: 0.0684

=== [2698/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.67it/s]
Hypertuning:  78%|███████▊  | 2698/3456 [1:02:46<17:24,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.1085
➡️ Total Profit: ₹3,308.49
➡️ Equity Curve R²: 0.4237
➡️ Monthly Consistency Score: 0.0128

=== [2699/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.84it/s]
Hypertuning:  78%|███████▊  | 2699/3456 [1:02:48<17:04,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1441
➡️ Total Profit: ₹-4,366.16
➡️ Equity Curve R²: 0.4430
➡️ Monthly Consistency Score: -0.0168

=== [2700/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.71it/s]
Hypertuning:  78%|███████▊  | 2700/3456 [1:02:49<17:10,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.9439
➡️ Total Profit: ₹45,992.91
➡️ Equity Curve R²: 0.2135
➡️ Monthly Consistency Score: 0.1831

=== [2701/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.71it/s]
Hypertuning:  78%|███████▊  | 2701/3456 [1:02:50<17:00,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.3120
➡️ Total Profit: ₹31,415.90
➡️ Equity Curve R²: 0.0969
➡️ Monthly Consistency Score: 0.1258

=== [2702/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.45it/s]
Hypertuning:  78%|███████▊  | 2702/3456 [1:02:52<17:07,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0404
➡️ Total Profit: ₹2,200.10
➡️ Equity Curve R²: 0.6688
➡️ Monthly Consistency Score: 0.0076

=== [2703/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.61it/s]
Hypertuning:  78%|███████▊  | 2703/3456 [1:02:53<17:17,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.2431
➡️ Total Profit: ₹61,755.08
➡️ Equity Curve R²: 0.3922
➡️ Monthly Consistency Score: 0.2509

=== [2704/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.74it/s]
Hypertuning:  78%|███████▊  | 2704/3456 [1:02:55<17:04,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.6803
➡️ Total Profit: ₹64,904.65
➡️ Equity Curve R²: 0.4186
➡️ Monthly Consistency Score: 0.3041

=== [2705/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.14it/s]
Hypertuning:  78%|███████▊  | 2705/3456 [1:02:56<17:02,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.7440
➡️ Total Profit: ₹-49,353.20
➡️ Equity Curve R²: 0.9524
➡️ Monthly Consistency Score: -0.2297

=== [2706/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.88it/s]
Hypertuning:  78%|███████▊  | 2706/3456 [1:02:57<17:11,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4394
➡️ Total Profit: ₹-22,698.55
➡️ Equity Curve R²: 0.8960
➡️ Monthly Consistency Score: -0.0991

=== [2707/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.25it/s]
Hypertuning:  78%|███████▊  | 2707/3456 [1:02:59<16:53,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1205
➡️ Total Profit: ₹3,555.27
➡️ Equity Curve R²: 0.1874
➡️ Monthly Consistency Score: 0.0148

=== [2708/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.46it/s]
Hypertuning:  78%|███████▊  | 2708/3456 [1:03:00<16:57,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.7161
➡️ Total Profit: ₹15,137.85
➡️ Equity Curve R²: 0.4142
➡️ Monthly Consistency Score: 0.0681

=== [2709/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.71it/s]
Hypertuning:  78%|███████▊  | 2709/3456 [1:03:01<16:50,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.5876
➡️ Total Profit: ₹27,108.20
➡️ Equity Curve R²: 0.7407
➡️ Monthly Consistency Score: 0.1067

=== [2710/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.18it/s]
Hypertuning:  78%|███████▊  | 2710/3456 [1:03:03<17:01,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0363
➡️ Total Profit: ₹-1,622.35
➡️ Equity Curve R²: 0.6517
➡️ Monthly Consistency Score: -0.0061

=== [2711/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.45it/s]
Hypertuning:  78%|███████▊  | 2711/3456 [1:03:04<17:09,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.1442
➡️ Total Profit: ₹29,982.15
➡️ Equity Curve R²: 0.0687
➡️ Monthly Consistency Score: 0.1089

=== [2712/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.91it/s]
Hypertuning:  78%|███████▊  | 2712/3456 [1:03:06<16:53,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.2344
➡️ Total Profit: ₹22,191.19
➡️ Equity Curve R²: 0.4404
➡️ Monthly Consistency Score: 0.0912

=== [2713/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.21it/s]
Hypertuning:  79%|███████▊  | 2713/3456 [1:03:07<16:52,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5764
➡️ Total Profit: ₹21,614.01
➡️ Equity Curve R²: 0.0843
➡️ Monthly Consistency Score: 0.0818

=== [2714/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.04it/s]
Hypertuning:  79%|███████▊  | 2714/3456 [1:03:08<17:08,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 0.1439
➡️ Total Profit: ₹4,350.17
➡️ Equity Curve R²: 0.0065
➡️ Monthly Consistency Score: 0.0183

=== [2715/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.33it/s]
Hypertuning:  79%|███████▊  | 2715/3456 [1:03:10<16:47,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.8107
➡️ Total Profit: ₹17,174.42
➡️ Equity Curve R²: 0.0306
➡️ Monthly Consistency Score: 0.0632

=== [2716/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 129.98it/s]
Hypertuning:  79%|███████▊  | 2716/3456 [1:03:11<16:51,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.7513
➡️ Total Profit: ₹46,003.83
➡️ Equity Curve R²: 0.3383
➡️ Monthly Consistency Score: 0.1840

=== [2717/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.85it/s]
Hypertuning:  79%|███████▊  | 2717/3456 [1:03:12<16:45,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.4554
➡️ Total Profit: ₹33,934.96
➡️ Equity Curve R²: 0.1809
➡️ Monthly Consistency Score: 0.1371

=== [2718/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.31it/s]
Hypertuning:  79%|███████▊  | 2718/3456 [1:03:14<16:54,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2067
➡️ Total Profit: ₹-14,752.66
➡️ Equity Curve R²: 0.8259
➡️ Monthly Consistency Score: -0.0488

=== [2719/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.26it/s]
Hypertuning:  79%|███████▊  | 2719/3456 [1:03:15<16:39,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.3021
➡️ Total Profit: ₹63,380.97
➡️ Equity Curve R²: 0.4275
➡️ Monthly Consistency Score: 0.2499

=== [2720/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.61it/s]
Hypertuning:  79%|███████▊  | 2720/3456 [1:03:16<16:43,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 4.4977
➡️ Total Profit: ₹67,036.47
➡️ Equity Curve R²: 0.6352
➡️ Monthly Consistency Score: 0.3205

=== [2721/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.98it/s]
Hypertuning:  79%|███████▊  | 2721/3456 [1:03:18<17:00,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.7007
➡️ Total Profit: ₹-45,160.11
➡️ Equity Curve R²: 0.9392
➡️ Monthly Consistency Score: -0.2087

=== [2722/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.74it/s]
Hypertuning:  79%|███████▉  | 2722/3456 [1:03:19<16:49,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.1651
➡️ Total Profit: ₹-6,002.31
➡️ Equity Curve R²: 0.6576
➡️ Monthly Consistency Score: -0.0272

=== [2723/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.62it/s]
Hypertuning:  79%|███████▉  | 2723/3456 [1:03:21<16:35,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1937
➡️ Total Profit: ₹-8,240.68
➡️ Equity Curve R²: 0.5132
➡️ Monthly Consistency Score: -0.0325

=== [2724/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.49it/s]
Hypertuning:  79%|███████▉  | 2724/3456 [1:03:22<16:41,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.3254
➡️ Total Profit: ₹21,627.91
➡️ Equity Curve R²: 0.5663
➡️ Monthly Consistency Score: 0.0962

=== [2725/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.33it/s]
Hypertuning:  79%|███████▉  | 2725/3456 [1:03:23<16:35,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.8920
➡️ Total Profit: ₹14,669.02
➡️ Equity Curve R²: 0.4475
➡️ Monthly Consistency Score: 0.0592

=== [2726/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.69it/s]
Hypertuning:  79%|███████▉  | 2726/3456 [1:03:25<16:43,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1651
➡️ Total Profit: ₹-8,751.56
➡️ Equity Curve R²: 0.7499
➡️ Monthly Consistency Score: -0.0361

=== [2727/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.70it/s]
Hypertuning:  79%|███████▉  | 2727/3456 [1:03:26<16:37,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.3926
➡️ Total Profit: ₹36,490.74
➡️ Equity Curve R²: 0.2602
➡️ Monthly Consistency Score: 0.1301

=== [2728/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.34it/s]
Hypertuning:  79%|███████▉  | 2728/3456 [1:03:27<16:45,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.3779
➡️ Total Profit: ₹24,330.29
➡️ Equity Curve R²: 0.4626
➡️ Monthly Consistency Score: 0.1020

=== [2729/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.85it/s]
Hypertuning:  79%|███████▉  | 2729/3456 [1:03:29<16:41,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.5511
➡️ Total Profit: ₹20,347.43
➡️ Equity Curve R²: 0.0579
➡️ Monthly Consistency Score: 0.0879

=== [2730/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.07it/s]
Hypertuning:  79%|███████▉  | 2730/3456 [1:03:30<16:55,  1.40s/it]

➡️ Profit-to-Drawdown Ratio: -0.2504
➡️ Total Profit: ₹-11,289.84
➡️ Equity Curve R²: 0.6788
➡️ Monthly Consistency Score: -0.0393

=== [2731/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.77it/s]
Hypertuning:  79%|███████▉  | 2731/3456 [1:03:32<16:35,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.8945
➡️ Total Profit: ₹24,045.22
➡️ Equity Curve R²: 0.0247
➡️ Monthly Consistency Score: 0.0892

=== [2732/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 129.69it/s]
Hypertuning:  79%|███████▉  | 2732/3456 [1:03:33<16:40,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.6643
➡️ Total Profit: ₹41,747.47
➡️ Equity Curve R²: 0.2316
➡️ Monthly Consistency Score: 0.1635

=== [2733/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.83it/s]
Hypertuning:  79%|███████▉  | 2733/3456 [1:03:34<16:30,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.4125
➡️ Total Profit: ₹32,043.55
➡️ Equity Curve R²: 0.1547
➡️ Monthly Consistency Score: 0.1291

=== [2734/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.85it/s]
Hypertuning:  79%|███████▉  | 2734/3456 [1:03:36<16:34,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.4675
➡️ Total Profit: ₹25,929.19
➡️ Equity Curve R²: 0.3713
➡️ Monthly Consistency Score: 0.0986

=== [2735/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.28it/s]
Hypertuning:  79%|███████▉  | 2735/3456 [1:03:37<16:15,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.2086
➡️ Total Profit: ₹53,606.45
➡️ Equity Curve R²: 0.5698
➡️ Monthly Consistency Score: 0.2142

=== [2736/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.21it/s]
Hypertuning:  79%|███████▉  | 2736/3456 [1:03:38<16:26,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.5924
➡️ Total Profit: ₹62,776.47
➡️ Equity Curve R²: 0.4445
➡️ Monthly Consistency Score: 0.2944

=== [2737/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.48it/s]
Hypertuning:  79%|███████▉  | 2737/3456 [1:03:40<16:18,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.7618
➡️ Total Profit: ₹-50,199.17
➡️ Equity Curve R²: 0.9467
➡️ Monthly Consistency Score: -0.2391

=== [2738/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.29it/s]
Hypertuning:  79%|███████▉  | 2738/3456 [1:03:41<16:23,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4249
➡️ Total Profit: ₹-20,431.19
➡️ Equity Curve R²: 0.8742
➡️ Monthly Consistency Score: -0.0897

=== [2739/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.72it/s]
Hypertuning:  79%|███████▉  | 2739/3456 [1:03:42<16:06,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1107
➡️ Total Profit: ₹3,997.52
➡️ Equity Curve R²: 0.3284
➡️ Monthly Consistency Score: 0.0164

=== [2740/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.48it/s]
Hypertuning:  79%|███████▉  | 2740/3456 [1:03:44<16:14,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.1241
➡️ Total Profit: ₹25,958.75
➡️ Equity Curve R²: 0.6713
➡️ Monthly Consistency Score: 0.1011

=== [2741/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.05it/s]
Hypertuning:  79%|███████▉  | 2741/3456 [1:03:45<16:35,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 1.6150
➡️ Total Profit: ₹27,575.97
➡️ Equity Curve R²: 0.7598
➡️ Monthly Consistency Score: 0.1108

=== [2742/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.14it/s]
Hypertuning:  79%|███████▉  | 2742/3456 [1:03:47<16:19,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1212
➡️ Total Profit: ₹-5,011.43
➡️ Equity Curve R²: 0.6113
➡️ Monthly Consistency Score: -0.0183

=== [2743/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.25it/s]
Hypertuning:  79%|███████▉  | 2743/3456 [1:03:48<16:03,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.4482
➡️ Total Profit: ₹33,262.52
➡️ Equity Curve R²: 0.2502
➡️ Monthly Consistency Score: 0.1260

=== [2744/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.45it/s]
Hypertuning:  79%|███████▉  | 2744/3456 [1:03:49<16:09,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.3528
➡️ Total Profit: ₹24,319.37
➡️ Equity Curve R²: 0.4288
➡️ Monthly Consistency Score: 0.0992

=== [2745/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.34it/s]
Hypertuning:  79%|███████▉  | 2745/3456 [1:03:51<16:02,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4580
➡️ Total Profit: ₹17,199.78
➡️ Equity Curve R²: 0.2015
➡️ Monthly Consistency Score: 0.0684

=== [2746/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.64it/s]
Hypertuning:  79%|███████▉  | 2746/3456 [1:03:52<16:09,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1085
➡️ Total Profit: ₹3,308.49
➡️ Equity Curve R²: 0.4237
➡️ Monthly Consistency Score: 0.0128

=== [2747/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.20it/s]
Hypertuning:  79%|███████▉  | 2747/3456 [1:03:53<15:54,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1441
➡️ Total Profit: ₹-4,366.16
➡️ Equity Curve R²: 0.4430
➡️ Monthly Consistency Score: -0.0168

=== [2748/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.60it/s]
Hypertuning:  80%|███████▉  | 2748/3456 [1:03:55<15:59,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.9439
➡️ Total Profit: ₹45,992.91
➡️ Equity Curve R²: 0.2135
➡️ Monthly Consistency Score: 0.1831

=== [2749/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.35it/s]
Hypertuning:  80%|███████▉  | 2749/3456 [1:03:56<16:17,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.2856
➡️ Total Profit: ₹30,785.43
➡️ Equity Curve R²: 0.0980
➡️ Monthly Consistency Score: 0.1229

=== [2750/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.68it/s]
Hypertuning:  80%|███████▉  | 2750/3456 [1:03:58<16:06,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.0404
➡️ Total Profit: ₹2,200.10
➡️ Equity Curve R²: 0.6688
➡️ Monthly Consistency Score: 0.0076

=== [2751/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.90it/s]
Hypertuning:  80%|███████▉  | 2751/3456 [1:03:59<15:51,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.2431
➡️ Total Profit: ₹61,755.08
➡️ Equity Curve R²: 0.3922
➡️ Monthly Consistency Score: 0.2509

=== [2752/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.31it/s]
Hypertuning:  80%|███████▉  | 2752/3456 [1:04:00<15:59,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.6803
➡️ Total Profit: ₹64,904.65
➡️ Equity Curve R²: 0.4186
➡️ Monthly Consistency Score: 0.3041

=== [2753/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.98it/s]
Hypertuning:  80%|███████▉  | 2753/3456 [1:04:02<15:53,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.7227
➡️ Total Profit: ₹-47,672.87
➡️ Equity Curve R²: 0.9423
➡️ Monthly Consistency Score: -0.2361

=== [2754/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.36it/s]
Hypertuning:  80%|███████▉  | 2754/3456 [1:04:03<16:02,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1853
➡️ Total Profit: ₹-8,089.51
➡️ Equity Curve R²: 0.7311
➡️ Monthly Consistency Score: -0.0347

=== [2755/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.51it/s]
Hypertuning:  80%|███████▉  | 2755/3456 [1:04:04<15:44,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1679
➡️ Total Profit: ₹6,870.20
➡️ Equity Curve R²: 0.3959
➡️ Monthly Consistency Score: 0.0274

=== [2756/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.10it/s]
Hypertuning:  80%|███████▉  | 2756/3456 [1:04:06<15:50,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.4329
➡️ Total Profit: ₹33,089.71
➡️ Equity Curve R²: 0.7420
➡️ Monthly Consistency Score: 0.1320

=== [2757/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.30it/s]
Hypertuning:  80%|███████▉  | 2757/3456 [1:04:07<15:43,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.5105
➡️ Total Profit: ₹8,999.49
➡️ Equity Curve R²: 0.2607
➡️ Monthly Consistency Score: 0.0362

=== [2758/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.10it/s]
Hypertuning:  80%|███████▉  | 2758/3456 [1:04:08<15:53,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1626
➡️ Total Profit: ₹-7,273.28
➡️ Equity Curve R²: 0.6778
➡️ Monthly Consistency Score: -0.0285

=== [2759/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.18it/s]
Hypertuning:  80%|███████▉  | 2759/3456 [1:04:10<16:01,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.3077
➡️ Total Profit: ₹30,002.52
➡️ Equity Curve R²: 0.0656
➡️ Monthly Consistency Score: 0.1116

=== [2760/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.36it/s]
Hypertuning:  80%|███████▉  | 2760/3456 [1:04:11<15:47,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.4714
➡️ Total Profit: ₹26,451.19
➡️ Equity Curve R²: 0.4369
➡️ Monthly Consistency Score: 0.1062

=== [2761/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.39it/s]
Hypertuning:  80%|███████▉  | 2761/3456 [1:04:12<15:38,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4270
➡️ Total Profit: ₹16,573.07
➡️ Equity Curve R²: 0.2631
➡️ Monthly Consistency Score: 0.0632

=== [2762/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.99it/s]
Hypertuning:  80%|███████▉  | 2762/3456 [1:04:14<15:46,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0218
➡️ Total Profit: ₹-1,033.36
➡️ Equity Curve R²: 0.5984
➡️ Monthly Consistency Score: -0.0035

=== [2763/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.15it/s]
Hypertuning:  80%|███████▉  | 2763/3456 [1:04:15<15:55,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.1441
➡️ Total Profit: ₹-4,366.16
➡️ Equity Curve R²: 0.4430
➡️ Monthly Consistency Score: -0.0168

=== [2764/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.48it/s]
Hypertuning:  80%|███████▉  | 2764/3456 [1:04:17<15:41,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.5536
➡️ Total Profit: ₹50,735.73
➡️ Equity Curve R²: 0.3829
➡️ Monthly Consistency Score: 0.2101

=== [2765/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.66it/s]
Hypertuning:  80%|████████  | 2765/3456 [1:04:18<15:32,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.4284
➡️ Total Profit: ₹33,305.43
➡️ Equity Curve R²: 0.1395
➡️ Monthly Consistency Score: 0.1348

=== [2766/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.70it/s]
Hypertuning:  80%|████████  | 2766/3456 [1:04:19<15:41,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1497
➡️ Total Profit: ₹8,980.11
➡️ Equity Curve R²: 0.5647
➡️ Monthly Consistency Score: 0.0314

=== [2767/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.55it/s]
Hypertuning:  80%|████████  | 2767/3456 [1:04:21<15:25,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.1838
➡️ Total Profit: ₹60,123.71
➡️ Equity Curve R²: 0.3881
➡️ Monthly Consistency Score: 0.2413

=== [2768/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.13it/s]
Hypertuning:  80%|████████  | 2768/3456 [1:04:22<15:34,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.5924
➡️ Total Profit: ₹62,776.47
➡️ Equity Curve R²: 0.4445
➡️ Monthly Consistency Score: 0.2944

=== [2769/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.60it/s]
Hypertuning:  80%|████████  | 2769/3456 [1:04:23<15:30,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6857
➡️ Total Profit: ₹-43,265.88
➡️ Equity Curve R²: 0.9365
➡️ Monthly Consistency Score: -0.2124

=== [2770/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.29it/s]
Hypertuning:  80%|████████  | 2770/3456 [1:04:25<15:37,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4047
➡️ Total Profit: ₹-19,571.19
➡️ Equity Curve R²: 0.8818
➡️ Monthly Consistency Score: -0.0845

=== [2771/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.45it/s]
Hypertuning:  80%|████████  | 2771/3456 [1:04:26<15:44,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.2258
➡️ Total Profit: ₹8,122.59
➡️ Equity Curve R²: 0.0902
➡️ Monthly Consistency Score: 0.0287

=== [2772/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.61it/s]
Hypertuning:  80%|████████  | 2772/3456 [1:04:27<15:30,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.6319
➡️ Total Profit: ₹44,405.99
➡️ Equity Curve R²: 0.8788
➡️ Monthly Consistency Score: 0.1923

=== [2773/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.98it/s]
Hypertuning:  80%|████████  | 2773/3456 [1:04:29<15:46,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 0.7572
➡️ Total Profit: ₹14,492.66
➡️ Equity Curve R²: 0.4465
➡️ Monthly Consistency Score: 0.0571

=== [2774/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.66it/s]
Hypertuning:  80%|████████  | 2774/3456 [1:04:30<15:34,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1516
➡️ Total Profit: ₹-6,835.24
➡️ Equity Curve R²: 0.7933
➡️ Monthly Consistency Score: -0.0278

=== [2775/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.58it/s]
Hypertuning:  80%|████████  | 2775/3456 [1:04:32<15:18,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.5967
➡️ Total Profit: ₹-28,570.38
➡️ Equity Curve R²: 0.8632
➡️ Monthly Consistency Score: -0.1099

=== [2776/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.79it/s]
Hypertuning:  80%|████████  | 2776/3456 [1:04:33<15:24,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.4124
➡️ Total Profit: ₹24,939.45
➡️ Equity Curve R²: 0.4801
➡️ Monthly Consistency Score: 0.0998

=== [2777/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.41it/s]
Hypertuning:  80%|████████  | 2777/3456 [1:04:34<15:26,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1405
➡️ Total Profit: ₹5,915.85
➡️ Equity Curve R²: 0.3357
➡️ Monthly Consistency Score: 0.0232

=== [2778/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.42it/s]
Hypertuning:  80%|████████  | 2778/3456 [1:04:36<15:37,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.5839
➡️ Total Profit: ₹15,835.69
➡️ Equity Curve R²: 0.3853
➡️ Monthly Consistency Score: 0.0600

=== [2779/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.74it/s]
Hypertuning:  80%|████████  | 2779/3456 [1:04:37<15:18,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.1789
➡️ Total Profit: ₹24,976.59
➡️ Equity Curve R²: 0.1295
➡️ Monthly Consistency Score: 0.1000

=== [2780/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.17it/s]
Hypertuning:  80%|████████  | 2780/3456 [1:04:38<15:22,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 4.8027
➡️ Total Profit: ₹61,396.47
➡️ Equity Curve R²: 0.8819
➡️ Monthly Consistency Score: 0.2561

=== [2781/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.86it/s]
Hypertuning:  80%|████████  | 2781/3456 [1:04:40<15:16,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.7090
➡️ Total Profit: ₹23,228.25
➡️ Equity Curve R²: 0.0684
➡️ Monthly Consistency Score: 0.0923

=== [2782/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.29it/s]
Hypertuning:  80%|████████  | 2782/3456 [1:04:41<15:24,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.1718
➡️ Total Profit: ₹10,111.03
➡️ Equity Curve R²: 0.6136
➡️ Monthly Consistency Score: 0.0342

=== [2783/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.03it/s]
Hypertuning:  81%|████████  | 2783/3456 [1:04:43<15:31,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.4143
➡️ Total Profit: ₹38,937.82
➡️ Equity Curve R²: 0.2672
➡️ Monthly Consistency Score: 0.1501

=== [2784/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.73it/s]
Hypertuning:  81%|████████  | 2784/3456 [1:04:44<15:17,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.5924
➡️ Total Profit: ₹62,776.47
➡️ Equity Curve R²: 0.4445
➡️ Monthly Consistency Score: 0.2944

=== [2785/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.79it/s]
Hypertuning:  81%|████████  | 2785/3456 [1:04:45<15:12,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4325
➡️ Total Profit: ₹-23,047.17
➡️ Equity Curve R²: 0.8633
➡️ Monthly Consistency Score: -0.1102

=== [2786/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.73it/s]
Hypertuning:  81%|████████  | 2786/3456 [1:04:47<15:21,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1904
➡️ Total Profit: ₹-7,054.23
➡️ Equity Curve R²: 0.8539
➡️ Monthly Consistency Score: -0.0322

=== [2787/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.30it/s]
Hypertuning:  81%|████████  | 2787/3456 [1:04:48<15:05,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4717
➡️ Total Profit: ₹15,428.31
➡️ Equity Curve R²: 0.0196
➡️ Monthly Consistency Score: 0.0581

=== [2788/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.33it/s]
Hypertuning:  81%|████████  | 2788/3456 [1:04:49<15:10,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.8046
➡️ Total Profit: ₹21,706.23
➡️ Equity Curve R²: 0.0108
➡️ Monthly Consistency Score: 0.0901

=== [2789/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.94it/s]
Hypertuning:  81%|████████  | 2789/3456 [1:04:51<15:03,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3711
➡️ Total Profit: ₹-12,418.69
➡️ Equity Curve R²: 0.5809
➡️ Monthly Consistency Score: -0.0458

=== [2790/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.76it/s]
Hypertuning:  81%|████████  | 2790/3456 [1:04:52<15:14,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3291
➡️ Total Profit: ₹-18,927.52
➡️ Equity Curve R²: 0.8554
➡️ Monthly Consistency Score: -0.0696

=== [2791/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.14it/s]
Hypertuning:  81%|████████  | 2791/3456 [1:04:53<15:00,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.0210
➡️ Total Profit: ₹724.14
➡️ Equity Curve R²: 0.1421
➡️ Monthly Consistency Score: 0.0027

=== [2792/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.27it/s]
Hypertuning:  81%|████████  | 2792/3456 [1:04:55<15:06,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2301
➡️ Total Profit: ₹-8,540.56
➡️ Equity Curve R²: 0.5886
➡️ Monthly Consistency Score: -0.0337

=== [2793/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.39it/s]
Hypertuning:  81%|████████  | 2793/3456 [1:04:56<14:58,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0358
➡️ Total Profit: ₹-1,579.62
➡️ Equity Curve R²: 0.6438
➡️ Monthly Consistency Score: -0.0057

=== [2794/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 110.70it/s]
Hypertuning:  81%|████████  | 2794/3456 [1:04:58<15:07,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.6234
➡️ Total Profit: ₹18,094.17
➡️ Equity Curve R²: 0.0191
➡️ Monthly Consistency Score: 0.0691

=== [2795/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.99it/s]
Hypertuning:  81%|████████  | 2795/3456 [1:04:59<14:52,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.1029
➡️ Total Profit: ₹26,957.16
➡️ Equity Curve R²: 0.1294
➡️ Monthly Consistency Score: 0.1078

=== [2796/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.11it/s]
Hypertuning:  81%|████████  | 2796/3456 [1:05:00<14:59,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.3082
➡️ Total Profit: ₹16,185.83
➡️ Equity Curve R²: 0.2745
➡️ Monthly Consistency Score: 0.0547

=== [2797/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 129.10it/s]
Hypertuning:  81%|████████  | 2797/3456 [1:05:02<14:53,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.7145
➡️ Total Profit: ₹24,911.96
➡️ Equity Curve R²: 0.0509
➡️ Monthly Consistency Score: 0.0972

=== [2798/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.30it/s]
Hypertuning:  81%|████████  | 2798/3456 [1:05:03<15:00,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.5449
➡️ Total Profit: ₹74,750.34
➡️ Equity Curve R²: 0.3701
➡️ Monthly Consistency Score: 0.3428

=== [2799/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.91it/s]
Hypertuning:  81%|████████  | 2799/3456 [1:05:04<14:46,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.6226
➡️ Total Profit: ₹87,924.33
➡️ Equity Curve R²: 0.4702
➡️ Monthly Consistency Score: 0.3692

=== [2800/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.46it/s]
Hypertuning:  81%|████████  | 2800/3456 [1:05:06<14:55,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.5592
➡️ Total Profit: ₹60,648.29
➡️ Equity Curve R²: 0.5824
➡️ Monthly Consistency Score: 0.2690

=== [2801/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.76it/s]
Hypertuning:  81%|████████  | 2801/3456 [1:05:07<14:48,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.5379
➡️ Total Profit: ₹-28,851.34
➡️ Equity Curve R²: 0.9094
➡️ Monthly Consistency Score: -0.1332

=== [2802/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.04it/s]
Hypertuning:  81%|████████  | 2802/3456 [1:05:08<14:55,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1687
➡️ Total Profit: ₹-6,443.39
➡️ Equity Curve R²: 0.8530
➡️ Monthly Consistency Score: -0.0292

=== [2803/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.39it/s]
Hypertuning:  81%|████████  | 2803/3456 [1:05:10<15:02,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.2434
➡️ Total Profit: ₹8,913.67
➡️ Equity Curve R²: 0.0678
➡️ Monthly Consistency Score: 0.0358

=== [2804/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.83it/s]
Hypertuning:  81%|████████  | 2804/3456 [1:05:11<14:49,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.9880
➡️ Total Profit: ₹21,713.51
➡️ Equity Curve R²: 0.1600
➡️ Monthly Consistency Score: 0.0953

=== [2805/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.34it/s]
Hypertuning:  81%|████████  | 2805/3456 [1:05:13<15:07,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.3269
➡️ Total Profit: ₹-10,528.22
➡️ Equity Curve R²: 0.5220
➡️ Monthly Consistency Score: -0.0386

=== [2806/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.44it/s]
Hypertuning:  81%|████████  | 2806/3456 [1:05:14<14:57,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.3557
➡️ Total Profit: ₹-20,058.44
➡️ Equity Curve R²: 0.8473
➡️ Monthly Consistency Score: -0.0735

=== [2807/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.74it/s]
Hypertuning:  81%|████████  | 2807/3456 [1:05:15<14:42,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3933
➡️ Total Profit: ₹-18,790.38
➡️ Equity Curve R²: 0.8504
➡️ Monthly Consistency Score: -0.0744

=== [2808/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.02it/s]
Hypertuning:  81%|████████▏ | 2808/3456 [1:05:17<14:48,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0250
➡️ Total Profit: ₹-928.74
➡️ Equity Curve R²: 0.3467
➡️ Monthly Consistency Score: -0.0036

=== [2809/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.69it/s]
Hypertuning:  81%|████████▏ | 2809/3456 [1:05:18<14:43,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0774
➡️ Total Profit: ₹-3,467.27
➡️ Equity Curve R²: 0.6677
➡️ Monthly Consistency Score: -0.0125

=== [2810/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.78it/s]
Hypertuning:  81%|████████▏ | 2810/3456 [1:05:19<14:50,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.6976
➡️ Total Profit: ₹19,223.25
➡️ Equity Curve R²: 0.0007
➡️ Monthly Consistency Score: 0.0727

=== [2811/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.99it/s]
Hypertuning:  81%|████████▏ | 2811/3456 [1:05:21<14:35,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.1696
➡️ Total Profit: ₹28,588.53
➡️ Equity Curve R²: 0.1376
➡️ Monthly Consistency Score: 0.1148

=== [2812/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.46it/s]
Hypertuning:  81%|████████▏ | 2812/3456 [1:05:22<14:41,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.2677
➡️ Total Profit: ₹14,057.65
➡️ Equity Curve R²: 0.2675
➡️ Monthly Consistency Score: 0.0480

=== [2813/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.81it/s]
Hypertuning:  81%|████████▏ | 2813/3456 [1:05:23<14:37,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.6373
➡️ Total Profit: ₹23,023.37
➡️ Equity Curve R²: 0.0975
➡️ Monthly Consistency Score: 0.0890

=== [2814/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.34it/s]
Hypertuning:  81%|████████▏ | 2814/3456 [1:05:25<14:48,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.2815
➡️ Total Profit: ₹74,748.50
➡️ Equity Curve R²: 0.3094
➡️ Monthly Consistency Score: 0.3302

=== [2815/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.18it/s]
Hypertuning:  81%|████████▏ | 2815/3456 [1:05:26<14:33,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 5.6711
➡️ Total Profit: ₹110,927.07
➡️ Equity Curve R²: 0.8082
➡️ Monthly Consistency Score: 0.4461

=== [2816/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.37it/s]
Hypertuning:  81%|████████▏ | 2816/3456 [1:05:28<14:36,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.5592
➡️ Total Profit: ₹60,648.29
➡️ Equity Curve R²: 0.5824
➡️ Monthly Consistency Score: 0.2690

=== [2817/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.73it/s]
Hypertuning:  82%|████████▏ | 2817/3456 [1:05:29<14:50,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.5161
➡️ Total Profit: ₹-23,461.48
➡️ Equity Curve R²: 0.9002
➡️ Monthly Consistency Score: -0.1118

=== [2818/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.16it/s]
Hypertuning:  82%|████████▏ | 2818/3456 [1:05:30<14:39,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.3415
➡️ Total Profit: ₹9,296.57
➡️ Equity Curve R²: 0.4914
➡️ Monthly Consistency Score: 0.0418

=== [2819/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.93it/s]
Hypertuning:  82%|████████▏ | 2819/3456 [1:05:32<14:24,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0764
➡️ Total Profit: ₹2,393.67
➡️ Equity Curve R²: 0.0350
➡️ Monthly Consistency Score: 0.0090

=== [2820/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.14it/s]
Hypertuning:  82%|████████▏ | 2820/3456 [1:05:33<14:32,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.6792
➡️ Total Profit: ₹18,190.73
➡️ Equity Curve R²: 0.1289
➡️ Monthly Consistency Score: 0.0732

=== [2821/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.51it/s]
Hypertuning:  82%|████████▏ | 2821/3456 [1:05:34<14:27,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0532
➡️ Total Profit: ₹-1,712.92
➡️ Equity Curve R²: 0.3359
➡️ Monthly Consistency Score: -0.0064

=== [2822/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 131.12it/s]
Hypertuning:  82%|████████▏ | 2822/3456 [1:05:36<14:37,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.3107
➡️ Total Profit: ₹-18,925.68
➡️ Equity Curve R²: 0.8759
➡️ Monthly Consistency Score: -0.0708

=== [2823/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.70it/s]
Hypertuning:  82%|████████▏ | 2823/3456 [1:05:37<14:25,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.0212
➡️ Total Profit: ₹729.62
➡️ Equity Curve R²: 0.1025
➡️ Monthly Consistency Score: 0.0027

=== [2824/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.18it/s]
Hypertuning:  82%|████████▏ | 2824/3456 [1:05:39<14:32,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.0637
➡️ Total Profit: ₹2,423.08
➡️ Equity Curve R²: 0.3356
➡️ Monthly Consistency Score: 0.0089

=== [2825/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.64it/s]
Hypertuning:  82%|████████▏ | 2825/3456 [1:05:40<14:25,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.3177
➡️ Total Profit: ₹12,788.03
➡️ Equity Curve R²: 0.3586
➡️ Monthly Consistency Score: 0.0511

=== [2826/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.52it/s]
Hypertuning:  82%|████████▏ | 2826/3456 [1:05:41<14:35,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.0271
➡️ Total Profit: ₹-1,113.08
➡️ Equity Curve R²: 0.5453
➡️ Monthly Consistency Score: -0.0041

=== [2827/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.38it/s]
Hypertuning:  82%|████████▏ | 2827/3456 [1:05:43<14:21,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1030
➡️ Total Profit: ₹26,959.90
➡️ Equity Curve R²: 0.1201
➡️ Monthly Consistency Score: 0.1084

=== [2828/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.99it/s]
Hypertuning:  82%|████████▏ | 2828/3456 [1:05:44<14:28,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.4518
➡️ Total Profit: ₹35,355.65
➡️ Equity Curve R²: 0.3125
➡️ Monthly Consistency Score: 0.1394

=== [2829/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.20it/s]
Hypertuning:  82%|████████▏ | 2829/3456 [1:05:45<14:23,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.7017
➡️ Total Profit: ₹24,910.08
➡️ Equity Curve R²: 0.0626
➡️ Monthly Consistency Score: 0.0972

=== [2830/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.97it/s]
Hypertuning:  82%|████████▏ | 2830/3456 [1:05:47<14:32,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 1.4467
➡️ Total Profit: ₹52,752.17
➡️ Equity Curve R²: 0.0089
➡️ Monthly Consistency Score: 0.2526

=== [2831/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.66it/s]
Hypertuning:  82%|████████▏ | 2831/3456 [1:05:48<14:21,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 5.5046
➡️ Total Profit: ₹107,669.81
➡️ Equity Curve R²: 0.8108
➡️ Monthly Consistency Score: 0.4404

=== [2832/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.31it/s]
Hypertuning:  82%|████████▏ | 2832/3456 [1:05:50<14:10,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.9339
➡️ Total Profit: ₹67,032.83
➡️ Equity Curve R²: 0.7263
➡️ Monthly Consistency Score: 0.3144

=== [2833/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.90it/s]
Hypertuning:  82%|████████▏ | 2833/3456 [1:05:51<14:18,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.4257
➡️ Total Profit: ₹-22,417.64
➡️ Equity Curve R²: 0.8629
➡️ Monthly Consistency Score: -0.1077

=== [2834/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.89it/s]
Hypertuning:  82%|████████▏ | 2834/3456 [1:05:52<14:27,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.2318
➡️ Total Profit: ₹-9,314.23
➡️ Equity Curve R²: 0.8697
➡️ Monthly Consistency Score: -0.0417

=== [2835/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.80it/s]
Hypertuning:  82%|████████▏ | 2835/3456 [1:05:54<14:11,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.4717
➡️ Total Profit: ₹15,428.31
➡️ Equity Curve R²: 0.0196
➡️ Monthly Consistency Score: 0.0581

=== [2836/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.38it/s]
Hypertuning:  82%|████████▏ | 2836/3456 [1:05:55<14:17,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.8046
➡️ Total Profit: ₹21,706.23
➡️ Equity Curve R²: 0.0108
➡️ Monthly Consistency Score: 0.0901

=== [2837/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.88it/s]
Hypertuning:  82%|████████▏ | 2837/3456 [1:05:57<14:09,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4463
➡️ Total Profit: ₹-14,936.81
➡️ Equity Curve R²: 0.6498
➡️ Monthly Consistency Score: -0.0548

=== [2838/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.01it/s]
Hypertuning:  82%|████████▏ | 2838/3456 [1:05:58<13:56,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3291
➡️ Total Profit: ₹-18,927.52
➡️ Equity Curve R²: 0.8554
➡️ Monthly Consistency Score: -0.0696

=== [2839/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.86it/s]
Hypertuning:  82%|████████▏ | 2839/3456 [1:05:59<14:00,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0210
➡️ Total Profit: ₹724.14
➡️ Equity Curve R²: 0.1421
➡️ Monthly Consistency Score: 0.0027

=== [2840/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.35it/s]
Hypertuning:  82%|████████▏ | 2840/3456 [1:06:01<13:48,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2301
➡️ Total Profit: ₹-8,540.56
➡️ Equity Curve R²: 0.5886
➡️ Monthly Consistency Score: -0.0337

=== [2841/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.44it/s]
Hypertuning:  82%|████████▏ | 2841/3456 [1:06:02<14:03,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0878
➡️ Total Profit: ₹-4,097.74
➡️ Equity Curve R²: 0.6654
➡️ Monthly Consistency Score: -0.0147

=== [2842/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.05it/s]
Hypertuning:  82%|████████▏ | 2842/3456 [1:06:03<14:12,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 0.6234
➡️ Total Profit: ₹18,094.17
➡️ Equity Curve R²: 0.0191
➡️ Monthly Consistency Score: 0.0691

=== [2843/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.30it/s]
Hypertuning:  82%|████████▏ | 2843/3456 [1:06:05<13:57,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1029
➡️ Total Profit: ₹26,957.16
➡️ Equity Curve R²: 0.1294
➡️ Monthly Consistency Score: 0.1078

=== [2844/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.93it/s]
Hypertuning:  82%|████████▏ | 2844/3456 [1:06:06<13:45,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3082
➡️ Total Profit: ₹16,185.83
➡️ Equity Curve R²: 0.2745
➡️ Monthly Consistency Score: 0.0547

=== [2845/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.39it/s]
Hypertuning:  82%|████████▏ | 2845/3456 [1:06:07<13:55,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.7145
➡️ Total Profit: ₹24,911.96
➡️ Equity Curve R²: 0.0509
➡️ Monthly Consistency Score: 0.0972

=== [2846/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.43it/s]
Hypertuning:  82%|████████▏ | 2846/3456 [1:06:09<13:47,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.5449
➡️ Total Profit: ₹74,750.34
➡️ Equity Curve R²: 0.3701
➡️ Monthly Consistency Score: 0.3428

=== [2847/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.79it/s]
Hypertuning:  82%|████████▏ | 2847/3456 [1:06:10<13:53,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.6226
➡️ Total Profit: ₹87,924.33
➡️ Equity Curve R²: 0.4702
➡️ Monthly Consistency Score: 0.3692

=== [2848/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.19it/s]
Hypertuning:  82%|████████▏ | 2848/3456 [1:06:11<13:42,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.5592
➡️ Total Profit: ₹60,648.29
➡️ Equity Curve R²: 0.5824
➡️ Monthly Consistency Score: 0.2690

=== [2849/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.03it/s]
Hypertuning:  82%|████████▏ | 2849/3456 [1:06:13<13:54,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.5849
➡️ Total Profit: ₹-31,995.51
➡️ Equity Curve R²: 0.9015
➡️ Monthly Consistency Score: -0.1570

=== [2850/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.37it/s]
Hypertuning:  82%|████████▏ | 2850/3456 [1:06:14<13:49,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.2583
➡️ Total Profit: ₹7,032.89
➡️ Equity Curve R²: 0.5500
➡️ Monthly Consistency Score: 0.0314

=== [2851/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.19it/s]
Hypertuning:  82%|████████▏ | 2851/3456 [1:06:16<13:51,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.4790
➡️ Total Profit: ₹16,666.88
➡️ Equity Curve R²: 0.0172
➡️ Monthly Consistency Score: 0.0640

=== [2852/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.54it/s]
Hypertuning:  83%|████████▎ | 2852/3456 [1:06:17<13:37,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.8321
➡️ Total Profit: ₹22,449.01
➡️ Equity Curve R²: 0.0802
➡️ Monthly Consistency Score: 0.0928

=== [2853/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.81it/s]
Hypertuning:  83%|████████▎ | 2853/3456 [1:06:18<13:48,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1864
➡️ Total Profit: ₹-6,120.57
➡️ Equity Curve R²: 0.3871
➡️ Monthly Consistency Score: -0.0228

=== [2854/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.84it/s]
Hypertuning:  83%|████████▎ | 2854/3456 [1:06:20<13:36,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3478
➡️ Total Profit: ₹-21,187.52
➡️ Equity Curve R²: 0.8734
➡️ Monthly Consistency Score: -0.0803

=== [2855/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.73it/s]
Hypertuning:  83%|████████▎ | 2855/3456 [1:06:21<13:40,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4134
➡️ Total Profit: ₹-20,421.75
➡️ Equity Curve R²: 0.8575
➡️ Monthly Consistency Score: -0.0806

=== [2856/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.15it/s]
Hypertuning:  83%|████████▎ | 2856/3456 [1:06:22<13:47,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.2301
➡️ Total Profit: ₹-8,540.56
➡️ Equity Curve R²: 0.5570
➡️ Monthly Consistency Score: -0.0344

=== [2857/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.06it/s]
Hypertuning:  83%|████████▎ | 2857/3456 [1:06:24<13:42,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.2358
➡️ Total Profit: ₹9,641.32
➡️ Equity Curve R²: 0.5361
➡️ Monthly Consistency Score: 0.0354

=== [2858/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.73it/s]
Hypertuning:  83%|████████▎ | 2858/3456 [1:06:25<13:33,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.9659
➡️ Total Profit: ₹21,666.93
➡️ Equity Curve R²: 0.0640
➡️ Monthly Consistency Score: 0.0791

=== [2859/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.18it/s]
Hypertuning:  83%|████████▎ | 2859/3456 [1:06:27<13:38,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1029
➡️ Total Profit: ₹26,957.16
➡️ Equity Curve R²: 0.1294
➡️ Monthly Consistency Score: 0.1078

=== [2860/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.67it/s]
Hypertuning:  83%|████████▎ | 2860/3456 [1:06:28<13:24,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2677
➡️ Total Profit: ₹14,057.65
➡️ Equity Curve R²: 0.2675
➡️ Monthly Consistency Score: 0.0480

=== [2861/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.15it/s]
Hypertuning:  83%|████████▎ | 2861/3456 [1:06:29<13:35,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.6373
➡️ Total Profit: ₹23,023.37
➡️ Equity Curve R²: 0.1283
➡️ Monthly Consistency Score: 0.0890

=== [2862/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.15it/s]
Hypertuning:  83%|████████▎ | 2862/3456 [1:06:31<13:26,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.3914
➡️ Total Profit: ₹53,881.25
➡️ Equity Curve R²: 0.0100
➡️ Monthly Consistency Score: 0.2531

=== [2863/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.97it/s]
Hypertuning:  83%|████████▎ | 2863/3456 [1:06:32<13:29,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 5.6711
➡️ Total Profit: ₹110,927.07
➡️ Equity Curve R²: 0.8082
➡️ Monthly Consistency Score: 0.4461

=== [2864/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.89it/s]
Hypertuning:  83%|████████▎ | 2864/3456 [1:06:33<13:17,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 3.5592
➡️ Total Profit: ₹60,648.29
➡️ Equity Curve R²: 0.5824
➡️ Monthly Consistency Score: 0.2690

=== [2865/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.18it/s]
Hypertuning:  83%|████████▎ | 2865/3456 [1:06:35<13:29,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.6884
➡️ Total Profit: ₹-37,664.76
➡️ Equity Curve R²: 0.9354
➡️ Monthly Consistency Score: -0.1892

=== [2866/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.89it/s]
Hypertuning:  83%|████████▎ | 2866/3456 [1:06:36<13:38,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.0246
➡️ Total Profit: ₹-868.83
➡️ Equity Curve R²: 0.7650
➡️ Monthly Consistency Score: -0.0040

=== [2867/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.50it/s]
Hypertuning:  83%|████████▎ | 2867/3456 [1:06:37<13:27,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1653
➡️ Total Profit: ₹-5,752.22
➡️ Equity Curve R²: 0.3749
➡️ Monthly Consistency Score: -0.0208

=== [2868/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.34it/s]
Hypertuning:  83%|████████▎ | 2868/3456 [1:06:39<13:18,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5965
➡️ Total Profit: ₹15,975.23
➡️ Equity Curve R²: 0.0548
➡️ Monthly Consistency Score: 0.0685

=== [2869/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.53it/s]
Hypertuning:  83%|████████▎ | 2869/3456 [1:06:40<13:28,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.0057
➡️ Total Profit: ₹179.43
➡️ Equity Curve R²: 0.2249
➡️ Monthly Consistency Score: 0.0007

=== [2870/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.19it/s]
Hypertuning:  83%|████████▎ | 2870/3456 [1:06:42<13:37,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.3532
➡️ Total Profit: ₹-21,111.08
➡️ Equity Curve R²: 0.8867
➡️ Monthly Consistency Score: -0.0789

=== [2871/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.37it/s]
Hypertuning:  83%|████████▎ | 2871/3456 [1:06:43<13:25,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.6027
➡️ Total Profit: ₹-31,768.01
➡️ Equity Curve R²: 0.8794
➡️ Monthly Consistency Score: -0.1311

=== [2872/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.42it/s]
Hypertuning:  83%|████████▎ | 2872/3456 [1:06:44<13:12,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1848
➡️ Total Profit: ₹6,072.24
➡️ Equity Curve R²: 0.1346
➡️ Monthly Consistency Score: 0.0229

=== [2873/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.70it/s]
Hypertuning:  83%|████████▎ | 2873/3456 [1:06:46<13:22,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.3498
➡️ Total Profit: ₹13,419.44
➡️ Equity Curve R²: 0.3441
➡️ Monthly Consistency Score: 0.0520

=== [2874/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.61it/s]
Hypertuning:  83%|████████▎ | 2874/3456 [1:06:47<13:11,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1521
➡️ Total Profit: ₹-4,585.88
➡️ Equity Curve R²: 0.3794
➡️ Monthly Consistency Score: -0.0171

=== [2875/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.32it/s]
Hypertuning:  83%|████████▎ | 2875/3456 [1:06:48<13:22,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.5033
➡️ Total Profit: ₹31,848.53
➡️ Equity Curve R²: 0.2779
➡️ Monthly Consistency Score: 0.1267

=== [2876/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.03it/s]
Hypertuning:  83%|████████▎ | 2876/3456 [1:06:50<13:08,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.8692
➡️ Total Profit: ₹55,008.29
➡️ Equity Curve R²: 0.7880
➡️ Monthly Consistency Score: 0.2218

=== [2877/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.75it/s]
Hypertuning:  83%|████████▎ | 2877/3456 [1:06:51<13:20,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.6725
➡️ Total Profit: ₹23,022.43
➡️ Equity Curve R²: 0.0860
➡️ Monthly Consistency Score: 0.0879

=== [2878/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.96it/s]
Hypertuning:  83%|████████▎ | 2878/3456 [1:06:53<13:05,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.6016
➡️ Total Profit: ₹58,401.25
➡️ Equity Curve R²: 0.0540
➡️ Monthly Consistency Score: 0.2740

=== [2879/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.48it/s]
Hypertuning:  83%|████████▎ | 2879/3456 [1:06:54<13:08,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 5.5046
➡️ Total Profit: ₹107,669.81
➡️ Equity Curve R²: 0.8108
➡️ Monthly Consistency Score: 0.4404

=== [2880/3456] Testing Parameters ===
smooth_length: 14
norm_period: 80
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.31it/s]
Hypertuning:  83%|████████▎ | 2880/3456 [1:06:55<13:16,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 3.9339
➡️ Total Profit: ₹67,032.83
➡️ Equity Curve R²: 0.7179
➡️ Monthly Consistency Score: 0.3176

=== [2881/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.57it/s]
Hypertuning:  83%|████████▎ | 2881/3456 [1:06:57<13:10,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.6816
➡️ Total Profit: ₹-49,359.17
➡️ Equity Curve R²: 0.9384
➡️ Monthly Consistency Score: -0.2133

=== [2882/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.29it/s]
Hypertuning:  83%|████████▎ | 2882/3456 [1:06:58<13:16,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.3876
➡️ Total Profit: ₹-19,820.35
➡️ Equity Curve R²: 0.8498
➡️ Monthly Consistency Score: -0.0881

=== [2883/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.21it/s]
Hypertuning:  83%|████████▎ | 2883/3456 [1:06:59<13:11,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.2451
➡️ Total Profit: ₹26,056.46
➡️ Equity Curve R²: 0.3949
➡️ Monthly Consistency Score: 0.1101

=== [2884/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.83it/s]
Hypertuning:  83%|████████▎ | 2884/3456 [1:07:01<12:54,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0096
➡️ Total Profit: ₹-327.75
➡️ Equity Curve R²: 0.0504
➡️ Monthly Consistency Score: -0.0013

=== [2885/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.65it/s]
Hypertuning:  83%|████████▎ | 2885/3456 [1:07:02<13:07,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.3356
➡️ Total Profit: ₹9,756.29
➡️ Equity Curve R²: 0.0409
➡️ Monthly Consistency Score: 0.0386

=== [2886/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.00it/s]
Hypertuning:  84%|████████▎ | 2886/3456 [1:07:04<12:58,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0703
➡️ Total Profit: ₹-1,899.03
➡️ Equity Curve R²: 0.3566
➡️ Monthly Consistency Score: -0.0070

=== [2887/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.20it/s]
Hypertuning:  84%|████████▎ | 2887/3456 [1:07:05<13:02,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.5140
➡️ Total Profit: ₹12,073.89
➡️ Equity Curve R²: 0.0267
➡️ Monthly Consistency Score: 0.0436

=== [2888/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.52it/s]
Hypertuning:  84%|████████▎ | 2888/3456 [1:07:06<12:48,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1606
➡️ Total Profit: ₹5,762.02
➡️ Equity Curve R²: 0.0574
➡️ Monthly Consistency Score: 0.0218

=== [2889/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 111.92it/s]
Hypertuning:  84%|████████▎ | 2889/3456 [1:07:08<12:57,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.1794
➡️ Total Profit: ₹7,116.96
➡️ Equity Curve R²: 0.2282
➡️ Monthly Consistency Score: 0.0278

=== [2890/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.41it/s]
Hypertuning:  84%|████████▎ | 2890/3456 [1:07:09<12:47,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.7397
➡️ Total Profit: ₹30,599.29
➡️ Equity Curve R²: 0.0095
➡️ Monthly Consistency Score: 0.1155

=== [2891/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.34it/s]
Hypertuning:  84%|████████▎ | 2891/3456 [1:07:10<12:50,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1607
➡️ Total Profit: ₹9,017.57
➡️ Equity Curve R²: 0.4397
➡️ Monthly Consistency Score: 0.0343

=== [2892/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.77it/s]
Hypertuning:  84%|████████▎ | 2892/3456 [1:07:12<12:39,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2723
➡️ Total Profit: ₹10,952.90
➡️ Equity Curve R²: 0.2194
➡️ Monthly Consistency Score: 0.0451

=== [2893/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.51it/s]
Hypertuning:  84%|████████▎ | 2893/3456 [1:07:13<12:49,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.7432
➡️ Total Profit: ₹59,349.20
➡️ Equity Curve R²: 0.3134
➡️ Monthly Consistency Score: 0.2392

=== [2894/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.92it/s]
Hypertuning:  84%|████████▎ | 2894/3456 [1:07:14<12:37,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6568
➡️ Total Profit: ₹32,712.87
➡️ Equity Curve R²: 0.1572
➡️ Monthly Consistency Score: 0.1335

=== [2895/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.34it/s]
Hypertuning:  84%|████████▍ | 2895/3456 [1:07:16<12:45,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.2755
➡️ Total Profit: ₹51,980.56
➡️ Equity Curve R²: 0.0843
➡️ Monthly Consistency Score: 0.1988

=== [2896/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.06it/s]
Hypertuning:  84%|████████▍ | 2896/3456 [1:07:17<12:49,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.8588
➡️ Total Profit: ₹41,469.19
➡️ Equity Curve R²: 0.1928
➡️ Monthly Consistency Score: 0.1772

=== [2897/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.95it/s]
Hypertuning:  84%|████████▍ | 2897/3456 [1:07:19<12:45,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.6983
➡️ Total Profit: ₹-51,943.34
➡️ Equity Curve R²: 0.9469
➡️ Monthly Consistency Score: -0.2307

=== [2898/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.06it/s]
Hypertuning:  84%|████████▍ | 2898/3456 [1:07:20<12:50,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.3766
➡️ Total Profit: ₹-22,171.27
➡️ Equity Curve R²: 0.8939
➡️ Monthly Consistency Score: -0.0948

=== [2899/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.00it/s]
Hypertuning:  84%|████████▍ | 2899/3456 [1:07:21<12:38,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.2569
➡️ Total Profit: ₹26,059.20
➡️ Equity Curve R²: 0.5306
➡️ Monthly Consistency Score: 0.1144

=== [2900/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.04it/s]
Hypertuning:  84%|████████▍ | 2900/3456 [1:07:23<12:25,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.0743
➡️ Total Profit: ₹2,543.21
➡️ Equity Curve R²: 0.1299
➡️ Monthly Consistency Score: 0.0099

=== [2901/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.09it/s]
Hypertuning:  84%|████████▍ | 2901/3456 [1:07:24<12:38,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1004
➡️ Total Profit: ₹23,447.01
➡️ Equity Curve R²: 0.5208
➡️ Monthly Consistency Score: 0.0928

=== [2902/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.63it/s]
Hypertuning:  84%|████████▍ | 2902/3456 [1:07:25<12:26,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2738
➡️ Total Profit: ₹-9,466.28
➡️ Equity Curve R²: 0.5816
➡️ Monthly Consistency Score: -0.0360

=== [2903/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.03it/s]
Hypertuning:  84%|████████▍ | 2903/3456 [1:07:27<12:32,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.7836
➡️ Total Profit: ₹16,965.26
➡️ Equity Curve R²: 0.0000
➡️ Monthly Consistency Score: 0.0608

=== [2904/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.23it/s]
Hypertuning:  84%|████████▍ | 2904/3456 [1:07:28<12:25,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2200
➡️ Total Profit: ₹7,893.85
➡️ Equity Curve R²: 0.0710
➡️ Monthly Consistency Score: 0.0296

=== [2905/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.40it/s]
Hypertuning:  84%|████████▍ | 2905/3456 [1:07:29<12:34,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.1297
➡️ Total Profit: ₹5,228.37
➡️ Equity Curve R²: 0.2416
➡️ Monthly Consistency Score: 0.0206

=== [2906/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.98it/s]
Hypertuning:  84%|████████▍ | 2906/3456 [1:07:31<12:39,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.5575
➡️ Total Profit: ₹24,950.21
➡️ Equity Curve R²: 0.0097
➡️ Monthly Consistency Score: 0.0941

=== [2907/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.35it/s]
Hypertuning:  84%|████████▍ | 2907/3456 [1:07:32<12:28,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2187
➡️ Total Profit: ₹12,277.57
➡️ Equity Curve R²: 0.4787
➡️ Monthly Consistency Score: 0.0474

=== [2908/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.36it/s]
Hypertuning:  84%|████████▍ | 2908/3456 [1:07:33<12:17,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3783
➡️ Total Profit: ₹15,216.55
➡️ Equity Curve R²: 0.1083
➡️ Monthly Consistency Score: 0.0648

=== [2909/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.53it/s]
Hypertuning:  84%|████████▍ | 2909/3456 [1:07:35<12:28,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.8014
➡️ Total Profit: ₹60,609.20
➡️ Equity Curve R²: 0.3478
➡️ Monthly Consistency Score: 0.2463

=== [2910/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.73it/s]
Hypertuning:  84%|████████▍ | 2910/3456 [1:07:36<12:18,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4545
➡️ Total Profit: ₹23,665.51
➡️ Equity Curve R²: 0.2437
➡️ Monthly Consistency Score: 0.0936

=== [2911/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 131.50it/s]
Hypertuning:  84%|████████▍ | 2911/3456 [1:07:38<12:21,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.2755
➡️ Total Profit: ₹51,980.56
➡️ Equity Curve R²: 0.0843
➡️ Monthly Consistency Score: 0.1988

=== [2912/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.65it/s]
Hypertuning:  84%|████████▍ | 2912/3456 [1:07:39<12:12,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.2036
➡️ Total Profit: ₹41,469.19
➡️ Equity Curve R²: 0.2528
➡️ Monthly Consistency Score: 0.1702

=== [2913/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 111.67it/s]
Hypertuning:  84%|████████▍ | 2913/3456 [1:07:40<12:27,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.8037
➡️ Total Profit: ₹-77,910.34
➡️ Equity Curve R²: 0.9769
➡️ Monthly Consistency Score: -0.3439

=== [2914/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.20it/s]
Hypertuning:  84%|████████▍ | 2914/3456 [1:07:42<12:32,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.1449
➡️ Total Profit: ₹-7,296.83
➡️ Equity Curve R²: 0.7303
➡️ Monthly Consistency Score: -0.0308

=== [2915/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.94it/s]
Hypertuning:  84%|████████▍ | 2915/3456 [1:07:43<12:19,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.2409
➡️ Total Profit: ₹25,726.93
➡️ Equity Curve R²: 0.4896
➡️ Monthly Consistency Score: 0.1102

=== [2916/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.62it/s]
Hypertuning:  84%|████████▍ | 2916/3456 [1:07:44<12:07,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.3669
➡️ Total Profit: ₹31,800.43
➡️ Equity Curve R²: 0.7546
➡️ Monthly Consistency Score: 0.1260

=== [2917/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.31it/s]
Hypertuning:  84%|████████▍ | 2917/3456 [1:07:46<12:18,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.0873
➡️ Total Profit: ₹2,352.41
➡️ Equity Curve R²: 0.1042
➡️ Monthly Consistency Score: 0.0084

=== [2918/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.38it/s]
Hypertuning:  84%|████████▍ | 2918/3456 [1:07:47<12:09,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2311
➡️ Total Profit: ₹-7,206.28
➡️ Equity Curve R²: 0.4877
➡️ Monthly Consistency Score: -0.0273

=== [2919/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.18it/s]
Hypertuning:  84%|████████▍ | 2919/3456 [1:07:48<12:13,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.2717
➡️ Total Profit: ₹7,211.11
➡️ Equity Curve R²: 0.1718
➡️ Monthly Consistency Score: 0.0276

=== [2920/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.53it/s]
Hypertuning:  84%|████████▍ | 2920/3456 [1:07:50<12:01,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.5382
➡️ Total Profit: ₹17,023.01
➡️ Equity Curve R²: 0.0860
➡️ Monthly Consistency Score: 0.0592

=== [2921/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.28it/s]
Hypertuning:  85%|████████▍ | 2921/3456 [1:07:51<12:14,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.1296
➡️ Total Profit: ₹5,226.49
➡️ Equity Curve R²: 0.2715
➡️ Monthly Consistency Score: 0.0209

=== [2922/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.25it/s]
Hypertuning:  85%|████████▍ | 2922/3456 [1:07:53<12:04,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4797
➡️ Total Profit: ₹-20,427.96
➡️ Equity Curve R²: 0.6289
➡️ Monthly Consistency Score: -0.0715

=== [2923/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.05it/s]
Hypertuning:  85%|████████▍ | 2923/3456 [1:07:54<12:14,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.4054
➡️ Total Profit: ₹-22,994.79
➡️ Equity Curve R²: 0.7683
➡️ Monthly Consistency Score: -0.0894

=== [2924/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.51it/s]
Hypertuning:  85%|████████▍ | 2924/3456 [1:07:55<12:02,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1135
➡️ Total Profit: ₹4,564.72
➡️ Equity Curve R²: 0.1112
➡️ Monthly Consistency Score: 0.0183

=== [2925/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.48it/s]
Hypertuning:  85%|████████▍ | 2925/3456 [1:07:57<12:09,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.8069
➡️ Total Profit: ₹62,497.79
➡️ Equity Curve R²: 0.3148
➡️ Monthly Consistency Score: 0.2560

=== [2926/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.38it/s]
Hypertuning:  85%|████████▍ | 2926/3456 [1:07:58<11:57,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4660
➡️ Total Profit: ₹24,792.75
➡️ Equity Curve R²: 0.2673
➡️ Monthly Consistency Score: 0.0948

=== [2927/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.12it/s]
Hypertuning:  85%|████████▍ | 2927/3456 [1:07:59<11:59,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.4534
➡️ Total Profit: ₹73,171.94
➡️ Equity Curve R²: 0.6400
➡️ Monthly Consistency Score: 0.3419

=== [2928/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.82it/s]
Hypertuning:  85%|████████▍ | 2928/3456 [1:08:01<11:47,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.8588
➡️ Total Profit: ₹41,469.19
➡️ Equity Curve R²: 0.1928
➡️ Monthly Consistency Score: 0.1772

=== [2929/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 130.23it/s]
Hypertuning:  85%|████████▍ | 2929/3456 [1:08:02<11:57,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.7017
➡️ Total Profit: ₹-54,400.11
➡️ Equity Curve R²: 0.9480
➡️ Monthly Consistency Score: -0.2343

=== [2930/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 92.39it/s]
Hypertuning:  85%|████████▍ | 2930/3456 [1:08:04<12:06,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.4009
➡️ Total Profit: ₹-20,951.27
➡️ Equity Curve R²: 0.8554
➡️ Monthly Consistency Score: -0.0927

=== [2931/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.77it/s]
Hypertuning:  85%|████████▍ | 2931/3456 [1:08:05<11:56,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.2451
➡️ Total Profit: ₹26,056.46
➡️ Equity Curve R²: 0.3949
➡️ Monthly Consistency Score: 0.1101

=== [2932/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.31it/s]
Hypertuning:  85%|████████▍ | 2932/3456 [1:08:06<11:47,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0502
➡️ Total Profit: ₹-1,718.71
➡️ Equity Curve R²: 0.0273
➡️ Monthly Consistency Score: -0.0064

=== [2933/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.34it/s]
Hypertuning:  85%|████████▍ | 2933/3456 [1:08:08<11:57,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.3356
➡️ Total Profit: ₹9,756.29
➡️ Equity Curve R²: 0.0409
➡️ Monthly Consistency Score: 0.0386

=== [2934/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.20it/s]
Hypertuning:  85%|████████▍ | 2934/3456 [1:08:09<11:46,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0025
➡️ Total Profit: ₹-71.79
➡️ Equity Curve R²: 0.4015
➡️ Monthly Consistency Score: -0.0003

=== [2935/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.53it/s]
Hypertuning:  85%|████████▍ | 2935/3456 [1:08:10<11:51,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.5140
➡️ Total Profit: ₹12,073.89
➡️ Equity Curve R²: 0.0267
➡️ Monthly Consistency Score: 0.0436

=== [2936/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.68it/s]
Hypertuning:  85%|████████▍ | 2936/3456 [1:08:12<11:41,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0148
➡️ Total Profit: ₹-626.16
➡️ Equity Curve R²: 0.2427
➡️ Monthly Consistency Score: -0.0023

=== [2937/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.78it/s]
Hypertuning:  85%|████████▍ | 2937/3456 [1:08:13<11:51,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.1794
➡️ Total Profit: ₹7,116.96
➡️ Equity Curve R²: 0.2282
➡️ Monthly Consistency Score: 0.0278

=== [2938/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.53it/s]
Hypertuning:  85%|████████▌ | 2938/3456 [1:08:14<11:42,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.7397
➡️ Total Profit: ₹30,599.29
➡️ Equity Curve R²: 0.0095
➡️ Monthly Consistency Score: 0.1155

=== [2939/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.23it/s]
Hypertuning:  85%|████████▌ | 2939/3456 [1:08:16<11:46,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.1607
➡️ Total Profit: ₹9,017.57
➡️ Equity Curve R²: 0.4397
➡️ Monthly Consistency Score: 0.0343

=== [2940/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.53it/s]
Hypertuning:  85%|████████▌ | 2940/3456 [1:08:17<11:35,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2723
➡️ Total Profit: ₹10,952.90
➡️ Equity Curve R²: 0.2194
➡️ Monthly Consistency Score: 0.0451

=== [2941/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.84it/s]
Hypertuning:  85%|████████▌ | 2941/3456 [1:08:18<11:50,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.8813
➡️ Total Profit: ₹39,615.77
➡️ Equity Curve R²: 0.0866
➡️ Monthly Consistency Score: 0.1700

=== [2942/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.77it/s]
Hypertuning:  85%|████████▌ | 2942/3456 [1:08:20<11:40,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.1426
➡️ Total Profit: ₹44,005.51
➡️ Equity Curve R²: 0.0001
➡️ Monthly Consistency Score: 0.1850

=== [2943/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.21it/s]
Hypertuning:  85%|████████▌ | 2943/3456 [1:08:21<11:43,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.2784
➡️ Total Profit: ₹74,803.31
➡️ Equity Curve R²: 0.5880
➡️ Monthly Consistency Score: 0.3283

=== [2944/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.89it/s]
Hypertuning:  85%|████████▌ | 2944/3456 [1:08:22<11:31,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.8588
➡️ Total Profit: ₹41,469.19
➡️ Equity Curve R²: 0.1928
➡️ Monthly Consistency Score: 0.1772

=== [2945/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.58it/s]
Hypertuning:  85%|████████▌ | 2945/3456 [1:08:24<11:42,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.7948
➡️ Total Profit: ₹-67,131.00
➡️ Equity Curve R²: 0.9611
➡️ Monthly Consistency Score: -0.3059

=== [2946/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.55it/s]
Hypertuning:  85%|████████▌ | 2946/3456 [1:08:25<11:32,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2009
➡️ Total Profit: ₹-10,169.51
➡️ Equity Curve R²: 0.7743
➡️ Monthly Consistency Score: -0.0441

=== [2947/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.88it/s]
Hypertuning:  85%|████████▌ | 2947/3456 [1:08:27<11:36,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1784
➡️ Total Profit: ₹24,430.57
➡️ Equity Curve R²: 0.5286
➡️ Monthly Consistency Score: 0.1085

=== [2948/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.90it/s]
Hypertuning:  85%|████████▌ | 2948/3456 [1:08:28<11:25,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.0743
➡️ Total Profit: ₹2,543.21
➡️ Equity Curve R²: 0.1299
➡️ Monthly Consistency Score: 0.0099

=== [2949/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.96it/s]
Hypertuning:  85%|████████▌ | 2949/3456 [1:08:29<11:36,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0942
➡️ Total Profit: ₹-2,509.35
➡️ Equity Curve R²: 0.5346
➡️ Monthly Consistency Score: -0.0098

=== [2950/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.24it/s]
Hypertuning:  85%|████████▌ | 2950/3456 [1:08:31<11:28,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4425
➡️ Total Profit: ₹16,450.05
➡️ Equity Curve R²: 0.3230
➡️ Monthly Consistency Score: 0.0597

=== [2951/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.77it/s]
Hypertuning:  85%|████████▌ | 2951/3456 [1:08:32<11:31,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.3807
➡️ Total Profit: ₹8,837.00
➡️ Equity Curve R²: 0.0377
➡️ Monthly Consistency Score: 0.0329

=== [2952/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.85it/s]
Hypertuning:  85%|████████▌ | 2952/3456 [1:08:33<11:20,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6249
➡️ Total Profit: ₹19,765.67
➡️ Equity Curve R²: 0.1233
➡️ Monthly Consistency Score: 0.0705

=== [2953/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.96it/s]
Hypertuning:  85%|████████▌ | 2953/3456 [1:08:35<11:28,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.0969
➡️ Total Profit: ₹3,968.37
➡️ Equity Curve R²: 0.2745
➡️ Monthly Consistency Score: 0.0157

=== [2954/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.47it/s]
Hypertuning:  85%|████████▌ | 2954/3456 [1:08:36<11:38,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.6187
➡️ Total Profit: ₹-28,338.88
➡️ Equity Curve R²: 0.6752
➡️ Monthly Consistency Score: -0.0990

=== [2955/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.59it/s]
Hypertuning:  86%|████████▌ | 2955/3456 [1:08:38<11:26,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.0728
➡️ Total Profit: ₹4,128.93
➡️ Equity Curve R²: 0.4862
➡️ Monthly Consistency Score: 0.0158

=== [2956/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.04it/s]
Hypertuning:  86%|████████▌ | 2956/3456 [1:08:39<11:13,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3783
➡️ Total Profit: ₹15,216.55
➡️ Equity Curve R²: 0.1083
➡️ Monthly Consistency Score: 0.0648

=== [2957/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.98it/s]
Hypertuning:  86%|████████▌ | 2957/3456 [1:08:40<11:26,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.7723
➡️ Total Profit: ₹59,979.67
➡️ Equity Curve R²: 0.3561
➡️ Monthly Consistency Score: 0.2443

=== [2958/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.70it/s]
Hypertuning:  86%|████████▌ | 2958/3456 [1:08:42<11:18,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4025
➡️ Total Profit: ₹21,411.03
➡️ Equity Curve R²: 0.2600
➡️ Monthly Consistency Score: 0.0892

=== [2959/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.88it/s]
Hypertuning:  86%|████████▌ | 2959/3456 [1:08:43<11:22,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.2070
➡️ Total Profit: ₹73,174.68
➡️ Equity Curve R²: 0.6350
➡️ Monthly Consistency Score: 0.3261

=== [2960/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.70it/s]
Hypertuning:  86%|████████▌ | 2960/3456 [1:08:44<11:12,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.8588
➡️ Total Profit: ₹41,469.19
➡️ Equity Curve R²: 0.1928
➡️ Monthly Consistency Score: 0.1772

=== [2961/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.52it/s]
Hypertuning:  86%|████████▌ | 2961/3456 [1:08:46<11:23,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.7656
➡️ Total Profit: ₹-67,821.22
➡️ Equity Curve R²: 0.9567
➡️ Monthly Consistency Score: -0.2859

=== [2962/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.81it/s]
Hypertuning:  86%|████████▌ | 2962/3456 [1:08:47<11:13,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3917
➡️ Total Profit: ₹-23,298.51
➡️ Equity Curve R²: 0.8308
➡️ Monthly Consistency Score: -0.0957

=== [2963/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.74it/s]
Hypertuning:  86%|████████▌ | 2963/3456 [1:08:49<11:16,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3100
➡️ Total Profit: ₹-11,893.73
➡️ Equity Curve R²: 0.7726
➡️ Monthly Consistency Score: -0.0525

=== [2964/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.16it/s]
Hypertuning:  86%|████████▌ | 2964/3456 [1:08:50<11:20,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.3877
➡️ Total Profit: ₹9,020.43
➡️ Equity Curve R²: 0.3777
➡️ Monthly Consistency Score: 0.0344

=== [2965/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.56it/s]
Hypertuning:  86%|████████▌ | 2965/3456 [1:08:51<11:19,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.2084
➡️ Total Profit: ₹4,870.53
➡️ Equity Curve R²: 0.0398
➡️ Monthly Consistency Score: 0.0173

=== [2966/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.85it/s]
Hypertuning:  86%|████████▌ | 2966/3456 [1:08:53<11:08,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4344
➡️ Total Profit: ₹-15,811.68
➡️ Equity Curve R²: 0.7741
➡️ Monthly Consistency Score: -0.0583

=== [2967/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.61it/s]
Hypertuning:  86%|████████▌ | 2967/3456 [1:08:54<11:12,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.1253
➡️ Total Profit: ₹3,913.85
➡️ Equity Curve R²: 0.2654
➡️ Monthly Consistency Score: 0.0155

=== [2968/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.58it/s]
Hypertuning:  86%|████████▌ | 2968/3456 [1:08:55<11:02,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5998
➡️ Total Profit: ₹19,154.83
➡️ Equity Curve R²: 0.1516
➡️ Monthly Consistency Score: 0.0657

=== [2969/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.84it/s]
Hypertuning:  86%|████████▌ | 2969/3456 [1:08:57<11:12,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.0815
➡️ Total Profit: ₹3,335.08
➡️ Equity Curve R²: 0.3167
➡️ Monthly Consistency Score: 0.0128

=== [2970/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.10it/s]
Hypertuning:  86%|████████▌ | 2970/3456 [1:08:58<11:06,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.5729
➡️ Total Profit: ₹-24,946.12
➡️ Equity Curve R²: 0.6380
➡️ Monthly Consistency Score: -0.0869

=== [2971/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.02it/s]
Hypertuning:  86%|████████▌ | 2971/3456 [1:09:00<11:11,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.0999
➡️ Total Profit: ₹-4,709.88
➡️ Equity Curve R²: 0.2849
➡️ Monthly Consistency Score: -0.0183

=== [2972/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.19it/s]
Hypertuning:  86%|████████▌ | 2972/3456 [1:09:01<11:03,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0431
➡️ Total Profit: ₹-1,823.46
➡️ Equity Curve R²: 0.1848
➡️ Monthly Consistency Score: -0.0072

=== [2973/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.53it/s]
Hypertuning:  86%|████████▌ | 2973/3456 [1:09:02<11:11,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 2.4199
➡️ Total Profit: ₹59,979.67
➡️ Equity Curve R²: 0.2977
➡️ Monthly Consistency Score: 0.2321

=== [2974/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.98it/s]
Hypertuning:  86%|████████▌ | 2974/3456 [1:09:04<10:58,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.6423
➡️ Total Profit: ₹32,714.71
➡️ Equity Curve R²: 0.2122
➡️ Monthly Consistency Score: 0.1304

=== [2975/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.50it/s]
Hypertuning:  86%|████████▌ | 2975/3456 [1:09:05<11:00,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.0355
➡️ Total Profit: ₹42,200.56
➡️ Equity Curve R²: 0.0022
➡️ Monthly Consistency Score: 0.1664

=== [2976/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.07it/s]
Hypertuning:  86%|████████▌ | 2976/3456 [1:09:06<10:50,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4864
➡️ Total Profit: ₹20,172.83
➡️ Equity Curve R²: 0.1620
➡️ Monthly Consistency Score: 0.0761

=== [2977/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 130.55it/s]
Hypertuning:  86%|████████▌ | 2977/3456 [1:09:08<11:04,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.6240
➡️ Total Profit: ₹-50,810.56
➡️ Equity Curve R²: 0.8919
➡️ Monthly Consistency Score: -0.2170

=== [2978/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.21it/s]
Hypertuning:  86%|████████▌ | 2978/3456 [1:09:09<10:52,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4714
➡️ Total Profit: ₹-27,914.48
➡️ Equity Curve R²: 0.7657
➡️ Monthly Consistency Score: -0.1312

=== [2979/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 131.20it/s]
Hypertuning:  86%|████████▌ | 2979/3456 [1:09:10<10:52,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.0694
➡️ Total Profit: ₹2,841.28
➡️ Equity Curve R²: 0.5422
➡️ Monthly Consistency Score: 0.0108

=== [2980/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.14it/s]
Hypertuning:  86%|████████▌ | 2980/3456 [1:09:12<10:54,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.4864
➡️ Total Profit: ₹11,143.45
➡️ Equity Curve R²: 0.0852
➡️ Monthly Consistency Score: 0.0442

=== [2981/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.65it/s]
Hypertuning:  86%|████████▋ | 2981/3456 [1:09:13<10:51,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2230
➡️ Total Profit: ₹-7,544.21
➡️ Equity Curve R²: 0.4462
➡️ Monthly Consistency Score: -0.0296

=== [2982/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.99it/s]
Hypertuning:  86%|████████▋ | 2982/3456 [1:09:15<10:41,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.4647
➡️ Total Profit: ₹-21,118.68
➡️ Equity Curve R²: 0.7604
➡️ Monthly Consistency Score: -0.0851

=== [2983/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.03it/s]
Hypertuning:  86%|████████▋ | 2983/3456 [1:09:16<10:43,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2559
➡️ Total Profit: ₹8,893.15
➡️ Equity Curve R²: 0.2561
➡️ Monthly Consistency Score: 0.0320

=== [2984/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.07it/s]
Hypertuning:  86%|████████▋ | 2984/3456 [1:09:17<10:33,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.0521
➡️ Total Profit: ₹1,503.98
➡️ Equity Curve R²: 0.0690
➡️ Monthly Consistency Score: 0.0060

=== [2985/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.84it/s]
Hypertuning:  86%|████████▋ | 2985/3456 [1:09:19<10:48,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.2216
➡️ Total Profit: ₹-11,779.62
➡️ Equity Curve R²: 0.7386
➡️ Monthly Consistency Score: -0.0421

=== [2986/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.06it/s]
Hypertuning:  86%|████████▋ | 2986/3456 [1:09:20<10:47,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.4794
➡️ Total Profit: ₹16,077.65
➡️ Equity Curve R²: 0.0528
➡️ Monthly Consistency Score: 0.0600

=== [2987/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.44it/s]
Hypertuning:  86%|████████▋ | 2987/3456 [1:09:21<10:50,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 1.3455
➡️ Total Profit: ₹37,431.68
➡️ Equity Curve R²: 0.0571
➡️ Monthly Consistency Score: 0.1698

=== [2988/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.62it/s]
Hypertuning:  86%|████████▋ | 2988/3456 [1:09:23<10:39,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.8869
➡️ Total Profit: ₹25,183.01
➡️ Equity Curve R²: 0.0113
➡️ Monthly Consistency Score: 0.0928

=== [2989/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.24it/s]
Hypertuning:  86%|████████▋ | 2989/3456 [1:09:24<10:47,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 1.5176
➡️ Total Profit: ₹44,648.20
➡️ Equity Curve R²: 0.0000
➡️ Monthly Consistency Score: 0.1692

=== [2990/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.55it/s]
Hypertuning:  87%|████████▋ | 2990/3456 [1:09:26<10:42,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 3.5954
➡️ Total Profit: ₹68,269.20
➡️ Equity Curve R²: 0.4737
➡️ Monthly Consistency Score: 0.2828

=== [2991/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 100.61it/s]
Hypertuning:  87%|████████▋ | 2991/3456 [1:09:27<10:45,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 1.8363
➡️ Total Profit: ₹50,252.95
➡️ Equity Curve R²: 0.0984
➡️ Monthly Consistency Score: 0.2014

=== [2992/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.19it/s]
Hypertuning:  87%|████████▋ | 2992/3456 [1:09:28<10:33,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.3285
➡️ Total Profit: ₹56,384.65
➡️ Equity Curve R²: 0.4293
➡️ Monthly Consistency Score: 0.2794

=== [2993/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.57it/s]
Hypertuning:  87%|████████▋ | 2993/3456 [1:09:30<10:43,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.5992
➡️ Total Profit: ₹-46,185.53
➡️ Equity Curve R²: 0.8803
➡️ Monthly Consistency Score: -0.2019

=== [2994/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.91it/s]
Hypertuning:  87%|████████▋ | 2994/3456 [1:09:31<10:53,  1.41s/it]

➡️ Profit-to-Drawdown Ratio: -0.3950
➡️ Total Profit: ₹-21,747.31
➡️ Equity Curve R²: 0.8343
➡️ Monthly Consistency Score: -0.0922

=== [2995/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 130.70it/s]
Hypertuning:  87%|████████▋ | 2995/3456 [1:09:33<10:43,  1.40s/it]

➡️ Profit-to-Drawdown Ratio: 0.1092
➡️ Total Profit: ₹4,472.65
➡️ Equity Curve R²: 0.5384
➡️ Monthly Consistency Score: 0.0171

=== [2996/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.26it/s]
Hypertuning:  87%|████████▋ | 2996/3456 [1:09:34<10:32,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.4141
➡️ Total Profit: ₹9,758.05
➡️ Equity Curve R²: 0.1090
➡️ Monthly Consistency Score: 0.0386

=== [2997/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 99.76it/s]
Hypertuning:  87%|████████▋ | 2997/3456 [1:09:35<10:41,  1.40s/it]

➡️ Profit-to-Drawdown Ratio: 0.6434
➡️ Total Profit: ₹13,708.39
➡️ Equity Curve R²: 0.1077
➡️ Monthly Consistency Score: 0.0529

=== [2998/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.85it/s]
Hypertuning:  87%|████████▋ | 2998/3456 [1:09:37<10:29,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.5414
➡️ Total Profit: ₹-27,900.52
➡️ Equity Curve R²: 0.8229
➡️ Monthly Consistency Score: -0.1113

=== [2999/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 129.97it/s]
Hypertuning:  87%|████████▋ | 2999/3456 [1:09:38<10:30,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.9015
➡️ Total Profit: ₹25,155.89
➡️ Equity Curve R²: 0.1732
➡️ Monthly Consistency Score: 0.0904

=== [3000/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.30it/s]
Hypertuning:  87%|████████▋ | 3000/3456 [1:09:39<10:18,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2156
➡️ Total Profit: ₹5,767.62
➡️ Equity Curve R²: 0.0234
➡️ Monthly Consistency Score: 0.0229

=== [3001/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.87it/s]
Hypertuning:  87%|████████▋ | 3001/3456 [1:09:41<10:26,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.1195
➡️ Total Profit: ₹-6,042.40
➡️ Equity Curve R²: 0.6896
➡️ Monthly Consistency Score: -0.0224

=== [3002/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.33it/s]
Hypertuning:  87%|████████▋ | 3002/3456 [1:09:42<10:16,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.4030
➡️ Total Profit: ₹33,126.69
➡️ Equity Curve R²: 0.0000
➡️ Monthly Consistency Score: 0.1279

=== [3003/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 101.66it/s]
Hypertuning:  87%|████████▋ | 3003/3456 [1:09:44<10:24,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.5131
➡️ Total Profit: ₹20,434.42
➡️ Equity Curve R²: 0.2327
➡️ Monthly Consistency Score: 0.0879

=== [3004/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.79it/s]
Hypertuning:  87%|████████▋ | 3004/3456 [1:09:45<10:19,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.8120
➡️ Total Profit: ₹23,054.83
➡️ Equity Curve R²: 0.0216
➡️ Monthly Consistency Score: 0.0859

=== [3005/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.84it/s]
Hypertuning:  87%|████████▋ | 3005/3456 [1:09:46<10:26,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 1.8020
➡️ Total Profit: ₹46,540.56
➡️ Equity Curve R²: 0.4022
➡️ Monthly Consistency Score: 0.1719

=== [3006/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.91it/s]
Hypertuning:  87%|████████▋ | 3006/3456 [1:09:48<10:16,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1887
➡️ Total Profit: ₹41,747.35
➡️ Equity Curve R²: 0.0176
➡️ Monthly Consistency Score: 0.1798

=== [3007/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.28it/s]
Hypertuning:  87%|████████▋ | 3007/3456 [1:09:49<10:17,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.7776
➡️ Total Profit: ₹63,391.93
➡️ Equity Curve R²: 0.5876
➡️ Monthly Consistency Score: 0.2521

=== [3008/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.76it/s]
Hypertuning:  87%|████████▋ | 3008/3456 [1:09:50<10:09,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.1473
➡️ Total Profit: ₹58,516.47
➡️ Equity Curve R²: 0.5536
➡️ Monthly Consistency Score: 0.2783

=== [3009/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 100.46it/s]
Hypertuning:  87%|████████▋ | 3009/3456 [1:09:52<10:21,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.7312
➡️ Total Profit: ₹-58,775.76
➡️ Equity Curve R²: 0.9156
➡️ Monthly Consistency Score: -0.2770

=== [3010/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.57it/s]
Hypertuning:  87%|████████▋ | 3010/3456 [1:09:53<10:09,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4672
➡️ Total Profit: ₹-30,265.56
➡️ Equity Curve R²: 0.9036
➡️ Monthly Consistency Score: -0.1249

=== [3011/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.98it/s]
Hypertuning:  87%|████████▋ | 3011/3456 [1:09:55<10:10,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1552
➡️ Total Profit: ₹-6,551.40
➡️ Equity Curve R²: 0.6947
➡️ Monthly Consistency Score: -0.0258

=== [3012/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.65it/s]
Hypertuning:  87%|████████▋ | 3012/3456 [1:09:56<10:01,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.3880
➡️ Total Profit: ₹26,794.41
➡️ Equity Curve R²: 0.5873
➡️ Monthly Consistency Score: 0.1134

=== [3013/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.38it/s]
Hypertuning:  87%|████████▋ | 3013/3456 [1:09:57<10:14,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 0.4551
➡️ Total Profit: ₹10,557.92
➡️ Equity Curve R²: 0.0124
➡️ Monthly Consistency Score: 0.0402

=== [3014/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.13it/s]
Hypertuning:  87%|████████▋ | 3014/3456 [1:09:59<10:03,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.5927
➡️ Total Profit: ₹-35,386.04
➡️ Equity Curve R²: 0.9114
➡️ Monthly Consistency Score: -0.1474

=== [3015/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.10it/s]
Hypertuning:  87%|████████▋ | 3015/3456 [1:10:00<10:04,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.8521
➡️ Total Profit: ₹33,295.85
➡️ Equity Curve R²: 0.6782
➡️ Monthly Consistency Score: 0.1328

=== [3016/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.80it/s]
Hypertuning:  87%|████████▋ | 3016/3456 [1:10:01<10:11,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 0.2764
➡️ Total Profit: ₹7,899.45
➡️ Equity Curve R²: 0.0263
➡️ Monthly Consistency Score: 0.0310

=== [3017/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 97.97it/s]
Hypertuning:  87%|████████▋ | 3017/3456 [1:10:03<10:10,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.1210
➡️ Total Profit: ₹-6,045.22
➡️ Equity Curve R²: 0.6940
➡️ Monthly Consistency Score: -0.0230

=== [3018/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 101.41it/s]
Hypertuning:  87%|████████▋ | 3018/3456 [1:10:04<10:06,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.2932
➡️ Total Profit: ₹31,995.77
➡️ Equity Curve R²: 0.0043
➡️ Monthly Consistency Score: 0.1172

=== [3019/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.87it/s]
Hypertuning:  87%|████████▋ | 3019/3456 [1:10:06<10:05,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.1270
➡️ Total Profit: ₹-5,057.94
➡️ Equity Curve R²: 0.6804
➡️ Monthly Consistency Score: -0.0209

=== [3020/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.19it/s]
Hypertuning:  87%|████████▋ | 3020/3456 [1:10:07<09:51,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.3282
➡️ Total Profit: ₹9,318.46
➡️ Equity Curve R²: 0.0506
➡️ Monthly Consistency Score: 0.0355

=== [3021/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.41it/s]
Hypertuning:  87%|████████▋ | 3021/3456 [1:10:08<10:03,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 2.4641
➡️ Total Profit: ₹62,087.19
➡️ Equity Curve R²: 0.4340
➡️ Monthly Consistency Score: 0.2268

=== [3022/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.98it/s]
Hypertuning:  87%|████████▋ | 3022/3456 [1:10:10<09:55,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.0866
➡️ Total Profit: ₹40,616.43
➡️ Equity Curve R²: 0.0000
➡️ Monthly Consistency Score: 0.1742

=== [3023/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.35it/s]
Hypertuning:  87%|████████▋ | 3023/3456 [1:10:11<09:54,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.2061
➡️ Total Profit: ₹73,171.94
➡️ Equity Curve R²: 0.5691
➡️ Monthly Consistency Score: 0.3232

=== [3024/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 96.71it/s]
Hypertuning:  88%|████████▊ | 3024/3456 [1:10:12<09:44,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.6498
➡️ Total Profit: ₹58,516.47
➡️ Equity Curve R²: 0.5046
➡️ Monthly Consistency Score: 0.2925

=== [3025/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 131.54it/s]
Hypertuning:  88%|████████▊ | 3025/3456 [1:10:14<09:51,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.6269
➡️ Total Profit: ₹-51,440.09
➡️ Equity Curve R²: 0.8915
➡️ Monthly Consistency Score: -0.2195

=== [3026/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.25it/s]
Hypertuning:  88%|████████▊ | 3026/3456 [1:10:15<10:00,  1.40s/it]

➡️ Profit-to-Drawdown Ratio: -0.3158
➡️ Total Profit: ₹-18,265.31
➡️ Equity Curve R²: 0.7388
➡️ Monthly Consistency Score: -0.0816

=== [3027/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 105.67it/s]
Hypertuning:  88%|████████▊ | 3027/3456 [1:10:17<09:48,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0095
➡️ Total Profit: ₹-418.72
➡️ Equity Curve R²: 0.6478
➡️ Monthly Consistency Score: -0.0016

=== [3028/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.80it/s]
Hypertuning:  88%|████████▊ | 3028/3456 [1:10:18<09:41,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0812
➡️ Total Profit: ₹1,971.63
➡️ Equity Curve R²: 0.0847
➡️ Monthly Consistency Score: 0.0074

=== [3029/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.13it/s]
Hypertuning:  88%|████████▊ | 3029/3456 [1:10:19<09:48,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.2230
➡️ Total Profit: ₹-7,544.21
➡️ Equity Curve R²: 0.4462
➡️ Monthly Consistency Score: -0.0296

=== [3030/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.96it/s]
Hypertuning:  88%|████████▊ | 3030/3456 [1:10:21<09:44,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2753
➡️ Total Profit: ₹-12,507.76
➡️ Equity Curve R²: 0.7319
➡️ Monthly Consistency Score: -0.0509

=== [3031/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.31it/s]
Hypertuning:  88%|████████▊ | 3031/3456 [1:10:22<09:49,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 0.3859
➡️ Total Profit: ₹12,153.15
➡️ Equity Curve R²: 0.1236
➡️ Monthly Consistency Score: 0.0430

=== [3032/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.18it/s]
Hypertuning:  88%|████████▊ | 3032/3456 [1:10:23<09:55,  1.41s/it]

➡️ Profit-to-Drawdown Ratio: 0.0521
➡️ Total Profit: ₹1,503.98
➡️ Equity Curve R²: 0.0690
➡️ Monthly Consistency Score: 0.0060

=== [3033/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.32it/s]
Hypertuning:  88%|████████▊ | 3033/3456 [1:10:25<09:54,  1.41s/it]

➡️ Profit-to-Drawdown Ratio: -0.2216
➡️ Total Profit: ₹-11,779.62
➡️ Equity Curve R²: 0.7386
➡️ Monthly Consistency Score: -0.0421

=== [3034/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.17it/s]
Hypertuning:  88%|████████▊ | 3034/3456 [1:10:26<09:42,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.4794
➡️ Total Profit: ₹16,077.65
➡️ Equity Curve R²: 0.0528
➡️ Monthly Consistency Score: 0.0600

=== [3035/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.21it/s]
Hypertuning:  88%|████████▊ | 3035/3456 [1:10:28<09:44,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 1.3455
➡️ Total Profit: ₹37,431.68
➡️ Equity Curve R²: 0.0571
➡️ Monthly Consistency Score: 0.1698

=== [3036/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 100.19it/s]
Hypertuning:  88%|████████▊ | 3036/3456 [1:10:29<09:33,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.8869
➡️ Total Profit: ₹25,183.01
➡️ Equity Curve R²: 0.0113
➡️ Monthly Consistency Score: 0.0928

=== [3037/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.85it/s]
Hypertuning:  88%|████████▊ | 3037/3456 [1:10:30<09:38,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.5176
➡️ Total Profit: ₹44,648.20
➡️ Equity Curve R²: 0.0000
➡️ Monthly Consistency Score: 0.1692

=== [3038/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 102.51it/s]
Hypertuning:  88%|████████▊ | 3038/3456 [1:10:32<09:30,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.5954
➡️ Total Profit: ₹68,269.20
➡️ Equity Curve R²: 0.4737
➡️ Monthly Consistency Score: 0.2828

=== [3039/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.76it/s]
Hypertuning:  88%|████████▊ | 3039/3456 [1:10:33<09:35,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.8363
➡️ Total Profit: ₹50,252.95
➡️ Equity Curve R²: 0.0984
➡️ Monthly Consistency Score: 0.2014

=== [3040/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 131.25it/s]
Hypertuning:  88%|████████▊ | 3040/3456 [1:10:35<09:40,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 2.3285
➡️ Total Profit: ₹56,384.65
➡️ Equity Curve R²: 0.4293
➡️ Monthly Consistency Score: 0.2794

=== [3041/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 102.19it/s]
Hypertuning:  88%|████████▊ | 3041/3456 [1:10:36<09:37,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.7279
➡️ Total Profit: ₹-59,069.63
➡️ Equity Curve R²: 0.9059
➡️ Monthly Consistency Score: -0.2637

=== [3042/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.21it/s]
Hypertuning:  88%|████████▊ | 3042/3456 [1:10:37<09:40,  1.40s/it]

➡️ Profit-to-Drawdown Ratio: -0.4915
➡️ Total Profit: ₹-27,400.08
➡️ Equity Curve R²: 0.8630
➡️ Monthly Consistency Score: -0.1260

=== [3043/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.06it/s]
Hypertuning:  88%|████████▊ | 3043/3456 [1:10:39<09:29,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.1118
➡️ Total Profit: ₹-5,307.35
➡️ Equity Curve R²: 0.7105
➡️ Monthly Consistency Score: -0.0206

=== [3044/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.44it/s]
Hypertuning:  88%|████████▊ | 3044/3456 [1:10:40<09:24,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.7755
➡️ Total Profit: ₹18,274.41
➡️ Equity Curve R²: 0.3140
➡️ Monthly Consistency Score: 0.0742

=== [3045/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.39it/s]
Hypertuning:  88%|████████▊ | 3045/3456 [1:10:41<09:30,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 0.4660
➡️ Total Profit: ₹9,928.39
➡️ Equity Curve R²: 0.0189
➡️ Monthly Consistency Score: 0.0380

=== [3046/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.96it/s]
Hypertuning:  88%|████████▊ | 3046/3456 [1:10:43<09:19,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4818
➡️ Total Profit: ₹-26,416.96
➡️ Equity Curve R²: 0.8198
➡️ Monthly Consistency Score: -0.1015

=== [3047/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 98.87it/s]
Hypertuning:  88%|████████▊ | 3047/3456 [1:10:44<09:24,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.4947
➡️ Total Profit: ₹13,767.63
➡️ Equity Curve R²: 0.0450
➡️ Monthly Consistency Score: 0.0522

=== [3048/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.92it/s]
Hypertuning:  88%|████████▊ | 3048/3456 [1:10:45<09:14,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0491
➡️ Total Profit: ₹1,507.62
➡️ Equity Curve R²: 0.1094
➡️ Monthly Consistency Score: 0.0060

=== [3049/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.01it/s]
Hypertuning:  88%|████████▊ | 3049/3456 [1:10:47<09:29,  1.40s/it]

➡️ Profit-to-Drawdown Ratio: -0.1882
➡️ Total Profit: ₹-9,890.09
➡️ Equity Curve R²: 0.7182
➡️ Monthly Consistency Score: -0.0356

=== [3050/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.86it/s]
Hypertuning:  88%|████████▊ | 3050/3456 [1:10:48<09:18,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.9735
➡️ Total Profit: ₹24,084.85
➡️ Equity Curve R²: 0.0131
➡️ Monthly Consistency Score: 0.0923

=== [3051/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.38it/s]
Hypertuning:  88%|████████▊ | 3051/3456 [1:10:50<09:20,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.2283
➡️ Total Profit: ₹34,171.68
➡️ Equity Curve R²: 0.0522
➡️ Monthly Consistency Score: 0.1484

=== [3052/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.22it/s]
Hypertuning:  88%|████████▊ | 3052/3456 [1:10:51<09:09,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.8869
➡️ Total Profit: ₹25,183.01
➡️ Equity Curve R²: 0.0113
➡️ Monthly Consistency Score: 0.0928

=== [3053/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.03it/s]
Hypertuning:  88%|████████▊ | 3053/3456 [1:10:52<09:17,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.4842
➡️ Total Profit: ₹15,462.43
➡️ Equity Curve R²: 0.2047
➡️ Monthly Consistency Score: 0.0598

=== [3054/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.36it/s]
Hypertuning:  88%|████████▊ | 3054/3456 [1:10:54<09:09,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.3280
➡️ Total Profit: ₹45,138.27
➡️ Equity Curve R²: 0.0403
➡️ Monthly Consistency Score: 0.1978

=== [3055/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.67it/s]
Hypertuning:  88%|████████▊ | 3055/3456 [1:10:55<09:13,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.5634
➡️ Total Profit: ₹58,503.30
➡️ Equity Curve R²: 0.5627
➡️ Monthly Consistency Score: 0.2363

=== [3056/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.99it/s]
Hypertuning:  88%|████████▊ | 3056/3456 [1:10:56<09:04,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.3285
➡️ Total Profit: ₹56,384.65
➡️ Equity Curve R²: 0.4293
➡️ Monthly Consistency Score: 0.2794

=== [3057/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.04it/s]
Hypertuning:  88%|████████▊ | 3057/3456 [1:10:58<09:13,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.6833
➡️ Total Profit: ₹-56,258.58
➡️ Equity Curve R²: 0.8944
➡️ Monthly Consistency Score: -0.2331

=== [3058/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.89it/s]
Hypertuning:  88%|████████▊ | 3058/3456 [1:10:59<09:05,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.5372
➡️ Total Profit: ₹-31,394.64
➡️ Equity Curve R²: 0.8556
➡️ Monthly Consistency Score: -0.1474

=== [3059/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.33it/s]
Hypertuning:  89%|████████▊ | 3059/3456 [1:11:01<09:07,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.3032
➡️ Total Profit: ₹-13,527.36
➡️ Equity Curve R²: 0.7083
➡️ Monthly Consistency Score: -0.0493

=== [3060/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.26it/s]
Hypertuning:  89%|████████▊ | 3060/3456 [1:11:02<08:57,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0994
➡️ Total Profit: ₹2,625.37
➡️ Equity Curve R²: 0.0304
➡️ Monthly Consistency Score: 0.0104

=== [3061/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.31it/s]
Hypertuning:  89%|████████▊ | 3061/3456 [1:11:03<09:03,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.0065
➡️ Total Profit: ₹182.75
➡️ Equity Curve R²: 0.3871
➡️ Monthly Consistency Score: 0.0007

=== [3062/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.78it/s]
Hypertuning:  89%|████████▊ | 3062/3456 [1:11:05<09:09,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.5031
➡️ Total Profit: ₹-30,084.08
➡️ Equity Curve R²: 0.9039
➡️ Monthly Consistency Score: -0.1233

=== [3063/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.93it/s]
Hypertuning:  89%|████████▊ | 3063/3456 [1:11:06<08:58,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.8487
➡️ Total Profit: ₹33,278.22
➡️ Equity Curve R²: 0.7261
➡️ Monthly Consistency Score: 0.1312

=== [3064/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.16it/s]
Hypertuning:  89%|████████▊ | 3064/3456 [1:11:08<09:02,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.4547
➡️ Total Profit: ₹12,163.09
➡️ Equity Curve R²: 0.0019
➡️ Monthly Consistency Score: 0.0475

=== [3065/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.33it/s]
Hypertuning:  89%|████████▊ | 3065/3456 [1:11:09<08:57,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2097
➡️ Total Profit: ₹-11,150.09
➡️ Equity Curve R²: 0.7507
➡️ Monthly Consistency Score: -0.0380

=== [3066/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 129.87it/s]
Hypertuning:  89%|████████▊ | 3066/3456 [1:11:10<08:49,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.4509
➡️ Total Profit: ₹34,257.61
➡️ Equity Curve R²: 0.0141
➡️ Monthly Consistency Score: 0.1248

=== [3067/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.97it/s]
Hypertuning:  89%|████████▊ | 3067/3456 [1:11:12<08:53,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2991
➡️ Total Profit: ₹-14,835.20
➡️ Equity Curve R²: 0.7243
➡️ Monthly Consistency Score: -0.0625

=== [3068/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.09it/s]
Hypertuning:  89%|████████▉ | 3068/3456 [1:11:13<08:44,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.1032
➡️ Total Profit: ₹2,930.28
➡️ Equity Curve R²: 0.1527
➡️ Monthly Consistency Score: 0.0110

=== [3069/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.65it/s]
Hypertuning:  89%|████████▉ | 3069/3456 [1:11:14<08:51,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.4570
➡️ Total Profit: ₹13,156.71
➡️ Equity Curve R²: 0.2404
➡️ Monthly Consistency Score: 0.0522

=== [3070/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.30it/s]
Hypertuning:  89%|████████▉ | 3070/3456 [1:11:16<08:57,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 1.3946
➡️ Total Profit: ₹47,400.11
➡️ Equity Curve R²: 0.0279
➡️ Monthly Consistency Score: 0.2086

=== [3071/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.95it/s]
Hypertuning:  89%|████████▉ | 3071/3456 [1:11:17<08:47,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.2061
➡️ Total Profit: ₹73,171.94
➡️ Equity Curve R²: 0.5691
➡️ Monthly Consistency Score: 0.3232

=== [3072/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.93it/s]
Hypertuning:  89%|████████▉ | 3072/3456 [1:11:18<08:38,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.9058
➡️ Total Profit: ₹54,260.11
➡️ Equity Curve R²: 0.3850
➡️ Monthly Consistency Score: 0.2554

=== [3073/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.75it/s]
Hypertuning:  89%|████████▉ | 3073/3456 [1:11:20<08:46,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.6317
➡️ Total Profit: ₹-49,133.48
➡️ Equity Curve R²: 0.9061
➡️ Monthly Consistency Score: -0.2155

=== [3074/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 131.50it/s]
Hypertuning:  89%|████████▉ | 3074/3456 [1:11:21<08:39,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3111
➡️ Total Profit: ₹-16,179.31
➡️ Equity Curve R²: 0.8453
➡️ Monthly Consistency Score: -0.0688

=== [3075/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.43it/s]
Hypertuning:  89%|████████▉ | 3075/3456 [1:11:23<08:43,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.9981
➡️ Total Profit: ₹32,645.69
➡️ Equity Curve R²: 0.0479
➡️ Monthly Consistency Score: 0.1213

=== [3076/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.09it/s]
Hypertuning:  89%|████████▉ | 3076/3456 [1:11:24<08:34,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.9682
➡️ Total Profit: ₹58,844.68
➡️ Equity Curve R²: 0.8456
➡️ Monthly Consistency Score: 0.2262

=== [3077/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.10it/s]
Hypertuning:  89%|████████▉ | 3077/3456 [1:11:25<08:39,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.5544
➡️ Total Profit: ₹-33,964.15
➡️ Equity Curve R²: 0.9171
➡️ Monthly Consistency Score: -0.1256

=== [3078/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.73it/s]
Hypertuning:  89%|████████▉ | 3078/3456 [1:11:27<08:32,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0499
➡️ Total Profit: ₹-1,983.71
➡️ Equity Curve R²: 0.4087
➡️ Monthly Consistency Score: -0.0074

=== [3079/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.88it/s]
Hypertuning:  89%|████████▉ | 3079/3456 [1:11:28<08:34,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1458
➡️ Total Profit: ₹-5,785.64
➡️ Equity Curve R²: 0.6576
➡️ Monthly Consistency Score: -0.0220

=== [3080/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.60it/s]
Hypertuning:  89%|████████▉ | 3080/3456 [1:11:29<08:25,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0537
➡️ Total Profit: ₹-1,847.56
➡️ Equity Curve R²: 0.3577
➡️ Monthly Consistency Score: -0.0070

=== [3081/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.65it/s]
Hypertuning:  89%|████████▉ | 3081/3456 [1:11:31<08:33,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4647
➡️ Total Profit: ₹-35,534.16
➡️ Equity Curve R²: 0.9100
➡️ Monthly Consistency Score: -0.1209

=== [3082/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.37it/s]
Hypertuning:  89%|████████▉ | 3082/3456 [1:11:32<08:28,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.3609
➡️ Total Profit: ₹16,083.49
➡️ Equity Curve R²: 0.1915
➡️ Monthly Consistency Score: 0.0594

=== [3083/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.94it/s]
Hypertuning:  89%|████████▉ | 3083/3456 [1:11:33<08:33,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.2451
➡️ Total Profit: ₹47,563.62
➡️ Equity Curve R²: 0.4189
➡️ Monthly Consistency Score: 0.1942

=== [3084/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 130.08it/s]
Hypertuning:  89%|████████▉ | 3084/3456 [1:11:35<08:37,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 2.0680
➡️ Total Profit: ₹47,439.37
➡️ Equity Curve R²: 0.4636
➡️ Monthly Consistency Score: 0.1744

=== [3085/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 95.76it/s]
Hypertuning:  89%|████████▉ | 3085/3456 [1:11:36<08:34,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 2.1292
➡️ Total Profit: ₹50,959.49
➡️ Equity Curve R²: 0.4304
➡️ Monthly Consistency Score: 0.1761

=== [3086/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.84it/s]
Hypertuning:  89%|████████▉ | 3086/3456 [1:11:38<08:40,  1.41s/it]

➡️ Profit-to-Drawdown Ratio: 3.4369
➡️ Total Profit: ₹81,535.86
➡️ Equity Curve R²: 0.5153
➡️ Monthly Consistency Score: 0.3503

=== [3087/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.39it/s]
Hypertuning:  89%|████████▉ | 3087/3456 [1:11:39<08:30,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.0032
➡️ Total Profit: ₹64,932.54
➡️ Equity Curve R²: 0.1729
➡️ Monthly Consistency Score: 0.2857

=== [3088/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.48it/s]
Hypertuning:  89%|████████▉ | 3088/3456 [1:11:40<08:19,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 9.0758
➡️ Total Profit: ₹96,641.14
➡️ Equity Curve R²: 0.8292
➡️ Monthly Consistency Score: 0.4758

=== [3089/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.55it/s]
Hypertuning:  89%|████████▉ | 3089/3456 [1:11:42<08:25,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.6148
➡️ Total Profit: ₹-49,199.53
➡️ Equity Curve R²: 0.9143
➡️ Monthly Consistency Score: -0.2170

=== [3090/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.12it/s]
Hypertuning:  89%|████████▉ | 3090/3456 [1:11:43<08:16,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2976
➡️ Total Profit: ₹-15,663.07
➡️ Equity Curve R²: 0.8341
➡️ Monthly Consistency Score: -0.0648

=== [3091/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 111.28it/s]
Hypertuning:  89%|████████▉ | 3091/3456 [1:11:44<08:17,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.6413
➡️ Total Profit: ₹22,019.80
➡️ Equity Curve R²: 0.0066
➡️ Monthly Consistency Score: 0.0826

=== [3092/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.87it/s]
Hypertuning:  89%|████████▉ | 3092/3456 [1:11:46<08:20,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.9682
➡️ Total Profit: ₹58,844.68
➡️ Equity Curve R²: 0.8456
➡️ Monthly Consistency Score: 0.2262

=== [3093/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.82it/s]
Hypertuning:  89%|████████▉ | 3093/3456 [1:11:47<08:17,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4242
➡️ Total Profit: ₹-19,642.95
➡️ Equity Curve R²: 0.8554
➡️ Monthly Consistency Score: -0.0688

=== [3094/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.94it/s]
Hypertuning:  90%|████████▉ | 3094/3456 [1:11:49<08:13,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2084
➡️ Total Profit: ₹-8,761.88
➡️ Equity Curve R²: 0.5826
➡️ Monthly Consistency Score: -0.0315

=== [3095/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.80it/s]
Hypertuning:  90%|████████▉ | 3095/3456 [1:11:50<08:15,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.5176
➡️ Total Profit: ₹16,991.63
➡️ Equity Curve R²: 0.0252
➡️ Monthly Consistency Score: 0.0612

=== [3096/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 111.06it/s]
Hypertuning:  90%|████████▉ | 3096/3456 [1:11:51<08:06,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0537
➡️ Total Profit: ₹-1,847.56
➡️ Equity Curve R²: 0.3577
➡️ Monthly Consistency Score: -0.0070

=== [3097/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.48it/s]
Hypertuning:  90%|████████▉ | 3097/3456 [1:11:53<08:12,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2553
➡️ Total Profit: ₹-13,601.80
➡️ Equity Curve R²: 0.7663
➡️ Monthly Consistency Score: -0.0472

=== [3098/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.96it/s]
Hypertuning:  90%|████████▉ | 3098/3456 [1:11:54<08:05,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.3965
➡️ Total Profit: ₹37,734.41
➡️ Equity Curve R²: 0.1117
➡️ Monthly Consistency Score: 0.1444

=== [3099/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.46it/s]
Hypertuning:  90%|████████▉ | 3099/3456 [1:11:55<08:07,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.6902
➡️ Total Profit: ₹56,994.42
➡️ Equity Curve R²: 0.4554
➡️ Monthly Consistency Score: 0.2413

=== [3100/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.20it/s]
Hypertuning:  90%|████████▉ | 3100/3456 [1:11:57<08:00,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.0680
➡️ Total Profit: ₹47,439.37
➡️ Equity Curve R²: 0.4636
➡️ Monthly Consistency Score: 0.1744

=== [3101/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.69it/s]
Hypertuning:  90%|████████▉ | 3101/3456 [1:11:58<08:07,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.1108
➡️ Total Profit: ₹50,958.55
➡️ Equity Curve R²: 0.3853
➡️ Monthly Consistency Score: 0.1769

=== [3102/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.90it/s]
Hypertuning:  90%|████████▉ | 3102/3456 [1:11:59<07:59,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.7738
➡️ Total Profit: ₹60,666.77
➡️ Equity Curve R²: 0.0765
➡️ Monthly Consistency Score: 0.2674

=== [3103/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.55it/s]
Hypertuning:  90%|████████▉ | 3103/3456 [1:12:01<08:02,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 4.3289
➡️ Total Profit: ₹84,672.55
➡️ Equity Curve R²: 0.6496
➡️ Monthly Consistency Score: 0.3571

=== [3104/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.86it/s]
Hypertuning:  90%|████████▉ | 3104/3456 [1:12:02<08:05,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 9.0758
➡️ Total Profit: ₹96,641.14
➡️ Equity Curve R²: 0.8292
➡️ Monthly Consistency Score: 0.4758

=== [3105/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.25it/s]
Hypertuning:  90%|████████▉ | 3105/3456 [1:12:04<08:02,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.7387
➡️ Total Profit: ₹-57,101.50
➡️ Equity Curve R²: 0.9273
➡️ Monthly Consistency Score: -0.2650

=== [3106/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.67it/s]
Hypertuning:  90%|████████▉ | 3106/3456 [1:12:05<07:56,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3809
➡️ Total Profit: ₹-22,528.80
➡️ Equity Curve R²: 0.8289
➡️ Monthly Consistency Score: -0.0924

=== [3107/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.48it/s]
Hypertuning:  90%|████████▉ | 3107/3456 [1:12:06<07:57,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.0460
➡️ Total Profit: ₹35,513.01
➡️ Equity Curve R²: 0.0382
➡️ Monthly Consistency Score: 0.1390

=== [3108/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.90it/s]
Hypertuning:  90%|████████▉ | 3108/3456 [1:12:08<07:48,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.7223
➡️ Total Profit: ₹42,447.29
➡️ Equity Curve R²: 0.6553
➡️ Monthly Consistency Score: 0.1547

=== [3109/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.45it/s]
Hypertuning:  90%|████████▉ | 3109/3456 [1:12:09<07:57,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.4281
➡️ Total Profit: ₹-20,904.83
➡️ Equity Curve R²: 0.8620
➡️ Monthly Consistency Score: -0.0729

=== [3110/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.07it/s]
Hypertuning:  90%|████████▉ | 3110/3456 [1:12:10<07:49,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3526
➡️ Total Profit: ₹-17,372.80
➡️ Equity Curve R²: 0.8129
➡️ Monthly Consistency Score: -0.0641

=== [3111/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.27it/s]
Hypertuning:  90%|█████████ | 3111/3456 [1:12:12<07:52,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.5258
➡️ Total Profit: ₹12,120.63
➡️ Equity Curve R²: 0.2184
➡️ Monthly Consistency Score: 0.0451

=== [3112/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.55it/s]
Hypertuning:  90%|█████████ | 3112/3456 [1:12:13<07:45,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1157
➡️ Total Profit: ₹-3,975.74
➡️ Equity Curve R²: 0.4100
➡️ Monthly Consistency Score: -0.0152

=== [3113/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.00it/s]
Hypertuning:  90%|█████████ | 3113/3456 [1:12:15<07:53,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.2841
➡️ Total Profit: ₹-15,494.15
➡️ Equity Curve R²: 0.7962
➡️ Monthly Consistency Score: -0.0539

=== [3114/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.44it/s]
Hypertuning:  90%|█████████ | 3114/3456 [1:12:16<07:46,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.6730
➡️ Total Profit: ₹23,045.33
➡️ Equity Curve R²: 0.0953
➡️ Monthly Consistency Score: 0.0839

=== [3115/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.55it/s]
Hypertuning:  90%|█████████ | 3115/3456 [1:12:17<07:48,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.6572
➡️ Total Profit: ₹35,108.53
➡️ Equity Curve R²: 0.4866
➡️ Monthly Consistency Score: 0.1386

=== [3116/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.92it/s]
Hypertuning:  90%|█████████ | 3116/3456 [1:12:19<07:40,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6303
➡️ Total Profit: ₹18,314.01
➡️ Equity Curve R²: 0.0284
➡️ Monthly Consistency Score: 0.0679

=== [3117/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.52it/s]
Hypertuning:  90%|█████████ | 3117/3456 [1:12:20<07:47,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.4575
➡️ Total Profit: ₹37,316.58
➡️ Equity Curve R²: 0.2336
➡️ Monthly Consistency Score: 0.1291

=== [3118/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.86it/s]
Hypertuning:  90%|█████████ | 3118/3456 [1:12:21<07:41,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.5756
➡️ Total Profit: ₹53,888.61
➡️ Equity Curve R²: 0.0207
➡️ Monthly Consistency Score: 0.2360

=== [3119/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.16it/s]
Hypertuning:  90%|█████████ | 3119/3456 [1:12:23<07:43,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 4.1623
➡️ Total Profit: ₹81,415.29
➡️ Equity Curve R²: 0.6614
➡️ Monthly Consistency Score: 0.3499

=== [3120/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.03it/s]
Hypertuning:  90%|█████████ | 3120/3456 [1:12:24<07:36,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.7101
➡️ Total Profit: ₹59,857.49
➡️ Equity Curve R²: 0.5392
➡️ Monthly Consistency Score: 0.2656

=== [3121/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.74it/s]
Hypertuning:  90%|█████████ | 3121/3456 [1:12:25<07:41,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.6266
➡️ Total Profit: ₹-49,132.54
➡️ Equity Curve R²: 0.9053
➡️ Monthly Consistency Score: -0.2152

=== [3122/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.96it/s]
Hypertuning:  90%|█████████ | 3122/3456 [1:12:27<07:35,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1255
➡️ Total Profit: ₹-6,530.15
➡️ Equity Curve R²: 0.7784
➡️ Monthly Consistency Score: -0.0269

=== [3123/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.70it/s]
Hypertuning:  90%|█████████ | 3123/3456 [1:12:28<07:39,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.9981
➡️ Total Profit: ₹32,645.69
➡️ Equity Curve R²: 0.0479
➡️ Monthly Consistency Score: 0.1213

=== [3124/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.00it/s]
Hypertuning:  90%|█████████ | 3124/3456 [1:12:30<07:31,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.8606
➡️ Total Profit: ₹56,712.86
➡️ Equity Curve R²: 0.8192
➡️ Monthly Consistency Score: 0.2157

=== [3125/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.49it/s]
Hypertuning:  90%|█████████ | 3125/3456 [1:12:31<07:38,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.5441
➡️ Total Profit: ₹-33,333.68
➡️ Equity Curve R²: 0.9164
➡️ Monthly Consistency Score: -0.1232

=== [3126/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.80it/s]
Hypertuning:  90%|█████████ | 3126/3456 [1:12:32<07:31,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.0354
➡️ Total Profit: ₹1,407.21
➡️ Equity Curve R²: 0.3618
➡️ Monthly Consistency Score: 0.0053

=== [3127/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.26it/s]
Hypertuning:  90%|█████████ | 3127/3456 [1:12:34<07:24,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.1458
➡️ Total Profit: ₹-5,785.64
➡️ Equity Curve R²: 0.6576
➡️ Monthly Consistency Score: -0.0220

=== [3128/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.82it/s]
Hypertuning:  91%|█████████ | 3128/3456 [1:12:35<07:25,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0537
➡️ Total Profit: ₹-1,847.56
➡️ Equity Curve R²: 0.3577
➡️ Monthly Consistency Score: -0.0070

=== [3129/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 111.64it/s]
Hypertuning:  91%|█████████ | 3129/3456 [1:12:36<07:34,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.4647
➡️ Total Profit: ₹-35,534.16
➡️ Equity Curve R²: 0.9100
➡️ Monthly Consistency Score: -0.1209

=== [3130/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.40it/s]
Hypertuning:  91%|█████████ | 3130/3456 [1:12:38<07:29,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.3610
➡️ Total Profit: ₹16,085.33
➡️ Equity Curve R²: 0.1915
➡️ Monthly Consistency Score: 0.0594

=== [3131/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.08it/s]
Hypertuning:  91%|█████████ | 3131/3456 [1:12:39<07:24,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.2451
➡️ Total Profit: ₹47,563.62
➡️ Equity Curve R²: 0.4189
➡️ Monthly Consistency Score: 0.1942

=== [3132/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.37it/s]
Hypertuning:  91%|█████████ | 3132/3456 [1:12:41<07:25,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.0680
➡️ Total Profit: ₹47,439.37
➡️ Equity Curve R²: 0.4636
➡️ Monthly Consistency Score: 0.1744

=== [3133/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.21it/s]
Hypertuning:  91%|█████████ | 3133/3456 [1:12:42<07:20,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.1556
➡️ Total Profit: ₹51,589.96
➡️ Equity Curve R²: 0.4348
➡️ Monthly Consistency Score: 0.1789

=== [3134/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.46it/s]
Hypertuning:  91%|█████████ | 3134/3456 [1:12:43<07:23,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 3.4369
➡️ Total Profit: ₹81,535.86
➡️ Equity Curve R²: 0.5153
➡️ Monthly Consistency Score: 0.3503

=== [3135/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.09it/s]
Hypertuning:  91%|█████████ | 3135/3456 [1:12:45<07:16,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.0032
➡️ Total Profit: ₹64,932.54
➡️ Equity Curve R²: 0.1729
➡️ Monthly Consistency Score: 0.2857

=== [3136/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.09it/s]
Hypertuning:  91%|█████████ | 3136/3456 [1:12:46<07:17,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 9.0758
➡️ Total Profit: ₹96,641.14
➡️ Equity Curve R²: 0.8292
➡️ Monthly Consistency Score: 0.4758

=== [3137/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.28it/s]
Hypertuning:  91%|█████████ | 3137/3456 [1:12:47<07:15,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.7014
➡️ Total Profit: ₹-56,128.13
➡️ Equity Curve R²: 0.9263
➡️ Monthly Consistency Score: -0.2568

=== [3138/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.82it/s]
Hypertuning:  91%|█████████ | 3138/3456 [1:12:49<07:17,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.2661
➡️ Total Profit: ₹-13,403.07
➡️ Equity Curve R²: 0.8086
➡️ Monthly Consistency Score: -0.0555

=== [3139/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.39it/s]
Hypertuning:  91%|█████████ | 3139/3456 [1:12:50<07:20,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 0.8084
➡️ Total Profit: ₹27,757.06
➡️ Equity Curve R²: 0.0017
➡️ Monthly Consistency Score: 0.1047

=== [3140/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.13it/s]
Hypertuning:  91%|█████████ | 3140/3456 [1:12:52<07:12,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.8606
➡️ Total Profit: ₹56,712.86
➡️ Equity Curve R²: 0.8509
➡️ Monthly Consistency Score: 0.2188

=== [3141/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.62it/s]
Hypertuning:  91%|█████████ | 3141/3456 [1:12:53<07:09,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4242
➡️ Total Profit: ₹-19,642.01
➡️ Equity Curve R²: 0.8564
➡️ Monthly Consistency Score: -0.0688

=== [3142/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.16it/s]
Hypertuning:  91%|█████████ | 3142/3456 [1:12:54<07:14,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.1350
➡️ Total Profit: ₹-5,372.79
➡️ Equity Curve R²: 0.4107
➡️ Monthly Consistency Score: -0.0194

=== [3143/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.88it/s]
Hypertuning:  91%|█████████ | 3143/3456 [1:12:56<07:05,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0681
➡️ Total Profit: ₹2,346.10
➡️ Equity Curve R²: 0.0610
➡️ Monthly Consistency Score: 0.0089

=== [3144/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.71it/s]
Hypertuning:  91%|█████████ | 3144/3456 [1:12:57<07:05,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1156
➡️ Total Profit: ₹-3,975.74
➡️ Equity Curve R²: 0.4128
➡️ Monthly Consistency Score: -0.0149

=== [3145/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.25it/s]
Hypertuning:  91%|█████████ | 3145/3456 [1:12:58<07:02,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2584
➡️ Total Profit: ₹-13,601.80
➡️ Equity Curve R²: 0.7639
➡️ Monthly Consistency Score: -0.0474

=== [3146/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.12it/s]
Hypertuning:  91%|█████████ | 3146/3456 [1:13:00<07:05,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.6153
➡️ Total Profit: ₹39,994.41
➡️ Equity Curve R²: 0.1860
➡️ Monthly Consistency Score: 0.1542

=== [3147/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.55it/s]
Hypertuning:  91%|█████████ | 3147/3456 [1:13:01<06:58,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.3826
➡️ Total Profit: ₹50,477.16
➡️ Equity Curve R²: 0.4500
➡️ Monthly Consistency Score: 0.2128

=== [3148/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.52it/s]
Hypertuning:  91%|█████████ | 3148/3456 [1:13:02<07:01,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.0680
➡️ Total Profit: ₹47,439.37
➡️ Equity Curve R²: 0.4636
➡️ Monthly Consistency Score: 0.1744

=== [3149/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.85it/s]
Hypertuning:  91%|█████████ | 3149/3456 [1:13:04<06:58,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.0159
➡️ Total Profit: ₹49,070.90
➡️ Equity Curve R²: 0.3477
➡️ Monthly Consistency Score: 0.1698

=== [3150/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.45it/s]
Hypertuning:  91%|█████████ | 3150/3456 [1:13:05<07:01,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.9700
➡️ Total Profit: ₹62,926.78
➡️ Equity Curve R²: 0.1339
➡️ Monthly Consistency Score: 0.2813

=== [3151/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.16it/s]
Hypertuning:  91%|█████████ | 3151/3456 [1:13:07<06:53,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.7665
➡️ Total Profit: ₹79,786.66
➡️ Equity Curve R²: 0.6242
➡️ Monthly Consistency Score: 0.3418

=== [3152/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.77it/s]
Hypertuning:  91%|█████████ | 3152/3456 [1:13:08<06:56,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 5.1571
➡️ Total Profit: ₹76,901.14
➡️ Equity Curve R²: 0.7344
➡️ Monthly Consistency Score: 0.3856

=== [3153/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.20it/s]
Hypertuning:  91%|█████████ | 3153/3456 [1:13:09<06:53,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.6402
➡️ Total Profit: ₹-47,998.34
➡️ Equity Curve R²: 0.9130
➡️ Monthly Consistency Score: -0.2060

=== [3154/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.98it/s]
Hypertuning:  91%|█████████▏| 3154/3456 [1:13:11<06:55,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.3717
➡️ Total Profit: ₹-19,136.03
➡️ Equity Curve R²: 0.8433
➡️ Monthly Consistency Score: -0.0821

=== [3155/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.72it/s]
Hypertuning:  91%|█████████▏| 3155/3456 [1:13:12<06:48,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4344
➡️ Total Profit: ₹15,046.59
➡️ Equity Curve R²: 0.1601
➡️ Monthly Consistency Score: 0.0599

=== [3156/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.70it/s]
Hypertuning:  91%|█████████▏| 3156/3456 [1:13:13<06:50,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.3562
➡️ Total Profit: ₹46,712.85
➡️ Equity Curve R²: 0.8474
➡️ Monthly Consistency Score: 0.1833

=== [3157/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.72it/s]
Hypertuning:  91%|█████████▏| 3157/3456 [1:13:15<06:47,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4425
➡️ Total Profit: ₹-22,162.01
➡️ Equity Curve R²: 0.8657
➡️ Monthly Consistency Score: -0.0758

=== [3158/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.07it/s]
Hypertuning:  91%|█████████▏| 3158/3456 [1:13:16<06:50,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.3112
➡️ Total Profit: ₹-14,059.92
➡️ Equity Curve R²: 0.6656
➡️ Monthly Consistency Score: -0.0522

=== [3159/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.16it/s]
Hypertuning:  91%|█████████▏| 3159/3456 [1:13:18<06:52,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 0.1999
➡️ Total Profit: ₹5,585.74
➡️ Equity Curve R²: 0.0481
➡️ Monthly Consistency Score: 0.0202

=== [3160/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.06it/s]
Hypertuning:  91%|█████████▏| 3160/3456 [1:13:19<06:45,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2742
➡️ Total Profit: ₹-8,841.26
➡️ Equity Curve R²: 0.4348
➡️ Monthly Consistency Score: -0.0344

=== [3161/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.87it/s]
Hypertuning:  91%|█████████▏| 3161/3456 [1:13:20<06:41,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3115
➡️ Total Profit: ₹-17,380.86
➡️ Equity Curve R²: 0.8141
➡️ Monthly Consistency Score: -0.0577

=== [3162/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.46it/s]
Hypertuning:  91%|█████████▏| 3162/3456 [1:13:22<06:44,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.6197
➡️ Total Profit: ₹21,918.09
➡️ Equity Curve R²: 0.0595
➡️ Monthly Consistency Score: 0.0790

=== [3163/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.16it/s]
Hypertuning:  92%|█████████▏| 3163/3456 [1:13:23<06:37,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.6572
➡️ Total Profit: ₹35,108.53
➡️ Equity Curve R²: 0.4497
➡️ Monthly Consistency Score: 0.1362

=== [3164/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.25it/s]
Hypertuning:  92%|█████████▏| 3164/3456 [1:13:24<06:39,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.0222
➡️ Total Profit: ₹27,797.65
➡️ Equity Curve R²: 0.2121
➡️ Monthly Consistency Score: 0.0974

=== [3165/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.65it/s]
Hypertuning:  92%|█████████▏| 3165/3456 [1:13:26<06:35,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.8557
➡️ Total Profit: ₹43,615.64
➡️ Equity Curve R²: 0.3690
➡️ Monthly Consistency Score: 0.1520

=== [3166/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.79it/s]
Hypertuning:  92%|█████████▏| 3166/3456 [1:13:27<06:38,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.7857
➡️ Total Profit: ₹55,019.53
➡️ Equity Curve R²: 0.0709
➡️ Monthly Consistency Score: 0.2416

=== [3167/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.57it/s]
Hypertuning:  92%|█████████▏| 3167/3456 [1:13:28<06:32,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.9957
➡️ Total Profit: ₹78,155.29
➡️ Equity Curve R²: 0.6146
➡️ Monthly Consistency Score: 0.3378

=== [3168/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 1.75
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.78it/s]
Hypertuning:  92%|█████████▏| 3168/3456 [1:13:30<06:34,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 5.3000
➡️ Total Profit: ₹79,032.96
➡️ Equity Curve R²: 0.8132
➡️ Monthly Consistency Score: 0.3959

=== [3169/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.82it/s]
Hypertuning:  92%|█████████▏| 3169/3456 [1:13:31<06:29,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.6380
➡️ Total Profit: ₹-47,905.29
➡️ Equity Curve R²: 0.9349
➡️ Monthly Consistency Score: -0.2119

=== [3170/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.02it/s]
Hypertuning:  92%|█████████▏| 3170/3456 [1:13:33<06:30,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.2208
➡️ Total Profit: ₹9,733.97
➡️ Equity Curve R²: 0.5867
➡️ Monthly Consistency Score: 0.0414

=== [3171/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.31it/s]
Hypertuning:  92%|█████████▏| 3171/3456 [1:13:34<06:33,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.7304
➡️ Total Profit: ₹14,576.34
➡️ Equity Curve R²: 0.3387
➡️ Monthly Consistency Score: 0.0647

=== [3172/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.25it/s]
Hypertuning:  92%|█████████▏| 3172/3456 [1:13:35<06:26,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.6168
➡️ Total Profit: ₹-23,934.42
➡️ Equity Curve R²: 0.6571
➡️ Monthly Consistency Score: -0.1010

=== [3173/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.53it/s]
Hypertuning:  92%|█████████▏| 3173/3456 [1:13:37<06:32,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 2.2781
➡️ Total Profit: ₹41,373.29
➡️ Equity Curve R²: 0.7710
➡️ Monthly Consistency Score: 0.1544

=== [3174/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.84it/s]
Hypertuning:  92%|█████████▏| 3174/3456 [1:13:38<06:26,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0150
➡️ Total Profit: ₹-491.91
➡️ Equity Curve R²: 0.5467
➡️ Monthly Consistency Score: -0.0018

=== [3175/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.49it/s]
Hypertuning:  92%|█████████▏| 3175/3456 [1:13:39<06:19,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.3339
➡️ Total Profit: ₹28,359.74
➡️ Equity Curve R²: 0.5818
➡️ Monthly Consistency Score: 0.1043

=== [3176/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.26it/s]
Hypertuning:  92%|█████████▏| 3176/3456 [1:13:41<06:21,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4372
➡️ Total Profit: ₹-25,272.66
➡️ Equity Curve R²: 0.6982
➡️ Monthly Consistency Score: -0.0932

=== [3177/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 129.97it/s]
Hypertuning:  92%|█████████▏| 3177/3456 [1:13:42<06:18,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.1963
➡️ Total Profit: ₹28,476.19
➡️ Equity Curve R²: 0.0964
➡️ Monthly Consistency Score: 0.1281

=== [3178/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.42it/s]
Hypertuning:  92%|█████████▏| 3178/3456 [1:13:43<06:21,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3232
➡️ Total Profit: ₹-11,120.88
➡️ Equity Curve R²: 0.1626
➡️ Monthly Consistency Score: -0.0371

=== [3179/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.89it/s]
Hypertuning:  92%|█████████▏| 3179/3456 [1:13:45<06:14,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2677
➡️ Total Profit: ₹12,622.89
➡️ Equity Curve R²: 0.1344
➡️ Monthly Consistency Score: 0.0463

=== [3180/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.11it/s]
Hypertuning:  92%|█████████▏| 3180/3456 [1:13:46<06:17,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.5076
➡️ Total Profit: ₹-26,906.28
➡️ Equity Curve R²: 0.5432
➡️ Monthly Consistency Score: -0.0937

=== [3181/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.09it/s]
Hypertuning:  92%|█████████▏| 3181/3456 [1:13:48<06:14,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.9380
➡️ Total Profit: ₹49,261.68
➡️ Equity Curve R²: 0.1938
➡️ Monthly Consistency Score: 0.1988

=== [3182/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.08it/s]
Hypertuning:  92%|█████████▏| 3182/3456 [1:13:49<06:16,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.4328
➡️ Total Profit: ₹22,536.43
➡️ Equity Curve R²: 0.2920
➡️ Monthly Consistency Score: 0.0878

=== [3183/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.44it/s]
Hypertuning:  92%|█████████▏| 3183/3456 [1:13:50<06:10,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.8733
➡️ Total Profit: ₹35,591.32
➡️ Equity Curve R²: 0.0886
➡️ Monthly Consistency Score: 0.1327

=== [3184/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.19it/s]
Hypertuning:  92%|█████████▏| 3184/3456 [1:13:52<06:13,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.6239
➡️ Total Profit: ₹27,909.07
➡️ Equity Curve R²: 0.0585
➡️ Monthly Consistency Score: 0.1018

=== [3185/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.08it/s]
Hypertuning:  92%|█████████▏| 3185/3456 [1:13:53<06:12,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.5696
➡️ Total Profit: ₹-41,885.90
➡️ Equity Curve R²: 0.8976
➡️ Monthly Consistency Score: -0.1861

=== [3186/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.34it/s]
Hypertuning:  92%|█████████▏| 3186/3456 [1:13:54<06:06,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1336
➡️ Total Profit: ₹6,343.05
➡️ Equity Curve R²: 0.6546
➡️ Monthly Consistency Score: 0.0270

=== [3187/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.14it/s]
Hypertuning:  92%|█████████▏| 3187/3456 [1:13:56<06:06,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2621
➡️ Total Profit: ₹-8,246.40
➡️ Equity Curve R²: 0.6222
➡️ Monthly Consistency Score: -0.0350

=== [3188/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.17it/s]
Hypertuning:  92%|█████████▏| 3188/3456 [1:13:57<06:08,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.5862
➡️ Total Profit: ₹-21,063.46
➡️ Equity Curve R²: 0.5907
➡️ Monthly Consistency Score: -0.0882

=== [3189/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.30it/s]
Hypertuning:  92%|█████████▏| 3189/3456 [1:13:58<06:05,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.3475
➡️ Total Profit: ₹42,634.23
➡️ Equity Curve R²: 0.7819
➡️ Monthly Consistency Score: 0.1578

=== [3190/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.00it/s]
Hypertuning:  92%|█████████▏| 3190/3456 [1:14:00<06:07,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.2898
➡️ Total Profit: ₹-13,617.32
➡️ Equity Curve R²: 0.7464
➡️ Monthly Consistency Score: -0.0503

=== [3191/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.33it/s]
Hypertuning:  92%|█████████▏| 3191/3456 [1:14:01<06:01,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1244
➡️ Total Profit: ₹3,911.11
➡️ Equity Curve R²: 0.3459
➡️ Monthly Consistency Score: 0.0140

=== [3192/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.93it/s]
Hypertuning:  92%|█████████▏| 3192/3456 [1:14:03<06:03,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.4372
➡️ Total Profit: ₹-25,272.66
➡️ Equity Curve R²: 0.6982
➡️ Monthly Consistency Score: -0.0932

=== [3193/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.57it/s]
Hypertuning:  92%|█████████▏| 3193/3456 [1:14:04<06:01,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.1964
➡️ Total Profit: ₹28,478.07
➡️ Equity Curve R²: 0.0874
➡️ Monthly Consistency Score: 0.1280

=== [3194/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.87it/s]
Hypertuning:  92%|█████████▏| 3194/3456 [1:14:05<06:05,  1.40s/it]

➡️ Profit-to-Drawdown Ratio: -0.3241
➡️ Total Profit: ₹-12,248.12
➡️ Equity Curve R²: 0.2269
➡️ Monthly Consistency Score: -0.0401

=== [3195/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.12it/s]
Hypertuning:  92%|█████████▏| 3195/3456 [1:14:07<05:58,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.3023
➡️ Total Profit: ₹14,254.26
➡️ Equity Curve R²: 0.1005
➡️ Monthly Consistency Score: 0.0534

=== [3196/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.96it/s]
Hypertuning:  92%|█████████▏| 3196/3456 [1:14:08<05:51,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3468
➡️ Total Profit: ₹-18,382.64
➡️ Equity Curve R²: 0.3026
➡️ Monthly Consistency Score: -0.0646

=== [3197/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.13it/s]
Hypertuning:  93%|█████████▎| 3197/3456 [1:14:10<05:56,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.0371
➡️ Total Profit: ₹51,780.74
➡️ Equity Curve R²: 0.2386
➡️ Monthly Consistency Score: 0.2099

=== [3198/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.27it/s]
Hypertuning:  93%|█████████▎| 3198/3456 [1:14:11<05:59,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 0.3940
➡️ Total Profit: ₹21,407.35
➡️ Equity Curve R²: 0.3542
➡️ Monthly Consistency Score: 0.0818

=== [3199/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.85it/s]
Hypertuning:  93%|█████████▎| 3199/3456 [1:14:12<05:52,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.0333
➡️ Total Profit: ₹42,111.32
➡️ Equity Curve R²: 0.0803
➡️ Monthly Consistency Score: 0.1589

=== [3200/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.36it/s]
Hypertuning:  93%|█████████▎| 3200/3456 [1:14:14<05:46,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.3167
➡️ Total Profit: ₹43,597.37
➡️ Equity Curve R²: 0.2680
➡️ Monthly Consistency Score: 0.1809

=== [3201/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.58it/s]
Hypertuning:  93%|█████████▎| 3201/3456 [1:14:15<05:51,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.6409
➡️ Total Profit: ₹-52,656.12
➡️ Equity Curve R²: 0.9395
➡️ Monthly Consistency Score: -0.2433

=== [3202/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.14it/s]
Hypertuning:  93%|█████████▎| 3202/3456 [1:14:16<05:47,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.0736
➡️ Total Profit: ₹3,297.41
➡️ Equity Curve R²: 0.6382
➡️ Monthly Consistency Score: 0.0149

=== [3203/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.81it/s]
Hypertuning:  93%|█████████▎| 3203/3456 [1:14:18<05:49,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.4207
➡️ Total Profit: ₹-18,092.42
➡️ Equity Curve R²: 0.6658
➡️ Monthly Consistency Score: -0.0789

=== [3204/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.11it/s]
Hypertuning:  93%|█████████▎| 3204/3456 [1:14:19<05:42,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0141
➡️ Total Profit: ₹-327.95
➡️ Equity Curve R²: 0.0049
➡️ Monthly Consistency Score: -0.0014

=== [3205/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 108.37it/s]
Hypertuning:  93%|█████████▎| 3205/3456 [1:14:20<05:45,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.6939
➡️ Total Profit: ₹16,835.86
➡️ Equity Curve R²: 0.0146
➡️ Monthly Consistency Score: 0.0599

=== [3206/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.27it/s]
Hypertuning:  93%|█████████▎| 3206/3456 [1:14:22<05:39,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0210
➡️ Total Profit: ₹709.93
➡️ Equity Curve R²: 0.5609
➡️ Monthly Consistency Score: 0.0027

=== [3207/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.97it/s]
Hypertuning:  93%|█████████▎| 3207/3456 [1:14:23<05:39,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4512
➡️ Total Profit: ₹10,391.11
➡️ Equity Curve R²: 0.0070
➡️ Monthly Consistency Score: 0.0365

=== [3208/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.22it/s]
Hypertuning:  93%|█████████▎| 3208/3456 [1:14:24<05:33,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6659
➡️ Total Profit: ₹14,588.33
➡️ Equity Curve R²: 0.0914
➡️ Monthly Consistency Score: 0.0594

=== [3209/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.67it/s]
Hypertuning:  93%|█████████▎| 3209/3456 [1:14:26<05:37,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1111
➡️ Total Profit: ₹27,849.48
➡️ Equity Curve R²: 0.0074
➡️ Monthly Consistency Score: 0.1142

=== [3210/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.10it/s]
Hypertuning:  93%|█████████▎| 3210/3456 [1:14:27<05:32,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2618
➡️ Total Profit: ₹8,175.61
➡️ Equity Curve R²: 0.1198
➡️ Monthly Consistency Score: 0.0290

=== [3211/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.18it/s]
Hypertuning:  93%|█████████▎| 3211/3456 [1:14:29<05:34,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4031
➡️ Total Profit: ₹9,953.28
➡️ Equity Curve R²: 0.0510
➡️ Monthly Consistency Score: 0.0407

=== [3212/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.01it/s]
Hypertuning:  93%|█████████▎| 3212/3456 [1:14:30<05:29,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0163
➡️ Total Profit: ₹-863.46
➡️ Equity Curve R²: 0.1484
➡️ Monthly Consistency Score: -0.0032

=== [3213/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.81it/s]
Hypertuning:  93%|█████████▎| 3213/3456 [1:14:31<05:34,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.1858
➡️ Total Profit: ₹55,559.80
➡️ Equity Curve R²: 0.2619
➡️ Monthly Consistency Score: 0.2250

=== [3214/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.36it/s]
Hypertuning:  93%|█████████▎| 3214/3456 [1:14:33<05:36,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 0.6559
➡️ Total Profit: ₹30,445.51
➡️ Equity Curve R²: 0.1536
➡️ Monthly Consistency Score: 0.1238

=== [3215/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.56it/s]
Hypertuning:  93%|█████████▎| 3215/3456 [1:14:34<05:30,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.9949
➡️ Total Profit: ₹71,634.07
➡️ Equity Curve R²: 0.8215
➡️ Monthly Consistency Score: 0.2990

=== [3216/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.25it/s]
Hypertuning:  93%|█████████▎| 3216/3456 [1:14:35<05:25,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.7667
➡️ Total Profit: ₹34,297.25
➡️ Equity Curve R²: 0.0022
➡️ Monthly Consistency Score: 0.1345

=== [3217/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.93it/s]
Hypertuning:  93%|█████████▎| 3217/3456 [1:14:37<05:30,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.6464
➡️ Total Profit: ₹-48,535.76
➡️ Equity Curve R²: 0.9351
➡️ Monthly Consistency Score: -0.2144

=== [3218/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.99it/s]
Hypertuning:  93%|█████████▎| 3218/3456 [1:14:38<05:24,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1902
➡️ Total Profit: ₹8,603.05
➡️ Equity Curve R²: 0.6107
➡️ Monthly Consistency Score: 0.0364

=== [3219/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.99it/s]
Hypertuning:  93%|█████████▎| 3219/3456 [1:14:40<05:25,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.5671
➡️ Total Profit: ₹11,316.34
➡️ Equity Curve R²: 0.1877
➡️ Monthly Consistency Score: 0.0507

=== [3220/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.86it/s]
Hypertuning:  93%|█████████▎| 3220/3456 [1:14:41<05:19,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.6168
➡️ Total Profit: ₹-23,934.42
➡️ Equity Curve R²: 0.6571
➡️ Monthly Consistency Score: -0.1010

=== [3221/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.45it/s]
Hypertuning:  93%|█████████▎| 3221/3456 [1:14:42<05:25,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.2781
➡️ Total Profit: ₹41,373.29
➡️ Equity Curve R²: 0.7710
➡️ Monthly Consistency Score: 0.1544

=== [3222/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.55it/s]
Hypertuning:  93%|█████████▎| 3222/3456 [1:14:44<05:18,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1351
➡️ Total Profit: ₹4,726.25
➡️ Equity Curve R²: 0.5895
➡️ Monthly Consistency Score: 0.0178

=== [3223/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.50it/s]
Hypertuning:  93%|█████████▎| 3223/3456 [1:14:45<05:20,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.3339
➡️ Total Profit: ₹28,359.74
➡️ Equity Curve R²: 0.5818
➡️ Monthly Consistency Score: 0.1043

=== [3224/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.81it/s]
Hypertuning:  93%|█████████▎| 3224/3456 [1:14:46<05:13,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.4372
➡️ Total Profit: ₹-25,272.66
➡️ Equity Curve R²: 0.6982
➡️ Monthly Consistency Score: -0.0932

=== [3225/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.72it/s]
Hypertuning:  93%|█████████▎| 3225/3456 [1:14:48<05:17,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1963
➡️ Total Profit: ₹28,476.19
➡️ Equity Curve R²: 0.0964
➡️ Monthly Consistency Score: 0.1281

=== [3226/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.89it/s]
Hypertuning:  93%|█████████▎| 3226/3456 [1:14:49<05:11,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3232
➡️ Total Profit: ₹-11,120.88
➡️ Equity Curve R²: 0.1626
➡️ Monthly Consistency Score: -0.0371

=== [3227/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.19it/s]
Hypertuning:  93%|█████████▎| 3227/3456 [1:14:51<05:12,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.5245
➡️ Total Profit: ₹24,734.26
➡️ Equity Curve R²: 0.0000
➡️ Monthly Consistency Score: 0.0901

=== [3228/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 105.67it/s]
Hypertuning:  93%|█████████▎| 3228/3456 [1:14:52<05:07,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.5076
➡️ Total Profit: ₹-26,906.28
➡️ Equity Curve R²: 0.5432
➡️ Monthly Consistency Score: -0.0937

=== [3229/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.70it/s]
Hypertuning:  93%|█████████▎| 3229/3456 [1:14:53<05:11,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1864
➡️ Total Profit: ₹42,126.37
➡️ Equity Curve R²: 0.0023
➡️ Monthly Consistency Score: 0.1836

=== [3230/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.10it/s]
Hypertuning:  93%|█████████▎| 3230/3456 [1:14:55<05:08,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4645
➡️ Total Profit: ₹23,663.67
➡️ Equity Curve R²: 0.2666
➡️ Monthly Consistency Score: 0.0929

=== [3231/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.61it/s]
Hypertuning:  93%|█████████▎| 3231/3456 [1:14:56<05:08,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.2576
➡️ Total Profit: ₹58,414.06
➡️ Equity Curve R²: 0.5488
➡️ Monthly Consistency Score: 0.2463

=== [3232/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.29it/s]
Hypertuning:  94%|█████████▎| 3232/3456 [1:14:57<05:02,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6239
➡️ Total Profit: ₹27,909.07
➡️ Equity Curve R²: 0.0585
➡️ Monthly Consistency Score: 0.1018

=== [3233/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.96it/s]
Hypertuning:  94%|█████████▎| 3233/3456 [1:14:59<05:05,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.6446
➡️ Total Profit: ₹-54,484.02
➡️ Equity Curve R²: 0.9337
➡️ Monthly Consistency Score: -0.2420

=== [3234/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.05it/s]
Hypertuning:  94%|█████████▎| 3234/3456 [1:15:00<05:00,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2483
➡️ Total Profit: ₹10,257.57
➡️ Equity Curve R²: 0.5557
➡️ Monthly Consistency Score: 0.0443

=== [3235/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.68it/s]
Hypertuning:  94%|█████████▎| 3235/3456 [1:15:01<05:01,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1899
➡️ Total Profit: ₹4,013.72
➡️ Equity Curve R²: 0.0305
➡️ Monthly Consistency Score: 0.0172

=== [3236/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.39it/s]
Hypertuning:  94%|█████████▎| 3236/3456 [1:15:03<05:03,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.5862
➡️ Total Profit: ₹-21,063.46
➡️ Equity Curve R²: 0.5907
➡️ Monthly Consistency Score: -0.0882

=== [3237/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.45it/s]
Hypertuning:  94%|█████████▎| 3237/3456 [1:15:04<05:00,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.9277
➡️ Total Profit: ₹18,566.45
➡️ Equity Curve R²: 0.0837
➡️ Monthly Consistency Score: 0.0693

=== [3238/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.52it/s]
Hypertuning:  94%|█████████▎| 3238/3456 [1:15:05<04:55,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0052
➡️ Total Profit: ₹206.25
➡️ Equity Curve R²: 0.6731
➡️ Monthly Consistency Score: 0.0008

=== [3239/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.91it/s]
Hypertuning:  94%|█████████▎| 3239/3456 [1:15:07<04:57,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.9418
➡️ Total Profit: ₹18,553.89
➡️ Equity Curve R²: 0.3511
➡️ Monthly Consistency Score: 0.0677

=== [3240/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.81it/s]
Hypertuning:  94%|█████████▍| 3240/3456 [1:15:08<04:51,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.4372
➡️ Total Profit: ₹-25,272.66
➡️ Equity Curve R²: 0.6982
➡️ Monthly Consistency Score: -0.0932

=== [3241/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.95it/s]
Hypertuning:  94%|█████████▍| 3241/3456 [1:15:10<04:55,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.0357
➡️ Total Profit: ₹25,958.07
➡️ Equity Curve R²: 0.0449
➡️ Monthly Consistency Score: 0.1173

=== [3242/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.24it/s]
Hypertuning:  94%|█████████▍| 3242/3456 [1:15:11<04:49,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3241
➡️ Total Profit: ₹-12,248.12
➡️ Equity Curve R²: 0.2269
➡️ Monthly Consistency Score: -0.0401

=== [3243/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.14it/s]
Hypertuning:  94%|█████████▍| 3243/3456 [1:15:12<04:51,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.2625
➡️ Total Profit: ₹12,625.63
➡️ Equity Curve R²: 0.1132
➡️ Monthly Consistency Score: 0.0471

=== [3244/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.53it/s]
Hypertuning:  94%|█████████▍| 3244/3456 [1:15:14<04:46,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3468
➡️ Total Profit: ₹-18,382.64
➡️ Equity Curve R²: 0.3026
➡️ Monthly Consistency Score: -0.0646

=== [3245/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.94it/s]
Hypertuning:  94%|█████████▍| 3245/3456 [1:15:15<04:50,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.0123
➡️ Total Profit: ₹51,151.21
➡️ Equity Curve R²: 0.2530
➡️ Monthly Consistency Score: 0.2088

=== [3246/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.80it/s]
Hypertuning:  94%|█████████▍| 3246/3456 [1:15:16<04:45,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.3453
➡️ Total Profit: ₹19,147.35
➡️ Equity Curve R²: 0.3631
➡️ Monthly Consistency Score: 0.0731

=== [3247/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.97it/s]
Hypertuning:  94%|█████████▍| 3247/3456 [1:15:18<04:46,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.5264
➡️ Total Profit: ₹53,530.91
➡️ Equity Curve R²: 0.5051
➡️ Monthly Consistency Score: 0.2265

=== [3248/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.01it/s]
Hypertuning:  94%|█████████▍| 3248/3456 [1:15:19<04:41,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.6239
➡️ Total Profit: ₹27,909.07
➡️ Equity Curve R²: 0.0585
➡️ Monthly Consistency Score: 0.1018

=== [3249/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.04it/s]
Hypertuning:  94%|█████████▍| 3249/3456 [1:15:21<04:44,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.6562
➡️ Total Profit: ₹-52,304.38
➡️ Equity Curve R²: 0.9401
➡️ Monthly Consistency Score: -0.2371

=== [3250/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.75it/s]
Hypertuning:  94%|█████████▍| 3250/3456 [1:15:22<04:46,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: -0.1556
➡️ Total Profit: ₹-7,387.91
➡️ Equity Curve R²: 0.8212
➡️ Monthly Consistency Score: -0.0310

=== [3251/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.82it/s]
Hypertuning:  94%|█████████▍| 3251/3456 [1:15:23<04:41,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3960
➡️ Total Profit: ₹-15,219.74
➡️ Equity Curve R²: 0.7295
➡️ Monthly Consistency Score: -0.0674

=== [3252/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.49it/s]
Hypertuning:  94%|█████████▍| 3252/3456 [1:15:25<04:35,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3191
➡️ Total Profit: ₹-7,451.64
➡️ Equity Curve R²: 0.0510
➡️ Monthly Consistency Score: -0.0301

=== [3253/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.01it/s]
Hypertuning:  94%|█████████▍| 3253/3456 [1:15:26<04:38,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.1450
➡️ Total Profit: ₹22,957.62
➡️ Equity Curve R²: 0.1987
➡️ Monthly Consistency Score: 0.0831

=== [3254/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.43it/s]
Hypertuning:  94%|█████████▍| 3254/3456 [1:15:27<04:33,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3629
➡️ Total Profit: ₹-17,719.04
➡️ Equity Curve R²: 0.8364
➡️ Monthly Consistency Score: -0.0696

=== [3255/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.60it/s]
Hypertuning:  94%|█████████▍| 3255/3456 [1:15:29<04:34,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1606
➡️ Total Profit: ₹-5,885.79
➡️ Equity Curve R²: 0.5346
➡️ Monthly Consistency Score: -0.0202

=== [3256/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.41it/s]
Hypertuning:  94%|█████████▍| 3256/3456 [1:15:30<04:29,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6167
➡️ Total Profit: ₹-38,659.86
➡️ Equity Curve R²: 0.8318
➡️ Monthly Consistency Score: -0.1419

=== [3257/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.81it/s]
Hypertuning:  94%|█████████▍| 3257/3456 [1:15:31<04:32,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.4141
➡️ Total Profit: ₹12,781.79
➡️ Equity Curve R²: 0.1783
➡️ Monthly Consistency Score: 0.0513

=== [3258/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.89it/s]
Hypertuning:  94%|█████████▍| 3258/3456 [1:15:33<04:28,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.0873
➡️ Total Profit: ₹2,528.37
➡️ Equity Curve R²: 0.0387
➡️ Monthly Consistency Score: 0.0088

=== [3259/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.75it/s]
Hypertuning:  94%|█████████▍| 3259/3456 [1:15:34<04:29,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.1385
➡️ Total Profit: ₹3,436.01
➡️ Equity Curve R²: 0.0637
➡️ Monthly Consistency Score: 0.0138

=== [3260/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.66it/s]
Hypertuning:  94%|█████████▍| 3260/3456 [1:15:35<04:23,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6985
➡️ Total Profit: ₹-38,514.46
➡️ Equity Curve R²: 0.7047
➡️ Monthly Consistency Score: -0.1448

=== [3261/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.49it/s]
Hypertuning:  94%|█████████▍| 3261/3456 [1:15:37<04:27,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.6008
➡️ Total Profit: ₹40,030.18
➡️ Equity Curve R²: 0.0356
➡️ Monthly Consistency Score: 0.1573

=== [3262/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.66it/s]
Hypertuning:  94%|█████████▍| 3262/3456 [1:15:38<04:22,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.7938
➡️ Total Profit: ₹33,015.41
➡️ Equity Curve R²: 0.1619
➡️ Monthly Consistency Score: 0.1277

=== [3263/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.50it/s]
Hypertuning:  94%|█████████▍| 3263/3456 [1:15:40<04:22,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4629
➡️ Total Profit: ₹20,922.69
➡️ Equity Curve R²: 0.3302
➡️ Monthly Consistency Score: 0.0746

=== [3264/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.18it/s]
Hypertuning:  94%|█████████▍| 3264/3456 [1:15:41<04:17,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.6716
➡️ Total Profit: ₹30,044.53
➡️ Equity Curve R²: 0.0225
➡️ Monthly Consistency Score: 0.1099

=== [3265/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.41it/s]
Hypertuning:  94%|█████████▍| 3265/3456 [1:15:42<04:20,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4601
➡️ Total Profit: ₹-33,110.71
➡️ Equity Curve R²: 0.8868
➡️ Monthly Consistency Score: -0.1517

=== [3266/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.20it/s]
Hypertuning:  95%|█████████▍| 3266/3456 [1:15:44<04:16,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4015
➡️ Total Profit: ₹15,717.93
➡️ Equity Curve R²: 0.3396
➡️ Monthly Consistency Score: 0.0741

=== [3267/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.65it/s]
Hypertuning:  95%|█████████▍| 3267/3456 [1:15:45<04:19,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.5653
➡️ Total Profit: ₹-27,031.53
➡️ Equity Curve R²: 0.8811
➡️ Monthly Consistency Score: -0.1016

=== [3268/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 109.64it/s]
Hypertuning:  95%|█████████▍| 3268/3456 [1:15:46<04:13,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.3826
➡️ Total Profit: ₹-12,466.66
➡️ Equity Curve R²: 0.6539
➡️ Monthly Consistency Score: -0.0571

=== [3269/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 109.65it/s]
Hypertuning:  95%|█████████▍| 3269/3456 [1:15:48<04:16,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.7481
➡️ Total Profit: ₹14,044.19
➡️ Equity Curve R²: 0.4710
➡️ Monthly Consistency Score: 0.0573

=== [3270/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.57it/s]
Hypertuning:  95%|█████████▍| 3270/3456 [1:15:49<04:11,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2576
➡️ Total Profit: ₹-8,753.40
➡️ Equity Curve R²: 0.6025
➡️ Monthly Consistency Score: -0.0334

=== [3271/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.21it/s]
Hypertuning:  95%|█████████▍| 3271/3456 [1:15:50<04:11,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.0833
➡️ Total Profit: ₹28,384.85
➡️ Equity Curve R²: 0.4791
➡️ Monthly Consistency Score: 0.1090

=== [3272/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.75it/s]
Hypertuning:  95%|█████████▍| 3272/3456 [1:15:52<04:06,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.2544
➡️ Total Profit: ₹7,895.81
➡️ Equity Curve R²: 0.0508
➡️ Monthly Consistency Score: 0.0324

=== [3273/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.47it/s]
Hypertuning:  95%|█████████▍| 3273/3456 [1:15:53<04:09,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.5803
➡️ Total Profit: ₹36,049.35
➡️ Equity Curve R²: 0.3764
➡️ Monthly Consistency Score: 0.1566

=== [3274/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.25it/s]
Hypertuning:  95%|█████████▍| 3274/3456 [1:15:54<04:05,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2027
➡️ Total Profit: ₹7,135.77
➡️ Equity Curve R²: 0.3274
➡️ Monthly Consistency Score: 0.0252

=== [3275/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.94it/s]
Hypertuning:  95%|█████████▍| 3275/3456 [1:15:56<04:06,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.1132
➡️ Total Profit: ₹26,957.16
➡️ Equity Curve R²: 0.0428
➡️ Monthly Consistency Score: 0.1142

=== [3276/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.15it/s]
Hypertuning:  95%|█████████▍| 3276/3456 [1:15:57<04:02,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.3371
➡️ Total Profit: ₹34,176.55
➡️ Equity Curve R²: 0.1028
➡️ Monthly Consistency Score: 0.1312

=== [3277/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.04it/s]
Hypertuning:  95%|█████████▍| 3277/3456 [1:15:59<04:04,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.1638
➡️ Total Profit: ₹54,522.49
➡️ Equity Curve R²: 0.4405
➡️ Monthly Consistency Score: 0.1988

=== [3278/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.76it/s]
Hypertuning:  95%|█████████▍| 3278/3456 [1:16:00<04:06,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.8886
➡️ Total Profit: ₹37,231.03
➡️ Equity Curve R²: 0.0411
➡️ Monthly Consistency Score: 0.1515

=== [3279/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.71it/s]
Hypertuning:  95%|█████████▍| 3279/3456 [1:16:01<04:01,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.0553
➡️ Total Profit: ₹69,729.20
➡️ Equity Curve R²: 0.7001
➡️ Monthly Consistency Score: 0.3147

=== [3280/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.47it/s]
Hypertuning:  95%|█████████▍| 3280/3456 [1:16:03<03:57,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.2966
➡️ Total Profit: ₹49,996.47
➡️ Equity Curve R²: 0.0341
➡️ Monthly Consistency Score: 0.2212

=== [3281/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.29it/s]
Hypertuning:  95%|█████████▍| 3281/3456 [1:16:04<03:59,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4273
➡️ Total Profit: ₹-27,793.86
➡️ Equity Curve R²: 0.8687
➡️ Monthly Consistency Score: -0.1305

=== [3282/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.78it/s]
Hypertuning:  95%|█████████▍| 3282/3456 [1:16:05<03:56,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5971
➡️ Total Profit: ₹18,594.29
➡️ Equity Curve R²: 0.2037
➡️ Monthly Consistency Score: 0.0827

=== [3283/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.66it/s]
Hypertuning:  95%|█████████▍| 3283/3456 [1:16:07<03:56,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.5350
➡️ Total Profit: ₹-25,792.96
➡️ Equity Curve R²: 0.8253
➡️ Monthly Consistency Score: -0.0999

=== [3284/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.49it/s]
Hypertuning:  95%|█████████▌| 3284/3456 [1:16:08<03:52,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.4351
➡️ Total Profit: ₹-13,852.06
➡️ Equity Curve R²: 0.5739
➡️ Monthly Consistency Score: -0.0631

=== [3285/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.98it/s]
Hypertuning:  95%|█████████▌| 3285/3456 [1:16:10<03:57,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 1.1964
➡️ Total Profit: ₹20,974.66
➡️ Equity Curve R²: 0.6510
➡️ Monthly Consistency Score: 0.0860

=== [3286/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.28it/s]
Hypertuning:  95%|█████████▌| 3286/3456 [1:16:11<03:52,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1977
➡️ Total Profit: ₹-6,493.40
➡️ Equity Curve R²: 0.5643
➡️ Monthly Consistency Score: -0.0243

=== [3287/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.66it/s]
Hypertuning:  95%|█████████▌| 3287/3456 [1:16:12<03:52,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.2133
➡️ Total Profit: ₹39,764.44
➡️ Equity Curve R²: 0.7773
➡️ Monthly Consistency Score: 0.1564

=== [3288/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.54it/s]
Hypertuning:  95%|█████████▌| 3288/3456 [1:16:14<03:47,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3364
➡️ Total Profit: ₹10,031.27
➡️ Equity Curve R²: 0.0091
➡️ Monthly Consistency Score: 0.0410

=== [3289/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.24it/s]
Hypertuning:  95%|█████████▌| 3289/3456 [1:16:15<03:49,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.7736
➡️ Total Profit: ₹40,459.83
➡️ Equity Curve R²: 0.4084
➡️ Monthly Consistency Score: 0.1760

=== [3290/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.64it/s]
Hypertuning:  95%|█████████▌| 3290/3456 [1:16:16<03:44,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3539
➡️ Total Profit: ₹11,657.61
➡️ Equity Curve R²: 0.2477
➡️ Monthly Consistency Score: 0.0412

=== [3291/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.71it/s]
Hypertuning:  95%|█████████▌| 3291/3456 [1:16:18<03:45,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.6316
➡️ Total Profit: ₹20,439.90
➡️ Equity Curve R²: 0.0652
➡️ Monthly Consistency Score: 0.0842

=== [3292/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.20it/s]
Hypertuning:  95%|█████████▌| 3292/3456 [1:16:19<03:41,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.5873
➡️ Total Profit: ₹40,572.01
➡️ Equity Curve R²: 0.3628
➡️ Monthly Consistency Score: 0.1605

=== [3293/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 129.12it/s]
Hypertuning:  95%|█████████▌| 3293/3456 [1:16:20<03:44,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.3131
➡️ Total Profit: ₹32,260.60
➡️ Equity Curve R²: 0.4301
➡️ Monthly Consistency Score: 0.1213

=== [3294/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.38it/s]
Hypertuning:  95%|█████████▌| 3294/3456 [1:16:22<03:40,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.8346
➡️ Total Profit: ₹34,969.19
➡️ Equity Curve R²: 0.0547
➡️ Monthly Consistency Score: 0.1419

=== [3295/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.21it/s]
Hypertuning:  95%|█████████▌| 3295/3456 [1:16:23<03:39,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.1267
➡️ Total Profit: ₹71,360.57
➡️ Equity Curve R²: 0.7312
➡️ Monthly Consistency Score: 0.3238

=== [3296/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 107.85it/s]
Hypertuning:  95%|█████████▌| 3296/3456 [1:16:24<03:35,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.7211
➡️ Total Profit: ₹60,648.29
➡️ Equity Curve R²: 0.3832
➡️ Monthly Consistency Score: 0.2831

=== [3297/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.56it/s]
Hypertuning:  95%|█████████▌| 3297/3456 [1:16:26<03:37,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4294
➡️ Total Profit: ₹-27,507.51
➡️ Equity Curve R²: 0.8789
➡️ Monthly Consistency Score: -0.1338

=== [3298/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.00it/s]
Hypertuning:  95%|█████████▌| 3298/3456 [1:16:27<03:33,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.7706
➡️ Total Profit: ₹21,379.57
➡️ Equity Curve R²: 0.0169
➡️ Monthly Consistency Score: 0.0981

=== [3299/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.86it/s]
Hypertuning:  95%|█████████▌| 3299/3456 [1:16:29<03:33,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4578
➡️ Total Profit: ₹-18,880.28
➡️ Equity Curve R²: 0.7559
➡️ Monthly Consistency Score: -0.0825

=== [3300/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.55it/s]
Hypertuning:  95%|█████████▌| 3300/3456 [1:16:30<03:29,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.1603
➡️ Total Profit: ₹-4,594.84
➡️ Equity Curve R²: 0.1101
➡️ Monthly Consistency Score: -0.0221

=== [3301/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.71it/s]
Hypertuning:  96%|█████████▌| 3301/3456 [1:16:31<03:31,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.0825
➡️ Total Profit: ₹20,341.37
➡️ Equity Curve R²: 0.6442
➡️ Monthly Consistency Score: 0.0828

=== [3302/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.89it/s]
Hypertuning:  96%|█████████▌| 3302/3456 [1:16:33<03:28,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.0828
➡️ Total Profit: ₹2,532.13
➡️ Equity Curve R²: 0.3903
➡️ Monthly Consistency Score: 0.0105

=== [3303/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.38it/s]
Hypertuning:  96%|█████████▌| 3303/3456 [1:16:34<03:28,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.1227
➡️ Total Profit: ₹38,136.55
➡️ Equity Curve R²: 0.7786
➡️ Monthly Consistency Score: 0.1463

=== [3304/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.18it/s]
Hypertuning:  96%|█████████▌| 3304/3456 [1:16:35<03:24,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.5506
➡️ Total Profit: ₹16,419.45
➡️ Equity Curve R²: 0.0039
➡️ Monthly Consistency Score: 0.0656

=== [3305/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.46it/s]
Hypertuning:  96%|█████████▌| 3305/3456 [1:16:37<03:25,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.4714
➡️ Total Profit: ₹35,418.88
➡️ Equity Curve R²: 0.2178
➡️ Monthly Consistency Score: 0.1439

=== [3306/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.23it/s]
Hypertuning:  96%|█████████▌| 3306/3456 [1:16:38<03:26,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.0859
➡️ Total Profit: ₹26,344.85
➡️ Equity Curve R²: 0.0338
➡️ Monthly Consistency Score: 0.0968

=== [3307/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.83it/s]
Hypertuning:  96%|█████████▌| 3307/3456 [1:16:39<03:22,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.1058
➡️ Total Profit: ₹-3,423.83
➡️ Equity Curve R²: 0.5128
➡️ Monthly Consistency Score: -0.0145

=== [3308/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.37it/s]
Hypertuning:  96%|█████████▌| 3308/3456 [1:16:41<03:19,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.8021
➡️ Total Profit: ₹18,794.83
➡️ Equity Curve R²: 0.0268
➡️ Monthly Consistency Score: 0.0719

=== [3309/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.79it/s]
Hypertuning:  96%|█████████▌| 3309/3456 [1:16:42<03:20,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.7173
➡️ Total Profit: ₹63,336.85
➡️ Equity Curve R²: 0.5965
➡️ Monthly Consistency Score: 0.2324

=== [3310/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.24it/s]
Hypertuning:  96%|█████████▌| 3310/3456 [1:16:43<03:16,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.8346
➡️ Total Profit: ₹34,969.19
➡️ Equity Curve R²: 0.0617
➡️ Monthly Consistency Score: 0.1460

=== [3311/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.52it/s]
Hypertuning:  96%|█████████▌| 3311/3456 [1:16:45<03:17,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.9125
➡️ Total Profit: ₹66,471.94
➡️ Equity Curve R²: 0.7563
➡️ Monthly Consistency Score: 0.3157

=== [3312/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.75it/s]
Hypertuning:  96%|█████████▌| 3312/3456 [1:16:46<03:18,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.5819
➡️ Total Profit: ₹54,256.47
➡️ Equity Curve R²: 0.1203
➡️ Monthly Consistency Score: 0.2330

=== [3313/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.72it/s]
Hypertuning:  96%|█████████▌| 3313/3456 [1:16:48<03:16,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4513
➡️ Total Profit: ₹-32,481.18
➡️ Equity Curve R²: 0.8864
➡️ Monthly Consistency Score: -0.1485

=== [3314/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.22it/s]
Hypertuning:  96%|█████████▌| 3314/3456 [1:16:49<03:12,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.4015
➡️ Total Profit: ₹15,717.93
➡️ Equity Curve R²: 0.3396
➡️ Monthly Consistency Score: 0.0741

=== [3315/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.17it/s]
Hypertuning:  96%|█████████▌| 3315/3456 [1:16:50<03:12,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.5415
➡️ Total Profit: ₹-24,554.27
➡️ Equity Curve R²: 0.8391
➡️ Monthly Consistency Score: -0.0936

=== [3316/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.97it/s]
Hypertuning:  96%|█████████▌| 3316/3456 [1:16:52<03:07,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.5182
➡️ Total Profit: ₹-21,638.48
➡️ Equity Curve R²: 0.8166
➡️ Monthly Consistency Score: -0.0955

=== [3317/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.03it/s]
Hypertuning:  96%|█████████▌| 3317/3456 [1:16:53<03:09,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.7481
➡️ Total Profit: ₹14,044.19
➡️ Equity Curve R²: 0.4710
➡️ Monthly Consistency Score: 0.0573

=== [3318/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.59it/s]
Hypertuning:  96%|█████████▌| 3318/3456 [1:16:54<03:06,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.0290
➡️ Total Profit: ₹986.61
➡️ Equity Curve R²: 0.5734
➡️ Monthly Consistency Score: 0.0037

=== [3319/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.99it/s]
Hypertuning:  96%|█████████▌| 3319/3456 [1:16:56<03:06,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.0833
➡️ Total Profit: ₹28,384.85
➡️ Equity Curve R²: 0.4791
➡️ Monthly Consistency Score: 0.1090

=== [3320/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.14it/s]
Hypertuning:  96%|█████████▌| 3320/3456 [1:16:57<03:02,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.2544
➡️ Total Profit: ₹7,895.81
➡️ Equity Curve R²: 0.0508
➡️ Monthly Consistency Score: 0.0324

=== [3321/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.49it/s]
Hypertuning:  96%|█████████▌| 3321/3456 [1:16:58<03:04,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.5803
➡️ Total Profit: ₹36,049.35
➡️ Equity Curve R²: 0.3764
➡️ Monthly Consistency Score: 0.1566

=== [3322/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.07it/s]
Hypertuning:  96%|█████████▌| 3322/3456 [1:17:00<03:01,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2027
➡️ Total Profit: ₹7,135.77
➡️ Equity Curve R²: 0.3274
➡️ Monthly Consistency Score: 0.0252

=== [3323/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.83it/s]
Hypertuning:  96%|█████████▌| 3323/3456 [1:17:01<03:00,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.1132
➡️ Total Profit: ₹26,957.16
➡️ Equity Curve R²: 0.0428
➡️ Monthly Consistency Score: 0.1142

=== [3324/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.33it/s]
Hypertuning:  96%|█████████▌| 3324/3456 [1:17:02<02:57,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.3371
➡️ Total Profit: ₹34,176.55
➡️ Equity Curve R²: 0.1028
➡️ Monthly Consistency Score: 0.1312

=== [3325/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.18it/s]
Hypertuning:  96%|█████████▌| 3325/3456 [1:17:04<02:59,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.1638
➡️ Total Profit: ₹54,522.49
➡️ Equity Curve R²: 0.4405
➡️ Monthly Consistency Score: 0.1988

=== [3326/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.33it/s]
Hypertuning:  96%|█████████▌| 3326/3456 [1:17:05<02:56,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.8886
➡️ Total Profit: ₹37,231.03
➡️ Equity Curve R²: 0.0411
➡️ Monthly Consistency Score: 0.1515

=== [3327/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.75it/s]
Hypertuning:  96%|█████████▋| 3327/3456 [1:17:07<02:56,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 3.0553
➡️ Total Profit: ₹69,729.20
➡️ Equity Curve R²: 0.7001
➡️ Monthly Consistency Score: 0.3147

=== [3328/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.76it/s]
Hypertuning:  96%|█████████▋| 3328/3456 [1:17:08<02:52,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.2966
➡️ Total Profit: ₹49,996.47
➡️ Equity Curve R²: 0.0341
➡️ Monthly Consistency Score: 0.2212

=== [3329/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 130.64it/s]
Hypertuning:  96%|█████████▋| 3329/3456 [1:17:09<02:54,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.5141
➡️ Total Profit: ₹-35,704.00
➡️ Equity Curve R²: 0.9000
➡️ Monthly Consistency Score: -0.1746

=== [3330/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.57it/s]
Hypertuning:  96%|█████████▋| 3330/3456 [1:17:11<02:51,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1467
➡️ Total Profit: ₹6,072.45
➡️ Equity Curve R²: 0.5544
➡️ Monthly Consistency Score: 0.0273

=== [3331/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.95it/s]
Hypertuning:  96%|█████████▋| 3331/3456 [1:17:12<02:52,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.5712
➡️ Total Profit: ₹-25,792.96
➡️ Equity Curve R²: 0.8248
➡️ Monthly Consistency Score: -0.1077

=== [3332/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 129.93it/s]
Hypertuning:  96%|█████████▋| 3332/3456 [1:17:13<02:48,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3230
➡️ Total Profit: ₹-9,595.70
➡️ Equity Curve R²: 0.4657
➡️ Monthly Consistency Score: -0.0443

=== [3333/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.62it/s]
Hypertuning:  96%|█████████▋| 3333/3456 [1:17:15<02:46,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.9476
➡️ Total Profit: ₹17,193.72
➡️ Equity Curve R²: 0.5521
➡️ Monthly Consistency Score: 0.0706

=== [3334/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.31it/s]
Hypertuning:  96%|█████████▋| 3334/3456 [1:17:16<02:46,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.1870
➡️ Total Profit: ₹5,506.61
➡️ Equity Curve R²: 0.4276
➡️ Monthly Consistency Score: 0.0218

=== [3335/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.01it/s]
Hypertuning:  96%|█████████▋| 3335/3456 [1:17:17<02:42,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.0319
➡️ Total Profit: ₹36,504.44
➡️ Equity Curve R²: 0.7404
➡️ Monthly Consistency Score: 0.1443

=== [3336/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.09it/s]
Hypertuning:  97%|█████████▋| 3336/3456 [1:17:19<02:42,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2545
➡️ Total Profit: ₹7,899.45
➡️ Equity Curve R²: 0.0449
➡️ Monthly Consistency Score: 0.0324

=== [3337/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.78it/s]
Hypertuning:  97%|█████████▋| 3337/3456 [1:17:20<02:44,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 1.6079
➡️ Total Profit: ₹36,679.82
➡️ Equity Curve R²: 0.3346
➡️ Monthly Consistency Score: 0.1607

=== [3338/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.03it/s]
Hypertuning:  97%|█████████▋| 3338/3456 [1:17:22<02:41,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.3309
➡️ Total Profit: ₹10,524.85
➡️ Equity Curve R²: 0.2098
➡️ Monthly Consistency Score: 0.0390

=== [3339/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.37it/s]
Hypertuning:  97%|█████████▋| 3339/3456 [1:17:23<02:37,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0599
➡️ Total Profit: ₹-1,800.68
➡️ Equity Curve R²: 0.4608
➡️ Monthly Consistency Score: -0.0074

=== [3340/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.67it/s]
Hypertuning:  97%|█████████▋| 3340/3456 [1:17:24<02:38,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.6706
➡️ Total Profit: ₹42,700.19
➡️ Equity Curve R²: 0.3422
➡️ Monthly Consistency Score: 0.1669

=== [3341/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.12it/s]
Hypertuning:  97%|█████████▋| 3341/3456 [1:17:26<02:36,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.2874
➡️ Total Profit: ₹31,630.13
➡️ Equity Curve R²: 0.3933
➡️ Monthly Consistency Score: 0.1200

=== [3342/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.53it/s]
Hypertuning:  97%|█████████▋| 3342/3456 [1:17:27<02:36,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.8390
➡️ Total Profit: ₹36,100.11
➡️ Equity Curve R²: 0.0698
➡️ Monthly Consistency Score: 0.1509

=== [3343/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.49it/s]
Hypertuning:  97%|█████████▋| 3343/3456 [1:17:28<02:32,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.9125
➡️ Total Profit: ₹66,471.94
➡️ Equity Curve R²: 0.7199
➡️ Monthly Consistency Score: 0.3065

=== [3344/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.41it/s]
Hypertuning:  97%|█████████▋| 3344/3456 [1:17:30<02:32,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.3518
➡️ Total Profit: ₹52,124.65
➡️ Equity Curve R²: 0.0185
➡️ Monthly Consistency Score: 0.2296

=== [3345/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.05it/s]
Hypertuning:  97%|█████████▋| 3345/3456 [1:17:31<02:30,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.6084
➡️ Total Profit: ₹-39,194.83
➡️ Equity Curve R²: 0.8660
➡️ Monthly Consistency Score: -0.1847

=== [3346/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.87it/s]
Hypertuning:  97%|█████████▋| 3346/3456 [1:17:32<02:29,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0791
➡️ Total Profit: ₹2,688.73
➡️ Equity Curve R²: 0.5250
➡️ Monthly Consistency Score: 0.0117

=== [3347/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.60it/s]
Hypertuning:  97%|█████████▋| 3347/3456 [1:17:34<02:29,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.5018
➡️ Total Profit: ₹-22,524.86
➡️ Equity Curve R²: 0.7020
➡️ Monthly Consistency Score: -0.0890

=== [3348/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.69it/s]
Hypertuning:  97%|█████████▋| 3348/3456 [1:17:35<02:26,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4852
➡️ Total Profit: ₹-16,630.34
➡️ Equity Curve R²: 0.4175
➡️ Monthly Consistency Score: -0.0743

=== [3349/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.65it/s]
Hypertuning:  97%|█████████▋| 3349/3456 [1:17:37<02:26,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.0360
➡️ Total Profit: ₹21,425.01
➡️ Equity Curve R²: 0.5954
➡️ Monthly Consistency Score: 0.0863

=== [3350/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.38it/s]
Hypertuning:  97%|█████████▋| 3350/3456 [1:17:38<02:25,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.3547
➡️ Total Profit: ₹-12,420.52
➡️ Equity Curve R²: 0.6803
➡️ Monthly Consistency Score: -0.0570

=== [3351/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.53it/s]
Hypertuning:  97%|█████████▋| 3351/3456 [1:17:39<02:22,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2618
➡️ Total Profit: ₹5,593.44
➡️ Equity Curve R²: 0.2973
➡️ Monthly Consistency Score: 0.0214

=== [3352/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.94it/s]
Hypertuning:  97%|█████████▋| 3352/3456 [1:17:41<02:21,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.4079
➡️ Total Profit: ₹12,163.09
➡️ Equity Curve R²: 0.0053
➡️ Monthly Consistency Score: 0.0488

=== [3353/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.65it/s]
Hypertuning:  97%|█████████▋| 3353/3456 [1:17:42<02:19,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.6960
➡️ Total Profit: ₹20,352.13
➡️ Equity Curve R²: 0.0011
➡️ Monthly Consistency Score: 0.0799

=== [3354/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.13it/s]
Hypertuning:  97%|█████████▋| 3354/3456 [1:17:43<02:19,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.0621
➡️ Total Profit: ₹23,999.29
➡️ Equity Curve R²: 0.1485
➡️ Monthly Consistency Score: 0.0929

=== [3355/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.82it/s]
Hypertuning:  97%|█████████▋| 3355/3456 [1:17:45<02:16,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.5211
➡️ Total Profit: ₹10,312.30
➡️ Equity Curve R²: 0.0522
➡️ Monthly Consistency Score: 0.0410

=== [3356/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.54it/s]
Hypertuning:  97%|█████████▋| 3356/3456 [1:17:46<02:15,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3362
➡️ Total Profit: ₹-9,368.90
➡️ Equity Curve R²: 0.3467
➡️ Monthly Consistency Score: -0.0360

=== [3357/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.89it/s]
Hypertuning:  97%|█████████▋| 3357/3456 [1:17:47<02:14,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.8670
➡️ Total Profit: ₹42,339.66
➡️ Equity Curve R²: 0.5395
➡️ Monthly Consistency Score: 0.1653

=== [3358/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.43it/s]
Hypertuning:  97%|█████████▋| 3358/3456 [1:17:49<02:15,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.9157
➡️ Total Profit: ₹38,363.79
➡️ Equity Curve R²: 0.0566
➡️ Monthly Consistency Score: 0.1613

=== [3359/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.34it/s]
Hypertuning:  97%|█████████▋| 3359/3456 [1:17:50<02:11,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.1985
➡️ Total Profit: ₹50,174.67
➡️ Equity Curve R²: 0.4482
➡️ Monthly Consistency Score: 0.2115

=== [3360/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.25
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.13it/s]
Hypertuning:  97%|█████████▋| 3360/3456 [1:17:52<02:10,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.4311
➡️ Total Profit: ₹52,131.93
➡️ Equity Curve R²: 0.1086
➡️ Monthly Consistency Score: 0.2334

=== [3361/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.41it/s]
Hypertuning:  97%|█████████▋| 3361/3456 [1:17:53<02:08,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.4650
➡️ Total Profit: ₹-32,064.10
➡️ Equity Curve R²: 0.8740
➡️ Monthly Consistency Score: -0.1500

=== [3362/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.72it/s]
Hypertuning:  97%|█████████▋| 3362/3456 [1:17:54<02:08,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0733
➡️ Total Profit: ₹-3,754.23
➡️ Equity Curve R²: 0.7448
➡️ Monthly Consistency Score: -0.0148

=== [3363/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 129.16it/s]
Hypertuning:  97%|█████████▋| 3363/3456 [1:17:56<02:04,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.0001
➡️ Total Profit: ₹27,685.57
➡️ Equity Curve R²: 0.0145
➡️ Monthly Consistency Score: 0.0997

=== [3364/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.20it/s]
Hypertuning:  97%|█████████▋| 3364/3456 [1:17:57<02:04,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.1159
➡️ Total Profit: ₹36,801.89
➡️ Equity Curve R²: 0.4217
➡️ Monthly Consistency Score: 0.1449

=== [3365/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.82it/s]
Hypertuning:  97%|█████████▋| 3365/3456 [1:17:58<02:02,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0630
➡️ Total Profit: ₹-2,004.33
➡️ Equity Curve R²: 0.5398
➡️ Monthly Consistency Score: -0.0078

=== [3366/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.02it/s]
Hypertuning:  97%|█████████▋| 3366/3456 [1:18:00<02:02,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4737
➡️ Total Profit: ₹-25,272.92
➡️ Equity Curve R²: 0.8594
➡️ Monthly Consistency Score: -0.0917

=== [3367/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.92it/s]
Hypertuning:  97%|█████████▋| 3367/3456 [1:18:01<02:02,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.4911
➡️ Total Profit: ₹13,720.22
➡️ Equity Curve R²: 0.0816
➡️ Monthly Consistency Score: 0.0509

=== [3368/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.93it/s]
Hypertuning:  97%|█████████▋| 3368/3456 [1:18:02<01:59,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.2032
➡️ Total Profit: ₹-4,575.94
➡️ Equity Curve R²: 0.0127
➡️ Monthly Consistency Score: -0.0174

=== [3369/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.57it/s]
Hypertuning:  97%|█████████▋| 3369/3456 [1:18:04<02:00,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.0570
➡️ Total Profit: ₹-2,901.67
➡️ Equity Curve R²: 0.6246
➡️ Monthly Consistency Score: -0.0104

=== [3370/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.55it/s]
Hypertuning:  98%|█████████▊| 3370/3456 [1:18:05<01:57,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0469
➡️ Total Profit: ₹2,357.89
➡️ Equity Curve R²: 0.5856
➡️ Monthly Consistency Score: 0.0086

=== [3371/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.91it/s]
Hypertuning:  98%|█████████▊| 3371/3456 [1:18:06<01:54,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.3055
➡️ Total Profit: ₹48,843.05
➡️ Equity Curve R²: 0.5925
➡️ Monthly Consistency Score: 0.1901

=== [3372/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.03it/s]
Hypertuning:  98%|█████████▊| 3372/3456 [1:18:08<01:53,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.0533
➡️ Total Profit: ₹43,179.37
➡️ Equity Curve R²: 0.4257
➡️ Monthly Consistency Score: 0.1627

=== [3373/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.35it/s]
Hypertuning:  98%|█████████▊| 3373/3456 [1:18:09<01:54,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 2.1687
➡️ Total Profit: ₹47,809.02
➡️ Equity Curve R²: 0.4267
➡️ Monthly Consistency Score: 0.1686

=== [3374/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.52it/s]
Hypertuning:  98%|█████████▊| 3374/3456 [1:18:11<01:51,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 3.5584
➡️ Total Profit: ₹80,401.26
➡️ Equity Curve R²: 0.5097
➡️ Monthly Consistency Score: 0.3484

=== [3375/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.00it/s]
Hypertuning:  98%|█████████▊| 3375/3456 [1:18:12<01:48,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 2.3947
➡️ Total Profit: ₹69,823.92
➡️ Equity Curve R²: 0.2775
➡️ Monthly Consistency Score: 0.3099

=== [3376/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.72it/s]
Hypertuning:  98%|█████████▊| 3376/3456 [1:18:13<01:48,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.6808
➡️ Total Profit: ₹47,868.29
➡️ Equity Curve R²: 0.0829
➡️ Monthly Consistency Score: 0.1940

=== [3377/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.63it/s]
Hypertuning:  98%|█████████▊| 3377/3456 [1:18:15<01:46,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.4202
➡️ Total Profit: ₹-27,655.51
➡️ Equity Curve R²: 0.8571
➡️ Monthly Consistency Score: -0.1305

=== [3378/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.31it/s]
Hypertuning:  98%|█████████▊| 3378/3456 [1:18:16<01:46,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0305
➡️ Total Profit: ₹-1,494.23
➡️ Equity Curve R²: 0.7062
➡️ Monthly Consistency Score: -0.0057

=== [3379/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.83it/s]
Hypertuning:  98%|█████████▊| 3379/3456 [1:18:17<01:47,  1.40s/it]

➡️ Profit-to-Drawdown Ratio: 1.1803
➡️ Total Profit: ₹36,224.14
➡️ Equity Curve R²: 0.2179
➡️ Monthly Consistency Score: 0.1387

=== [3380/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.29it/s]
Hypertuning:  98%|█████████▊| 3380/3456 [1:18:19<01:44,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.2899
➡️ Total Profit: ₹42,543.61
➡️ Equity Curve R²: 0.5603
➡️ Monthly Consistency Score: 0.1618

=== [3381/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.59it/s]
Hypertuning:  98%|█████████▊| 3381/3456 [1:18:20<01:42,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0242
➡️ Total Profit: ₹-744.33
➡️ Equity Curve R²: 0.4797
➡️ Monthly Consistency Score: -0.0029

=== [3382/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.06it/s]
Hypertuning:  98%|█████████▊| 3382/3456 [1:18:22<01:41,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.4623
➡️ Total Profit: ₹-24,143.84
➡️ Equity Curve R²: 0.8417
➡️ Monthly Consistency Score: -0.0868

=== [3383/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.77it/s]
Hypertuning:  98%|█████████▊| 3383/3456 [1:18:23<01:39,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.5833
➡️ Total Profit: ₹15,348.85
➡️ Equity Curve R²: 0.1384
➡️ Monthly Consistency Score: 0.0574

=== [3384/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.65it/s]
Hypertuning:  98%|█████████▊| 3384/3456 [1:18:24<01:38,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4218
➡️ Total Profit: ₹-13,095.94
➡️ Equity Curve R²: 0.2385
➡️ Monthly Consistency Score: -0.0508

=== [3385/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.88it/s]
Hypertuning:  98%|█████████▊| 3385/3456 [1:18:26<01:38,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 0.6569
➡️ Total Profit: ₹19,030.68
➡️ Equity Curve R²: 0.0117
➡️ Monthly Consistency Score: 0.0684

=== [3386/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.54it/s]
Hypertuning:  98%|█████████▊| 3386/3456 [1:18:27<01:37,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 0.5255
➡️ Total Profit: ₹21,830.69
➡️ Equity Curve R²: 0.1083
➡️ Monthly Consistency Score: 0.0788

=== [3387/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.11it/s]
Hypertuning:  98%|█████████▊| 3387/3456 [1:18:28<01:34,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.3055
➡️ Total Profit: ₹48,843.05
➡️ Equity Curve R²: 0.5925
➡️ Monthly Consistency Score: 0.1901

=== [3388/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.14it/s]
Hypertuning:  98%|█████████▊| 3388/3456 [1:18:30<01:33,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.0839
➡️ Total Profit: ₹29,439.37
➡️ Equity Curve R²: 0.0408
➡️ Monthly Consistency Score: 0.1163

=== [3389/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.54it/s]
Hypertuning:  98%|█████████▊| 3389/3456 [1:18:31<01:31,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.7495
➡️ Total Profit: ₹38,570.00
➡️ Equity Curve R²: 0.4505
➡️ Monthly Consistency Score: 0.1366

=== [3390/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.05it/s]
Hypertuning:  98%|█████████▊| 3390/3456 [1:18:33<01:30,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 3.2803
➡️ Total Profit: ₹81,530.34
➡️ Equity Curve R²: 0.4790
➡️ Monthly Consistency Score: 0.3441

=== [3391/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.32it/s]
Hypertuning:  98%|█████████▊| 3391/3456 [1:18:34<01:28,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 4.6622
➡️ Total Profit: ₹91,192.55
➡️ Equity Curve R²: 0.7344
➡️ Monthly Consistency Score: 0.3904

=== [3392/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.30it/s]
Hypertuning:  98%|█████████▊| 3392/3456 [1:18:35<01:27,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.6808
➡️ Total Profit: ₹47,868.29
➡️ Equity Curve R²: 0.0829
➡️ Monthly Consistency Score: 0.1940

=== [3393/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.65it/s]
Hypertuning:  98%|█████████▊| 3393/3456 [1:18:37<01:25,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4246
➡️ Total Profit: ₹-26,459.96
➡️ Equity Curve R²: 0.8660
➡️ Monthly Consistency Score: -0.1320

=== [3394/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.08it/s]
Hypertuning:  98%|█████████▊| 3394/3456 [1:18:38<01:25,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1220
➡️ Total Profit: ₹-6,187.19
➡️ Equity Curve R²: 0.7739
➡️ Monthly Consistency Score: -0.0247

=== [3395/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.99it/s]
Hypertuning:  98%|█████████▊| 3395/3456 [1:18:39<01:24,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 1.3513
➡️ Total Profit: ₹37,072.65
➡️ Equity Curve R²: 0.4466
➡️ Monthly Consistency Score: 0.1626

=== [3396/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.15it/s]
Hypertuning:  98%|█████████▊| 3396/3456 [1:18:41<01:21,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.0513
➡️ Total Profit: ₹34,673.51
➡️ Equity Curve R²: 0.3767
➡️ Monthly Consistency Score: 0.1344

=== [3397/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.68it/s]
Hypertuning:  98%|█████████▊| 3397/3456 [1:18:42<01:20,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0163
➡️ Total Profit: ₹511.91
➡️ Equity Curve R²: 0.4783
➡️ Monthly Consistency Score: 0.0020

=== [3398/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 116.75it/s]
Hypertuning:  98%|█████████▊| 3398/3456 [1:18:43<01:19,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.3886
➡️ Total Profit: ₹-19,278.32
➡️ Equity Curve R²: 0.8315
➡️ Monthly Consistency Score: -0.0717

=== [3399/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.66it/s]
Hypertuning:  98%|█████████▊| 3399/3456 [1:18:45<01:16,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2431
➡️ Total Profit: ₹5,609.59
➡️ Equity Curve R²: 0.0443
➡️ Monthly Consistency Score: 0.0215

=== [3400/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.21it/s]
Hypertuning:  98%|█████████▊| 3400/3456 [1:18:46<01:16,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4095
➡️ Total Profit: ₹-10,967.76
➡️ Equity Curve R²: 0.1386
➡️ Monthly Consistency Score: -0.0429

=== [3401/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.59it/s]
Hypertuning:  98%|█████████▊| 3401/3456 [1:18:47<01:14,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.7143
➡️ Total Profit: ₹20,286.92
➡️ Equity Curve R²: 0.0070
➡️ Monthly Consistency Score: 0.0732

=== [3402/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.23it/s]
Hypertuning:  98%|█████████▊| 3402/3456 [1:18:49<01:13,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2180
➡️ Total Profit: ₹9,397.93
➡️ Equity Curve R²: 0.3765
➡️ Monthly Consistency Score: 0.0329

=== [3403/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.36it/s]
Hypertuning:  98%|█████████▊| 3403/3456 [1:18:50<01:11,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.6570
➡️ Total Profit: ₹35,105.79
➡️ Equity Curve R²: 0.5497
➡️ Monthly Consistency Score: 0.1346

=== [3404/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.92it/s]
Hypertuning:  98%|█████████▊| 3404/3456 [1:18:52<01:10,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.3029
➡️ Total Profit: ₹9,311.18
➡️ Equity Curve R²: 0.1428
➡️ Monthly Consistency Score: 0.0358

=== [3405/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 128.08it/s]
Hypertuning:  99%|█████████▊| 3405/3456 [1:18:53<01:10,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 1.5618
➡️ Total Profit: ₹35,418.59
➡️ Equity Curve R²: 0.4512
➡️ Monthly Consistency Score: 0.1219

=== [3406/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.48it/s]
Hypertuning:  99%|█████████▊| 3406/3456 [1:18:54<01:08,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.0052
➡️ Total Profit: ₹61,792.18
➡️ Equity Curve R²: 0.1310
➡️ Monthly Consistency Score: 0.2744

=== [3407/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.24it/s]
Hypertuning:  99%|█████████▊| 3407/3456 [1:18:56<01:06,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 4.4124
➡️ Total Profit: ₹86,306.66
➡️ Equity Curve R²: 0.7224
➡️ Monthly Consistency Score: 0.3734

=== [3408/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 10
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 132.92it/s]
Hypertuning:  99%|█████████▊| 3408/3456 [1:18:57<01:05,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.5311
➡️ Total Profit: ₹43,604.65
➡️ Equity Curve R²: 0.0677
➡️ Monthly Consistency Score: 0.1734

=== [3409/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.73it/s]
Hypertuning:  99%|█████████▊| 3409/3456 [1:18:58<01:03,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.4467
➡️ Total Profit: ₹-30,804.10
➡️ Equity Curve R²: 0.8722
➡️ Monthly Consistency Score: -0.1436

=== [3410/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.09it/s]
Hypertuning:  99%|█████████▊| 3410/3456 [1:19:00<01:02,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0305
➡️ Total Profit: ₹-1,494.23
➡️ Equity Curve R²: 0.7181
➡️ Monthly Consistency Score: -0.0058

=== [3411/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.92it/s]
Hypertuning:  99%|█████████▊| 3411/3456 [1:19:01<01:00,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.0001
➡️ Total Profit: ₹27,685.57
➡️ Equity Curve R²: 0.0145
➡️ Monthly Consistency Score: 0.0997

=== [3412/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.82it/s]
Hypertuning:  99%|█████████▊| 3412/3456 [1:19:02<00:59,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.7488
➡️ Total Profit: ₹48,931.80
➡️ Equity Curve R²: 0.7052
➡️ Monthly Consistency Score: 0.1915

=== [3413/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.37it/s]
Hypertuning:  99%|█████████▉| 3413/3456 [1:19:04<00:58,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0432
➡️ Total Profit: ₹-1,373.86
➡️ Equity Curve R²: 0.5380
➡️ Monthly Consistency Score: -0.0054

=== [3414/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.99it/s]
Hypertuning:  99%|█████████▉| 3414/3456 [1:19:05<00:57,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4737
➡️ Total Profit: ₹-25,272.92
➡️ Equity Curve R²: 0.8594
➡️ Monthly Consistency Score: -0.0917

=== [3415/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.62it/s]
Hypertuning:  99%|█████████▉| 3415/3456 [1:19:06<00:55,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 0.4911
➡️ Total Profit: ₹13,720.22
➡️ Equity Curve R²: 0.0816
➡️ Monthly Consistency Score: 0.0509

=== [3416/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 131.61it/s]
Hypertuning:  99%|█████████▉| 3416/3456 [1:19:08<00:54,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2032
➡️ Total Profit: ₹-4,575.94
➡️ Equity Curve R²: 0.0127
➡️ Monthly Consistency Score: -0.0174

=== [3417/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.90it/s]
Hypertuning:  99%|█████████▉| 3417/3456 [1:19:09<00:52,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.0570
➡️ Total Profit: ₹-2,901.67
➡️ Equity Curve R²: 0.6246
➡️ Monthly Consistency Score: -0.0104

=== [3418/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.81it/s]
Hypertuning:  99%|█████████▉| 3418/3456 [1:19:11<00:51,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.0469
➡️ Total Profit: ₹2,359.73
➡️ Equity Curve R²: 0.5855
➡️ Monthly Consistency Score: 0.0086

=== [3419/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.09it/s]
Hypertuning:  99%|█████████▉| 3419/3456 [1:19:12<00:49,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.3055
➡️ Total Profit: ₹48,843.05
➡️ Equity Curve R²: 0.5925
➡️ Monthly Consistency Score: 0.1901

=== [3420/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.57it/s]
Hypertuning:  99%|█████████▉| 3420/3456 [1:19:13<00:48,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.0839
➡️ Total Profit: ₹29,439.37
➡️ Equity Curve R²: 0.0408
➡️ Monthly Consistency Score: 0.1163

=== [3421/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.51it/s]
Hypertuning:  99%|█████████▉| 3421/3456 [1:19:15<00:47,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.1973
➡️ Total Profit: ₹48,439.49
➡️ Equity Curve R²: 0.4303
➡️ Monthly Consistency Score: 0.1714

=== [3422/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.41it/s]
Hypertuning:  99%|█████████▉| 3422/3456 [1:19:16<00:46,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: 3.5584
➡️ Total Profit: ₹80,401.26
➡️ Equity Curve R²: 0.5097
➡️ Monthly Consistency Score: 0.3484

=== [3423/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.44it/s]
Hypertuning:  99%|█████████▉| 3423/3456 [1:19:17<00:44,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.3947
➡️ Total Profit: ₹69,823.92
➡️ Equity Curve R²: 0.2775
➡️ Monthly Consistency Score: 0.3099

=== [3424/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 10
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.69it/s]
Hypertuning:  99%|█████████▉| 3424/3456 [1:19:19<00:43,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.6808
➡️ Total Profit: ₹47,868.29
➡️ Equity Curve R²: 0.0829
➡️ Monthly Consistency Score: 0.1940

=== [3425/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 127.96it/s]
Hypertuning:  99%|█████████▉| 3425/3456 [1:19:20<00:42,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.4309
➡️ Total Profit: ₹-28,631.42
➡️ Equity Curve R²: 0.8705
➡️ Monthly Consistency Score: -0.1384

=== [3426/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.75it/s]
Hypertuning:  99%|█████████▉| 3426/3456 [1:19:21<00:41,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.1545
➡️ Total Profit: ₹-8,359.79
➡️ Equity Curve R²: 0.7861
➡️ Monthly Consistency Score: -0.0320

=== [3427/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.02it/s]
Hypertuning:  99%|█████████▉| 3427/3456 [1:19:23<00:39,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.3682
➡️ Total Profit: ₹13,404.14
➡️ Equity Curve R²: 0.1011
➡️ Monthly Consistency Score: 0.0487

=== [3428/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.17it/s]
Hypertuning:  99%|█████████▉| 3428/3456 [1:19:24<00:37,  1.33s/it]

➡️ Profit-to-Drawdown Ratio: 1.3320
➡️ Total Profit: ₹43,930.93
➡️ Equity Curve R²: 0.5691
➡️ Monthly Consistency Score: 0.1680

=== [3429/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.51it/s]
Hypertuning:  99%|█████████▉| 3429/3456 [1:19:25<00:36,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.0243
➡️ Total Profit: ₹-743.39
➡️ Equity Curve R²: 0.5041
➡️ Monthly Consistency Score: -0.0029

=== [3430/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 118.72it/s]
Hypertuning:  99%|█████████▉| 3430/3456 [1:19:27<00:35,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.5241
➡️ Total Profit: ₹-30,922.00
➡️ Equity Curve R²: 0.8952
➡️ Monthly Consistency Score: -0.1136

=== [3431/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 109.26it/s]
Hypertuning:  99%|█████████▉| 3431/3456 [1:19:28<00:33,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.1994
➡️ Total Profit: ₹5,571.59
➡️ Equity Curve R²: 0.0015
➡️ Monthly Consistency Score: 0.0206

=== [3432/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 120.29it/s]
Hypertuning:  99%|█████████▉| 3432/3456 [1:19:30<00:32,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.2032
➡️ Total Profit: ₹-4,575.94
➡️ Equity Curve R²: 0.0127
➡️ Monthly Consistency Score: -0.0174

=== [3433/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.19it/s]
Hypertuning:  99%|█████████▉| 3433/3456 [1:19:31<00:31,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.7533
➡️ Total Profit: ₹20,920.21
➡️ Equity Curve R²: 0.0008
➡️ Monthly Consistency Score: 0.0763

=== [3434/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 119.70it/s]
Hypertuning:  99%|█████████▉| 3434/3456 [1:19:32<00:29,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 0.2125
➡️ Total Profit: ₹9,399.77
➡️ Equity Curve R²: 0.3946
➡️ Monthly Consistency Score: 0.0332

=== [3435/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 126.16it/s]
Hypertuning:  99%|█████████▉| 3435/3456 [1:19:34<00:28,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.2286
➡️ Total Profit: ₹47,214.42
➡️ Equity Curve R²: 0.5760
➡️ Monthly Consistency Score: 0.1843

=== [3436/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 129.85it/s]
Hypertuning:  99%|█████████▉| 3436/3456 [1:19:35<00:26,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.0839
➡️ Total Profit: ₹29,439.37
➡️ Equity Curve R²: 0.0408
➡️ Monthly Consistency Score: 0.1163

=== [3437/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 117.49it/s]
Hypertuning:  99%|█████████▉| 3437/3456 [1:19:36<00:26,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 1.7495
➡️ Total Profit: ₹38,570.94
➡️ Equity Curve R²: 0.4382
➡️ Monthly Consistency Score: 0.1378

=== [3438/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 124.62it/s]
Hypertuning:  99%|█████████▉| 3438/3456 [1:19:38<00:24,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.7657
➡️ Total Profit: ₹58,401.25
➡️ Equity Curve R²: 0.0513
➡️ Monthly Consistency Score: 0.2579

=== [3439/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 122.02it/s]
Hypertuning: 100%|█████████▉| 3439/3456 [1:19:39<00:23,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 4.4124
➡️ Total Profit: ₹86,306.66
➡️ Equity Curve R²: 0.7156
➡️ Monthly Consistency Score: 0.3755

=== [3440/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 30
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 125.18it/s]
Hypertuning: 100%|█████████▉| 3440/3456 [1:19:40<00:21,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 1.6808
➡️ Total Profit: ₹47,868.29
➡️ Equity Curve R²: 0.0829
➡️ Monthly Consistency Score: 0.1940

=== [3441/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.32it/s]
Hypertuning: 100%|█████████▉| 3441/3456 [1:19:42<00:20,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.4514
➡️ Total Profit: ₹-27,433.99
➡️ Equity Curve R²: 0.8394
➡️ Monthly Consistency Score: -0.1295

=== [3442/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.95it/s]
Hypertuning: 100%|█████████▉| 3442/3456 [1:19:43<00:19,  1.38s/it]

➡️ Profit-to-Drawdown Ratio: -0.2272
➡️ Total Profit: ₹-11,834.43
➡️ Equity Curve R²: 0.8181
➡️ Monthly Consistency Score: -0.0477

=== [3443/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.99it/s]
Hypertuning: 100%|█████████▉| 3443/3456 [1:19:45<00:17,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.0516
➡️ Total Profit: ₹30,558.13
➡️ Equity Curve R²: 0.1926
➡️ Monthly Consistency Score: 0.1278

=== [3444/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.03
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 111.37it/s]
Hypertuning: 100%|█████████▉| 3444/3456 [1:19:46<00:16,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: 1.2011
➡️ Total Profit: ₹36,162.51
➡️ Equity Curve R²: 0.5162
➡️ Monthly Consistency Score: 0.1444

=== [3445/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.27it/s]
Hypertuning: 100%|█████████▉| 3445/3456 [1:19:47<00:14,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 0.2096
➡️ Total Profit: ₹6,182.38
➡️ Equity Curve R²: 0.3624
➡️ Monthly Consistency Score: 0.0241

=== [3446/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 123.96it/s]
Hypertuning: 100%|█████████▉| 3446/3456 [1:19:49<00:13,  1.34s/it]

➡️ Profit-to-Drawdown Ratio: -0.4692
➡️ Total Profit: ₹-30,496.36
➡️ Equity Curve R²: 0.8782
➡️ Monthly Consistency Score: -0.1226

=== [3447/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 121.61it/s]
Hypertuning: 100%|█████████▉| 3447/3456 [1:19:50<00:12,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: -0.2709
➡️ Total Profit: ₹-10,651.16
➡️ Equity Curve R²: 0.2328
➡️ Monthly Consistency Score: -0.0388

=== [3448/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.05
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 107.40it/s]
Hypertuning: 100%|█████████▉| 3448/3456 [1:19:51<00:10,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.6392
➡️ Total Profit: ₹-23,740.48
➡️ Equity Curve R²: 0.5378
➡️ Monthly Consistency Score: -0.0888

=== [3449/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.89it/s]
Hypertuning: 100%|█████████▉| 3449/3456 [1:19:53<00:09,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: -0.0897
➡️ Total Profit: ₹-4,793.08
➡️ Equity Curve R²: 0.6264
➡️ Monthly Consistency Score: -0.0167

=== [3450/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.70it/s]
Hypertuning: 100%|█████████▉| 3450/3456 [1:19:54<00:08,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: -0.3483
➡️ Total Profit: ₹-22,587.68
➡️ Equity Curve R²: 0.8063
➡️ Monthly Consistency Score: -0.0824

=== [3451/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 111.74it/s]
Hypertuning: 100%|█████████▉| 3451/3456 [1:19:55<00:06,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 1.2724
➡️ Total Profit: ₹26,957.16
➡️ Equity Curve R²: 0.3052
➡️ Monthly Consistency Score: 0.1041

=== [3452/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.07
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 111.07it/s]
Hypertuning: 100%|█████████▉| 3452/3456 [1:19:57<00:05,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 0.3256
➡️ Total Profit: ₹9,314.82
➡️ Equity Curve R²: 0.0844
➡️ Monthly Consistency Score: 0.0363

=== [3453/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.005

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 112.33it/s]
Hypertuning: 100%|█████████▉| 3453/3456 [1:19:58<00:04,  1.37s/it]

➡️ Profit-to-Drawdown Ratio: 2.0349
➡️ Total Profit: ₹44,866.24
➡️ Equity Curve R²: 0.5388
➡️ Monthly Consistency Score: 0.1603

=== [3454/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.01

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 113.10it/s]
Hypertuning: 100%|█████████▉| 3454/3456 [1:20:00<00:02,  1.35s/it]

➡️ Profit-to-Drawdown Ratio: 2.0056
➡️ Total Profit: ₹59,534.01
➡️ Equity Curve R²: 0.1320
➡️ Monthly Consistency Score: 0.2567

=== [3455/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.015

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 114.29it/s]
Hypertuning: 100%|█████████▉| 3455/3456 [1:20:01<00:01,  1.36s/it]

➡️ Profit-to-Drawdown Ratio: 2.7471
➡️ Total Profit: ₹71,638.03
➡️ Equity Curve R²: 0.5058
➡️ Monthly Consistency Score: 0.3000

=== [3456/3456] Testing Parameters ===
smooth_length: 14
norm_period: 90
upper_thresh: 2
lower_thresh: -2.5
rs_period: 14
rs_percentile: 50
tp_pct: 0.1
sl_pct: 0.02

<ipython-input-10-980624002>:85: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  temp_data = temp_data.groupby('Ticker', group_keys=False).apply(apply_strategy)

100%|██████████| 1/1 [00:00<00:00, 115.25it/s]
Hypertuning: 100%|██████████| 3456/3456 [1:20:02<00:00,  1.39s/it]

➡️ Profit-to-Drawdown Ratio: 1.4564
➡️ Total Profit: ₹41,476.47
➡️ Equity Curve R²: 0.0844
➡️ Monthly Consistency Score: 0.1672

✅ Hyperparameter tuning complete. Top 5 results:
      smooth_length  norm_period  upper_thresh  lower_thresh  rs_period  \
2271             10           90          2.00          -2.5         14
2223             10           90          2.00          -2.5         10
1983             10           90          1.75          -2.5         14
2287             10           90          2.00          -2.5         14
1935             10           90          1.75          -2.5         10

      rs_percentile  tp_pct  sl_pct  Profit/Drawdown  Total Profit  Equity R2  \
2271             10     0.1    0.02        10.076177   107292.9628   0.906551
2223             10     0.1    0.02        10.076177   107292.9628   0.906551
1983             10     0.1    0.02        10.076177   107292.9628   0.906551
2287             30     0.1    0.02        10.076177   107292.9628   0.906551
1935             10     0.1    0.02        10.076177   107292.9628   0.906551

      Monthly Consistency  Composite Score
2271             0.571072         5.457816
2223             0.571072         5.457816
1983             0.571072         5.457816
2287             0.571072         5.457816
1935             0.571072         5.457816